### ISSUE TITLE
5.1 HTC Settings.apk - Multiple resources error

### ISSUE THREAD

**Issue by jtothe4n** [iBotPeaches/Apktool#1003]
Used 2.0.1, official release of apktool.
Tried to decompile the HTC One M9 5.1 2.10 based Settings.apk (https://www.dropbox.com/s/nuqgb38uinjhppz/Settings.apk?dl=0) and got the error below.
2.7 based Settings.apk decompiled fine.

```
I: Using Apktool 2.0.1 on Settings.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Multiple resources:
spec=0x7f100000 bool/config_allow_edit_carrier_enabled, config=[DEFAULT]
        at brut.androlib.res.data.ResConfig.addResource(ResConfig.java:63)
        at brut.androlib.res.data.ResConfig.addResource(ResConfig.java:56)
        at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:223)

        at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:191
)
        at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:159)
        at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:11
6)
        at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:78)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibRes
ources.java:538)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.jav
a:63)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.jav
a:55)
        at brut.androlib.Androlib.getResTable(Androlib.java:64)
        at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:209)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:92)
        at brut.apktool.Main.cmdDecode(Main.java:165)
        at brut.apktool.Main.main(Main.java:81)
```

**Comment by iBotPeaches** [comment]
Same type of error as the plagued #644 

I will research it again, now that I have another apk that duplicates this.
