### ISSUE TITLE
brut.androlib.AndrolibException: brut.androlib.AndrolibException: could not exec command:

### ISSUE THREAD

**Issue by alucine** [iBotPeaches/Apktool#1006]
With this application: https://play.google.com/store/apps/details?id=dji.pilot

Command to decode works fine: java -jar apktool_2.0.1.jar d -s DJI-Pilot.apk 

But without changes, commando to build fail with this traces:
```
C:\rober\software\unpack\apktool\DJI-Pilot\res\values\public.xml:522: error: Public symbol drawable/youtube_logo declared here is not defined.
C:\rober\software\unpack\apktool\DJI-Pilot\res\values\public.xml:523: error: Public symbol drawable/youtube_logo_album declared here is not defined.
C:\rober\software\unpack\apktool\DJI-Pilot\res\values\public.xml:1319: error: Public symbol drawable/youtubelivestream_custommode_help declared here is not defined.
brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\Users\rgilcasa\AppData\Local\Temp\brut_util_Jar_2982349530769104937.tmp, p, --f
orced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 19, --version-code, 26, --version-name, @string/versionname, -F, C:\Users\rgilcasa\AppData\Local\Temp\APKTOOL4217292283490686813.tmp
, -0, arsc, -I, C:\Users\rgilcasa\apktool\framework\1.apk, -S, C:\rober\software\unpack\apktool\DJI-Pilot\res, -M, C:\rober\software\unpack\apktool\DJI-Pilot\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:459)
        at brut.androlib.Androlib.buildResources(Androlib.java:397)
        at brut.androlib.Androlib.build(Androlib.java:285)
        at brut.androlib.Androlib.build(Androlib.java:256)
        at brut.apktool.Main.cmdBuild(Main.java:225)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\Users\rgilcasa\AppData\Local\Temp\brut_util_Jar_2982349530769104937.tmp, p, --forced-package-id, 127,
 --min-sdk-version, 16, --target-sdk-version, 19, --version-code, 26, --version-name, @string/versionname, -F, C:\Users\rgilcasa\AppData\Local\Temp\APKTOOL4217292283490686813.tmp, -0, arsc, -I, C:\Use
rs\rgilcasa\apktool\framework\1.apk, -S, C:\rober\software\unpack\apktool\DJI-Pilot\res, -M, C:\rober\software\unpack\apktool\DJI-Pilot\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:445)
        ... 5 more
Caused by: brut.common.BrutException: could not exec command: [C:\Users\rgilcasa\AppData\Local\Temp\brut_util_Jar_2982349530769104937.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-
sdk-version, 19, --version-code, 26, --version-name, @string/versionname, -F, C:\Users\rgilcasa\AppData\Local\Temp\APKTOOL4217292283490686813.tmp, -0, arsc, -I, C:\Users\rgilcasa\apktool\framework\1.a
pk, -S, C:\rober\software\unpack\apktool\DJI-Pilot\res, -M, C:\rober\software\unpack\apktool\DJI-Pilot\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:89)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:413)
        ... 6 more
```

**Comment by iBotPeaches** [comment]
doh.

```
libpng error: Not a PNG file
ERROR: Failure processing PNG image /home/ibotpeaches/Downloads/Apktool/Bug1006/dji.pilot/res/drawable-nodpi-v4/main_bg1.png
libpng error: Not a PNG file
ERROR: Failure processing PNG image /home/ibotpeaches/Downloads/Apktool/Bug1006/dji.pilot/res/drawable-nodpi-v4/main_bg2.png
libpng error: Not a PNG file
ERROR: Failure processing PNG image /home/ibotpeaches/Downloads/Apktool/Bug1006/dji.pilot/res/drawable-nodpi-v4/main_bg3.png
```

Not sure if my computer or images yet.

**Comment by alucine** [comment]
I don't have problem with images, i tested with old version of apktool and the same result, not work build apk, i don't know because fail :(

**Comment by alucine** [comment]
More test.... and the same problem...

>java -jar apktool_2.0.1.jar d -s DJI-Pilot.apk
I: Using Apktool 2.0.1 on DJI-Pilot.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\rgilcasa\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying raw classes.dex file...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

>java -jar apktool_2.0.1.jar b --aapt "c:\Program Files\android-sdk-windows\build-tools\22.0.1\aapt.exe" c:\rober\software\unpack\apktool\DJI-Pilot --output c:\rober\so
ftware\unpack\apktool\crack.apk
I: Using Apktool 2.0.1
I: Checking whether resources has changed...
I: Building resources...
ERROR: Asset package include 'C:\Users\rgilcasa\apktool\framework\1.apk' not found.
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [c:\Program Files\android-sdk-windows\build-tools\22.0.1
\aapt.exe, p, --min-sdk-version, 16, --target-sdk-version, 19, --version-code, 26, --version-name, @string/versionname, -F, C:\Users\rgilcasa\AppData\Local\Temp\APKTOOL5434682649063263436.tmp, -0, ars
c, -I, C:\Users\rgilcasa\apktool\framework\1.apk, -S, c:\rober\software\unpack\apktool\DJI-Pilot\res, -M, c:\rober\software\unpack\apktool\DJI-Pilot\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:459)
        at brut.androlib.Androlib.buildResources(Androlib.java:397)
        at brut.androlib.Androlib.build(Androlib.java:285)
        at brut.androlib.Androlib.build(Androlib.java:256)
        at brut.apktool.Main.cmdBuild(Main.java:225)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [c:\Program Files\android-sdk-windows\build-tools\22.0.1\aapt.exe, p, --min-sdk-version, 16, --target-sdk
-version, 19, --version-code, 26, --version-name, @string/versionname, -F, C:\Users\rgilcasa\AppData\Local\Temp\APKTOOL5434682649063263436.tmp, -0, arsc, -I, C:\Users\rgilcasa\apktool\framework\1.apk,
 -S, c:\rober\software\unpack\apktool\DJI-Pilot\res, -M, c:\rober\software\unpack\apktool\DJI-Pilot\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:445)
        ... 5 more
Caused by: brut.common.BrutException: could not exec command: [c:\Program Files\android-sdk-windows\build-tools\22.0.1\aapt.exe, p, --min-sdk-version, 16, --target-sdk-version, 19, --version-code, 26,
 --version-name, @string/versionname, -F, C:\Users\rgilcasa\AppData\Local\Temp\APKTOOL5434682649063263436.tmp, -0, arsc, -I, C:\Users\rgilcasa\apktool\framework\1.apk, -S, c:\rober\software\unpack\apk
tool\DJI-Pilot\res, -M, c:\rober\software\unpack\apktool\DJI-Pilot\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:89)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:413)
        ... 6 more

This file, C:\Users\rgilcasa\apktool\framework\1.apk, exits and it's generate with previous command.

I don't understand what happened :(...

Any help will be appreciated

**Comment by BurgerZ** [comment]
````
ERROR: Asset package include 'C:\Users\rgilcasa\apktool\framework\1.apk' not found
````
That error is from Android build-tools v21.x.
Use Android SDK Build-tools v20 to build your apk.

**Comment by iBotPeaches** [comment]
Like in my comment here - https://github.com/iBotPeaches/Apktool/issues/1006#issuecomment-124509893

I had 3 bad images. These images were bad in the original apk as well, so nothing that apktool had anything to do with. After opening these images in gimp and saving. They were images again in the sense that `aapt` could process them.

```
ibotpeaches@tombstone:~/Downloads/Apktool/Bug1006$ apktool b dji.pilot
I: Using Apktool 2.0.3-e7c1bc-SNAPSHOT
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
warning: string 've_save_to_HD_close' has no default translation.
warning: string 've_save_to_HD_open' has no default translation.
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
ibotpeaches@tombstone:~/Downloads/Apktool/Bug1006$ 
```

This is outside the scope of apktool. (Fixing bad images), so closing this.

**Comment by dengshiwei** [comment]
I don't understand

**Comment by jack16099** [comment]
open those PNG files inside res/ folder and open each file with notepad. then click file-save as and  select PNG and it'll ask to replace the original file. replace it. Do this to all the PNG files mentioned in the error log. After you do this to all the bad PNG files, it will build.

**Comment by Nidiots** [comment]
install imagemagick https://www.imagemagick.org/script/index.php  and run 
magick  mogrify  *.png
 in problem image folder.
