### ISSUE TITLE
Apk decode working fine but same decoding not getting zipped

### ISSUE THREAD

**Issue by rajdeep74** [iBotPeaches/Apktool#1011]
java -jar apktool.jar d ApkBookmark.apk

its working fine but when i run 

java -jar apktool.jar b ApkBookmark --output ApkBookmark1.apk

then its shows error

I: Using Apktool 2.0.1
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/tmp/brut_util_Jar_3965032287368341236.tmp, p, --forced-package-id, 127, --min-sdk-version, 8, --target-sdk-version, 19, --version-code, 1, --version-name, 1.0, -F, /tmp/APKTOOL4792804545534464608.tmp, -0, arsc, -I, /home/mbtube/apktool/framework/1.apk, -S, /home/mbtube/public_html/apk/ApkBookmark/res, -M, /home/mbtube/public_html/apk/ApkBookmark/AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:459)
        at brut.androlib.Androlib.buildResources(Androlib.java:397)
        at brut.androlib.Androlib.build(Androlib.java:285)
        at brut.androlib.Androlib.build(Androlib.java:256)
        at brut.apktool.Main.cmdBuild(Main.java:225)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/tmp/brut_util_Jar_3965032287368341236.tmp, p, --forced-package-id, 127, --min-sdk-version, 8, --target-sdk-version, 19, --version-code, 1, --version-name, 1.0, -F, /tmp/APKTOOL4792804545534464608.tmp, -0, arsc, -I, /home/mbtube/apktool/framework/1.apk, -S, /home/mbtube/public_html/apk/ApkBookmark/res, -M, /home/mbtube/public_html/apk/ApkBookmark/AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:445)
        ... 5 more
Caused by: brut.common.BrutException: could not exec command: [/tmp/brut_util_Jar_3965032287368341236.tmp, p, --forced-package-id, 127, --min-sdk-version, 8, --target-sdk-version, 19, --version-code, 1, --version-name, 1.0, -F, /tmp/APKTOOL4792804545534464608.tmp, -0, arsc, -I, /home/mbtube/apktool/framework/1.apk, -S, /home/mbtube/public_html/apk/ApkBookmark/res, -M, /home/mbtube/public_html/apk/ApkBookmark/AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:93)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:413)
        ... 6 more
Caused by: java.io.IOException: Cannot run program "/tmp/brut_util_Jar_3965032287368341236.tmp": error=13, Permission denied
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
        at java.lang.Runtime.exec(Runtime.java:617)
        at java.lang.Runtime.exec(Runtime.java:485)
        at brut.util.OS.exec(OS.java:84)
        ... 7 more
Caused by: java.io.IOException: error=13, Permission denied
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:187)
        at java.lang.ProcessImpl.start(ProcessImpl.java:130)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
        ... 10 more

**Comment by iBotPeaches** [comment]
You can't execute binaries from `/tmp`. You can load an additional aapt via `--aapt`. I should add support to drop `aapt` into a different location via parameter since this is becoming common.

**Comment by rajdeep74** [comment]
how can load an additional aapt via --aapt ??
can you give me full command ??

**Comment by rajdeep74** [comment]
i used --aapt and getting this error


java -jar apktool.jar b --aapt ApkBookmark --output ApkBookmark1.apk
I: Using Apktool 2.0.1
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.PathNotExist: apktool.yml
        at brut.androlib.Androlib.readMetaFile(Androlib.java:251)
        at brut.androlib.Androlib.build(Androlib.java:263)
        at brut.androlib.Androlib.build(Androlib.java:256)
        at brut.apktool.Main.cmdBuild(Main.java:225)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.directory.PathNotExist: apktool.yml
        at brut.directory.AbstractDirectory.getFileInput(AbstractDirectory.java:103)
        at brut.androlib.Androlib.readMetaFile(Androlib.java:246)
        ... 4 more

**Comment by rajdeep74** [comment]
any one there ?? , its not working here

**Comment by BurgerZ** [comment]
@rajdeep74 you used this command:
````
java -jar apktool.jar b --aapt ApkBookmark --output ApkBookmark1.apk
````
But you leave the --aapt option empty (ApkBookmark is not the full path to your aapt file).
You should use something like this:
````
java -jar apktool.jar b --aapt /the/full/path/to/aapt ApkBookmark --output ApkBookmark1.apk
````

**Comment by rajdeep74** [comment]
@BurgerZ what do you mean by /the/full/path/to/aapt ?? 
i don't have any aapt application in my server 
anyway i created simple aapt folder and used this command . this aapt is empty

i used this command 

java -jar apktool.jar b --aapt /aapt ApkBookmark --output ApkBookmark1.apk



and i got this error





java -jar apktool.jar b --aapt /aapt ApkBookmark --output ApkBookmark1.apk
I: Using Apktool 2.0.1
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: aapt location could not be found. Defaulting back to default
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/tmp/brut_util_Jar_6544684552699989127.tmp, p, --forced-package-id, 127, --min-sdk-version, 8, --target-sdk-version, 19, --version-code, 1, --version-name, 1.0, -F, /tmp/APKTOOL953529964527395179.tmp, -0, arsc, -I, /home/mbtube/apktool/framework/1.apk, -S, /home/mbtube/public_html/apk/ApkBookmark/res, -M, /home/mbtube/public_html/apk/ApkBookmark/AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:459)
        at brut.androlib.Androlib.buildResources(Androlib.java:397)
        at brut.androlib.Androlib.build(Androlib.java:285)
        at brut.androlib.Androlib.build(Androlib.java:256)
        at brut.apktool.Main.cmdBuild(Main.java:225)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/tmp/brut_util_Jar_6544684552699989127.tmp, p, --forced-package-id, 127, --min-sdk-version, 8, --target-sdk-version, 19, --version-code, 1, --version-name, 1.0, -F, /tmp/APKTOOL953529964527395179.tmp, -0, arsc, -I, /home/mbtube/apktool/framework/1.apk, -S, /home/mbtube/public_html/apk/ApkBookmark/res, -M, /home/mbtube/public_html/apk/ApkBookmark/AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:445)
        ... 5 more
Caused by: brut.common.BrutException: could not exec command: [/tmp/brut_util_Jar_6544684552699989127.tmp, p, --forced-package-id, 127, --min-sdk-version, 8, --target-sdk-version, 19, --version-code, 1, --version-name, 1.0, -F, /tmp/APKTOOL953529964527395179.tmp, -0, arsc, -I, /home/mbtube/apktool/framework/1.apk, -S, /home/mbtube/public_html/apk/ApkBookmark/res, -M, /home/mbtube/public_html/apk/ApkBookmark/AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:93)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:413)
        ... 6 more
Caused by: java.io.IOException: Cannot run program "/tmp/brut_util_Jar_6544684552699989127.tmp": error=13, Permission denied
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
        at java.lang.Runtime.exec(Runtime.java:617)
        at java.lang.Runtime.exec(Runtime.java:485)
        at brut.util.OS.exec(OS.java:84)
        ... 7 more
Caused by: java.io.IOException: error=13, Permission denied
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:187)
        at java.lang.ProcessImpl.start(ProcessImpl.java:130)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
        ... 10 more

**Comment by BurgerZ** [comment]
/the/full/path/to/aapt - is NOT the path to the folder named aapt, this is the full path to aapt FILE. Unpack aapt binary from apktool.jar (prebuilt folder inside jar file) to any location and use this path for --aapt option.
Anyway you need to read help carefully. All you need can be found there.

**Comment by rajdeep74** [comment]
@BurgerZ 
i uploaded aapt file of linux in aapt folder and used this command

java -jar apktool.jar b --aapt /aapt/aapt ApkBookmark --output ApkBookmark1.apk

but still error i am getting 

java -jar apktool.jar b --aapt /aapt/aapt ApkBookmark --output ApkBookmark1.apk
I: Using Apktool 2.0.1
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: aapt location could not be found. Defaulting back to default
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/tmp/brut_util_Jar_6308460060892632736.tmp, p, --forced-package-id, 127, --min-sdk-version, 8, --target-sdk-version, 19, --version-code, 1, --version-name, 1.0, -F, /tmp/APKTOOL4840100077740578488.tmp, -0, arsc, -I, /home/mbtube/apktool/framework/1.apk, -S, /home/mbtube/public_html/apk/ApkBookmark/res, -M, /home/mbtube/public_html/apk/ApkBookmark/AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:459)
        at brut.androlib.Androlib.buildResources(Androlib.java:397)
        at brut.androlib.Androlib.build(Androlib.java:285)
        at brut.androlib.Androlib.build(Androlib.java:256)
        at brut.apktool.Main.cmdBuild(Main.java:225)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/tmp/brut_util_Jar_6308460060892632736.tmp, p, --forced-package-id, 127, --min-sdk-version, 8, --target-sdk-version, 19, --version-code, 1, --version-name, 1.0, -F, /tmp/APKTOOL4840100077740578488.tmp, -0, arsc, -I, /home/mbtube/apktool/framework/1.apk, -S, /home/mbtube/public_html/apk/ApkBookmark/res, -M, /home/mbtube/public_html/apk/ApkBookmark/AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:445)
        ... 5 more
Caused by: brut.common.BrutException: could not exec command: [/tmp/brut_util_Jar_6308460060892632736.tmp, p, --forced-package-id, 127, --min-sdk-version, 8, --target-sdk-version, 19, --version-code, 1, --version-name, 1.0, -F, /tmp/APKTOOL4840100077740578488.tmp, -0, arsc, -I, /home/mbtube/apktool/framework/1.apk, -S, /home/mbtube/public_html/apk/ApkBookmark/res, -M, /home/mbtube/public_html/apk/ApkBookmark/AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:93)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:413)
        ... 6 more
Caused by: java.io.IOException: Cannot run program "/tmp/brut_util_Jar_6308460060892632736.tmp": error=13, Permission denied
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
        at java.lang.Runtime.exec(Runtime.java:617)
        at java.lang.Runtime.exec(Runtime.java:485)
        at brut.util.OS.exec(OS.java:84)
        ... 7 more
Caused by: java.io.IOException: error=13, Permission denied
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:187)
        at java.lang.ProcessImpl.start(ProcessImpl.java:130)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
        ... 10 more

**Comment by BurgerZ** [comment]
````
java -jar apktool.jar b --aapt /aapt/aapt --output ApkBookmark1.apk ApkBookmark 
````

Note that in help:
````
apktool b [options] <app_path>
````
This means that all options go first, the app folder goes as last argument.

**Comment by rajdeep74** [comment]
still showing same error , i think its because /tmp folder is not executable 

@BurgerZ is there any other way ??

**Comment by iBotPeaches** [comment]
Burgerz has helped out a lot more than I would have. This is a bug tracker, not a support forum. Your problem is simple. You can't execute binaries from `/tmp`, which is the default location that the `aapt` binary copies to and loads from.

I will extend / change / adapt the `aapt` parameter to store the internal `aapt` binary in that location (if the file path isn't present) or make a new parameter. 

Either way, this is getting locked. I know what needs to be done, and this has spread too far into support.

**Comment by iBotPeaches** [comment]
Closing in favour of #1017 (A target option when --aapt parameter points to a writable file directory)
