### ISSUE TITLE
public xml error when compile

### ISSUE THREAD

**Issue by trancongmanwin** [iBotPeaches/Apktool#1012]
i can't  compile my apk
```
D:\apktool\gloud1\res\values\public.xml:2157: error: Public symbol string/suppor
t_device declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2210: error: Public symbol string/suppor
t_device_lab declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2209: error: Public symbol string/suppor
t_gamepad_lab declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2211: error: Public symbol string/suppor
t_tips declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:1954: error: Public symbol string/sure_e
xit declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2124: error: Public symbol string/switch
_smooth declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2125: error: Public symbol string/switch
_smooth_1 declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2126: error: Public symbol string/switch
_stand declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2588: error: Public symbol string/switch
_window declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2371: error: Public symbol string/tcp de
clared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2665: error: Public symbol string/teleco
m_card_tips declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2652: error: Public symbol string/teleco
m_lab declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2662: error: Public symbol string/teleco
m_mobile_lab declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2113: error: Public symbol string/test_n
et_tips declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2184: error: Public symbol string/test_r
esult declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2448: error: Public symbol string/testin
g declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2145: error: Public symbol string/text_i
s_null declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2334: error: Public symbol string/time_p
lay declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2414: error: Public symbol string/top_up
_success declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2183: error: Public symbol string/trial_
time_5min declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2182: error: Public symbol string/trial_
time_over declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2276: error: Public symbol string/try_ga
me declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2397: error: Public symbol string/try_le
ft_min declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2204: error: Public symbol string/type d
eclared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2380: error: Public symbol string/type_l
ab declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2372: error: Public symbol string/udp de
clared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2104: error: Public symbol string/un_bin
d declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2438: error: Public symbol string/un_buy
_game declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2439: error: Public symbol string/un_buy
_game_lose_gold declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2422: error: Public symbol string/un_buy
_package declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2423: error: Public symbol string/un_buy
_tips declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2419: error: Public symbol string/un_sta
rt_game declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2351: error: Public symbol string/unbind
 declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2431: error: Public symbol string/unbind
_all declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2353: error: Public symbol string/unbind
_error declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2430: error: Public symbol string/unbind
_mail declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2429: error: Public symbol string/unbind
_phone declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2354: error: Public symbol string/unbind
_success declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2352: error: Public symbol string/unbind
_tips declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2561: error: Public symbol string/unconn
_tip declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2664: error: Public symbol string/unicom
_card_tips declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2651: error: Public symbol string/unicom
_lab declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2661: error: Public symbol string/unicom
_mibile_lab declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2669: error: Public symbol string/unknow
_decode declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2106: error: Public symbol string/unknow
_erro declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2263: error: Public symbol string/unknow
_error declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2053: error: Public symbol string/unkonw
_error declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2073: error: Public symbol string/unkonw
_stop_host declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2526: error: Public symbol string/unpayc
omplete declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2396: error: Public symbol string/unuser
_save declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:1935: error: Public symbol string/update
 declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2406: error: Public symbol string/update
_date declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2110: error: Public symbol string/update
_fail declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2272: error: Public symbol string/update
_fail_from_bind declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2251: error: Public symbol string/update
_fail_to_account declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2097: error: Public symbol string/update
_is_run declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2407: error: Public symbol string/update
_log declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2358: error: Public symbol string/update
_tips declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2109: error: Public symbol string/update
_to declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2180: error: Public symbol string/upleve
l_tips declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2318: error: Public symbol string/upload
_save declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2103: error: Public symbol string/upload
_tips declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2278: error: Public symbol string/upload
er_lab declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2531: error: Public symbol string/use_re
charge_code_btn declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2378: error: Public symbol string/user_c
ard_date declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2365: error: Public symbol string/user_c
oin_tips declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2067: error: Public symbol string/user_e
xit declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2002: error: Public symbol string/user_e
xpired declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2545: error: Public symbol string/user_i
d_lable declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2152: error: Public symbol string/user_l
eve_lab declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2153: error: Public symbol string/user_m
oney_lab declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2390: error: Public symbol string/user_s
ave declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2464: error: Public symbol string/user_s
et declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2208: error: Public symbol string/user_t
icket declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2151: error: Public symbol string/userid
_lab declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:1946: error: Public symbol string/verif
declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2029: error: Public symbol string/verify
_data declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2031: error: Public symbol string/verify
_online declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2024: error: Public symbol string/verify
_parm declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2320: error: Public symbol string/verify
_tips declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2032: error: Public symbol string/verify
_tokey declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2627: error: Public symbol string/vip_ex
pire_tips declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2604: error: Public symbol string/vip_ju
risdication_tips declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2628: error: Public symbol string/vip_no
t_expire_tips declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2606: error: Public symbol string/vip_pr
ice_lab declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2165: error: Public symbol string/vip_pr
ivilege declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2577: error: Public symbol string/vip_wa
it_dialog_content declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2491: error: Public symbol string/vistio
r_tips declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2038: error: Public symbol string/volume
 declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2284: error: Public symbol string/web_ve
rify_100 declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2285: error: Public symbol string/web_ve
rify_101 declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2286: error: Public symbol string/web_ve
rify_102 declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2287: error: Public symbol string/web_ve
rify_103 declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2288: error: Public symbol string/web_ve
rify_104 declared here is not defined.
D:\apktool\gloud1\res\valuException in thread "main" es\public.xml:2289: error:
Public symbol string/web_verify_105 declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2290: error: Public symbol string/web_ve
rify_106 declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2291: error: Public symbol string/web_ve
rify_107 declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2292: error: Public symbol string/web_ve
rify_108 declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2293: error: Public symbol string/web_ve
rify_109 declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2294: error: Public symbol string/web_ve
rify_110 declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2295: error: Public symbol string/web_ve
rify_111 declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2296: error: Public symbol string/web_ve
rify_112 declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2297: error: Public symbol string/web_ve
rify_200 declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2298: error: Public symbol string/web_ve
rify_201 declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2299: error: Public symbol string/web_ve
rify_210 declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2300: error: Public symbol string/web_ve
rify_220 declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2301: error: Public symbol string/web_ve
rify_221 declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2302: error: Public symbol string/web_ve
rify_222 declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2303: error: Public symbol string/web_ve
rify_223 declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2304: error: Public symbol string/web_ve
rify_224 declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2305: error: Public symbol string/web_ve
rify_230 declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2306: error: Public symbol string/web_ve
rify_240 declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2307: error: Public symbol string/web_ve
rify_241 declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2308: error: Public symbol string/web_ve
rify_242 declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2309: error: Public symbol string/web_ve
rify_243 declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2310: error: Public symbol string/web_ve
rify_250 declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2311: error: Public symbol string/web_ve
rify_300 declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2313: error: Public symbol string/web_ve
rify_401 declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2314: error: Public symbol string/web_ve
rify_402 declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2315: error: Public symbol string/web_ve
rify_403 declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2316: error: Public symbol string/web_ve
rify_404 declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2312: error: Public symbol string/web_ve
rify_500 declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2059: error: Public symbol string/web_ve
rify_failed declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2166: error: Public symbol string/welcom
e declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:2626: error: Public symbol string/wx_pay
_tips declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:1975: error: Public symbol string/x_a_ex
it declared here is not defined.
D:\apktool\gloud1\res\values\public.xml:1973: error: Public symbol string/yes de
clared here is not defined.
brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.Br
utException: could not exec command: [C:\Users\BAOPHAT\AppData\Local\Temp\brut_u
til_Jar_4605554859056728413.tmp, p, --forced-package-id, 127, --min-sdk-version,
 14, --target-sdk-version, 19, --version-code, 20150720, --version-name, 1.3.1,
-F, C:\Users\BAOPHAT\AppData\Local\Temp\APKTOOL2311458553390943574.tmp, -0, arsc
, -I, C:\Users\BAOPHAT\apktool\framework\1.apk, -S, D:\apktool\gloud1\res, -M, D
:\apktool\gloud1\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:437)
        at brut.androlib.Androlib.buildResources(Androlib.java:374)
        at brut.androlib.Androlib.build(Androlib.java:277)
        at brut.androlib.Androlib.build(Androlib.java:250)
        at brut.apktool.Main.cmdBuild(Main.java:225)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not
 exec command: [C:\Users\BAOPHAT\AppData\Local\Temp\brut_util_Jar_46055548590567
28413.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-vers
ion, 19, --version-code, 20150720, --version-name, 1.3.1, -F, C:\Users\BAOPHAT\A
ppData\Local\Temp\APKTOOL2311458553390943574.tmp, -0, arsc, -I, C:\Users\BAOPHAT
\apktool\framework\1.apk, -S, D:\apktool\gloud1\res, -M, D:\apktool\gloud1\Andro
idManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.jav
a:488)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:423)
        ... 5 more
Caused by: brut.common.BrutException: could not exec command: [C:\Users\BAOPHAT\
AppData\Local\Temp\brut_util_Jar_4605554859056728413.tmp, p, --forced-package-id
, 127, --min-sdk-version, 14, --target-sdk-version, 19, --version-code, 20150720
, --version-name, 1.3.1, -F, C:\Users\BAOPHAT\AppData\Local\Temp\APKTOOL23114585
53390943574.tmp, -0, arsc, -I, C:\Users\BAOPHAT\apktool\framework\1.apk, -S, D:\
apktool\gloud1\res, -M, D:\apktool\gloud1\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:89)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.jav
a:482)
        ... 6 more
```

**Comment by iBotPeaches** [comment]
Do you have an apk? This seems like a botched package name or something, but can't be sure without an apk.

**Comment by shmshd12** [comment]
Did you decompile any other app too after this app was decompiled? 
For me I had this problem and it was solved by decompiling the app in other name to get framework.apk of the same app and then compiling worked well :) and one I had the issue again and that did not work but the latest version of Apktool worked :)

**Comment by shmshd12** [comment]
Always public.XML is the problem maker xD

**Comment by thedaydreamer** [comment]
Hey @shmshd12 - I am facing similar problem with few apks. Can you please tell what steps you followed to resolve this problem ?

**Comment by andersbl** [comment]
facing the same problem. anybody who resolved it ?

**Comment by iBotPeaches** [comment]
When you have this problem, usually there is an error in the very beginning (that is the real error), then this is the side effect of that error. Since the original poster never included a full stacktrace and/or apk and everyone else here has no stacktraces or apks, I'm going to close this.
