### ISSUE TITLE
Truncated opcodes - Error occurred while disassembling class Landroid.support.v4.app.ListFragment$4;  - skipping class

### ISSUE THREAD

**Issue by JimmyJones97** [iBotPeaches/Apktool#1018]
APK Source: http://www73.zippyshare.com/v/N1W88gtl/file.html

Having a issue with a apk i was sent, seems methods were injected with rather long names and invalid opcodes at the end.

```sh
Error occurred while disassembling class Landroid.support.v4.app.ListFragment$4;
 - skipping class
Error while processing method Landroid/support/v4/app/ListFragment$3;->LiRrrXzro
MO1QDDYCVZYHQLYeEn4j9fqzQQXktc5c9MVHTw50IXVQHeu1YDffJOFt6ktCL5LYQrEEzmLpIjQhSKyQ
l9cgSDwsfkgcNhMxyso7fpBuDyEjGWRyP75GGHhebCzGIQ9kmAu1G16Rd02vTYqaoMy8AVJ3CIcB7zmz
iJEKr7W7NWi()Ljava/lang/String;

org.jf.util.ExceptionWithContext: The last instruction in the method is truncate
d
        at org.jf.dexlib2.dexbacked.DexBackedMethodImplementation$1$1.readNextIt
em(DexBackedMethodImplementation.java:87)
        at org.jf.dexlib2.dexbacked.DexBackedMethodImplementation$1$1.readNextIt
em(DexBackedMethodImplementation.java:75)
        at org.jf.dexlib2.dexbacked.util.VariableSizeLookaheadIterator.computeNe
xt(VariableSizeLookaheadIterator.java:60)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractI
terator.java:143)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.j
ava:138)
        at com.google.common.collect.ImmutableCollection$Builder.addAll(Immutabl
eCollection.java:300)
        at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.
java:691)
        at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:275
)
        at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:226
)
        at org.jf.baksmali.Adaptors.MethodDefinition.<init>(MethodDefinition.jav
a:92)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeVirtualMethods(ClassDef
inition.java:327)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java
:113)
        at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:226)
        at org.jf.baksmali.baksmali.access$000(baksmali.java:56)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:150)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:148)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Error while processing method Landroid/support/v4/app/FragmentTransitionCompat21
$5;->9YsG8REijY36ogSdQq4uMjCovRdvPEpxWTze8jJHxwWzAsgyFjxZwU9eHCooZwCFxyA7xeD7Blr
atbhHy6eW3uoDZg68IB3X0L39py9Q162ptnVlpjxB8GuFMnx1pP9yuz98dGtGNQoqUOtgQ7BiqbKgGgm
GQL5w5H7Y7X2q203XeVcMRVQG()Ljava/lang/String;
```

**Comment by iBotPeaches** [comment]
I would fire this at https://github.com/JesusFreke/smali as the issue appears to be isolated to the smali project.

**Comment by iBotPeaches** [comment]
I unfortunately [lost](https://plus.google.com/+ConnorTumbleson/posts/ZHQvksFo81K) this APK when I lost my HDD a few weeks ago. I updated smali to upstream `2.1.0` and I *think* this was fixed there, but I have no way to check. 

We can re-open this if the problem still exists. I just don't have the APK to confirm.
