### ISSUE TITLE
Bug in miui7 decompilation MiuiHome.apk

### ISSUE THREAD

**Issue by miuifrance** [iBotPeaches/Apktool#1021]
Impossible to decompile miui7 MiuiHome.apk :

```
I: Using Apktool 2.0.1 on MiuiHome.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Multiple resources: spec=0x7f02007c drawable/icon_notification_bg, config=-sw720dp-xhdpi-v13
    at brut.androlib.res.data.ResConfig.addResource(ResConfig.java:63)
    at brut.androlib.res.data.ResConfig.addResource(ResConfig.java:56)
    at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:223)
    at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:191)
    at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:159)
    at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:116)
    at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:78)
    at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
    at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:538)
    at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:63)
    at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:55)
    at brut.androlib.Androlib.getResTable(Androlib.java:64)
    at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:209)
    at brut.androlib.ApkDecoder.decode(ApkDecoder.java:92)
    at brut.apktool.Main.cmdDecode(Main.java:165)
    at brut.apktool.Main.main(Main.java:81)
```

**Comment by iBotPeaches** [comment]
Introduction of another stupid qualifier "godzillaui" with value of `0x0b`. In addition to having 4 digit mnc/mcc values.

Will need an aapt patch in addition to changes at apktool level.

**Comment by BurgerZ** [comment]
I can make a pull request with the code for aapt.

**Comment by iBotPeaches** [comment]
```
ibotpeaches@raganok:~/Downloads/Apktool/MIUI7/miui7$ apktool d MiuiHome.apk -t miui -f
I: Using Apktool 2.0.2-421999-SNAPSHOT on MiuiHome.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/apktool/framework/1-miui.apk
I: Loading resource table from file: /home/ibotpeaches/apktool/framework/16-miui.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
```

```
ibotpeaches@raganok:~/Downloads/Apktool/MIUI7/miui7$ apktool b MiuiHome
I: Using Apktool 2.0.2-421999-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Building apk file...
```

**Comment by miuifrance** [comment]
Thank you :)
just waiting for new apktool

**Comment by dnomikos** [comment]
Worked! Thank you all :)

**Comment by akhirasip** [comment]
good job,...thanks a lot,...God bless you brother,....it's worked,....
