### ISSUE TITLE
Impossible to decompile miui7 Weather.apk

### ISSUE THREAD

**Issue by miuifrance** [iBotPeaches/Apktool#1022]
Impossible to decompile MIUI7 Weather.apk

I: Using Apktool 2.0.1 on Weather.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Multiple resources: spec=0x7f06002c dimen/view_index_item_title_size, config=-sw600dp-v13
    at brut.androlib.res.data.ResConfig.addResource(ResConfig.java:63)
    at brut.androlib.res.data.ResConfig.addResource(ResConfig.java:56)
    at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:223)
    at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:191)
    at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:159)
    at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:116)
    at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:78)
    at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
    at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:538)
    at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:63)
    at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:55)
    at brut.androlib.Androlib.getResTable(Androlib.java:64)
    at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:209)
    at brut.androlib.ApkDecoder.decode(ApkDecoder.java:92)
    at brut.apktool.Main.cmdDecode(Main.java:165)
    at brut.apktool.Main.main(Main.java:81)

**Comment by iBotPeaches** [comment]
We can keep one MIUI7 bug report open. #1021
