### ISSUE TITLE
Couldn't recompile framework-res.apk for Samsung Galaxy S6 android 5.0.2

### ISSUE THREAD

**Issue by kaneawk** [iBotPeaches/Apktool#1026]
When recompile the framework-res,Apktool leave a error:

D:\Tools\smali>java -jar apktool-2.0.2-dirty-small.jar b framework-res
I: Using Apktool 2.0.2-dirty
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
D:\Tools\smali\framework-res\res\drawable-sw360dp-xxxhdpi-v13\ic_knox_badge.PNG:
 error: File is case-insensitive equivalent to: D:\Tools\smali\framework-res\res
\drawable-xxxhdpi-v4\ic_knox_badge.png
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.Androl
ibException: brut.common.BrutException: could not exec command: [C:\Users\Kane\A
ppData\Local\Temp\brut_util_Jar_4946276495833273641.tmp, p, --forced-package-id,
 1, --min-sdk-version, 21, --target-sdk-version, 21, --version-code, 21, --versi
on-name, 5.0.2-SC05GOMU1AOE1, -F, C:\Users\Kane\AppData\Local\Temp\APKTOOL869204
1025033582714.tmp, -x, -0, arsc, -S, D:\Tools\smali\framework-res\res, -M, D:\To
ols\smali\framework-res\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:465)
        at brut.androlib.Androlib.buildResources(Androlib.java:403)
        at brut.androlib.Androlib.build(Androlib.java:291)
        at brut.androlib.Androlib.build(Androlib.java:261)
        at brut.apktool.Main.cmdBuild(Main.java:225)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not
 exec command: [C:\Users\Kane\AppData\Local\Temp\brut_util_Jar_49462764958332736
41.tmp, p, --forced-package-id, 1, --min-sdk-version, 21, --target-sdk-version,
21, --version-code, 21, --version-name, 5.0.2-SC05GOMU1AOE1, -F, C:\Users\Kane\A
ppData\Local\Temp\APKTOOL8692041025033582714.tmp, -x, -0, arsc, -S, D:\Tools\sma
li\framework-res\res, -M, D:\Tools\smali\framework-res\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.jav
a:425)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:451)
        ... 5 more
Caused by: brut.common.BrutException: could not exec command: [C:\Users\Kane\App
Data\Local\Temp\brut_util_Jar_4946276495833273641.tmp, p, --forced-package-id, 1
, --min-sdk-version, 21, --target-sdk-version, 21, --version-code, 21, --version
-name, 5.0.2-SC05GOMU1AOE1, -F, C:\Users\Kane\AppData\Local\Temp\APKTOOL86920410
25033582714.tmp, -x, -0, arsc, -S, D:\Tools\smali\framework-res\res, -M, D:\Tool
s\smali\framework-res\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:89)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.jav
a:419)
        ... 6 more

framework-res.apk:
https://mega.nz/#!itAiGTAa!g3vAzBiP653v5fLxorQivN6oI5bHdxSmB3JrrjOQsMk

Apktool should be replaced PNG to png or let Apktool don't case sensitive...-_-||

**Comment by iBotPeaches** [comment]
```
D:\Tools\smali\framework-res\res\drawable-sw360dp-xxxhdpi-v13\ic_knox_badge.PNG:
error: File is case-insensitive equivalent to: D:\Tools\smali\framework-res\res
\drawable-xxxhdpi-v4\ic_knox_badge.png
```

This was just a bad built application, that a newer more restrictive aapt caught. Not really apktool's fault.
