### ISSUE TITLE
No resource identifier found for attribute 'touchscreenBlocksFocus' in package 'android'

### ISSUE THREAD

**Issue by leenjewel** [iBotPeaches/Apktool#1033]
First，I decode my apk successfull

```
java -jar apktool.jar -f -o out d MySDKAPPExample.apk
```

And then I try to rebuild it

```
 java -jar apktool.jar b out
```

The error and rebuild log

```
I: Using Apktool 2.0.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
/Users/leenjewel/Tmp/test/apktool/out/res/layout-v21/abc_screen_toolbar.xml:5: error: No resource identifier found for attribute 'touchscreenBlocksFocus' in package 'android'

Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/var/folders/h6/52x2jg8975sg2pr7y0p24x5r0000gn/T/brut_util_Jar_3946747843061666395.tmp, p, --forced-package-id, 127, --min-sdk-version, 8, --target-sdk-version, 21, --version-code, 1, --version-name, 1.0, -F, /var/folders/h6/52x2jg8975sg2pr7y0p24x5r0000gn/T/APKTOOL1290025347067455141.tmp, -0, arsc, -I, /Users/leenjewel/Library/apktool/framework/1.apk, -S, /Users/leenjewel/Tmp/test/apktool/out/res, -M, /Users/leenjewel/Tmp/test/apktool/out/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:459)
	at brut.androlib.Androlib.buildResources(Androlib.java:397)
	at brut.androlib.Androlib.build(Androlib.java:285)
	at brut.androlib.Androlib.build(Androlib.java:256)
	at brut.apktool.Main.cmdBuild(Main.java:225)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/var/folders/h6/52x2jg8975sg2pr7y0p24x5r0000gn/T/brut_util_Jar_3946747843061666395.tmp, p, --forced-package-id, 127, --min-sdk-version, 8, --target-sdk-version, 21, --version-code, 1, --version-name, 1.0, -F, /var/folders/h6/52x2jg8975sg2pr7y0p24x5r0000gn/T/APKTOOL1290025347067455141.tmp, -0, arsc, -I, /Users/leenjewel/Library/apktool/framework/1.apk, -S, /Users/leenjewel/Tmp/test/apktool/out/res, -M, /Users/leenjewel/Tmp/test/apktool/out/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:445)
	... 5 more
Caused by: brut.common.BrutException: could not exec command: [/var/folders/h6/52x2jg8975sg2pr7y0p24x5r0000gn/T/brut_util_Jar_3946747843061666395.tmp, p, --forced-package-id, 127, --min-sdk-version, 8, --target-sdk-version, 21, --version-code, 1, --version-name, 1.0, -F, /var/folders/h6/52x2jg8975sg2pr7y0p24x5r0000gn/T/APKTOOL1290025347067455141.tmp, -0, arsc, -I, /Users/leenjewel/Library/apktool/framework/1.apk, -S, /Users/leenjewel/Tmp/test/apktool/out/res, -M, /Users/leenjewel/Tmp/test/apktool/out/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:89)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:413)
	... 6 more
```

By the way, my apk build with `appcompat-v7 Library Project`

And res/layout-v21/abc_screen_toolbar.xml:

```xml
<?xml version="1.0" encoding="utf-8"?>
<android.support.v7.internal.widget.ActionBarOverlayLayout android:id="@id/decor_content_parent" android:fitsSystemWindows="true" android:layout_width="fill_parent" android:layout_height="fill_parent"
  xmlns:android="http://schemas.android.com/apk/res/android" xmlns:app="http://schemas.android.com/apk/res-auto">
    <include layout="@layout/abc_screen_content_include" />
    <android.support.v7.internal.widget.ActionBarContainer android:gravity="top" android:id="@id/action_bar_container" android:layout_width="fill_parent" android:layout_height="wrap_content" android:layout_alignParentTop="true" android:touchscreenBlocksFocus="true" style="?attr/actionBarStyle">
        <android.support.v7.widget.Toolbar android:id="@id/action_bar" android:layout_width="fill_parent" android:layout_height="wrap_content" app:navigationContentDescription="@string/abc_action_bar_up_description" style="?attr/toolbarStyle" />
        <android.support.v7.internal.widget.ActionBarContextView android:theme="?actionBarTheme" android:id="@id/action_context_bar" android:visibility="gone" android:layout_width="fill_parent" android:layout_height="wrap_content" style="?attr/actionModeStyle" />
    </android.support.v7.internal.widget.ActionBarContainer>
</android.support.v7.internal.widget.ActionBarOverlayLayout>
```

**Comment by iBotPeaches** [comment]
Doesn't look like Apktool is at fault: https://code.google.com/p/android/issues/detail?id=159688

**Comment by leenjewel** [comment]
Thanks！

I rebuild my apk without `appcompat-v7 library project` and retry to decode and rebuild it by apptool, It work well.

**Comment by otacon507** [comment]
I'm having a similar issue : 

```
C:\Program Files (x86)\apktool>apktool b plw -o plw.apk
I: Using Apktool 2.2.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: C:\Program Files (x86)\apktool\plw\AndroidManifest.xml:25: error: No resour
ce identifier found for attribute 'resizeableActivity' in package 'android'
W:
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.Androl
ibException: brut.common.BrutException: could not exec (exit code = 1): [C:\User
s\Snap\AppData\Local\Temp\brut_util_Jar_4168724031890796899.tmp, p, --forced-pa
ckage-id, 127, --min-sdk-version, 15, --target-sdk-version, 24, --version-code,
3102, --version-name, 3.2.34, -F, C:\Users\Snap\AppData\Local\Temp\APKTOOL69021
36759987987265.tmp, -0, arsc, -0, arsc, -I, C:\Users\Snap\AppData\Local\apktool
\framework\1.apk, -S, C:\Program Files (x86)\apktool\plw\res, -M, C:\Program F
iles (x86)\apktool\plw\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:473)
        at brut.androlib.Androlib.buildResources(Androlib.java:407)
        at brut.androlib.Androlib.build(Androlib.java:306)
        at brut.androlib.Androlib.build(Androlib.java:263)
        at brut.apktool.Main.cmdBuild(Main.java:224)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not
 exec (exit code = 1): [C:\Users\Snap\AppData\Local\Temp\brut_util_Jar_41687240
31890796899.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sd
k-version, 24, --version-code, 3102, --version-name, 3.2.34, -F, C:\Users\Snap\
AppData\Local\Temp\APKTOOL6902136759987987265.tmp, -0, arsc, -0, arsc, -I, C:\Us
ers\Snap\AppData\Local\apktool\framework\1.apk, -S, C:\Program Files (x86)\apkt
ool\plw\res, -M, C:\Program Files (x86)\apktool\plw\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.jav
a:439)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:459)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\
Snap\AppData\Local\Temp\brut_util_Jar_4168724031890796899.tmp, p, --forced-pack
age-id, 127, --min-sdk-version, 15, --target-sdk-version, 24, --version-code, 31
02, --version-name, 3.2.34, -F, C:\Users\Snap\AppData\Local\Temp\APKTOOL6902136
759987987265.tmp, -0, arsc, -0, arsc, -I, C:\Users\Snap\AppData\Local\apktool\f
ramework\1.apk, -S, C:\Program Files (x86)\apktool\plw\res, -M, C:\Program Fil
es (x86)\apktool\plw\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.jav
a:433)
        ... 6 more

```

By the same issue above, I am assuming that I need to comment out that resource directive in the manifest? Thank you

**Comment by iBotPeaches** [comment]
@otacon507 https://developer.android.com/preview/features/multi-window.html

That resource is from Android N. This will be supported once we get an official Android N source drop which contains the framework file.

**Comment by ohmerhe** [comment]
I got the same issue, when just decode and rebuild apk:

W: /Users/ohmer/Projects/pascal/dex/build/com.hujiang.aioral.demo/src/res/drawable-v21/abc_ratingbar_indicator_material.xml:7: error: No resource identifier found for attribute 'tileModeX' in package 'android'
W:
W: /Users/ohmer/Projects/pascal/dex/build/com.hujiang.aioral.demo/src/res/drawable-v21/abc_ratingbar_small_material.xml:7: error: No resource identifier found for attribute 'tileModeX' in package 'android'
W:
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/xs/8s3xsqmd1v18gg_17k540jdm0000gn/T/brut_util_Jar_4589128497693274318.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 23, --version-code, 1, --version-name, 1.0.0, -F, /var/folders/xs/8s3xsqmd1v18gg_17k540jdm0000gn/T/APKTOOL8373984771673948624.tmp, -0, arsc, -0, arsc, -I, /Users/ohmer/Library/apktool/framework/1.apk, -S, /Users/ohmer/Projects/pascal/dex/build/com.hujiang.aioral.demo/src/res, -M, /Users/ohmer/Projects/pascal/dex/build/com.hujiang.aioral.demo/src/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:478)
	at brut.androlib.Androlib.buildResources(Androlib.java:412)
	at brut.androlib.Androlib.build(Androlib.java:311)
	at brut.androlib.Androlib.build(Androlib.java:264)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/xs/8s3xsqmd1v18gg_17k540jdm0000gn/T/brut_util_Jar_4589128497693274318.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 23, --version-code, 1, --version-name, 1.0.0, -F, /var/folders/xs/8s3xsqmd1v18gg_17k540jdm0000gn/T/APKTOOL8373984771673948624.tmp, -0, arsc, -0, arsc, -I, /Users/ohmer/Library/apktool/framework/1.apk, -S, /Users/ohmer/Projects/pascal/dex/build/com.hujiang.aioral.demo/src/res, -M, /Users/ohmer/Projects/pascal/dex/build/com.hujiang.aioral.demo/src/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:439)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:464)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/xs/8s3xsqmd1v18gg_17k540jdm0000gn/T/brut_util_Jar_4589128497693274318.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 23, --version-code, 1, --version-name, 1.0.0, -F, /var/folders/xs/8s3xsqmd1v18gg_17k540jdm0000gn/T/APKTOOL8373984771673948624.tmp, -0, arsc, -0, arsc, -I, /Users/ohmer/Library/apktool/framework/1.apk, -S, /Users/ohmer/Projects/pascal/dex/build/com.hujiang.aioral.demo/src/res, -M, /Users/ohmer/Projects/pascal/dex/build/com.hujiang.aioral.demo/src/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:433)
	... 6 more

**Comment by ohmerhe** [comment]
why i can not use support v7, i need it.
How can i solve this question.
