### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by shanmugapriyad** [iBotPeaches/Apktool#1042]
```
I: Copying raw classes.dex file...
I: Loading resource table...
I: Error - exception thrown from apktool
brut.androlib.AndrolibException: Could not decode arsc file
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:56)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:491)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:74)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:66)
	at brut.androlib.Androlib.getResTable(Androlib.java:50)
	at brut.androlib.ApkDecoder.getResTable(ApkDecoder.java:189)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:114)
	at brut.apktool.Main.cmdDecode(Main.java:146)
	at brut.apktool.Main.main(Main.java:77)
	at com.citrix.MAM.Android.ManagedAppUtility.f.a(Unknown Source)
	at com.citrix.MAM.Android.a.i.a(Unknown Source)
	at com.citrix.MAM.Android.a.b.a(Unknown Source)
	at com.citrix.MAM.Android.ManagedAppUtility.AppMain.main(Unknown Source)
Caused by: java.io.IOException: Expected: 0x001c0001, got: 0x00000000
	at brut.util.ExtDataInput.skipCheckInt(ExtDataInput.java:48)
	at brut.androlib.res.decoder.StringBlock.read(StringBlock.java:44)
	at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:102)
	at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:83)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:49)
	... 12 more
```

**Comment by iBotPeaches** [comment]
Based on this stacktrace, apktool is packaged within an application. For this reason, I have no idea what version of apktool is being used or if any changes were made to the source.

For this reason, I'm closing this report. You are welcome to report a bug using just apktool directly on CLI, and uploading an APK for me to investigate with.
