### ISSUE TITLE
Decompile Error

### ISSUE THREAD

**Issue by chas3366** [iBotPeaches/Apktool#1045]
I am receiving this error when trying to decompile Settings.apk from the latest HTC M9 update
2.11.651.19 CL591203 release-keys:

```
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Multiple resources: spec=0x7f100000 bool/config_allow_edit_
carrier_enabled, config=[DEFAULT]
at brut.androlib.res.data.ResConfig.addResource(ResCo nfig.java:63)
at brut.androlib.res.data.ResConfig.addResource(ResCo nfig.java:56)
at brut.androlib.res.decoder.ARSCDecoder.readEntry(AR SCDecoder.java:223)
at brut.androlib.res.decoder.ARSCDecoder.readConfig(A RSCDecoder.java:191)
at brut.androlib.res.decoder.ARSCDecoder.readType(ARS CDecoder.java:159)
at brut.androlib.res.decoder.ARSCDecoder.readPackage( ARSCDecoder.java:116)
at brut.androlib.res.decoder.ARSCDecoder.readTable(AR SCDecoder.java:78)
at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCD ecoder.java:47)
at brut.androlib.res.AndrolibResources.getResPackages FromApk(AndrolibResources.java:544)
at brut.androlib.res.AndrolibResources.loadMainPkg(An drolibResources.java:63)
at brut.androlib.res.AndrolibResources.getResTable(An drolibResources.java:55)
at brut.androlib.Androlib.getResTable(Androlib.java:6 5)
at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDe coder.java:197)
at brut.androlib.ApkDecoder.decode(ApkDecoder.java:96 )
at brut.apktool.Main.cmdDecode(Main.java:165)
at brut.apktool.Main.main(Main.java:81)
```

I have tried 2.0, 2.0.1 and a fresh build from the repository.

Settings.apk: https://www.dropbox.com/s/hkzm829v0x7c8ua/Settings.apk?dl=0

Any help would be appreciated

**Comment by iBotPeaches** [comment]
Same underlying problem as #644 and that has been a bug for almost 2 years. So not sure if I will figure out what HTC is doing.
