### ISSUE TITLE
Problem with building app without changes

### ISSUE THREAD

**Issue by vitya007** [iBotPeaches/Apktool#1048]
D:\AndroidTest>java -jar apktool.jar d apps/Poweramp.apk
I: Using Apktool 2.0.1 on Poweramp.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Vitek\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

D:\AndroidTest>java -jar apktool.jar b Poweramp
I: Using Apktool 2.0.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
D:\AndroidTest\Poweramp\res\drawable-hdpi-v4\matte_ab_back.PNG: error: File is c
ase-insensitive equivalent to: D:\AndroidTest\Poweramp\res\drawable-xxhdpi-v4\ma
tte_ab_back.png
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.Androl
ibException: brut.common.BrutException: could not exec command: [C:\Windows\TEMP
\brut_util_Jar_6636500249392231205.tmp, p, --forced-package-id, 127, --min-sdk-v
ersion, 9, --target-sdk-version, 21, --version-code, 581, --version-name, 2.0.10
-build-581-uni, -F, C:\Windows\TEMP\APKTOOL4396478699890231710.tmp, -I, C:\Users
\Vitek\apktool\framework\1.apk, -S, D:\AndroidTest\Poweramp\res, -M, D:\AndroidT
est\Poweramp\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:459)
        at brut.androlib.Androlib.buildResources(Androlib.java:397)
        at brut.androlib.Androlib.build(Androlib.java:285)
        at brut.androlib.Androlib.build(Androlib.java:256)
        at brut.apktool.Main.cmdBuild(Main.java:225)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not
 exec command: [C:\Windows\TEMP\brut_util_Jar_6636500249392231205.tmp, p, --forc
ed-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 21, --version-co
de, 581, --version-name, 2.0.10-build-581-uni, -F, C:\Windows\TEMP\APKTOOL439647
8699890231710.tmp, -I, C:\Users\Vitek\apktool\framework\1.apk, -S, D:\AndroidTes
t\Poweramp\res, -M, D:\AndroidTest\Poweramp\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.jav
a:419)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:445)
        ... 5 more
Caused by: brut.common.BrutException: could not exec command: [C:\Windows\TEMP\b
rut_util_Jar_6636500249392231205.tmp, p, --forced-package-id, 127, --min-sdk-ver
sion, 9, --target-sdk-version, 21, --version-code, 581, --version-name, 2.0.10-b
uild-581-uni, -F, C:\Windows\TEMP\APKTOOL4396478699890231710.tmp, -I, C:\Users\V
itek\apktool\framework\1.apk, -S, D:\AndroidTest\Poweramp\res, -M, D:\AndroidTes
t\Poweramp\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:89)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.jav
a:413)
        ... 6 more

D:\AndroidTest>

**Comment by iBotPeaches** [comment]
```
D:\AndroidTest\Poweramp\res\drawable-hdpi-v4\matte_ab_back.PNG: error: File is c
ase-insensitive equivalent to: D:\AndroidTest\Poweramp\res\drawable-xxhdpi-v4\ma
tte_ab_back.png
```

If you fix that, the problem should go away.
