### ISSUE TITLE
xiaomi Mi4c  Android 5.1.1 decompile ok, but back to compile error

### ISSUE THREAD

**Issue by Fays** [iBotPeaches/Apktool#1049]
miui.apk
```
I: Using Apktool 2.0.2-0abaab-SNAPSHOT on miui.apk
I: Loading resource table...
I: Decoding Shared Library (androidhwext), pkgId: 15
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/fays/apktool/framework/1-MI4c.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
```

miui.apk
```
I: Using Apktool 2.0.2-0abaab-SNAPSHOT
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
/home/fays/tradMI4c/workdir/decoded/app/miui/miui.apk/res/layout/action_bar_expanded_menu_layout.xml:2: error: Error: No resource found that matches the given name (at 'id' with value '@id/expanded_menu').
/home/fays/tradMI4c/workdir/decoded/app/miui/miui.apk/res/layout/action_bar_home.xml:4: error: Error: No resource found that matches the given name (at 'id' with value '@id/up').
/home/fays/tradMI4c/workdir/decoded/app/miui/miui.apk/res/color/tertiary_text_light.xml:5: error: Error: No resource found that matches the given name (at 'color' with value '@color/pressed_text_light').
/home/fays/tradMI4c/workdir/decoded/app/miui/miui.apk/res/color/tertiary_text_light.xml:6: error: Error: No resource found that matches the given name (at 'color' with value '@color/selected_text_light').
/home/fays/tradMI4c/workdir/decoded/app/miui/miui.apk/res/color/tertiary_text_light.xml:7: error: Error: No resource found that matches the given name (at 'color' with value '@color/activated_text_light').
/home/fays/tradMI4c/workdir/decoded/app/miui/miui.apk/res/color/tertiary_text_light.xml:8: error: Error: No resource found that matches the given name (at 'color' with value '@color/dim_foreground_light').
xception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/tmp/brut_util_Jar_2109900971554145322.tmp, p, --forced-package-id, 16, --min-sdk-version, 16, --target-sdk-version, 19, --rename-manifest-package, com.miui.core, --version-code, 1020000, --version-name, 1.2.0.0, -F, /tmp/APKTOOL8466618352399775316.tmp, -x, -0, resources.arsc, -0, arsc, -I, /home/fays/apktool/framework/1-MI4c.apk, -S, /home/fays/tradMI4c/workdir/decoded/app/miui/miui.apk/res, -M, /home/fays/tradMI4c/workdir/decoded/app/miui/miui.apk/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:465)
	at brut.androlib.Androlib.buildResources(Androlib.java:403)
	at brut.androlib.Androlib.build(Androlib.java:291)
	at brut.androlib.Androlib.build(Androlib.java:261)
	at brut.apktool.Main.cmdBuild(Main.java:225)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/tmp/brut_util_Jar_2109900971554145322.tmp, p, --forced-package-id, 16, --min-sdk-version, 16, --target-sdk-version, 19, --rename-manifest-package, com.miui.core, --version-code, 1020000, --version-name, 1.2.0.0, -F, /tmp/APKTOOL8466618352399775316.tmp, -x, -0, resources.arsc, -0, arsc, -I, /home/fays/apktool/framework/1-MI4c.apk, -S, /home/fays/tradMI4c/workdir/decoded/app/miui/miui.apk/res, -M, /home/fays/tradMI4c/workdir/decoded/app/miui/miui.apk/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:425)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:451)
	... 5 more
Caused by: brut.common.BrutException: could not exec command: [/tmp/brut_util_Jar_2109900971554145322.tmp, p, --forced-package-id, 16, --min-sdk-version, 16, --target-sdk-version, 19, --rename-manifest-package, com.miui.core, --version-code, 1020000, --version-name, 1.2.0.0, -F, /tmp/APKTOOL8466618352399775316.tmp, -x, -0, resources.arsc, -0, arsc, -I, /home/fays/apktool/framework/1-MI4c.apk, -S, /home/fays/tradMI4c/workdir/decoded/app/miui/miui.apk/res, -M, /home/fays/tradMI4c/workdir/decoded/app/miui/miui.apk/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:89)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)
	... 6 more
```

**Comment by iBotPeaches** [comment]
I'm very close to dropping support on MIUI entirely. The constant out of the norm changes to AOSP in order to change qualifiers and AOSP build systems blows my mind. This is more and more difficult to support without breaking Apktool.

I have only supported MIUI thus far because I used to have a personal hobby project with MIUI and their roms. That has changed and thus at any time I can remove these hacky fixes that already exist in the Apktool codebase.

This might anger/upset a ton of people, because I know a great deal of you utilize Apktool for MIUI. So, please attach all MIUI frameworks and this `miui.apk` file, which actually looks like a framework. I can't promise anything, but meet me halfway with the files I need and I'll take a look.

**Comment by iBotPeaches** [comment]
Closing in favour of #806 - All MIUI bugs in one place.
