### ISSUE TITLE
Exception in thread "main"

### ISSUE THREAD

**Issue by bmatichuk** [iBotPeaches/Apktool#1050]
Using Samsung s3
extracted SystemUI.apk

ran the following:

 apktool d SystemUI.apk

bmatichuk$ apktool d SystemUI.apk
I: Using Apktool 2.0.1 on SystemUI.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/bmatichuk/Library/apktool/framework/1.apk
W: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x0104071e
I: Regular manifest package...
I: Decoding file-resources...
W: Could not decode attr value, using undecoded value instead: ns=android, name=drawable, value=0x01081052
W: Could not decode attr value, using undecoded value instead: ns=android, name=drawable, value=0x0108081c
W: Could not decode attr value, using undecoded value instead: ns=android, name=drawable, value=0x01081053
W: Could not decode attr value, using undecoded value instead: ns=android, name=drawable, value=0x01080a90
W: Could not decode attr value, using undecoded value instead: ns=android, name=drawable, value=0x01081052
I: Decoding values */* XMLs...
Exception in thread "main" brut.androlib.err.UndefinedResObject: resource spec: 0x0104084e
	at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:65)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:61)
	at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferenceValue.java:57)
	at brut.androlib.res.data.value.ResReferenceValue.encodeAsResXml(ResReferenceValue.java:47)
	at brut.androlib.res.data.value.ResScalarValue.encodeAsResXmlValue(ResScalarValue.java:58)
	at brut.androlib.res.data.value.ResScalarValue.encodeAsResXmlNonEscapedItemValue(ResScalarValue.java:62)
	at brut.androlib.res.data.value.ResArrayValue.serializeToResValuesXml(ResArrayValue.java:68)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:496)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:252)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:134)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:104)
	at brut.apktool.Main.cmdDecode(Main.java:165)
	at brut.apktool.Main.main(Main.java:81)
bmatichuk$

**Comment by bmatichuk** [comment]
Problem solved.
https://github.com/iBotPeaches/Apktool/issues/1041

However, in my mind Exception = Error. Particularly when magic numbers appear.

**Comment by iBotPeaches** [comment]
Glad it was all solved!
