### ISSUE TITLE
decompile ok but recompile error...help pliz

### ISSUE THREAD

**Issue by gaijin1893** [iBotPeaches/Apktool#1052]
here is the log

Log For : framework-res.apk 

 Log Type : Recompiling 

 Log Recorded At : 12 2015-10- 17:27:40,66 

 Log Recorded By : Advanced ApkTool v4.1.0 By BDFreak 

------------------------------------------------------ 

W: Could not find sources
D:\DISK E\android\projek tomat\PROJECTXPERIZ5\AdvancedApkTool\3-Out\framework-res.apk\AndroidManifest.xml:596: error: Error parsing XML: not well-formed (invalid token)

Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\Users\gaijin\AppData\Local\Temp\brut_util_Jar_7869614284807889441.tmp, p, --forced-package-id, 1, --min-sdk-version, 22, --target-sdk-version, 22, --version-code, 22, --version-name, 5.1.1-6d7b2e95b1, -F, C:\Users\gaijin\AppData\Local\Temp\APKTOOL5616877381576790481.tmp, -x, -0, arsc, -S, D:\DISK E\android\projek tomat\PROJECTXPERIZ5\AdvancedApkTool\3-Out\framework-res.apk\res, -M, D:\DISK E\android\projek tomat\PROJECTXPERIZ5\AdvancedApkTool\3-Out\framework-res.apk\AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:443)
	at brut.androlib.Androlib.buildResources(Androlib.java:380)
	at brut.androlib.Androlib.build(Androlib.java:283)
	at brut.androlib.Androlib.build(Androlib.java:255)
	at brut.apktool.Main.cmdBuild(Main.java:225)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\Users\gaijin\AppData\Local\Temp\brut_util_Jar_7869614284807889441.tmp, p, --forced-package-id, 1, --min-sdk-version, 22, --target-sdk-version, 22, --version-code, 22, --version-name, 5.1.1-6d7b2e95b1, -F, C:\Users\gaijin\AppData\Local\Temp\APKTOOL5616877381576790481.tmp, -x, -0, arsc, -S, D:\DISK E\android\projek tomat\PROJECTXPERIZ5\AdvancedApkTool\3-Out\framework-res.apk\res, -M, D:\DISK E\android\projek tomat\PROJECTXPERIZ5\AdvancedApkTool\3-Out\framework-res.apk\AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:511)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:429)
	... 5 more
Caused by: brut.common.BrutException: could not exec command: [C:\Users\gaijin\AppData\Local\Temp\brut_util_Jar_7869614284807889441.tmp, p, --forced-package-id, 1, --min-sdk-version, 22, --target-sdk-version, 22, --version-code, 22, --version-name, 5.1.1-6d7b2e95b1, -F, C:\Users\gaijin\AppData\Local\Temp\APKTOOL5616877381576790481.tmp, -x, -0, arsc, -S, D:\DISK E\android\projek tomat\PROJECTXPERIZ5\AdvancedApkTool\3-Out\framework-res.apk\res, -M, D:\DISK E\android\projek tomat\PROJECTXPERIZ5\AdvancedApkTool\3-Out\framework-res.apk\AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:89)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:505)
	... 6 more

**Comment by iBotPeaches** [comment]
1. You are using a tool that is a wrapper around apktool. Bug reports here must be using just apktool directly, as I cannot confirm whether any tool wrappers do any non-standard work.

2. The error was printed first `D:\DISK E\android\projek tomat\PROJECTXPERIZ5\AdvancedApkTool\3-Out\framework-res.apk\AndroidManifest.xml:596: error: Error parsing XML: not well-formed (invalid token)`. You have a malformed token in `AndroidManifest.xml`.
