### ISSUE TITLE
Windows Defender identifies the new aapt.exe as Trojan:Win32/Repjexi (apktool-2.0.2.jar)

### ISSUE THREAD

**Issue by minsko** [iBotPeaches/Apktool#1054]
Attempting to build an APK on windows using the released apktool-2.0.2.jar causes the following error:
```
C:\dev\apk>java -jar c:\apps\apktool\apktool_2.0.2.jar build app-debug_22.0.1 --output test_202.apk
I: Using Apktool 2.0.2
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could
 not exec command: [C:\Users\MINSKO~1.PRE\AppData\Local\Temp\brut_util_Jar_3350856700361269765.tmp, p, --forced-package-id, 1
27, --min-sdk-version, 22, --target-sdk-version, 22, --version-code, 1, --version-name, 1.0, -F, C:\Users\MINSKO~1.PRE\AppDat
a\Local\Temp\APKTOOL930219708321474365.tmp, -0, resources.arsc, -0, arsc, -I, C:\Users\minsko.PREINT\apktool\framework\1.apk,
 -S, C:\dev\apk\app-debug_22.0.1\res, -M, C:\dev\apk\app-debug_22.0.1\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:465)
        at brut.androlib.Androlib.buildResources(Androlib.java:403)
        at brut.androlib.Androlib.build(Androlib.java:291)
        at brut.androlib.Androlib.build(Androlib.java:261)
        at brut.apktool.Main.cmdBuild(Main.java:225)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\Users\MINSKO~1.PRE\AppData
\Local\Temp\brut_util_Jar_3350856700361269765.tmp, p, --forced-package-id, 127, --min-sdk-version, 22, --target-sdk-version,
22, --version-code, 1, --version-name, 1.0, -F, C:\Users\MINSKO~1.PRE\AppData\Local\Temp\APKTOOL930219708321474365.tmp, -0, r
esources.arsc, -0, arsc, -I, C:\Users\minsko.PREINT\apktool\framework\1.apk, -S, C:\dev\apk\app-debug_22.0.1\res, -M, C:\dev\
apk\app-debug_22.0.1\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:425)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:451)
        ... 5 more
Caused by: brut.common.BrutException: could not exec command: [C:\Users\MINSKO~1.PRE\AppData\Local\Temp\brut_util_Jar_3350856
700361269765.tmp, p, --forced-package-id, 127, --min-sdk-version, 22, --target-sdk-version, 22, --version-code, 1, --version-
name, 1.0, -F, C:\Users\MINSKO~1.PRE\AppData\Local\Temp\APKTOOL930219708321474365.tmp, -0, resources.arsc, -0, arsc, -I, C:\U
sers\minsko.PREINT\apktool\framework\1.apk, -S, C:\dev\apk\app-debug_22.0.1\res, -M, C:\dev\apk\app-debug_22.0.1\AndroidManif
est.xml]
        at brut.util.OS.exec(OS.java:93)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)
        ... 6 more
Caused by: java.io.IOException: Cannot run program "C:\Users\MINSKO~1.PRE\AppData\Local\Temp\brut_util_Jar_335085670036126976
5.tmp": CreateProcess error=225, Operation did not complete successfully because the file contains a virus or potentially unw
anted software
        at java.lang.ProcessBuilder.start(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at brut.util.OS.exec(OS.java:84)
        ... 7 more
Caused by: java.io.IOException: CreateProcess error=225, Operation did not complete successfully because the file contains a
virus or potentially unwanted software
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
        ... 11 more
```
When downloading the latest source from github, 
brut.apktool\apktool-lib\src\main\resources\prebuilt\aapt\windows\aapt.exe (commit 0fb21a3), also triggers this detection.

Windows Defender has the newest definitions: 1.207.2979.0.

**Comment by iBotPeaches** [comment]
Yep, someone reported on XDA - http://forum.xda-developers.com/showpost.php?p=63278143&postcount=3698

I can assure you there is nothing malicious in this aapt binary. I am investigating why this happened.

**Comment by iBotPeaches** [comment]
https://code.google.com/p/android/issues/detail?id=183525&q=Win32%2FRepjexi&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars

https://code.google.com/p/android/issues/detail?id=184183&q=Win32%2FRepjexi&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars

https://code.google.com/p/android/issues/detail?id=184212&q=Win32%2FRepjexi&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars

https://code.google.com/p/android/issues/detail?id=186916&q=Win32%2FRepjexi&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars

Seems this may be out of my control. Will keep an eye on things and do some research.

**Comment by minsko** [comment]
It looks like Window's Defender has been fixed.
Virus definition 1.207.3087.0 no longer treats is as a virus

**Comment by iBotPeaches** [comment]
Good to hear. I had submitted the binary and this was the response I got.

```
The Microsoft Malware Protection Center (MMPC) has investigated the following file(s) which we received on 10/13/2015 6:11:28 AM Pacific Time.
Below is the determination for your submission.

========
Submission ID MMPC15101363118683

  Submitted Files
  =============================================
  aapt.exe [Not Malware]




Your submission was scanned using antimalware definition version 1.207.3041.0.
========
```
