### ISSUE TITLE
java.lang.ClassCastException: ResBoolValue cannot be cast to ResAttr

### ISSUE THREAD

**Issue by zoujunhua** [iBotPeaches/Apktool#1065]
flyme-res.apk: https://github.com/zoujunhua86/Shared/blob/master/flyme-res.apk
framework-res.apk: https://github.com/zoujunhua86/Shared/blob/master/framework-res.apk

I can't decode the flyme-res.apk.

After installed the framework apks, I have confronted with the following errors when decoding flyme-res.apk:

```
I: Using Apktool 2.0.3-8fee34-SNAPSHOT on flyme-res.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/zoujunhua/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
Exception in thread "main" java.lang.ClassCastException:   brut.androlib.res.data.value.ResBoolValue cannot be cast to brut.androlib.res.data.value.ResAttr
at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:65)
at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:502)
at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:252)
at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:136)
at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
at brut.apktool.Main.cmdDecode(Main.java:165)
at brut.apktool.Main.main(Main.java:81)
```

**Comment by pwelyn** [comment]
It looks like resources that aapt cannot identify.

**Comment by iBotPeaches** [comment]
Continuing to add files to this `if` statement, I believe is the wrong way to go about this. I might need a tiny rewrite in the `AttrDecoder`. It should detect if the class is an instance of `ResScalarType` and/or bring support that the `ResAttr` requires to the other classes via the established `ResValuesXmlSerializable`.

**Comment by iBotPeaches** [comment]
Patching this, introduced

```
eption in thread "main" brut.androlib.err.UndefinedResObject: resource spec: 0x01000000
	at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:65)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:61)
	at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferenceValue.java:57)
	at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:54)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:502)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:252)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:136)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
	at brut.apktool.Main.cmdDecode(Main.java:165)
	at brut.apktool.Main.main(Main.java:81)
```
Which I believe is an invalid resource. Since the first framework resource is

````
      spec resource 0x01010000 android:attr/theme: flags=0x40000000
```

So not sure yet on this.

**Comment by menshen** [comment]
this bug has fixed?

**Comment by iBotPeaches** [comment]
Sorry, 4+ years later - I don't have application and this was reported now on a build very old. Who knows if it'll work now, but the bug sitting here is doing nothing. So I'm closing it for the sanity of this tracker.
