### ISSUE TITLE
unable to decode binaries from appyet

### ISSUE THREAD

**Issue by ooopsalionnn** [iBotPeaches/Apktool#1066]
Errors seen when decompiling any binary from appyet.com

Exception in thread "main" brut.androlib.err.UndefinedResObject: resource spec:
0x01010462
        at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
        at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:65)
        at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:61)
        at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferen
ceValue.java:57)
        at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(Re
sStyleValue.java:54)
        at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResour
ces.java:502)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:252
)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:135)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
        at brut.apktool.Main.cmdDecode(Main.java:165)
        at brut.apktool.Main.main(Main.java:81)

**Comment by pwelyn** [comment]
Delete $HOME/apktool/framework/1.apk file.

**Comment by ooopsalionnn** [comment]
Hey, thanks cleaning that, got it fixed.

Sorry for the trouble and Thank You !!!
