### ISSUE TITLE
Unsupported CM12.1 (android 5.1.1r24) Framework

### ISSUE THREAD

**Issue by xxoscarxx28** [iBotPeaches/Apktool#1068]
I am using apktool v2.0.2 and encountered another Multiple Resource error while installing framework apks
```
Exception in thread "main" brut.androlib.AndrolibException: Multiple resources: spec=0x0103035f style/Theme.DeviceDefault.Resolver, config=-round
	at brut.androlib.res.data.ResConfig.addResource(ResConfig.java:63)
	at brut.androlib.res.data.ResConfig.addResource(ResConfig.java:56)
	at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:223)
	at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:191)
	at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:159)
	at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:116)
	at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:78)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:39)
	at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:599)
	at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:581)
	at brut.androlib.Androlib.installFramework(Androlib.java:676)
	at brut.apktool.Main.cmdInstallFramework(Main.java:240)
	at brut.apktool.Main.main(Main.java:87)
```

Here is the framework-res.apk
https://drive.google.com/file/d/0B23GqSfUuBdIUzY1Z2hfM3VyWlU/view?usp=sharing

**Comment by iBotPeaches** [comment]
This is not an official CM 12.1 There is a qualifier called "darktheme" which is not supported.
