### ISSUE TITLE
Error with APK

### ISSUE THREAD

**Issue by zeroprobe** [iBotPeaches/Apktool#1075]
Attempting to recompile Poweramp Free.

After renaming .PNG to .png to get past case insensitive errors, I now only have two errors.

C:\Users\Johnny\Downloads\AndroidMultitool_3.56\Decompiled_apk\Poweramp-2.0.10-build-581-uni\res\layout-v16\status_controls_big.xml:2: error: No resource identifier found for attribute 'layout_maxHeight' in package 'android'

C:\Users\Johnny\Downloads\AndroidMultitool_3.56\Decompiled_apk\Poweramp-2.0.10-build-581-uni\res\layout-v16\status_controls_big.xml:2: error: No resource identifier found for attribute 'layout_minHeight' in package 'android'

This is the line in question.
<FrameLayout android:layout_width="fill_parent" android:layout_height="128.0dip" internal:layout_maxHeight="128.0dip" internal:layout_minHeight="128.0dip"

https://play.google.com/store/apps/details?id=com.maxmpz.audioplayer&hl=en_GB
## Compile apk

APKTOOL JAR        = Program_Files\apktool.jar
SOURCE FOLDER      = Decompiled_apk\Poweramp-2.0.10-build-581-uni
DESTINATION APK    = Compiled_apk\Poweramp-2.0.10-build-581-uni.apk.apk
## Compiling Compiled_apk\Poweramp-2.0.10-build-581-uni.apk

I: Using Apktool 2.0.2
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
warning: string 'pref_huge' has no default translation.
warning: string 'pref_large' has no default translation.
warning: string 'uv_number_of_subscribers_format' has no default translation.
C:\Users\Johnny\Downloads\AndroidMultitool_3.56\Decompiled_apk\Poweramp-2.0.10-build-581-uni\res\layout-v16\status_controls_big.xml:2: error: No resource identifier found for attribute 'layout_maxHeight' in package 'android'

C:\Users\Johnny\Downloads\AndroidMultitool_3.56\Decompiled_apk\Poweramp-2.0.10-build-581-uni\res\layout-v16\status_controls_big.xml:2: error: No resource identifier found for attribute 'layout_minHeight' in package 'android'

Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\Users\Johnny\AppData\Local\Temp\brut_util_Jar_4483116861319940048.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 21, --version-code, 581, --version-name, 2.0.10-build-581-uni, -F, C:\Users\Johnny\AppData\Local\Temp\APKTOOL6953606917775016265.tmp, -0, arsc, -I, C:\Users\Johnny\apktool\framework\1.apk, -S, C:\Users\Johnny\Downloads\AndroidMultitool_3.56\Decompiled_apk\Poweramp-2.0.10-build-581-uni\res, -M, C:\Users\Johnny\Downloads\AndroidMultitool_3.56\Decompiled_apk\Poweramp-2.0.10-build-581-uni\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:465)
        at brut.androlib.Androlib.buildResources(Androlib.java:403)
        at brut.androlib.Androlib.build(Androlib.java:291)
        at brut.androlib.Androlib.build(Androlib.java:261)
        at brut.apktool.Main.cmdBuild(Main.java:225)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\Users\Johnny\AppData\Local\Temp\brut_util_Jar_4483116861319940048.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 21, --version-code, 581, --version-name, 2.0.10-build-581-uni, -F, C:\Users\Johnny\AppData\Local\Temp\APKTOOL6953606917775016265.tmp, -0, arsc, -I, C:\Users\Johnny\apktool\framework\1.apk, -S, C:\Users\Johnny\Downloads\AndroidMultitool_3.56\Decompiled_apk\Poweramp-2.0.10-build-581-uni\res, -M, C:\Users\Johnny\Downloads\AndroidMultitool_3.56\Decompiled_apk\Poweramp-2.0.10-build-581-uni\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:425)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:451)
        ... 5 more
Caused by: brut.common.BrutException: could not exec command: [C:\Users\Johnny\AppData\Local\Temp\brut_util_Jar_4483116861319940048.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 21, --version-code, 581, --version-name, 2.0.10-build-581-uni, -F, C:\Users\Johnny\AppData\Local\Temp\APKTOOL6953606917775016265.tmp, -0, arsc, -I, C:\Users\Johnny\apktool\framework\1.apk, -S, C:\Users\Johnny\Downloads\AndroidMultitool_3.56\Decompiled_apk\Poweramp-2.0.10-build-581-uni\res, -M, C:\Users\Johnny\Downloads\AndroidMultitool_3.56\Decompiled_apk\Poweramp-2.0.10-build-581-uni\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:89)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)
        ... 6 more
## Adding AndroidManifest.xml file and META-INF folder completed

```
# Press any ket to continue or CTRL + C to break
```

**Comment by iBotPeaches** [comment]
Sorry for the delay, this seems to be same root issue as #1361, going to merge these tickets together to track easier.
