### ISSUE TITLE
cannot pack decompiled package in ubuntu 

### ISSUE THREAD

**Issue by juxiangwu** [iBotPeaches/Apktool#1077]
```
java -jar apktool_2.0.2.jar b app-debug app-debug-unsigned.apk
I: Using Apktool 2.0.2
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/tmp/brut_util_Jar_1849179997615666734.tmp, p, --forced-package-id, 127, --min-sdk-version, 22, --target-sdk-version, 23, --version-code, 1, --version-name, 1.0, -F, /tmp/APKTOOL4414689351894874391.tmp, -0, resources.arsc, -0, arsc, -I, /root/apktool/framework/1.apk, -S, /root/Develop/tool-sets/ApkTool/app-debug/res, -M, /root/Develop/tool-sets/ApkTool/app-debug/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:465)
	at brut.androlib.Androlib.buildResources(Androlib.java:403)
	at brut.androlib.Androlib.build(Androlib.java:291)
	at brut.androlib.Androlib.build(Androlib.java:261)
	at brut.apktool.Main.cmdBuild(Main.java:225)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/tmp/brut_util_Jar_1849179997615666734.tmp, p, --forced-package-id, 127, --min-sdk-version, 22, --target-sdk-version, 23, --version-code, 1, --version-name, 1.0, -F, /tmp/APKTOOL4414689351894874391.tmp, -0, resources.arsc, -0, arsc, -I, /root/apktool/framework/1.apk, -S, /root/Develop/tool-sets/ApkTool/app-debug/res, -M, /root/Develop/tool-sets/ApkTool/app-debug/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:425)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:451)
	... 5 more
Caused by: brut.common.BrutException: could not exec command: [/tmp/brut_util_Jar_1849179997615666734.tmp, p, --forced-package-id, 127, --min-sdk-version, 22, --target-sdk-version, 23, --version-code, 1, --version-name, 1.0, -F, /tmp/APKTOOL4414689351894874391.tmp, -0, resources.arsc, -0, arsc, -I, /root/apktool/framework/1.apk, -S, /root/Develop/tool-sets/ApkTool/app-debug/res, -M, /root/Develop/tool-sets/ApkTool/app-debug/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:93)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)
	... 6 more
Caused by: java.io.IOException: Cannot run program "/tmp/brut_util_Jar_1849179997615666734.tmp": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
	at java.lang.Runtime.exec(Runtime.java:617)
	at java.lang.Runtime.exec(Runtime.java:485)
	at brut.util.OS.exec(OS.java:84)
	... 7 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:186)
	at java.lang.ProcessImpl.start(ProcessImpl.java:130)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
	... 10 more
```

**Comment by iBotPeaches** [comment]
You can't execute binaries from `/tmp`. You can download an `aapt` binary here - http://connortumbleson.com/apktool/aapt/ and use the parameter `--aapt location/to/file/` and it will work.

This isn't a bug.

**Comment by usmansharif525** [comment]
Hi @iBotPeaches can you show me how I will use `--aapt` parameter in this command `java -jar apktool_2.0.2.jar b app-debug app-debug-unsigned.apk`
I am totally new with Android and cli
I am using windows with sdkStudio
I am trying like that 
```java -Xmx128m -jar C:/Users/HP/.apkstudio/vendor/apktool.jar -f b --aapt C:/Users/HP/Downloads/c1_ver6.17 -o C:/Users/HP/Downloads/Video/c9_ver6.17.apk```
Please help asap
