### ISSUE TITLE
Crash with UndefinedResObject on latest Android Wear apk

### ISSUE THREAD

**Issue by CodyToombs** [iBotPeaches/Apktool#1082]
**APK available at:**
http://www.apkmirror.com/apk/google-inc/android-wear/android-wear-1-4-0-2392391-gms-android-apk-download/

**Terminal output:**
```
I: Using Apktool 2.0.2 on com.google.android.wearable.app_1.4.0.2392391.gms-733923910_minAPI18(nodpi).apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/codytoombs/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
Exception in thread "main" brut.androlib.err.UndefinedResObject: resource spec: 0x010104dd
	at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:65)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:61)
	at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferenceValue.java:57)
	at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:54)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:502)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:252)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:135)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
	at brut.apktool.Main.cmdDecode(Main.java:165)
	at brut.apktool.Main.main(Main.java:81)
```

**Comment by iBotPeaches** [comment]
Delete the file at `$HOME/apktool/framework/1.apk` and re-try. Seems to be an outdated framework.

```
ibotpeaches@tombstone:~/Downloads/Apktool/Bug1082$ apktool d com.google.android.wearable.app_1.4.0.2392391.gms-733923910_minAPI18\(nodpi\).apk 
I: Using Apktool 2.0.3-e7c1bc-SNAPSHOT on com.google.android.wearable.app_1.4.0.2392391.gms-733923910_minAPI18(nodpi).apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
ibotpeaches@tombstone:~/Downloads/Apktool/Bug1082$ 
```
