### ISSUE TITLE
Exception in thread "main" brut.androlib.err.UndefinedResObject

### ISSUE THREAD

**Issue by ruijun** [iBotPeaches/Apktool#1086]
When I use apktool, it appear this error:

```
E:\APKTool>java -jar apktool.jar d demo.apk
I: Using Apktool 2.0.2 on demo.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Administrator\apktool\framework\1.
apk
I: Regular manifest package...
I: Decoding file-resources...
W: Could not decode attr value, using undecoded value instead: ns=android, name=
color, value=0x0101042c
W: Could not decode attr value, using undecoded value instead: ns=android, name=
color, value=0x0101042c
W: Could not decode attr value, using undecoded value instead: ns=android, name=
color, value=0x0101042b
I: Decoding values */* XMLs...
Exception in thread "main" brut.androlib.err.UndefinedResObject: resource spec:
0x010301f8
        at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
        at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:65)
        at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:61)
        at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferen
ceValue.java:57)
        at brut.androlib.res.data.value.ResReferenceValue.encodeAsResXml(ResRefe
renceValue.java:47)
        at brut.androlib.res.data.value.ResScalarValue.encodeAsResXmlAttr(ResSca
larValue.java:46)
        at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(Re
sStyleValue.java:49)
        at brut.androlib.res.data.value.ResBagValue.serializeToResValuesXml(ResB
agValue.java:41)
        at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResour
ces.java:502)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:252
)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:135)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
        at brut.apktool.Main.cmdDecode(Main.java:165)
        at brut.apktool.Main.main(Main.java:81)
```

How can I solve this error?

**Comment by iBotPeaches** [comment]
Delete the file at `C:\Users\Administrator\apktool\framework\1.apk` and give it another shot.

**Comment by ruijun** [comment]
@iBotPeaches  Thank you. It is fine for me.

**Comment by ruijun** [comment]
@iBotPeaches  I have another problem:

When I use apktool.bat b E:\APKTool\demo

```
E:\APKTool>apktool.bat b E:\APKTool\demo
I: Using Apktool 2.0.2
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
E:\APKTool\demo\res\layout\notification.xml:2: error: No resource identifi
er found for attribute 'layout_maxHeight' in package 'android'

E:\APKTool\demo\res\layout\notification:2: error: No resource identifi
er found for attribute 'layout_minHeight' in package 'android'

Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.Androl
ibException: brut.common.BrutException: could not exec command: [C:\Users\ADMINI
~1\AppData\Local\Temp\brut_util_Jar_2883198745343773053.tmp, p, --forced-package
-id, 127, --min-sdk-version, 14, --target-sdk-version, 22, --version-code, 7328,
 --version-name, 3.0.028, -F, C:\Users\ADMINI~1\AppData\Local\Temp\APKTOOL161276
7888076467134.tmp, -0, resources.arsc, -0, assets/demo, -0, assets/icudt46l.zip,
-0, assets/addr, -0, assets/name, -0, assets/file, -0, arsc, -I, C:\Users\Administ
rator\apktool\framework\1.apk, -S, E:\APKTool\demo\res, -M, E:\APKTool\demo\Androi
dManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:465)
        at brut.androlib.Androlib.buildResources(Androlib.java:403)
        at brut.androlib.Androlib.build(Androlib.java:291)
        at brut.androlib.Androlib.build(Androlib.java:261)
        at brut.apktool.Main.cmdBuild(Main.java:225)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not
 exec command: [C:\Users\ADMINI~1\AppData\Local\Temp\brut_util_Jar_2883198745343
773053.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-ver
sion, 22, --version-code, 7328, --version-name, 3.0.028, -F, C:\Users\ADMINI~1\A
ppData\Local\Temp\APKTOOL1612767888076467134.tmp, -0, resources.arsc, -0, assets
/demo, -0, assets/icudt46l.zip, -0, assets/addr, -0, assets/name, -0, assets/file,
-0, arsc, -I, C:\Users\Administrator\apktool\framework\1.apk, -S, E:\APKTool\demo
\res, -M, E:\APKTool\demo\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.jav
a:425)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:451)
        ... 5 more
Caused by: brut.common.BrutException: could not exec command: [C:\Users\ADMINI~1
\AppData\Local\Temp\brut_util_Jar_2883198745343773053.tmp, p, --forced-package-i
d, 127, --min-sdk-version, 14, --target-sdk-version, 22, --version-code, 7328, -
-version-name, 3.0.028, -F, C:\Users\ADMINI~1\AppData\Local\Temp\APKTOOL16127678
88076467134.tmp, -0, resources.arsc, -0, assets/demo, -0, assets/icudt46l.zip, -0
, assets/osn, -0, assets/qyy, -0, assets/woqi, -0, arsc, -I, C:\Users\Administra
```

**Comment by iBotPeaches** [comment]
That issue is related to #1019 as custom internal attributes are decode improperly. If you can share that application into #1019 or here, that would be great. Another APK that experiences this issue will be great for researching this.

**Comment by dilanfdo** [comment]
thanks

**Comment by ValentinZhao** [comment]
Thanks that worked for me.
