### ISSUE TITLE
Unicode in AndroidManifest.xml gives "invalid character" when packing (apktool 2.0.2)

### ISSUE THREAD

**Issue by JulianSchuette** [iBotPeaches/Apktool#1102]
Repackaging an APK with (obfuscated) unicode class names gives the following error:

```
java -jar apktool.jar b ./ -o repackaged.apk
I: Using Apktool 2.0.2
I: Checking whether resources has changed...
I: Building resources...
Warning: AndroidManifest.xml already defines minSdkVersion (in http://schemas.android.com/apk/res/android); using existing value in manifest.
Warning: AndroidManifest.xml already defines targetSdkVersion (in http://schemas.android.com/apk/res/android); using existing value in manifest.
AndroidManifest.xml:97: Tag <activity> attribute name has invalid character '.'.
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/tmp/brut_util_Jar_3047420235950007978.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 22, --version-code, 219, --version-name, 2.1.9, -F, /tmp/APKTOOL2209834678239360166.tmp, -0, resources.arsc, -0, arsc, -I, ~/apktool/framework/1.apk, -S, ./res, -M, ./AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:465)
	at brut.androlib.Androlib.buildResources(Androlib.java:403)
	at brut.androlib.Androlib.build(Androlib.java:291)
	at brut.androlib.Androlib.build(Androlib.java:261)
	at brut.apktool.Main.cmdBuild(Main.java:225)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/tmp/brut_util_Jar_3047420235950007978.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 22, --version-code, 219, --version-name, 2.1.9, -F, /tmp/APKTOOL2209834678239360166.tmp, -0, resources.arsc, -0, arsc, -I, ~/apktool/framework/1.apk, -S, ./res, -M, ./AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:425)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:451)
	... 5 more
Caused by: brut.common.BrutException: could not exec command: [/tmp/brut_util_Jar_3047420235950007978.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 22, --version-code, 219, --version-name, 2.1.9, -F, /tmp/APKTOOL2209834678239360166.tmp, -0, resources.arsc, -0, arsc, -I, ~/apktool/framework/1.apk, -S, ./res, -M, ./AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:89)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)
	... 6 more
```

Respective line in AndroidManifest.xml:
```
97:        <activity android:name="o.ᔮ" android:theme="@style/Theme.IAPTheme"/>
```

**Comment by iBotPeaches** [comment]
Yep. Haven't figured this out yet. Obviously a custom `aapt` is involved. #885
