### ISSUE TITLE
Unable to build apk file by using apktool after decompile

### ISSUE THREAD

**Issue by sridharreddysuram123** [iBotPeaches/Apktool#1106]
```

I: Checking whether resources has changed...
I: Building resources...
C:\Users\ssuram\Desktop\Tess\Test\res\values-v23\styles.xml:5: error: Error retrieving pa
rent for item: No resource found that matches the given name '@android:style/AlertDialog'.

C:\Users\ssuram\Desktop\Tess\Test\res\values-v23\styles.xml:6: error: Error retrieving pa
rent for item: No resource found that matches the given name '@android:style/DialogWindowTitle'
.

Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: br
ut.common.BrutException: could not exec command: [C:\Users\ssuram\AppData\Local\Temp\brut_util_
Jar_7469819303594108011.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-v
ersion, 16, --version-code, 285, --version-name, 8.6.0.0.93D, -F, C:\Users\ssuram\AppData\Local
\Temp\APKTOOL4347588568436142594.tmp, -0, resources.arsc, -0, res/raw/activation.p12, -0, res/r
aw/motorolaplugin.apk, -0, res/raw/samsungplugin.apk, -0, res/raw/samsungproxy.apk, -0, arsc, -
I, C:\Users\ssuram\apktool\framework\1.apk, -S, C:\Users\ssuram\Desktop\Tess\Test\res, -M
, C:\Users\ssuram\Desktop\Tess\Test\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:465)
        at brut.androlib.Androlib.buildResources(Androlib.java:403)
        at brut.androlib.Androlib.build(Androlib.java:291)
        at brut.androlib.Androlib.build(Androlib.java:261)
        at brut.apktool.Main.cmdBuild(Main.java:225)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command:
[C:\Users\ssuram\AppData\Local\Temp\brut_util_Jar_7469819303594108011.tmp, p, --forced-package-
id, 127, --min-sdk-version, 14, --target-sdk-version, 16, --version-code, 285, --version-name,
8.6.0.0.93D, -F, C:\Users\ssuram\AppData\Local\Temp\APKTOOL4347588568436142594.tmp, -0, resourc
es.arsc, -0, res/raw/activation.p12, -0, res/raw/motorolaplugin.apk, -0, res/raw/samsungplugin.
apk, -0, res/raw/samsungproxy.apk, -0, arsc, -I, C:\Users\ssuram\apktool\framework\1.apk, -S, C
:\Users\ssuram\Desktop\Tess\Test\res, -M, C:\Users\ssuram\Desktop\Tess\Test\Android
Manifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:425)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:451)
        ... 5 more
Caused by: brut.common.BrutException: could not exec command: [C:\Users\ssuram\AppData\Local\Te
mp\brut_util_Jar_7469819303594108011.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, -
-target-sdk-version, 16, --version-code, 285, --version-name, 8.6.0.0.93D, -F, C:\Users\ssuram\
AppData\Local\Temp\APKTOOL4347588568436142594.tmp, -0, resources.arsc, -0, res/raw/activation.p
12, -0, res/raw/motorolaplugin.apk, -0, res/raw/samsungplugin.apk, -0, res/raw/samsungproxy.apk
, -0, arsc, -I, C:\Users\ssuram\apktool\framework\1.apk, -S, C:\Users\ssuram\Desktop\Tess\mobil
eiron\res, -M, C:\Users\ssuram\Desktop\Tess\Test\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:89)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)
        ... 6 more
```

**Comment by iBotPeaches** [comment]
Do you have frameworks and/or the apk?

**Comment by sridharreddysuram123** [comment]
Hey, this got resolved myself. I just got the framework-res.apk file from Android M device and replaced to apktool framework folder and renamed to 1.apk. 
From that time onward its working fine.. 

Thanks for providing this tool.
