### ISSUE TITLE
Samsung android 6.0 framework-res error

### ISSUE THREAD

**Issue by mythtrandyr** [iBotPeaches/Apktool#1109]
<B>I upload apk to: </b>
<a href=http://www.filedropper.com/framework-res_1>http://www.filedropper.com/framework-res_1</a></div>

<B>output is::</b>
<pre><code>C:\Users\Admin\Desktop\Test_Lollipop>apktool if framework-res.apk
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:52)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:39)
        at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:599)
        at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:581)
        at brut.androlib.Androlib.installFramework(Androlib.java:683)
        at brut.apktool.Main.cmdInstallFramework(Main.java:240)
        at brut.apktool.Main.main(Main.java:87)
Caused by: java.io.IOException: Expected: 0x00000008, got: 0x00000000
        at brut.util.ExtDataInput.skipCheckShort(ExtDataInput.java:56)
        at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:282)
        at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:224)
        at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:212)
        at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:154)
        at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:116)
        at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:78)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
        ... 6 more
</code></pre>

<pre><codeC:\Users\Admin\Desktop\Test_Lollipop>apktool d framework-res.apk
I: Using Apktool 2.0.3-831765-SNAPSHOT on framework-res.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:52)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:544)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:63)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:55)
        at brut.androlib.Androlib.getResTable(Androlib.java:66)
        at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:198)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:96)
        at brut.apktool.Main.cmdDecode(Main.java:165)
        at brut.apktool.Main.main(Main.java:81)
Caused by: java.io.IOException: Expected: 0x00000008, got: 0x00000000
        at brut.util.ExtDataInput.skipCheckShort(ExtDataInput.java:56)
        at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:282)
        at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:224)
        at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:212)
        at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:154)
        at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:116)
        at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:78)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
        ... 8 more
</code></pre>

**Comment by iBotPeaches** [comment]
Yep, appears after reading a `ComplexEntry` we fail the `ResValue` check. This might mean it is infact not a `ComplexEntry` or something else entirely. We got `0x0` when expecting `0x08`, so maybe there is a new `NULL` type/entry I'm missing.

Will check AOSP.

**Comment by mythtrandyr** [comment]
re-upload framework-res.apk - https://www.dropbox.com/s/s68uyt9052dshs8/framework-res.apk?dl=0

**Comment by ManhIT-CMB** [comment]
@iBotPeaches APK files M - G920F
https://drive.google.com/file/d/0B40ItdHKfkyQZmVkWi1PeXMyUEk/view?usp=sharing

**Comment by iBotPeaches** [comment]
^ Yes same problem with that apk. Research is still ongoing.

**Comment by mythtrandyr** [comment]
@iBotPeaches 
Any news for fix this bug?
Happy New Year! :)

**Comment by uzumaki333** [comment]
Happy new year! Any idea when can this be fixed? Waiting for this eagerly.

**Comment by iBotPeaches** [comment]
I have no idea. Some bugs sit here unfixed for years, while others are fixed in days while others take months.

User contributed research and/or fixes helps greatly. I'm only one man :p

**Comment by uzumaki333** [comment]
apparently the framework apk gets decoded using apktool version 2.0.0

**Comment by uzumaki333** [comment]
it seems 2.00 version works for Samsung 6.0 framework apk but does not work for Nexus/Stocked/AOSP.
2.0.3 works great for Nexus/Stocked/AOSP but not for Samsung 6.0 framework apk

**Comment by nmeuret** [comment]
Well it seems that the 2.0 only decompile the resources of 6.0 apks, not the smali part. So it may be ok to install resources files, but not to work on the code (SystemUI ...).

**Comment by iBotPeaches** [comment]
Fixed this earlier and forgot to update this - https://github.com/iBotPeaches/Apktool/commit/ba62238843f26496a876c9ef2b1e273a1ff8080b

Confirming

```
➜  Bug1109 apktool d framework-res.apk -f
I: Using Apktool 2.2.0-e1dd43-SNAPSHOT on framework-res.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1109 
```

Sorry for the delay.
