### ISSUE TITLE
 Apktool 2.0.3 Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file

### ISSUE THREAD

**Issue by yuwu** [iBotPeaches/Apktool#1121]
```
I: Using Apktool 2.0.3 on taobao.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:52)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:544)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:63)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:55)
	at brut.androlib.Androlib.getResTable(Androlib.java:66)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:198)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:96)
	at brut.apktool.Main.cmdDecode(Main.java:165)
	at brut.apktool.Main.main(Main.java:81)
Caused by: java.io.IOException: Expected: 0x001c0001, got: 0x00000001
	at brut.util.ExtDataInput.skipCheckChunkTypeInt(ExtDataInput.java:75)
	at brut.util.ExtDataInput.skipCheckChunkTypeInt(ExtDataInput.java:73)
	at brut.androlib.res.decoder.StringBlock.read(StringBlock.java:44)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:73)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
	... 8 more
```

**Comment by yuwu** [comment]
help me:

**Comment by yuwu** [comment]
@iBotPeaches 
 apktool d taobao.apk

**Comment by iBotPeaches** [comment]
Can you upload the apk?

**Comment by iBotPeaches** [comment]
Closing in favour of #1131

**Comment by jjarongay50** [comment]
The APKTool is not compatible on that apk...
