### ISSUE TITLE
Unknown code like ♀∟ code

### ISSUE THREAD

**Issue by 6157bhr** [iBotPeaches/Apktool#1152]
sir, please help me to decompile the apk.
I'm using your's latest version (2.0.3) and get this error..
FYI, there is some files with unknown code..
```
D:\PROJECT 84\Alat>apktool d xxx.apk
I: Using Apktool 2.0.3 on xxx.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\xxx\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: Error copying file: ♀∟.xml
at brut.androlib.Androlib.decodeUnknownFiles(Androlib.java:214)
at brut.androlib.ApkDecoder.decode(ApkDecoder.java:158)
at brut.apktool.Main.cmdDecode(Main.java:165)
at brut.apktool.Main.main(Main.java:81)
Caused by: brut.directory.DirectoryException: Error copying file: ♀∟.xml
at brut.directory.DirUtil.copyToDir(DirUtil.java:88)
at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:207)
at brut.androlib.Androlib.decodeUnknownFiles(Androlib.java:207)
... 3 more
Caused by: java.io.FileNotFoundException: xxx\unknown\♀∟.xml (The filename, directory name, or volume label syntax is incorrect)
at java.io.FileOutputStream.open0(Native Method)
at java.io.FileOutputStream.open(Unknown Source)
at java.io.FileOutputStream.<init>(Unknown Source)
at java.io.FileOutputStream.<init>(Unknown Source)
at brut.directory.DirUtil.copyToDir(DirUtil.java:84)
... 5 more
```

**Comment by iBotPeaches** [comment]
Duplicate #1129
