### ISSUE TITLE
samsung systemui recompiling issue

### ISSUE THREAD

**Issue by giorkam80** [iBotPeaches/Apktool#1159]
```
warning: string 'keyguard_accessibility_status' has no default translation.
warning: string 'kg_password_wrong_pin_code' has no default translation.
warning: string 'lockscreen_voiceunlock_dialog_title_text' has no default translation.
warning: string 'lockscreen_voiceunlock_recognising_text' has no default translation.
warning: string 'unablechange_soundmode_incarmode' has no default translation.
/sdcard/SpeedSoftware/Extracted/SystemUI_src/res/layout/keyguard_fmm_unlock_view.xml:32: error: Error: No resource found that matches the given name (at 'style' with value '@style/Ok_theme').

Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/data/data/per.pqy.apktool/apktool/openjdk/bin/aaptnew, p, --min-sdk-version, 21, --target-sdk-version, 21, --version-code, 21, --version-name, 5.0.2-G901FXXU1BOH4, -F, /data/data/per.pqy.apktool/APKTOOL551561160155493470.tmp, -0, arsc, -I, /data/data/per.pqy.apktool/1.apk, -S, /sdcard/SpeedSoftware/Extracted/SystemUI_src/res, -M, /sdcard/SpeedSoftware/Extracted/SystemUI_src/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:458)
	at brut.androlib.Androlib.buildResources(Androlib.java:396)
	at brut.androlib.Androlib.build(Androlib.java:285)
	at brut.androlib.Androlib.build(Androlib.java:256)
	at brut.apktool.Main.cmdBuild(Main.java:225)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/data/data/per.pqy.apktool/apktool/openjdk/bin/aaptnew, p, --min-sdk-version, 21, --target-sdk-version, 21, --version-code, 21, --version-name, 5.0.2-G901FXXU1BOH4, -F, /data/data/per.pqy.apktool/APKTOOL551561160155493470.tmp, -0, arsc, -I, /data/data/per.pqy.apktool/1.apk, -S, /sdcard/SpeedSoftware/Extracted/SystemUI_src/res, -M, /sdcard/SpeedSoftware/Extracted/SystemUI_src/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:444)
	... 5 more
Caused by: brut.common.BrutException: could not exec command: [/data/data/per.pqy.apktool/apktool/openjdk/bin/aaptnew, p, --min-sdk-version, 21, --target-sdk-version, 21, --version-code, 21, --version-name, 5.0.2-G901FXXU1BOH4, -F, /data/data/per.pqy.apktool/APKTOOL551561160155493470.tmp, -0, arsc, -I, /data/data/per.pqy.apktool/1.apk, -S, /sdcard/SpeedSoftware/Extracted/SystemUI_src/res, -M, /sdcard/SpeedSoftware/Extracted/SystemUI_src/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:89)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:413)
	... 6 more
I: Using Apktool 2.0.0-07ea41-SNAPSHOT
I: Smaling smali folder into classes.dex...
I: Building resources...
```

**Comment by giorkam80** [comment]
Any help im a starter any understanding is welcome :)

**Comment by iBotPeaches** [comment]
Could you please upload/attach the frameworks and associated apk with this problem?

**Comment by giorkam80** [comment]
https://www.dropbox.com/s/kvr2rzvc28libx8/SystemUI.apk?dl=0
https://www.dropbox.com/s/1mi6kx16kqljjl9/framework-res.apk?dl=0

**Comment by iBotPeaches** [comment]
```
➜  Bug1159  grep -r -i 'Ok_theme'
SystemUI/res/layout/keyguard_fmm_unlock_view.xml: style="@style/Ok_theme" />
Binary file SystemUI/build/apk/classes.dex matches
SystemUI/smali/com/android/keyguard/R$style.smali:.field public static final Ok_theme:I = 0x7f0f000d
SystemUI/smali/com/android/systemui/R$style.smali:.field public static final Ok_theme:I = 0x7f0f000d
SystemUI/smali/com/sec/android/sviewcover/R$style.smali:.field public static final Ok_theme:I = 0x7f0f000d
➜  Bug1159  aapt d resources SystemUI.apk | grep '0x7f0f000d' 
      INVALID TYPE CONFIG FOR RESOURCE 0x7f0f000d
```

As you can see, we have the theme in both source and resources. However, the resource has `INVALID TYPE CONFIG`.

There is nothing apktool can do about this. It doesn't currently know the type of invalid types. It is casted to boolean for `DUMMY_RESOURCE`. You can remake a style for that resource `Ok_theme` or remove the reference to it.

Unfortunately there is nothing apktool can do here currently.

**Comment by giorkam80** [comment]
But this systemui was recompiled succesfully by someone replacing some icons but how;;sorry for the noob question.he skipped the errors;how;how do i remove the reference;;
