### ISSUE TITLE
error while loading shared libraries: libz.so.1: cannot open shared object file

### ISSUE THREAD

**Issue by Yokosa** [iBotPeaches/Apktool#1165]
Hello 
I have problem whit recompiling. I was looking for a solution but never found. Could someone help me?

```
grzegorz@grzegorz-X510LN:~/Pulpit/Katalog bez nazwy$ apktool b SystemUII: Using Apktool 2.0.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
Exception in thread "main" /tmp/brut_util_Jar_4725780192128114282.tmp: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/tmp/brut_util_Jar_4725780192128114282.tmp, p, --forced-package-id, 127, --min-sdk-version, 17, --target-sdk-version, 17, --version-code, 17, --version-name, 4.2.2-43, -F, /tmp/APKTOOL2385241654917404844.tmp, -I, /home/grzegorz/apktool/framework/1.apk, -S, /home/grzegorz/Pulpit/Katalog bez nazwy/SystemUI/res, -M, /home/grzegorz/Pulpit/Katalog bez nazwy/SystemUI/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:459)
	at brut.androlib.Androlib.buildResources(Androlib.java:397)
	at brut.androlib.Androlib.build(Androlib.java:285)
	at brut.androlib.Androlib.build(Androlib.java:256)
	at brut.apktool.Main.cmdBuild(Main.java:225)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/tmp/brut_util_Jar_4725780192128114282.tmp, p, --forced-package-id, 127, --min-sdk-version, 17, --target-sdk-version, 17, --version-code, 17, --version-name, 4.2.2-43, -F, /tmp/APKTOOL2385241654917404844.tmp, -I, /home/grzegorz/apktool/framework/1.apk, -S, /home/grzegorz/Pulpit/Katalog bez nazwy/SystemUI/res, -M, /home/grzegorz/Pulpit/Katalog bez nazwy/SystemUI/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:445)
	... 5 more
Caused by: brut.common.BrutException: could not exec command: [/tmp/brut_util_Jar_4725780192128114282.tmp, p, --forced-package-id, 127, --min-sdk-version, 17, --target-sdk-version, 17, --version-code, 17, --version-name, 4.2.2-43, -F, /tmp/APKTOOL2385241654917404844.tmp, -I, /home/grzegorz/apktool/framework/1.apk, -S, /home/grzegorz/Pulpit/Katalog bez nazwy/SystemUI/res, -M, /home/grzegorz/Pulpit/Katalog bez nazwy/SystemUI/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:89)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:413)
	... 6 more
```

**Comment by iBotPeaches** [comment]
```
error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
```

Don't think apktool or aapt has anything to do with this error. Seems to be isolated to 32bit support on 64bit system (i think).

http://stackoverflow.com/questions/21256866/libz-so-1-cannot-open-shared-object-file

**Comment by Yokosa** [comment]
Thank you very much, everything is working perfectly now :)

**Comment by iBotPeaches** [comment]
Glad it worked out. Closing this then.
