### ISSUE TITLE
Cannot build .apk file using apktool 2.0.3

### ISSUE THREAD

**Issue by AashishTech** [iBotPeaches/Apktool#1175]
I'm using apktool 2.0.3

I can decompile the apk easily but without making any changes when I try to recompile it, the following error comes(Please help):
```
I: Using Apktool 2.0.3
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
C:\Users\User\Downloads\apktool-AashishTech\pawo1\AndroidManifest.xml:14: error:
 No resource identifier found for attribute 'isGame' in package 'android'

Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.Androl
ibException: brut.common.BrutException: could not exec command: [C:\Users\User\A
ppData\Local\Temp\brut_util_Jar_5054684620690300249.tmp, p, --forced-package-id,
 127, --min-sdk-version, 9, --target-sdk-version, 23, --version-code, 15, --vers
ion-name, 2.0.4, -F, C:\Users\User\AppData\Local\Temp\APKTOOL6089721994366000321
.tmp, -0, arsc, -0, split0, -0, split1, -0, split2, -0, arsc, -I, C:\Users\User\
apktool\framework\1.apk, -S, C:\Users\User\Downloads\apktool-AashishTech\pawo1\r
es, -M, C:\Users\User\Downloads\apktool-AashishTech\pawo1\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:472)
        at brut.androlib.Androlib.buildResources(Androlib.java:410)
        at brut.androlib.Androlib.build(Androlib.java:298)
        at brut.androlib.Androlib.build(Androlib.java:268)
        at brut.apktool.Main.cmdBuild(Main.java:225)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not
 exec command: [C:\Users\User\AppData\Local\Temp\brut_util_Jar_50546846206903002
49.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version,
 23, --version-code, 15, --version-name, 2.0.4, -F, C:\Users\User\AppData\Local\
Temp\APKTOOL6089721994366000321.tmp, -0, arsc, -0, split0, -0, split1, -0, split
2, -0, arsc, -I, C:\Users\User\apktool\framework\1.apk, -S, C:\Users\User\Downlo
ads\apktool-AashishTech\pawo1\res, -M, C:\Users\User\Downloads\apktool-AashishTe
ch\pawo1\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.jav
a:425)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:458)
        ... 5 more
Caused by: brut.common.BrutException: could not exec command: [C:\Users\User\App
Data\Local\Temp\brut_util_Jar_5054684620690300249.tmp, p, --forced-package-id, 1
27, --min-sdk-version, 9, --target-sdk-version, 23, --version-code, 15, --versio
n-name, 2.0.4, -F, C:\Users\User\AppData\Local\Temp\APKTOOL6089721994366000321.t
mp, -0, arsc, -0, split0, -0, split1, -0, split2, -0, arsc, -I, C:\Users\User\ap
ktool\framework\1.apk, -S, C:\Users\User\Downloads\apktool-AashishTech\pawo1\res
, -M, C:\Users\User\Downloads\apktool-AashishTech\pawo1\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:89)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.jav
a:419)
        ... 6 more
```

**Comment by iBotPeaches** [comment]
```
C:\Users\User\Downloads\apktool-AashishTech\pawo1\AndroidManifest.xml:14: error:
 No resource identifier found for attribute 'isGame' in package 'android'
```

`isGame` is a valid attribute according to http://developer.android.com/guide/topics/manifest/application-element.html

Update your frameworks. Check out docs for help - http://ibotpeaches.github.io/Apktool/documentation/#framework-files

**Comment by AashishTech** [comment]
Okay..just removed the 1.apk file from /framework and its done. Thank you :)
