### ISSUE TITLE
Movnow Plus

### ISSUE THREAD

**Issue by kz1080** [iBotPeaches/Apktool#1179]
Error Message：
```
C:\apktool>apktool.bat d -f Movnow.apk
I: Baksmaling...
I: Loading resource table...
I: Loaded.
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Mars\apktool\framework\1.apk
W: Could not decode attr value, using undecoded value instead: ns=android, name=
versionCode, value=0x00000174
I: Loading resource table from file: C:\Users\Mars\apktool\framework\1.apk
W: Could not decode attr value, using undecoded value instead: ns=android, name=
versionName, value=0x0000001d
Exception in thread "main" java.lang.NullPointerException
        at java.io.Writer.write(Unknown Source)
        at brut.androlib.res.util.ExtMXSerializer.writeAttributeValue(ExtMXSeria
lizer.java:38)
        at org.xmlpull.mxp1_serializer.MXSerializer.attribute(MXSerializer.java:
673)
        at org.xmlpull.v1.wrapper.classic.XmlSerializerDelegate.attribute(XmlSer
ializerDelegate.java:106)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartT
ag(StaticXmlSerializerWrapper.java:267)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(Stati
cXmlSerializerWrapper.java:211)
        at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamD
ecoder.java:80)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDe
coder.java:130)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPull
StreamDecoder.java:144)
        at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecode
r.java:131)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:218
)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:115)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:114)
        at brut.apktool.Main.cmdDecode(Main.java:146)
        at brut.apktool.Main.main(Main.java:77)

C:\apktool>
```

**Comment by iBotPeaches** [comment]
Give a read to the framework files portion of our docs - http://ibotpeaches.github.io/Apktool/documentation/#framework-files. Your `$HOME/apktool/framework/1.apk` is probably out of date.

```
➜  Bug1179 apktool d movnow\ plus_v3.7.5_apkpure.com.apk 
I: Using Apktool 2.1.0-57a8eb-SNAPSHOT on movnow plus_v3.7.5_apkpure.com.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1179 
```
