### ISSUE TITLE
Doesn't decompile correctly mihome.apk

### ISSUE THREAD

**Issue by maddoctor** [iBotPeaches/Apktool#1181]
App mihome.apk found in playstore, is not decompiled correctly with the latest version of jbart. Please advise.
https://play.google.com/store/apps/details?id=com.xiaomi.smarthome&utm_source=android.downloadatoz.com&referrer=utm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_term%3Dmihome+3.5.1&pcampaignid=APPU_1_BxnWVrXUJsX9yQPpnp_wAg

**Comment by BurgerZ** [comment]
Any log? Attached apk (or direct link to it)?
Anyway, it's apktool's issue, jbart itself has nothing to do with recompiling process - it just calls external apktool.

**Comment by iBotPeaches** [comment]
```
➜  Bug1181 apktool d MiHome_v3.4.13_apkpure.com.apk 
I: Using Apktool 2.1.0-5c7702-SNAPSHOT on MiHome_v3.4.13_apkpure.com.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1181 
```

No problem on the latest master code. Check in the upcoming 2.1.0 release.

**Comment by maddoctor** [comment]
Trying to decompile the latest version of Mi Home 3.4.15 I get this log using 2a

Process log:
[04.03.2016 22:58:31.725] I: FRIDAY 04.03.2016 22:58:31
[04.03.2016 22:58:31.725] I: Copyright: 2012-2014, Andrei Zhukouski (BurgerZ@xda)
[04.03.2016 22:58:31.725] I: www: http://burgerz.pro
[04.03.2016 22:58:31.725] I: Email: az.burgerz@gmail.com
[04.03.2016 22:58:31.725] I: All Rights Reserved
[04.03.2016 22:58:31.725] I: **************************************************
[04.03.2016 22:58:31.741] I: Welcome to jBART v2a build 20150824.02
[04.03.2016 22:58:31.741] I: **************************************************
[04.03.2016 22:58:31.741] I: Apkengine version: Apktool 3.0.1-BZ
[04.03.2016 22:58:31.741] I: Java version: 1.8.0_71
[04.03.2016 22:58:31.741] I: OS name: Windows 10
[04.03.2016 22:58:31.741] I: OS version: 10.0
[04.03.2016 22:58:31.741] I: OS arch: 64 bit
[04.03.2016 22:58:31.741] I: Home directory: D:\Xiaomi\jBART-master\
[04.03.2016 22:58:31.741] I: 
[04.03.2016 23:00:08.619] I: Loaded JSON patcher config: D:\Xiaomi\jBART-master\data\patches\miui\smali\thememanager_method.conf
[04.03.2016 23:00:08.619] I: Loaded JSON patcher config: D:\Xiaomi\jBART-master\data\patches\miui\smali\updater_method.conf
[04.03.2016 23:00:08.642] I: Loaded JSON patcher config: D:\Xiaomi\jBART-master\data\patches\miui\manifest\manifest_patches.conf
[04.03.2016 23:00:08.646] I: Loaded NXT patcher config: D:\Xiaomi\jBART-master\data\patches\nxt\ContactsProvider\T9.ptch
[04.03.2016 23:00:08.771] I: ******** Installing frameworks ********
[04.03.2016 23:00:08.817] I: **** Decompiling Mi Home_3.4.15.apk ****
[04.03.2016 23:00:08.864] I: Loading resource table...
[04.03.2016 23:00:09.083] I: Decoding AndroidManifest.xml with resources...
[04.03.2016 23:00:09.737] I: Loading resource table from file: D:\Xiaomi\jBART-master\data\frameworks\1.apk
[04.03.2016 23:00:09.972] I: Regular manifest package...
[04.03.2016 23:00:10.300] I: Decoding file-resources...
[04.03.2016 23:00:17.619] I: Decoding values */* XMLs...
[04.03.2016 23:00:18.126] I: Copying raw classes.dex file...
[04.03.2016 23:00:18.680] I: Copying raw classes2.dex file...
[04.03.2016 23:00:18.711] I: Copying assets and libs...
[04.03.2016 23:00:19.102] I: Check for available patches...
[04.03.2016 23:00:19.102] I: Check for available NXT patches...
[04.03.2016 23:00:19.102] I: ******** Decompiling finished ********
[04.03.2016 23:00:19.117] I: Time elapsed: 0h 0m 10s 424ms

Using latest version 3h I get this log:

Process log:
[04.03.2016 23:02:39] I: 
[04.03.2016 23:02:39] I: 
[04.03.2016 23:02:39] I: FRIDAY 04.03.2016 23:02:39
[04.03.2016 23:02:39] I: Copyright: 2012-2015, Andrei Zhukouski (BurgerZ)
[04.03.2016 23:02:39] I: www: http://burgerz.pro
[04.03.2016 23:02:39] I: Email: az.burgerz@gmail.com
[04.03.2016 23:02:39] I: All Rights Reserved
[04.03.2016 23:02:39] I: **************************************************
[04.03.2016 23:02:39] I: Welcome to jBART v3h build 20160106.07
[04.03.2016 23:02:39] I: **************************************************
[04.03.2016 23:02:39] I: Java version: 1.8.0_71
[04.03.2016 23:02:39] I: OS name: Windows 10
[04.03.2016 23:02:39] I: OS version: 10.0
[04.03.2016 23:02:39] I: OS arch: 64 bit
[04.03.2016 23:02:39] I: Home directory: D:\Xiaomi\jBART-master\
[04.03.2016 23:02:39] I: 
[04.03.2016 23:02:55] I: Loaded NXT patcher config: D:\Xiaomi\jBART-master\data\patches\nxt\ContactsProvider\T9.ptch
[04.03.2016 23:02:55] I: 
[04.03.2016 23:02:55] I: 
[04.03.2016 23:02:55] I: FRIDAY 04.03.2016 23:02:55
[04.03.2016 23:02:55] I: Copyright: 2012-2015, Andrei Zhukouski (BurgerZ)
[04.03.2016 23:02:55] I: www: http://burgerz.pro
[04.03.2016 23:02:55] I: Email: az.burgerz@gmail.com
[04.03.2016 23:02:55] I: All Rights Reserved
[04.03.2016 23:02:55] I: **************************************************
[04.03.2016 23:02:55] I: Welcome to jBART v3h build 20160106.07
[04.03.2016 23:02:55] I: **************************************************
[04.03.2016 23:02:55] I: Java version: 1.8.0_71
[04.03.2016 23:02:55] I: OS name: Windows 10
[04.03.2016 23:02:55] I: OS version: 10.0
[04.03.2016 23:02:55] I: OS arch: 64 bit
[04.03.2016 23:02:55] I: Home directory: D:\Xiaomi\jBART-master\
[04.03.2016 23:02:55] I: 
[04.03.2016 23:02:55] I: 
[04.03.2016 23:02:55] I: ******** Installing frameworks ********
[04.03.2016 23:02:55] I: **** Decompiling Mi Home_3.4.15.apk ****
[04.03.2016 23:02:55] I: File apktool.jar not found. Using apktool-3.0.9-bz-small.jar
[04.03.2016 23:02:56] I: I: Loading resource table...
[04.03.2016 23:02:56] I: I: Decoding AndroidManifest.xml with resources...
[04.03.2016 23:02:56] I: I: Loading resource table from file: D:\Xiaomi\jBART-master\data\frameworks\1.apk
[04.03.2016 23:02:56] I: I: Package: com.xiaomi.smarthome (com.xiaomi.smarthome)
[04.03.2016 23:02:56] I: I: Regular manifest package...
[04.03.2016 23:02:56] I: I: Decoding file-resources...
[04.03.2016 23:03:03] I: I: Decoding values */* XMLs...
[04.03.2016 23:03:04] I: I: Copying raw classes.dex file...
[04.03.2016 23:03:04] I: I: Copying raw classes2.dex file...
[04.03.2016 23:03:04] I: I: Copying assets and libs...
[04.03.2016 23:03:05] W: Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: Error copying file: assets
[04.03.2016 23:03:05] W: 	at brut.androlib.Androlib.decodeRawFiles(Androlib.java:159)
[04.03.2016 23:03:05] W: 	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:157)
[04.03.2016 23:03:05] W: 	at brut.apktool.Main.cmdDecode(Main.java:191)
[04.03.2016 23:03:05] W: 	at brut.apktool.Main.main(Main.java:106)
[04.03.2016 23:03:05] W: Caused by: brut.directory.DirectoryException: Error copying file: assets
[04.03.2016 23:03:05] W: 	at brut.directory.DirUtil.copyToDir(DirUtil.java:91)
[04.03.2016 23:03:05] W: 	at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:207)
[04.03.2016 23:03:05] W: 	at brut.androlib.Androlib.decodeRawFiles(Androlib.java:150)
[04.03.2016 23:03:05] W: 	... 3 more
[04.03.2016 23:03:05] W: Caused by: brut.directory.DirectoryException: Error copying file: static/static.home.mi.com/app/shop/img?id=shop_02c7360b334e35457001998c7b08b75e.jpg
[04.03.2016 23:03:05] W: 	at brut.directory.DirUtil.copyToDir(DirUtil.java:88)
[04.03.2016 23:03:05] W: 	at brut.directory.DirUtil.copyToDir(DirUtil.java:61)
[04.03.2016 23:03:05] W: 	at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:197)
[04.03.2016 23:03:05] W: 	at brut.directory.DirUtil.copyToDir(DirUtil.java:77)
[04.03.2016 23:03:05] W: 	... 5 more
[04.03.2016 23:03:05] W: Caused by: java.io.FileNotFoundException: D:\Xiaomi\jBART-master\Mi Home_3.4.15.apk.bzprj\decompiled\Mi Home_3.4.15.apk\assets\static\static.home.mi.com\app\shop\img?id=shop_02c7360b334e35457001998c7b08b75e.jpg (The filename, directory name, or volume label syntax is incorrect)
[04.03.2016 23:03:05] W: 	at java.io.FileOutputStream.open0(Native Method)
[04.03.2016 23:03:05] W: 	at java.io.FileOutputStream.open(Unknown Source)
[04.03.2016 23:03:05] W: 	at java.io.FileOutputStream.<init>(Unknown Source)
[04.03.2016 23:03:05] W: 	at java.io.FileOutputStream.<init>(Unknown Source)
[04.03.2016 23:03:05] W: 	at brut.directory.DirUtil.copyToDir(DirUtil.java:84)
[04.03.2016 23:03:05] W: 	... 8 more
[04.03.2016 23:03:05] S: pro.burgerz.bart.core.exceptions.DecompileException: pro.burgerz.bart.core.exceptions.ExecuteException: Could not exec (exit code = 1): [javaw, -Xms247m, -Xmx247m, -jar, D:\Xiaomi\jBART-master\data\tools\lib\apktool-3.0.9-bz-small.jar, d, -f, -s, -p, D:\Xiaomi\jBART-master\data\frameworks, -o, D:\Xiaomi\jBART-master\Mi Home_3.4.15.apk.bzprj\decompiled\Mi Home_3.4.15.apk, D:\Google\Xiaomi\Mi Home\Smart Home\Mi Home_3.4.15.apk]
[04.03.2016 23:03:05] I: Time elapsed: 0h 0m 9s 669ms


And if I try, even with the 2a to decompile the same app, other version that I usually get from a russian site where they add the russian language, the file is decompiled ok and this is the log:
[04.03.2016 23:05:11] I: FRIDAY 04.03.2016 23:05:11
[04.03.2016 23:05:11] I: Copyright: 2012-2015, Andrei Zhukouski (BurgerZ)
[04.03.2016 23:05:11] I: www: http://burgerz.pro
[04.03.2016 23:05:11] I: Email: az.burgerz@gmail.com
[04.03.2016 23:05:11] I: All Rights Reserved
[04.03.2016 23:05:11] I: **************************************************
[04.03.2016 23:05:11] I: Welcome to jBART v3h build 20160106.07
[04.03.2016 23:05:11] I: **************************************************
[04.03.2016 23:05:11] I: Java version: 1.8.0_71
[04.03.2016 23:05:11] I: OS name: Windows 10
[04.03.2016 23:05:11] I: OS version: 10.0
[04.03.2016 23:05:11] I: OS arch: 64 bit
[04.03.2016 23:05:11] I: Home directory: D:\Xiaomi\jBART-master\
[04.03.2016 23:05:11] I: 
[04.03.2016 23:05:11] I: 
[04.03.2016 23:05:11] I: ******** Installing frameworks ********
[04.03.2016 23:05:11] I: **** Decompiling Smart Home 3.4.12 GR-EN-FR.apk ****
[04.03.2016 23:05:12] I: I: Loading resource table...
[04.03.2016 23:05:12] I: I: Decoding AndroidManifest.xml with resources...
[04.03.2016 23:05:12] I: I: Loading resource table from file: D:\Xiaomi\jBART-master\data\frameworks\1.apk
[04.03.2016 23:05:12] I: I: Package: com.xiaomi.smarthome (com.xiaomi.smarthome)
[04.03.2016 23:05:12] I: I: Regular manifest package...
[04.03.2016 23:05:12] I: I: Decoding file-resources...
[04.03.2016 23:05:21] I: I: Decoding values */* XMLs...
[04.03.2016 23:05:21] I: I: Copying raw classes.dex file...
[04.03.2016 23:05:22] I: I: Copying assets and libs...
[04.03.2016 23:05:22] I: I: Copying unknown files...
[04.03.2016 23:05:23] I: I: Copying original files...
[04.03.2016 23:05:23] I: Check for available patches...
[04.03.2016 23:05:23] I: Check for available NXT patches...
[04.03.2016 23:05:23] I: ******** Decompiling finished ********
[04.03.2016 23:05:23] I: Time elapsed: 0h 0m 11s 719ms

The difference is at these lines:
**[04.03.2016 23:05:22] I: I: Copying unknown files...
[04.03.2016 23:05:23] I: I: Copying original files...**

If I try to recompile after the file I get an error message
[04.03.2016 23:08:55] I: FRIDAY 04.03.2016 23:08:55
[04.03.2016 23:08:55] I: Copyright: 2012-2015, Andrei Zhukouski (BurgerZ)
[04.03.2016 23:08:55] I: www: http://burgerz.pro
[04.03.2016 23:08:55] I: Email: az.burgerz@gmail.com
[04.03.2016 23:08:55] I: All Rights Reserved
[04.03.2016 23:08:55] I: **************************************************
[04.03.2016 23:08:55] I: Welcome to jBART v3h build 20160106.07
[04.03.2016 23:08:55] I: **************************************************
[04.03.2016 23:08:55] I: Java version: 1.8.0_71
[04.03.2016 23:08:55] I: OS name: Windows 10
[04.03.2016 23:08:55] I: OS version: 10.0
[04.03.2016 23:08:55] I: OS arch: 64 bit
[04.03.2016 23:08:55] I: Home directory: D:\Xiaomi\jBART-master\
[04.03.2016 23:08:55] I: 
[04.03.2016 23:08:55] I: 
[04.03.2016 23:08:55] I: ******** Compiling file started ********
[04.03.2016 23:08:55] I: **** Compiling Mi Home_3.4.15.apk ****
[04.03.2016 23:08:55] W: Exception in thread "main" brut.androlib.AndrolibException: brut.directory.PathNotExist: apktool.yml
[04.03.2016 23:08:55] W: 	at brut.androlib.Androlib.readMetaFile(Androlib.java:263)
[04.03.2016 23:08:55] W: 	at brut.androlib.Androlib.build(Androlib.java:275)
[04.03.2016 23:08:55] W: 	at brut.androlib.Androlib.build(Androlib.java:268)
[04.03.2016 23:08:55] W: 	at brut.apktool.Main.cmdBuild(Main.java:252)
[04.03.2016 23:08:55] W: 	at brut.apktool.Main.main(Main.java:109)
[04.03.2016 23:08:55] W: Caused by: brut.directory.PathNotExist: apktool.yml
[04.03.2016 23:08:55] W: 	at brut.directory.AbstractDirectory.getFileInput(AbstractDirectory.java:105)
[04.03.2016 23:08:55] W: 	at brut.androlib.Androlib.readMetaFile(Androlib.java:258)
[04.03.2016 23:08:55] W: 	... 4 more
[04.03.2016 23:08:55] S: pro.burgerz.bart.core.exceptions.CompileException: pro.burgerz.bart.core.exceptions.ExecuteException: Could not exec (exit code = 1): [javaw, -Xms247m, -Xmx247m, -jar, D:\Xiaomi\jBART-master\data\tools\lib\apktool-3.0.9-bz-small.jar, b, D:\Xiaomi\jBART-master\Mi Home_3.4.15.apk.bzprj\decompiled\Mi Home_3.4.15.apk, -f, -c, -p, D:\Xiaomi\jBART-master\data\frameworks, -a, D:\Xiaomi\jBART-master\data\tools\win\aapt.exe, -o, D:\Xiaomi\jBART-master\Mi Home_3.4.15.apk.bzprj\compiled\Mi Home_3.4.15.apk]
[04.03.2016 23:08:55] I: Time elapsed: 0h 0m 0s 379ms

The first file can be downloaded from here to test it yourself:
https://www.mediafire.com/?v5ekk7pcjxj38kx

I found somewhere the upcoming 2.1.0 release. How do I add it?

**Comment by maddoctor** [comment]
I renamed the file so that it will have the name of the using apktool, but again I get errors...

Process log:
[04.03.2016 23:15:28] I: 
[04.03.2016 23:15:28] I: 
[04.03.2016 23:15:28] I: FRIDAY 04.03.2016 23:15:28
[04.03.2016 23:15:28] I: Copyright: 2012-2015, Andrei Zhukouski (BurgerZ)
[04.03.2016 23:15:28] I: www: http://burgerz.pro
[04.03.2016 23:15:28] I: Email: az.burgerz@gmail.com
[04.03.2016 23:15:28] I: All Rights Reserved
[04.03.2016 23:15:28] I: **************************************************
[04.03.2016 23:15:28] I: Welcome to jBART v3h build 20160106.07
[04.03.2016 23:15:28] I: **************************************************
[04.03.2016 23:15:28] I: Java version: 1.8.0_71
[04.03.2016 23:15:28] I: OS name: Windows 10
[04.03.2016 23:15:28] I: OS version: 10.0
[04.03.2016 23:15:28] I: OS arch: 64 bit
[04.03.2016 23:15:28] I: Home directory: D:\Xiaomi\jBART-master\
[04.03.2016 23:15:28] I: 
[04.03.2016 23:17:09] I: Loaded NXT patcher config: D:\Xiaomi\jBART-master\data\patches\nxt\ContactsProvider\T9.ptch
[04.03.2016 23:17:09] I: 
[04.03.2016 23:17:09] I: 
[04.03.2016 23:17:09] I: FRIDAY 04.03.2016 23:17:09
[04.03.2016 23:17:09] I: Copyright: 2012-2015, Andrei Zhukouski (BurgerZ)
[04.03.2016 23:17:09] I: www: http://burgerz.pro
[04.03.2016 23:17:09] I: Email: az.burgerz@gmail.com
[04.03.2016 23:17:09] I: All Rights Reserved
[04.03.2016 23:17:09] I: **************************************************
[04.03.2016 23:17:09] I: Welcome to jBART v3h build 20160106.07
[04.03.2016 23:17:09] I: **************************************************
[04.03.2016 23:17:09] I: Java version: 1.8.0_71
[04.03.2016 23:17:09] I: OS name: Windows 10
[04.03.2016 23:17:09] I: OS version: 10.0
[04.03.2016 23:17:09] I: OS arch: 64 bit
[04.03.2016 23:17:09] I: Home directory: D:\Xiaomi\jBART-master\
[04.03.2016 23:17:09] I: 
[04.03.2016 23:17:09] I: 
[04.03.2016 23:17:09] I: ******** Installing frameworks ********
[04.03.2016 23:17:10] I: **** Decompiling Mi Home_3.4.15.apk ****
[04.03.2016 23:17:10] I: File apktool.jar not found. Using apktool-3.0.9-bz-small.jar
[04.03.2016 23:17:10] I: I: Using Apktool 2.1.0-57a8eb-SNAPSHOT on Mi Home_3.4.15.apk
[04.03.2016 23:17:10] I: I: Loading resource table...
[04.03.2016 23:17:11] I: I: Decoding AndroidManifest.xml with resources...
[04.03.2016 23:17:11] I: I: Loading resource table from file: D:\Xiaomi\jBART-master\data\frameworks\1.apk
[04.03.2016 23:17:12] I: I: Regular manifest package...
[04.03.2016 23:17:12] I: I: Decoding file-resources...
[04.03.2016 23:17:19] I: I: Decoding values */* XMLs...
[04.03.2016 23:17:20] I: I: Copying raw classes.dex file...
[04.03.2016 23:17:20] I: I: Copying raw classes2.dex file...
[04.03.2016 23:17:20] I: I: Copying assets and libs...
[04.03.2016 23:17:21] W: Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: Error copying file: assets
[04.03.2016 23:17:21] W: 	at brut.androlib.Androlib.decodeRawFiles(Androlib.java:151)
[04.03.2016 23:17:21] W: 	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:155)
[04.03.2016 23:17:21] W: 	at brut.apktool.Main.cmdDecode(Main.java:163)
[04.03.2016 23:17:21] W: 	at brut.apktool.Main.main(Main.java:81)
[04.03.2016 23:17:21] W: Caused by: brut.directory.DirectoryException: Error copying file: assets
[04.03.2016 23:17:21] W: 	at brut.directory.DirUtil.copyToDir(DirUtil.java:91)
[04.03.2016 23:17:21] W: 	at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:207)
[04.03.2016 23:17:21] W: 	at brut.androlib.Androlib.decodeRawFiles(Androlib.java:142)
[04.03.2016 23:17:21] W: 	... 3 more
[04.03.2016 23:17:21] W: Caused by: brut.directory.DirectoryException: Error copying file: static/static.home.mi.com/app/shop/img?id=shop_02c7360b334e35457001998c7b08b75e.jpg
[04.03.2016 23:17:21] W: 	at brut.directory.DirUtil.copyToDir(DirUtil.java:88)
[04.03.2016 23:17:21] W: 	at brut.directory.DirUtil.copyToDir(DirUtil.java:61)
[04.03.2016 23:17:21] W: 	at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:197)
[04.03.2016 23:17:21] W: 	at brut.directory.DirUtil.copyToDir(DirUtil.java:77)
[04.03.2016 23:17:21] W: 	... 5 more
[04.03.2016 23:17:21] W: Caused by: java.io.FileNotFoundException: D:\Xiaomi\jBART-master\Mi Home_3.4.15.apk.bzprj\decompiled\Mi Home_3.4.15.apk\assets\static\static.home.mi.com\app\shop\img?id=shop_02c7360b334e35457001998c7b08b75e.jpg (The filename, directory name, or volume label syntax is incorrect)
[04.03.2016 23:17:21] W: 	at java.io.FileOutputStream.open0(Native Method)
[04.03.2016 23:17:21] W: 	at java.io.FileOutputStream.open(Unknown Source)
[04.03.2016 23:17:21] W: 	at java.io.FileOutputStream.<init>(Unknown Source)
[04.03.2016 23:17:21] W: 	at java.io.FileOutputStream.<init>(Unknown Source)
[04.03.2016 23:17:21] W: 	at brut.directory.DirUtil.copyToDir(DirUtil.java:84)
[04.03.2016 23:17:21] W: 	... 8 more
[04.03.2016 23:17:21] S: pro.burgerz.bart.core.exceptions.DecompileException: pro.burgerz.bart.core.exceptions.ExecuteException: Could not exec (exit code = 1): [javaw, -Xms247m, -Xmx247m, -jar, D:\Xiaomi\jBART-master\data\tools\lib\apktool-3.0.9-bz-small.jar, d, -f, -s, -p, D:\Xiaomi\jBART-master\data\frameworks, -o, D:\Xiaomi\jBART-master\Mi Home_3.4.15.apk.bzprj\decompiled\Mi Home_3.4.15.apk, D:\Google\Xiaomi\Mi Home\Smart Home\Mi Home_3.4.15.apk]
[04.03.2016 23:17:21] I: Time elapsed: 0h 0m 11s 324ms

**Comment by iBotPeaches** [comment]
Please use apktool directly for the purpose of Bug Reports. I trust Burgerz work, but bug reports should always use the native tool itself vs a wrapper.

**Comment by maddoctor** [comment]
Can you please write me with what command you decompiled the apk?

**Comment by iBotPeaches** [comment]
It was written in my first response to this bug report...

`apktool d filename.apk`

**Comment by maddoctor** [comment]
C:\>apktool d Mi.apk
Destination directory (C:\\Mi) already exists. Use -f switch if you want to overwrite it.

C:\>apktool d Mi.apk
I: Using Apktool 2.1.0-57a8eb-SNAPSHOT on Mi.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Maddoctor\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Copying assets and libs...
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: Error copying file: assets
        at brut.androlib.Androlib.decodeRawFiles(Androlib.java:151)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:155)
        at brut.apktool.Main.cmdDecode(Main.java:163)
        at brut.apktool.Main.main(Main.java:81)
Caused by: brut.directory.DirectoryException: Error copying file: assets
        at brut.directory.DirUtil.copyToDir(DirUtil.java:91)
        at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:207)
        at brut.androlib.Androlib.decodeRawFiles(Androlib.java:142)
        ... 3 more
Caused by: brut.directory.DirectoryException: Error copying file: static/static.home.mi.com/app/shop/img?id=shop_02c7360b334e35457001998c7b08b75e.jpg
        at brut.directory.DirUtil.copyToDir(DirUtil.java:88)
        at brut.directory.DirUtil.copyToDir(DirUtil.java:61)
        at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:197)
        at brut.directory.DirUtil.copyToDir(DirUtil.java:77)
        ... 5 more
Caused by: java.io.FileNotFoundException: Mi\assets\static\static.home.mi.com\app\shop\img?id=shop_02c7360b334e35457001998c7b08b75e.jpg (The filename, directory name, or volume label syntax is incorrect)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at brut.directory.DirUtil.copyToDir(DirUtil.java:84)
        ... 8 more

**Comment by maddoctor** [comment]
Well I did it as you told me, but as you see I get errors....

**Comment by BurgerZ** [comment]
I think I need to update apktool.jar to the latest official version (2.1.0-SNAPHOT) in my tool instead of my own to avoid such situations. I do not maintain my own version of apktool now, I'll try to support official apktool development process.
