### ISSUE TITLE
 Could not decode arsc file, Expected: 0x00000008, got: 0x00000000

### ISSUE THREAD

**Issue by galian123** [iBotPeaches/Apktool#1189]
Hi iBotPeaches,
I met one issue. I used latest apktool.jar v2.0.3 to install framework res apk. framework-res.apk is compiled on Android 6.0.1.
I pull framework-res.apk from my phone.
PS: apktool_2.0.3.jar works well on other apks.
the crash stack is as follows:
```
$ java -jar ../../apktool/apktool_2.0.3.jar if framework-res.apk
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:52)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:39)
        at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:599)
        at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:581)
        at brut.androlib.Androlib.installFramework(Androlib.java:683)
        at brut.apktool.Main.cmdInstallFramework(Main.java:240)
        at brut.apktool.Main.main(Main.java:87)
Caused by: java.io.IOException: Expected: 0x00000008, got: 0x00000000
        at brut.util.ExtDataInput.skipCheckShort(ExtDataInput.java:56)
        at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:282)
        at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:224)
        at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:212)
        at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:154)
        at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:116)
        at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:78)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
        ... 6 more
```
Thanks a lot:)

**Comment by iBotPeaches** [comment]
Duplicate - #1131
