### ISSUE TITLE
Missing a path in lateste snapshot

### ISSUE THREAD

**Issue by realtebo** [iBotPeaches/Apktool#1192]
I followed your guide to build from source.

then i succesfully decompiled an apk, but when trying to rebuild  ('b') I got
```

I: Using Apktool 2.1.0-ea2c82-SNAPSHOT
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.PathNotExist: apktool.yml
	at brut.androlib.Androlib.readMetaFile(Androlib.java:249)
	at brut.androlib.Androlib.build(Androlib.java:261)
	at brut.androlib.Androlib.build(Androlib.java:254)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.directory.PathNotExist: apktool.yml
	at brut.directory.AbstractDirectory.getFileInput(AbstractDirectory.java:105)
	at brut.androlib.Androlib.readMetaFile(Androlib.java:245)
	... 4 more

```

what am I doing wrong ?

**Comment by iBotPeaches** [comment]
Post the command you used to build this application.

**Comment by realtebo** [comment]
I'm under Linux, so I used instructions from here: http://ibotpeaches.github.io/Apktool/build/
```

git clone git://github.com/iBotPeaches/Apktool.git
cd Apktool
./gradlew build fatJar proguard


```

**Comment by realtebo** [comment]
The I installed the new apk compiled into /usr/local/bin

```
realtebo@realtebo-VirtualBox ~/Apktool/brut.apktool/apktool-cli/build/libs $ sudo cp apktool-2.1.0-ea2c82-SNAPSHOT-small.jar /usr/local/bin/apktool.jar
realtebo@realtebo-VirtualBox ~ $ cd apk/
realtebo@realtebo-VirtualBox ~/apk $ 
realtebo@realtebo-VirtualBox ~/apk $ sudo apktool if framework-res.apk 
I: Framework installed to: /root/apktool/framework/1.apk

realtebo@realtebo-VirtualBox ~/apk $ sudo apktool d framework-res.apk 
I: Using Apktool 2.1.0-ea2c82-SNAPSHOT on framework-res.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files..

realtebo@realtebo-VirtualBox ~/apk $ sudo apktool b framework-res.apk 
I: Using Apktool 2.1.0-ea2c82-SNAPSHOT
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.PathNotExist: apktool.yml
	at brut.androlib.Androlib.readMetaFile(Androlib.java:249)
	at brut.androlib.Androlib.build(Androlib.java:261)
	at brut.androlib.Androlib.build(Androlib.java:254)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.directory.PathNotExist: apktool.yml
	at brut.directory.AbstractDirectory.getFileInput(AbstractDirectory.java:105)
	at brut.androlib.Androlib.readMetaFile(Androlib.java:245)
	... 4 more

```
And this is the end of the story.

**Comment by iBotPeaches** [comment]
`apktool b framework-res`

**Comment by realtebo** [comment]
Without sudo I got 'permission denied'.... 

but using sudo .... 

```
realtebo@realtebo-VirtualBox ~/apk $ sudo apktool b framework-res
I: Using Apktool 2.1.0-ea2c82-SNAPSHOT
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
W: warning: string 'allow_button' has no default translation.
W: warning: string 'deny_button' has no default translation.
W: warning: string 'other_permissions' has no default translation.
W: warning: string 'permdesc_authenticateAccounts' has no default translation.
W: warning: string 'permdesc_clearAppCache' has no default translation.
W: warning: string 'permdesc_manageAccounts' has no default translation.
W: warning: string 'permdesc_manageAppTokens' has no default translation.
W: warning: string 'permdesc_setProcessLimit' has no default translation.
W: warning: string 'permdesc_shutdown' has no default translation.
W: warning: string 'permdesc_signalPersistentProcesses' has no default translation.
W: warning: string 'permgroupdesc_accounts' has no default translation.
W: warning: string 'permgrouplab_accounts' has no default translation.
W: warning: string 'permission_remember_choice' has no default translation.
W: warning: string 'permission_title' has no default translation.
W: warning: string 'permlab_authenticateAccounts' has no default translation.
W: warning: string 'permlab_bindPackageVerifier' has no default translation.
W: warning: string 'permlab_manageAccounts' has no default translation.
W: warning: string 'permlab_performCdmaProvisioning' has no default translation.
W: warning: string 'permlab_runSetActivityWatcher' has no default translation.
W: warning: string 'permlab_setProcessLimit' has no default translation.
W: warning: string 'permlab_useCredentials' has no default translation.
I: Building apk file...
I: Copying unknown files/dir...
```

**Comment by BurgerZ** [comment]
@realtebo There are no errors in your log

**Comment by realtebo** [comment]
@BurgerZ , @iBotPeaches : thanks a lot !

I was misusing the rebuild ('b') command at all: i was targeting an apk instead of a folder. Sorry for waste of time
