### ISSUE TITLE
Error copying unknown file

### ISSUE THREAD

**Issue by h4ng3r** [iBotPeaches/Apktool#1193]
```
I: Using Apktool 2.0.3 on XXXXXXX.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /root/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
Exception in thread "main" java.lang.NullPointerException
	at brut.util.OS.rmdir(OS.java:34)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:76)
	at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:207)
	at brut.androlib.Androlib.decodeUnknownFiles(Androlib.java:207)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:158)
	at brut.apktool.Main.cmdDecode(Main.java:165)
	at brut.apktool.Main.main(Main.java:81)
```

**Comment by iBotPeaches** [comment]
Could you provide apk? (Email (ibotpeaches) (at) gmail (dot) com) if its private).

These errors isolated to the Unknown Files usually are best handled with investigating the APK directly and then making a similar unit test.

**Comment by iBotPeaches** [comment]
Its definitely not rebuildable, but our changes to the Unknown File handler in 2.1.0 seems to have fixed this.

```
➜  Bug1193 apktool d base.apk 
I: Using Apktool 2.1.0-180728-SNAPSHOT on base.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1193 
```

Rebuilding dexguard apps falls under #1014 and #885
