### ISSUE TITLE
Error occurred while disassembling class

### ISSUE THREAD

**Issue by linhmui** [iBotPeaches/Apktool#1197]
### Information
1. **Apktool 2.0.3
2. Windows 8.1
3. **APK From Google Play

Error occurred while disassembling class Ltv.ouya.console.util.a; - skip
ss
org.jf.util.ExceptionWithContext: The last instruction in the method is
d
        at org.jf.dexlib2.dexbacked.DexBackedMethodImplementation$1$1.re
em(DexBackedMethodImplementation.java:87)
        at org.jf.dexlib2.dexbacked.DexBackedMethodImplementation$1$1.re
em(DexBackedMethodImplementation.java:75)
        at org.jf.dexlib2.dexbacked.util.VariableSizeLookaheadIterator.c
xt(VariableSizeLookaheadIterator.java:60)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(A
terator.java:143)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIt
ava:138)
        at com.google.common.collect.ImmutableCollection$Builder.addAll(
eCollection.java:300)
        at com.google.common.collect.ImmutableList$Builder.addAll(Immuta
java:691)
        at com.google.common.collect.ImmutableList.copyOf(ImmutableList.
)
        at com.google.common.collect.ImmutableList.copyOf(ImmutableList.
)
        at org.jf.baksmali.Adaptors.MethodDefinition.<init>(MethodDefini
a:92)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeDirectMethods(C
nition.java:281)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinit
:112)
        at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:225)
        at org.jf.baksmali.baksmali.access$000(baksmali.java:55)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:149)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:147)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Sou
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown So
        at java.lang.Thread.run(Unknown Source)
Error while processing method Ltv/ouya/console/util/a;->firstTime()V

I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
### APK
https://www.dropbox.com/s/iknso1d8w6wtsy3/legend.apk?dl=0

**Comment by iBotPeaches** [comment]
Hm. I've seen this error before trying to Deodex Android L (preview) APKs, but this is a Google Play application. Could you toss this stack trace over to smali? JF might have a better understanding than me.

See https://github.com/JesusFreke/smali/issues/269 & https://github.com/JesusFreke/smali/issues/287

**Comment by linhmui** [comment]
@iBotPeaches Thanks for your quick reply. What do your mean? when i run apktool d (apk file) it show many text like above, and when i see result of Apktool decode, it dont got full smali of apk code, Please try decode apk in my link: 
https://www.dropbox.com/s/iknso1d8w6wtsy3/legend.apk?dl=0

**Comment by iBotPeaches** [comment]
Nah, I'm aware, but that failure is smali and I don't  understand the internals of dex files enough, so I linked the bug reports I thought were related and you should try reporting this upstream to smali.

**Comment by marckevinflores** [comment]
I got that same problem i try to decompile services.odex
Do you have any solution to solve that

**Comment by marckevinflores** [comment]
but my phone is running in 4.4.2 and MTK6572

**Comment by iBotPeaches** [comment]
Perhaps MTK back ported some fixes that led to the issue? I'm not sure but I do know the EXACT stacktrace from the original report is something that cannot be fixed because it falls in the 5.0/5.1 pool.

You said you had "the same problem" so I grouped them into the same group. Feel free to open another issue following the template and including a stacktrace/apk and I can take another look.
