### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by tylerstyler123** [iBotPeaches/Apktool#1198]
### Information
1. **apktool_2.0.3** -
2. **Windows 10)** -
3. **S5 Active 

So I am having a problem recompiling a file, it is a stock email app off of my phone. I had a small issue decompiling it before, then I updated my framework file and it worked. I have  not made any changes yet. 
When I try to recompile i get this error every time. 

I: Using Apktool 2.0.3
I: Checking whether resources has changed...
I: Building resources...
Exception in thread "main" java.lang.NullPointerException
        at java.lang.ProcessBuilder.start(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at brut.util.OS.exec(OS.java:84)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:458)
        at brut.androlib.Androlib.buildResources(Androlib.java:410)
        at brut.androlib.Androlib.build(Androlib.java:298)
        at brut.androlib.Androlib.build(Androlib.java:268)
        at brut.apktool.Main.cmdBuild(Main.java:225)
        at brut.apktool.Main.main(Main.java:84)

**Comment by iBotPeaches** [comment]
This looks like the internal binary (aapt) was not found. Almost like its missing from the application. I would check this bug report, maybe you have the old Windows Defender or this has regressed. - https://github.com/iBotPeaches/Apktool/issues/1054
