### ISSUE TITLE
Errors after just decode and rebuild a framework-res.apk 

### ISSUE THREAD

**Issue by aleksander0m** [iBotPeaches/Apktool#1200]
I'd like to update a framework-res.apk, but it looks like that just decoding and rebuilding the APK itself is problematic, without even updating anything myself. The tablet (Samsung Galaxy Tab 4 10.1, lollipop) boots with my updated framework-res.apk, but then several different applications will crash (like Settings, see below).

This looks suspicious:

```
Resources$NotFoundException: Resource "android:drawable/APKTOOL_DUMMY_ad1" (1080ad1)  is not a Drawable (color or path): TypedValue{t=0x12/d=0x0 a=1 r=0x1080ad1}
```
### Information
1. **Apktool Version (`apktool -version`)** - 2.1.0-a7535f-SNAPSHOT
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - Samsung tablet, original framework-res.apk.
### Stacktrace/Logcat

```
E/AndroidRuntime( 1982): FATAL EXCEPTION: main
E/AndroidRuntime( 1982): Process: com.android.settings, PID: 1982
E/AndroidRuntime( 1982): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.android.settings.Settings}: android.view.InflateException: Binary XML file line #7: Error inflating class android.widget.ListView
E/AndroidRuntime( 1982):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2802)
E/AndroidRuntime( 1982):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2867)
E/AndroidRuntime( 1982):        at android.app.ActivityThread.access$900(ActivityThread.java:181)
E/AndroidRuntime( 1982):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1476)
E/AndroidRuntime( 1982):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 1982):        at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime( 1982):        at android.app.ActivityThread.main(ActivityThread.java:6134)
E/AndroidRuntime( 1982):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 1982):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 1982):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
E/AndroidRuntime( 1982):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
E/AndroidRuntime( 1982): Caused by: android.view.InflateException: Binary XML file line #7: Error inflating class android.widget.ListView
E/AndroidRuntime( 1982):        at android.view.LayoutInflater.createView(LayoutInflater.java:640)
E/AndroidRuntime( 1982):        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
E/AndroidRuntime( 1982):        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:689)
E/AndroidRuntime( 1982):        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:748)
E/AndroidRuntime( 1982):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
E/AndroidRuntime( 1982):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
E/AndroidRuntime( 1982):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
E/AndroidRuntime( 1982):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
E/AndroidRuntime( 1982):        at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
E/AndroidRuntime( 1982):        at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
E/AndroidRuntime( 1982):        at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
E/AndroidRuntime( 1982):        at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:449)
E/AndroidRuntime( 1982):        at android.app.Activity.setContentView(Activity.java:2278)
E/AndroidRuntime( 1982):        at android.preference.PreferenceActivity.onCreate(PreferenceActivity.java:731)
E/AndroidRuntime( 1982):        at com.android.settings.SettingsActivity.onCreateTablet(SettingsActivity.java:2916)
E/AndroidRuntime( 1982):        at com.android.settings.SettingsActivity.onCreate(SettingsActivity.java:1606)
E/AndroidRuntime( 1982):        at android.app.Activity.performCreate(Activity.java:6374)
E/AndroidRuntime( 1982):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
E/AndroidRuntime( 1982):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
E/AndroidRuntime( 1982):        ... 10 more
E/AndroidRuntime( 1982): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime( 1982):        at java.lang.reflect.Constructor.newInstance(Native Method)
E/AndroidRuntime( 1982):        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
E/AndroidRuntime( 1982):        at android.view.LayoutInflater.createView(LayoutInflater.java:614)
E/AndroidRuntime( 1982):        ... 28 more
E/AndroidRuntime( 1982): Caused by: android.content.res.Resources$NotFoundException: Resource "android:drawable/APKTOOL_DUMMY_ad1" (1080ad1)  is not a Drawable (color or path): TypedValue{t=0x12/d=0x0 a=1 r=0x1080ad1}
E/AndroidRuntime( 1982):        at android.content.res.Resources.loadDrawableForCookie(Resources.java:3739)
E/AndroidRuntime( 1982):        at android.content.res.Resources.loadDrawable(Resources.java:3651)
E/AndroidRuntime( 1982):        at android.content.res.Resources.getDrawable(Resources.java:1865)
E/AndroidRuntime( 1982):        at android.content.res.Resources.getDrawable(Resources.java:1831)
E/AndroidRuntime( 1982):        at android.widget.AbsListView.initAbsListView(AbsListView.java:1233)
E/AndroidRuntime( 1982):        at android.widget.AbsListView.<init>(AbsListView.java:1130)
E/AndroidRuntime( 1982):        at android.widget.ListView.<init>(ListView.java:164)
E/AndroidRuntime( 1982):        at android.widget.ListView.<init>(ListView.java:160)
E/AndroidRuntime( 1982):        at android.widget.ListView.<init>(ListView.java:156)
E/AndroidRuntime( 1982):        ... 31 more
W/ActivityManager( 1075):   Force finishing activity com.android.settings/.Settings
```
### Steps to Reproduce
1. `apktool decode --no-src --output tmp framework-res.orig.apk`
2. `apktool build --copy-original --output framework-res.apk tmp`
### Frameworks

If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)
[framework-res.orig.apk.zip](https://github.com/iBotPeaches/Apktool/files/185756/framework-res.orig.apk.zip)
### APK

If this APK can be freely shared, please upload/attach a link to it.

It is the framework apk the one I want to update. 
### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
   That's what doesn't work.
2. If you are trying to install a modified apk, did you resign it?
   No, but I used `--copy-original` to keep the AndroidManifest and previous signature.
3. Are you using the latest apktool version?
   Yes, from git, as of today.

**Comment by aleksander0m** [comment]
```
$ grep -r "APKTOOL_DUMMY_ad1" tmp/
tmp/res/values/styles.xml:        <item name="twListMultiSelectBackground">@drawable/APKTOOL_DUMMY_ad1</item>
tmp/res/values/public.xml:    <public type="drawable" name="APKTOOL_DUMMY_ad1" id="0x01080ad1" />
tmp/res/values-nodpi-v4/drawables.xml:    <item type="drawable" name="APKTOOL_DUMMY_ad1">false</item>
```

**Comment by iBotPeaches** [comment]
```
➜  Bug1200 aapt d resources framework-res.orig.apk | grep 'CONFIG'
      INVALID TYPE CONFIG FOR RESOURCE 0x0105020b
      INVALID TYPE CONFIG FOR RESOURCE 0x0105020c
      INVALID TYPE CONFIG FOR RESOURCE 0x0105020d
      INVALID TYPE CONFIG FOR RESOURCE 0x0105020e
      INVALID TYPE CONFIG FOR RESOURCE 0x0105020f
      INVALID TYPE CONFIG FOR RESOURCE 0x01050210
      INVALID TYPE CONFIG FOR RESOURCE 0x01050211
      INVALID TYPE CONFIG FOR RESOURCE 0x01050212
      INVALID TYPE CONFIG FOR RESOURCE 0x01050213
      INVALID TYPE CONFIG FOR RESOURCE 0x01050214
      INVALID TYPE CONFIG FOR RESOURCE 0x01050215
      ... 50ish more
```

Apktool cannot create a resource if it doesn't know its type, which as you can see happens for a lot of resources. The true cause or reason for this is still unknown to me, but its been around for awhile.

Apktool to allow recompilation inserts dummy attributes with the resource ids of those invalid type resources. This fixes compilation, but if those resources were suppose to be a type like (`drawable`), then the application will fail because the dummy attributes are of the correct type, but simply a boolean value. 

So the next question is logically, "how did it know resource `0x01080ad1` is a `drawable` when it said `INVALID TYPE CONFIG FOR RESOURCE 0x01080AD1`. Well thats a good question that I haven't quite figured out.

I think there is already an open bug for this, but I can't find it. So will keep this open for now.

**Comment by iBotPeaches** [comment]
The next release properly matches type to dummy resources instead of making them booleans.
