### ISSUE TITLE
Re-compile error: "input directory '7z' does not exist"

### ISSUE THREAD

**Issue by evildog1** [iBotPeaches/Apktool#1202]
### Information
1. **Apktool Version:** 2.0.3
2. **Operating System:** Windows
3. **APK From?** Other

### Stacktrace/Logcat
```
I: Using Apktool 2.0.3
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
ERROR: input directory '7z' does not exist
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\Users\quocd\AppData\Local\Temp\brut_util_Jar_1572986843158093019.tmp, p, --forced-package-id, 127, --min-sdk-version, 8, --target-sdk-version, 16, --version-code, 652170, --version-name, 6.5.0.2170, -F, C:\Users\quocd\AppData\Local\Temp\APKTOOL8834988971384276643.tmp, -0, conf, -0, ini, -0, , -0, 7z, -0, arsc, -I, C:\Users\quocd\apktool\framework\1.apk, -S, F:\APK Easy Tool\Decompiled APKs\qqbrowser_6.5.0.2170_20820.apk\res, -M, F:\APK Easy Tool\Decompiled APKs\qqbrowser_6.5.0.2170_20820.apk\AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:472)
	at brut.androlib.Androlib.buildResources(Androlib.java:410)
	at brut.androlib.Androlib.build(Androlib.java:298)
	at brut.androlib.Androlib.build(Androlib.java:268)
	at brut.apktool.Main.cmdBuild(Main.java:225)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\Users\quocd\AppData\Local\Temp\brut_util_Jar_1572986843158093019.tmp, p, --forced-package-id, 127, --min-sdk-version, 8, --target-sdk-version, 16, --version-code, 652170, --version-name, 6.5.0.2170, -F, C:\Users\quocd\AppData\Local\Temp\APKTOOL8834988971384276643.tmp, -0, conf, -0, ini, -0, , -0, 7z, -0, arsc, -I, C:\Users\quocd\apktool\framework\1.apk, -S, F:\APK Easy Tool\Decompiled APKs\qqbrowser_6.5.0.2170_20820.apk\res, -M, F:\APK Easy Tool\Decompiled APKs\qqbrowser_6.5.0.2170_20820.apk\AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:425)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:458)
	... 5 more
Caused by: brut.common.BrutException: could not exec command: [C:\Users\quocd\AppData\Local\Temp\brut_util_Jar_1572986843158093019.tmp, p, --forced-package-id, 127, --min-sdk-version, 8, --target-sdk-version, 16, --version-code, 652170, --version-name, 6.5.0.2170, -F, C:\Users\quocd\AppData\Local\Temp\APKTOOL8834988971384276643.tmp, -0, conf, -0, ini, -0, , -0, 7z, -0, arsc, -I, C:\Users\quocd\apktool\framework\1.apk, -S, F:\APK Easy Tool\Decompiled APKs\qqbrowser_6.5.0.2170_20820.apk\res, -M, F:\APK Easy Tool\Decompiled APKs\qqbrowser_6.5.0.2170_20820.apk\AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:89)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)
	... 6 more
```

### Steps to Reproduce
1. Place the APK file at the same place where apktool.jar is located
2. Decompile the APK: java -jar apktool.jar d qqbrowser.apk
3. Don't change anything. Recompile the APK: java -jar apktool.jar b qqbrowser qqnew.apk

### Frameworks
Framework-res from my Sony Xperia Z3 Compact
[framework-res.zip](https://github.com/iBotPeaches/Apktool/files/186169/framework-res.zip)

### APK
[qqbrowser.zip](https://github.com/iBotPeaches/Apktool/files/186163/qqbrowser.zip)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? **Yes**
2. If you are trying to install a modified apk, did you resign it? **(not answerable)**
3. Are you using the latest apktool version? **Yes**

**Comment by iBotPeaches** [comment]
```
➜  Bug1202 apktool d qqbrowser.apk 
I: Using Apktool 2.1.0-5c7702-SNAPSHOT on qqbrowser.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1202 apktool b qqbrowser
I: Using Apktool 2.1.0-5c7702-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
➜  Bug1202 
```

Fixed here https://github.com/iBotPeaches/Apktool/commit/22bd5b0acc15abf9405028f473a7f14e3e16e954 - Fix in upcoming 2.1.0 release.
