### ISSUE TITLE
LG StartupWizard request for framework id: 3

### ISSUE THREAD

**Issue by Eduardgur** [iBotPeaches/Apktool#1210]
### Information
1. **Apktool Version (`apktool -version`)** - Any
2. **Operating System (Mac, Linux, Windows)** - Windows 10
3. **APK From? (Playstore, ROM, Other)** - Stock Rom

I get the error with any apktool version on any LGStartupWizard.apk after the D855 got to the market .
On the decompile stage I asked for framework id: 3. I tried every single apk in the system and non work.

`Exception in thread "main" brut.androlib.AndrolibException: Expected pkg of id: 3, got: 1
	at brut.androlib.res.AndrolibResources.loadFrameworkPkg(AndrolibResources.java:136)
	at brut.androlib.res.data.ResTable.getPackage(ResTable.java:83)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:66)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:62)
	at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferenceValue.java:57)
	at brut.androlib.res.data.value.ResReferenceValue.encodeAsResXml(ResReferenceValue.java:47)
	at brut.androlib.res.data.value.ResScalarValue.encodeAsResXmlAttr(ResScalarValue.java:46)
	at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:49)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:507)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:261)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:128)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:106)
	at brut.apktool.Main.cmdDecode(Main.java:163)
	at brut.apktool.Main.main(Main.java:81)
`

**Comment by iBotPeaches** [comment]
In the terms of MIUI which additionally had a missing framework, it was hiding among `/system/app` like a regular application. 

Either way, a missing framework is not a bug in apktool.

**Comment by Eduardgur** [comment]
Ok sorry, the problem is Ive tried every apk in /app any other way to find
the framework ?

*גורמן אדוארד | מנהל מעבדה ותחום טכני | בלאק קיוב בע"מ*
*Eduard.Gur@gmail.com <Eduard.Gur@gmail.com>*


2016-03-26 15:14 GMT+03:00 Connor Tumbleson <notifications@github.com>:
