### ISSUE TITLE
DirectoryException for resources with unicode characters in the file name

### ISSUE THREAD

**Issue by salamandra16** [iBotPeaches/Apktool#1214]
### Information
1. **Apktool Version 2.0.3
2. **Operating System Windows
3. **APK From? Other

### Stacktrace/Logcat
```
I: Using Apktool 2.0.3 on test.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\novikov\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: Error copying file: ♂ΓÇè .xml
        at brut.androlib.Androlib.decodeUnknownFiles(Androlib.java:214)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:158)
        at brut.apktool.Main.cmdDecode(Main.java:165)
        at brut.apktool.Main.main(Main.java:81)
Caused by: brut.directory.DirectoryException: Error copying file: ♂ΓÇè  .xml
        at brut.directory.DirUtil.copyToDir(DirUtil.java:88)
        at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:207)
        at brut.androlib.Androlib.decodeUnknownFiles(Androlib.java:207)
        ... 3 more
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `
java -jar C:\apk\apktool.jar d C:\test.apk
### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. Are you using the latest apktool version?
The latest that works. 2.1.0 does not work also on Linux OS in addition to Windows

**Comment by iBotPeaches** [comment]
Could you try with 2.1.0? There were major changes to how unknown files are handled.

**Comment by iBotPeaches** [comment]
This seems like a charset issue on Windows. While the original APK wasn't provided, I took a similar Proguard application and decoded it on Windows without trouble.

We can revisit if an APK is provided.
