### ISSUE TITLE
[URGENT] IDK THE REASON! PLZ HELP!

### ISSUE THREAD

**Issue by Unknown-Peach** [iBotPeaches/Apktool#1215]
APKTOOL VERSION: 2.1.0
APK LINK:[https://www.dropbox.com/home?preview=TheApk.apk](url)

> I DONT KNOW THE REASON? CAN ANYONE HELP? REQUEST AND THX

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.
```
C:\Users\vivek\Videos\Chatware\ApkTool\apktool>apktool b 1
I: Using Apktool 2.1.0
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: warning: string 'ActionChannelChangedPhoto' has no default translation.
W: warning: string 'ActionChannelChangedTitle' has no default translation.
W: warning: string 'ActionChannelInvite' has no default translation.
W: warning: string 'ActionChannelRemovedPhoto' has no default translation.
W: warning: string 'ActionCreateChannel' has no default translation.
W: warning: string 'AddContactChat' has no default translation.
W: warning: string 'AddMutual' has no default translation.
W: warning: string 'ChannelAddAdmin' has no default translation.
W: warning: string 'ChannelAddMembers' has no default translation.
W: warning: string 'ChannelAddTo' has no default translation.
W: warning: string 'ChannelAddToTitle' has no default translation.
W: warning: string 'ChannelAddUserAdminAlert' has no default translation.
W: warning: string 'ChannelAddedBy' has no default translation.
W: warning: string 'ChannelAdminNotParticipant' has no default translation.
W: warning: string 'ChannelAdministrators' has no default translation.
W: warning: string 'ChannelAdminsInfo' has no default translation.
W: warning: string 'ChannelAlertCreate' has no default translation.
W: warning: string 'ChannelAlertText' has no default translation.
W: warning: string 'ChannelAlertTitle' has no default translation.
W: warning: string 'ChannelBlockedUsers' has no default translation.
W: warning: string 'ChannelBroadcast' has no default translation.
W: warning: string 'ChannelCantOpenPrivate' has no default translation.
W: warning: string 'ChannelCantSendMessage' has no default translation.
W: warning: string 'ChannelComment' has no default translation.
W: warning: string 'ChannelCreator' has no default translation.
W: warning: string 'ChannelDelete' has no default translation.
W: warning: string 'ChannelDeleteAlert' has no default translation.
W: warning: string 'ChannelDeleteInfo' has no default translation.
W: warning: string 'ChannelEdit' has no default translation.
W: warning: string 'ChannelEditor' has no default translation.
W: warning: string 'ChannelInviteLinkTitle' has no default translation.
W: warning: string 'ChannelInviteViaLink' has no default translation.
W: warning: string 'ChannelJoin' has no default translation.
W: warning: string 'ChannelJoinTo' has no default translation.
W: warning: string 'ChannelLinkInfo' has no default translation.
W: warning: string 'ChannelLinkTitle' has no default translation.
W: warning: string 'ChannelMembers' has no default translation.
W: warning: string 'ChannelMembersInfo' has no default translation.
W: warning: string 'ChannelModerator' has no default translation.
W: warning: string 'ChannelMute' has no default translation.
W: warning: string 'ChannelPrivate' has no default translation.
W: warning: string 'ChannelPrivateInfo' has no default translation.
W: warning: string 'ChannelPrivateLinkHelp' has no default translation.
W: warning: string 'ChannelPublic' has no default translation.
W: warning: string 'ChannelPublicEmptyUsername' has no default translation.
W: warning: string 'ChannelPublicInfo' has no default translation.
W: warning: string 'ChannelPublicLimitReached' has no default translation.
W: warning: string 'ChannelRemoveUser' has no default translation.
W: warning: string 'ChannelRemoveUserAdmin' has no default translation.
W: warning: string 'ChannelSettings' has no default translation.
W: warning: string 'ChannelUnmute' has no default translation.
W: warning: string 'ChannelUserAddLimit' has no default translation.
W: warning: string 'ChannelUserCantAdd' has no default translation.
W: warning: string 'ChannelUserLeftError' has no default translation.
W: warning: string 'ChannelUsernameHelp' has no default translation.
W: warning: string 'ChannelUsernamePlaceholder' has no default translation.
W: warning: string 'ChannelWasPrivateAlert' has no default translation.
W: warning: string 'Comments' has no default translation.
W: warning: string 'CommentsInfo' has no default translation.
W: warning: string 'DescriptionInfo' has no default translation.
W: warning: string 'DescriptionPlaceholder' has no default translation.
W: warning: string 'EnterChannelName' has no default translation.
W: warning: string 'LeaveChannel' has no default translation.
W: warning: string 'LinkAvailable' has no default translation.
W: warning: string 'LinkChecking' has no default translation.
W: warning: string 'LinkInUse' has no default translation.
W: warning: string 'LinkInvalid' has no default translation.
W: warning: string 'LinkInvalidLong' has no default translation.
W: warning: string 'LinkInvalidShort' has no default translation.
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.Androl
ibException: brut.common.BrutException: could not exec (exit code = 1): [C:\User
s\vivek\AppData\Local\Temp\brut_util_Jar_7958093092483383730.tmp, p, --forced-pa
ckage-id, 127, --min-sdk-version, 9, --target-sdk-version, 22, --version-code, 1
459492241, --version-name, 1.05, -F, C:\Users\vivek\AppData\Local\Temp\APKTOOL90
98644478350717568.tmp, -0, arsc, -0, arsc, -I, C:\Users\vivek\apktool\framework\
1.apk, -S, C:\Users\vivek\Videos\Chatware\ApkTool\apktool\1\res, -M, C:\Users\vi
vek\Videos\Chatware\ApkTool\apktool\1\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:433)
        at brut.androlib.Androlib.buildResources(Androlib.java:371)
        at brut.androlib.Androlib.build(Androlib.java:281)
        at brut.androlib.Androlib.build(Androlib.java:254)
        at brut.apktool.Main.cmdBuild(Main.java:224)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not
 exec (exit code = 1): [C:\Users\vivek\AppData\Local\Temp\brut_util_Jar_79580930
92483383730.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk
-version, 22, --version-code, 1459492241, --version-name, 1.05, -F, C:\Users\viv
ek\AppData\Local\Temp\APKTOOL9098644478350717568.tmp, -0, arsc, -0, arsc, -I, C:
\Users\vivek\apktool\framework\1.apk, -S, C:\Users\vivek\Videos\Chatware\ApkTool
\apktool\1\res, -M, C:\Users\vivek\Videos\Chatware\ApkTool\apktool\1\AndroidMani
fest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.jav
a:433)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:419)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\
vivek\AppData\Local\Temp\brut_util_Jar_7958093092483383730.tmp, p, --forced-pack
age-id, 127, --min-sdk-version, 9, --target-sdk-version, 22, --version-code, 145
9492241, --version-name, 1.05, -F, C:\Users\vivek\AppData\Local\Temp\APKTOOL9098
644478350717568.tmp, -0, arsc, -0, arsc, -I, C:\Users\vivek\apktool\framework\1.
apk, -S, C:\Users\vivek\Videos\Chatware\ApkTool\apktool\1\res, -M, C:\Users\vive
k\Videos\Chatware\ApkTool\apktool\1\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.jav
a:427)
        ... 6 more
W: warning: string 'LinkInvalidStartNumber' has no default translation.
W: warning: string 'MoreInfo' has no default translation.
W: warning: string 'NewChannel' has no default translation.
W: warning: string 'NobodyLikesSpam1' has no default translation.
W: warning: string 'NobodyLikesSpam2' has no default translation.
W: warning: string 'OpenChannelProfile' has no default translation.
W: warning: string 'ReportSpam' has no default translation.
W: warning: string 'ReportSpamAlert' has no default translation.
W: warning: string 'ReportSpamAlertGroup' has no default translation.
W: warning: string 'ShowDiscussion' has no default translation.
W: warning: string 'comments_few' has no default translation.
W: warning: string 'comments_many' has no default translation.
W: warning: string 'comments_one' has no default translation.
W: warning: string 'comments_other' has no default translation.
W: warning: string 'comments_two' has no default translation.
W: warning: string 'comments_zero' has no default translation.
W: warning: string 'updateBuild' has no default translation.
W: warning: string 'updateText' has no default translation.
W: Failed to generate resource table for split ''
W: C:\Users\vivek\Videos\Chatware\ApkTool\apktool\1\res\values-v21\styles.xml:30
: error: Error: Color types not allowed (at 'android:borderRight' with value '#f
f54759e').
W:
```
C:\Users\vivek\Videos\Chatware\ApkTool\apktool>

**Comment by iBotPeaches** [comment]
```
Error: Color types not allowed (at 'android:borderRight' with value '#ff54759e')
```

Some colors will only take references via `@color` instead of a literal color. I believe you found one, as AAPT becomes more restrictive and errors out on these you will discover them. 

This is not a bug.
