### ISSUE TITLE
apktool 2.1.0 recompiling errors

### ISSUE THREAD

**Issue by hxrofo** [iBotPeaches/Apktool#1216]
### Information
1. **Apktool Version: 2.1.0
2. **Operating System: Kali Linux
3. **APK From: Play store (facebook app)
Link: https://play.google.com/store/apps/details?id=com.facebook.katana&hl=en
P.S: tried different apps from google play, same errors

### Stacktrace/Logcat
root@kali:~/apktool# java -jar apktool.jar b -o test.apk facebook
I: Using Apktool 2.1.0
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: /tmp/brut_util_Jar_3296692393869994056.tmp: error while loading shared libraries: libgcc_s.so.1: cannot open shared object file: No such file or directory
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 127): [/tmp/brut_util_Jar_3296692393869994056.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 23, --version-code, 18971686, --version-name, 58.0.0.28.70, -F, /tmp/APKTOOL8749237186933601936.tmp, -0, FBSIG, -0, xzs, -0, arsc, -I, /root/apktool/framework/1.apk, -S, /root/apktool/facebook/res, -M, /root/apktool/facebook/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:433)
	at brut.androlib.Androlib.buildResources(Androlib.java:371)
	at brut.androlib.Androlib.build(Androlib.java:281)
	at brut.androlib.Androlib.build(Androlib.java:254)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 127): [/tmp/brut_util_Jar_3296692393869994056.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 23, --version-code, 18971686, --version-name, 58.0.0.28.70, -F, /tmp/APKTOOL8749237186933601936.tmp, -0, FBSIG, -0, xzs, -0, arsc, -I, /root/apktool/framework/1.apk, -S, /root/apktool/facebook/res, -M, /root/apktool/facebook/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:433)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:419)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 127): [/tmp/brut_util_Jar_3296692393869994056.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 23, --version-code, 18971686, --version-name, 58.0.0.28.70, -F, /tmp/APKTOOL8749237186933601936.tmp, -0, FBSIG, -0, xzs, -0, arsc, -I, /root/apktool/framework/1.apk, -S, /root/apktool/facebook/res, -M, /root/apktool/facebook/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:427)
	... 6 more
```
### Steps to Reproduce
1) cd /root/apktool/
files in the folder:
apktool.jar
aapt
facebook.apk
virus.apk
sign.jar
2) chmod +x apktool.jar
chmod +x aapt
3) decompiling facebook.apk and virus.apk
java -jar apktool.jar d facebook.apk
java -jar apktool.jar d virus.apk
===> NO ERRORS, LOOKS GOOD
4) copied the necessary files from virus to facebook/smali/com/ and edited AndroidManifest.xml of facebook
===> no problem
5) Re-compiling facebook:
java -jar apktool.jar b -o facebook2.apk facebook
===> ERRORS AS SEEN IN THE LOG ABOVE
P.S: tried older versions of apktool.jar
       tried more than 2 aapt
       tried the default apktool installed in kali linux, with android-sdk installed

java -version
java version "1.7.0_91"
OpenJDK Runtime Environment (IcedTea 2.6.3) (7u91-2.6.3-1)
OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)

java path variable set correctly, no problem.
### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
  ===> YES I DID, decompiled facebook.apk and tried recompiling it AS IT IS, but got the same errors
2. Are you using the latest apktool version?
===> YES I AM. 
https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.1.0.jar

Thanks for helping me out

**Comment by BurgerZ** [comment]
> error while loading shared libraries: libgcc_s.so.1: cannot open shared object file: No such file or directory
Just open terminal and issue:
`sudo apt-get install lib32stdc++6`

**Comment by hxrofo** [comment]
@BurgerZ thanks mate. it works now, but i did apt-get install gcc-multilib.
Problem solved
thanks again

**Comment by BurgerZ** [comment]
@hxrofo Installing such packages like gcc-multilib is not good idea as it will also install a lot of useless dependencies, a lot.

**Comment by hxrofo** [comment]
@BurgerZ thanks. i took your advice and removed gcc-multilib and installed just lib32z1-dev, because the other two libs are already installed.
