### ISSUE TITLE
Decode and rebuild does not work no changes.

### ISSUE THREAD

**Issue by Josenzo** [iBotPeaches/Apktool#1218]
### Information
1. 2.1.0
2. Mac
3. http://www.apk4fun.com/apk/1114/ Pinterest 5.12.1

The pinterest apk 5.12.1 can't be rebuilded/compiled after decode. Without any change. Just decode and build.

```
$ apktool build com.pinterest-5.12.1-APK4Fun.com/ -o pinterest.ap
I: Using Apktool 2.1.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether resources has changed...
I: Building resources...
W: /Users/enzo/src/elevenyellow/pinterest/hacking/com.pinterest-5.12.1-APK4Fun.com/res/values-v23/styles.xml:5: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/WindowTitle'.
W: 
W: /Users/enzo/src/elevenyellow/pinterest/hacking/com.pinterest-5.12.1-APK4Fun.com/res/values-v23/styles.xml:6: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/WindowTitleBackground'.
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/nq/48fs7w791mz9q_h0xgxmxw380000gn/T/brut_util_Jar_5273555467037361335.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 23, --version-code, 51202, --version-name, 5.12.1, -F, /var/folders/nq/48fs7w791mz9q_h0xgxmxw380000gn/T/APKTOOL8096602686341509278.tmp, -0, arsc, -0, enc, -0, arsc, -I, /Users/enzo/Library/apktool/framework/1.apk, -S, /Users/enzo/src/elevenyellow/pinterest/hacking/com.pinterest-5.12.1-APK4Fun.com/res, -M, /Users/enzo/src/elevenyellow/pinterest/hacking/com.pinterest-5.12.1-APK4Fun.com/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:433)
	at brut.androlib.Androlib.buildResources(Androlib.java:371)
	at brut.androlib.Androlib.build(Androlib.java:281)
	at brut.androlib.Androlib.build(Androlib.java:254)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/nq/48fs7w791mz9q_h0xgxmxw380000gn/T/brut_util_Jar_5273555467037361335.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 23, --version-code, 51202, --version-name, 5.12.1, -F, /var/folders/nq/48fs7w791mz9q_h0xgxmxw380000gn/T/APKTOOL8096602686341509278.tmp, -0, arsc, -0, enc, -0, arsc, -I, /Users/enzo/Library/apktool/framework/1.apk, -S, /Users/enzo/src/elevenyellow/pinterest/hacking/com.pinterest-5.12.1-APK4Fun.com/res, -M, /Users/enzo/src/elevenyellow/pinterest/hacking/com.pinterest-5.12.1-APK4Fun.com/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:433)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:419)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/nq/48fs7w791mz9q_h0xgxmxw380000gn/T/brut_util_Jar_5273555467037361335.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 23, --version-code, 51202, --version-name, 5.12.1, -F, /var/folders/nq/48fs7w791mz9q_h0xgxmxw380000gn/T/APKTOOL8096602686341509278.tmp, -0, arsc, -0, enc, -0, arsc, -I, /Users/enzo/Library/apktool/framework/1.apk, -S, /Users/enzo/src/elevenyellow/pinterest/hacking/com.pinterest-5.12.1-APK4Fun.com/res, -M, /Users/enzo/src/elevenyellow/pinterest/hacking/com.pinterest-5.12.1-APK4Fun.com/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:427)
	... 6 more
```

**Comment by iBotPeaches** [comment]
```
➜  Downloads apktool b com.pinterest-5.12.1-www.APK4Fun.com
I: Using Apktool 2.0.3
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
```

Could not duplicate. Check your frameworks. Looks like a framework problem. You can remove the file at `$HOME/apktool/framework/1.apk` and try again.
