### ISSUE TITLE
Compatibility with old KitKat aapt

### ISSUE THREAD

**Issue by Hikari-no-Tenshi** [iBotPeaches/Apktool#1221]
1. Apktool Version: 2.0.3 and up.
2. Operating System Windows
3. APK From: MiUI7 android 4.4.2

Commit https://github.com/iBotPeaches/Apktool/commit/eabb7d819b9a13f256153a174b8dd05e21c619f1 broke compatibility with old KitKat aapt.

Latest aapt doesn't work good for MiUI7 based on android 4.4.2. I've compiled custom aapt from AOSP 4.4.4 source code that was working fine on apktool 2.0.2 and below.

For example, with original apktool and aapt on recompilation of mediatek-res.apk i get lots of errors:
`error: Error: No resource found that matches the given name (at 'id' with value '@id/bookmarkCoverflow').`

With custom aapt i just get error:
```
[*] Рекомпіляція mediatek-res
I: Using Apktool 2.1.0
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = -1073741819): [C:\Users\Serhij\AppData\Local\Temp\BAT_temp\brut_util_Jar_2821555928312825099.tmp, p, --forced-package-id, 2, --min-sdk-version, 19, --target-sdk-version, 19, --version-code, 19, --version-name, 4.4.2, -F, C:\Users\Serhij\AppData\Local\Temp\BAT_temp\APKTOOL6951576291834491888.tmp, -x, -0, arsc, -0, db, -0, arsc, -I, .\framework\1.apk, -S, C:\BatchApkToolMod\bin\..\_INPUT_APK-miui\mediatek-res\res, -M, C:\BatchApkToolMod\bin\..\_INPUT_APK-miui\mediatek-res\AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:433)
	at brut.androlib.Androlib.buildResources(Androlib.java:371)
	at brut.androlib.Androlib.build(Androlib.java:281)
	at brut.androlib.Androlib.build(Androlib.java:254)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = -1073741819): [C:\Users\Serhij\AppData\Local\Temp\BAT_temp\brut_util_Jar_2821555928312825099.tmp, p, --forced-package-id, 2, --min-sdk-version, 19, --target-sdk-version, 19, --version-code, 19, --version-name, 4.4.2, -F, C:\Users\Serhij\AppData\Local\Temp\BAT_temp\APKTOOL6951576291834491888.tmp, -x, -0, arsc, -0, db, -0, arsc, -I, .\framework\1.apk, -S, C:\BatchApkToolMod\bin\..\_INPUT_APK-miui\mediatek-res\res, -M, C:\BatchApkToolMod\bin\..\_INPUT_APK-miui\mediatek-res\AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:433)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:419)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = -1073741819): [C:\Users\Serhij\AppData\Local\Temp\BAT_temp\brut_util_Jar_2821555928312825099.tmp, p, --forced-package-id, 2, --min-sdk-version, 19, --target-sdk-version, 19, --version-code, 19, --version-name, 4.4.2, -F, C:\Users\Serhij\AppData\Local\Temp\BAT_temp\APKTOOL6951576291834491888.tmp, -x, -0, arsc, -0, db, -0, arsc, -I, .\framework\1.apk, -S, C:\BatchApkToolMod\bin\..\_INPUT_APK-miui\mediatek-res\res, -M, C:\BatchApkToolMod\bin\..\_INPUT_APK-miui\mediatek-res\AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:427)
	... 6 more
[*] ---> Помилка рекомпіляції "mediatek-res"
```
On apktool 2.0.2 with custom aapt no errors:
```
[*] Рекомпіляція mediatek-res
I: Using Apktool 2.0.2
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
aapt: warning: string 'byteShort' has no default translation in C:\BatchApkToolMod\bin\..\_INPUT_APK-miui\mediatek-res\res; found: en_US ru uk
aapt: warning: string 'ext_media_checking_notification_title2' has no default translation in C:\BatchApkToolMod\bin\..\_INPUT_APK-miui\mediatek-res\res; found: ru uk zh_TW
aapt: warning: string 'missed_call_display' has no default translation in C:\BatchApkToolMod\bin\..\_INPUT_APK-miui\mediatek-res\res; found: ru uk zh_TW
aapt: warning: string 'missed_message_display' has no default translation in C:\BatchApkToolMod\bin\..\_INPUT_APK-miui\mediatek-res\res; found: ru uk zh_TW
aapt: warning: string 'repeat_weekdays' has no default translation in C:\BatchApkToolMod\bin\..\_INPUT_APK-miui\mediatek-res\res; found: ru uk zh_CN
I: Building apk file...
```

[mediatek-res.zip](https://github.com/iBotPeaches/Apktool/files/215640/mediatek-res.zip)
[frameworks.zip](https://github.com/iBotPeaches/Apktool/files/215642/frameworks.zip)
[aapt.zip](https://github.com/iBotPeaches/Apktool/files/215643/aapt.zip)

**Comment by iBotPeaches** [comment]
Sorry not patching or investigating MIUI problems anymore. The stress and time isn't worth it anymore.

**Comment by Hikari-no-Tenshi** [comment]
Ok.
Anyway thanks for Your work on apktool.
