### ISSUE TITLE
Unable to run application after recompiling using apktool 2.0.3 or 2.1.0

### ISSUE THREAD

**Issue by shunguoy** [iBotPeaches/Apktool#1228]
### Information
1. **Apktool Version (`apktool -version`)** -   2.0.3  and 2.1.0
2. **Operating System (Mac, Linux, Windows)** -  MAC, Windows and Linux
3. **APK From? (Playstore, ROM, Other)** -  Other

### Stacktrace/Logcat
```
04-18 15:07:57.258 1615-1754/? E/Surface: getSlotFromBufferLocked: unknown buffer: 0xa12a56a0
04-18 15:07:57.261 2127-2127/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.ibm.supportdesignlibtest, PID: 2127
                                                 java.lang.IllegalStateException: Expected 18 but was 17
                                                     at com.android.dex.EncodedValueReader.checkType(EncodedValueReader.java:283)
                                                     at com.android.dex.EncodedValueReader.readType(EncodedValueReader.java:183)
                                                     at libcore.reflect.AnnotationAccess.decodeValue(AnnotationAccess.java:704)
                                                     at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:663)
                                                     at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:641)
                                                     at libcore.reflect.AnnotationAccess.getDeclaredAnnotation(AnnotationAccess.java:171)
                                                     at libcore.reflect.AnnotationAccess.getAnnotation(AnnotationAccess.java:72)
                                                     at java.lang.Class.getAnnotation(Class.java:359)
                                                     at android.support.design.widget.CoordinatorLayout.getResolvedLayoutParams(Unknown Source)
                                                     at android.support.design.widget.CoordinatorLayout.prepareChildren(Unknown Source)
                                                     at android.support.design.widget.CoordinatorLayout.onMeasure(Unknown Source)
                                                     at android.view.View.measure(View.java:18788)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                     at android.support.v7.internal.widget.ContentFrameLayout.onMeasure(Unknown Source)
                                                     at android.view.View.measure(View.java:18788)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                     at android.view.View.measure(View.java:18788)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                     at android.view.View.measure(View.java:18788)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                     at android.view.View.measure(View.java:18788)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                     at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
                                                     at android.view.View.measure(View.java:18788)
                                                     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2100)
                                                     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1216)
                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1452)
                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                     at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
04-18 15:07:57.272 1300-1400/? W/ActivityManager:   Force finishing activity com.ibm.supportdesignlibtest/.MainActivity
04-18 15:07:57.289 952-952/? E/EGL_emulation: tid 952: eglCreateSyncKHR(1294): error 0x3004 (EGL_BAD_ATTRIBUTE)
04-18 15:07:57.409 1300-1344/? I/OpenGLRenderer: Initialized EGL, version 1.4
04-18 15:07:57.428 1300-1344/? W/EGL_emulation: eglSurfaceAttrib not implemented
04-18 15:07:57.428 1300-1344/? W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0x9b9f6820, error=EGL_SUCCESS
04-18 15:07:57.769 1300-1417/? I/ActivityManager: Killing 1650:com.android.printspooler/u0a40 (adj 15): empty #17
04-18 15:07:57.826 1300-1314/? W/ActivityManager: Activity pause timeout for ActivityRecord{998752 u0 com.ibm.supportdesignlibtest/.MainActivity t378 f}
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)
NO this is customer made test case.  We have the apk in our local disk

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? 
2. If you are trying to install a modified apk, did you resign it?  Yes
3. Are you using the latest apktool version?  Yes, apktool 2.1

**Comment by iBotPeaches** [comment]
While the stacktrace shows a problem there is nothing in it that points to something in apktool and without APK there just isn't anything I can do here. 

Sorry but you probably understand that investigating bugs such as decoding with only a stacktrace from the host running said application is difficult to work from.
