### ISSUE TITLE
Failed with the APK using DataBinding

### ISSUE THREAD

**Issue by ashqal** [iBotPeaches/Apktool#1229]
### Information
1. **Apktool Version (`apktool -version`)** - 2.1.0
2. **Operating System (Mac, Linux, Windows)** - Mac
3. **APK From? (Playstore, ROM, Other)** - Other

### Stacktrace/Logcat
```
ashqal-2:databind Asha$ java -jar /Users/Asha/Desktop/databind/apktool_2.1.0.jar d /Users/Asha/Desktop/databind/app-debug.apk 
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
I: Using Apktool 2.1.0 on app-debug.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/Asha/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
Exception in thread "main" brut.androlib.err.UndefinedResObject: resource spec: 0x01010462
	at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:66)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:62)
	at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferenceValue.java:57)
	at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:54)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:510)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:264)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:128)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:106)
	at brut.apktool.Main.cmdDecode(Main.java:163)
	at brut.apktool.Main.main(Main.java:81)
```

### Steps to Reproduce
1. `apktool -d xxx.apk`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
[app-debug.apk.zip](https://github.com/iBotPeaches/Apktool/files/225423/app-debug.apk.zip)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? `YES`
2. If you are trying to install a modified apk, did you resign it? `NOT MODIFIED`
3. Are you using the latest apktool version? `YES`

### Reference
[Data Binding Guide](https://developer.android.com/tools/data-binding/guide.html)

**Comment by iBotPeaches** [comment]
```
➜  Bug1229 apktool d app-debug.apk 
I: Using Apktool 2.1.0-180728-SNAPSHOT on app-debug.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1229 
```

Try and remove the file at `$HOME/apktool/framework/1.apk` and try again. Seems to be a framework problem.

**Comment by ashqal** [comment]
It works. Thank you very much.

**Comment by bachiri** [comment]
Thanks Man It works for me too
