### ISSUE TITLE
Cannot rebuild Settings.apk from DOOGEE Stock ROM

### ISSUE THREAD

**Issue by xjpmauricio** [iBotPeaches/Apktool#1245]
Cannot rebuild Settings.apk from DOOGEE Stock ROM.

### Information
1. Apktool Version 2.1.1 from iBotPeaches/Apktool
2. Windows 10
3. Stock ROM from this device: http://www.everbuying.net/product1084654.html?gclid=Cj0KEQjw9tW5BRDk29KDnqWu4fMBEiQAKj7spwjGwG8tXx3HU7SBLvDN2EFMyb_2Oy-Jet8X7moK3NAaAi788P8HAQ

### stacktrace:
W: D:\WORK\shore\Phones\doogee\X5pro\X5pro\Settings\res\values\public.xml:102: error: Public symbol drawable/preference_highlight declared here is not defined.
Exception in thread "main" W: D:\WORK\shore\Phones\doogee\X5pro\X5pro\Settings\res\values\public.xml:58: error: Public symbol drawable/preview declared here is not defined.
brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\JOSMAU~1\AppData\Local\Temp\brut_util_Jar_8360466780133675605.tmp, p, --forced-package-id, 127, --min-sdk-version, 22, --target-sdk-version, 22, --version-code, 22, --version-name, 5.1-1458122746, -F, C:\Users\JOSMAU~1\AppData\Local\Temp\APKTOOL7122069834414303805.tmp, -0, arsc, -0, arsc, -I, C:\Users\José Maurício\apktool\framework\1.apk, -S, D:\WORK\shore\Phones\doogee\X5pro\X5pro\Settings\res, -M, D:\WORK\shore\Phones\doogee\X5pro\X5pro\Settings\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:437)
        at brut.androlib.Androlib.buildResources(Androlib.java:371)
        at brut.androlib.Androlib.build(Androlib.java:281)
        at brut.androlib.Androlib.build(Androlib.java:254)
        at brut.apktool.Main.cmdBuild(Main.java:224)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\JOSMAU~1\AppData\Local\Temp\brut_util_Jar_8360466780133675605.tmp, p, --forced-package-id, 127, --min-sdk-version, 22, --target-sdk-version, 22, --version-code, 22, --version-name, 5.1-1458122746, -F, C:\Users\JOSMAU~1\AppData\Local\Temp\APKTOOL7122069834414303805.tmp, -0, arsc, -0, arsc, -I, C:\Users\José Maurício\apktool\framework\1.apk, -S, D:\WORK\shore\Phones\doogee\X5pro\X5pro\Settings\res, -M, D:\WORK\shore\Phones\doogee\X5pro\X5pro\Settings\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:436)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:423)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\JOSMAU~1\AppData\Local\Temp\brut_util_Jar_8360466780133675605.tmp, p, --forced-package-id, 127, --min-sdk-version, 22, --target-sdk-version, 22, --version-code, 22, --version-name, 5.1-1458122746, -F, C:\Users\JOSMAU~1\AppData\Local\Temp\APKTOOL7122069834414303805.tmp, -0, arsc, -0, arsc, -I, C:\Users\José Maurício\apktool\framework\1.apk, -S, D:\WORK\shore\Phones\doogee\X5pro\X5pro\Settings\res, -M, D:\WORK\shore\Phones\doogee\X5pro\X5pro\Settings\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:430)
        ... 6 more

### Steps to Reproduce
1.install framework: apktool if framework-res.apk
2.install framework:  apktool if mediatek-res.apk
3. decompile apk: apktool d -s -f Settings.apk
4. change apktool.yml to include installed frameworks id's 1 & 8
5. rebuild apk: apktool b Settings

### Frameworks and Settings apk
https://mega.nz/#!lFRE0KCI!JRbDVpLuog26JOOxbGPmPXIP5zx4pqosV2FakqzBw0w

apktool.yml:

!!brut.androlib.meta.MetaInfo
apkFileName: Settings.apk
compressionType: false
doNotCompress:
- arsc
isFrameworkApk: false
packageInfo:
  forcedPackageId: '127'
  renameManifestPackage: null
sdkInfo:
  minSdkVersion: '22'
  targetSdkVersion: '22'
sharedLibrary: false
unknownFiles: {}
usesFramework:
  ids:
  - 1
  tag: null
version: 2.1.1
versionInfo:
  versionCode: '22'
  versionName: 5.1-1458122746

**Comment by iBotPeaches** [comment]
```
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image /home/ibotpeaches/Downloads/Apktool/Bug1245/Settings/res/drawable-hdpi-v4/lock_anim_0.png
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image /home/ibotpeaches/Downloads/Apktool/Bug1245/Settings/res/drawable-hdpi-v4/lock_anim_1.png
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image /home/ibotpeaches/Downloads/Apktool/Bug1245/Settings/res/drawable-hdpi-v4/lock_anim_10.png
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image /home/ibotpeaches/Downloads/Apktool/Bug1245/Settings/res/drawable-hdpi-v4/lock_anim_11.png
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image /home/ibotpeaches/Downloads/Apktool/Bug1245/Settings/res/drawable-hdpi-v4/lock_anim_12.png
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image /home/ibotpeaches/Downloads/Apktool/Bug1245/Settings/res/drawable-hdpi-v4/lock_anim_13.png
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image /home/ibotpeaches/Downloads/Apktool/Bug1245/Settings/res/drawable-hdpi-v4/lock_anim_14.png
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image /home/ibotpeaches/Downloads/Apktool/Bug1245/Settings/res/drawable-hdpi-v4/lock_anim_2.png
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image /home/ibotpeaches/Downloads/Apktool/Bug1245/Settings/res/drawable-hdpi-v4/lock_anim_3.png
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image /home/ibotpeaches/Downloads/Apktool/Bug1245/Settings/res/drawable-hdpi-v4/lock_anim_4.png
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image /home/ibotpeaches/Downloads/Apktool/Bug1245/Settings/res/drawable-hdpi-v4/lock_anim_5.png
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image /home/ibotpeaches/Downloads/Apktool/Bug1245/Settings/res/drawable-hdpi-v4/lock_anim_6.png
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image /home/ibotpeaches/Downloads/Apktool/Bug1245/Settings/res/drawable-hdpi-v4/lock_anim_7.png
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image /home/ibotpeaches/Downloads/Apktool/Bug1245/Settings/res/drawable-hdpi-v4/lock_anim_8.png
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image /home/ibotpeaches/Downloads/Apktool/Bug1245/Settings/res/drawable-hdpi-v4/lock_anim_9.png
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image /home/ibotpeaches/Downloads/Apktool/Bug1245/Settings/res/drawable-hdpi-v4/lockscreen_default_preview.png
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image /home/ibotpeaches/Downloads/Apktool/Bug1245/Settings/res/drawable-xhdpi-v4/setup_illustration_tile.png
```

Fix these bad images and the rest of the errors should fix themselves.

**Comment by xjpmauricio** [comment]
Wow! that one worked! I picked up all the png files with errors, opened them with Microsoft Paint (photoshop cannot open these corrupted files), did a save as with overwitte of the original and voilá! Now I can compile with no errors!!! Thanks!!! YOu saved my life!!!
