### ISSUE TITLE
Apktool  any version not let me to decompile any odex file

### ISSUE THREAD

**Issue by Androdiver** [iBotPeaches/Apktool#1247]
### Information
1. **Apktool Version 4.3/4.1/etc any of these version i tried cant decompile my odex or apk file even framework is not impoting why
This error is showing when import my framework res apk

```
ERROR: ld.so: object 'libsigchain.so' from LD_PRELOAD cannot be preloaded: ignored.
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:56)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:40)
	at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:562)
	at brut.androlib.Androlib.installFramework(Androlib.java:473)
	at brut.apktool.Main.cmdInstallFramework(Main.java:250)
	at brut.apktool.Main.main(Main.java:81)
Caused by: java.io.IOException: Expected: 0x001c0001, got: 0x00000000
	at brut.util.ExtDataInput.skipCheckInt(ExtDataInput.java:48)
	at brut.androlib.res.decoder.StringBlock.read(StringBlock.java:44)
	at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:102)
	at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:83)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:49)
	... 5 more
```

2. **Operating System (Android lollipop 5.0.2 AOSP)** -
3.odex from my framework

https://www.mediafire.com/download/rfb3vtw4gj7vn9j

My framework-res.apk

https://www.mediafire.com/download/cobq0q42zl62vqr

My systemUI.apk
https://www.mediafire.com/download/rntt0qjsm5v4g99

My systemUI.odex
https://www.mediafire.com/download/w8x1ddjypno5eb2

**Comment by iBotPeaches** [comment]
Apktool does not handle `odex` files. It must be deodexed before apktool handles it. The other error is some system problem. You are having problems loading shared libraries.

```
➜  Bug1247 apktool d framework-res.apk 
I: Using Apktool 2.1.1 on framework-res.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1247 
```

Also no error.
