### ISSUE TITLE
Crash on decompiling Settings.apk

### ISSUE THREAD

**Issue by TheShadowRunner** [iBotPeaches/Apktool#1249]
### Information
apktool 2.1.1
Windows XP 32 bit
Settings.apk from ROM (Sony Z1C 5.1.1).
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) Client VM (build 24.79-b02, mixed mode, sharing)

### Stacktrace/Logcat

C:\Unzipped\a>java -jar apktool.jar d -s Settings.apk
I: Using Apktool 2.1.1 on Settings.apk
I: Loading resource table...
I: Decoding Shared Library (com.sonyericsson.uxp), pkgId: 2
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Documents and Settings\Alcahest\apktool\
framework\1.apk
I: Decoding Shared Library (com.sonyericsson.uxp), pkgId: 2
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at brut.util.ExtDataInput.readIntArray(ExtDataInput.java:34)
        at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:
200)
        at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.j
ava:153)
        at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.ja
va:115)
        at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.jav
a:77)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibRes
ources.java:555)
        at brut.androlib.res.AndrolibResources.loadFrameworkPkg(AndrolibResource
s.java:124)
        at brut.androlib.res.data.ResTable.getPackage(ResTable.java:83)
        at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:66)
        at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:62)
        at brut.androlib.res.decoder.ResAttrDecoder.decode(ResAttrDecoder.java:3
9)
        at brut.androlib.res.decoder.AXmlResourceParser.getAttributeValue(AXmlRe
sourceParser.java:369)
        at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValu
e(XmlPullParserDelegate.java:69)
        at brut.androlib.res.decoder.XmlPullStreamDecoder$1.parseManifest(XmlPul
lStreamDecoder.java:97)
        at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamD
ecoder.java:65)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDe
coder.java:141)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPull
StreamDecoder.java:153)
        at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecode
r.java:140)
        at brut.androlib.res.AndrolibResources.decodeManifestWithResources(Andro
libResources.java:208)
        at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:133)

        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:106)
        at brut.apktool.Main.cmdDecode(Main.java:163)
        at brut.apktool.Main.main(Main.java:81)

### Steps to Reproduce
Just run apktool.jar d -s Settings.apk

### Frameworks
Apk is from Sony OEM ROM.
Frameworks: framework-res.apk & SemcGenericUxpRes.apk

### APK
Attached is the APK and its 2 frameworks.
http://videoff7.free.fr/apk+frameworks.zip

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
yes, sadly it crashes on 'apktool d' and doesn't even go further.

3. Are you using the latest apktool version?
To my knowledge, yes. I'm just trying to alter 2 text lines in an exisiting XML, but cannot even decompile. When using apktool ver 2.0.0, I can actually decompile but recompiling never works.
Since 2.0.0 is outdated, I would like 2.1.1 decompiling fixed first then maybe recompile will work.. ^^

**Comment by iBotPeaches** [comment]
```
➜  Bug1249 apktool if framework-res.apk -t 1249
I: Decoding Shared Library (com.sonyericsson.uxp), pkgId: 2
I: Framework installed to: /home/ibotpeaches/apktool/framework/1-1249.apk
➜  Bug1249 apktool if SemcGenericUxpRes.apk -t 1249
I: Framework installed to: /home/ibotpeaches/apktool/framework/2-1249.apk
➜  Bug1249 apktool d Settings.apk -t 1249
I: Using Apktool 2.1.1 on Settings.apk
I: Loading resource table...
I: Decoding Shared Library (com.sonyericsson.uxp), pkgId: 2
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/apktool/framework/1-1249.apk
I: Decoding Shared Library (com.sonyericsson.uxp), pkgId: 2
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Loading resource table from file: /home/ibotpeaches/apktool/framework/2-1249.apk
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1249 
```

The error you have is `Exception in thread "main" java.lang.OutOfMemoryError: Java heap space`. While Apktool probably isn't the most optimized Java CLI application on the market, this is easily fixable on your end by increasing the java heap size. I use `512M` locally and don't have any troubles.
