### ISSUE TITLE
Errors decoding Settings.apk - MIUI 7 v6.5.26 Rom !

### ISSUE THREAD

**Issue by ManhIT-CMB** [iBotPeaches/Apktool#1260]
### Information
1. **Apktool Version: 2.1.1
2. **Operating System: Windows 10 x64
3. **APK From?: Rom MIUI 7 v6.5.26 Xiaomi Redmi 3

### Stacktrace/Logcat
```
I: Using Apktool 2.1.1 on Settings.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\ManhIT\apktool\framework\1.apk
I: Loading resource table from file: C:\Users\ManhIT\apktool\framework\16.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Loading resource table from file: C:\Users\ManhIT\apktool\framework\17.apk
I: Decoding values */* XMLs...
Exception in thread "main" brut.androlib.err.UndefinedResObject: resource spec: 0x01010501
        at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
        at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:66)
        at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:62)
        at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferenceValue.java:57)
        at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:54)
        at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:513)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:264)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:128)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:108)
        at brut.apktool.Main.cmdDecode(Main.java:163)
        at brut.apktool.Main.main(Main.java:81)
```

Include stacktrace here

### Steps to Reproduce
1. `apktool `

apktool.bat if framework-ext-res.apk

apktool.bat if framework-res.apk

apktool.bat if miui.apk

apktool.bat if miuisystem.apk

apktool.bat d Settings.apk

[Settings.zip](https://github.com/iBotPeaches/Apktool/files/288584/Settings.zip)

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)
[framework.zip](https://github.com/iBotPeaches/Apktool/files/288585/framework.zip)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by iBotPeaches** [comment]
Unfortunately official support for MIUI was dropped months ago. Sorry.
