### ISSUE TITLE
Cannot recompile using apktool...please help...

### ISSUE THREAD

**Issue by brainhacker550** [iBotPeaches/Apktool#1262]
Hello, im having problems recompiling apks using apktool when i try to recompile it gives me this errors...
```
┌─[root]@[none]─[~/Desktop/apkR]
└──╼ $ apktool b facebook -o face.apk
 00:50:37 up 22 min,  1 user,  load average: 1.86, 0.82, 0.45
USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT
root     tty2     :0               00:29   22:01   2:15   1:01  firefox-esr
I: Using Apktool 2.1.1-dirty
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: aapt: tools/aapt/Images.cpp:811: void checkNinePatchSerialization(android::Res_png_9patch*, void*): Assertion `outPatch->getXDivs()[i] == inPatch->getXDivs()[i]' failed.
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 134): [/usr/bin/aapt, p, --min-sdk-version, 15, --target-sdk-version, 23, --version-code, 30034615, --version-name, 77.0.0.20.66, -F, /tmp/APKTOOL3189886894890103237.tmp, -0, FBSIG, -0, md5, -0, js, -0, assets/js-modules/UNBUNDLE, -0, xzs, -0, arsc, -I, /root/apktool/framework/1.apk, -S, /root/Desktop/pentest/facebook/res, -M, /root/Desktop/pentest/facebook/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:437)
	at brut.androlib.Androlib.buildResources(Androlib.java:371)
	at brut.androlib.Androlib.build(Androlib.java:281)
	at brut.androlib.Androlib.build(Androlib.java:254)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 134): [/usr/bin/aapt, p, --min-sdk-version, 15, --target-sdk-version, 23, --version-code, 30034615, --version-name, 77.0.0.20.66, -F, /tmp/APKTOOL3189886894890103237.tmp, -0, FBSIG, -0, md5, -0, js, -0, assets/js-modules/UNBUNDLE, -0, xzs, -0, arsc, -I, /root/apktool/framework/1.apk, -S, /root/Desktop/pentest/facebook/res, -M, /root/Desktop/pentest/facebook/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:436)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:423)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 134): [/usr/bin/aapt, p, --min-sdk-version, 15, --target-sdk-version, 23, --version-code, 30034615, --version-name, 77.0.0.20.66, -F, /tmp/APKTOOL3189886894890103237.tmp, -0, FBSIG, -0, md5, -0, js, -0, assets/js-modules/UNBUNDLE, -0, xzs, -0, arsc, -I, /root/apktool/framework/1.apk, -S, /root/Desktop/pentest/facebook/res, -M, /root/Desktop/pentest/facebook/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:430)
	... 6 more
```
I used the "Facebook" app as an example but this error happens to each and every apk..
the original facebook.apk was decompiled with apktool which went smoothly.....
iv'e installed the framework-res.apk, SystemUI.apk and twframework-res.apk.....
Please help... Thanks in advance...

**Comment by iBotPeaches** [comment]
Never seen this error before. Seems `aapt` binary is choking on a 9patch image. Did the decode succeed or have any warnings?

**Comment by mackkill** [comment]
I face the same issue,as well as the following:
W: E:\APP\res\values\public.xml:206: error: Public symbol drawable/tupian declared here is not defined

**Comment by iBotPeaches** [comment]
Closing issue due to no response from original post in over a month. I tested downloading Facebook apk and decoding it and rebuilding and did not experience this issue.

Will re-visit if more details or affected apk is posted.

```
➜  Bug1262 apktool d facebook.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1262 apktool b facebook.apk
I: Using Apktool 2.2.0-e1dd43-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
➜  Bug1262 
```
