### ISSUE TITLE
apktool don't work

### ISSUE THREAD

**Issue by aleks921** [iBotPeaches/Apktool#1265]
I want do this comand: java -jar apktool.jar d -d 202.apk out
I use apktool 1.4.1.
I get error.
```
C:\apktool>java -jar apktool.jar d -d 202.apk out
I: Baksmaling...
testI: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Could not decode ars
c file
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:55)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibRes
ources.java:315)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.jav
a:50)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.jav
a:43)
        at brut.androlib.Androlib.getResTable(Androlib.java:44)
        at brut.androlib.ApkDecoder.getResTable(ApkDecoder.java:148)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:98)
        at brut.apktool.Main.cmdDecode(Main.java:120)
        at brut.apktool.Main.main(Main.java:57)
Caused by: java.io.IOException: Expected: 0x001c0001, got: 0x00000000
        at brut.util.ExtDataInput.skipCheckInt(ExtDataInput.java:48)
        at brut.androlib.res.decoder.StringBlock.read(StringBlock.java:45)
        at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:97
)
        at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:82)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:48)
        ... 8 more
```

Help me please. How fixed apktool and decompile apk ?

**Comment by iBotPeaches** [comment]
Apktool 1.4.1 is like 3 years old.

**Comment by aleks921** [comment]
How me this comand "java -jar apktool.jar d -d 202.apk out" do in last version apktool ?
Option -d not found in new version.
I want to debug android program without sorce.

**Comment by aleks921** [comment]
I read this aticle https://habrahabr.ru/post/150825/ and want to repeat. How me do this on new version ?

**Comment by aleks921** [comment]
C:\apktool2>apktool d -d 202.apk
SmaliDebugging has been removed in 2.1.0 onward. Please see: https://github.com/
iBotPeaches/Apktool/issues/1061

**Comment by iBotPeaches** [comment]
Yes smali debugging has been removed.

**Comment by aleks921** [comment]
How me do debug ? I want to debug android tools without sorce in eclipse with smali.

**Comment by iBotPeaches** [comment]
This is a bug tracker. Not for support. You aren't reading anything that I'm saying.
