### ISSUE TITLE
New version don't work.

### ISSUE THREAD

**Issue by aleks921** [iBotPeaches/Apktool#1266]
I try new version apktool 2.1.1.
C:\apktool2>apktool d 202.apk
I: Using Apktool 2.1.1 on 202.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\microsoft\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
Exception in thread "main" brut.androlib.err.UndefinedResObject: resource spec:
0x010302d4
        at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
        at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:66)
        at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:62)
        at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferen
ceValue.java:57)
        at brut.androlib.res.data.value.ResReferenceValue.encodeAsResXml(ResRefe
renceValue.java:47)
        at brut.androlib.res.data.value.ResScalarValue.encodeAsResXmlAttr(ResSca
larValue.java:46)
        at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(Re
sStyleValue.java:49)
        at brut.androlib.res.data.value.ResBagValue.serializeToResValuesXml(ResB
agValue.java:42)
        at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResour
ces.java:513)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:264
)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:128)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:108)
        at brut.apktool.Main.cmdDecode(Main.java:163)
        at brut.apktool.Main.main(Main.java:81)

**Comment by iBotPeaches** [comment]
Stop making issues. You aren't following the issue guidelines or reading the wiki.
