### ISSUE TITLE
Unable to decompile apk

### ISSUE THREAD

**Issue by jack16099** [iBotPeaches/Apktool#1268]
Getting error during decompile. 

Here's the apk file link http://goo.gl/unOPO8

```
C:\Users\user\ApkTool_JB\New folder>apktool d back.apk
I: Using Apktool 2.1.1 on back.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\user\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.Direc
toryException: Error copying file: ??   .xml
        at brut.androlib.Androlib.decodeUnknownFiles(Androlib.java:208)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:158)
        at brut.apktool.Main.cmdDecode(Main.java:163)
        at brut.apktool.Main.main(Main.java:81)
Caused by: brut.directory.DirectoryException: Error copying file: ??    .xml
        at brut.directory.DirUtil.copyToDir(DirUtil.java:88)
        at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:207
)
        at brut.androlib.Androlib.decodeUnknownFiles(Androlib.java:201)
        ... 3 more
Caused by: java.io.FileNotFoundException: back\unknown\??       .xml (The filena
me, directory name, or volume label syntax is incorrect)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at brut.directory.DirUtil.copyToDir(DirUtil.java:84)
        ... 5 more
```

**Comment by iBotPeaches** [comment]
The short story is that UTF8 is a second child on Windows, hardly cared for and even moving to a default of UTF8 breaks other things.

Your install is having troubles visually the output of Dexguard, which creates this weird named files. The process of renaming these files, in addition to conventions used in side of files is already an existing report - #885 

Since this is mostly isolated to Dexguard, I'm unsure if apktool's job should be to "unbreak" those applciations.
