### ISSUE TITLE
canid Recompil Error

### ISSUE THREAD

**Issue by LorDo** [iBotPeaches/Apktool#1276]
### Information
1. **Apktool Version (`2.1.1`)** -
2. **Operating System (Windows 10 Pro 64bit AND Windows 7 32bit)** -
3. **APK From? (ROM VZW-G900VVRU2DPD1-20160603114654)** -
4. **JRE/JDK Version (jre1.8.0_92/jdk1.8.0_92)** -

### Stacktrace/Logcat
```
I: Using Apktool 2.1.1
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: ERROR: input directory 'C:\Users\User\AppData\Local\Temp\APKTOOL1990217157982282728.tmp' does not exist
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\User\AppData\Local\Temp\brut_util_Jar_6891000038206391354.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 23, --version-code, 542580, --version-name, , -F, C:\Users\User\AppData\Local\Temp\APKTOOL1990217157982282728.tmp, -0, arsc, -0, cdl, -0, txt, -0, arsc, -I, C:\Users\User\apktool\framework\1.apk, -S, F:\Android\Data\app\original\projects\canid\res, -M, F:\Android\Data\app\original\projects\canid\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:437)
        at brut.androlib.Androlib.buildResources(Androlib.java:371)
        at brut.androlib.Androlib.build(Androlib.java:281)
        at brut.androlib.Androlib.build(Androlib.java:254)
        at brut.apktool.Main.cmdBuild(Main.java:224)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\User\AppData\Local\Temp\brut_util_Jar_6891000038206391354.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 23, --version-code, 542580, --version-name, , -F, C:\Users\User\AppData\Local\Temp\APKTOOL1990217157982282728.tmp, -0, arsc, -0, cdl, -0, txt, -0, arsc, -I, C:\Users\User\apktool\framework\1.apk, -S, F:\Android\Data\app\original\projects\canid\res, -M, F:\Android\Data\app\original\projects\canid\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:436)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:423)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\User\AppData\Local\Temp\brut_util_Jar_6891000038206391354.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 23, --version-code, 542580, --version-name, , -F, C:\Users\User\AppData\Local\Temp\APKTOOL1990217157982282728.tmp, -0, arsc, -0, cdl, -0, txt, -0, arsc, -I, C:\Users\User\apktool\framework\1.apk, -S, F:\Android\Data\app\original\projects\canid\res, -M, F:\Android\Data\app\original\projects\canid\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:430)
        ... 6 more
```
### Steps to Reproduce
1. `apktool `
I cleared the temp folder and try again. It does not solve the problem.

### Frameworks
http://www.mediafire.com/download/ui0346z12ix8atf/framework-res.apk
http://www.mediafire.com/download/thrjuqbp175zmuv/twframework-res.apk

### APK
http://www.mediafire.com/download/dmmzzn4n35mme65/canid.apk

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? | YES
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version? | YES

**Comment by iBotPeaches** [comment]
```
➜  Bug1276 apktool if framework-res.apk -t 1276
I: Framework installed to: /home/ibotpeaches/apktool/framework/1-1276.apk
➜  Bug1276 apktool if twframework-res.apk -t 1276
I: Framework installed to: /home/ibotpeaches/apktool/framework/2-1276.apk
➜  Bug1276 apktool d canid.apk -t 1276
I: Using Apktool 2.1.1 on canid.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/apktool/framework/1-1276.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1276 apktool b canid
I: Using Apktool 2.1.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Building apk file...
I: Copying unknown files/dir...
➜  Bug1276 
```

Could not duplicate. Looks like you are having temp folder problems. Apktool needs to write files to a temporary location in order to build archives.
