### ISSUE TITLE
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file

### ISSUE THREAD

**Issue by sandeepcmsm** [iBotPeaches/Apktool#1287]
### Information
1. **Apktool Version (`2.0.3 , 2.1.1 , 2.2.0-a4270d-SNAPSHOT , All versions `)** -
2. **Operating System (Mac el captain, Windows 10)** -
3. **APK From? (Playstore)** -

### Stacktrace/Logcat

```
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:52)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:555)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:72)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:64)
	at brut.androlib.Androlib.getResTable(Androlib.java:64)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:193)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
	at brut.apktool.Main.cmdDecode(Main.java:163)
	at brut.apktool.Main.main(Main.java:81)
Caused by: java.io.IOException: Expected: 0x001c0001, got: 0x00000001
	at brut.util.ExtDataInput.skipCheckChunkTypeInt(ExtDataInput.java:75)
	at brut.util.ExtDataInput.skipCheckChunkTypeInt(ExtDataInput.java:73)
	at brut.androlib.res.decoder.StringBlock.read(StringBlock.java:44)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:72)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
	... 8 more
```

### Steps to Reproduce
1. `apktool d Android_app.apk`

### Frameworks
http://www.mediafire.com/download/1exk27gu8aza53w/framework-res.apk

### APK
http://www.mediafire.com/download/5axnc9ad563f53n/Android_app.apk

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? YES
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version? YES

**Comment by sanli** [comment]
I meet same problem as this. seems is some kind of change on arsc file, bellow list some basic info of my investigation.

the resources.arsc file contain 2 extra bytes in head, "0100 0000", which cause ARSCDecoder throw a exception.

resources.arsc hex code:

    0200 1400 945d 0000 0100 0000 0000 0000
    // bellow "0100 0000" can not accept by ARSCDecoder
    0100 0000 0100 1c00 d417 0000 9900 0000
    0000 0000 0001 0000 8002 0000 0000 0000

Seems this kind of arsc file as not compatible with apktool, is it a new version or some private format? will update after get more info.

**Comment by iBotPeaches** [comment]
This seems to have the same additional bytes that my researched Android N apks have. See #1223 and #1226 for support on those. My guess is that once Android N is officially released with full SDK/code drop we can get this fixed.

Going to merge this into #1223 for organization.
