### ISSUE TITLE
Movile Apktool won't recompile

### ISSUE THREAD

**Issue by ltsjames** [iBotPeaches/Apktool#1288]
```
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec: [/data/data/per.pqy.apktool/apktool/openjdk/bin/aaptnew, p, --min-sdk-version, 14, --target-sdk-version, 21, --version-code, 143, --version-name, 10.8.5.7666, -F, /data/data/per.pqy.apktool/APKTOOL1151487177064642415.tmp, -0, arsc, -0, vbl, -0, arsc, -I, /data/data/per.pqy.apktool/1.apk, -S, /sdcard/Download/kik.night_src/res, -M, /sdcard/Download/kik.night_src/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:437)
	at brut.androlib.Androlib.buildResources(Androlib.java:371)
	at brut.androlib.Androlib.build(Androlib.java:281)
	at brut.androlib.Androlib.build(Androlib.java:254)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec: [/data/data/per.pqy.apktool/apktool/openjdk/bin/aaptnew, p, --min-sdk-version, 14, --target-sdk-version, 21, --version-code, 143, --version-name, 10.8.5.7666, -F, /data/data/per.pqy.apktool/APKTOOL1151487177064642415.tmp, -0, arsc, -0, vbl, -0, arsc, -I, /data/data/per.pqy.apktool/1.apk, -S, /sdcard/Download/kik.night_src/res, -M, /sdcard/Download/kik.night_src/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:436)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:423)
	... 5 more
Caused by: brut.common.BrutException: could not exec: [/data/data/per.pqy.apktool/apktool/openjdk/bin/aaptnew, p, --min-sdk-version, 14, --target-sdk-version, 21, --version-code, 143, --version-name, 10.8.5.7666, -F, /data/data/per.pqy.apktool/APKTOOL1151487177064642415.tmp, -0, arsc, -0, vbl, -0, arsc, -I, /data/data/per.pqy.apktool/1.apk, -S, /sdcard/Download/kik.night_src/res, -M, /sdcard/Download/kik.night_src/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:97)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:430)
	... 6 more
Caused by: java.io.IOException: Cannot run program "/data/data/per.pqy.apktool/apktool/openjdk/bin/aaptnew": error=13, Permission denied
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
	at brut.util.OS.exec(OS.java:90)
	... 7 more
Caused by: java.io.IOException: error=13, Permission denied
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:186)
	at java.lang.ProcessImpl.start(ProcessImpl.java:130)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
	... 8 more
```
I: Using Apktool 2.1.1
I: Smaling smali folder into classes.dex...
I: Building resources...

**Comment by iBotPeaches** [comment]
Not sure what this iteration of Apktool is. It sure isn't the official releases I provide as the error is referencing an aapt `data/data/per.pqy.apktool/apktool/openjdk/bin/aaptnew` from an Android filesystem. 

Please consult whoever made this forked version of apktool.
