### ISSUE TITLE
build apk faild just after decompile the apk

### ISSUE THREAD

**Issue by ragerous** [iBotPeaches/Apktool#1292]
Whatever apk i tried ,I can only decompile the apk successfully ,but  build failed.This happened all the time just after i build the apk without changing anything.
I was using the mac and java version is"1.8.0_74" and the apktool.jar (I've  tried both from clone and build  or download directly from the homePage)
here is my operation and the log:
```
bogon:samli ime$ java -jar apktool_2.1.1.jar apktool d wx.apk
I: Using Apktool 2.1.1 on wx.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/ime/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
bogon:samli ime$ 
bogon:samli ime$ 
bogon:samli ime$ 
bogon:samli ime$ java -jar apktool_2.1.1.jar apktool b wx
I: Using Apktool 2.1.1
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: java.io.FileNotFoundException: b (No such file or directory)
	at brut.androlib.Androlib.readMetaFile(Androlib.java:249)
	at brut.androlib.Androlib.build(Androlib.java:261)
	at brut.androlib.Androlib.build(Androlib.java:254)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.directory.DirectoryException: java.io.FileNotFoundException: b (No such file or directory)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:55)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:38)
	at brut.androlib.res.util.ExtFile.getDirectory(ExtFile.java:55)
	at brut.androlib.Androlib.readMetaFile(Androlib.java:245)
	... 4 more
Caused by: java.io.FileNotFoundException: b (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:53)
	... 7 more
```

**Comment by sanli** [comment]
you are running with a wrong command line arguments, seems should be:

    java -jar apktool_2.1.1.jar b wx

**Comment by iBotPeaches** [comment]
As @sanli said. This isn't a bug.
