### ISSUE TITLE
java.io.IOException: Specified path not found

### ISSUE THREAD

**Issue by leol1912** [iBotPeaches/Apktool#1295]
Apktool - 2.1.1
OS - Win7 64Bit
Apk - Selfmade

When Im trying to build an .apk apktool always throws the same error:
_______________________________________________________________________________________
```
I: Using Apktool 2.1.1
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
Exception in thread "main" brut.androlib.AndrolibException: java.io.IOException:
 Das System kann den angegebenen Pfad nicht finden
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:437)
        at brut.androlib.Androlib.buildResources(Androlib.java:371)
        at brut.androlib.Androlib.build(Androlib.java:281)
        at brut.androlib.Androlib.build(Androlib.java:254)
        at brut.apktool.Main.cmdBuild(Main.java:224)
        at brut.apktool.Main.main(Main.java:84)
Caused by: java.io.IOException: Das System kann den angegebenen Pfad nicht finde
n
        at java.io.WinNTFileSystem.createFileExclusively(Native Method)
        at java.io.File.createTempFile(Unknown Source)
        at java.io.File.createTempFile(Unknown Source)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:416)
        ... 5 more
```
_____________________________________________________________________________________________
Translation for Exception: System cannot find the path specified

Does anyone know what the problem is?

**Comment by iBotPeaches** [comment]
You already opened a bug here - #1293

These problems are similar. This is your environment and not a bug.
