### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by prox212** [iBotPeaches/Apktool#1296]
```
apktool 
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/jf/baksmali/baksmali : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at brut.androlib.ApktoolProperties.loadProps(ApktoolProperties.java:54)
	at brut.androlib.ApktoolProperties.get(ApktoolProperties.java:37)
	at brut.androlib.ApktoolProperties.get(ApktoolProperties.java:32)
	at brut.androlib.Androlib.getVersion(Androlib.java:656)
	at brut.apktool.Main.usage(Main.java:438)
	at brut.apktool.Main.main(Main.java:100)

```

how to quickly solve the problem ?

**Comment by BurgerZ** [comment]
Install java 8

**Comment by iBotPeaches** [comment]
```
➜  Desktop java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
➜  Desktop sudo update-alternatives --config java
There are 3 choices for the alternative java (providing /usr/bin/java).

  Selection    Path                                            Priority   Status
------------------------------------------------------------
  0            /usr/lib/jvm/java-7-oracle/jre/bin/java          1084      auto mode
  1            /usr/lib/jvm/java-7-oracle/jre/bin/java          1084      manual mode
  2            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      manual mode
* 3            /usr/lib/jvm/java-8-oracle/jre/bin/java          1083      manual mode

Press <enter> to keep the current choice[*], or type selection number: 0
update-alternatives: using /usr/lib/jvm/java-7-oracle/jre/bin/java to provide /usr/bin/java (java) in auto mode
➜  Desktop java -version
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)
➜  Desktop apktool d issue1244.apk 
I: Using Apktool 2.2.0-475178-SNAPSHOT on issue1244.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Desktop apktool b issue1244
I: Using Apktool 2.2.0-475178-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Building apk file...
I: Copying unknown files/dir...
➜  Desktop 
```

I haven't moved Apktool to Java8 dependency. Since the original report clobbered the template required for submission and the entire stack trace is missing. I'm closing this.
