### ISSUE TITLE
apktool b throwing error 

### ISSUE THREAD

**Issue by raviwithu** [iBotPeaches/Apktool#1300]
### Information
1. **Apktool Version (`apktool -version`)** - 2.1.1-dirty
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - CTF

### Stacktrace/Logcat

```
apktool b cocon_apk2/ -o Newcocon2.apk
I: Using Apktool 2.1.1-dirty
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 134): [/usr/bin/aapt, p, --min-sdk-version, 7, --version-code, 1, --version-name, 1.0, -F, /tmp/APKTOOL6796545138946088649.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/Desktop/Android/APps/cocon_apk2/res, -M, /root/Desktop/Android/APps/cocon_apk2/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:437)
	at brut.androlib.Androlib.buildResources(Androlib.java:371)
	at brut.androlib.Androlib.build(Androlib.java:281)
	at brut.androlib.Androlib.build(Androlib.java:254)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 134): [/usr/bin/aapt, p, --min-sdk-version, 7, --version-code, 1, --version-name, 1.0, -F, /tmp/APKTOOL6796545138946088649.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/Desktop/Android/APps/cocon_apk2/res, -M, /root/Desktop/Android/APps/cocon_apk2/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:436)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:423)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 134): [/usr/bin/aapt, p, --min-sdk-version, 7, --version-code, 1, --version-name, 1.0, -F, /tmp/APKTOOL6796545138946088649.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/Desktop/Android/APps/cocon_apk2/res, -M, /root/Desktop/Android/APps/cocon_apk2/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:430)
	... 6 more
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? 
2. If you are trying to install a modified apk, did you resign it? no
3. Are you using the latest apktool version? 2.1.1-dirty

**Comment by iBotPeaches** [comment]
Doesn't seem to be a real error. Try with the real verbose output `-v` and/or uploading an APK for me to a take a peek at.

Also, 2.2.0 is out so give that a shot.

**Comment by raviwithu** [comment]
Aug 10, 2016 3:57:10 PM brut.androlib.Androlib build
INFO: Using Apktool 2.1.1-dirty
Aug 10, 2016 3:57:10 PM brut.androlib.Androlib buildSourcesSmali
INFO: Checking whether sources has changed...
Aug 10, 2016 3:57:10 PM brut.androlib.Androlib buildResourcesFull
INFO: Checking whether resources has changed...
Aug 10, 2016 3:57:10 PM brut.androlib.Androlib buildResourcesFull
INFO: Building resources...
Aug 10, 2016 3:57:10 PM brut.androlib.res.AndrolibResources aaptPackage
INFO: /usr/bin/aapt being used as aapt location.
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO: Configurations:
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO:  (default)
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO:  ldpi-v4
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO:  mdpi-v4
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO:  hdpi-v4
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 134): [/usr/bin/aapt, p, -v, --min-sdk-version, 7, --version-code, 1, --version-name, 1.0, -F, /tmp/APKTOOL512454021955012943.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/Desktop/Android/APps/cocon_apk2/res, -M, /root/Desktop/Android/APps/cocon_apk2/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:437)
	at brut.androlib.Androlib.buildResources(Androlib.java:371)
	at brut.androlib.Androlib.build(Androlib.java:281)
	at brut.androlib.Androlib.build(Androlib.java:254)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 134): [/usr/bin/aapt, p, -v, --min-sdk-version, 7, --version-code, 1, --version-name, 1.0, -F, /tmp/APKTOOL512454021955012943.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/Desktop/Android/APps/cocon_apk2/res, -M, /root/Desktop/Android/APps/cocon_apk2/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:436)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:423)
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO: Files:
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 134): [/usr/bin/aapt, p, -v, --min-sdk-version, 7, --version-code, 1, --version-name, 1.0, -F, /tmp/APKTOOL512454021955012943.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/Desktop/Android/APps/cocon_apk2/res, -M, /root/Desktop/Android/APps/cocon_apk2/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:430)
	... 6 more
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO:   drawable/icon.png
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO:     Src: (ldpi-v4) /root/Desktop/Android/APps/cocon_apk2/res/drawable-ldpi-v4/icon.png
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO:     Src: (mdpi-v4) /root/Desktop/Android/APps/cocon_apk2/res/drawable-mdpi-v4/icon.png
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO:     Src: (hdpi-v4) /root/Desktop/Android/APps/cocon_apk2/res/drawable-hdpi-v4/icon.png
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO:   layout/main.xml
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO:     Src: () /root/Desktop/Android/APps/cocon_apk2/res/layout/main.xml
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO:   values/ids.xml
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO:     Src: () /root/Desktop/Android/APps/cocon_apk2/res/values/ids.xml
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO:   values/public.xml
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO:     Src: () /root/Desktop/Android/APps/cocon_apk2/res/values/public.xml
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO:   values/strings.xml
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO:     Src: () /root/Desktop/Android/APps/cocon_apk2/res/values/strings.xml
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO:   AndroidManifest.xml
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO:     Src: () /root/Desktop/Android/APps/cocon_apk2/AndroidManifest.xml
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO: 
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO: Resource Dirs:
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO:   Type drawable
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO:     drawable/icon.png
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO:       Src: (ldpi-v4) /root/Desktop/Android/APps/cocon_apk2/res/drawable-ldpi-v4/icon.png
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO:       Src: (mdpi-v4) /root/Desktop/Android/APps/cocon_apk2/res/drawable-mdpi-v4/icon.png
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO:       Src: (hdpi-v4) /root/Desktop/Android/APps/cocon_apk2/res/drawable-hdpi-v4/icon.png
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO:   Type layout
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO:     layout/main.xml
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO:       Src: () /root/Desktop/Android/APps/cocon_apk2/res/layout/main.xml
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO:   Type values
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO:     values/ids.xml
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO:       Src: () /root/Desktop/Android/APps/cocon_apk2/res/values/ids.xml
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO:     values/public.xml
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO:       Src: () /root/Desktop/Android/APps/cocon_apk2/res/values/public.xml
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO:     values/strings.xml
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO:       Src: () /root/Desktop/Android/APps/cocon_apk2/res/values/strings.xml
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO: Including resources from package: /root/.local/share/apktool/framework/1.apk
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO: applyFileOverlay for drawable
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO: applyFileOverlay for layout
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO: applyFileOverlay for anim
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO: applyFileOverlay for animator
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO: applyFileOverlay for interpolator
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO: applyFileOverlay for transition
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO: applyFileOverlay for xml
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO: applyFileOverlay for raw
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO: applyFileOverlay for color
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO: applyFileOverlay for menu
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO: applyFileOverlay for mipmap
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO: Processing image: /root/Desktop/Android/APps/cocon_apk2/res/drawable-ldpi-v4/icon.png
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO:     (processed image /root/Desktop/Android/APps/cocon_apk2/res/drawable-ldpi-v4/icon.png: 100% size of source)
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO: Processing image: /root/Desktop/Android/APps/cocon_apk2/res/drawable-mdpi-v4/icon.png
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO: Processing image: /root/Desktop/Android/APps/cocon_apk2/res/drawable-hdpi-v4/icon.png
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO:     (processed image /root/Desktop/Android/APps/cocon_apk2/res/drawable-mdpi-v4/icon.png: 100% size of source)
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO:     (processed image /root/Desktop/Android/APps/cocon_apk2/res/drawable-hdpi-v4/icon.png: 100% size of source)
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO:     (new resource id icon from ldpi-v4/drawable/icon.png #generated)
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO:     (new resource id icon from mdpi-v4/drawable/icon.png #generated)
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO:     (new resource id icon from hdpi-v4/drawable/icon.png #generated)
Aug 10, 2016 3:57:10 PM java.util.logging.LogManager$RootLogger log
INFO:     (new resource id main from /root/Desktop/Android/APps/cocon_apk2/res/layout/main.xml)

**Comment by raviwithu** [comment]
i tried with 2.2.0 as well getting the same error. 
[cocon_apk2.zip](https://github.com/iBotPeaches/Apktool/files/412001/cocon_apk2.zip)

**Comment by raviwithu** [comment]
Attached zip file of the decompiled apk which i want to build

**Comment by iBotPeaches** [comment]
Download of original file (apk) please. I can't be sure you haven't edited the APK already and caused this :)

**Comment by iBotPeaches** [comment]
```
➜  Bug1300 apktool b cocon_apk2
I: Using Apktool 2.2.0-2783ec-SNAPSHOT
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
I: Building apk file...
I: Copying unknown files/dir...
➜  Bug1300
```

No errors anyway and I believe exit code 134 is aborted, so you may have some antivirus or something killing the process.

**Comment by raviwithu** [comment]
[cocon_apk.apk.zip](https://github.com/iBotPeaches/Apktool/files/412019/cocon_apk.apk.zip)
