### ISSUE TITLE
ArrayIndexOutOfBoundsException: 373 - Stringblock during Utf8 read

### ISSUE THREAD

**Issue by YMXZ** [iBotPeaches/Apktool#1306]
1.2.2.0
2.linux 7.0 64
3.APK：https://transfer.sh/9VI6D/app.apk

```
[root@VM_20_164_centos ~]# apktool d app.apk
I: Using Apktool 2.2.0 on app.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /root/.local/share/apktool/framework/1.apk
I: Renamed manifest package found! Replacing com.vnvhh8t.flowmaxx with com.fuyyc.flowmasttu
I: Decoding file-resources...
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 373
    at brut.androlib.res.decoder.StringBlock.getUtf8(StringBlock.java:304)
    at brut.androlib.res.decoder.StringBlock.getString(StringBlock.java:102)
    at brut.androlib.res.decoder.AXmlResourceParser.getName(AXmlResourceParser.java:174)
    at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getName(XmlPullParserDelegate.java:57)
    at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:63)
    at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:141)
    at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(ResStreamDecoderContainer.java:33)
    at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:120)
    at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:105)
    at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:262)
    at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:131)
    at brut.androlib.ApkDecoder.decode(ApkDecoder.java:108)
    at brut.apktool.Main.cmdDecode(Main.java:163)
    at brut.apktool.Main.main(Main.java:81)
```

**Comment by YMXZ** [comment]
[root@iZ94dre1wukZ openvpn]# apktool b app
I: Using Apktool 2.2.0
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec: [/tmp/brut_util_Jar_729206274353726722.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --version-code, 10, --version-name, 4.0, -F, /tmp/APKTOOL5892384106966198733.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /etc/openvpn/app/res, -M, /etc/openvpn/app/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:473)
	at brut.androlib.Androlib.buildResources(Androlib.java:407)
	at brut.androlib.Androlib.build(Androlib.java:306)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec: [/tmp/brut_util_Jar_729206274353726722.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --version-code, 10, --version-name, 4.0, -F, /tmp/APKTOOL5892384106966198733.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /etc/openvpn/app/res, -M, /etc/openvpn/app/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:439)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:459)
	... 5 more
Caused by: brut.common.BrutException: could not exec: [/tmp/brut_util_Jar_729206274353726722.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --version-code, 10, --version-name, 4.0, -F, /tmp/APKTOOL5892384106966198733.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /etc/openvpn/app/res, -M, /etc/openvpn/app/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:97)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:433)
	... 6 more
Caused by: java.io.IOException: Cannot run program "/tmp/brut_util_Jar_729206274353726722.tmp": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at brut.util.OS.exec(OS.java:90)
	... 7 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 8 more

**Comment by iBotPeaches** [comment]
I confirm this. This is very low level in apktool. I haven't seen the StringBlock broken in almost a year. Not sure if an intentional effort to break apktool or some locale/charset/language/something that the StringBlock code is choking on.

**Comment by iBotPeaches** [comment]
I have the applications for the other bug - https://github.com/iBotPeaches/Apktool/issues/2378

So closing this one as duplicate for the other (yes I know this one was first).
