### ISSUE TITLE
Failed to recompile Youtube 11.32.53

### ISSUE THREAD

**Issue by Phone-Guru** [iBotPeaches/Apktool#1309]
### Information
1. **Apktool Version (`apktool -version`)** -2.2
2. **Operating System (Mac, Linux, Windows)** -Windows 10 64-bit
3. **APK From? (Playstore, ROM, Other)** - APKMirror.com

### Stacktrace/Logcat
```
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
A subdirectory or file modified-system-apk-files-here already exists.
W: C:\Users\Ilan\Desktop\APKToolALBEN5\projects\YouTube113253.apk\AndroidManifest.xml:31: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: C:\Users\Ilan\Desktop\APKToolALBEN5\projects\YouTube113253.apk\AndroidManifest.xml:32: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: C:\Users\Ilan\Desktop\APKToolALBEN5\projects\YouTube113253.apk\AndroidManifest.xml:33: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: C:\Users\Ilan\Desktop\APKToolALBEN5\projects\YouTube113253.apk\AndroidManifest.xml:34: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: C:\Users\Ilan\Desktop\APKToolALBEN5\projects\YouTube113253.apk\AndroidManifest.xml:105: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: C:\Users\Ilan\Desktop\APKToolALBEN5\projects\YouTube113253.apk\AndroidManifest.xml:113: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: C:\Users\Ilan\Desktop\APKToolALBEN5\projects\YouTube113253.apk\AndroidManifest.xml:120: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: C:\Users\Ilan\Desktop\APKToolALBEN5\projects\YouTube113253.apk\AndroidManifest.xml:121: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: C:\Users\Ilan\Desktop\APKToolALBEN5\projects\YouTube113253.apk\AndroidManifest.xml:122: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: C:\Users\Ilan\Desktop\APKToolALBEN5\projects\YouTube113253.apk\AndroidManifest.xml:135: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: C:\Users\Ilan\Desktop\APKToolALBEN5\projects\YouTube113253.apk\AndroidManifest.xml:136: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: C:\Users\Ilan\Desktop\APKToolALBEN5\projects\YouTube113253.apk\AndroidManifest.xml:137: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: C:\Users\Ilan\Desktop\APKToolALBEN5\projects\YouTube113253.apk\AndroidManifest.xml:143: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: C:\Users\Ilan\Desktop\APKToolALBEN5\projects\YouTube113253.apk\AndroidManifest.xml:144: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: C:\Users\Ilan\Desktop\APKToolALBEN5\projects\YouTube113253.apk\AndroidManifest.xml:183: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: C:\Users\Ilan\Desktop\APKToolALBEN5\projects\YouTube113253.apk\AndroidManifest.xml:189: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: C:\Users\Ilan\Desktop\APKToolALBEN5\projects\YouTube113253.apk\AndroidManifest.xml:190: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: C:\Users\Ilan\Desktop\APKToolALBEN5\projects\YouTube113253.apk\AndroidManifest.xml:191: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: C:\Users\Ilan\Desktop\APKToolALBEN5\projects\YouTube113253.apk\AndroidManifest.xml:192: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: C:\Users\Ilan\Desktop\APKToolALBEN5\projects\YouTube113253.apk\AndroidManifest.xml:193: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: C:\Users\Ilan\Desktop\APKToolALBEN5\projects\YouTube113253.apk\AndroidManifest.xml:213: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
W: C:\Users\Ilan\Desktop\APKToolALBEN5\projects\YouTube113253.apk\AndroidManifest.xml:233: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Ilan\AppData\Local\Temp\brut_util_Jar_7223273768912789335.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 24, --version-code, 113253634, --version-name, 11.32.53, -F, C:\Users\Ilan\AppData\Local\Temp\APKTOOL9027147944768166414.tmp, -0, arsc, -0, webp, -0, arsc, -I, C:\Users\Ilan\AppData\Local\apktool\framework\1.apk, -S, C:\Users\Ilan\Desktop\APKToolALBEN5\projects\YouTube113253.apk\res, -M, C:\Users\Ilan\Desktop\APKToolALBEN5\projects\YouTube113253.apk\AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:473)
	at brut.androlib.Androlib.buildResources(Androlib.java:407)
	at brut.androlib.Androlib.build(Androlib.java:306)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Ilan\AppData\Local\Temp\brut_util_Jar_7223273768912789335.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 24, --version-code, 113253634, --version-name, 11.32.53, -F, C:\Users\Ilan\AppData\Local\Temp\APKTOOL9027147944768166414.tmp, -0, arsc, -0, webp, -0, arsc, -I, C:\Users\Ilan\AppData\Local\apktool\framework\1.apk, -S, C:\Users\Ilan\Desktop\APKToolALBEN5\projects\YouTube113253.apk\res, -M, C:\Users\Ilan\Desktop\APKToolALBEN5\projects\YouTube113253.apk\AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:439)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:459)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Ilan\AppData\Local\Temp\brut_util_Jar_7223273768912789335.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 24, --version-code, 113253634, --version-name, 11.32.53, -F, C:\Users\Ilan\AppData\Local\Temp\APKTOOL9027147944768166414.tmp, -0, arsc, -0, webp, -0, arsc, -I, C:\Users\Ilan\AppData\Local\apktool\framework\1.apk, -S, C:\Users\Ilan\Desktop\APKToolALBEN5\projects\YouTube113253.apk\res, -M, C:\Users\Ilan\Desktop\APKToolALBEN5\projects\YouTube113253.apk\AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:433)
	... 6 more
```
### Steps to Reproduce
1. decompile, recompile, no changes

**Comment by iBotPeaches** [comment]
Already fixed here - https://github.com/iBotPeaches/Apktool/commit/64644a1242d47d8f69fb358f590b4312eeab5a12

Will be in 2.2.1.
