### ISSUE TITLE
brut.directory.DirectoryException: Error copying file: ?   .xml

### ISSUE THREAD

**Issue by ikoutone** [iBotPeaches/Apktool#1314]
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.0
2. **Operating System (Mac, Linux, Windows)** - Windows 10 64bit
3. **APK From? (Playstore, ROM, Other)** - Playstore (App is called Pivo)

### Stacktrace/Logcat

D:\Zipit>java -jar apktool.jar d -rf base.apk
I: Using Apktool 2.2.0 on base.apk
I: Copying raw resources...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: Error copying file: ?   .xml
        at brut.androlib.Androlib.decodeUnknownFiles(Androlib.java:217)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:158)
        at brut.apktool.Main.cmdDecode(Main.java:163)
        at brut.apktool.Main.main(Main.java:81)
Caused by: brut.directory.DirectoryException: Error copying file: ?    .xml
        at brut.directory.DirUtil.copyToDir(DirUtil.java:88)
        at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:207)
        at brut.androlib.Androlib.decodeUnknownFiles(Androlib.java:210)
        ... 3 more
Caused by: java.io.FileNotFoundException: base\unknown\?       .xml (The filename, directory name, or volume label syntax is incorrect)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at brut.directory.DirUtil.copyToDir(DirUtil.java:84)
        ... 5 more

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

[base.zip](https://github.com/iBotPeaches/Apktool/files/462378/base.zip)

**Comment by pjakubczyk** [comment]
Does it happen when you use dexguard ?

**Comment by ikoutone** [comment]
Not really sure how to do that, I was just following this article http://bertonjulian.github.io/2015/01/30/root-detection-bypass.html to see if I can bypass the root detection of the Pivo app.

**Comment by iBotPeaches** [comment]
This seems to be a Windows problem with non standard characters. Unix can't even visualize them, but it doesn't crash here.

```
-rw-rw-r-- 1 ibotpeaches ibotpeaches    420 Sep 18 17:41 ? .xml
-rw-rw-r-- 1 ibotpeaches ibotpeaches    864 Sep 18 17:41 ? .xml
-rw-rw-r-- 1 ibotpeaches ibotpeaches   1376 Sep 18 17:41 ??.xml
-rw-rw-r-- 1 ibotpeaches ibotpeaches    516 Sep 18 17:41 ??.xml
```

This is Windows problem. I'm not sure if there is any easy fix I have for this, unless I write a hashed file name out and convert back.

**Comment by dejanberic** [comment]
So is this fixed or not?
I use 2.2.2 and get the same error.
One way I would go about it is create a mapping between old names and new names so I could use old names when building back apk file.
New names could be generated like: "_APK_HEX_FILE_{HEX_VALUES_OF_FILENAME_CHARACTERS}"

**Comment by burma69** [comment]
Same error here with 2.2.2 @Windows 10 and Windows 7

I: Copying unknown files...
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: Error copying file: ?.xml
        at brut.androlib.Androlib.decodeUnknownFiles(Androlib.java:217)

**Comment by maxerbox** [comment]
I got the same error. It's a Windows issue. Maybe, we can let theses files
in a archive..... They are obfuscated by proguard.
