### ISSUE TITLE
error while decompiling APK , multiple Resource : specs = 0x7f030151 layout/__dont_play,config=-sw100dp

### ISSUE THREAD

**Issue by krashanu** [iBotPeaches/Apktool#1315]
### Information
1. **Apktool Version (`apktool -version`)** - 2.0.0
2. **Operating System (Mac, Linux, Windows)** - win 8.1 (32bit)
3. **APK From? (Playstore, ROM, Other)** - other (moded whatsapp)

### Stacktrace/Logcat

```
I: Using Apktool 2.0.0-RC4 on WhatsApp.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Multiple resources: spec=0x7f030151 layout/__1_Dont_Play, config=-sw100dp
        at brut.androlib.res.data.ResConfig.addResource(ResConfig.java:63)
        at brut.androlib.res.data.ResConfig.addResource(ResConfig.java:56)
        at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:217)
        at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:188)
        at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:156)
        at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:113)
        at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:78)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:622)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:73)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:65)
        at brut.androlib.Androlib.getResTable(Androlib.java:63)
        at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:209)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:92)
        at brut.apktool.Main.cmdDecode(Main.java:165)
        at brut.apktool.Main.main(Main.java:81)

```

### Steps to Reproduce
1. `apktool `

### APK
http://www.mediafire.com/download/9q9devfh56kr7a6/FMWA4.83.apk

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes 

###Additional information :- issue is with resource.arsc file of the apk .

**Comment by iBotPeaches** [comment]
Same exact error as recently reported #1316 , marking as duplicate to investigate together.
