### ISSUE TITLE
Motorola Quark framework-res.apk Multiple resources error

### ISSUE THREAD

**Issue by mhous33** [iBotPeaches/Apktool#1316]
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.0
2. **Operating System (Mac, Linux, Windows)** - Linux, Windows
3. **APK From? (Playstore, ROM, Other)** - ROM
### Stacktrace/Logcat

```
Include stacktrace here
```

C:\Users\mhous33\apktool>apktool if framework-res.apk
W: Duplicate Resource Detected. Ignoring duplicate: string-mcc310-mnc960/config_default_vm_number
W: Duplicate Resource Detected. Ignoring duplicate: string-mcc310-mnc960/config_default_vm_number
W: Duplicate Resource Detected. Ignoring duplicate: string-mcc310-mnc960/config_default_vm_number
W: Duplicate Resource Detected. Ignoring duplicate: string-mcc310-mnc960/config_default_vm_number
W: Duplicate Resource Detected. Ignoring duplicate: bool-mcc310-mnc00/config_telephony_use_own_number_for_voicemail
W: Duplicate Resource Detected. Ignoring duplicate: bool-mcc310-mnc960/config_telephony_use_own_number_for_voicemail
W: Duplicate Resource Detected. Ignoring duplicate: bool-mcc310-mnc960/config_telephony_use_own_number_for_voicemail
W: Duplicate Resource Detected. Ignoring duplicate: bool-mcc310-mnc960/config_telephony_use_own_number_for_voicemail
W: Duplicate Resource Detected. Ignoring duplicate: bool-mcc310-mnc960/config_telephony_use_own_number_for_voicemail
I: Framework installed to: C:\Users\mhous33\AppData\Local\apktool\framework\1.apk

C:\Users\mhous33\apktool>apktool d -s framework-res.apk
I: Using Apktool 2.2.0 on framework-res.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Multiple resources: spec=0x0104065a string/config_default_vm_number, config=-mcc310-mnc960
        at brut.androlib.res.data.ResType.addResource(ResType.java:66)
        at brut.androlib.res.data.ResType.addResource(ResType.java:55)
        at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:264)
        at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:220)
        at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:156)
        at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:118)
        at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:80)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:558)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:72)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:64)
        at brut.androlib.Androlib.getResTable(Androlib.java:67)
        at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:193)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
        at brut.apktool.Main.cmdDecode(Main.java:163)
        at brut.apktool.Main.main(Main.java:81)
C:\Users\mhous33\apktool>

[framework-res.zip](https://github.com/iBotPeaches/Apktool/files/465761/framework-res.zip)
### Steps to Reproduce
1. `apktool`
   apktool if framework-res.apk
   apktool d -s framework-res.apk
   ### Frameworks
   If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
   (`.apks` that live in `/system/framework` or `/system/priv-app`)
### APK

If this APK can be freely shared, please upload/attach a link to it.
### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? n/a
3. Are you using the latest apktool version? yes

**Comment by iBotPeaches** [comment]
```
➜  Bug1316 apktool d framework-res.apk
I: Using Apktool 2.2.1-4c93cb-SNAPSHOT on framework-res.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Multiple resources: spec=0x0104065a string/config_default_vm_number, config=-mcc310-mnc960
	at brut.androlib.res.data.ResType.addResource(ResType.java:66)
	at brut.androlib.res.data.ResType.addResource(ResType.java:55)
	at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:270)
	at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:226)
	at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:156)
	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:118)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:80)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:558)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:72)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:64)
	at brut.androlib.Androlib.getResTable(Androlib.java:68)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:193)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
	at brut.apktool.Main.cmdDecode(Main.java:163)
	at brut.apktool.Main.main(Main.java:81)
➜  Bug1316 
```

I duplicate.

**Comment by kaneawk** [comment]
I have also encountered this problem on Moto Z with Dialer.apk.

Error output:
> 
I: Using Apktool 2.2.1-81b22d-SNAPSHOT on Dialer.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Multiple resources: spec=0x7f0d0000 bool/config_enable_network_mode, config=-mcc310-mnc380
        at brut.androlib.res.data.ResType.addResource(ResType.java:66)
        at brut.androlib.res.data.ResType.addResource(ResType.java:55)
        at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:270)
        at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:226)
        at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:156)
        at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:118)
        at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:80)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:558)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:72)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:64)
        at brut.androlib.Androlib.getResTable(Androlib.java:68)
        at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:193)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
        at brut.apktool.Main.cmdDecode(Main.java:163)
        at brut.apktool.Main.main(Main.java:81)
> 

@iBotPeaches

**Comment by penn5** [comment]
Why is this closed? It hasn't been resolved...
