### ISSUE TITLE
"Invalid value type: 8" on Nougat LG V20

### ISSUE THREAD

**Issue by xpirt** [iBotPeaches/Apktool#1317]
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.0
2. **Operating System (Mac, Linux, Windows)** - Windows 10
3. **APK From? (Playstore, ROM, Other)** - Stock ROM

### Stacktrace/Logcat

```
Exception in thread "main" brut.androlib.AndrolibException: Invalid value type: 8
        at brut.androlib.res.data.value.ResValueFactory.factory(ResValueFactory.java:68)
        at brut.androlib.res.decoder.ResAttrDecoder.decode(ResAttrDecoder.java:32)
        at brut.androlib.res.decoder.AXmlResourceParser.getAttributeValue(AXmlResourceParser.java:373)
        at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValue(XmlPullParserDelegate.java:69)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
        at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:83)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:141)
        at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(ResStreamDecoderContainer.java:33)
        at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:120)
        at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:105)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:262)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:131)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:108)
        at brut.apktool.Main.cmdDecode(Main.java:163)
        at brut.apktool.Main.main(Main.java:81)
```

### Steps to Reproduce
1. `apktool d SomeNougatLGApks.apk`

### Frameworks
LG proprietary frameworks:
framework-res.apk: https://mega.nz/#!OFV3gA5S!ixsoPy9K8Y8d_wB5HjTLgjauwVG3U7RidtAP2ix4gxc
lge-res.apk: https://mega.nz/#!aMURkLzC!73b-H3DnOKCgVhAGvj3zVkxEfHyohYAIarI4n6FdADs

### APK
LGMyPhoneCare.apk: https://mega.nz/#!zA0XXbjZ!Q3SS1bHJq0Cew1TNkqQNWC70LKE_VMfYK3SAx2FYN4c
(but same error on a bunch of other LG apks)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Yes
3. Are you using the latest apktool version? Yes

**Comment by xpirt** [comment]
As of [https://developer.android.com/reference/android/util/TypedValue.html#COMPLEX_MANTISSA_SHIFT](url), this type value is named COMPLEX_MANTISSA_SHIFT.

**Comment by iBotPeaches** [comment]
It is actually `TYPE_DYNAMIC_ATTRIBUTE`, but yes is a bug. Keeping this open for the time being, but this falls under the whole "Android Nougat" support bug reports.

**Comment by xpirt** [comment]
Oh you're right! Just added reference to it and quick built apktool to test, it worked just fine.

Sent pull request.
