### ISSUE TITLE
Multiple resources due to dexguard resource obfuscation

### ISSUE THREAD

**Issue by lmao-0xB5C** [iBotPeaches/Apktool#1320]
### Information
1. **Apktool Version (`apktool -version`)** -2.2.0
2. **Operating System (Mac, Linux, Windows)** - Windows 10
3. **APK From? (Playstore, ROM, Other)** - Action Launcher

Getting this error when decompiling Action Launcher
### Stacktrace/Logcat

```
I: Using Apktool 2.2.0 on AL.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Multiple resources: spec=0x7f090000 plurals/APKTOOL_DUMMYVAL_0x7f090000, config=-sr
        at brut.androlib.res.data.ResType.addResource(ResType.java:66)
        at brut.androlib.res.data.ResType.addResource(ResType.java:55)
        at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:264)
        at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:220)
        at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:156)
        at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:118)
        at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:80)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:558)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:72)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:64)
        at brut.androlib.Androlib.getResTable(Androlib.java:67)
        at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:193)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
        at brut.apktool.Main.cmdDecode(Main.java:163)
        at brut.apktool.Main.main(Main.java:81)
```

**Comment by iBotPeaches** [comment]
Appears to be a new iteration of the Dexguard resource obfuscation.

**Comment by iBotPeaches** [comment]
Sorry years later. I don't have an apk for this and triaging these tickets without it is near next impossible.

Closing.
