### ISSUE TITLE
Still Can't recompile AOSP Nougat SystemUI

### ISSUE THREAD

**Issue by Phone-Guru** [iBotPeaches/Apktool#1330]
Information - This is not a duplicate of the other issue

Apktool Version (apktool -version) -2.2.1
Operating System (Mac, Linux, Windows) -Windows 10 64-bit
APK From? (Playstore, ROM, Other) -AOSP Nougat ROM for SGS4
Stacktrace/Logcat

java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
A subdirectory or file modified-system-apk-files-here already exists.
```
W: Could not find sources
W: C:\Users\Ilan\Desktop\APKToolALBEN5\projects\SystemUI7.apk\res\values\styles.xml:2070: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/TextAppearance.StatusBar'.
W: 
W: C:\Users\Ilan\Desktop\APKToolALBEN5\projects\SystemUI7.apk\res\values\styles.xml:2071: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/TextAppearance.StatusBar'.
W: 
W: C:\Users\Ilan\Desktop\APKToolALBEN5\projects\SystemUI7.apk\res\values\styles.xml:2076: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/TextAppearance.StatusBar'.
W: 
W: C:\Users\Ilan\Desktop\APKToolALBEN5\projects\SystemUI7.apk\res\values\styles.xml:2086: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/TextAppearance.StatusBar'.
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Ilan\AppData\Local\Temp\brut_util_Jar_3733580573281903296.tmp, p, --forced-package-id, 127, --min-sdk-version, 24, --target-sdk-version, 24, --version-code, 24, --version-name, 7.0, -F, C:\Users\Ilan\AppData\Local\Temp\APKTOOL8949540748492794871.tmp, -0, arsc, -0, arsc, -I, C:\Users\Ilan\AppData\Local\apktool\framework\1.apk, -S, C:\Users\Ilan\Desktop\APKToolALBEN5\projects\SystemUI7.apk\res, -M, C:\Users\Ilan\Desktop\APKToolALBEN5\projects\SystemUI7.apk\AndroidManifest.xml]
    at brut.androlib.Androlib.buildResourcesFull(Androlib.java:473)
    at brut.androlib.Androlib.buildResources(Androlib.java:407)
    at brut.androlib.Androlib.build(Androlib.java:306)
    at brut.androlib.Androlib.build(Androlib.java:263)
    at brut.apktool.Main.cmdBuild(Main.java:224)
    at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Ilan\AppData\Local\Temp\brut_util_Jar_3733580573281903296.tmp, p, --forced-package-id, 127, --min-sdk-version, 24, --target-sdk-version, 24, --version-code, 24, --version-name, 7.0, -F, C:\Users\Ilan\AppData\Local\Temp\APKTOOL8949540748492794871.tmp, -0, arsc, -0, arsc, -I, C:\Users\Ilan\AppData\Local\apktool\framework\1.apk, -S, C:\Users\Ilan\Desktop\APKToolALBEN5\projects\SystemUI7.apk\res, -M, C:\Users\Ilan\Desktop\APKToolALBEN5\projects\SystemUI7.apk\AndroidManifest.xml]
    at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:439)
    at brut.androlib.Androlib.buildResourcesFull(Androlib.java:459)
    ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Ilan\AppData\Local\Temp\brut_util_Jar_3733580573281903296.tmp, p, --forced-package-id, 127, --min-sdk-version, 24, --target-sdk-version, 24, --version-code, 24, --version-name, 7.0, -F, C:\Users\Ilan\AppData\Local\Temp\APKTOOL8949540748492794871.tmp, -0, arsc, -0, arsc, -I, C:\Users\Ilan\AppData\Local\apktool\framework\1.apk, -S, C:\Users\Ilan\Desktop\APKToolALBEN5\projects\SystemUI7.apk\res, -M, C:\Users\Ilan\Desktop\APKToolALBEN5\projects\SystemUI7.apk\AndroidManifest.xml]
    at brut.util.OS.exec(OS.java:95)
    at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:433)
    ... 6 more
```

Steps to Reproduce

apktoold apktool b
Frameworks

If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(.apks that live in /system/framework or /system/priv-app)

APK

If this APK can be freely shared, please upload/attach a link to it.

Questions to ask before submission

Have you tried apktool d, apktool b without changing anything? YES
If you are trying to install a modified apk, did you resign it?
Are you using the latest apktool version? YES

**Comment by iBotPeaches** [comment]
I'm going to need frameworks and the offending apk (SystemUI.apk) to diagnose this any further. This is usually an outdated framework or old written APK that no longer conforms to the newest aapt binary standards.

Apktool isn't met to fix apks so sometimes manual intervention will be required to rebuild some applications, especially with those that have complicated dependencies on other frameworks.

**Comment by Phone-Guru** [comment]
[SystemUI.zip](https://github.com/iBotPeaches/Apktool/files/494266/SystemUI.zip)

**Comment by Phone-Guru** [comment]
Files uploaded

**Comment by Escapingbug** [comment]
I have the same issus as well..Uploaded SystemUi and framework.res used, still can't recompile.

**Comment by iBotPeaches** [comment]
```
➜  Bug1330 apktool if framework-res.apk -t 1330
I: Framework installed to: /home/ibotpeaches/.local/share/apktool/framework/1-1330.apk
➜  Bug1330 apktool d SystemUI.apk -t 1330
I: Using Apktool 2.2.1-4c93cb-SNAPSHOT on SystemUI.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1-1330.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1330 apktool b SystemUI
I: Using Apktool 2.2.1-4c93cb-SNAPSHOT
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
I: Building apk file...
I: Copying unknown files/dir...
➜  Bug1330 
```

Could not duplicate. Await the 2.2.1 release.

**Comment by Phone-Guru** [comment]
I've tried 2.2.1, it still doesn't work.  Can you please attach the apktool.jar that you used?

**Comment by iBotPeaches** [comment]
If you have the snapshot of 2.2.1 run, `apktool empty-framework-dir --force`

**Comment by Phone-Guru** [comment]
Tried it, it didn't work

**Comment by Fielder2016** [comment]
are you loading the correct Framework? ( apktool if framework-res.apk -t 1330 )
