### ISSUE TITLE
ADK Editor Java.io... Expected 0x001c0001 got 0x00000001

### ISSUE THREAD

**Issue by parind** [iBotPeaches/Apktool#1332]
Tried on all 2.x.x versions. Still encounter this. The APK name is ADK Editor v1.5.5. Actually need to translate but due to this problem I couldnt.
```
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:52)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:538)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:63)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:55)
	at brut.androlib.Androlib.getResTable(Androlib.java:64)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:209)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:92)
	at brut.apktool.Main.cmdDecode(Main.java:165)
	at brut.apktool.Main.main(Main.java:81)
Caused by: java.io.IOException: Expected: 0x001c0001, got: 0x00000001
	at brut.util.ExtDataInput.skipCheckChunkTypeInt(ExtDataInput.java:75)
	at brut.util.ExtDataInput.skipCheckChunkTypeInt(ExtDataInput.java:73)
	at brut.androlib.res.decoder.StringBlock.read(StringBlock.java:44)
	at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:73)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
	... 8 more
I: Using Apktool 2.0.0 on adk_editor_1.5.5.apk
I: Loading resource table...
```

The APK Link is posted below in the second post. Please @iBotPeaches If u can decompile this with any setting, let me know.

**Comment by parind** [comment]
Here is the link: https://drive.google.com/file/d/0B6MdaSw1G4vdSUtldmZQZ3gyOVE/view?usp=drivesdk
Knowing that Classes.dex is a StubApp, I am only interested in Resources.

**Comment by iBotPeaches** [comment]
Confirmed.

**Comment by parind** [comment]
Any Progress @iBotPeaches

**Comment by iBotPeaches** [comment]
I confirmed the ticket. I did not make any progress towards a resolution. If/when that happens this ticket will be updated.

Accepting PRs if you write a fix.

**Comment by xpirt** [comment]
@parind try this, should fix the issue.

[apktool-2.2.1-dirty_issue-1332.jar](https://mega.nz/#!iZdDwKpA!7B3xorpgfu3fXJTI-9opC8ZBql69QpVtTf61YUQoxW4)

**Comment by parind** [comment]
@xpirt Wow that was quick. Thank You Xpirt now I may able to convert it to English. Thank you @xpirt and @ibotpeaches
And I saw the error. From Xpirt's fork. It was in ExtDataInput [brut.j.util/src/main/java/brut/util/ExtDataInput.java] @iBotpeaches you might have to fix this to make it stable for some apks.

**Comment by iBotPeaches** [comment]
@xpirt I'll take a look. Will have to confirm if APK is still readable and buildable and that we aren't just skipping valid data blocks.

Thanks for investigating!

**Comment by parind** [comment]
@ibotpeaches The Apk is Readable and buildable.
In the other versions of Apktool The resources.arsc couldnt be decompiled. Whereas in this it worked like a charm. Btw there was only one diff in the dirty version

**Comment by iBotPeaches** [comment]
@parind Yes, I see the diff. That is such a low level function though whose purpose is to check expected data and changing it makes me slightly nervous as it will move expected failures further along in the chain.

Just needs some investigation.

**Comment by parind** [comment]
@iBotPeaches Do you have any idea how can I dump the original dex in case of a Protected Apk using the com.qihoo.util.StubApplication protection. If you know just let me know.

**Comment by yekta88** [comment]
plese crack adk editor
