### ISSUE TITLE
Unable to decode this APK

### ISSUE THREAD

**Issue by CaledoniaProject** [iBotPeaches/Apktool#1333]
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.0
2. **Operating System (Mac, Linux, Windows)** - Mac
3. **APK From? (Playstore, ROM, Other)** - Other

### Stacktrace/Logcat

```
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/xxxx/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
Exception in thread "main" java.lang.NullPointerException
	at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:58)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:516)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:267)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:131)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:108)
	at brut.apktool.Main.cmdDecode(Main.java:163)
	at brut.apktool.Main.main(Main.java:81)
```

### Steps to Reproduce
1. `apktool d XXX.apk`

### APK
If this APK can be freely shared, please upload/attach a link to it.

http://qn-apk.wdjcdn.com/6/25/20c935b140e4e25b119ac73edd797256.apk

**Comment by iBotPeaches** [comment]
```
➜  Bug1333 apktool d 20c935b140e4e25b119ac73edd797256.apk 
I: Using Apktool 2.2.1-4c93cb-SNAPSHOT on 20c935b140e4e25b119ac73edd797256.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes4.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1333 apktool b 20c935b140e4e25b119ac73edd797256
I: Using Apktool 2.2.1-4c93cb-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes4 folder into classes4.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
➜  Bug1333 
```

Could not duplicate.
