### ISSUE TITLE
How to fix this error?

### ISSUE THREAD

**Issue by userdsp** [iBotPeaches/Apktool#1339]
### Information
1. **Apktool Version (`apktool -version`)** -2.2.0
2. **Operating System (Mac, Linux, Windows)** -NetHunter-kali linux
3. **APK From? (Playstore, ROM, Other)** -Paystore

### Stacktrace/Logcat

```
Include stacktrace here
```
maling classes.dex...

root@kali:~/backdoor-apk/backdoor-apk# apktool b CCleaner
I: Using Apktool 2.2.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: /tmp/brut_util_Jar_357642935668388323.tmp: 1: /tmp/brut_util_Jar_357642935668388323.tmp: Syntax error: word unexpected (expecting ")")
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 2): [/tmp/brut_util_Jar_357642935668388323.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 19, --version-code, 71411557, --version-name, v1.15.57, -F, /tmp/APKTOOL2721858424829424455.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/backdoor-apk/backdoor-apk/CCleaner/res, -M, /root/backdoor-apk/backdoor-apk/CCleaner/AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:473)
        at brut.androlib.Androlib.buildResources(Androlib.java:407)
        at brut.androlib.Androlib.build(Androlib.java:306)
        at brut.androlib.Androlib.build(Androlib.java:263)
        at brut.apktool.Main.cmdBuild(Main.java:224)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 2): [/tmp/brut_util_Jar_357642935668388323.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 19, --version-code, 71411557, --version-name, v1.15.57, -F, /tmp/APKTOOL2721858424829424455.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/backdoor-apk/backdoor-apk/CCleaner/res, -M, /root/backdoor-apk/backdoor-apk/CCleaner/AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:439)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:459)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 2): [/tmp/brut_util_Jar_357642935668388323.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 19, --version-code, 71411557, --version-name, v1.15.57, -F, /tmp/APKTOOL2721858424829424455.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/backdoor-apk/backdoor-apk/CCleaner/res, -M, /root/backdoor-apk/backdoor-apk/CCleaner/AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:433)
        ... 6 more
### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Eror is when i use apktool b apk
2. Yes

**Comment by iBotPeaches** [comment]
Do you use some non-standard shell? I use fish/zsh/bourne and this error looks connected to a bash problem.

**Comment by userdsp** [comment]
I am using nethunter terminal

**Comment by userdsp** [comment]
shell is "/system/bin/sh -"

**Comment by userdsp** [comment]
I am trying now from my PC over ssh. Must be ok if the problem is the shell, correct?

**Comment by userdsp** [comment]
Can you help me to fix this error?

**Comment by iBotPeaches** [comment]
I could not find anything across the shells I use and tested. This seems to be a support problem vs a bug in the tool. Closing this.
