### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by FynnHan** [iBotPeaches/Apktool#1342]
at java.util.Properties$LineReader.readLine(Properties.java:434)
	at java.util.Properties.load0(Properties.java:353)
	at java.util.Properties.load(Properties.java:341)
	at brut.androlib.ApktoolProperties.loadProps(ApktoolProperties.java:46)
	at brut.androlib.ApktoolProperties.get(ApktoolProperties.java:37)
	at brut.androlib.ApktoolProperties.get(ApktoolProperties.java:32)
	at brut.androlib.Androlib.getVersion(Androlib.java:701)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:94)
	at brut.apktool.Main.cmdDecode(Main.java:188)
	at brut.apktool.Main.main(Main.java:103)

**Comment by OsBelief** [comment]
I met the same problem, how to solve
