### ISSUE TITLE
Could not load resources.arsc from file

### ISSUE THREAD

**Issue by FynnHan** [iBotPeaches/Apktool#1343]
- brut.androlib.AndrolibException:

 Could not load resources.arsc from file: C:\Users\zpj\AppData\Local\apktool\framework\1.apk
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:560)
	at brut.androlib.res.AndrolibResources.loadFrameworkPkg(AndrolibResources.java:124)
	at brut.androlib.res.data.ResTable.getPackage(ResTable.java:83)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:66)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:62)
	at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferenceValue.java:62)
	at brut.androlib.res.data.value.ResReferenceValue.referentIsNull(ResReferenceValue.java:73)
	at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:48)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:516)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:267)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:132)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:108)
	at brut.apktool.Main.cmdDecode(Main.java:162)
	at brut.apktool.Main.main(Main.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

- Caused

 by: brut.directory.DirectoryException: java.util.zip.ZipException: zip file is empty
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:55)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:38)
	at brut.androlib.res.util.ExtFile.getDirectory(ExtFile.java:55)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:557)
	... 18 more

- Caused

 by: java.util.zip.ZipException: zip file is empty
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:53)
	... 21 more

**Comment by iBotPeaches** [comment]
Delete the file at `C:\Users\zpj\AppData\Local\apktool\framework\1.apk`.
