### ISSUE TITLE
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file

### ISSUE THREAD

**Issue by CODeRUS** [iBotPeaches/Apktool#1346]
### Information
1. **Apktool Version 2.2.0** -
2. **Operating System Windows 10 x64** -
3. **APK From Playstore** -

### Stacktrace/Logcat

```
C:\Users\coder\Downloads\apktool>apktool d com.alibaba.aliexpresshd-2.apk
I: Using Apktool 2.2.0 on com.alibaba.aliexpresshd-2.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:52)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:558)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:72)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:64)
        at brut.androlib.Androlib.getResTable(Androlib.java:67)
        at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:193)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
        at brut.apktool.Main.cmdDecode(Main.java:163)
        at brut.apktool.Main.main(Main.java:81)
Caused by: java.io.IOException: Expected: 0x001c0001, got: 0x00000001
        at brut.util.ExtDataInput.skipCheckChunkTypeInt(ExtDataInput.java:75)
        at brut.util.ExtDataInput.skipCheckChunkTypeInt(ExtDataInput.java:73)
        at brut.androlib.res.decoder.StringBlock.read(StringBlock.java:44)
        at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:75)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
        ... 8 more
```

### Steps to Reproduce
1. `apktool d com.alibaba.aliexpresshd-2.apk`

### APK
APK can be easily fetched from https://play.google.com/store/apps/details?id=com.alibaba.aliexpresshd

**Comment by iBotPeaches** [comment]
```
➜  Bug1346 apktool d com.alibaba.aliexpresshd.apk 
I: Using Apktool 2.2.1-4c93cb-SNAPSHOT on com.alibaba.aliexpresshd.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1346 
```

Wait for the 2.2.1 release.

**Comment by CODeRUS** [comment]
sure, thanks
