### ISSUE TITLE
Cannot Decompile And Recompile [FATAL EXCEPTION]

### ISSUE THREAD

**Issue by Nattas** [iBotPeaches/Apktool#1348]
### Information
1. **Apktool Version (2.2.1)** -
2. **Operating System (Linux)** -
3. **APK From? (Playstore, ROM, Other)** -

### Stacktrace/Logcat
```
I: Using Apktool 2.2.1
I: Checking whether sources has changed...
[Fatal Error] AndroidManifest.xml:1:1: Content is not allowed in prolog.
I: Checking whether resources has changed...
I: Building apk file...
Exception in thread "main" brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 139): [/tmp/brut_util_Jar_5722015575492230134.tmp, p, -F, /home/user/Desktop/pixel/dist/app-debug.apk, -0, arsc, -0, arsc, /home/user/Desktop/pixel/build/apk]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:439)
	at brut.androlib.Androlib.buildApk(Androlib.java:675)
	at brut.androlib.Androlib.build(Androlib.java:315)
	at brut.androlib.Androlib.build(Androlib.java:264)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.common.BrutException: could not exec (exit code = 139): [/tmp/brut_util_Jar_5722015575492230134.tmp, p, -F, /home/user/Desktop/pixel/dist/app-debug.apk, -0, arsc, -0, arsc, /home/user/Desktop/pixel/build/apk]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:433)
	... 5 more
```

### Steps to Reproduce
1. `apktool d pixel.apk -r`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
http://www.apkmirror.com/apk/google-inc/pixel-launcher/pixel-launcher-7-1-1-3359438-release/pixel-launcher-7-1-1-3359438-android-apk-download/
### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by iBotPeaches** [comment]
Can I have output of `uname -a`?

**Comment by Nattas** [comment]
Linux nadav 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Nattas** [comment]
wont decompile without -r and wont recompile at all

**Comment by Nattas** [comment]
root@nadav:/home/nadav/Desktop# apktool d app-debug.apk -o app -f -r
I: Using Apktool 2.2.1 on app-debug.apk
I: Copying raw resources...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
root@nadav:/home/nadav/Desktop# apktool b app
I: Using Apktool 2.2.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
[Fatal Error] AndroidManifest.xml:1:1: Content is not allowed in prolog.
I: Checking whether resources has changed...
I: Copying raw resources...
I: Building apk file...
Exception in thread "main" brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 139): [/tmp/brut_util_Jar_3780784690587722521.tmp, p, -F, /home/nadav/Desktop/app/dist/app-debug.apk, -0, arsc, -0, arsc, /home/nadav/Desktop/app/build/apk]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:439)
	at brut.androlib.Androlib.buildApk(Androlib.java:675)
	at brut.androlib.Androlib.build(Androlib.java:315)
	at brut.androlib.Androlib.build(Androlib.java:264)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.common.BrutException: could not exec (exit code = 139): [/tmp/brut_util_Jar_3780784690587722521.tmp, p, -F, /home/nadav/Desktop/app/dist/app-debug.apk, -0, arsc, -0, arsc, /home/nadav/Desktop/app/build/apk]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:433)
	... 5 more



I Guess... idk if it helps.

**Comment by Nattas** [comment]
everything works just fine,had a corrupted binary
