### ISSUE TITLE
Problem with decompilation apk file.

### ISSUE THREAD

**Issue by aleks921** [iBotPeaches/Apktool#1350]
--------------------------------------------------
Batch ApkTool                : 3.4.5
SMALI                        : smali-2.1.2.jar
Уровень API                  : 23
APKTOOL                      : apktool_2.1.1.jar
Экспертный режим             : НЕТ
Подпись                      : НЕТ
--------------------------------------------------

[*] Декомпиляция 123.apk
I: Using Apktool 2.1.1 on 123.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Multiple res specs: attr/2
	at brut.androlib.res.data.ResTypeSpec.addResSpec(ResTypeSpec.java:78)
	at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:256)
	at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:217)
	at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:153)
	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:115)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:77)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:555)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:72)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:64)
	at brut.androlib.Androlib.getResTable(Androlib.java:64)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:193)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
	at brut.apktool.Main.cmdDecode(Main.java:163)
	at brut.apktool.Main.main(Main.java:81)
[*] ---> Ошибка декомпиляции 123.apk

**Comment by iBotPeaches** [comment]
This should have been fixed with - https://github.com/iBotPeaches/Apktool/commit/567907b187ad2f78b3564d0a0405e3b207832e17

#894 

This was fixed in 2.2.0 and according to your stacktrace, you are using 2.1.1. So closing this.
