### ISSUE TITLE
No resource identifier found for attribute 'resizeableActivity' in package 'android'

### ISSUE THREAD

**Issue by evildog1** [iBotPeaches/Apktool#1355]
### Information
1. **Apktool Version** 2.2.1
2. **Operating System** Windows
3. **APK From?** Other

### Stacktrace/Logcat

```
F:\java -jar apktool.jar b b1714-mobogram_new new
I: Using Apktool 2.2.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: F:\b1714-mobogram_new\AndroidManifest.xml:151: error: No resource identifier found for attribute 'resizeableActivity' in package 'android'
W:
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\q\AppData\Local\Temp\brut_util_Jar_7809292983443974712.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 24, --version-code, 85195, --version-name, T3.13.1-M9.3, -F, C:\Users\q\AppData\Local\Temp\APKTOOL6397967757207518600.tmp, -0, arsc, -0, arsc, -I, C:\Users\q\AppData\Local\apktool\framework\1.apk, -S, F:\b1714-mobogram_new\res, -M, F:\b1714-mobogram_new\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:478)
        at brut.androlib.Androlib.buildResources(Androlib.java:412)
        at brut.androlib.Androlib.build(Androlib.java:311)
        at brut.androlib.Androlib.build(Androlib.java:264)
        at brut.apktool.Main.cmdBuild(Main.java:227)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\q\AppData\Local\Temp\brut_util_Jar_7809292983443974712.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 24, --version-code, 85195, --version-name, T3.13.1-M9.3, -F, C:\Users\q\AppData\Local\Temp\APKTOOL6397967757207518600.tmp, -0, arsc, -0, arsc, -I, C:\Users\q\AppData\Local\apktool\framework\1.apk, -S, F:\b1714-mobogram_new\res, -M, F:\b1714-mobogram_new\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:439)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:464)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\q\AppData\Local\Temp\brut_util_Jar_7809292983443974712.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 24, --version-code, 85195, --version-name, T3.13.1-M9.3, -F, C:\Users\q\AppData\Local\Temp\APKTOOL6397967757207518600.tmp, -0, arsc, -0, arsc, -I, C:\Users\q\AppData\Local\apktool\framework\1.apk, -S, F:\b1714-mobogram_new\res, -M, F:\b1714-mobogram_new\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:433)
        ... 6 more
```

### Steps to Reproduce
1. Install framework
2. `apktool d b1714-mobogram_new.apk`
3. `apktool b b1714-mobogram_new newapk`

### Frameworks
http://usersdownload.com/69cfbkr7fm8j.html

### APK
http://usersdownload.com/n79xxsudav1w.html

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Can't answer this question, since apktool unable to recompile
3. Are you using the latest apktool version? Yes, also tried v2.1.1

**Comment by iBotPeaches** [comment]
So what is happening here is the framework attached does not have the resources for this application. This application looks like a regular ole application from the Google Play Store which means it has no dependencies on any OEM framework.

I skip the attached framework and use the internal framework in Apktool and no errors.

```
➜  Bug1355 apktool d b1714-mobogram_new.apk -f
I: Using Apktool 2.2.2-7c6c7a-SNAPSHOT on b1714-mobogram_new.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1355 apktool b b1714-mobogram_new
I: Using Apktool 2.2.2-7c6c7a-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
➜  Bug1355 
```

**Comment by evildog1** [comment]
Thanks for the infomation

**Comment by wang-bin** [comment]
the error still exists in 2.2.2
