### ISSUE TITLE
SamsungCamera force closing after decompiling / recompiling

### ISSUE THREAD

**Issue by Gi4nnelli** [iBotPeaches/Apktool#1356]
I'm quite new to modding apps but I ran into a problem. When trying to recompile SamsungCamera4.apk I get 4 warnings:

W: warning: string 'GPS_msg' has no default translation.
W: warning: string 'editableshortcut_helptext' has no default translation.
W: warning: string 'reset_dialog_msg' has no default translation.

At first I just ignored it and tried the apk. When trying to run the apk it just force closes and says camera has stopped working.

### Information
1. Apktool Version 2.2.1 
2. Operating System Windows 10 -
3. APK From? Samsung Galaxy A5 2016 stock Touchwizz ROM

### Stacktrace/Logcat
---- 1 nov. 2016 17:40:16 ----
```
11-01 17:35:06.150  3740  3740 I Timeline: Timeline: Activity_launch_request id:com.sec.android.app.camera time:57201

11-01 17:35:06.250  8353  8353 W SELinux : SELinux: seapp_context_lookup: seinfo=default, level=s0:c512,c768, pkgname=com.sec.android.app.camera 

11-01 17:35:06.320  8353  8353 W System  : ClassLoader referenced unknown path: /data/app/com.sec.android.app.camera-1/lib/arm

11-01 17:35:06.750  2360  3976 I CameraService: CameraService::connect call (PID 8353 "com.sec.android.app.camera", camera ID 0) for HAL version default and Camera API version 1

11-01 17:35:06.770  8353  8353 E AndroidRuntime: Process: com.sec.android.app.camera, PID: 8353

11-01 17:35:06.770  8353  8353 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sec.android.app.camera/com.sec.android.app.camera.Camera}: java.lang.SecurityException: Permission Denial: get/set setting for user asks to run as user -2 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL

11-01 17:35:06.770  8353  8353 E AndroidRuntime: 	at com.sec.android.app.camera.Camera.initializeGLSurfaceView(Camera.java:5243)

11-01 17:35:06.770  8353  8353 E AndroidRuntime: 	at com.sec.android.app.camera.Camera.onCreate(Camera.java:7198)

11-01 17:35:47.400  9516  9616 I PLM     : App title : Camera & activity name : com.sec.android.app.camera.Camera_com.sec.android.app.camera

11-01 17:36:30.300  3740  3740 I Timeline: Timeline: Activity_launch_request id:com.sec.android.app.camera time:141351

11-01 17:36:30.320  2677  5517 I ActivityManager: Start proc 10036:com.sec.android.app.camera/u0a37 for activity com.sec.android.app.camera/.Camera

11-01 17:36:30.330 10036 10036 W SELinux : SELinux: seapp_context_lookup: seinfo=default, level=s0:c512,c768, pkgname=com.sec.android.app.camera 

11-01 17:36:30.420 10036 10036 W System  : ClassLoader referenced unknown path: /data/app/com.sec.android.app.camera-1/lib/arm

11-01 17:36:30.820  2360  3204 I CameraService: CameraService::connect call (PID 10036 "com.sec.android.app.camera", camera ID 0) for HAL version default and Camera API version 1

11-01 17:36:30.840 10036 10036 E AndroidRuntime: Process: com.sec.android.app.camera, PID: 10036

11-01 17:36:30.840 10036 10036 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sec.android.app.camera/com.sec.android.app.camera.Camera}: java.lang.SecurityException: Permission Denial: get/set setting for user asks to run as user -2 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL

11-01 17:36:30.840 10036 10036 E AndroidRuntime: 	at com.sec.android.app.camera.Camera.initializeGLSurfaceView(Camera.java:5243)

11-01 17:36:30.840 10036 10036 E AndroidRuntime: 	at com.sec.android.app.camera.Camera.onCreate(Camera.java:7198)

11-01 17:36:30.840  2677  3526 W ActivityManager:   Force finishing activity com.sec.android.app.camera/.Camera

11-01 17:36:31.150  2677  3526 I WindowManager: Screenshot max retries 4 of Token{88289c9 ActivityRecord{cb485d0 u0 com.sec.android.app.camera/.Camera t6 f}} appWin=Window{882432 u0 d0 p2677 Starting com.sec.android.app.camera} drawState=4

11-01 17:36:31.650  2677  2749 W ActivityManager: Activity pause timeout for ActivityRecord{cb485d0 u0 com.sec.android.app.camera/.Camera t6 f}

11-01 17:36:32.980  2677  3738 I ActivityManager: Process com.sec.android.app.camera (pid 10036)(adj 9) has died(41,489)

11-01 17:36:43.720  3740  3740 I Timeline: Timeline: Activity_launch_request id:com.sec.android.app.camera time:154778

11-01 17:36:43.750 10089 10089 W SELinux : SELinux: seapp_context_lookup: seinfo=default, level=s0:c512,c768, pkgname=com.sec.android.app.camera 

11-01 17:36:43.750  2677  3442 I ActivityManager: Start proc 10089:com.sec.android.app.camera/u0a37 for activity com.sec.android.app.camera/.Camera

11-01 17:36:43.830 10089 10089 W System  : ClassLoader referenced unknown path: /data/app/com.sec.android.app.camera-1/lib/arm

11-01 17:36:44.150  2360  3975 I CameraService: CameraService::connect call (PID 10089 "com.sec.android.app.camera", camera ID 0) for HAL version default and Camera API version 1

11-01 17:36:44.160 10089 10089 E AndroidRuntime: Process: com.sec.android.app.camera, PID: 10089

11-01 17:36:44.160 10089 10089 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sec.android.app.camera/com.sec.android.app.camera.Camera}: java.lang.SecurityException: Permission Denial: get/set setting for user asks to run as user -2 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL

11-01 17:36:44.160 10089 10089 E AndroidRuntime: 	at com.sec.android.app.camera.Camera.initializeGLSurfaceView(Camera.java:5243)

11-01 17:36:44.160 10089 10089 E AndroidRuntime: 	at com.sec.android.app.camera.Camera.onCreate(Camera.java:7198)

11-01 17:36:44.160  2677  2693 W ActivityManager:   Force finishing activity com.sec.android.app.camera/.Camera

11-01 17:36:44.680  2677  2749 W ActivityManager: Activity pause timeout for ActivityRecord{141dfab u0 com.sec.android.app.camera/.Camera t7 f}

11-01 17:36:45.500  2677  3736 I ActivityManager: Process com.sec.android.app.camera (pid 10089)(adj 9) has died(41,480)

11-01 17:37:22.110  3740  3740 I Timeline: Timeline: Activity_launch_request id:com.sec.android.app.camera time:193168

11-01 17:37:22.140 10169 10169 W SELinux : SELinux: seapp_context_lookup: seinfo=default, level=s0:c512,c768, pkgname=com.sec.android.app.camera 

11-01 17:37:22.140  2677  2693 I ActivityManager: Start proc 10169:com.sec.android.app.camera/u0a37 for activity com.sec.android.app.camera/.Camera

11-01 17:37:22.210 10169 10169 W System  : ClassLoader referenced unknown path: /data/app/com.sec.android.app.camera-1/lib/arm

11-01 17:37:22.530  2360  3976 I CameraService: CameraService::connect call (PID 10169 "com.sec.android.app.camera", camera ID 0) for HAL version default and Camera API version 1

11-01 17:37:22.540 10169 10169 E AndroidRuntime: Process: com.sec.android.app.camera, PID: 10169

11-01 17:37:22.540 10169 10169 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sec.android.app.camera/com.sec.android.app.camera.Camera}: java.lang.SecurityException: Permission Denial: get/set setting for user asks to run as user -2 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL

11-01 17:37:22.540 10169 10169 E AndroidRuntime: 	at com.sec.android.app.camera.Camera.initializeGLSurfaceView(Camera.java:5243)

11-01 17:37:22.540 10169 10169 E AndroidRuntime: 	at com.sec.android.app.camera.Camera.onCreate(Camera.java:7198)

11-01 17:37:22.540  2677  4035 W ActivityManager:   Force finishing activity com.sec.android.app.camera/.Camera

11-01 17:37:23.070  2677  2749 W ActivityManager: Activity pause timeout for ActivityRecord{84264cd u0 com.sec.android.app.camera/.Camera t8 f}

11-01 17:37:24.140  2677  3737 I ActivityManager: Process com.sec.android.app.camera (pid 10169)(adj 9) has died(40,482)

11-01 17:39:14.780  3740  3740 I Timeline: Timeline: Activity_launch_request id:com.sec.android.app.camera time:305832

11-01 17:39:14.800  2677  3526 I ActivityManager: Start proc 10900:com.sec.android.app.camera/u0a37 for activity com.sec.android.app.camera/.Camera

11-01 17:39:14.810 10900 10900 W SELinux : SELinux: seapp_context_lookup: seinfo=default, level=s0:c512,c768, pkgname=com.sec.android.app.camera 

11-01 17:39:14.870 10900 10900 W System  : ClassLoader referenced unknown path: /data/app/com.sec.android.app.camera-1/lib/arm

11-01 17:39:15.190  2360  3977 I CameraService: CameraService::connect call (PID 10900 "com.sec.android.app.camera", camera ID 0) for HAL version default and Camera API version 1

11-01 17:39:15.190 10900 10900 E AndroidRuntime: Process: com.sec.android.app.camera, PID: 10900

11-01 17:39:15.190 10900 10900 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sec.android.app.camera/com.sec.android.app.camera.Camera}: java.lang.SecurityException: Permission Denial: get/set setting for user asks to run as user -2 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL

11-01 17:39:15.190 10900 10900 E AndroidRuntime: 	at com.sec.android.app.camera.Camera.initializeGLSurfaceView(Camera.java:5243)

11-01 17:39:15.190 10900 10900 E AndroidRuntime: 	at com.sec.android.app.camera.Camera.onCreate(Camera.java:7198)

11-01 17:39:15.200  2677  3629 W ActivityManager:   Force finishing activity com.sec.android.app.camera/.Camera

11-01 17:39:15.720  2677  2749 W ActivityManager: Activity pause timeout for ActivityRecord{43db00e u0 com.sec.android.app.camera/.Camera t13 f}

11-01 17:39:16.600  2677  4035 I ActivityManager: Process com.sec.android.app.camera (pid 10900)(adj 9) has died(87,501)
```
---- 1 nov. 2016 17:40:16 ----

```
C:\apktool>apktool if framework-res.apk
I: Framework installed to: C:\Users\Max\AppData\Local\apktool\framework\1.apk

C:\apktool>apktool if twframework-res.apk
'apktool' is not recognized as an internal or external command,
operable program or batch file.

C:\apktool>apktool if twframework-res.apk
I: Framework installed to: C:\Users\Max\AppData\Local\apktool\framework\2.apk

C:\apktool>d SamsungCamera4.apk -o decompiled
'd' is not recognized as an internal or external command,
operable program or batch file.

C:\apktool>apktool d SamsungCamera4.apk -o decompiled
I: Using Apktool 2.2.1 on SamsungCamera4.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Max\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
```
// After this I editted something in the dimens.xml//
```
C:\apktool>apktool b decompiled -o SamsungCamera5.apk
I: Using Apktool 2.2.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: warning: string 'GPS_msg' has no default translation.
W: warning: string 'editableshortcut_helptext' has no default translation.
W: warning: string 'reset_dialog_msg' has no default translation.
I: Building apk file...
I: Copying unknown files/dir...
```

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? YES
2. If you are trying to install a modified apk, did you resign it? YES and NO, didn't make a difference. Also, when I don't edit the Manifest, I shouldn't have to resign right?
3. Are you using the latest apktool version? YES, also tried versions 2.1.1 and 2.0.0

Framework-resp:
https://www.dropbox.com/s/34h6cjr86mgahll/framework-res.apk?dl=0
twframework-resp:
https://www.dropbox.com/s/nxvfmkwytkkraqz/twframework-res.apk?dl=0
Logcat:
https://www.dropbox.com/s/c2ko7868xr5utvn/Log_2016-11-01_17-40-16.txt?dl=0
SamsungCamera4 original apk:
https://www.dropbox.com/s/yadlas5plbw3cnd/SamsungCamera4.apk?dl=0
SamsungCamera4 modded apk:
https://www.dropbox.com/s/4336skyf1y2quzc/SamsungCamera4mod.apk?dl=0

**Comment by iBotPeaches** [comment]
These errors have to do with a lack of a permission.

```
11-01 17:35:06.770  8353  8353 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sec.android.app.camera/com.sec.android.app.camera.Camera}: java.lang.SecurityException: Permission Denial: get/set setting for user asks to run as user -2 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL
```

I don't have a Samsung anymore, see this - https://plus.google.com/+ConnorTumbleson/posts/6u5pnTLYVzD

So my ability to diagnose this and/or investigate is going to be quite limited since nothing seems to be wrong on apktool's side.

**Comment by Gi4nnelli** [comment]
I see, what I also noticed a difference In apk file size. Might that explain why my permission gets denied, or is it just a permission problem? For now I will carry on and let you know if I make any progress.

**Comment by iBotPeaches** [comment]
I don't have samsung to triage this effectively. Sorry for the 4+ year delay, but as shown here. The ticket wasn't going anywhere and I want to have any good backlog to fix issues. I need to lay some down in the past.

Closing.
