### ISSUE TITLE
Decompile error: Invalid CEN header (bad signature)

### ISSUE THREAD

**Issue by evildog1** [iBotPeaches/Apktool#1357]
### Information
1. **Apktool Version** 2.2.1
2. **Operating System** Windows 10
3. **APK From?** Other

### Stacktrace/Logcat

```
F:\apktool>apktool d kingouser.apk
I: Using Apktool 2.2.1 on kingouser.apk
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: java.util.zip.ZipException: invalid CEN header (bad signature)
        at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:272)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:96)
        at brut.apktool.Main.cmdDecode(Main.java:166)
        at brut.apktool.Main.main(Main.java:81)
Caused by: brut.directory.DirectoryException: java.util.zip.ZipException: invalid CEN header (bad signature)
        at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:55)
        at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:38)
        at brut.androlib.res.util.ExtFile.getDirectory(ExtFile.java:55)
        at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:270)
        ... 3 more
Caused by: java.util.zip.ZipException: invalid CEN header (bad signature)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:53)
        ... 6 more
```

### Steps to Reproduce
1. `apktool d kingouser.apk `

### Frameworks
http://usersdownload.com/69cfbkr7fm8j.html

### APK
http://usersdownload.com/xe1ze43by5pl.html

### Questions to ask before submission
Are you using the latest apktool version? Yes 2.2.1

**Comment by evildog1** [comment]
Nevermind. The APK were corrupted. Please close this issue
