### ISSUE TITLE
apktool build failed: Argument list too long

### ISSUE THREAD

**Issue by WenhaiLin** [iBotPeaches/Apktool#1368]
It might be because there are too many files inside the `assets` directory.

`AndrolibResources.java --> aaptPackage --> apkOptions.doNotCompress `

### Version

apktool 2.2.1    
Mac

### Stacktrace/Logcat

I: Using Apktool 2.2.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec: [/var/folders/s9/9kkqryfx3d78w4_br0nvr93m0000gn/T/brut_util_Jar_8293313825619114639.tmp, p, --forced-package-id, 127, --min-sdk-version, 8, --target-sdk-version, 8, --version-code, 93042, --version-name, 5.0.016, -F, /var/folders/s9/9kkqryfx3d78w4_br0nvr93m0000gn/T/APKTOOL1289103720394523856.tmp, -0, arsc, -0, zip, -0, gzip, -0, assets/libclearsdk.gzip.ver, ........【too many files】.........
-I, /Users/ll/Library/apktool/framework/1.apk, -S, /Users/ll/soft/apk_decode/res, -M, /Users/ll/soft/apk_decode/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:97)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:433)
	... 6 more
Caused by: java.io.IOException: Cannot run program "/var/folders/s9/9kkqryfx3d78w4_br0nvr93m0000gn/T/brut_util_Jar_8293313825619114639.tmp": error=7, Argument list too long
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at brut.util.OS.exec(OS.java:90)
	... 7 more
Caused by: java.io.IOException: error=7, Argument list too long
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 8 more

### Steps to Reproduce
1. `apktool d xxxx.apk`
2. `apktool b xxxx`

**Comment by iBotPeaches** [comment]
#1272 seems Windows and Mac is affected. I need to rewrite the staged insertion of these files to make command length smaller.
