### ISSUE TITLE
No resource identifier found for attribute 'networkSecurityConfig' in package 'android'

### ISSUE THREAD

**Issue by xaywe** [iBotPeaches/Apktool#1371]
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.1
2. **Operating System (Mac, Linux, Windows)** -Mac
3. **APK From? (Playstore, ROM, Other)** - Other

### Stacktrace/Logcat

I: Using Apktool 2.2.1
I: Smaling smali folder into classes.dex...
I: Building resources...
W: /tmp/apktool/result/AndroidManifest.xml:15: error: No resource identifier found for attribute 'networkSecurityConfig' in package 'android'
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/lp/cwd098392572b2w4gf0474lc0000gn/T/brut_util_Jar_7861807700606846493.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 24, --version-code, 16112112, --version-name, F, -F, /var/folders/lp/cwd098392572b2w4gf0474lc0000gn/T/APKTOOL2967809708839644739.tmp, -0, arsc, -0, properties, -0, arsc, -I, /Users/blabla/Library/apktool/framework/1.apk, -S, /tmp/apktool/result/res, -M, /tmp/apktool/result/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:478)
	at brut.androlib.Androlib.buildResources(Androlib.java:412)
	at brut.androlib.Androlib.build(Androlib.java:311)
	at brut.androlib.Androlib.build(Androlib.java:264)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/lp/cwd098392572b2w4gf0474lc0000gn/T/brut_util_Jar_7861807700606846493.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 24, --version-code, 16112112, --version-name, Furby, -F, /var/folders/lp/cwd098392572b2w4gf0474lc0000gn/T/APKTOOL2967809708839644739.tmp, -0, arsc, -0, properties, -0, arsc, -I, /Users/blabla/Library/apktool/framework/1.apk, -S, /tmp/apktool/result/res, -M, /tmp/apktool/result/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:439)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:464)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/lp/cwd098392572b2w4gf0474lc0000gn/T/brut_util_Jar_7861807700606846493.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 24, --version-code, 16112112, --version-name, F, -F, /var/folders/lp/cwd098392572b2w4gf0474lc0000gn/T/APKTOOL2967809708839644739.tmp, -0, arsc, -0, properties, -0, arsc, -I, /Users/blabla/Library/apktool/framework/1.apk, -S, /tmp/apktool/result/res, -M, /tmp/apktool/result/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:433)
	... 6 more

### Steps to Reproduce
1. APK with a custom Security Network ->https://developer.android.com/training/articles/security-config.html
2. Decompile apk 'apktool.sh d app.apk  -f -o result/'
3. Mount apk decompiled 'apktool.sh b result/ -f -o app.rebuild.apk'
4. Exception reported

**Comment by levyitay** [comment]
I have the same issue, couldn't find a workaround

**Comment by iBotPeaches** [comment]
https://developer.android.com/training/articles/security-config.html

As you can see `networkSecurityConfig` is an Android N attribute, so this is probably a framework problem. If you have at least apktool 2.2.1, run `apktool empty-framework-dir --force` and try again.

**Comment by xaywe** [comment]
Thank you! It worked! :)

**Comment by iBotPeaches** [comment]
Glad you solved it. Closing this.
