### ISSUE TITLE
Can't decompile EMUI 5.0 Noutgat system files

### ISSUE THREAD

**Issue by ngocgiap32** [iBotPeaches/Apktool#1372]
### Information
1. **Apktool Version (`apktool -2.2.1`)** -
2. **Operating System ( Windows)** -
3. **APK From? ( ROM)** -

### Stacktrace/Logcat

```

 Log For : SystemUI.apk 

 Log Type : Decompiling 

 Log Recorded At : Sun 04-12-2016 21:41:50.01 

 Log Recorded By : Advanced ApkTool v4.2.0 By BDFreak 

------------------------------------------------------ 

W: Config flags size > 56. Size = 60. Exceeding bytes: 0x18030000.
W: Invalid config flags detected. Dropping resources: drawable-xhdpi-v4-ERR0
W: Config flags size > 56. Size = 60. Exceeding bytes: 0x48030000.
W: Invalid config flags detected. Dropping resources: drawable-xhdpi-v4-ERR1
W: Config flags size > 56. Size = 60. Exceeding bytes: 0x9C000000.
W: Invalid config flags detected. Dropping resources: drawable-xhdpi-v4-ERR2
W: Config flags size > 56. Size = 60. Exceeding bytes: 0x48030000.
W: Invalid config flags detected. Dropping resources: drawable-xhdpi-v4-ERR3
W: Config flags size > 56. Size = 60. Exceeding bytes: 0x9C000000.
W: Invalid config flags detected. Dropping resources: drawable-xhdpi-v4-ERR4
W: Config flags size > 56. Size = 60. Exceeding bytes: 0x18030000.
W: Invalid config flags detected. Dropping resources: drawable-xhdpi-v4-ERR5
W: Config flags size > 56. Size = 60. Exceeding bytes: 0x18030000.
W: Invalid config flags detected. Dropping resources: drawable-xxhdpi-v4-ERR6
W: Config flags size > 56. Size = 60. Exceeding bytes: 0x9C000000.
W: Invalid config flags detected. Dropping resources: drawable-xxhdpi-v4-ERR7
W: Config flags size > 56. Size = 60. Exceeding bytes: 0xAA000000.
W: Invalid config flags detected. Dropping resources: drawable-xxhdpi-v4-ERR8
W: Config flags size > 56. Size = 60. Exceeding bytes: 0x9C000000.
W: Invalid config flags detected. Dropping resources: drawable-xxhdpi-v4-ERR9
W: Config flags size > 56. Size = 60. Exceeding bytes: 0x18030000.
W: Invalid config flags detected. Dropping resources: drawable-xxhdpi-v4-ERR10
Exception in thread "main" brut.androlib.AndrolibException: Multiple resources: spec=0x7f020213 drawable/ic_qs_signal_lte, config=-mcc214-xxhdpi-v4
	at brut.androlib.res.data.ResType.addResource(ResType.java:66)
	at brut.androlib.res.data.ResType.addResource(ResType.java:55)
	at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:270)
	at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:226)
	at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:156)
	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:118)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:80)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:558)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:72)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:64)
	at brut.androlib.Androlib.getResTable(Androlib.java:68)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:193)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
	at brut.apktool.Main.cmdDecode(Main.java:166)
	at brut.apktool.Main.main(Main.java:81)

------------------------------------------------------ ```


### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Huawei). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)
https://drive.google.com/drive/folders/0B3PWs6XjAgodOVNySENFLURNZFU?usp=sharing

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://drive.google.com/file/d/0B3PWs6XjAgodQmJqU19HR3N5SHc/view?usp=sharing

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by iBotPeaches** [comment]
Has the "opta" and "optb" qualifiers from Huawei builds. These are not supported. Sorry.

**Comment by dcionline** [comment]
You saw that files open one time?
