### ISSUE TITLE
Failed to decompile the apk

### ISSUE THREAD

**Issue by felix-antony** [iBotPeaches/Apktool#1381]
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.1
2. **Operating System (Mac, Linux, Windows)** - Mac Sierra, and JDK 1.8
3. **APK From? (Playstore, ROM, Other)** - Local apk

### Stacktrace/Logcat
```
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: file must be a directory: client-xxxx
	at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:225)
	at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:137)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:106)
	at brut.apktool.Main.cmdDecode(Main.java:166)
	at brut.apktool.Main.main(Main.java:81)
Caused by: brut.directory.DirectoryException: file must be a directory: client-xxxx
	at brut.directory.FileDirectory.<init>(FileDirectory.java:38)
	at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:205)
	... 4 more
```
### Steps to Reproduce
1. Decompile the apk with following command :  apktool d xxxx.apk

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? -  Answer : I have just tried to decompile the apk with this command: apktool d xxxx.apk

**Comment by iBotPeaches** [comment]
Haven't seen this problem before. Almost like the manifest couldn't be located or the structure of the application invalid.

I will need the APK unforunately to look at this any further. If the application is private, you can email me (ibotpeaches) (at) gmail (dot) com, with the subject - [PRIVATE] Bug 1381 - Apktool otherwise just upload it here.

**Comment by iBotPeaches** [comment]
Closing. 4+ years later, no application.
