### ISSUE TITLE
Fix error decompile apktool

### ISSUE THREAD

**Issue by zzsienzz** [iBotPeaches/Apktool#1387]
I: Using Apktool 2.2.1 on mi.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\****\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Copying assets and libs...
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: Error copying file: assets
        at brut.androlib.Androlib.decodeRawFiles(Androlib.java:155)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:157)
        at brut.apktool.Main.cmdDecode(Main.java:166)
        at brut.apktool.Main.main(Main.java:81)
Caused by: brut.directory.DirectoryException: Error copying file: assets
        at brut.directory.DirUtil.copyToDir(DirUtil.java:91)
        at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:207)
        at brut.androlib.Androlib.decodeRawFiles(Androlib.java:146)
        ... 3 more
Caused by: brut.directory.DirectoryException: Error copying file: static/static.home.mi.com/app/shop/img?id=shop_02c7360b334e35457001998c7b08b75e.jpg
        at brut.directory.DirUtil.copyToDir(DirUtil.java:88)
        at brut.directory.DirUtil.copyToDir(DirUtil.java:61)
        at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:197)
        at brut.directory.DirUtil.copyToDir(DirUtil.java:77)
        ... 5 more
Caused by: java.io.FileNotFoundException: mi\assets\static\static.home.mi.com\app\shop\img?id=shop_02c7360b334e35457001998c7b08b75e.jpg (The filename, directory name, or volume label syntax is incorrect)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at brut.directory.DirUtil.copyToDir(DirUtil.java:84)
        ... 8 more
DONE!

**Comment by iBotPeaches** [comment]
Please don't remove the template when reporting issues. This is not a valid filepath

```
mi\assets\static\static.home.mi.com\app\shop\img?id=shop_02c7360b334e35457001998c7b08b75e.jpg
```

Fix this and any others.

**Comment by zzsienzz** [comment]
i want editor apk file, find a way please help my,thanks

**Comment by iBotPeaches** [comment]
Help me help you. Follow directions when reporting a bug.
