### ISSUE TITLE
Null Pointer Exception at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1792)

### ISSUE THREAD

**Issue by digininja** [iBotPeaches/Apktool#1388]
### Information
1. **Apktool Version (`apktool -version`)** - Apktool 2.0.2-dirty
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - https://apkpure.com/herd-of-sheffield/com.wildinart.herdofsheffield

### Stacktrace/Logcat

```
I: Using Apktool 2.0.2-dirty on Herd of Sheffield_v1.1_apkpure.com.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
Exception in thread "main" java.lang.NullPointerException
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1792)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744)
	at brut.androlib.res.AndrolibResources.getFrameworkApk(AndrolibResources.java:570)
	at brut.androlib.res.AndrolibResources.loadFrameworkPkg(AndrolibResources.java:112)
	at brut.androlib.res.data.ResTable.getPackage(ResTable.java:82)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:65)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:61)
	at brut.androlib.res.decoder.ResAttrDecoder.decode(ResAttrDecoder.java:39)
	at brut.androlib.res.decoder.AXmlResourceParser.getAttributeValue(AXmlResourceParser.java:369)
	at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValue(XmlPullParserDelegate.java:69)
	at brut.androlib.res.decoder.XmlPullStreamDecoder$1.parseManifest(XmlPullStreamDecoder.java:97)
	at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:65)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:141)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:153)
	at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:140)
	at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:199)
	at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:140)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:100)
	at brut.apktool.Main.cmdDecode(Main.java:165)
	at brut.apktool.Main.main(Main.java:81)
```

### Steps to Reproduce
1. `apktool d Herd\ of\ Sheffield_v1.1_apkpure.com.apk  `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

https://apkpure.com/herd-of-sheffield/com.wildinart.herdofsheffield

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? No, just decompiling the file
2. If you are trying to install a modified apk, did you resign it? No
3. Are you using the latest apktool version? Latest from the Ubuntu repo

**Comment by iBotPeaches** [comment]
```
➜  Bug1388 apktool d herd-sheff.apk 
I: Using Apktool 2.2.2-31d015-SNAPSHOT on herd-sheff.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/connortumbleson/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1388 
```

Could not duplicate. You are a few versions behind as well. 2.0.2 is really old, since then we have had the release of 2.0.3, 2.1.0, 2.1.1, 2.2.0, 2.2.1 and pending 2.2.2.

**Comment by digininja** [comment]
OK, I'll try with a newer version but that is the latest one in the Ubuntu
16.04 repo.
