### ISSUE TITLE
Space in folder path for building apktool - fails.

### ISSUE THREAD

**Issue by jack16099** [iBotPeaches/Apktool#1394]
I'm unable to build apktool via Git Bash. Here's the full log
```
user@user-PC MINGW32 /Apktool (master)
$ ./gradlew.bat build fatjar proguard
Download https://jcenter.bintray.com/eu/appsatori/gradle-fatjar-plugin/0.3/gradle-fatjar-plugin-0.3.pom
Download https://jcenter.bintray.com/eu/appsatori/gradle-fatjar-plugin/0.3/gradle-fatjar-plugin-0.3.jar
Building SNAPSHOT (master): 166bf5
Download https://repo1.maven.org/maven2/net/sf/proguard/proguard-gradle/5.2.1/proguard-gradle-5.2.1.pom
Download https://repo1.maven.org/maven2/net/sf/proguard/proguard-parent/5.2.1/proguard-parent-5.2.1.pom
Download https://repo1.maven.org/maven2/net/sf/proguard/proguard-base/5.2.1/proguard-base-5.2.1.pom
Download https://repo1.maven.org/maven2/net/sf/proguard/proguard-gradle/5.2.1/proguard-gradle-5.2.1.jar
Download https://repo1.maven.org/maven2/net/sf/proguard/proguard-base/5.2.1/proguard-base-5.2.1.jar
Download https://repo1.maven.org/maven2/junit/junit/4.10/junit-4.10.pom
Download https://repo1.maven.org/maven2/org/smali/baksmali/2.1.3/baksmali-2.1.3.pom
Download https://repo1.maven.org/maven2/org/smali/smali/2.1.3/smali-2.1.3.pom
Download https://repo1.maven.org/maven2/org/yaml/snakeyaml/1.17/snakeyaml-1.17.pom
Download https://repo1.maven.org/maven2/xpp3/xpp3/1.1.4c/xpp3-1.1.4c.pom
Download https://repo1.maven.org/maven2/com/google/guava/guava/14.0/guava-14.0.pom
Download https://repo1.maven.org/maven2/com/google/guava/guava-parent/14.0/guava-parent-14.0.pom
Download https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/7/oss-parent-7.pom
Download https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.pom
Download https://repo1.maven.org/maven2/org/apache/commons/commons-parent/22/commons-parent-22.pom
Download https://repo1.maven.org/maven2/org/apache/apache/9/apache-9.pom
Download https://repo1.maven.org/maven2/commons-io/commons-io/2.4/commons-io-2.4.pom
Download https://repo1.maven.org/maven2/org/apache/commons/commons-parent/25/commons-parent-25.pom
Download https://repo1.maven.org/maven2/org/smali/util/2.1.3/util-2.1.3.pom
Download https://repo1.maven.org/maven2/org/smali/dexlib2/2.1.3/dexlib2-2.1.3.pom
Download https://repo1.maven.org/maven2/commons-cli/commons-cli/1.2/commons-cli-1.2.pom
Download https://repo1.maven.org/maven2/org/apache/commons/commons-parent/11/commons-parent-11.pom
Download https://repo1.maven.org/maven2/org/apache/apache/4/apache-4.pom
Download https://repo1.maven.org/maven2/org/antlr/antlr-runtime/3.5.2/antlr-runtime-3.5.2.pom
Download https://repo1.maven.org/maven2/org/antlr/antlr-master/3.5.2/antlr-master-3.5.2.pom
Download https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/9/oss-parent-9.pom
Download https://repo1.maven.org/maven2/org/antlr/stringtemplate/3.2.1/stringtemplate-3.2.1.pom
Download https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.pom
Download https://repo1.maven.org/maven2/antlr/antlr/2.7.7/antlr-2.7.7.pom
Download https://repo1.maven.org/maven2/com/google/guava/guava/18.0/guava-18.0.pom
Download https://repo1.maven.org/maven2/com/google/guava/guava-parent/18.0/guava-parent-18.0.pom
Download https://repo1.maven.org/maven2/junit/junit/4.10/junit-4.10.jar
Download https://repo1.maven.org/maven2/org/smali/baksmali/2.1.3/baksmali-2.1.3.jar
Download https://repo1.maven.org/maven2/org/smali/smali/2.1.3/smali-2.1.3.jar
Download https://repo1.maven.org/maven2/org/yaml/snakeyaml/1.17/snakeyaml-1.17.jar
Download https://repo1.maven.org/maven2/xpp3/xpp3/1.1.4c/xpp3-1.1.4c.jar
Download https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar
Download https://repo1.maven.org/maven2/commons-io/commons-io/2.4/commons-io-2.4.jar
Download https://repo1.maven.org/maven2/org/smali/util/2.1.3/util-2.1.3.jar
Download https://repo1.maven.org/maven2/org/smali/dexlib2/2.1.3/dexlib2-2.1.3.jar
Download https://repo1.maven.org/maven2/commons-cli/commons-cli/1.2/commons-cli-1.2.jar
Download https://repo1.maven.org/maven2/org/antlr/antlr-runtime/3.5.2/antlr-runtime-3.5.2.jar
Download https://repo1.maven.org/maven2/org/antlr/stringtemplate/3.2.1/stringtemplate-3.2.1.jar
Download https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar
Download https://repo1.maven.org/maven2/antlr/antlr/2.7.7/antlr-2.7.7.jar
Download https://repo1.maven.org/maven2/com/google/guava/guava/18.0/guava-18.0.jar
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar
:assemble
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test UP-TO-DATE
:check UP-TO-DATE
:build
:brut.apktool:compileJava UP-TO-DATE
:brut.apktool:processResources UP-TO-DATE
:brut.apktool:classes UP-TO-DATE
:brut.apktool:jar
:brut.apktool:assemble
:brut.apktool:compileTestJava UP-TO-DATE
:brut.apktool:processTestResources UP-TO-DATE
:brut.apktool:testClasses UP-TO-DATE
:brut.apktool:test UP-TO-DATE
:brut.apktool:check UP-TO-DATE
:brut.apktool:build
:brut.j.common:compileJavawarning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning

:brut.j.common:processResources UP-TO-DATE
:brut.j.common:classes
:brut.j.common:jar
:brut.j.common:assemble
:brut.j.common:compileTestJava UP-TO-DATE
:brut.j.common:processTestResources UP-TO-DATE
:brut.j.common:testClasses UP-TO-DATE
:brut.j.common:test UP-TO-DATE
:brut.j.common:check UP-TO-DATE
:brut.j.common:build
:brut.j.util:compileJavawarning: [options] bootstrap class path not set in conjunction with -source 1.7
Note: C:\Program Files\Git\Apktool\brut.j.util\src\main\java\brut\util\Duo.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning

:brut.j.util:processResources UP-TO-DATE
:brut.j.util:classes
:brut.j.util:jar
:brut.j.dir:compileJavawarning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning

:brut.j.dir:processResources UP-TO-DATE
:brut.j.dir:classes
:brut.j.dir:jar
:brut.j.dir:assemble
:brut.j.dir:compileTestJava UP-TO-DATE
:brut.j.dir:processTestResources UP-TO-DATE
:brut.j.dir:testClasses UP-TO-DATE
:brut.j.dir:test UP-TO-DATE
:brut.j.dir:check UP-TO-DATE
:brut.j.dir:build
:brut.j.util:assemble
:brut.j.util:compileTestJava UP-TO-DATE
:brut.j.util:processTestResources UP-TO-DATE
:brut.j.util:testClasses UP-TO-DATE
:brut.j.util:test UP-TO-DATE
:brut.j.util:check UP-TO-DATE
:brut.j.util:build
:brut.apktool:apktool-lib:compileJavawarning: [options] bootstrap class path not set in conjunction with -source 1.7
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning

:brut.apktool:apktool-lib:processResources
:brut.apktool:apktool-lib:classes
:brut.apktool:apktool-lib:jar
:brut.apktool:apktool-cli:compileJavawarning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning

:brut.apktool:apktool-cli:processResources UP-TO-DATE
:brut.apktool:apktool-cli:classes
:brut.apktool:apktool-cli:jar
:brut.apktool:apktool-cli:assemble
:brut.apktool:apktool-cli:compileTestJava UP-TO-DATE
:brut.apktool:apktool-cli:processTestResources UP-TO-DATE
:brut.apktool:apktool-cli:testClasses UP-TO-DATE
:brut.apktool:apktool-cli:test UP-TO-DATE
:brut.apktool:apktool-cli:check UP-TO-DATE
:brut.apktool:apktool-cli:build
:brut.apktool:apktool-lib:assemble
:brut.apktool:apktool-lib:compileTestJava
Download https://repo1.maven.org/maven2/xmlunit/xmlunit/1.3/xmlunit-1.3.pom
Download https://repo1.maven.org/maven2/junit/junit/4.12/junit-4.12.pom
Download https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.pom
Download https://repo1.maven.org/maven2/org/hamcrest/hamcrest-parent/1.3/hamcrest-parent-1.3.pom
Download https://repo1.maven.org/maven2/xmlunit/xmlunit/1.3/xmlunit-1.3.jar
Download https://repo1.maven.org/maven2/junit/junit/4.12/junit-4.12.jar
Download https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
warning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning
:brut.apktool:apktool-lib:processTestResources
:brut.apktool:apktool-lib:testClasses
:brut.apktool:apktool-lib:test

brut.androlib.AndResGuardTest > classMethod FAILED
    brut.directory.DirectoryException: file must be a directory: C:\Program%20Files\Git\Apktool\brut.apktool\apktool-lib\build\resources\test\brut\apktool\issue1170
        at brut.directory.FileDirectory.<init>(FileDirectory.java:38)
        at brut.directory.FileDirectory.<init>(FileDirectory.java:32)
        at brut.androlib.TestUtils.copyResourceDir(TestUtils.java:101)
        at brut.androlib.TestUtils.copyResourceDir(TestUtils.java:91)
        at brut.androlib.AndResGuardTest.beforeClass(AndResGuardTest.java:35)

brut.androlib.BuildAndDecodeJarTest > classMethod FAILED
    brut.directory.DirectoryException: file must be a directory: C:\Program%20Files\Git\Apktool\brut.apktool\apktool-lib\build\resources\test\brut\apktool\testjar
        at brut.directory.FileDirectory.<init>(FileDirectory.java:38)
        at brut.directory.FileDirectory.<init>(FileDirectory.java:32)
        at brut.androlib.TestUtils.copyResourceDir(TestUtils.java:101)
        at brut.androlib.TestUtils.copyResourceDir(TestUtils.java:91)
        at brut.androlib.BuildAndDecodeJarTest.beforeClass(BuildAndDecodeJarTest.java:42)

brut.androlib.BuildAndDecodeTest > classMethod FAILED
    brut.directory.DirectoryException: file must be a directory: C:\Program%20Files\Git\Apktool\brut.apktool\apktool-lib\build\resources\test\brut\apktool\testapp
        at brut.directory.FileDirectory.<init>(FileDirectory.java:38)
        at brut.directory.FileDirectory.<init>(FileDirectory.java:32)
        at brut.androlib.TestUtils.copyResourceDir(TestUtils.java:101)
        at brut.androlib.TestUtils.copyResourceDir(TestUtils.java:91)
        at brut.androlib.BuildAndDecodeTest.beforeClass(BuildAndDecodeTest.java:52)

brut.androlib.DebugTagRetainedTest > classMethod FAILED
    brut.directory.DirectoryException: file must be a directory: C:\Program%20Files\Git\Apktool\brut.apktool\apktool-lib\build\resources\test\brut\apktool\issue1235
        at brut.directory.FileDirectory.<init>(FileDirectory.java:38)
        at brut.directory.FileDirectory.<init>(FileDirectory.java:32)
        at brut.androlib.TestUtils.copyResourceDir(TestUtils.java:101)
        at brut.androlib.TestUtils.copyResourceDir(TestUtils.java:91)
        at brut.androlib.DebugTagRetainedTest.beforeClass(DebugTagRetainedTest.java:46)

brut.androlib.DoubleExtensionUnknownFileTest > classMethod FAILED
    brut.directory.DirectoryException: file must be a directory: C:\Program%20Files\Git\Apktool\brut.apktool\apktool-lib\build\resources\test\brut\apktool\issue1244
        at brut.directory.FileDirectory.<init>(FileDirectory.java:38)
        at brut.directory.FileDirectory.<init>(FileDirectory.java:32)
        at brut.androlib.TestUtils.copyResourceDir(TestUtils.java:101)
        at brut.androlib.TestUtils.copyResourceDir(TestUtils.java:91)
        at brut.androlib.DoubleExtensionUnknownFileTest.beforeClass(DoubleExtensionUnknownFileTest.java:43)

brut.androlib.LargeIntsInManifestTest > classMethod FAILED
    brut.directory.DirectoryException: file must be a directory: C:\Program%20Files\Git\Apktool\brut.apktool\apktool-lib\build\resources\test\brut\apktool\issue767
        at brut.directory.FileDirectory.<init>(FileDirectory.java:38)
        at brut.directory.FileDirectory.<init>(FileDirectory.java:32)
        at brut.androlib.TestUtils.copyResourceDir(TestUtils.java:101)
        at brut.androlib.TestUtils.copyResourceDir(TestUtils.java:91)
        at brut.androlib.LargeIntsInManifestTest.beforeClass(LargeIntsInManifestTest.java:41)

brut.androlib.MissingVersionManifestTest > classMethod FAILED
    brut.directory.DirectoryException: file must be a directory: C:\Program%20Files\Git\Apktool\brut.apktool\apktool-lib\build\resources\test\brut\apktool\issue1264
        at brut.directory.FileDirectory.<init>(FileDirectory.java:38)
        at brut.directory.FileDirectory.<init>(FileDirectory.java:32)
        at brut.androlib.TestUtils.copyResourceDir(TestUtils.java:101)
        at brut.androlib.TestUtils.copyResourceDir(TestUtils.java:91)
        at brut.androlib.MissingVersionManifestTest.beforeClass(MissingVersionManifestTest.java:41)

brut.androlib.ProviderAttributeTest > classMethod FAILED
    brut.directory.DirectoryException: file must be a directory: C:\Program%20Files\Git\Apktool\brut.apktool\apktool-lib\build\resources\test\brut\apktool\issue636
        at brut.directory.FileDirectory.<init>(FileDirectory.java:38)
        at brut.directory.FileDirectory.<init>(FileDirectory.java:32)
        at brut.androlib.TestUtils.copyResourceDir(TestUtils.java:101)
        at brut.androlib.TestUtils.copyResourceDir(TestUtils.java:91)
        at brut.androlib.ProviderAttributeTest.beforeClass(ProviderAttributeTest.java:41)

brut.androlib.ReferenceVersionCodeTest > classMethod FAILED
    brut.directory.DirectoryException: file must be a directory: C:\Program%20Files\Git\Apktool\brut.apktool\apktool-lib\build\resources\test\brut\apktool\issue1234
        at brut.directory.FileDirectory.<init>(FileDirectory.java:38)
        at brut.directory.FileDirectory.<init>(FileDirectory.java:32)
        at brut.androlib.TestUtils.copyResourceDir(TestUtils.java:101)
        at brut.androlib.TestUtils.copyResourceDir(TestUtils.java:91)
        at brut.androlib.ReferenceVersionCodeTest.beforeClass(ReferenceVersionCodeTest.java:41)

brut.androlib.SharedLibraryTest > classMethod FAILED
    brut.directory.DirectoryException: file must be a directory: C:\Program%20Files\Git\Apktool\brut.apktool\apktool-lib\build\resources\test\brut\apktool\shared_libraries
        at brut.directory.FileDirectory.<init>(FileDirectory.java:38)
        at brut.directory.FileDirectory.<init>(FileDirectory.java:32)
        at brut.androlib.TestUtils.copyResourceDir(TestUtils.java:101)
        at brut.androlib.TestUtils.copyResourceDir(TestUtils.java:91)
        at brut.androlib.SharedLibraryTest.beforeClass(SharedLibraryTest.java:40)

brut.androlib.UnknownCompressionTest > classMethod FAILED
    brut.directory.DirectoryException: file must be a directory: C:\Program%20Files\Git\Apktool\brut.apktool\apktool-lib\build\resources\test\brut\apktool\unknown_compression
        at brut.directory.FileDirectory.<init>(FileDirectory.java:38)
        at brut.directory.FileDirectory.<init>(FileDirectory.java:32)
        at brut.androlib.TestUtils.copyResourceDir(TestUtils.java:101)
        at brut.androlib.TestUtils.copyResourceDir(TestUtils.java:91)
        at brut.androlib.UnknownCompressionTest.beforeClass(UnknownCompressionTest.java:42)

11 tests completed, 11 failed
:brut.apktool:apktool-lib:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':brut.apktool:apktool-lib:test'.
> There were failing tests. See the report at: file:///C:/Program%20Files/Git/Apktool/brut.apktool/apktool-lib/build/reports/tests/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2 mins 14.156 secs
```

**Comment by iBotPeaches** [comment]
Can confirm if you have a space in the folder path of Apktool, building it fails.

```

brut.androlib.AndResGuardTest > classMethod FAILED
    brut.directory.DirectoryException: file must be a directory: /Users/connortumbleson/Desktop/Space%20Folder/Apktool/brut.apktool/apktool-lib/build/resources/test/brut/apktool/issue1170
        at brut.directory.FileDirectory.<init>(FileDirectory.java:38)
        at brut.directory.FileDirectory.<init>(FileDirectory.java:32)
        at brut.androlib.TestUtils.copyResourceDir(TestUtils.java:101)
        at brut.androlib.TestUtils.copyResourceDir(TestUtils.java:91)
        at brut.androlib.AndResGuardTest.beforeClass(AndResGuardTest.java:35)
```

On my Mac. 

Merry Christmas if you celebrate it!
