### ISSUE TITLE
HTC Sense Recompile Failure (Missing Resources)

### ISSUE THREAD

**Issue by AnthonySmith01** [iBotPeaches/Apktool#1412]
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.1
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Settings.apk, from HTC Desire 510 Rom (Android 4.4.3)

Hi, thanks for the awesome tool.

I'm having some problems modifying a Settings.apk for a HTC Android ROM. 
I've tried a straight decompile, recompile and sign (without modifications) but it still seems to fail.

First I pulled com.htc.resources.apk and framework-res.apk, then executing:
java -jar apktool.jar if framework-res.apk
java -jar apktool.jar if com.htc.resources.apk

De-compiling with java -jar apktool.jar d -s Settings.apk gives the following:
```
I: Using Apktool 2.2.1 on Settings.apk
I: Loading resource table...
W: Skipping "android" package group
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\New\AppData\Local\apktool\framework\1.apk
I: Loading resource table from file: C:\Users\New\AppData\Local\apktool\framework\2.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying raw classes.dex file...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
```

Recompiling java -jar apktool.jar b Settings displays the following:

```
I: Using Apktool 2.2.1
I: Copying Settings classes.dex file...
I: Checking whether resources has changed...
I: Building resources...
W: E/ResourceType( 8636): Failed resolving ResTable_map name at 1420 with ident 0x02020019
W: W/ResourceType( 8636): Attempt to retrieve bag 0x02010011 which is invalid or in a cycle.
W: W/ResourceType( 8636): Attempt to retrieve bag 0x02010011 which is invalid or in a cycle.
W: W/ResourceType( 8636): Attempt to retrieve bag 0x02010011 which is invalid or in a cycle.
W: W/ResourceType( 8636): Attempt to retrieve bag 0x02010011 which is invalid or in a cycle.
W: E/ResourceType( 8636): Failed resolving ResTable_map name at 1588 with ident 0x02020017
W: E/ResourceType( 8636): Failed resolving ResTable_map name at 1484 with ident 0x0202001c
W: W/ResourceType( 8636): Attempt to retrieve bag 0x02010011 which is invalid or in a cycle.
W: W/ResourceType( 8636): Attempt to retrieve bag 0x02010011 which is invalid or in a cycle.
W: W/ResourceType( 8636): Attempt to retrieve bag 0x02010011 which is invalid or in a cycle.
W: W/ResourceType( 8636): Attempt to retrieve bag 0x02010011 which is invalid or in a cycle.
W: W/ResourceType( 8636): Attempt to retrieve bag 0x02010011 which is invalid or in a cycle.
W: W/ResourceType( 8636): Attempt to retrieve bag 0x02010011 which is invalid or in a cycle.
W: W/ResourceType( 8636): Attempt to retrieve bag 0x02010011 which is invalid or in a cycle.
W: W/ResourceType( 8636): Attempt to retrieve bag 0x02010012 which is invalid or in a cycle.
W: W/ResourceType( 8636): Attempt to retrieve bag 0x02010012 which is invalid or in a cycle.
W: W/ResourceType( 8636): Attempt to retrieve bag 0x02010012 which is invalid or in a cycle.
W: W/ResourceType( 8636): Attempt to retrieve bag 0x02010012 which is invalid or in a cycle.
W: W/ResourceType( 8636): Attempt to retrieve bag 0x02010011 which is invalid or in a cycle.
W: W/ResourceType( 8636): Attempt to retrieve bag 0x02010011 which is invalid or in a cycle.
W: E/ResourceType( 8636): Failed resolving ResTable_map name at 2552 with ident 0x0202000f
W: warning: Package not found for resource #02010011
W: warning: Package not found for resource #02010011
W: warning: Package not found for resource #02010011
W: warning: Package not found for resource #02010011
W: warning: Package not found for resource #02010011
W: warning: Package not found for resource #02010014
W: warning: Package not found for resource #02010012
W: warning: Package not found for resource #02010011
W: warning: Package not found for resource #02010011
W: warning: Package not found for resource #02010011
W: warning: Package not found for resource #02010011
W: warning: Package not found for resource #02010011
W: warning: Package not found for resource #02010011
W: warning: Package not found for resource #02010011
W: warning: Package not found for resource #02010012
W: warning: Package not found for resource #02010012
W: warning: Package not found for resource #02010012
W: warning: Package not found for resource #02010012
W: warning: Package not found for resource #02010011
W: warning: Package not found for resource #02010011
W: warning: Package not found for resource #02010033
I: Building apk file...
I: Copying unknown files/dir...
```

I then using apk-signer to sign the apk and push it via adb to the app folder. Logcat indicates a runtime exception as follows when tapping settings:
```
E/AndroidRuntime_2_crash( 1510): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings
/com.android.settings.Settings}: android.content.res.Resources$NotFoundException: File res/drawable/htc_window_background.xml from drawable resource ID #0x7f02005e
E/AndroidRuntime_2_crash( 1510):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2439)
E/AndroidRuntime_2_crash( 1510):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495)
E/AndroidRuntime_2_crash( 1510):        at android.app.ActivityThread.access$800(ActivityThread.java:153)
E/AndroidRuntime_2_crash( 1510):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
E/AndroidRuntime_2_crash( 1510):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime_2_crash( 1510):        at android.os.Looper.loop(Looper.java:157)
E/AndroidRuntime_2_crash( 1510):        at android.app.ActivityThread.main(ActivityThread.java:5633)
E/AndroidRuntime_2_crash( 1510):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime_2_crash( 1510):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime_2_crash( 1510):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:89
6)
E/AndroidRuntime_2_crash( 1510):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)
E/AndroidRuntime_2_crash( 1510):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime_2_crash( 1510): Caused by: android.content.res.Resources$NotFoundException: File res/drawable/htc_windo
w_background.xml from drawable resource ID #0x7f02005e
E/AndroidRuntime_2_crash( 1510):        at android.content.res.Resources.loadDrawable(Resources.java:2141)
E/AndroidRuntime_2_crash( 1510):        at android.content.res.Resources.getDrawable(Resources.java:711)
E/AndroidRuntime_2_crash( 1510):        at android.view.Window.setBackgroundDrawableResource(Window.java:1036)
E/AndroidRuntime_2_crash( 1510):        at com.android.settings.framework.app.HtcInternalPreferenceActivity.setupTranslu
centStatusBar(HtcInternalPreferenceActivity.java:177)
E/AndroidRuntime_2_crash( 1510):        at com.android.settings.framework.app.HtcInternalPreferenceActivity.onCreate(Htc
InternalPreferenceActivity.java:156)
E/AndroidRuntime_2_crash( 1510):        at com.android.settings.HtcAbsSettings.onCreate(HtcAbsSettings.java:135)
E/AndroidRuntime_2_crash( 1510):        at com.android.settings.Settings.onCreate(Settings.java:233)
E/AndroidRuntime_2_crash( 1510):        at android.app.Activity.performCreate(Activity.java:5312)
E/AndroidRuntime_2_crash( 1510):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
E/AndroidRuntime_2_crash( 1510):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2395)
E/AndroidRuntime_2_crash( 1510):        ... 11 more
E/AndroidRuntime_2_crash( 1510): Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #4: <item> tag r
equires a 'drawable' attribute or child tag defining a drawable
E/AndroidRuntime_2_crash( 1510):        at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:164)
E/AndroidRuntime_2_crash( 1510):        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:937)
E/AndroidRuntime_2_crash( 1510):        at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
E/AndroidRuntime_2_crash( 1510):        at android.content.res.Resources.loadDrawable(Resources.java:2137)
E/AndroidRuntime_2_crash( 1510):        ... 20 more
```

I've confirmed that the file in the run-time error is present in the re-compiled .apk.

Any ideas or workarounds?
I recall someone mentioning elsewhere to try "removing the sharedLibrary tag from apktool.yml and forcing aapt to the 19.1.0 release", but I'm not sure how to do this.

Thanks! :)

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)
[com.htc.resources.zip](https://github.com/iBotPeaches/Apktool/files/704317/com.htc.resources.zip)
[framework-res.zip](https://github.com/iBotPeaches/Apktool/files/704319/framework-res.zip)

.apks are attached as zips due to file restrictions

### APK
If this APK can be freely shared, please upload/attach a link to it.

[Settings.zip](https://github.com/iBotPeaches/Apktool/files/704321/Settings.zip)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Yes
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
Sorry for missing this ticket for 4+ years. I don't see myself not having an HTC device to be able to do anything here. These large companies have such modified build systems - who knows.

Closing.
