### ISSUE TITLE
Error while recompiling an app

### ISSUE THREAD

**Issue by EvoWizz** [iBotPeaches/Apktool#1416]
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.2
2. **Operating System (Mac, Linux, Windows)** - Windows 10
3. **APK From? (Playstore, ROM, Other)** - Play Store

I was trying to rebuild an apk, and here is my problem:

```
W: C:\Users\...\appname\res\values-v24\styles.xml:3: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Animation.OptionsPanel'.
W:
W: C:\Users\...\appname\res\values-v24\styles.xml:4: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Animation.LockScreen'.
W:
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [ C:\Users\...\AppData\Local\Temp\brut_util_Jar_2912099408141363281.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 24, --version-code, "versioncodeishere", --version-name, "versionnameishere", --no-version-vectors, -F,  C:\Users\...\AppData\Local\Temp\APKTOOL8574854182611121376.tmp, -0, arsc, -0, res/raw/ep_acoustic_model, -0, apk, -0, arsc, -I,  C:\Users\...\AppData\Local\apktool\framework\1.apk, -S,   C:\Users\...\appname\res, -M,  C:\Users\...\appname\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:477)
        at brut.androlib.Androlib.buildResources(Androlib.java:411)
        at brut.androlib.Androlib.build(Androlib.java:310)
        at brut.androlib.Androlib.build(Androlib.java:263)
        at brut.apktool.Main.cmdBuild(Main.java:227)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\...\AppData\Local\Temp\brut_util_Jar_2912099408141363281.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 24, --version-code, "versioncodeishere", --version-name, "versionnameishere", --no-version-vectors, -F, C:\Users\...\AppData\Local\Temp\APKTOOL8574854182611121376.tmp, -0, arsc, -0, res/raw/ep_acoustic_model, -0, apk, -0, arsc, -I, C:\Users\...\AppData\Local\apktool\framework\1.apk, -S, C:\Users\...\appname\res, -M, C:\Users\...\appname\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:440)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:463)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\...\AppData\Local\Temp\brut_util_Jar_2912099408141363281.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 24, --version-code, versioncodeishere, --version-name, "versionnameishere", --no-version-vectors, -F, C:\Users\...\AppData\Local\Temp\APKTOOL8574854182611121376.tmp, -0, arsc, -0, res/raw/ep_acoustic_model, -0, apk, -0, arsc, -I, C:\Users\...\AppData\Local\apktool\framework\1.apk, -S, C:\Users\...\appname\res, -M, C:\Users\...\appname\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:434)
        ... 6 more
```

Help please :/

**Comment by TamilanPeriyasamy** [comment]
Hi , delete auto generated 1.apk file(/framework/1.apk) after build and rebuild.  

I have same issue using apktool-2.1.1 in Linux Operating System
but now working fine using apktool-2.2.2 in Linux Operating System.

**Comment by iBotPeaches** [comment]
As said, this seems to be an outdated framework problem as both those resources missing are found in the official `themes.xml` file of AOSP.

Try running

```
apktool empty-framework-dir --force
```

and give it another shot.

**Comment by EvoWizz** [comment]
@iBotPeaches I tried what you said, and I still have the problem (so now, this is a bug :/ )

**Comment by coolpixs4** [comment]
Dear @iBotPeaches, not working for me

C:\apktool_miui7>apktool empty-framework-dir --force
I: Removing 1.apk framework file...
I: Removing 17.apk framework file...

C:\apktool_miui7>apktool b facebook
I: Using Apktool 2.2.2
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.err.Ca
ntFindFrameworkResException
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:477)
        at brut.androlib.Androlib.buildResources(Androlib.java:411)
        at brut.androlib.Androlib.build(Androlib.java:310)
        at brut.androlib.Androlib.build(Androlib.java:263)
        at brut.apktool.Main.cmdBuild(Main.java:227)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.err.CantFindFrameworkResException
        at brut.androlib.res.AndrolibResources.getFrameworkApk(AndrolibResources
.java:592)
        at brut.androlib.Androlib.parseUsesFramework(Androlib.java:718)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:465)
        ... 5 more

C:\apktool_miui7>
