### ISSUE TITLE
No resource identifier found for attribute 'contextUri' in package 'android' on apktool 2.2.2

### ISSUE THREAD

**Issue by thupten1234** [iBotPeaches/Apktool#1418]
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.2
2. **Operating System (Mac, Linux, Windows)** - Linux Mint
3. **APK From? (Playstore, ROM, Other)** - Other

###Include stacktrace here
apktool decompile works but the apktool build fails with following error.

$apktool b abc_folder
I: Using Apktool 2.2.2
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: warning: string 'changelog_v4' has no default translation.
W: /home/ttcc/Downloads/abc_folder/res/xml-v25/my_wallpaper.xml:2: error: No resource identifier found for attribute 'contextUri' in package 'android'
W: 
W: /home/ttcc/Downloads/abc_folder/res/xml-v25/my_wallpaper.xml:2: error: No resource identifier found for attribute 'contextDescription' in package 'android'
W: 
W: /home/ttcc/Downloads/abc_folder/res/xml-v25/my_wallpaper.xml:2: error: No resource identifier found for attribute 'showMetadataInPreview' in package 'android'
W: 
W: /home/ttcc/Downloads/abc_folder/res/xml-v25/map_wallpaper.xml:2: error: No resource identifier found for attribute 'contextUri' in package 'android'
W: 
W: /home/ttcc/Downloads/abc_folder/res/xml-v25/map_wallpaper.xml:2: error: No resource identifier found for attribute 'contextDescription' in package 'android'
W: 
W: /home/ttcc/Downloads/abc_folder/res/xml-v25/map_wallpaper.xml:2: error: No resource identifier found for attribute 'showMetadataInPreview' in package 'android'
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_1833399004826324962.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 24, --version-code, 50012, --version-name, 5.0.1, --no-version-vectors, -F, /tmp/APKTOOL1788799121958141603.tmp, -0, arsc, -0, apk, -0, arsc, -I, /home/ttcc/.local/share/apktool/framework/1.apk, -S, /home/ttcc/Downloads/abc_folder/res, -M, /home/ttcc/Downloads/abc_folder/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:477)
	at brut.androlib.Androlib.buildResources(Androlib.java:411)
	at brut.androlib.Androlib.build(Androlib.java:310)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_1833399004826324962.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 24, --version-code, 50012, --version-name, 5.0.1, --no-version-vectors, -F, /tmp/APKTOOL1788799121958141603.tmp, -0, arsc, -0, apk, -0, arsc, -I, /home/ttcc/.local/share/apktool/framework/1.apk, -S, /home/ttcc/Downloads/abc_folder/res, -M, /home/ttcc/Downloads/abc_folder/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:440)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:463)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_1833399004826324962.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 24, --version-code, 50012, --version-name, 5.0.1, --no-version-vectors, -F, /tmp/APKTOOL1788799121958141603.tmp, -0, arsc, -0, apk, -0, arsc, -I, /home/ttcc/.local/share/apktool/framework/1.apk, -S, /home/ttcc/Downloads/abc_folder/res, -M, /home/ttcc/Downloads/abc_folder/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:434)
	... 6 more

### Steps to Reproduce
1. `apktool b abc_folder`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)
NONE

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? did not get tere
3. Are you using the latest apktool version? 2.2.2

**Comment by iBotPeaches** [comment]
Give 

```
apktool empty-framework-dir --force
```

then re-try (decode and build).

**Comment by thupten1234** [comment]
it worked. thanks.
