### ISSUE TITLE
Multiple resources error

### ISSUE THREAD

**Issue by akashsoni474** [iBotPeaches/Apktool#1419]
```
I: Using Apktool 2.2.1 on framework-res.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Multiple resources: spec=0x0103035d style/Theme.DeviceDefault.Resolver, config=-round
	at brut.androlib.res.data.ResType.addResource(ResType.java:66)
	at brut.androlib.res.data.ResType.addResource(ResType.java:55)
	at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:270)
	at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:226)
	at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:156)
	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:118)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:80)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:558)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:72)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:64)
	at brut.androlib.Androlib.getResTable(Androlib.java:68)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:193)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
	at brut.apktool.Main.cmdDecode(Main.java:166)
	at brut.apktool.Main.main(Main.java:81)
```
please help me to fix this error 
i am getting this error on framework-res.apk of ressurrection remix,temasek and blisspop roms

**Comment by iBotPeaches** [comment]
Will need apk to investigate multiple resource errors. The stacktrace just tells me of the problem, need more to investigate.

**Comment by akashsoni474** [comment]
okk sir uploading the apk

**Comment by akashsoni474** [comment]
https://yadi.sk/d/IhWCi_0Z3BFmp2

here is the framework-res.apk

**Comment by akashsoni474** [comment]
@iBotPeaches you got the apk..??

**Comment by maxerbox** [comment]
Same here

**Comment by maxerbox** [comment]
Exception in thread "main" brut.androlib.AndrolibException: Multiple resources: spec=0x7f080000 string/APKTOOL_DUMMYVAL_0x7f080000, config=-sr
        at brut.androlib.res.data.ResType.addResource(ResType.java:66)
        at brut.androlib.res.data.ResType.addResource(ResType.java:55)
        at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:270)
        at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:226)
        at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:156)
        at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:118)
        at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:80)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:559)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:72)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:64)
        at brut.androlib.Androlib.getResTable(Androlib.java:67)
        at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:193)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
        at brut.apktool.Main.cmdDecode(Main.java:166)
        at brut.apktool.Main.main(Main.java:81)

**Comment by maxerbox** [comment]
Apk: (just rename the extension .zip to .apk)
[AppBounty_Free gift_cards_2.4.6_apk-dl.com.zip](https://github.com/iBotPeaches/Apktool/files/801508/AppBounty_Free.gift_cards_2.4.6_apk-dl.com.zip)

**Comment by White-Tiger** [comment]
same issue as @maxerbox with AccuBattery
[com.digibites.accubattery_v1.1.7c.apk.zip](https://github.com/iBotPeaches/Apktool/files/804856/com.digibites.accubattery_v1.1.7c.apk.zip)

**Comment by iBotPeaches** [comment]
Sorry for the delay. This is indeed Dexguard, which is a tough thing to work around due to resource names being malformed/removed. This is currently being tracked in #1320
