### ISSUE TITLE
Error while building with unmodified decoded resources

### ISSUE THREAD

**Issue by Anth0ny229** [iBotPeaches/Apktool#1422]
I have decoded and tried to rebuild without any changes and i'm getting some errors.

### Information
1. **Apktool Version (Apktool v2.2.2 with smali v2.1.3 and baksmali v2.1.3)** -
2. **Operating System (Windows)** -
3. **APK From? (Playstore)** -

### Stacktrace/Logcat

```
C:\Users\anth0\Documents\Visual Studio 2015\Projects\Imgur>apktool b base
I: Using Apktool 2.2.2
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
W: C:\Users\anth0\Documents\Visual Studio 2015\Projects\Imgur\base\res\drawable\ic_eye.xml:4: error: No resource identifier found for attribute 'fillType' in package 'android'
W:
W: C:\Users\anth0\Documents\Visual Studio 2015\Projects\Imgur\base\res\drawable\ic_open_book.xml:4: error: No resource identifier found for attribute 'fillType' in package 'android'
W:
W: C:\Users\anth0\Documents\Visual Studio 2015\Projects\Imgur\base\res\drawable\ic_open_book.xml:5: error: No resource identifier found for attribute 'fillType' in package 'android'
W:
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\anth0\AppData\Local\Temp\brut_util_Jar_7716879310898542247.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 25, --version-code, 357, --version-name, 2.8.0.2701, --no-version-vectors, -F, C:\Users\anth0\AppData\Local\Temp\APKTOOL4082212122753963634.tmp, -0, arsc, -0, sql, -0, arsc, -I, C:\Users\anth0\AppData\Local\apktool\framework\1.apk, -S, C:\Users\anth0\Documents\Visual Studio 2015\Projects\Imgur\base\res, -M, C:\Users\anth0\Documents\Visual Studio 2015\Projects\Imgur\base\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:477)
        at brut.androlib.Androlib.buildResources(Androlib.java:411)
        at brut.androlib.Androlib.build(Androlib.java:310)
        at brut.androlib.Androlib.build(Androlib.java:263)
        at brut.apktool.Main.cmdBuild(Main.java:227)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\anth0\AppData\Local\Temp\brut_util_Jar_7716879310898542247.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 25, --version-code, 357, --version-name, 2.8.0.2701, --no-version-vectors, -F, C:\Users\anth0\AppData\Local\Temp\APKTOOL4082212122753963634.tmp, -0, arsc, -0, sql, -0, arsc, -I, C:\Users\anth0\AppData\Local\apktool\framework\1.apk, -S, C:\Users\anth0\Documents\Visual Studio 2015\Projects\Imgur\base\res, -M, C:\Users\anth0\Documents\Visual Studio 2015\Projects\Imgur\base\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:440)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:463)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\anth0\AppData\Local\Temp\brut_util_Jar_7716879310898542247.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 25, --version-code, 357, --version-name, 2.8.0.2701, --no-version-vectors, -F, C:\Users\anth0\AppData\Local\Temp\APKTOOL4082212122753963634.tmp, -0, arsc, -0, sql, -0, arsc, -I, C:\Users\anth0\AppData\Local\apktool\framework\1.apk, -S, C:\Users\anth0\Documents\Visual Studio 2015\Projects\Imgur\base\res, -M, C:\Users\anth0\Documents\Visual Studio 2015\Projects\Imgur\base\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:434)
        ... 6 more
```

### Steps to Reproduce
1. `apktool d base.apk`
2. `apktool b base`

### APK
http://jmp.sh/ZHynPZx

**Comment by iBotPeaches** [comment]
Couldn't seem to duplicate.

```
➜  Bug1422 apktool d base.apk 
I: Using Apktool 2.2.2 on base.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1422 apktool b base
I: Using Apktool 2.2.2
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
➜  Bug1422 
```

Maybe your framework is out of date. Give `apktool empty-framework-dir` a shot.
