### ISSUE TITLE
error ...

### ISSUE THREAD

**Issue by kevinet** [iBotPeaches/Apktool#1426]
### Information
1. **Apktool Version (`apktool -version`)** -2.2.2
2. **Operating System (Mac, Linux, Windows)** -mac
3. **APK From? (Playstore, ROM, Other)** -other

### Stacktrace/Logcat
```
I: Using Apktool 2.2.2
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: /Users/kevin/work/buildTools/temp/res/values-v23/styles.xml:7: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/WindowTitle'.
W: 
W: /Users/kevin/work/buildTools/temp/res/values-v23/styles.xml:8: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/WindowTitleBackground'.
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/qx/rgvslxy94dxd2j5s433wr_q40000gn/T/brut_util_Jar_834728102755725425.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 22, --version-code, 4011, --version-name, 4.0.1, --no-version-vectors, -F, /var/folders/qx/rgvslxy94dxd2j5s433wr_q40000gn/T/APKTOOL7994603508774947424.tmp, -0, arsc, -0, arsc, -I, /Users/kevin/Library/apktool/framework/1.apk, -S, /Users/kevin/work/buildTools/temp/res, -M, /Users/kevin/work/buildTools/temp/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:477)
	at brut.androlib.Androlib.buildResources(Androlib.java:411)
	at brut.androlib.Androlib.build(Androlib.java:310)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/qx/rgvslxy94dxd2j5s433wr_q40000gn/T/brut_util_Jar_834728102755725425.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 22, --version-code, 4011, --version-name, 4.0.1, --no-version-vectors, -F, /var/folders/qx/rgvslxy94dxd2j5s433wr_q40000gn/T/APKTOOL7994603508774947424.tmp, -0, arsc, -0, arsc, -I, /Users/kevin/Library/apktool/framework/1.apk, -S, /Users/kevin/work/buildTools/temp/res, -M, /Users/kevin/work/buildTools/temp/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:440)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:463)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/qx/rgvslxy94dxd2j5s433wr_q40000gn/T/brut_util_Jar_834728102755725425.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 22, --version-code, 4011, --version-name, 4.0.1, --no-version-vectors, -F, /var/folders/qx/rgvslxy94dxd2j5s433wr_q40000gn/T/APKTOOL7994603508774947424.tmp, -0, arsc, -0, arsc, -I, /Users/kevin/Library/apktool/framework/1.apk, -S, /Users/kevin/work/buildTools/temp/res, -M, /Users/kevin/work/buildTools/temp/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:434)
	... 6 more
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
http://openbox.mobilem.360.cn/index/d/sid/1768944

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? yes
3. Are you using the latest apktool version? yes

**Comment by iBotPeaches** [comment]
```
➜  Bug1426 wget http://openbox.mobilem.360.cn/index/d/sid/1768944
--2017-03-15 07:17:50--  http://openbox.mobilem.360.cn/index/d/sid/1768944
Resolving openbox.mobilem.360.cn (openbox.mobilem.360.cn)... 218.30.118.222
Connecting to openbox.mobilem.360.cn (openbox.mobilem.360.cn)|218.30.118.222|:80... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: http://shouji.360tpcdn.com/170314/44df3c68b2159cc9929fba84cb615888/cn.wecook.app_4100.apk [following]
--2017-03-15 07:17:51--  http://shouji.360tpcdn.com/170314/44df3c68b2159cc9929fba84cb615888/cn.wecook.app_4100.apk
Resolving shouji.360tpcdn.com (shouji.360tpcdn.com)... 104.192.108.19, 104.192.108.20
Connecting to shouji.360tpcdn.com (shouji.360tpcdn.com)|104.192.108.19|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 18785037 (18M) [application/vnd.android.package-archive]
Saving to: ‘1768944’

1768944                                   100%[==================================================================================>]  17.91M  2.14MB/s    in 11s     

2017-03-15 07:18:02 (1.64 MB/s) - ‘1768944’ saved [18785037/18785037]

➜  Bug1426 ls
1768944
➜  Bug1426 mv 1768944 foo.apk
➜  Bug1426 apktool d foo.apk 
I: Using Apktool 2.2.2 on foo.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1426 apktool b foo
I: Using Apktool 2.2.2
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
➜  Bug1426 
```

Couldn't duplicate. Try running `apktool empty-framework-dir --force` and try both the decode & build again.
