### ISSUE TITLE
qq6.6.9 return complie err

### ISSUE THREAD

**Issue by qssq** [iBotPeaches/Apktool#1427]
apktool version 2.2.2
download url
[qq6.6.9](http://ncy1.mqego.com/qq6.6.9zsb.apk)
```
W:
W: F:\QQ_weichat\669\src669.apk_dir\res\layout-mdpi-v4\qapp_center_notification.xml:12: error: Error: No resource found that matches the given name (at 'style' with value '@style/progress_horizontal')
.
W:
W: F:\QQ_weichat\669\src669.apk_dir\res\layout-hdpi-v4\qapp_center_notification.xml:12: error: Error: No resource found that matches the given name (at 'style' with value '@style/progress_horizontal')
.
W:
W: F:\QQ_weichat\669\src669.apk_dir\res\layout\qzone_custom_commen_title.xml:2: error: No resource identifier found for attribute 'skintype' in package 'com.tencent.mobileqq'
W:
W: F:\QQ_weichat\669\src669.apk_dir\res\drawable\name_APKTOOL_DUPLICATENAME_0x7f02079e.xml:5: error: No resource identifier found for attribute 'tint_color' in package 'com.tencent.mobileqq'
W:
W: F:\QQ_weichat\669\src669.apk_dir\res\drawable\name_APKTOOL_DUPLICATENAME_0x7f02079e.xml:7: error: No resource identifier found for attribute 'tint_color' in package 'com.tencent.mobileqq'
W:
W: F:\QQ_weichat\669\src669.apk_dir\res\drawable\name_APKTOOL_DUPLICATENAME_0x7f02079e.xml:8: error: No resource identifier found for attribute 'tint_color' in package 'com.tencent.mobileqq'
W:
W: F:\QQ_weichat\669\src669.apk_dir\res\drawable\name_APKTOOL_DUPLICATENAME_0x7f0207a2.xml:5: error: No resource identifier found for attribute 'tint_color' in package 'com.tencent.mobileqq'
W:
W: F:\QQ_weichat\669\src669.apk_dir\res\drawable\name_APKTOOL_DUPLICATENAME_0x7f0207a2.xml:7: error: No resource identifier found for attribute 'tint_color' in package 'com.tencent.mobileqq'
W:
W: F:\QQ_weichat\669\src669.apk_dir\res\drawable\name_APKTOOL_DUPLICATENAME_0x7f0207a2.xml:9: error: No resource identifier found for attribute 'tint_color' in package 'com.tencent.mobileqq'
W:
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Administrator\AppData\Local\Temp\brut_
util_Jar_5163487404651140567.tmp, p, --forced-package-id, 127, --min-sdk-version, 8, --target-sdk-version, 9, --version-code, 482, --version-name, 6.6.9, --no-version-vectors, -F, C:\Users\Administrat
or\AppData\Local\Temp\APKTOOL5013041594688246490.tmp, -0, arsc, -0, apk, -0, assets/apollo_def_rsc, -0, assets/classes2.dex.MD5, -0, assets/classes3.dex.MD5, -0, assets/classes4.dex.MD5, -0, assets/cl
asses5.dex.MD5, -0, ini, -0, txt, -0, assets/txlib, -0, signature, -0, assets/plugins/PluginManifest, -0, material, -0, frag, -0, vert, -0, fp, -0, vp, -0, arsc, -I, C:\Users\Administrator\AppData\Loc
al\apktool\framework\1.apk, -S, F:\QQ_weichat\669\src669.apk_dir\res, -M, F:\QQ_weichat\669\src669.apk_dir\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:477)
        at brut.androlib.Androlib.buildResources(Androlib.java:411)
        at brut.androlib.Androlib.build(Androlib.java:310)
        at brut.androlib.Androlib.build(Androlib.java:263)
        at brut.apktool.Main.cmdBuild(Main.java:227)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Administrator\AppData\Local\Temp\brut_util_Jar_5163487404651140567.tmp, p, --forced-pac
kage-id, 127, --min-sdk-version, 8, --target-sdk-version, 9, --version-code, 482, --version-name, 6.6.9, --no-version-vectors, -F, C:\Users\Administrator\AppData\Local\Temp\APKTOOL5013041594688246490.
tmp, -0, arsc, -0, apk, -0, assets/apollo_def_rsc, -0, assets/classes2.dex.MD5, -0, assets/classes3.dex.MD5, -0, assets/classes4.dex.MD5, -0, assets/classes5.dex.MD5, -0, ini, -0, txt, -0, assets/txli
b, -0, signature, -0, assets/plugins/PluginManifest, -0, material, -0, frag, -0, vert, -0, fp, -0, vp, -0, arsc, -I, C:\Users\Administrator\AppData\Local\apktool\framework\1.apk, -S, F:\QQ_weichat\669
\src669.apk_dir\res, -M, F:\QQ_weichat\669\src669.apk_dir\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:440)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:463)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Administrator\AppData\Local\Temp\brut_util_Jar_5163487404651140567.tmp, p, --forced-package-id, 127, --min-sdk-version,
8, --target-sdk-version, 9, --version-code, 482, --version-name, 6.6.9, --no-version-vectors, -F, C:\Users\Administrator\AppData\Local\Temp\APKTOOL5013041594688246490.tmp, -0, arsc, -0, apk, -0, asset
s/apollo_def_rsc, -0, assets/classes2.dex.MD5, -0, assets/classes3.dex.MD5, -0, assets/classes4.dex.MD5, -0, assets/classes5.dex.MD5, -0, ini, -0, txt, -0, assets/txlib, -0, signature, -0, assets/plug
ins/PluginManifest, -0, material, -0, frag, -0, vert, -0, fp, -0, vp, -0, arsc, -I, C:\Users\Administrator\AppData\Local\apktool\framework\1.apk, -S, F:\QQ_weichat\669\src669.apk_dir\res, -M, F:\QQ_we
ichat\669\src669.apk_dir\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:434)
        ... 6 more
转换完毕 生成的apk在F:\QQ_weichat\669\src669.apk_dir/dist/目录下
```

**Comment by yanzi1225627** [comment]
This is the same problem with [1423](https://github.com/iBotPeaches/Apktool/issues/1423), I suggest you use apktool V2.0.3 version.

**Comment by iBotPeaches** [comment]
This is a separate issue related to AndResGuard, as I can see the `/R` folder and resources.

**Comment by iBotPeaches** [comment]
Merging into https://github.com/iBotPeaches/Apktool/issues/1423 as duplicate.
