### ISSUE TITLE
i got error while recompiling systemui.apk from samsung note 3 

### ISSUE THREAD

**Issue by ghost** [iBotPeaches/Apktool#1430]
### Information
1. *apkt00l version 2.2.2
2. Lubuntu 16.04
3. from rom 

**issue** 
**1.this when i decompile** 
```
wahaj@wahaj-sheikh:/usr/local/bin$ sudo apktool if SystemUI.apk 
I: Framework installed to: /root/.local/share/apktool/framework/127.apk
wahaj@wahaj-sheikh:/usr/local/bin$ sudo apktool d SystemUI.apk 
I: Using Apktool 2.2.2 on SystemUI.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /root/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
```
**after i do no change and modification is systemui just decompile and recompile** 
```
wahaj@wahaj-sheikh:/usr/local/bin$ sudo apktool b SystemUI
I: Using Apktool 2.2.2
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: /usr/local/bin/SystemUI/res/values/styles.xml:2130: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Widget.TimePicker'.
W: 
W: /usr/local/bin/SystemUI/res/values/styles.xml:2143: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Widget.HorizontalScrollView'.
W: 
W: /usr/local/bin/SystemUI/res/values/styles.xml:2172: error: Error: No resource found that matches the given name: attr 'android:buttonPanelSideLayout'.
W: 
W: /usr/local/bin/SystemUI/res/values/styles.xml:2193: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Widget.TimePicker'.
W: 
W: /usr/local/bin/SystemUI/res/values/styles.xml:2194: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Widget.TimePicker'.
W: 
W: /usr/local/bin/SystemUI/res/values/styles.xml:2199: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Widget.TimePicker'.
W: 
W: /usr/local/bin/SystemUI/res/values/styles.xml:2208: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Widget.TimePicker'.
W: 
W: /usr/local/bin/SystemUI/res/values/styles.xml:2311: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Theme.Holo.CompactMenu'.
W: 
W: /usr/local/bin/SystemUI/res/values/styles.xml:2418: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Theme.Holo.CompactMenu'.
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_2076923831404745433.tmp, p, --forced-package-id, 127, --min-sdk-version, 25, --target-sdk-version, 25, --version-code, 25, --version-name, 7.1.1, --no-version-vectors, -F, /tmp/APKTOOL3343728554734539319.tmp, -0, arsc, -0, res/drawable-nodpi-v4/texture6_alpha1, -0, res/drawable-nodpi-v4/texture_alpha, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /usr/local/bin/SystemUI/res, -M, /usr/local/bin/SystemUI/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:477)
	at brut.androlib.Androlib.buildResources(Androlib.java:411)
	at brut.androlib.Androlib.build(Androlib.java:310)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_2076923831404745433.tmp, p, --forced-package-id, 127, --min-sdk-version, 25, --target-sdk-version, 25, --version-code, 25, --version-name, 7.1.1, --no-version-vectors, -F, /tmp/APKTOOL3343728554734539319.tmp, -0, arsc, -0, res/drawable-nodpi-v4/texture6_alpha1, -0, res/drawable-nodpi-v4/texture_alpha, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /usr/local/bin/SystemUI/res, -M, /usr/local/bin/SystemUI/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:440)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:463)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_2076923831404745433.tmp, p, --forced-package-id, 127, --min-sdk-version, 25, --target-sdk-version, 25, --version-code, 25, --version-name, 7.1.1, --no-version-vectors, -F, /tmp/APKTOOL3343728554734539319.tmp, -0, arsc, -0, res/drawable-nodpi-v4/texture6_alpha1, -0, res/drawable-nodpi-v4/texture_alpha, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /usr/local/bin/SystemUI/res, -M, /usr/local/bin/SystemUI/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:434)
	... 6 more
```

### Frameworks (change file extension to apk)
[framework-res.zip](https://github.com/iBotPeaches/Apktool/files/769103/framework-res.zip)

### APK (change file extension to apk)
[SystemUI.zip](https://github.com/iBotPeaches/Apktool/files/769104/SystemUI.zip)

@iBotPeaches help me plz

**Comment by zitronenmelissa** [comment]
Samsung Roms have special frameworks. You habe to install the correct framework(s), especially for compiling SystemUI. I had the same problem with Slim Rom (which uses framework-res.apk and org.slim.framework-res.apk)
Remove previously installed frameworks from .local/share/apktool/framework/ 
Then install correct frameworks: framework-res.apk and the Samsung Touchwiz framework twframework-res.apk.   (apktool if path/to/framework/framework-xy.apk)
Then You can decompile - edit - recompile :-)    worked for me

**Comment by wahajs00** [comment]
Thanks i iwill try

**Comment by iBotPeaches** [comment]
I don't have samsung so my chance to be able to do anything here outside of decode/build is rare. Closing as 4+ years old and no responses.
