### ISSUE TITLE
Error when trying to rebuild apk after changing the ids of the xml files in res/layout folder

### ISSUE THREAD

**Issue by d0ntchadon** [iBotPeaches/Apktool#1432]
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.2
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - Other

### Stacktrace/Logcat

I: Using Apktool 2.2.2
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: /home/maimat3/fyp/sample/res/layout/main.xml:4: error: Error: No resource found that matches the given name (at 'textAppearance' with value '@string/asdqwe').
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_75584545060659084.tmp, p, --forced-package-id, 127, --min-sdk-version, 8, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /tmp/APKTOOL6927997678515264928.tmp, -0, arsc, -0, arsc, -I, /home/maimat3/.local/share/apktool/framework/1.apk, -S, /home/maimat3/fyp/sample/res, -M, /home/maimat3/fyp/sample/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:477)
	at brut.androlib.Androlib.buildResources(Androlib.java:411)
	at brut.androlib.Androlib.build(Androlib.java:310)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_75584545060659084.tmp, p, --forced-package-id, 127, --min-sdk-version, 8, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /tmp/APKTOOL6927997678515264928.tmp, -0, arsc, -0, arsc, -I, /home/maimat3/.local/share/apktool/framework/1.apk, -S, /home/maimat3/fyp/sample/res, -M, /home/maimat3/fyp/sample/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:440)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:463)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_75584545060659084.tmp, p, --forced-package-id, 127, --min-sdk-version, 8, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /tmp/APKTOOL6927997678515264928.tmp, -0, arsc, -0, arsc, -I, /home/maimat3/.local/share/apktool/framework/1.apk, -S, /home/maimat3/fyp/sample/res, -M, /home/maimat3/fyp/sample/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:434)
	... 6 more

### Steps to Reproduce
1. Decode a sample apk
2. Go to sample/res/layout and open any xml file there
3. Rename 1 of the field there, i.e. changing "@string/headcolor" to "@string/asdasd"
4.Build the sample back.

**Comment by iBotPeaches** [comment]
I can't tell if this is a real report or not.

You just made a reference to a string that doesn't exist, so of course it would fail.

```
W: /home/maimat3/fyp/sample/res/layout/main.xml:4: error: Error: No resource found that matches the given name (at 'textAppearance' with value '@string/asdqwe').
```

**Comment by d0ntchadon** [comment]
sorry i wasnt clear in explaining my problem. but even if i changed the corresponding field in the dex file to the same name by disassembling it with baksmali and changing the corresponding name,  the same error still occurs.
