### ISSUE TITLE
No resource identifier found for attribute 'shortcutId' in package 'android'

### ISSUE THREAD

**Issue by udaykoushik** [iBotPeaches/Apktool#1433]
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.2
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat

```
W: ~/xxx/res/xml-v25/shortcuts.xml:4: error: No resource identifier found for attribute 'shortcutId' in package 'android'
W: 
W: ~/xxx/res/xml-v25/shortcuts.xml:4: error: No resource identifier found for attribute 'shortcutShortLabel' in package 'android'
W: 
W: ~/xxx/res/xml-v25/shortcuts.xml:4: error: No resource identifier found for attribute 'shortcutLongLabel' in package 'android'
W: 
W: ~/xxx/res/xml-v25/shortcuts.xml:4: error: No resource identifier found for attribute 'shortcutDisabledMessage' in package 'android'
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_6388456163199079315.tmp, p, --forced-package-id, 127, --min-sdk-version, 18, --target-sdk-version, 22, --version-code, 20, --version-name, 1.0.8, --no-version-vectors, -F, /tmp/APKTOOL651736895095854420.tmp, -0, arsc, -0, arsc, -I, ~/.local/share/apktool/framework/1.apk, -S, ~/xxx/res, -M, ~/xxx/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:477)
	at brut.androlib.Androlib.buildResources(Androlib.java:411)
	at brut.androlib.Androlib.build(Androlib.java:310)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_6388456163199079315.tmp, p, --forced-package-id, 127, --min-sdk-version, 18, --target-sdk-version, 22, --version-code, 20, --version-name, 1.0.8, --no-version-vectors, -F, /tmp/APKTOOL651736895095854420.tmp, -0, arsc, -0, arsc, -I, ~/.local/share/apktool/framework/1.apk, -S, ~/xxx/res, -M, ~/xxx/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:440)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:463)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_6388456163199079315.tmp, p, --forced-package-id, 127, --min-sdk-version, 18, --target-sdk-version, 22, --version-code, 20, --version-name, 1.0.8, --no-version-vectors, -F, /tmp/APKTOOL651736895095854420.tmp, -0, arsc, -0, arsc, -I, ~/.local/share/apktool/framework/1.apk, -S, ~/xxx/res, -M, ~/xxx/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:434)
	... 6 more
```

### Steps to Reproduce
1. `apktool d <something.apk>`
2. `apktool b <something>`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? YES
2. If you are trying to install a modified apk, did you resign it? YES
3. Are you using the latest apktool version? YES

**Comment by udaykoushik** [comment]
Using Apktool 2.2.3-6cc251-SNAPSHOT solved the issue
