### ISSUE TITLE
Exception in thread "main" brut.androlib.AndrolibException: Could not decode XML(IOException)

### ISSUE THREAD

**Issue by mgsjon** [iBotPeaches/Apktool#1435]
### Information
1. **Apktool Version (`apktool -version`)** -apktool-2.2.3-dirty-small
2. **Operating System (Mac, Linux, Windows)** -win10
3. **APK From? (Playstore, ROM, Other)** [xpose.apk](https://drive.google.com/open?id=0B1O-7Dbpw-HDN1VHZFJhZVBXQ1k)

### Stacktrace/Logcat
```
I: Using Apktool @version@ on photo.apk
I: Loading resource table...
I: finied Loading resource table!
I: Decoding AndroidManifest.xml with resources...
Exception in thread "main" brut.androlib.AndrolibException: Could not decode XML(IOException)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:149)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:155)
	at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:140)
	at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:208)
	at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:136)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:106)
	at brut.apktool.Main.cmdDecode(Main.java:172)
	at brut.apktool.Main.main(Main.java:87)
Caused by: java.io.IOException: Expected: 0x00080003, got: 0x00080000
	at brut.util.ExtDataInput.skipCheckInt(ExtDataInput.java:48)
	at brut.androlib.res.decoder.AXmlResourceParser.doNext(AXmlResourceParser.java:843)
	at brut.androlib.res.decoder.AXmlResourceParser.next(AXmlResourceParser.java:100)
	at brut.androlib.res.decoder.AXmlResourceParser.nextToken(AXmlResourceParser.java:110)
	at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.nextToken(XmlPullParserDelegate.java:105)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:140)
	... 7 more
```
### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
cannot free
### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?-yes
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?-yes ,use source code to decompile the apk

**Comment by iBotPeaches** [comment]
Do you have apk? For issues like these, need apk to investigate further.

**Comment by wahajs00** [comment]
hey i have also this same error on Lubuntu 64 bit

**Comment by mgsjon** [comment]
hi,this is the trouble apk file,@iBotPeaches

**Comment by mgsjon** [comment]
@wahajs00 hi,how did you  solved the error?

**Comment by iBotPeaches** [comment]
Confirmed.

```
➜  Bug1435 apktool d xpose_t.apk -f -s
I: Using Apktool 2.2.2 on xpose_t.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
Exception in thread "main" brut.androlib.AndrolibException: Could not decode XML
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:147)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:153)
	at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:140)
	at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:208)
	at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:136)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:106)
	at brut.apktool.Main.cmdDecode(Main.java:166)
	at brut.apktool.Main.main(Main.java:81)
Caused by: java.io.IOException: Expected: 0x00080003, got: 0x00080000
	at brut.util.ExtDataInput.skipCheckInt(ExtDataInput.java:48)
	at brut.androlib.res.decoder.AXmlResourceParser.doNext(AXmlResourceParser.java:843)
	at brut.androlib.res.decoder.AXmlResourceParser.next(AXmlResourceParser.java:100)
	at brut.androlib.res.decoder.AXmlResourceParser.nextToken(AXmlResourceParser.java:110)
	at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.nextToken(XmlPullParserDelegate.java:105)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:140)
	... 7 more
```

**Comment by wahajs00** [comment]
I haven't solve this isue

**Comment by EmmerikSchou** [comment]
I had the sam error, but when I launched cmd in admin mode and put in the full path ("C:\windows\Test.apk) it worked perfectly

**Comment by itruf** [comment]
Same error

**Comment by sankethj** [comment]
I have the same issue help here 
I am a linux user

**Comment by iBotPeaches** [comment]
Sorry not sure. Application says it has virus so it was removed from computer, drive will refuse to give it and I have no idea how to download something from Baidu.

Either way this ticket is pushing 4-5 years. If we didn't solve it then, we wouldn't now.
