### ISSUE TITLE
Apktool 2.2.2 Error when decompiling and recompiling apks

### ISSUE THREAD

**Issue by darkprince626** [iBotPeaches/Apktool#1437]
Hi I'm using apktool version 2.2.2 and am unable to compile or recompile any apks. This includes apks from apkmirror and google play. I'm using this on windows 10. Any help would be appreciated. Thanks!

John
This is the error I get:

```
I: Using Apktool 2.2.2
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: java.io.FileNotFoundException: cask.apk (The system cannot find the file specified)
        at brut.androlib.Androlib.readMetaFile(Androlib.java:258)
        at brut.androlib.Androlib.build(Androlib.java:270)
        at brut.androlib.Androlib.build(Androlib.java:263)
        at brut.apktool.Main.cmdBuild(Main.java:227)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.directory.DirectoryException: java.io.FileNotFoundException: cask.apk (The system cannot find the file specified)
        at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:55)
        at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:38)
        at brut.directory.ExtFile.getDirectory(ExtFile.java:51)
        at brut.androlib.Androlib.readMetaFile(Androlib.java:254)
        ... 4 more
Caused by: java.io.FileNotFoundException: cask.apk (The system cannot find the file specified)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:53)
        ... 7 more
```

**Comment by iBotPeaches** [comment]
What command are you running? This seems to be an invalid use of the params based on error.

**Comment by darkprince626** [comment]
I am running the command
apktool b app.apk

**Comment by darkprince626** [comment]
Ooops. I used the wrong commands it seems.
