### ISSUE TITLE
 brut.androlib.AndrolibException

### ISSUE THREAD

**Issue by linuxforarabs** [iBotPeaches/Apktool#1465]
### Information
1. **Apktool Version (`2.2.2`)** -
2. **Operating System (Mac, Linux, Windows)*linux-ubuntu* -
3. **APK From? (Playstore, ROM, Other)** -ROM

### Stacktrace/Logcat

```: Using Apktool 2.0.2-dirty on SystemUI.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:52)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:544)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:63)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:55)
	at brut.androlib.Androlib.getResTable(Androlib.java:65)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:197)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:96)
	at brut.apktool.Main.cmdDecode(Main.java:165)
	at brut.apktool.Main.main(Main.java:81)
Caused by: java.io.IOException: Expected: 0x00000008, got: 0x00000000
	at brut.util.ExtDataInput.skipCheckShort(ExtDataInput.java:56)
	at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:254)
	at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:203)
	at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:191)
	at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:159)
	at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:116)
	at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:78)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
	... 8 more

```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)
/system/priv-app
### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?YES
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?yes

**Comment by iBotPeaches** [comment]
ROM this is from? Possible to get frameworks and associated application?

**Comment by linuxforarabs** [comment]
4 files i download it from samsung-updates.com
yes i upload it ? 
frameworks-res.apk

**Comment by iBotPeaches** [comment]
Yes please upload all frameworks and the apk you used in the original report.

**Comment by linuxforarabs** [comment]
[framework-res.apk.zip](https://github.com/iBotPeaches/Apktool/files/883264/framework-res.apk.zip)

**Comment by iBotPeaches** [comment]
```
➜  Bug1465 apktool d framework-res.apk 
I: Using Apktool 2.2.3-74f76a-SNAPSHOT on framework-res.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1465 apktool b framework-res
I: Using Apktool 2.2.3-74f76a-SNAPSHOT
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
W: warning: string 'abbrev_month' has no default translation.
W: warning: string 'abbrev_month_day' has no default translation.
W: warning: string 'abbrev_month_day_year' has no default translation.
W: warning: string 'abbrev_month_year' has no default translation.
W: warning: string 'abbrev_wday_abbrev_month_day_no_year' has no default translation.
W: warning: string 'abbrev_wday_day_abbrev_month_no_year' has no default translation.
...
I: Building apk file...
I: Copying unknown files/dir...
➜  Bug1465 
```

Decoded and Rebuilt. No errors. Couldn't duplicate.
