### ISSUE TITLE
can not recompile apk

### ISSUE THREAD

**Issue by u8-xiaohei** [iBotPeaches/Apktool#1466]
### Information
1. apktool 2.2.2
2. Operating System (Windows)
3. apk build with android studio

I export an apk from android studio.  I decompiled it with apktool successfully.
but when I tried to recompile it with apktool b command, it failed with error "No Resource found".
I didn't change anything after decompile, just to recompile it. I had delete the framework/1.apk.

here is the apk: http://121.42.144.254/u8.apk

the stacktrace is :
###
```
I: Building resources...
W: G:\git_coding\Android\U8SDKTool-Win-P34\tool\win\u8\res\values-v24\styles.xml
:7: error: Error retrieving parent for item: No resource found that matches the
given name '@android:style/Animation.OptionsPanel'.
W:
W: G:\git_coding\Android\U8SDKTool-Win-P34\tool\win\u8\res\values-v24\styles.xml
:8: error: Error retrieving parent for item: No resource found that matches the
given name '@android:style/Animation.LockScreen'.
W:
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.Androl
ibException: brut.common.BrutException: could not exec (exit code = 1): [C:\User
s\CHENJI~1.CHE\AppData\Local\Temp\brut_util_Jar_7322565221153004207.tmp, p, --fo
rced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 25, --version
-code, 1, --version-name, 1.0, --no-version-vectors, -F, C:\Users\CHENJI~1.CHE\A
ppData\Local\Temp\APKTOOL7257789197178797238.tmp, -0, arsc, -0, arsc, -I, C:\Use
rs\chenjie.chen\AppData\Local\apktool\framework\1.apk, -S, G:\git_coding\Android
\U8SDKTool-Win-P34\tool\win\u8\res, -M, G:\git_coding\Android\U8SDKTool-Win-P34\
tool\win\u8\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:477)
        at brut.androlib.Androlib.buildResources(Androlib.java:411)
        at brut.androlib.Androlib.build(Androlib.java:310)
        at brut.androlib.Androlib.build(Androlib.java:263)
        at brut.apktool.Main.cmdBuild(Main.java:227)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not
 exec (exit code = 1): [C:\Users\CHENJI~1.CHE\AppData\Local\Temp\brut_util_Jar_7
322565221153004207.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --ta
rget-sdk-version, 25, --version-code, 1, --version-name, 1.0, --no-version-vecto
rs, -F, C:\Users\CHENJI~1.CHE\AppData\Local\Temp\APKTOOL7257789197178797238.tmp,
 -0, arsc, -0, arsc, -I, C:\Users\chenjie.chen\AppData\Local\apktool\framework\1
.apk, -S, G:\git_coding\Android\U8SDKTool-Win-P34\tool\win\u8\res, -M, G:\git_co
ding\Android\U8SDKTool-Win-P34\tool\win\u8\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.jav
a:440)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:463)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\
CHENJI~1.CHE\AppData\Local\Temp\brut_util_Jar_7322565221153004207.tmp, p, --forc
ed-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 25, --version-c
ode, 1, --version-name, 1.0, --no-version-vectors, -F, C:\Users\CHENJI~1.CHE\App
Data\Local\Temp\APKTOOL7257789197178797238.tmp, -0, arsc, -0, arsc, -I, C:\Users
\chenjie.chen\AppData\Local\apktool\framework\1.apk, -S, G:\git_coding\Android\U
8SDKTool-Win-P34\tool\win\u8\res, -M, G:\git_coding\Android\U8SDKTool-Win-P34\to
ol\win\u8\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.jav
a:434)
        ... 6 more
```

**Comment by iBotPeaches** [comment]
Couldn't duplicate on unix.

```
➜  Bug1466 apktool d u8.apk 
I: Using Apktool 2.2.3-74f76a-SNAPSHOT on u8.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1466 apktool b u8
I: Using Apktool 2.2.3-74f76a-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Building apk file...
I: Copying unknown files/dir...
➜  Bug1466 
```

Try running `apktool empty-framework-dir --force` and try again

**Comment by iBotPeaches** [comment]
Since this was a Windows ticket. I tried on Windows as well.

```
Connor@iBotPeaches MINGW64 ~/Desktop/bin
$ java -jar apktool.jar d u8.apk
I: Using Apktool 2.2.2 on u8.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Connor\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

Connor@iBotPeaches MINGW64 ~/Desktop/bin
$ java -jar apktool.jar b u8
I: Using Apktool 2.2.2
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Building apk file...
I: Copying unknown files/dir...

Connor@iBotPeaches MINGW64 ~/Desktop/bin
```

**Comment by u8-xiaohei** [comment]
@iBotPeaches  I'm really sorry to have cost you so much time and energy.  I delete the 1.apk from C:/Users/my_name/apktool/framework/1.apk。 but then I found the note in your website. the framework apk had changed to AppData/Local/ directory.

So when I deleted the correct framework apk， It's OK.  Thank you very much.
