### ISSUE TITLE
Problem with decompile resource apk.

### ISSUE THREAD

**Issue by maxben14** [iBotPeaches/Apktool#1472]
I try compile resource with apktool but get error.
--------------------------------------------------
Batch ApkTool                : 3.6.5
APKTOOL                      : apktool_2.2.2.jar
Экспертный режим             : НЕТ
Подпись                      : ДА
--------------------------------------------------

[*] Рекомпиляция SitiCard
I: Using Apktool 2.2.2
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
W: res\menu\k.xml:0: error: Resource entry k is already defined.
W: C:\Users\PC\Desktop\prilojenie\nbatch365\bin\..\_INPUT_APK\SitiCard\res\values\menus.xml:3: Originally defined here.
W: 
W: res\menu\k_APKTOOL_DUPLICATENAME_0x7f0f0001.xml:0: error: Resource entry k_APKTOOL_DUPLICATENAME_0x7f0f0001 is already defined.
W: C:\Users\PC\Desktop\prilojenie\nbatch365\bin\..\_INPUT_APK\SitiCard\res\values\menus.xml:4: Originally defined here.
W: 
W: res\menu\k_APKTOOL_DUPLICATENAME_0x7f0f0002.xml:0: error: Resource entry k_APKTOOL_DUPLICATENAME_0x7f0f0002 is already defined.
W: C:\Users\PC\Desktop\prilojenie\nbatch365\bin\..\_INPUT_APK\SitiCard\res\values\menus.xml:5: Originally defined here.
W: 
W: res\menu\k_APKTOOL_DUPLICATENAME_0x7f0f0003.xml:0: error: Resource entry k_APKTOOL_DUPLICATENAME_0x7f0f0003 is already defined.
W: C:\Users\PC\Desktop\prilojenie\nbatch365\bin\..\_INPUT_APK\SitiCard\res\values\menus.xml:6: Originally defined here.
W: 
W: res\menu\k_APKTOOL_DUPLICATENAME_0x7f0f0004.xml:0: error: Resource entry k_APKTOOL_DUPLICATENAME_0x7f0f0004 is already defined.
W: C:\Users\PC\Desktop\prilojenie\nbatch365\bin\..\_INPUT_APK\SitiCard\res\values\menus.xml:7: Originally defined here.
W: 
W: res\menu\k_APKTOOL_DUPLICATENAME_0x7f0f0005.xml:0: error: Resource entry k_APKTOOL_DUPLICATENAME_0x7f0f0005 is already defined.
W: C:\Users\PC\Desktop\prilojenie\nbatch365\bin\..\_INPUT_APK\SitiCard\res\values\menus.xml:8: Originally defined here.
W: 
W: res\menu\k_APKTOOL_DUPLICATENAME_0x7f0f0006.xml:0: error: Resource entry k_APKTOOL_DUPLICATENAME_0x7f0f0006 is already defined.
W: C:\Users\PC\Desktop\prilojenie\nbatch365\bin\..\_INPUT_APK\SitiCard\res\values\menus.xml:9: Originally defined here.
W: 
W: res\menu\k_APKTOOL_DUPLICATENAME_0x7f0f0007.xml:0: error: Resource entry k_APKTOOL_DUPLICATENAME_0x7f0f0007 is already defined.
W: C:\Users\PC\Desktop\prilojenie\nbatch365\bin\..\_INPUT_APK\SitiCard\res\values\menus.xml:10: Originally defined here.
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\PC\AppData\Local\Temp\BAT_temp\brut_util_Jar_2512721389132825227.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 25, --version-code, 9213, --version-name, 2.0.0.9520, --no-version-vectors, -F, C:\Users\PC\AppData\Local\Temp\BAT_temp\APKTOOL5506603121875378193.tmp, -0, arsc, -0, assets/classes.dex.dat, -0, assets/dp.arm-v7.so.dat, -0, assets/dp.arm-v8.so.dat, -0, assets/dp.arm.so.dat, -0, assets/dp.x86.so.dat, -0, assets/dp.x86_64.so.dat, -0, dat, -0, arsc, -I, .\framework\1.apk, -S, C:\Users\PC\Desktop\prilojenie\nbatch365\bin\..\_INPUT_APK\SitiCard\res, -M, C:\Users\PC\Desktop\prilojenie\nbatch365\bin\..\_INPUT_APK\SitiCard\AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:477)
	at brut.androlib.Androlib.buildResources(Androlib.java:411)
	at brut.androlib.Androlib.build(Androlib.java:310)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\PC\AppData\Local\Temp\BAT_temp\brut_util_Jar_2512721389132825227.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 25, --version-code, 9213, --version-name, 2.0.0.9520, --no-version-vectors, -F, C:\Users\PC\AppData\Local\Temp\BAT_temp\APKTOOL5506603121875378193.tmp, -0, arsc, -0, assets/classes.dex.dat, -0, assets/dp.arm-v7.so.dat, -0, assets/dp.arm-v8.so.dat, -0, assets/dp.arm.so.dat, -0, assets/dp.x86.so.dat, -0, assets/dp.x86_64.so.dat, -0, dat, -0, arsc, -I, .\framework\1.apk, -S, C:\Users\PC\Desktop\prilojenie\nbatch365\bin\..\_INPUT_APK\SitiCard\res, -M, C:\Users\PC\Desktop\prilojenie\nbatch365\bin\..\_INPUT_APK\SitiCard\AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:440)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:463)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\PC\AppData\Local\Temp\BAT_temp\brut_util_Jar_2512721389132825227.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 25, --version-code, 9213, --version-name, 2.0.0.9520, --no-version-vectors, -F, C:\Users\PC\AppData\Local\Temp\BAT_temp\APKTOOL5506603121875378193.tmp, -0, arsc, -0, assets/classes.dex.dat, -0, assets/dp.arm-v7.so.dat, -0, assets/dp.arm-v8.so.dat, -0, assets/dp.arm.so.dat, -0, assets/dp.x86.so.dat, -0, assets/dp.x86_64.so.dat, -0, dat, -0, arsc, -I, .\framework\1.apk, -S, C:\Users\PC\Desktop\prilojenie\nbatch365\bin\..\_INPUT_APK\SitiCard\res, -M, C:\Users\PC\Desktop\prilojenie\nbatch365\bin\..\_INPUT_APK\SitiCard\AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:434)
	... 6 more
[*] ---> Ошибка рекомпиляции "SitiCard"

ГОТОВО с 1 ОШИБКАМИ.

My apk http://rgho.st/8vNCYVpyP

Please, help me how decompile resource in this apk.

**Comment by iBotPeaches** [comment]
> File is deleted

Can't confirm or investigate. Closing this. You may re-upload and leave a comment.

**Comment by maxben14** [comment]
Sorry, i re-upload apk http://rgho.st/6MCmqYV8c

**Comment by iBotPeaches** [comment]
Same APK as #1474 , closing as duplicate.
