### ISSUE TITLE
Unable to recompile SystemUI and Settings from LOS 14.1

### ISSUE THREAD

**Issue by Phone-Guru** [iBotPeaches/Apktool#1473]
### Information
1. **Apktool Version (`apktool -version`)** -2.2.2
2. **Operating System (Mac, Linux, Windows)** -Windows
3. **APK From? (Playstore, ROM, Other)** -Ressurection Remix ROM for Galaxy S4

### Stacktrace/Logcat

```
|07/04/2017 -- 17:17:47.09| 
-------------------------------------------------------------------------- 
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
A subdirectory or file modified-system-apk-files-here already exists.
W: C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\res\values\styles.xml:1780: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Theme.DeviceDefault.Light.Voice'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\res\values\styles.xml:1847: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Preference.Material.DialogPreference.EditTextPreference'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\res\values\styles.xml:1855: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/PreferencePanel'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\res\values\styles.xml:1863: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/PreferenceHeaderList'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\res\values\styles.xml:1874: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/PreferenceFragmentList'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\res\values\styles.xml:1881: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/PreferenceHeaderPanel'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\res\values\styles.xml:1882: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/PreferenceHeaderList'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\res\values\styles.xml:1888: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/PreferenceFragment.Material'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\res\values\styles.xml:1974: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Animation.Material.Activity'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\res\values\styles.xml:2027: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Preference.Material.DialogPreference'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\res\values\styles.xml:2124: error: Error: No resource found that matches the given name: attr 'android:errorColor'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\res\values\styles.xml:2122: error: Error: No resource found that matches the given name: attr 'android:preferencePanelStyle'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\res\values\styles.xml:2123: error: Error: No resource found that matches the given name: attr 'android:regularColor'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\res\values\styles.xml:2125: error: Error: No resource found that matches the given name: attr 'android:successColor'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\res\values\styles.xml:2144: error: Error: No resource found that matches the given name: attr 'android:errorColor'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\res\values\styles.xml:2142: error: Error: No resource found that matches the given name: attr 'android:preferencePanelStyle'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\res\values\styles.xml:2143: error: Error: No resource found that matches the given name: attr 'android:regularColor'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\res\values\styles.xml:2145: error: Error: No resource found that matches the given name: attr 'android:successColor'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\res\values\styles.xml:2200: error: Error: No resource found that matches the given name: attr 'android:errorColor'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\res\values\styles.xml:2197: error: Error: No resource found that matches the given name: attr 'android:preferenceFragmentListStyle'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\res\values\styles.xml:2198: error: Error: No resource found that matches the given name: attr 'android:preferenceFragmentPaddingSide'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\res\values\styles.xml:2195: error: Error: No resource found that matches the given name: attr 'android:preferenceHeaderPanelStyle'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\res\values\styles.xml:2196: error: Error: No resource found that matches the given name: attr 'android:preferenceListStyle'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\res\values\styles.xml:2194: error: Error: No resource found that matches the given name: attr 'android:preferencePanelStyle'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\res\values\styles.xml:2199: error: Error: No resource found that matches the given name: attr 'android:regularColor'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\res\values\styles.xml:2201: error: Error: No resource found that matches the given name: attr 'android:successColor'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\res\values\styles.xml:2234: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/ThemeOverlay.DeviceDefault.Dark.ActionBar.Accent'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\res\values\styles.xml:2244: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Theme.DeviceDefault.Settings.DialogWhenLarge'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\res\values\styles.xml:2254: error: Error: No resource found that matches the given name: attr 'android:errorColor'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\res\values\styles.xml:2253: error: Error: No resource found that matches the given name: attr 'android:regularColor'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\res\values\styles.xml:2255: error: Error: No resource found that matches the given name: attr 'android:successColor'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\res\values\styles.xml:2269: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Theme.DeviceDefault.Settings.Dialog.Alert'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\res\values\styles.xml:2288: error: Error: No resource found that matches the given name: attr 'android:errorColor'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\res\values\styles.xml:2287: error: Error: No resource found that matches the given name: attr 'android:regularColor'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\res\values\styles.xml:2289: error: Error: No resource found that matches the given name: attr 'android:successColor'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\res\values\styles.xml:2295: error: Error: No resource found that matches the given name: attr 'android:regularColor'.
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Ilan\AppData\Local\Temp\brut_util_Jar_5081752759538112954.tmp, p, --forced-package-id, 127, --min-sdk-version, 25, --target-sdk-version, 25, --version-code, 25, --version-name, 7.1.1, --no-version-vectors, -F, C:\Users\Ilan\AppData\Local\Temp\APKTOOL3200032820442139146.tmp, -0, arsc, -0, res/drawable-nodpi-v4/gesture_ambient_lift, -0, res/drawable-nodpi-v4/gesture_ambient_tap, -0, res/drawable-nodpi-v4/gesture_double_tap, -0, res/drawable-nodpi-v4/gesture_fingerprint_swipe, -0, res/drawable-nodpi-v4/gesture_twist, -0, arsc, -I, C:\Users\Ilan\AppData\Local\apktool\framework\1.apk, -I, C:\Users\Ilan\AppData\Local\apktool\framework\63.apk, -S, C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\res, -M, C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:477)
	at brut.androlib.Androlib.buildResources(Androlib.java:411)
	at brut.androlib.Androlib.build(Androlib.java:310)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Ilan\AppData\Local\Temp\brut_util_Jar_5081752759538112954.tmp, p, --forced-package-id, 127, --min-sdk-version, 25, --target-sdk-version, 25, --version-code, 25, --version-name, 7.1.1, --no-version-vectors, -F, C:\Users\Ilan\AppData\Local\Temp\APKTOOL3200032820442139146.tmp, -0, arsc, -0, res/drawable-nodpi-v4/gesture_ambient_lift, -0, res/drawable-nodpi-v4/gesture_ambient_tap, -0, res/drawable-nodpi-v4/gesture_double_tap, -0, res/drawable-nodpi-v4/gesture_fingerprint_swipe, -0, res/drawable-nodpi-v4/gesture_twist, -0, arsc, -I, C:\Users\Ilan\AppData\Local\apktool\framework\1.apk, -I, C:\Users\Ilan\AppData\Local\apktool\framework\63.apk, -S, C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\res, -M, C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:440)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:463)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Ilan\AppData\Local\Temp\brut_util_Jar_5081752759538112954.tmp, p, --forced-package-id, 127, --min-sdk-version, 25, --target-sdk-version, 25, --version-code, 25, --version-name, 7.1.1, --no-version-vectors, -F, C:\Users\Ilan\AppData\Local\Temp\APKTOOL3200032820442139146.tmp, -0, arsc, -0, res/drawable-nodpi-v4/gesture_ambient_lift, -0, res/drawable-nodpi-v4/gesture_ambient_tap, -0, res/drawable-nodpi-v4/gesture_double_tap, -0, res/drawable-nodpi-v4/gesture_fingerprint_swipe, -0, res/drawable-nodpi-v4/gesture_twist, -0, arsc, -I, C:\Users\Ilan\AppData\Local\apktool\framework\1.apk, -I, C:\Users\Ilan\AppData\Local\apktool\framework\63.apk, -S, C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\res, -M, C:\Users\Ilan\Desktop\APKTool\projects\Settings.apk\AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:434)
	... 6 more



SystemUI
A subdirectory or file modified-system-apk-files-here already exists.
W: C:\Users\Ilan\Desktop\APKTool\projects\SystemUI.apk\res\values\styles.xml:2150: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/TextAppearance.StatusBar'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\SystemUI.apk\res\values\styles.xml:2163: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/TextAppearance.StatusBar.Ticker'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\SystemUI.apk\res\values\styles.xml:2209: error: Error: No resource found that matches the given name: attr 'android:navigationBarColordyanamic'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\SystemUI.apk\res\values\styles.xml:2230: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/TextAppearance.StatusBar'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\SystemUI.apk\res\values\styles.xml:2231: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/TextAppearance.StatusBar'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\SystemUI.apk\res\values\styles.xml:2236: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/TextAppearance.StatusBar'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\SystemUI.apk\res\values\styles.xml:2245: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/TextAppearance.StatusBar'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\SystemUI.apk\res\values\styles.xml:2348: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Theme.DeviceDefault.Settings.Dark'.
W: 
W: C:\Users\Ilan\Desktop\APKTool\projects\SystemUI.apk\res\values\styles.xml:2455: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Theme.DeviceDefault.Settings.Dark'.
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Ilan\AppData\Local\Temp\brut_util_Jar_8231030935897030033.tmp, p, --forced-package-id, 127, --min-sdk-version, 25, --target-sdk-version, 25, --version-code, 25, --version-name, 7.1.1, --no-version-vectors, -F, C:\Users\Ilan\AppData\Local\Temp\APKTOOL8378420772534824292.tmp, -0, arsc, -0, res/drawable-nodpi-v4/texture6_alpha1, -0, res/drawable-nodpi-v4/texture_alpha, -0, arsc, -I, C:\Users\Ilan\AppData\Local\apktool\framework\1.apk, -S, C:\Users\Ilan\Desktop\APKTool\projects\SystemUI.apk\res, -M, C:\Users\Ilan\Desktop\APKTool\projects\SystemUI.apk\AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:477)
	at brut.androlib.Androlib.buildResources(Androlib.java:411)
	at brut.androlib.Androlib.build(Androlib.java:310)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Ilan\AppData\Local\Temp\brut_util_Jar_8231030935897030033.tmp, p, --forced-package-id, 127, --min-sdk-version, 25, --target-sdk-version, 25, --version-code, 25, --version-name, 7.1.1, --no-version-vectors, -F, C:\Users\Ilan\AppData\Local\Temp\APKTOOL8378420772534824292.tmp, -0, arsc, -0, res/drawable-nodpi-v4/texture6_alpha1, -0, res/drawable-nodpi-v4/texture_alpha, -0, arsc, -I, C:\Users\Ilan\AppData\Local\apktool\framework\1.apk, -S, C:\Users\Ilan\Desktop\APKTool\projects\SystemUI.apk\res, -M, C:\Users\Ilan\Desktop\APKTool\projects\SystemUI.apk\AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:440)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:463)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Ilan\AppData\Local\Temp\brut_util_Jar_8231030935897030033.tmp, p, --forced-package-id, 127, --min-sdk-version, 25, --target-sdk-version, 25, --version-code, 25, --version-name, 7.1.1, --no-version-vectors, -F, C:\Users\Ilan\AppData\Local\Temp\APKTOOL8378420772534824292.tmp, -0, arsc, -0, res/drawable-nodpi-v4/texture6_alpha1, -0, res/drawable-nodpi-v4/texture_alpha, -0, arsc, -I, C:\Users\Ilan\AppData\Local\apktool\framework\1.apk, -S, C:\Users\Ilan\Desktop\APKTool\projects\SystemUI.apk\res, -M, C:\Users\Ilan\Desktop\APKTool\projects\SystemUI.apk\AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:434)
	... 6 more
```
### Steps to Reproduce
1. `apktool ` decompile
recompile

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version? yes

**Comment by Phone-Guru** [comment]
[fw.zip](https://github.com/iBotPeaches/Apktool/files/905886/fw.zip)

**Comment by Phone-Guru** [comment]
https://www.mediafire.com/?k7na3u3mcye3ald

**Comment by Phone-Guru** [comment]
Hello!!!!!

**Comment by iBotPeaches** [comment]
```
➜  fw apktool if 63.apk -t 1473
I: Framework installed to: /home/ibotpeaches/.local/share/apktool/framework/63-1473.apk
➜  fw apktool if 127.apk -t 1473
I: Framework installed to: /home/ibotpeaches/.local/share/apktool/framework/127-1473.apk
➜  fw cd ..
➜  Bug1473 apktool d 1.apk -t 1473
I: Using Apktool 2.2.3-74f76a-SNAPSHOT on 1.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1473 apktool b 1
I: Using Apktool 2.2.3-74f76a-SNAPSHOT
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
W: warning: string 'global_actions_screenshot_status' has no default translation.
W: warning: string 'reboot_confirm' has no default translation.
W: warning: string 'wfcSpnFormat' has no default translation.
I: Building apk file...
I: Copying unknown files/dir...
➜  Bug1473 
```

I didn't see a `Settings.apk` in the download. Just SystemUI and two framework files.

**Comment by Phone-Guru** [comment]
https://mega.nz/#!CNhhCR7Z

**Comment by iBotPeaches** [comment]
@Phone-Guru 

> Enter decryption key

for that download link :(

**Comment by Phone-Guru** [comment]
Didn't realise it was encrypted. Try this
https://mega.nz/#!CNhhCR7Z!I37SzqEs0Rcszp95GVkZBAqLNeM2Q4F00xSruNJwMZc

**Comment by iBotPeaches** [comment]
```
➜  Bug1473 apktool if 1.apk -t 1473
I: Framework installed to: /home/ibotpeaches/.local/share/apktool/framework/1-1473.apk
➜  Bug1473 apktool if 63.apk -t 1473
I: Framework installed to: /home/ibotpeaches/.local/share/apktool/framework/63-1473.apk
➜  Bug1473 apktool if 127.apk -t 1473
I: Framework installed to: /home/ibotpeaches/.local/share/apktool/framework/127-1473.apk
➜  Bug1473 apktool d Settings.apk -t 1473
I: Using Apktool 2.2.3-74f76a-SNAPSHOT on Settings.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1-1473.apk
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/63-1473.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1473 apktool b Settings
I: Using Apktool 2.2.3-74f76a-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: warning: string 'cmlicense_title' has no default translation.
W: warning: string 'cmupdate_settings_title' has no default translation.
W: warning: string 'crypt_keeper_change_password_summary' has no default translation.
W: warning: string 'crypt_keeper_change_password_title' has no default translation.
W: warning: string 'crypt_keeper_choose_your_password_header' has no default translation.
W: warning: string 'crypt_keeper_replace_password_summary' has no default translation.
W: warning: string 'crypt_keeper_replace_password_title' has no default translation.
W: warning: string 'heads_up_notifications_enabled_summary' has no default translation.
W: warning: string 'heads_up_notifications_enabled_title' has no default translation.
W: warning: string 'lockscreen_weather_enabled_title' has no default translation.
W: warning: string 'update_recovery_off_warning' has no default translation.
W: warning: string 'update_recovery_on_warning' has no default translation.
W: warning: string 'update_recovery_summary' has no default translation.
W: warning: string 'update_recovery_title' has no default translation.
I: Building apk file...
I: Copying unknown files/dir...
➜  Bug1473 
```

No problem at all here. Steps I took above.

**Comment by Phone-Guru** [comment]
What about the SystemUI.apk not recompiling?

**Comment by iBotPeaches** [comment]
I did not check that one. Re-opening.

**Comment by Phone-Guru** [comment]
I managed to get the Settings apk to recompile.  I don't understand why installing the frameworks through apktool works differently from simply placing them in the correct folder.  They end up in the same place.  Still not tried SystemUI.

**Comment by Phone-Guru** [comment]
SystemUI.apk works now too

**Comment by brmraju** [comment]
Unable to compile SystemUI using apktool 2.2.4 for LineageOS 14.1

I tried to compile as below:
----------------------------------------------------------------------------------------------

C:\Users\brmra\Desktop\System Files>java -jar apktool.jar b SystemUI -c

I: Using Apktool 2.2.4
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: C:\Users\brmra\Desktop\System Files\SystemUI\res\values\styles.xml:2143: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Animation.OptionsPanel'.
W:
W: C:\Users\brmra\Desktop\System Files\SystemUI\res\values\styles.xml:2144: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Animation.OptionsPanel'.
W:
W: C:\Users\brmra\Desktop\System Files\SystemUI\res\values\styles.xml:2149: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Animation.OptionsPanel'.
W:
W: C:\Users\brmra\Desktop\System Files\SystemUI\res\values\styles.xml:2159: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Animation.OptionsPanel'.
W:
W: C:\Users\brmra\Desktop\System Files\SystemUI\res\values\styles.xml:2262: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Widget.Material.Light.CompoundButton'.
W:
W: C:\Users\brmra\Desktop\System Files\SystemUI\res\values\styles.xml:2369: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Widget.Material.Light.CompoundButton'.
W:
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\brmra\AppData\Local\Temp\brut_util_Jar_1753715275400709341.tmp, p, --forced-package-id, 127, --min-sdk-version, 25, --target-sdk-version, 25, --version-code, 25, --version-name, 7.1.2, --no-version-vectors, -F, C:\Users\brmra\AppData\Local\Temp\APKTOOL7800045293833290918.tmp, -0, arsc, -0, arsc, -I, C:\Users\brmra\AppData\Local\apktool\framework\1.apk, -S, C:\Users\brmra\Desktop\System Files\SystemUI\res, -M, C:\Users\brmra\Desktop\System Files\SystemUI\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:496)
        at brut.androlib.Androlib.buildResources(Androlib.java:430)
        at brut.androlib.Androlib.build(Androlib.java:329)
        at brut.androlib.Androlib.build(Androlib.java:267)
        at brut.apktool.Main.cmdBuild(Main.java:230)
        at brut.apktool.Main.main(Main.java:83)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\brmra\AppData\Local\Temp\brut_util_Jar_1753715275400709341.tmp, p, --forced-package-id, 127, --min-sdk-version, 25, --target-sdk-version, 25, --version-code, 25, --version-name, 7.1.2, --no-version-vectors, -F, C:\Users\brmra\AppData\Local\Temp\APKTOOL7800045293833290918.tmp, -0, arsc, -0, arsc, -I, C:\Users\brmra\AppData\Local\apktool\framework\1.apk, -S, C:\Users\brmra\Desktop\System Files\SystemUI\res, -M, C:\Users\brmra\Desktop\System Files\SystemUI\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:441)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:482)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\brmra\AppData\Local\Temp\brut_util_Jar_1753715275400709341.tmp, p, --forced-package-id, 127, --min-sdk-version, 25, --target-sdk-version, 25, --version-code, 25, --version-name, 7.1.2, --no-version-vectors, -F, C:\Users\brmra\AppData\Local\Temp\APKTOOL7800045293833290918.tmp, -0, arsc, -0, arsc, -I, C:\Users\brmra\AppData\Local\apktool\framework\1.apk, -S, C:\Users\brmra\Desktop\System Files\SystemUI\res, -M, C:\Users\brmra\Desktop\System Files\SystemUI\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:435)
        ... 6 more

-------------------------------------------------------------------------------------------------------------------
