### ISSUE TITLE
Error occurred while disassembling class (long file name)

### ISSUE THREAD

**Issue by evildog1** [iBotPeaches/Apktool#1475]
### Information
1. **Apktool Version** 2.2.2
2. **Operating System** Windows
3. **APK From?** Playstore

### Stacktrace/Logcat

**Decompile**
```
I: Using Apktool 2.2.2 on GODDESS KISS_v1.025.12_apkpure.com.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...


Error occurred while disassembling class Landroid.support.annotation.8Tz5LA2k3tuqMOaR25BQAcjwwktSWC05W6zPbQ5eynl4VLDYe14qngr2B2UOpxjce0HSMkKcKpYlMHTOSeRILTbgpmfXL4jgAQDATuJjsaqdqmYi4nXQy7nYTkMp920bYq7qUUbNZCwFNs0KkqWxhyiZvvna6JwRtCFH06nbTJzcIfq7OIV5; - skipping class


Error occurred while disassembling class Landroid.support.TDwnsSw91wwhpxescCKCYel62fuIpMlm0wAl5peMLv2cP5AvZevUXccIOrbYnkhfC3OmPPxu34XIB19IRDxWSyQMdSU7KHsItSWnz6KvXBdyuOBJWaRNOlaHONwEKOOgS51oPQg9hr0AIPgWnd7XDfbFxhWhxMPUygGIW6hiKlDnjyO37Gsg; - skipping class
org.jf.util.ExceptionWithContext: The last instruction in the method is truncated
	at org.jf.dexlib2.dexbacked.DexBackedMethodImplementation$1$1.readNextItem(DexBackedMethodImplementation.java:87)
	at org.jf.dexlib2.dexbacked.DexBackedMethodImplementation$1$1.readNextItem(DexBackedMethodImplementation.java:75)
	at org.jf.dexlib2.dexbacked.util.VariableSizeLookaheadIterator.computeNext(VariableSizeLookaheadIterator.java:60)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:300)
	at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:691)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:275)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:226)
	at org.jf.baksmali.Adaptors.MethodDefinition.<init>(MethodDefinition.java:92)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeVirtualMethods(ClassDefinition.java:326)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:113)
	at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:225)
	at org.jf.baksmali.baksmali.access$000(baksmali.java:55)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:149)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:147)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
org.jf.util.ExceptionWithContext: The last instruction in the method is truncated
	at org.jf.dexlib2.dexbacked.DexBackedMethodImplementation$1$1.readNextItem(DexBackedMethodImplementation.java:87)
	at org.jf.dexlib2.dexbacked.DexBackedMethodImplementation$1$1.readNextItem(DexBackedMethodImplementation.java:75)
	at org.jf.dexlib2.dexbacked.util.VariableSizeLookaheadIterator.computeNext(VariableSizeLookaheadIterator.java:60)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:300)
	at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:691)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:275)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:226)
	at org.jf.baksmali.Adaptors.MethodDefinition.<init>(MethodDefinition.java:92)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeVirtualMethods(ClassDefinition.java:326)
	at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:113)
	at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:225)
	at org.jf.baksmali.baksmali.access$000(baksmali.java:55)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:149)
	at org.jf.baksmali.baksmali$1.call(baksmali.java:147)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Error while processing method Landroid/support/TDwnsSw91wwhpxescCKCYel62fuIpMlm0wAl5peMLv2cP5AvZevUXccIOrbYnkhfC3OmPPxu34XIB19IRDxWSyQMdSU7KHsItSWnz6KvXBdyuOBJWaRNOlaHONwEKOOgS51oPQg9hr0AIPgWnd7XDfbFxhWhxMPUygGIW6hiKlDnjyO37Gsg;->UcXci5T7cXfSno42QnXCWEPSNy3EwTTSaln2jSXG3kNDA4e8dBcxb183SvMP5oZi7d9vl1xsr7F9DceFgDpdzVgdpj88o1sqQUx6HIoY7wrlCvU8lcuwapJPlvoSBnhPZzhixkWxKzA5tk1Qom2nFb164s5Yf2d5PBjRGIeJbuLQORLcfcjT()Ljava/lang/String;

......
......

I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
```

The log is too long (2 MB >) so i can't post longer than that

**Compile**
```
I: Using Apktool 2.2.2
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
..\Decompiled APKs\GODDESS KISS_v1.025.12_apkpure.com\smali\android\support\v4\animation\TvczsLgJKZHK2vDjSDj1FbudxNJXlZXGTAiA002CHbZpq7PoBNJRhjBNB3F99KDokxsBV0EkBBjUVlMDPGaF23e68kXnReHJPWMn14u7gdCYk8OK70dr2i02vKJeVBVOTwyYnhw7vXVwvt8PWxR9iq2wSWh1XSLBUQqixFIXNV9mNbQVn7qe.smali[63,0] mismatched input '' expecting END_METHOD_DIRECTIVE
Exception in thread "main" brut.androlib.AndrolibException: Could not smali file: android/support/v4/animation/TvczsLgJKZHK2vDjSDj1FbudxNJXlZXGTAiA002CHbZpq7PoBNJRhjBNB3F99KDokxsBV0EkBBjUVlMDPGaF23e68kXnReHJPWMn14u7gdCYk8OK70dr2i02vKJeVBVOTwyYnhw7vXVwvt8PWxR9iq2wSWh1XSLBUQqixFIXNV9mNbQVn7qe.smali
	at brut.androlib.src.SmaliBuilder.buildFile(SmaliBuilder.java:75)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:59)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:36)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:404)
	at brut.androlib.Androlib.buildSources(Androlib.java:335)
	at brut.androlib.Androlib.build(Androlib.java:291)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:84)

```

### Steps to Reproduce
1. `apktool d -f -o <path> <path>`
2. `apktool b -o <path> <path>`

### APK
https://play.google.com/store/apps/details?id=com.flerogames.GK&hl=en

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes. I don't change anything
2. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
Yes the warnings are valid, but I think perfectly fine. You'll have to double check with https://github.com/JesusFreke/smali on that.

Using 2.2.3-dev

```
➜  Bug1475 apktool b com.flerogames.GK
I: Using Apktool 2.2.3-74f76a-SNAPSHOT
I: Smaling smali folder into classes.dex...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
➜  Bug1475 
```

Apktool 2.2.3 includes smali 2.2, which i s new. Confusing, I know. Our versions are eerily similar.

**Comment by evildog1** [comment]
I tried Jesus's smali 2.2.0 but still not working. I got a lot of error like this

`out\com\unity3d\player\w$2.smali[38,0] mismatched input '' expecting END_METHOD_DIRECTIVE`
