### ISSUE TITLE
I am trying inject payload into apk, I try manually and script and msfvenom but error occurred.Then i just decompile and recompile a apk and same error happen 

UPDATE: Solved by updating to 2.2.2 

### ISSUE THREAD

**Issue by netship01** [iBotPeaches/Apktool#1479]
Information
1. **Apktool Version (`apktool -version`)** -v2.2.1-dirty
2. **Operating System (Mac, Linux, Windows)** - Kali Linux latest Rolling with latest update
3. **APK From? (Playstore, ROM, Other)** - other

### Stacktrace/Logcat
root@GFreak:~# apktool b /root/Desktop/original
I: Using Apktool 2.2.1-dirty
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 139): [/usr/bin/aapt, p, --min-sdk-version, 8, --target-sdk-version, 17, --version-code, 309, --version-name, 3.09, -F, /tmp/APKTOOL515627416228292456.tmp, -0, html, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/Desktop/original/res, -M, /root/Desktop/original/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:478)
	at brut.androlib.Androlib.buildResources(Androlib.java:412)
	at brut.androlib.Androlib.build(Androlib.java:311)
	at brut.androlib.Androlib.build(Androlib.java:264)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 139): [/usr/bin/aapt, p, --min-sdk-version, 8, --target-sdk-version, 17, --version-code, 309, --version-name, 3.09, -F, /tmp/APKTOOL515627416228292456.tmp, -0, html, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/Desktop/original/res, -M, /root/Desktop/original/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:439)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:464)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 139): [/usr/bin/aapt, p, --min-sdk-version, 8, --target-sdk-version, 17, --version-code, 309, --version-name, 3.09, -F, /tmp/APKTOOL515627416228292456.tmp, -0, html, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/Desktop/original/res, -M, /root/Desktop/original/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:433)
	... 6 more

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool '
1-decomiple apk using ---  apktool d -o /root/Desktop/original /root/Desktop/a/Vidmate.apk
2-recompile using ---  apktool b /root/Desktop/original
 and then error occured
### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://vidmate-apk.com/download/Vidmate.apk
Every apk have this issue i try many like facebook lite etc all have same issue.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
    Yeah same error happen
2. If you are trying to install a modified apk, did you resign it?
  i can't even recompile.
3. Are you using the latest apktool version?
    yes

Solved

**Comment by teleworm1337x** [comment]
apk isnt working for some android applications !

**Comment by xpaceseven** [comment]
i'm also facing the same issue, [jiofi login](https://jiofilocalhtml.run) [https://forpc.onl](forpc)

**Comment by fizersur** [comment]
same issue and its still unresolved ! [vidmate 2014](https://get-vidmate.com/vidmate-2014/)  [instagram saver](https://instasave.onl/)

**Comment by iBotPeaches** [comment]
Locking this. Attracting spam comments from bots.
