### ISSUE TITLE
No resource found that matches ... "Animation.OptionsPanel" & "Animation.LockScreen"

### ISSUE THREAD

**Issue by 8bitp** [iBotPeaches/Apktool#1485]
### Information
1. **Apktool Version (`2.2.2`)** -
2. **Operating System (GNU/Linux Ubuntu 16.04)** -
3. **APK From? (https://www.whatsapp.com/android/)** -

### Stacktrace/Logcat

```
I: Using Apktool 2.2.2
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: /home/username/WhatsApp_2.17.144/res/values-v24/styles.xml:7: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Animation.OptionsPanel'.
W: 
W: /home/username/WhatsApp_2.17.144/res/values-v24/styles.xml:8: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Animation.LockScreen'.
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_4402206955110660676.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 25, --version-code, 451750, --version-name, 2.17.144, --no-version-vectors, -F, /tmp/APKTOOL2547811858099918364.tmp, -0, arsc, -0, arsc, -I, /home/username/.local/share/apktool/framework/1.apk, -S, /home/username/WhatsApp_2.17.144/res, -M, /home/username/WhatsApp_2.17.144/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:477)
	at brut.androlib.Androlib.buildResources(Androlib.java:411)
	at brut.androlib.Androlib.build(Androlib.java:310)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_4402206955110660676.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 25, --version-code, 451750, --version-name, 2.17.144, --no-version-vectors, -F, /tmp/APKTOOL2547811858099918364.tmp, -0, arsc, -0, arsc, -I, /home/username/.local/share/apktool/framework/1.apk, -S, /home/username/WhatsApp_2.17.144/res, -M, /home/username/WhatsApp_2.17.144/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:440)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:463)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_4402206955110660676.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 25, --version-code, 451750, --version-name, 2.17.144, --no-version-vectors, -F, /tmp/APKTOOL2547811858099918364.tmp, -0, arsc, -0, arsc, -I, /home/username/.local/share/apktool/framework/1.apk, -S, /home/username/WhatsApp_2.17.144/res, -M, /home/username/WhatsApp_2.17.144/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:434)
	... 6 more

```

### Steps to Reproduce
1. `apktool d WhatsApp_2.17.144.apk`
2. `apktool b WhatsApp_2.17.144`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://www.cdn.whatsapp.net/android/2.17.144/WhatsApp.apk

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? ---
3. Are you using the latest apktool version? yes

**Comment by iBotPeaches** [comment]
Could not duplicate.

```
➜  Bug1485 apktool d WhatsApp.apk 
I: Using Apktool 2.2.3-74f76a-SNAPSHOT on WhatsApp.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1485 apktool b WhatsApp
I: Using Apktool 2.2.3-74f76a-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
➜  Bug1485 
```

Try `apktool empty-framework-dir --force`

**Comment by pharazone** [comment]
same problem
