### ISSUE TITLE
I decompiled, change package name, recompile, sign. After installing,  "Unfortunately, app has stopped working".

### ISSUE THREAD

**Issue by uzairlodhi23** [iBotPeaches/Apktool#1487]
### Information
1. **Apktool Version (`apktool -version`)** -2.2.2
2. **Operating System (Mac, Linux, Windows)** -Windows
3. **APK From? (Playstore, ROM, Other)** -Playstore

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes.
2. If you are trying to install a modified apk, did you resign it? Yes.
3. Are you using the latest apktool version? Yes.

**Comment by iBotPeaches** [comment]
The real error is hidden in the logcat. During this "Unforunately, app has stopped working" message make sure you have `adb logcat` running and get the real error then. 

The error you have is generic and nothing I can do about that without more details.

**Comment by uzairlodhi23** [comment]
Exception in thread "main" Can't construct a java object for tag:yaml.org,2002:brut.androlib.meta.MetaInfo; exception=Class not found: brut.androlib.meta.MetaInfo
 in 'reader', line 1, column 1:
    !!brut.androlib.meta.MetaInfo
    ^
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:333)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:481)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:412)
	at brut.androlib.Androlib.readMetaFile(Androlib.java:254)
	at brut.androlib.Androlib.build(Androlib.java:268)
	at brut.androlib.Androlib.build(Androlib.java:261)
	at brut.apktool.Main.cmdBuild(Main.java:225)
	at brut.apktool.Main.main(Main.java:84)
Caused by: org.yaml.snakeyaml.error.YAMLException: Class not found: brut.androlib.meta.MetaInfo
	at org.yaml.snakeyaml.constructor.Constructor.getClassForNode(Constructor.java:633)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.getConstructor(Constructor.java:321)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:331)
	... 10 more
Process exited with code 1

**Comment by iBotPeaches** [comment]
Interesting. This error is during the rebuild of the application. I thought you mentioned it was successfully built and then installed on host device?

**Comment by uzairlodhi23** [comment]
i have done same process again and now it is giving this error during building process

**Comment by iBotPeaches** [comment]
Okay, that error in above stack trace I've never seen before. Its almost like the the `apktool.yml` file has been modified and broken.

**Comment by iBotPeaches** [comment]
The original error had no logcat attached, on further inspection an error was posted that means a manual modification to `apktool.yml` was made and/or invalid apktool binary was used. Closing this due to 1+ month passing. Feel free to add those missing details and I can revisit.
