### ISSUE TITLE
Error: input directory 'conf' does not exit

### ISSUE THREAD

**Issue by JDEast1029** [iBotPeaches/Apktool#1494]
```
F:\apkTest\test1>apktool b com.tencent.mm_6.5.7_1041
I: Using Apktool 2.0.3
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether resources has changed...
I: Building resources...
ERROR: input directory 'conf' does not exist
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.Androl
ibException: brut.common.BrutException: could not exec command: [C:\Users\ADMINI
~1\AppData\Local\Temp\brut_util_Jar_293576378916421636.tmp, p, --forced-package-
id, 127, --min-sdk-version, 16, --target-sdk-version, 23, --version-code, 1041,
--version-name, 6.5.7, -F, C:\Users\ADMINI~1\AppData\Local\Temp\APKTOOL191826380
0577403751.tmp, -0, arsc, -0, zip, -0, sec, -0, , -0, conf, -0, dat, -0, txt, -0
, data, -0, spx, -0, arsc, -I, C:\Users\Administrator\apktool\framework\1.apk, -
S, F:\apkTest\test1\com.tencent.mm_6.5.7_1041\res, -M, F:\apkTest\test1\com.tenc
ent.mm_6.5.7_1041\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:472)
        at brut.androlib.Androlib.buildResources(Androlib.java:410)
        at brut.androlib.Androlib.build(Androlib.java:298)
        at brut.androlib.Androlib.build(Androlib.java:268)
        at brut.apktool.Main.cmdBuild(Main.java:225)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not
 exec command: [C:\Users\ADMINI~1\AppData\Local\Temp\brut_util_Jar_2935763789164
21636.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-vers
ion, 23, --version-code, 1041, --version-name, 6.5.7, -F, C:\Users\ADMINI~1\AppD
ata\Local\Temp\APKTOOL1918263800577403751.tmp, -0, arsc, -0, zip, -0, sec, -0, ,
 -0, conf, -0, dat, -0, txt, -0, data, -0, spx, -0, arsc, -I, C:\Users\Administr
ator\apktool\framework\1.apk, -S, F:\apkTest\test1\com.tencent.mm_6.5.7_1041\res
, -M, F:\apkTest\test1\com.tencent.mm_6.5.7_1041\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.jav
a:425)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:458)
        ... 5 more
Caused by: brut.common.BrutException: could not exec command: [C:\Users\ADMINI~1
\AppData\Local\Temp\brut_util_Jar_293576378916421636.tmp, p, --forced-package-id
, 127, --min-sdk-version, 16, --target-sdk-version, 23, --version-code, 1041, --
version-name, 6.5.7, -F, C:\Users\ADMINI~1\AppData\Local\Temp\APKTOOL19182638005
77403751.tmp, -0, arsc, -0, zip, -0, sec, -0, , -0, conf, -0, dat, -0, txt, -0,
data, -0, spx, -0, arsc, -I, C:\Users\Administrator\apktool\framework\1.apk, -S,
 F:\apkTest\test1\com.tencent.mm_6.5.7_1041\res, -M, F:\apkTest\test1\com.tencen
t.mm_6.5.7_1041\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:89)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.jav
a:419)
        ... 6 more
```

**Comment by iBotPeaches** [comment]
This issue was fixed in 2.1.0 here - https://github.com/iBotPeaches/Apktool/issues/1122

Please upgrade.
