### ISSUE TITLE
Error: No resource found that matches the given name (at 'style' with value ).

### ISSUE THREAD

**Issue by JDEast1029** [iBotPeaches/Apktool#1499]
### Information
1. **Apktool Version (`apktool_2.2.2`)** -
2. **Operating System (Windows)** -
3. **APK From? (Playstore)** -

### Stacktrace/Logcat

```
W:
W: F:\apkTest\test9-apktool_2.2.2\com.tencent.mm_6.5.7_1041\res\layout\yz.xml:10
: error: Error: No resource found that matches the given name (at 'style' with v
alue '@style/mass_send_divide_line').
W:
W: F:\apkTest\test9-apktool_2.2.2\com.tencent.mm_6.5.7_1041\res\layout\yz.xml:11
: error: Error: No resource found that matches the given name (at 'style' with v
alue '@style/mass_send_again_btn').
W:
W: F:\apkTest\test9-apktool_2.2.2\com.tencent.mm_6.5.7_1041\res\layout\z0.xml:4:
 error: Error: No resource found that matches the given name (at 'style' with va
lue '@style/mass_send_time').
W:
W: F:\apkTest\test9-apktool_2.2.2\com.tencent.mm_6.5.7_1041\res\layout\z0.xml:6:
 error: Error: No resource found that matches the given name (at 'style' with va
lue '@style/mass_send_contact').
W: F:\apkTest\test9-apktool_2.2.2\com.tencent.mm_6.5.7_1041\res\xml\e.xml:5: err
or: No resource identifier found for attribute 'can_delete' in package 'com.tenc
ent.mm'
W:
W: F:\apkTest\test9-apktool_2.2.2\com.tencent.mm_6.5.7_1041\res\xml\e.xml:5: err
or: No resource identifier found for attribute 'empty_wording' in package 'com.t
encent.mm'
W:
W: F:\apkTest\test9-apktool_2.2.2\com.tencent.mm_6.5.7_1041\res\xml\e.xml:8: err
or: No resource identifier found for attribute 'btn_visibility' in package 'com.
tencent.mm'
W:
W: F:\apkTest\test9-apktool_2.2.2\com.tencent.mm_6.5.7_1041\res\xml\e.xml:8: err
or: No resource identifier found for attribute 'empty_wording' in package 'com.t
encent.mm'
W:
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.Androl
ibException: brut.common.BrutException: could not exec (exit code = 1): [C:\User
s\ADMINI~1\AppData\Local\Temp\brut_util_Jar_7330349609201051751.tmp, p, --forced
-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 23, --version-cod
e, 1041, --version-name, 6.5.7, --no-version-vectors, -F, C:\Users\ADMINI~1\AppD
ata\Local\Temp\APKTOOL4561769053342661392.tmp, -0, arsc, -0, zip, -0, sec, -0, a
ssets/color_emoji, -0, conf, -0, dat, -0, txt, -0, data, -0, spx, -0, svg, -0, a
pk, -0, arsc, -I, C:\Users\Administrator\AppData\Local\apktool\framework\1.apk,
-S, F:\apkTest\test9-apktool_2.2.2\com.tencent.mm_6.5.7_1041\res, -M, F:\apkTest
\test9-apktool_2.2.2\com.tencent.mm_6.5.7_1041\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:477)
        at brut.androlib.Androlib.buildResources(Androlib.java:411)
        at brut.androlib.Androlib.build(Androlib.java:310)
        at brut.androlib.Androlib.build(Androlib.java:263)
        at brut.apktool.Main.cmdBuild(Main.java:227)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not
 exec (exit code = 1): [C:\Users\ADMINI~1\AppData\Local\Temp\brut_util_Jar_73303
49609201051751.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target
-sdk-version, 23, --version-code, 1041, --version-name, 6.5.7, --no-version-vect
ors, -F, C:\Users\ADMINI~1\AppData\Local\Temp\APKTOOL4561769053342661392.tmp, -0
, arsc, -0, zip, -0, sec, -0, assets/color_emoji, -0, conf, -0, dat, -0, txt, -0
, data, -0, spx, -0, svg, -0, apk, -0, arsc, -I, C:\Users\Administrator\AppData\
Local\apktool\framework\1.apk, -S, F:\apkTest\test9-apktool_2.2.2\com.tencent.mm
_6.5.7_1041\res, -M, F:\apkTest\test9-apktool_2.2.2\com.tencent.mm_6.5.7_1041\An
droidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.jav
a:440)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:463)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\
ADMINI~1\AppData\Local\Temp\brut_util_Jar_7330349609201051751.tmp, p, --forced-p
ackage-id, 127, --min-sdk-version, 16, --target-sdk-version, 23, --version-code,
 1041, --version-name, 6.5.7, --no-version-vectors, -F, C:\Users\ADMINI~1\AppDat
a\Local\Temp\APKTOOL4561769053342661392.tmp, -0, arsc, -0, zip, -0, sec, -0, ass
ets/color_emoji, -0, conf, -0, dat, -0, txt, -0, data, -0, spx, -0, svg, -0, apk
, -0, arsc, -I, C:\Users\Administrator\AppData\Local\apktool\framework\1.apk, -S
, F:\apkTest\test9-apktool_2.2.2\com.tencent.mm_6.5.7_1041\res, -M, F:\apkTest\t
est9-apktool_2.2.2\com.tencent.mm_6.5.7_1041\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.jav
a:434)
        ... 6 more

```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? 
3. Are you using the latest apktool version? yes

**Comment by iBotPeaches** [comment]
Tencent again? What does this application do. This is the 5th or 6th different bug report about this application. Where can I get this version of Tencent?

**Comment by JDEast1029** [comment]
APK can be downloaded here: http://123.155.153.145/imtt.dd.qq.com/16891/A57EB927AA21AB73D521BE20DD0BF61B.apk?mkey=591395060d248689&f=9610&c=0&fsname=com.tencent.mm_6.5.7_1041.apk&csr=1bbd&p=.apk

**Comment by iBotPeaches** [comment]
Tencent being collected here - https://github.com/iBotPeaches/Apktool/issues/1423

Marking as duplicate.
