### ISSUE TITLE
Unable to decompile APK using Apktool 2.2.3-ea16f3-SNAPSHOT

### ISSUE THREAD

**Issue by rdtq** [iBotPeaches/Apktool#1500]
### Information
1. **Apktool Version (`apktool -version`)** -  2.2.3-ea16f3-SNAPSHOT
2. **Operating System (Mac, Linux, Windows)** - Ubuntu 16.04
3. **APK From? (Playstore, ROM, Other)** - https://play.google.com/store/apps/details?id=ru.mw&hl=en

### Stacktrace/Logcat

```
I: Using Apktool 2.2.3-ea16f3-SNAPSHOT on ru.mw-1.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Multiple resources: spec=0x7f0a0000 string/APKTOOL_DUMMYVAL_0x7f0a0000, config=-sr
	at brut.androlib.res.data.ResType.addResource(ResType.java:66)
	at brut.androlib.res.data.ResType.addResource(ResType.java:55)
	at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:270)
	at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:226)
	at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:156)
	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:118)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:80)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:562)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:72)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:64)
	at brut.androlib.Androlib.getResTable(Androlib.java:67)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:207)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:109)
	at brut.apktool.Main.cmdDecode(Main.java:166)
	at brut.apktool.Main.main(Main.java:81)

```

### Steps to Reproduce
1. `apktool d ru.mw-1.apk`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

APK can be downloaded here: https://play.google.com/store/apps/details?id=ru.mw&hl=en

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

Yes. I have tried  2.2.3-ea16f3-SNAPSHOT and 2.2.2 - looks like it won't decompile in either of them.

**Comment by rdtq** [comment]
Here is the stacktrace with version 2.2.2 - essentially the same.
```
I: Using Apktool 2.2.2 on ru.mw-1.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Multiple resources: spec=0x7f0a0000 string/APKTOOL_DUMMYVAL_0x7f0a0000, config=-sr
	at brut.androlib.res.data.ResType.addResource(ResType.java:66)
	at brut.androlib.res.data.ResType.addResource(ResType.java:55)
	at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:270)
	at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:226)
	at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:156)
	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:118)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:80)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:559)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:72)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:64)
	at brut.androlib.Androlib.getResTable(Androlib.java:67)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:193)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
	at brut.apktool.Main.cmdDecode(Main.java:166)
	at brut.apktool.Main.main(Main.java:81)
```

**Comment by iBotPeaches** [comment]
Might be qualifier related. I'll take a look when I get home, thanks for following issue template. If you are interested in accelerating my research.

Do `aapt d configurations ru.mw-1.apk` and dump the output here otherwise I'll take care of it when I grab some free time.

**Comment by rdtq** [comment]
Sure thing.
```
rdtq@pc:~$ aapt d configurations ru.mw-1.apk

anydpi-v21
nodpi-v4
xlarge-v4
xlarge-v11
sw600dp-v13
v21
v23
small-land-v4
normal-land-v4
ldpi-v4
mdpi-v4
large-mdpi-v4
ldrtl-mdpi-v17
tvdpi-v4
hdpi-v4
sw600dp-hdpi-v13
ldrtl-hdpi-v17
hdpi-v21
xhdpi-v4
ldrtl-xhdpi-v17
xhdpi-v21
xxhdpi-v4
sw600dp-xxhdpi-v13
ldrtl-xxhdpi-v17
xxxhdpi-v4
sw600dp-xxxhdpi-v13
ldrtl-xxxhdpi-v17
xxxhdpi-v21
v11
w400dp-v13
xlarge-v14
v16
sw600dp-v16
v17
sw600dp-v21
v22
small-port-v4
large-port-v4
xlarge-port-v14
small-port-v16
land
large-land-v4
land-v16
land-v17
xlarge-mdpi-v11
large-mdpi-v14
v19
ru
ca
da
fa
ja
ka
pa
ta
nb
be
de
ne
te
af
bg
th
fi
hi
si
vi
kk
mk
sk
uk
el
gl
ml
nl
pl
sl
tl
am
km
rm
bn
en
in
kn
mn
ko
lo
no
ro
sq
ar
fr
hr
mr
sr
tr
ur
bs
cs
es
is
ms
et
it
lt
pt
eu
gu
hu
zu
lv
sv
iw
sw
hy
ky
my
az
uz
bs-rBA
en-rCA
fr-rCA
lo-rLA
uk-rUA
en-rZA
en-rGB
bn-rBD
in-rID
et-rEE
ka-rGE
en-rIE
ar-rEG
ky-rKG
km-rKH
th-rTH
fi-rFI
sl-rSI
zh-rHK
si-rLK
mk-rMK
ur-rPK
sk-rSK
sq-rAL
hy-rAM
my-rMM
zh-rCN
pa-rIN
ta-rIN
te-rIN
hi-rIN
ml-rIN
en-rIN
kn-rIN
mr-rIN
gu-rIN
mn-rMN
vi-rVN
ro-rRO
ne-rNP
pt-rBR
hr-rHR
gl-rES
eu-rES
is-rIS
sr-rRS
en-rUS
es-rUS
lt-rLT
pt-rPT
en-rAU
hu-rHU
lv-rLV
zh-rTW
be-rBY
ms-rMY
az-rAZ
kk-rKZ
en-rNZ
uz-rUZ
large-v4
w820dp-v13
h720dp-v13
sw330dp-v13
sw480dp-v13
v18
sw600dp-port-v13
sw600dp-land-v13
large-port-mdpi-v4
xlarge-port-mdpi-v4
sw720dp-port-v13
night-v8
v12
v14
ldltr-v21
v24
v25
large-mdpi-v16
large-mdpi-v21
v13
port
```

**Comment by rdtq** [comment]
In case it might help, this is how it looks when I just unzip that APK:
![screenshot from 2017-05-10 19-15-06](https://cloud.githubusercontent.com/assets/22523840/25909185/04674dbe-35b5-11e7-80d5-1d6dcec7e066.png)


And this is how MANIFEST.MF (unzipped) looks:
![screenshot from 2017-05-10 19-09-29](https://cloud.githubusercontent.com/assets/22523840/25909060/a6cbd2ce-35b4-11e7-9e21-275202470ca3.png)

They are doing something funny with the names.

**Comment by quyeticb** [comment]
Has anyone solved this problem yet?

**Comment by iBotPeaches** [comment]
@quyeticb This issue isn't even 24 hours. Its more than likely dexguard or dexprotector

**Comment by iBotPeaches** [comment]
This is an enhanced Dexguard trick after taking a look this morning. I already have a bug tracking this change at #1320 , closing as duplicate.
