### ISSUE TITLE
Can not rebuild with roundIcon

### ISSUE THREAD

**Issue by mkadono1** [iBotPeaches/Apktool#1503]
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.2
2. **Operating System (Mac, Linux, Windows)** - Mac
3. **APK From? (Playstore, ROM, Other)** - Internal

### Stacktrace/Logcat

```
I: Using Apktool 2.2.2
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: /Users/sampleuser1/Downloads/android_sdk-master/tools/app-debug/AndroidManifest.xml:4: error: No resource identifier found for attribute 'roundIcon' in package 'android'
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/n4/4hqvhcc14jn9bpdjvdjd5rw40000gr/T/brut_util_Jar_8054352204109204110.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 25, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /var/folders/n4/4hqvhcc14jn9bpdjvdjd5rw40000gr/T/APKTOOL8152626282685287010.tmp, -0, arsc, -0, arsc, -I, /Users/sampleuser1/Library/apktool/framework/1.apk, -S, /Users/sampleuser1/Downloads/android_sdk-master/tools/app-debug/res, -M, /Users/sampleuser1/Downloads/android_sdk-master/tools/app-debug/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:477)
	at brut.androlib.Androlib.buildResources(Androlib.java:411)
	at brut.androlib.Androlib.build(Androlib.java:310)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/n4/4hqvhcc14jn9bpdjvdjd5rw40000gr/T/brut_util_Jar_8054352204109204110.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 25, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /var/folders/n4/4hqvhcc14jn9bpdjvdjd5rw40000gr/T/APKTOOL8152626282685287010.tmp, -0, arsc, -0, arsc, -I, /Users/sampleuser1/Library/apktool/framework/1.apk, -S, /Users/sampleuser1/Downloads/android_sdk-master/tools/app-debug/res, -M, /Users/sampleuser1/Downloads/android_sdk-master/tools/app-debug/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:440)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:463)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/n4/4hqvhcc14jn9bpdjvdjd5rw40000gr/T/brut_util_Jar_8054352204109204110.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 25, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /var/folders/n4/4hqvhcc14jn9bpdjvdjd5rw40000gr/T/APKTOOL8152626282685287010.tmp, -0, arsc, -0, arsc, -I, /Users/sampleuser1/Library/apktool/framework/1.apk, -S, /Users/sampleuser1/Downloads/android_sdk-master/tools/app-debug/res, -M, /Users/sampleuser1/Downloads/android_sdk-master/tools/app-debug/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:434)
	... 6 more
```

### Steps to Reproduce
1. apktool d app-debug.apk
2. apktool b app-debug

### Questions to ask before submission
Hello, I use latest apkTool (v2.2.2) to decompile and rebuild. but an error occurs and it fails to rebuild.
The word "roundIcon" is found, I think this probably occurs this error.
I try to operate an apk which is built by a simple project with roundIcon, as I expected, the same error occurs.
Additionally, I also try to the same apk except removing roundIcon, this error does not occur and it suceeds to rebuild.
How can I rebuild with roundIcon?

Thank you for your attention.

**Comment by iBotPeaches** [comment]
Sounds like a framework problem, try running `apktool empty-framework-dir --force` and try again. This resource was added in 7.1 - https://developer.android.com/about/versions/nougat/android-7.1.html#circular-icons

Which is in 2.2.2

**Comment by mkadono1** [comment]
I'm sorry to be late. 
After running "apktool empty-framework-dir --force", the rebuild is success.
Thank you.
