### ISSUE TITLE
 apk tool cant recompile the unchanged decompiled apk

### ISSUE THREAD

**Issue by reverser69** [iBotPeaches/Apktool#1510]
hi

i decompile the apk then i try to build it again without any changes but apktool returns error
```
D:\PROGRAM\crack tool\APK\ApkTool>apktool d C:\Users\XXXX\Desktop\X.apk
I: Using Apktool 2.0.3 on X.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\XXXX\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

D:\PROGRAM\crack tool\APK\ApkTool>apktool b "D:\PROGRAM\crack tool\APK\ApkTool\X"
I: Using Apktool 2.0.3
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
Failed to generate resource table for split ''
D:\PROGRAM\crack tool\APK\ApkTool\X\res\values\styles.xml:16: error: Error: Resource is not public. (at 'bottomBarBackground' with value '@android:drawable/ab_bottom_solid_light_holo').

Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\Users\XXXX\AppData\Local\Temp\brut_util_Jar_6811329636660105694.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 19, --version-code, 190012, --version-name, 1.6.5, -F, C:\Users\XXXX\AppData\Local\Temp\APKTOOL6484213971148074400.tmp, -0, arsc, -0, arsc, -I, C:\Users\XXXX\apktool\framework\1.apk, -S, D:\PROGRAM\crack tool\APK\ApkTool\X\res, -M, D:\PROGRAM\crack tool\APK\ApkTool\X\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:472)
        at brut.androlib.Androlib.buildResources(Androlib.java:410)
        at brut.androlib.Androlib.build(Androlib.java:298)
        at brut.androlib.Androlib.build(Androlib.java:268)
        at brut.apktool.Main.cmdBuild(Main.java:225)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\Users\XXXX\AppData\Local\Temp\brut_util_Jar_6811329636660105694.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 19, --version-code, 190012, --version-name, 1.6.5, -F, C:\Users\XXXX\AppData\Local\Temp\APKTOOL6484213971148074400.tmp, -0, arsc, -0, arsc, -I, C:\Users\XXXX\apktool\framework\1.apk, -S, D:\PROGRAM\crack tool\APK\ApkTool\X\res, -M, D:\PROGRAM\crack tool\APK\ApkTool\X\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:425)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:458)
        ... 5 more
Caused by: brut.common.BrutException: could not exec command: [C:\Users\XXXX\AppData\Local\Temp\brut_util_Jar_6811329636660105694.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 19, --version-code, 190012, --version-name, 1.6.5, -F, C:\Users\XXXX\AppData\Local\Temp\APKTOOL6484213971148074400.tmp, -0, arsc, -0, arsc, -I, C:\Users\XXXX\apktool\framework\1.apk, -S, D:\PROGRAM\crack tool\APK\ApkTool\X\res, -M, D:\PROGRAM\crack tool\APK\ApkTool\X\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:89)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)
        ... 6 more
```
 

tried  apktool d -f -r
```
D:\PROGRAM\crack tool\APK\ApkTool>apktool d -f -r C:\Users\XXXX\Desktop\X.apk
I: Using Apktool 2.0.3 on X.apk
I: Copying raw resources...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

D:\PROGRAM\crack tool\APK\ApkTool>apktool b "D:\PROGRAM\crack tool\APK\ApkTool\X"
I: Using Apktool 2.0.3
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
[Fatal Error] AndroidManifest.xml:1:1: Content is not allowed in prolog.
I: Checking whether resources has changed...
I: Copying raw resources...
I: Copying libs... (/lib)
I: Building apk file...
```
and cant install apk file.

**Comment by reverser69** [comment]
i searched here and found out that it is caused by protectors.can you give me lead on it ?
i just want to edit a smali file.isnt there a way just decoding dex file, editing smali and replace the dex of original apk?!

**Comment by CunningLogic** [comment]
you could, you know, just use baksmali?

**Comment by reverser69** [comment]
So the protection is just fir resources?
Can you refer me to a tutorian on how to use baksmali and its commands?
Am i to extract the dex and decompile it edit it then replace it within APK?

**Comment by CunningLogic** [comment]
Rtfm

**Comment by reverser69** [comment]
Im really curiuos about how it is caused and how can one fix it.what protector is involved?

**Comment by iBotPeaches** [comment]
Plenty of resources out there for you on the web. There isn't a bug in apktool in this, so closing this.
