### ISSUE TITLE
AndrolibException exception during repackaging

### ISSUE THREAD

**Issue by pilgun** [iBotPeaches/Apktool#1513]
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.2
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - F-Droid

### Stacktrace/Logcat

```
C:\projects\android\apktool>java -jar apktool_2.2.2.jar decode --no-src -o output apps\com.fastaccess.github_210.apk
I: Using Apktool 2.2.2 on com.fastaccess.github_210.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\aleksandr.pilgun\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying raw classes.dex file...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

C:\projects\android\apktool>java -jar apktool_2.2.2.jar build output
I: Using Apktool 2.2.2
I: Copying output classes.dex file...
I: Checking whether resources has changed...
I: Building resources...
W: warning: string 'auto_theme_mode' has no default translation.
W: warning: string 'on' has no default translation.
Exception in thread "main" W: warning: string 'write' has no default translation.
brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\ALEKSA~1.PIL\AppData\Local\Temp\brut_util_Jar_462710430117626561.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 25, --version-code, 210, --version-name, 2.1.0, --no-version-vectors, -F, C:\Users\ALEKSA~1.PIL\AppData\Local\Temp\APKTOOL4628354964258982504.tmp, -0, arsc, -0, arsc, -I, C:\Users\aleksandr.pilgun\AppData\Local\apktool\framework\1.apk, -S, C:\projects\android\apktool\output\res, -M, C:\projects\android\apktool\output\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:477)
        at brut.androlib.Androlib.buildResources(Androlib.java:411)
        at brut.androlib.Androlib.build(Androlib.java:310)
        at brut.androlib.Androlib.build(Androlib.java:263)
        at brut.apktool.Main.cmdBuild(Main.java:227)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\ALEKSA~1.PIL\AppData\Local\Temp\brut_util_Jar_462710430117626561.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 25, --version-code, 210, --version-name, 2.1.0, --no-version-vectors, -F, C:\Users\ALEKSA~1.PIL\AppData\Local\Temp\APKTOOL4628354964258982504.tmp, -0, arsc, -0, arsc, -I, C:\Users\aleksandr.pilgun\AppData\Local\apktool\framework\1.apk, -S, C:\projects\android\apktool\output\res, -M, C:\projects\android\apktool\output\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:440)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:463)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\ALEKSA~1.PIL\AppData\Local\Temp\brut_util_Jar_462710430117626561.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 25, --version-code, 210, --version-name, 2.1.0, --no-version-vectors, -F, C:\Users\ALEKSA~1.PIL\AppData\Local\Temp\APKTOOL4628354964258982504.tmp, -0, arsc, -0, arsc, -I, C:\Users\aleksandr.pilgun\AppData\Local\apktool\framework\1.apk, -S, C:\projects\android\apktool\output\res, -M, C:\projects\android\apktool\output\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:434)
        ... 6 more
W: C:\projects\android\apktool\output\AndroidManifest.xml:8: error: No resource identifier found for attribute 'roundIcon' in package 'android'
W:
```

### Steps to Reproduce
Just rebuild this APK without changing and without disassembling (--no-src)
1. `java -jar apktool_2.2.2.jar decode --no-src -o output apps\com.fastaccess.github_210.apk`
2. `java -jar apktool_2.2.2.jar build output`

### Frameworks
no frameworks

### APK
[com.fastaccess.github APK from F-Droid](https://f-droid.org/repo/com.fastaccess.github_210.apk)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? - Yes.
2. If you are trying to install a modified apk, did you resign it? - This is repackage-time crash.
3. Are you using the latest apktool version? - Yes.

**Comment by iBotPeaches** [comment]
```
➜  Bug1513 apktool d --no-src com.fastaccess.github_210.apk 
I: Using Apktool 2.2.3-0e6eaf-SNAPSHOT on com.fastaccess.github_210.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying raw classes.dex file...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1513 apktool b com.fastaccess.github_210
I: Using Apktool 2.2.3-0e6eaf-SNAPSHOT
I: Copying com.fastaccess.github_210 classes.dex file...
I: Checking whether resources has changed...
I: Building resources...
W: warning: string 'auto_theme_mode' has no default translation.
W: warning: string 'on' has no default translation.
W: warning: string 'write' has no default translation.
I: Building apk file...
I: Copying unknown files/dir...
➜  Bug1513 
```

Looks like you might have an out of date framework. Try `apktool empty-framework-dir --force`, then retry that command.
