### ISSUE TITLE
unable to recompile SystemUI.apk from Resurrection Remix 5.8.3 for Xiaomi Mi Mix

### ISSUE THREAD

**Issue by mcn1970** [iBotPeaches/Apktool#1517]
### Information
1. **Apktool Version (`apktool -version`)** -2.2.2
2. **Operating System (Mac, Linux, Windows)** -W10
3. **APK From? (Playstore, ROM, Other)** -systemui.apk from Resurrection Remix 5.8.3 7.1.2 Nougat

### Stacktrace/Logcat
```
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\WINDOWS\system32> cd..
PS C:\WINDOWS> cd..
PS C:\> cd users
PS C:\users> cd mcn19
PS C:\users\mcn19> .\apktool d systemui.apk
I: Using Apktool 2.2.2 on systemui.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\mcn19\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
PS C:\users\mcn19> .\apktool b systemui
I: Using Apktool 2.2.2
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: C:\users\mcn19\systemui\res\values\styles.xml:2150: error: Error retrieving parent for item: No resource found that m
atches the given name '@android:style/Widget.WebTextView'.
W:
W: C:\users\mcn19\systemui\res\values\styles.xml:2173: error: Error retrieving parent for item: No resource found that m
atches the given name '@android:style/Widget.GenericQuickContactBadge'.
W:
W: C:\users\mcn19\systemui\res\values\styles.xml:2219: error: Error: No resource found that matches the given name: attr
 'android:buttonPanelSideLayout'.
W:
W: C:\users\mcn19\systemui\res\values\styles.xml:2240: error: Error retrieving parent for item: No resource found that m
atches the given name '@android:style/Widget.WebTextView'.
W:
W: C:\users\mcn19\systemui\res\values\styles.xml:2241: error: Error retrieving parent for item: No resource found that m
atches the given name '@android:style/Widget.WebTextView'.
W:
W: C:\users\mcn19\systemui\res\values\styles.xml:2246: error: Error retrieving parent for item: No resource found that m
atches the given name '@android:style/Widget.WebTextView'.
W:
W: C:\users\mcn19\systemui\res\values\styles.xml:2255: error: Error retrieving parent for item: No resource found that m
atches the given name '@android:style/Widget.WebTextView'.
W:
W: C:\users\mcn19\systemui\res\values\styles.xml:2358: error: Error retrieving parent for item: No resource found that m
atches the given name '@android:style/Theme.Leanback.Settings.Dialog'.
W:
W: C:\users\mcn19\systemui\res\values\styles.xml:2465: error: Error retrieving parent for item: No resource found that m
atches the given name '@android:style/Theme.Leanback.Settings.Dialog'.
W:
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException:
could not exec (exit code = 1): [C:\Users\mcn19\AppData\Local\Temp\brut_util_Jar_3488190005384795187.tmp, p, --forced-pa
ckage-id, 127, --min-sdk-version, 25, --target-sdk-version, 25, --version-code, 25, --version-name, 7.1.2, --no-version-
vectors, -F, C:\Users\mcn19\AppData\Local\Temp\APKTOOL1773825033644329577.tmp, -0, arsc, -0, res/drawable-nodpi-v4/textu
re6_alpha1, -0, res/drawable-nodpi-v4/texture_alpha, -0, arsc, -I, C:\Users\mcn19\AppData\Local\apktool\framework\1.apk,
 -S, C:\users\mcn19\systemui\res, -M, C:\users\mcn19\systemui\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:477)
        at brut.androlib.Androlib.buildResources(Androlib.java:411)
        at brut.androlib.Androlib.build(Androlib.java:310)
        at brut.androlib.Androlib.build(Androlib.java:263)
        at brut.apktool.Main.cmdBuild(Main.java:227)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\mcn19\A
ppData\Local\Temp\brut_util_Jar_3488190005384795187.tmp, p, --forced-package-id, 127, --min-sdk-version, 25, --target-sd
k-version, 25, --version-code, 25, --version-name, 7.1.2, --no-version-vectors, -F, C:\Users\mcn19\AppData\Local\Temp\AP
KTOOL1773825033644329577.tmp, -0, arsc, -0, res/drawable-nodpi-v4/texture6_alpha1, -0, res/drawable-nodpi-v4/texture_alp
ha, -0, arsc, -I, C:\Users\mcn19\AppData\Local\apktool\framework\1.apk, -S, C:\users\mcn19\systemui\res, -M, C:\users\mc
n19\systemui\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:440)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:463)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\mcn19\AppData\Local\Temp\brut_util_Jar_3
488190005384795187.tmp, p, --forced-package-id, 127, --min-sdk-version, 25, --target-sdk-version, 25, --version-code, 25
, --version-name, 7.1.2, --no-version-vectors, -F, C:\Users\mcn19\AppData\Local\Temp\APKTOOL1773825033644329577.tmp, -0,
 arsc, -0, res/drawable-nodpi-v4/texture6_alpha1, -0, res/drawable-nodpi-v4/texture_alpha, -0, arsc, -I, C:\Users\mcn19\
AppData\Local\apktool\framework\1.apk, -S, C:\users\mcn19\systemui\res, -M, C:\users\mcn19\systemui\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:434)
        ... 6 more
PS C:\users\mcn19>
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?yes
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?yes

**Comment by iBotPeaches** [comment]
Hey, officially I took a stance to not support Huawei and Xiaomi as their qualifier changes conflict with future AOSP updates making changes to apktool decoder impossible, as that would break on future AOSP releases.

I'm tempted to close this because Xiaomi Mi Mix, but please upload frameworks and apk and let me take a look, because it looks like #1499

**Comment by NeoInChina** [comment]
apktool 2.3.0 could not decompile any ask from Huawei Mate10. Here I upload the framework file

[framework-res.apk.zip](https://github.com/iBotPeaches/Apktool/files/1543206/framework-res.apk.zip)
[SystemUI.apk.zip](https://github.com/iBotPeaches/Apktool/files/1543207/SystemUI.apk.zip)

**Comment by iBotPeaches** [comment]
https://github.com/iBotPeaches/Apktool/blob/master/ROADMAP.md#qualifier-plugin-system - In backlog roadmap for plugin system for these crazy OEMs.
