### ISSUE TITLE
out-of-range debug info offsets 

### ISSUE THREAD

**Issue by 404neko** [iBotPeaches/Apktool#1518]
### Information
1. **Apktool Version (`apktool 2.2.2`)** -
2. **Operating System (Windows)** -
3. **APK From? (Playstore)** -

### Stacktrace/Logcat
```
Error occurred while disassembling class Lvi.c; - skipping class
java.lang.ArrayIndexOutOfBoundsException: 0
        at org.jf.dexlib2.dexbacked.util.DebugInfo$DebugInfoImpl.iterator(DebugInfo.java:128)
        at org.jf.baksmali.Adaptors.MethodDefinition.addDebugInfo(MethodDefinition.java:576)
        at org.jf.baksmali.Adaptors.MethodDefinition.getMethodItems(MethodDefinition.java:378)
        at org.jf.baksmali.Adaptors.MethodDefinition.writeTo(MethodDefinition.java:238)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeVirtualMethods(ClassDefinition.java:327)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:113)
        at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:225)
        at org.jf.baksmali.baksmali.access$000(baksmali.java:55)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:149)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:147)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```
it is long but every part of the logcat is similay

### Steps to Reproduce
1. `apktool `

### APK
https://mega.nz/#!PUtDmKgT!XqvcJyjleMtYVuDEqCl99wX9i6nLlQs2G74zlXMHe4s

### Questions to ask before submission
Nothing

**Comment by iBotPeaches** [comment]
I would cross submit this to smali - https://github.com/JesusFreke/smali

I thought this was a similar issue that this fixed - https://github.com/JesusFreke/smali/commit/384161e060fc2bb40848b818d75f201c0ec037c8 but looks slightly different.

**Comment by iBotPeaches** [comment]
smali is correctly catching the error and telling you (the user) that those classes are skipped. My guess is that there is no way those classes would verify anyway.
