### ISSUE TITLE
Android O Signature issue with edited framework-res.apk #bootloop

### ISSUE THREAD

**Issue by argraur** [iBotPeaches/Apktool#1519]
### Information
1. **Apktool Version 2.2.3-a918b4-SNAPSHOT** -
2. **Operating System Linux** -
3. **APK From? ROM** -

### Stacktrace/Logcat

```
05-30 21:54:12.865  6624  6624 E System  : ******************************************
05-30 21:54:12.866  6624  6624 E System  : ************ Failure starting system services
05-30 21:54:12.866  6624  6624 E System  : java.lang.NullPointerException: Attempt to read from field 'android.content.pm.Signature[] android.content.pm.PackageParser$Package.mSignatures' on a null object reference
05-30 21:54:12.866  6624  6624 E System  : 	at com.android.server.pm.PackageManagerService.grantSignaturePermission(PackageManagerService.java:11857)
05-30 21:54:12.866  6624  6624 E System  : 	at com.android.server.pm.PackageManagerService.grantPermissionsLPw(PackageManagerService.java:11607)
05-30 21:54:12.866  6624  6624 E System  : 	at com.android.server.pm.PackageManagerService.updatePermissionsLPw(PackageManagerService.java:11463)
05-30 21:54:12.866  6624  6624 E System  : 	at com.android.server.pm.PackageManagerService.<init>(PackageManagerService.java:2705)
05-30 21:54:12.866  6624  6624 E System  : 	at com.android.server.pm.PackageManagerService.main(PackageManagerService.java:2144)
05-30 21:54:12.866  6624  6624 E System  : 	at com.android.server.SystemServer.startBootstrapServices(SystemServer.java:576)
05-30 21:54:12.866  6624  6624 E System  : 	at com.android.server.SystemServer.run(SystemServer.java:393)
05-30 21:54:12.866  6624  6624 E System  : 	at com.android.server.SystemServer.main(SystemServer.java:259)
05-30 21:54:12.866  6624  6624 E System  : 	at java.lang.reflect.Method.invoke(Native Method)
05-30 21:54:12.866  6624  6624 E System  : 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
05-30 21:54:12.866  6624  6624 E System  : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
05-30 21:54:12.866  6624  6624 D AndroidRuntime: Shutting down VM
05-30 21:54:12.866  6624  6624 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
05-30 21:54:12.866  6624  6624 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'android.content.pm.Signature[] android.content.pm.PackageParser$Package.mSignatures' on a null object reference
05-30 21:54:12.866  6624  6624 E AndroidRuntime: 	at com.android.server.pm.PackageManagerService.grantSignaturePermission(PackageManagerService.java:11857)
05-30 21:54:12.866  6624  6624 E AndroidRuntime: 	at com.android.server.pm.PackageManagerService.grantPermissionsLPw(PackageManagerService.java:11607)
05-30 21:54:12.866  6624  6624 E AndroidRuntime: 	at com.android.server.pm.PackageManagerService.updatePermissionsLPw(PackageManagerService.java:11463)
05-30 21:54:12.866  6624  6624 E AndroidRuntime: 	at com.android.server.pm.PackageManagerService.<init>(PackageManagerService.java:2705)
05-30 21:54:12.866  6624  6624 E AndroidRuntime: 	at com.android.server.pm.PackageManagerService.main(PackageManagerService.java:2144)
05-30 21:54:12.866  6624  6624 E AndroidRuntime: 	at com.android.server.SystemServer.startBootstrapServices(SystemServer.java:576)
05-30 21:54:12.866  6624  6624 E AndroidRuntime: 	at com.android.server.SystemServer.run(SystemServer.java:393)
05-30 21:54:12.866  6624  6624 E AndroidRuntime: 	at com.android.server.SystemServer.main(SystemServer.java:259)
05-30 21:54:12.866  6624  6624 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-30 21:54:12.866  6624  6624 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
05-30 21:54:12.866  6624  6624 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
05-30 21:54:12.867  6624  6624 E AndroidRuntime: Error reporting crash
05-30 21:54:12.867  6624  6624 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void android.app.IActivityManager.handleApplicationCrash(android.os.IBinder, android.app.ApplicationErrorReport$ParcelableCrashInfo)' on a null object reference
05-30 21:54:12.867  6624  6624 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:115)
05-30 21:54:12.867  6624  6624 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
05-30 21:54:12.867  6624  6624 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
05-30 21:54:12.867  6624  6624 E AndroidRuntime: 	at java.lang.Thread.dispatchUncaughtException(Thread.java:1953)
```

### Steps to Reproduce
1. `java -jar apktool-2.2.3-a918b4-SNAPSHOT-small.jar b framework-res -c`
2. `adb wait-for-device`
3. `adb logcat > logcat.txt`

### Questions to ask before submission
1. Yeah
2. Even with -c flag
3. Useless. Android O support introduces in 2.2.3 by latest commits.

**Comment by argraur** [comment]
[logcat.txt](https://github.com/iBotPeaches/Apktool/files/1039544/logcat.txt)
Full logcat

**Comment by iBotPeaches** [comment]
`-c` will be deprecated additionally please try with `--no-src` to see if the disassembling and re-assembling of source is causing this.

**Comment by argraur** [comment]
Ok sure.

**Comment by iBotPeaches** [comment]
As for `-c`. Nougat especially shut that down with full application block signatures. Changing any file invalidates it and thus rejects it, making that feature useless.

You will probably need to resign system applications if you plan on modifying them.

**Comment by argraur** [comment]
Should I use both? -c and --no-src?

**Comment by iBotPeaches** [comment]
`-c` takes original `AndroidManifest.xml` and `META-INF` folder and injects them into compiled apk. Usually this prevents signature signing as long as you don't require a modification to the manifest.

However, with Nougat and further any change to any file in the application invalidates the signature and gets rejected. Smali may be good, but rarely can it produce the same hash equivalent file when it decodes so disassembling and assembling the source causes that `classes.dex` file and probably most of the resources to fail the block check and get rejected.

However x2, the error is not about signature failing but an NPE on a signature related feature.

**Comment by argraur** [comment]
I think if we want to resign system applications we should change all keys with our ones, and sign every apk in priv-app/ and framework/

**Comment by argraur** [comment]
Hmm for my ROM, I always used -c flag (ROM is stock based).
I'd like to disable the signature check, but I don't know how to do that ;_;

**Comment by argraur** [comment]
But won't it cause SafetyNet fail? If we don't use Magisk.

**Comment by argraur** [comment]
Everything works after signature checking disable. Thanks!

**Comment by AragurDEV** [comment]
@argraur how did you disable it?
