### ISSUE TITLE
Error on decompile whit v2.2.2  java.lang.NullPointerException

### ISSUE THREAD

**Issue by Deltafox79** [iBotPeaches/Apktool#1526]
### Information
1. **Apktool Version 2.2.2
2. Windows
3. **APK From Playstore

### Stacktrace/Logcat

> W: null
> Exception in thread "main" java.lang.NullPointerException
> 	at brut.androlib.res.data.value.ResValueFactory.factory(ResValueFactory.java:74)
> 	at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:315)
> 	at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:241)
> 	at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:226)
> 	at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:156)
> 	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:118)
> 	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:80)
> 	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
> 	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:559)
> 	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:72)
> 	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:64)
> 	at brut.androlib.Androlib.getResTable(Androlib.java:67)
> 	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:193)
> 	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
> 	at brut.apktool.Main.cmdDecode(Main.java:166)
> 	at brut.apktool.Main.main(Main.java:81)

apk for test "framework.apk"

 http://www15.zippyshare.com/v/uHV4OodJ/file.html

**Comment by iBotPeaches** [comment]
Confirmed.

**Comment by lpcdma** [comment]
I found this problem related to language coding, such as the use of non-UTF-8 buffer will appear this problem. But I can not think of a common solution

```
java.nio.charset.MalformedInputException: Input length = 2
        at java.nio.charset.CoderResult.throwException(Unknown Source)
        at java.nio.charset.CharsetDecoder.decode(Unknown Source)
        at brut.androlib.res.decoder.StringBlock.decodeString(StringBlock.java:300)
        at brut.androlib.res.decoder.StringBlock.getString(StringBlock.java:110)
        at brut.androlib.res.decoder.StringBlock.getHTML(StringBlock.java:126)
        at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:316)
        at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:241)
        at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:226)
        at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:156)
        at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:118)
        at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:80)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:562)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:72)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:64)
        at brut.androlib.Androlib.getResTable(Androlib.java:68)
        at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:207)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:109)
        at brut.apktool.Main.cmdDecode(Main.java:166)
        at brut.apktool.Main.main(Main.java:81)
```

**Comment by iBotPeaches** [comment]
@lpcdma That stacktrace doesn't look the same as this one. The original issue never made it to the string decoder, it NPE`d far earlier than that.

**Comment by iBotPeaches** [comment]
> File has expired and does not exist anymore on this server

Sorry, 4+ years later. I can't triage anymore and you probably aren't following a ticket that wasn't fixed in years.

Closing.
