### ISSUE TITLE
Error when Compiling

### ISSUE THREAD

**Issue by madScript01** [iBotPeaches/Apktool#1531]
### Information
1. Apktool 2.2.3
2. Kali Linux

### Logcat
```
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_3968780579896419013.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 23, --version-code, 18875923, --version-name, 8.4.0.518, --no-version-vectors, -F, /tmp/APKTOOL138317774422927471.tmp, -0, arsc, -0, apk, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/Downloads/spotify/res, -M, /root/Downloads/spotify/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:493)
	at brut.androlib.Androlib.buildResources(Androlib.java:427)
	at brut.androlib.Androlib.build(Androlib.java:326)
	at brut.androlib.Androlib.build(Androlib.java:264)
	at brut.apktool.Main.cmdBuild(Main.java:231)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_3968780579896419013.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 23, --version-code, 18875923, --version-name, 8.4.0.518, --no-version-vectors, -F, /tmp/APKTOOL138317774422927471.tmp, -0, arsc, -0, apk, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/Downloads/spotify/res, -M, /root/Downloads/spotify/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:441)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:479)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_3968780579896419013.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 23, --version-code, 18875923, --version-name, 8.4.0.518, --no-version-vectors, -F, /tmp/APKTOOL138317774422927471.tmp, -0, arsc, -0, apk, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/Downloads/spotify/res, -M, /root/Downloads/spotify/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:435)
	... 6 more
```
### Steps to Reproduce
1. "apktool d -f -o spotify Spotify_8.4.0.518.apk"
2. Manually inserted a payload into the file and then when I try to compile the apk file with "apktool b spotify" it gives me this error

**Comment by iBotPeaches** [comment]
Hmm. Crashed on aapt execution, nothing in that stacktrace from apktool itself. Try running with `-v` and just upload that huge output into a text file and put it here.

Or just wait and I'll grab this Spotify apk and investigate myself.

**Comment by madScript01** [comment]
Ok, if when  I use the -v i will put here the logcat and then i will also put a link tho the apk file

**Comment by madScript01** [comment]
So here is the logcat and now here is the link to he apk:

http://www.mediafire.com/file/m2dx5sj8qp7j25w/Spotify_8.4.0.518.apk
[logs.txt](https://github.com/iBotPeaches/Apktool/files/1078143/logs.txt)

**Comment by madScript01** [comment]
Well looks like my problem won't be fixed :(

**Comment by iBotPeaches** [comment]
```
➜  Bug1531 apktool d Spotify_8.4.0.518.apk 
I: Using Apktool 2.2.3 on Spotify_8.4.0.518.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1531 apktool b Spotify_8.4.0.518
I: Using Apktool 2.2.3
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
➜  Bug1531 
```

Could not duplicate.
