### ISSUE TITLE
Error decompiling Hangouts v.20+

### ISSUE THREAD

**Issue by PerLycke** [iBotPeaches/Apktool#1534]
### Information
1. 2.2.4-acb004-SNAPSHOT (and 2.2.3)
2. Mac
3. Play Store

### Stacktrace/Logcat

```
I: Using Apktool 2.2.4-acb004-SNAPSHOT on Hangouts.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:52)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:562)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:72)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:64)
	at brut.androlib.Androlib.getResTable(Androlib.java:68)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:207)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:109)
	at brut.apktool.Main.cmdDecode(Main.java:166)
	at brut.apktool.Main.main(Main.java:81)
Caused by: java.io.IOException: Expected: 0x00000008, got: 0x00000202
	at brut.util.ExtDataInput.skipCheckShort(ExtDataInput.java:56)
	at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:309)
	at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:241)
	at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:226)
	at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:156)
	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:118)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:80)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
	... 8 more
```

### Steps to Reproduce
1. apktool d Hangouts.apk

**Comment by iBotPeaches** [comment]
Confirmed.

**Comment by iBotPeaches** [comment]
Started looking into this. It failed on resource `0x7f0e0449` which was supposed to be an `id` type attribute.

```
➜  Bug1534 aapt d resources hangouts.apk | grep '0x7f0e0449'                                                             
      INVALID TYPE CONFIG FOR RESOURCE 0x7f0e0449
        INVALID RESOURCE 0x7f0e0449: t=0x00 d=0x0000016c (s=0x0202 r=0x10)
```

This group has 1098 resources. We have 1097. Will need to create some work-around for this.

**Comment by iBotPeaches** [comment]
The `ResChunk_header` on every chunk has the `size` of the entire chunk. We are reading too much data, hence the error. We incorrectly trusted that `entrySize` correctly reflected the amount of resources.

So at the 1098 resource we are at position `8567862` in the file, however we the max side according to the "chunk" is `8567860`.

We are exceeded the chunk. We need to add a check if position is equal to the max, then quit that chunk.
