### ISSUE TITLE
i have a really problem with recompile Farming Simulator 18 

### ISSUE THREAD

**Issue by IntensityTeam** [iBotPeaches/Apktool#1535]
ApkTool 2.2.3 

apktool b FS18.apk

```
C:\Users\filip\Desktop\apktool>apktool b C:\Users\filip\Desktop\apktool\FS18
I: Using Apktool 2.2.3
I: Checking whether resources has changed...
I: Building resources...
W: C:\Users\filip\Desktop\apktool\FS18\res\layout-v22\abc_alert_dialog_button_bar_material.xml:2: error: No resource identifier found for attribute 'scrollIndicators' in package 'android'
W:
W: C:\Users\filip\Desktop\apktool\FS18\res\layout-v21\abc_screen_toolbar.xml:5: error: No resource identifier found for attribute 'touchscreenBlocksFocus' in package 'android'
W:
W: C:\Users\filip\Desktop\apktool\FS18\res\drawable\abc_ic_ab_back_material.xml:4: error: No resource identifier found for attribute 'fillColor' in package 'android'
W:
W: C:\Users\filip\Desktop\apktool\FS18\res\drawable\abc_ic_arrow_drop_right_black_24dp.xml:5: error: No resource identifier found for attribute 'fillColor' in package 'android'
W:
W: C:\Users\filip\Desktop\apktool\FS18\res\drawable\abc_ic_clear_material.xml:4: error: No resource identifier found for attribute 'fillColor' in package 'android'
W:
W: C:\Users\filip\Desktop\apktool\FS18\res\drawable\abc_ic_go_search_api_material.xml:4: error: No resource identifier found for attribute 'fillColor' in package 'android'
W:
W: C:\Users\filip\Desktop\apktool\FS18\res\drawable\abc_ic_menu_overflow_material.xml:4: error: No resource identifier found for attribute 'fillColor' in package 'android'
W:
W: C:\Users\filip\Desktop\apktool\FS18\res\drawable\abc_ic_search_api_material.xml:4: error: No resource identifier found for attribute 'fillColor' in package 'android'
W:
W: C:\Users\filip\Desktop\apktool\FS18\res\drawable\abc_ic_voice_search_api_material.xml:4: error: No resource identifier found for attribute 'fillColor' in package 'android'
W:
W: C:\Users\filip\Desktop\apktool\FS18\res\drawable-v21\abc_ratingbar_indicator_material.xml:7: error: No resource identifier found for attribute 'tileModeX' in package 'android'
Exception in thread "main" W:
W: C:\Users\filip\Desktop\apktool\FS18\res\drawable-v21\abc_ratingbar_material.xml:7: error: No resource identifier found for attribute 'tileModeX' in package 'android'
brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\filip\AppData\Local\Temp\brut_util_Jar_5987438473773632346.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 24, --version-code, 24201003, --version-name, 1.0.0.3 - Google - OES2, --no-version-vectors, -F, C:\Users\filip\AppData\Local\Temp\APKTOOL6830767461334564357.tmp, -0, arsc, -0, save, -0, arsc, -I, C:\Users\filip\AppData\Local\apktool\framework\1.apk, -S, C:\Users\filip\Desktop\apktool\FS18\res, -M, C:\Users\filip\Desktop\apktool\FS18\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:493)
        at brut.androlib.Androlib.buildResources(Androlib.java:427)
        at brut.androlib.Androlib.build(Androlib.java:326)
        at brut.androlib.Androlib.build(Androlib.java:264)
        at brut.apktool.Main.cmdBuild(Main.java:231)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\filip\AppData\Local\Temp\brut_util_Jar_5987438473773632346.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 24, --version-code, 24201003, --version-name, 1.0.0.3 - Google - OES2, --no-version-vectors, -F, C:\Users\filip\AppData\Local\Temp\APKTOOL6830767461334564357.tmp, -0, arsc, -0, save, -0, arsc, -I, C:\Users\filip\AppData\Local\apktool\framework\1.apk, -S, C:\Users\filip\Desktop\apktool\FS18\res, -M, C:\Users\filip\Desktop\apktool\FS18\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:441)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:479)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\filip\AppData\Local\Temp\brut_util_Jar_5987438473773632346.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 24, --version-code, 24201003, --version-name, 1.0.0.3 - Google - OES2, --no-version-vectors, -F, C:\Users\filip\AppData\Local\Temp\APKTOOL6830767461334564357.tmp, -0, arsc, -0, save, -0, arsc, -I, C:\Users\filip\AppData\Local\apktool\framework\1.apk, -S, C:\Users\filip\Desktop\apktool\FS18\res, -M, C:\Users\filip\Desktop\apktool\FS18\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:435)
        ... 6 more
W:
W: C:\Users\filip\Desktop\apktool\FS18\res\drawable-v21\abc_ratingbar_small_material.xml:7: error: No resource identifier found for attribute 'tileModeX' in package 'android'
W:
W: C:\Users\filip\Desktop\apktool\FS18\res\drawable\abc_vector_test.xml:4: error: No resource identifier found for attribute 'fillColor' in package 'android'
W:
W: C:\Users\filip\Desktop\apktool\FS18\res\drawable\com_facebook_button_login_logo.xml:4: error: No resource identifier found for attribute 'fillColor' in package 'android'
W:
W: C:\Users\filip\Desktop\apktool\FS18\res\drawable\com_facebook_favicon_blue.xml:4: error: No resource identifier found for attribute 'fillColor' in package 'android'
W:

C:\Users\filip\Desktop\apktool>

```

**Comment by iBotPeaches** [comment]
Try running `apktool empty-framework-dir --force` and retry and let me know.

**Comment by IntensityTeam** [comment]
same thing 
`
C:\Users\filip\Desktop\apktool>apktool b -f FS18
I: Using Apktool 2.2.3
I: Copying FS18 classes.dex file...
I: Building resources...
W: C:\Users\filip\Desktop\apktool\FS18\res\layout-v22\abc_alert_dialog_button_bar_material.xml:2: error: No resource identifier found for attribute 'scrollIndicators' in package 'android'
W:
W: C:\Users\filip\Desktop\apktool\FS18\res\layout-v21\abc_screen_toolbar.xml:5: error: No resource identifier found for attribute 'touchscreenBlocksFocus' in package 'android'
Exception in thread "main" W:
W: C:\Users\filip\Desktop\apktool\FS18\res\drawable\abc_ic_ab_back_material.xml:4: error: No resource identifier found for attribute 'fillColor' in package 'android'
brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\filip\AppData\Local\Temp\brut_util_Jar_4647694766371294899.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 24, --version-code, 24201003, --version-name, 1.0.0.3 - Google - OES2, --no-version-vectors, -F, C:\Users\filip\AppData\Local\Temp\APKTOOL3079492848461368045.tmp, -0, arsc, -0, save, -0, arsc, -I, C:\Users\filip\AppData\Local\apktool\framework\1.apk, -S, C:\Users\filip\Desktop\apktool\FS18\res, -M, C:\Users\filip\Desktop\apktool\FS18\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:493)
        at brut.androlib.Androlib.buildResources(Androlib.java:427)
        at brut.androlib.Androlib.build(Androlib.java:326)
        at brut.androlib.Androlib.build(Androlib.java:264)
        at brut.apktool.Main.cmdBuild(Main.java:231)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\filip\AppData\Local\Temp\brut_util_Jar_4647694766371294899.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 24, --version-code, 24201003, --version-name, 1.0.0.3 - Google - OES2, --no-version-vectors, -F, C:\Users\filip\AppData\Local\Temp\APKTOOL3079492848461368045.tmp, -0, arsc, -0, save, -0, arsc, -I, C:\Users\filip\AppData\Local\apktool\framework\1.apk, -S, C:\Users\filip\Desktop\apktool\FS18\res, -M, C:\Users\filip\Desktop\apktool\FS18\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:441)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:479)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\filip\AppData\Local\Temp\brut_util_Jar_4647694766371294899.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 24, --version-code, 24201003, --version-name, 1.0.0.3 - Google - OES2, --no-version-vectors, -F, C:\Users\filip\AppData\Local\Temp\APKTOOL3079492848461368045.tmp, -0, arsc, -0, save, -0, arsc, -I, C:\Users\filip\AppData\Local\apktool\framework\1.apk, -S, C:\Users\filip\Desktop\apktool\FS18\res, -M, C:\Users\filip\Desktop\apktool\FS18\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:435)
        ... 6 more
W:
W: C:\Users\filip\Desktop\apktool\FS18\res\drawable\abc_ic_arrow_drop_right_black_24dp.xml:5: error: No resource identifier found for attribute 'fillColor' in package 'android'
W:
W: C:\Users\filip\Desktop\apktool\FS18\res\drawable\abc_ic_clear_material.xml:4: error: No resource identifier found for attribute 'fillColor' in package 'android'
W:
W: C:\Users\filip\Desktop\apktool\FS18\res\drawable\abc_ic_go_search_api_material.xml:4: error: No resource identifier found for attribute 'fillColor' in package 'android'
W:
W: C:\Users\filip\Desktop\apktool\FS18\res\drawable\abc_ic_menu_overflow_material.xml:4: error: No resource identifier found for attribute 'fillColor' in package 'android'
W:
W: C:\Users\filip\Desktop\apktool\FS18\res\drawable\abc_ic_search_api_material.xml:4: error: No resource identifier found for attribute 'fillColor' in package 'android'
W:
W: C:\Users\filip\Desktop\apktool\FS18\res\drawable\abc_ic_voice_search_api_material.xml:4: error: No resource identifier found for attribute 'fillColor' in package 'android'
W:
W: C:\Users\filip\Desktop\apktool\FS18\res\drawable-v21\abc_ratingbar_indicator_material.xml:7: error: No resource identifier found for attribute 'tileModeX' in package 'android'
W:
W: C:\Users\filip\Desktop\apktool\FS18\res\drawable-v21\abc_ratingbar_material.xml:7: error: No resource identifier found for attribute 'tileModeX' in package 'android'
W:
W: C:\Users\filip\Desktop\apktool\FS18\res\drawable-v21\abc_ratingbar_small_material.xml:7: error: No resource identifier found for attribute 'tileModeX' in package 'android'
W:
W: C:\Users\filip\Desktop\apktool\FS18\res\drawable\abc_vector_test.xml:4: error: No resource identifier found for attribute 'fillColor' in package 'android'
W:
W: C:\Users\filip\Desktop\apktool\FS18\res\drawable\com_facebook_button_login_logo.xml:4: error: No resource identifier found for attribute 'fillColor' in package 'android'
W:
W: C:\Users\filip\Desktop\apktool\FS18\res\drawable\com_facebook_favicon_blue.xml:4: error: No resource identifier found for attribute 'fillColor' in package 'android'
W:`

**Comment by iBotPeaches** [comment]
I'll look into it. Confirming this is the application? https://play.google.com/store/apps/details?id=com.giantssoftware.fs18.google&hl=en

Also triple ticks ``` is what triggers the code blocks :)

**Comment by IntensityTeam** [comment]
so what can i do to recompile it 

    Il Mercoledì 21 Giugno 2017 14:56, Connor Tumbleson <notifications@github.com> ha scritto:
 

 I'll look into it. Confirming this is the application? https://play.google.com/store/apps/details?id=com.giantssoftware.fs18.google&hl=enAlso triple ticks ``` is what triggers the code blocks :)—

**Comment by iBotPeaches** [comment]
I can't look into this due this is being a paid application. I apologize.
