### ISSUE TITLE
Recompiling error

### ISSUE THREAD

**Issue by dbof10** [iBotPeaches/Apktool#1537]
Information

Apktool Version: Tried both apktool 2.2.3
Operating System: MacOS
APK: https://drive.google.com/open?id=0B4utNhIw_evpNHlveGVvVWRDVDQ

Stacktrace/Logcat

```
I: Using Apktool 2.2.3
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: res/drawable/$avd_hide_password__0.xml: Invalid file name: must contain only [a-zA-Z0-9_.]. Ignoring...
W: res/drawable/$avd_hide_password__1.xml: Invalid file name: must contain only [a-zA-Z0-9_.]. Ignoring...
W: res/drawable/$avd_hide_password__2.xml: Invalid file name: must contain only [a-zA-Z0-9_.]. Ignoring...
W: res/drawable/$avd_show_password__0.xml: Invalid file name: must contain only [a-zA-Z0-9_.]. Ignoring...
W: res/drawable/$avd_show_password__1.xml: Invalid file name: must contain only [a-zA-Z0-9_.]. Ignoring...
W: res/drawable/$avd_show_password__2.xml: Invalid file name: must contain only [a-zA-Z0-9_.]. Ignoring...
W: A/        ( 5036): First type is not attr!
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 134): [/var/folders/dd/qm71z_9j6jd8yr8hfj0xj5j00000gp/T/brut_util_Jar_7912458143856853366.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 25, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /var/folders/dd/qm71z_9j6jd8yr8hfj0xj5j00000gp/T/APKTOOL1582439934222996058.tmp, -0, arsc, -0, res/raw/joda_atlantic_jan_mayen, -0, res/raw/joda_est, -0, res/raw/joda_etc_gmt, -0, res/raw/joda_etc_gmt_1, -0, res/raw/joda_etc_gmt_10, -0, res/raw/joda_etc_gmt_11, -0, res/raw/joda_etc_gmt_12, -0, res/raw/joda_etc_gmt_13, -0, res/raw/joda_etc_gmt_14, -0, res/raw/joda_etc_gmt_2, -0, res/raw/joda_etc_gmt_3, -0, res/raw/joda_etc_gmt_4, -0, res/raw/joda_etc_gmt_5, -0, res/raw/joda_etc_gmt_6, -0, res/raw/joda_etc_gmt_7, -0, res/raw/joda_etc_gmt_8, -0, res/raw/joda_etc_gmt_9, -0, res/raw/joda_etc_gmtplus1, -0, res/raw/joda_etc_gmtplus10, -0, res/raw/joda_etc_gmtplus11, -0, res/raw/joda_etc_gmtplus12, -0, res/raw/joda_etc_gmtplus2, -0, res/raw/joda_etc_gmtplus3, -0, res/raw/joda_etc_gmtplus4, -0, res/raw/joda_etc_gmtplus5, -0, res/raw/joda_etc_gmtplus6, -0, res/raw/joda_etc_gmtplus7, -0, res/raw/joda_etc_gmtplus8, -0, res/raw/joda_etc_gmtplus9, -0, res/raw/joda_etc_uct, -0, res/raw/joda_etc_utc, -0, res/raw/joda_hst, -0, res/raw/joda_mst, -0, res/raw/joda_pacific_johnston, -0, arsc, -I, /Users/daniel/Library/apktool/framework/1.apk, -S, /Users/daniel/Downloads/app-debug/res, -M, /Users/daniel/Downloads/app-debug/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:493)
	at brut.androlib.Androlib.buildResources(Androlib.java:427)
	at brut.androlib.Androlib.build(Androlib.java:326)
	at brut.androlib.Androlib.build(Androlib.java:264)
	at brut.apktool.Main.cmdBuild(Main.java:231)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 134): [/var/folders/dd/qm71z_9j6jd8yr8hfj0xj5j00000gp/T/brut_util_Jar_7912458143856853366.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 25, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /var/folders/dd/qm71z_9j6jd8yr8hfj0xj5j00000gp/T/APKTOOL1582439934222996058.tmp, -0, arsc, -0, res/raw/joda_atlantic_jan_mayen, -0, res/raw/joda_est, -0, res/raw/joda_etc_gmt, -0, res/raw/joda_etc_gmt_1, -0, res/raw/joda_etc_gmt_10, -0, res/raw/joda_etc_gmt_11, -0, res/raw/joda_etc_gmt_12, -0, res/raw/joda_etc_gmt_13, -0, res/raw/joda_etc_gmt_14, -0, res/raw/joda_etc_gmt_2, -0, res/raw/joda_etc_gmt_3, -0, res/raw/joda_etc_gmt_4, -0, res/raw/joda_etc_gmt_5, -0, res/raw/joda_etc_gmt_6, -0, res/raw/joda_etc_gmt_7, -0, res/raw/joda_etc_gmt_8, -0, res/raw/joda_etc_gmt_9, -0, res/raw/joda_etc_gmtplus1, -0, res/raw/joda_etc_gmtplus10, -0, res/raw/joda_etc_gmtplus11, -0, res/raw/joda_etc_gmtplus12, -0, res/raw/joda_etc_gmtplus2, -0, res/raw/joda_etc_gmtplus3, -0, res/raw/joda_etc_gmtplus4, -0, res/raw/joda_etc_gmtplus5, -0, res/raw/joda_etc_gmtplus6, -0, res/raw/joda_etc_gmtplus7, -0, res/raw/joda_etc_gmtplus8, -0, res/raw/joda_etc_gmtplus9, -0, res/raw/joda_etc_uct, -0, res/raw/joda_etc_utc, -0, res/raw/joda_hst, -0, res/raw/joda_mst, -0, res/raw/joda_pacific_johnston, -0, arsc, -I, /Users/daniel/Library/apktool/framework/1.apk, -S, /Users/daniel/Downloads/app-debug/res, -M, /Users/daniel/Downloads/app-debug/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:441)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:479)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 134): [/var/folders/dd/qm71z_9j6jd8yr8hfj0xj5j00000gp/T/brut_util_Jar_7912458143856853366.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 25, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /var/folders/dd/qm71z_9j6jd8yr8hfj0xj5j00000gp/T/APKTOOL1582439934222996058.tmp, -0, arsc, -0, res/raw/joda_atlantic_jan_mayen, -0, res/raw/joda_est, -0, res/raw/joda_etc_gmt, -0, res/raw/joda_etc_gmt_1, -0, res/raw/joda_etc_gmt_10, -0, res/raw/joda_etc_gmt_11, -0, res/raw/joda_etc_gmt_12, -0, res/raw/joda_etc_gmt_13, -0, res/raw/joda_etc_gmt_14, -0, res/raw/joda_etc_gmt_2, -0, res/raw/joda_etc_gmt_3, -0, res/raw/joda_etc_gmt_4, -0, res/raw/joda_etc_gmt_5, -0, res/raw/joda_etc_gmt_6, -0, res/raw/joda_etc_gmt_7, -0, res/raw/joda_etc_gmt_8, -0, res/raw/joda_etc_gmt_9, -0, res/raw/joda_etc_gmtplus1, -0, res/raw/joda_etc_gmtplus10, -0, res/raw/joda_etc_gmtplus11, -0, res/raw/joda_etc_gmtplus12, -0, res/raw/joda_etc_gmtplus2, -0, res/raw/joda_etc_gmtplus3, -0, res/raw/joda_etc_gmtplus4, -0, res/raw/joda_etc_gmtplus5, -0, res/raw/joda_etc_gmtplus6, -0, res/raw/joda_etc_gmtplus7, -0, res/raw/joda_etc_gmtplus8, -0, res/raw/joda_etc_gmtplus9, -0, res/raw/joda_etc_uct, -0, res/raw/joda_etc_utc, -0, res/raw/joda_hst, -0, res/raw/joda_mst, -0, res/raw/joda_pacific_johnston, -0, arsc, -I, /Users/daniel/Library/apktool/framework/1.apk, -S, /Users/daniel/Downloads/app-debug/res, -M, /Users/daniel/Downloads/app-debug/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:435)
	... 6 more
```

Steps to Reproduce

Download Linux wrapper script
Download apktool-2.2.3
Rename downloaded jar to apktool.jar
Move both files (apktool.jar & apktool) to /usr/local/bin
chmod +x apktool apktool.jar
apktool d ***.apk
apktool b ***
Frameworks

No

APK

https://drive.google.com/open?id=0B4utNhIw_evpNHlveGVvVWRDVDQ

Questions to ask before submission

Have you tried apktool d, apktool b without changing anything?
Yes
If you are trying to install a modified apk, did you resign it?
NO
Are you using the latest apktool version?
Yes

Resource https://github.com/dlew/joda-time-android

**Comment by iBotPeaches** [comment]
Both errors are exact duplicates of #1532 so closing as duplicate.

**Comment by dbof10** [comment]
Could you take a look at 
```
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 134): [/var/folders/dd/qm71z_9j6jd8yr8hfj0xj5j00000gp/T/brut_util_Jar_7912458143856853366.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 25, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /var/folders/dd/qm71z_9j6jd8yr8hfj0xj5j00000gp/T/APKTOOL1582439934222996058.tmp, -0, arsc, -0, res/raw/joda_atlantic_jan_mayen, -0, res/raw/joda_est, -0, res/raw/joda_etc_gmt, -0, res/raw/joda_etc_gmt_1, -0, res/raw/joda_etc_gmt_10, -0, res/raw/joda_etc_gmt_11, -0, res/raw/joda_etc_gmt_12, -0, res/raw/joda_etc_gmt_13, -0, res/raw/joda_etc_gmt_14, -0, res/raw/joda_etc_gmt_2, -0, res/raw/joda_etc_gmt_3, -0, res/raw/joda_etc_gmt_4, -0, res/raw/joda_etc_gmt_5, -0, res/raw/joda_etc_gmt_6, -0, res/raw/joda_etc_gmt_7, -0, res/raw/joda_etc_gmt_8, -0, res/raw/joda_etc_gmt_9, -0, res/raw/joda_etc_gmtplus1, -0, res/raw/joda_etc_gmtplus10, -0, res/raw/joda_etc_gmtplus11, -0, res/raw/joda_etc_gmtplus12, -0, res/raw/joda_etc_gmtplus2, -0, res/raw/joda_etc_gmtplus3, -0, res/raw/joda_etc_gmtplus4, -0, res/raw/joda_etc_gmtplus5, -0, res/raw/joda_etc_gmtplus6, -0, res/raw/joda_etc_gmtplus7, -0, res/raw/joda_etc_gmtplus8, -0, res/raw/joda_etc_gmtplus9, -0, res/raw/joda_etc_uct, -0, res/raw/joda_etc_utc, -0, res/raw/joda_hst, -0, res/raw/joda_mst, -0, res/raw/joda_pacific_johnston, -0, arsc, -I, /Users/daniel/Library/apktool/framework/1.apk, -S, /Users/daniel/Downloads/app-debug/res, -M, /Users/daniel/Downloads/app-debug/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:441)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:479)
```
Another error with resources

**Comment by iBotPeaches** [comment]
That error is `aapt` failing because of

```
W: res/drawable/$avd_hide_password__0.xml: Invalid file name: must contain only [a-zA-Z0-9_.]. Ignoring...
W: res/drawable/$avd_hide_password__1.xml: Invalid file name: must contain only [a-zA-Z0-9_.]. Ignoring...
```

**Comment by dbof10** [comment]
Ok. Thank you
