### ISSUE TITLE
Error while recompile without change using v2.0.3, v2.1.0, v2.2.2, v2.2.3

### ISSUE THREAD

**Issue by polaris0227** [iBotPeaches/Apktool#1548]
### Information
1. **Apktool Version v2.0.3, v2.1.0, v2.2.2, v2.2.3 ** -
2. **Operating System (Windows 8)** -
3. **APK From? (Other)** -

### Stacktrace/Logcat

```
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\PMH\AppData\Local\Temp\brut_util_Jar_7847003529894331423.tmp, p, --forced-package-id, 127, --min-sdk-version, 17, --target-sdk-version, 21, --version-code, 303533177, --version-name, RabbitAndroidApp-3.0.6579.0_303533177, --no-version-vectors, -F, C:\Users\PMH\AppData\Local\Temp\APKTOOL1225558984687499562.tmp, -0, arsc, -0, apk, -0, res/raw/joda_atlantic_jan_mayen, -0, res/raw/joda_est, -0, res/raw/joda_etc_gmt, -0, res/raw/joda_etc_gmt_1, -0, res/raw/joda_etc_gmt_10, -0, res/raw/joda_etc_gmt_11, -0, res/raw/joda_etc_gmt_12, -0, res/raw/joda_etc_gmt_13, -0, res/raw/joda_etc_gmt_14, -0, res/raw/joda_etc_gmt_2, -0, res/raw/joda_etc_gmt_3, -0, res/raw/joda_etc_gmt_4, -0, res/raw/joda_etc_gmt_5, -0, res/raw/joda_etc_gmt_6, -0, res/raw/joda_etc_gmt_7, -0, res/raw/joda_etc_gmt_8, -0, res/raw/joda_etc_gmt_9, -0, res/raw/joda_etc_gmtplus1, -0, res/raw/joda_etc_gmtplus10, -0, res/raw/joda_etc_gmtplus11, -0, res/raw/joda_etc_gmtplus12, -0, res/raw/joda_etc_gmtplus2, -0, res/raw/joda_etc_gmtplus3, -0, res/raw/joda_etc_gmtplus4, -0, res/raw/joda_etc_gmtplus5, -0, res/raw/joda_etc_gmtplus6, -0, res/raw/joda_etc_gmtplus7, -0, res/raw/joda_etc_gmtplus8, -0, res/raw/joda_etc_gmtplus9, -0, res/raw/joda_etc_uct, -0, res/raw/joda_etc_utc, -0, res/raw/joda_hst, -0, res/raw/joda_mst, -0, res/raw/nk_de_de, -0, res/raw/nk_de_de_audio, -0, res/raw/nk_en_gb, -0, res/raw/nk_en_gb_audio, -0, res/raw/nk_en_us, -0, res/raw/nk_es_es, -0, res/raw/nk_es_es_audio, -0, res/raw/nk_es_mx, -0, res/raw/nk_fr_ca, -0, res/raw/nk_fr_ca_audio, -0, res/raw/nk_fr_fr, -0, res/raw/nk_fr_fr_audio, -0, res/raw/nk_it_it, -0, res/raw/nk_it_it_audio, -0, res/raw/nk_nl_nl, -0, res/raw/nk_nl_nl_audio, -0, arsc, -I, e:\Software\android\decompile\Tools\AdvancedApkTool\1-BDFreak\Frameworks\1.apk, -S, e:\Software\android\decompile\Tools\AdvancedApkTool\3-Out\amazon.apk\res, -M, e:\Software\android\decompile\Tools\AdvancedApkTool\3-Out\amazon.apk\AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:477)
	at brut.androlib.Androlib.buildResources(Androlib.java:411)
	at brut.androlib.Androlib.build(Androlib.java:310)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\PMH\AppData\Local\Temp\brut_util_Jar_7847003529894331423.tmp, p, --forced-package-id, 127, --min-sdk-version, 17, --target-sdk-version, 21, --version-code, 303533177, --version-name, RabbitAndroidApp-3.0.6579.0_303533177, --no-version-vectors, -F, C:\Users\PMH\AppData\Local\Temp\APKTOOL1225558984687499562.tmp, -0, arsc, -0, apk, -0, res/raw/joda_atlantic_jan_mayen, -0, res/raw/joda_est, -0, res/raw/joda_etc_gmt, -0, res/raw/joda_etc_gmt_1, -0, res/raw/joda_etc_gmt_10, -0, res/raw/joda_etc_gmt_11, -0, res/raw/joda_etc_gmt_12, -0, res/raw/joda_etc_gmt_13, -0, res/raw/joda_etc_gmt_14, -0, res/raw/joda_etc_gmt_2, -0, res/raw/joda_etc_gmt_3, -0, res/raw/joda_etc_gmt_4, -0, res/raw/joda_etc_gmt_5, -0, res/raw/joda_etc_gmt_6, -0, res/raw/joda_etc_gmt_7, -0, res/raw/joda_etc_gmt_8, -0, res/raw/joda_etc_gmt_9, -0, res/raw/joda_etc_gmtplus1, -0, res/raw/joda_etc_gmtplus10, -0, res/raw/joda_etc_gmtplus11, -0, res/raw/joda_etc_gmtplus12, -0, res/raw/joda_etc_gmtplus2, -0, res/raw/joda_etc_gmtplus3, -0, res/raw/joda_etc_gmtplus4, -0, res/raw/joda_etc_gmtplus5, -0, res/raw/joda_etc_gmtplus6, -0, res/raw/joda_etc_gmtplus7, -0, res/raw/joda_etc_gmtplus8, -0, res/raw/joda_etc_gmtplus9, -0, res/raw/joda_etc_uct, -0, res/raw/joda_etc_utc, -0, res/raw/joda_hst, -0, res/raw/joda_mst, -0, res/raw/nk_de_de, -0, res/raw/nk_de_de_audio, -0, res/raw/nk_en_gb, -0, res/raw/nk_en_gb_audio, -0, res/raw/nk_en_us, -0, res/raw/nk_es_es, -0, res/raw/nk_es_es_audio, -0, res/raw/nk_es_mx, -0, res/raw/nk_fr_ca, -0, res/raw/nk_fr_ca_audio, -0, res/raw/nk_fr_fr, -0, res/raw/nk_fr_fr_audio, -0, res/raw/nk_it_it, -0, res/raw/nk_it_it_audio, -0, res/raw/nk_nl_nl, -0, res/raw/nk_nl_nl_audio, -0, arsc, -I, e:\Software\android\decompile\Tools\AdvancedApkTool\1-BDFreak\Frameworks\1.apk, -S, e:\Software\android\decompile\Tools\AdvancedApkTool\3-Out\amazon.apk\res, -M, e:\Software\android\decompile\Tools\AdvancedApkTool\3-Out\amazon.apk\AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:440)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:463)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\PMH\AppData\Local\Temp\brut_util_Jar_7847003529894331423.tmp, p, --forced-package-id, 127, --min-sdk-version, 17, --target-sdk-version, 21, --version-code, 303533177, --version-name, RabbitAndroidApp-3.0.6579.0_303533177, --no-version-vectors, -F, C:\Users\PMH\AppData\Local\Temp\APKTOOL1225558984687499562.tmp, -0, arsc, -0, apk, -0, res/raw/joda_atlantic_jan_mayen, -0, res/raw/joda_est, -0, res/raw/joda_etc_gmt, -0, res/raw/joda_etc_gmt_1, -0, res/raw/joda_etc_gmt_10, -0, res/raw/joda_etc_gmt_11, -0, res/raw/joda_etc_gmt_12, -0, res/raw/joda_etc_gmt_13, -0, res/raw/joda_etc_gmt_14, -0, res/raw/joda_etc_gmt_2, -0, res/raw/joda_etc_gmt_3, -0, res/raw/joda_etc_gmt_4, -0, res/raw/joda_etc_gmt_5, -0, res/raw/joda_etc_gmt_6, -0, res/raw/joda_etc_gmt_7, -0, res/raw/joda_etc_gmt_8, -0, res/raw/joda_etc_gmt_9, -0, res/raw/joda_etc_gmtplus1, -0, res/raw/joda_etc_gmtplus10, -0, res/raw/joda_etc_gmtplus11, -0, res/raw/joda_etc_gmtplus12, -0, res/raw/joda_etc_gmtplus2, -0, res/raw/joda_etc_gmtplus3, -0, res/raw/joda_etc_gmtplus4, -0, res/raw/joda_etc_gmtplus5, -0, res/raw/joda_etc_gmtplus6, -0, res/raw/joda_etc_gmtplus7, -0, res/raw/joda_etc_gmtplus8, -0, res/raw/joda_etc_gmtplus9, -0, res/raw/joda_etc_uct, -0, res/raw/joda_etc_utc, -0, res/raw/joda_hst, -0, res/raw/joda_mst, -0, res/raw/nk_de_de, -0, res/raw/nk_de_de_audio, -0, res/raw/nk_en_gb, -0, res/raw/nk_en_gb_audio, -0, res/raw/nk_en_us, -0, res/raw/nk_es_es, -0, res/raw/nk_es_es_audio, -0, res/raw/nk_es_mx, -0, res/raw/nk_fr_ca, -0, res/raw/nk_fr_ca_audio, -0, res/raw/nk_fr_fr, -0, res/raw/nk_fr_fr_audio, -0, res/raw/nk_it_it, -0, res/raw/nk_it_it_audio, -0, res/raw/nk_nl_nl, -0, res/raw/nk_nl_nl_audio, -0, arsc, -I, e:\Software\android\decompile\Tools\AdvancedApkTool\1-BDFreak\Frameworks\1.apk, -S, e:\Software\android\decompile\Tools\AdvancedApkTool\3-Out\amazon.apk\res, -M, e:\Software\android\decompile\Tools\AdvancedApkTool\3-Out\amazon.apk\AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:434)
	... 6 more
```

### APK
https://drive.google.com/file/d/0B1o-k8SwIZ6WbXg5RlI1Q3VSLXc/view?usp=sharing

### Questions to ask before submission
1. I used Advanced apk tool to recompile
2. I couldn't get new apk because i got error while recompile
3. I tried to use v2.0.3, v2.1.0, v2.2.2, v2.2.3

Hope anyone to help me.
Kind regards.

**Comment by polaris0227** [comment]
If anyone needs apk to check, please inform me.
I'll share apk if needed.
Thanks again.

**Comment by iBotPeaches** [comment]
There isn't an error in your above stacktrace, just the exit 1 code caused by a BrutException. That usually means aapt failed, but the error/warning prior to that failure is above. Usually the entire apktool output is good to post for that reason.

However, I took the attached apk

```
➜  Bug1548 apktool d signed_AmazonFlex-3.0.6579.0-Prod-release-RabbitAndroidAppSigned.apk 
I: Using Apktool 2.2.4-988fd1-SNAPSHOT on signed_AmazonFlex-3.0.6579.0-Prod-release-RabbitAndroidAppSigned.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1548 apktool b signed_AmazonFlex-3.0.6579.0-Prod-release-RabbitAndroidAppSigned
I: Using Apktool 2.2.4-988fd1-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
W: warning: string 'delivery_recipient_secure_location_amzl' has no default translation.
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
➜  Bug1548 
```

Could not duplicate.
