### ISSUE TITLE
Failure processing PNG image (4-bit PNG?!)

### ISSUE THREAD

**Issue by IgorEisberg** [iBotPeaches/Apktool#1559]
### Information
1. **Apktool Version: 2.2.3**
2. **Operating System: Windows 10 Ann. Update (x64)**
3. **APK From? ROM (ColorOS)**

### Decompile

```
java -jar apktool_2.2.3.jar d OppoWeather.apk
I: Using Apktool 2.2.3 on OppoWeather.apk
I: Loading resource table...
I: Decoding Shared Library (oppo), pkgId: 12
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Iceberg\AppData\Local\apktool\framework\1.apk
I: Loading resource table from file: C:\Users\Iceberg\AppData\Local\apktool\framework\12.apk
I: Decoding Shared Library (com.mediatek), pkgId: 8
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
```

### Recompile

```
java -jar apktool_2.2.3.jar b OppoWeather
I: Using Apktool 2.2.3
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
W: libpng error: Read Error
W: ERROR: Failure processing PNG image D:\Desktop\OppoWeather\OppoWeather\res\drawable-xxhdpi-v4\fog_day_fog2.png
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Iceberg\AppData\Local\Temp\brut_util_Jar_7119727420143806455.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 22, --version-code, 40001, --version-name, 4.0.0, --no-version-vectors, -F, C:\Users\Iceberg\AppData\Local\Temp\APKTOOL6591758469764326393.tmp, -0, arsc, -0, arsc, -I, C:\Users\Iceberg\AppData\Local\apktool\framework\1.apk, -I, C:\Users\Iceberg\AppData\Local\apktool\framework\12.apk, -S, D:\Desktop\OppoWeather\OppoWeather\res, -M, D:\Desktop\OppoWeather\OppoWeather\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:493)
        at brut.androlib.Androlib.buildResources(Androlib.java:427)
        at brut.androlib.Androlib.build(Androlib.java:326)
        at brut.androlib.Androlib.build(Androlib.java:264)
        at brut.apktool.Main.cmdBuild(Main.java:231)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Iceberg\AppData\Local\Temp\brut_util_Jar_7119727420143806455.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 22, --version-code, 40001, --version-name, 4.0.0, --no-version-vectors, -F, C:\Users\Iceberg\AppData\Local\Temp\APKTOOL6591758469764326393.tmp, -0, arsc, -0, arsc, -I, C:\Users\Iceberg\AppData\Local\apktool\framework\1.apk, -I, C:\Users\Iceberg\AppData\Local\apktool\framework\12.apk, -S, D:\Desktop\OppoWeather\OppoWeather\res, -M, D:\Desktop\OppoWeather\OppoWeather\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:441)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:479)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Iceberg\AppData\Local\Temp\brut_util_Jar_7119727420143806455.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 22, --version-code, 40001, --version-name, 4.0.0, --no-version-vectors, -F, C:\Users\Iceberg\AppData\Local\Temp\APKTOOL6591758469764326393.tmp, -0, arsc, -0, arsc, -I, C:\Users\Iceberg\AppData\Local\apktool\framework\1.apk, -I, C:\Users\Iceberg\AppData\Local\apktool\framework\12.apk, -S, D:\Desktop\OppoWeather\OppoWeather\res, -M, D:\Desktop\OppoWeather\OppoWeather\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:435)
        ... 6 more
```

### Steps to Reproduce
Just decompile and recompile.
NOTE: The classes.dex is missing, it's fine.
The only thing that can open this "damaged" 4-bit PNG file seems to be Color Quantizer. Then it can save it to a new PNG (also 4 bit) which then works on all image viewers.

### APK + Frameworks
http://www.mediafire.com/file/aq8bbuig1ubrgxv/OppoWeather.zip

**Comment by iBotPeaches** [comment]
Interesting

```
➜  drawable-xxhdpi-v4 file fog_day_fog2.png
fog_day_fog2.png: PNG image data, 1618 x 629, 4-bit colormap, non-interlaced
➜  drawable-xxhdpi-v4 file fog_day_fog1.png
fog_day_fog1.png: PNG image data, 1758 x 421, 8-bit colormap, non-interlaced
➜  drawable-xxhdpi-v4 
```

I might have to do some tests if Android can even load/parse this 4 bit colormap, or if this is just a build tool limitation.

**Comment by theGeekyLad** [comment]
## [SystemUI.apk] Temporary Fix
Grab the fixed `pip_dismiss_scrim.9.png` from the link below. The APK **finally recompiles** but I had no luck booting up my N5X after flashing it though. You guys could try it out. Running Oreo Release here.

[https://goo.gl/12kgue](url)

**Comment by iBotPeaches** [comment]
Chucking this up to a bad image. Nothing Apktool can do.

> Something appears to be missing…

I can't really triage anymore anyway. Sorry for 4+ year delay.
