### ISSUE TITLE
libpng error: Not a PNG file (Wrong decompiled extensions)

### ISSUE THREAD

**Issue by IgorEisberg** [iBotPeaches/Apktool#1560]
### Information
1. **Apktool Version: 2.2.3**
2. **Operating System: Windows 10 Ann. Update (x64)**
3. **APK From? ROM (ColorOS)**

### Decompile

```
java -jar apktool_2.2.3.jar d Keyguard.apk
I: Using Apktool 2.2.3 on Keyguard.apk
I: Loading resource table...
I: Decoding Shared Library (oppo), pkgId: 12
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Iceberg\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Loading resource table from file: C:\Users\Iceberg\AppData\Local\apktool\framework\12.apk
I: Decoding Shared Library (com.mediatek), pkgId: 8
I: Decoding values */* XMLs...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
```

### Recompile

```
java -jar apktool_2.2.3.jar b Keyguard
I: Using Apktool 2.2.3
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image D:\Desktop\OppoWeather\Keyguard\res\drawable-nodpi-v4\left_card_preview_braca_exp.png
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image D:\Desktop\OppoWeather\Keyguard\res\drawable-nodpi-v4\right_card_preview_braca_exp.png
W: libpng error: Not a PNG file
W: ERROR: Failure processing PNG image D:\Desktop\OppoWeather\Keyguard\res\drawable-nodpi-v4\unlock_demo_thumb_braca_exp.png
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Iceberg\AppData\Local\Temp\brut_util_Jar_8932293899077050717.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 21, --version-code, 5, --version-name, 3.0.0, --no-version-vectors, -F, C:\Users\Iceberg\AppData\Local\Temp\APKTOOL589869890265844230.tmp, -0, arsc, -0, arsc, -I, C:\Users\Iceberg\AppData\Local\apktool\framework\1.apk, -I, C:\Users\Iceberg\AppData\Local\apktool\framework\12.apk, -S, D:\Desktop\OppoWeather\Keyguard\res, -M, D:\Desktop\OppoWeather\Keyguard\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:493)
        at brut.androlib.Androlib.buildResources(Androlib.java:427)
        at brut.androlib.Androlib.build(Androlib.java:326)
        at brut.androlib.Androlib.build(Androlib.java:264)
        at brut.apktool.Main.cmdBuild(Main.java:231)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Iceberg\AppData\Local\Temp\brut_util_Jar_8932293899077050717.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 21, --version-code, 5, --version-name, 3.0.0, --no-version-vectors, -F, C:\Users\Iceberg\AppData\Local\Temp\APKTOOL589869890265844230.tmp, -0, arsc, -0, arsc, -I, C:\Users\Iceberg\AppData\Local\apktool\framework\1.apk, -I, C:\Users\Iceberg\AppData\Local\apktool\framework\12.apk, -S, D:\Desktop\OppoWeather\Keyguard\res, -M, D:\Desktop\OppoWeather\Keyguard\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:441)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:479)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Iceberg\AppData\Local\Temp\brut_util_Jar_8932293899077050717.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 21, --version-code, 5, --version-name, 3.0.0, --no-version-vectors, -F, C:\Users\Iceberg\AppData\Local\Temp\APKTOOL589869890265844230.tmp, -0, arsc, -0, arsc, -I, C:\Users\Iceberg\AppData\Local\apktool\framework\1.apk, -I, C:\Users\Iceberg\AppData\Local\apktool\framework\12.apk, -S, D:\Desktop\OppoWeather\Keyguard\res, -M, D:\Desktop\OppoWeather\Keyguard\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:435)
        ... 6 more
```

### Steps to Reproduce
Just decompile and recompile.
NOTE: The classes.dex is missing, it's fine.
Seems like the decompilation named these three files with *.png extension, when these should be named *.jpg, hence the error.
Files with "Exif" signature are correctly identified and named as *.jpg, while those with "JFIF" signature seem to be named *.png for some reason.

### APK + Frameworks
http://www.mediafire.com/file/8ymox4c039pyym9/Keyguard.zip

**Comment by iBotPeaches** [comment]
Hmm. looks like it was intended to be a `png`.

```
➜  Bug1560 unzip -l Keyguard.apk  | grep 'left_card'
   187578  2017-04-11 15:04   res/drawable-nodpi-v4/left_card_preview.jpg
   231835  2017-04-11 15:04   res/drawable-nodpi-v4/left_card_preview_braca_exp.png
   227576  2017-04-11 15:13   res/drawable-nodpi-v4/left_card_preview_globe_exp.png
```
Apktool does file headers for any magic values. It relies solely on the file extension provided in the file for decoding purposes.

**Comment by IgorEisberg** [comment]
Interesting. How the hell did they manage to build that APK to begin with if so... 0_0

**Comment by iBotPeaches** [comment]
Yeah not much apktool can do here. Apktool is not in the business to automatically parse/fix headers of images. We do some image manipulations, but that is strictly for 9patch images.

This is just some seriously messed up images. Case in point below.

```
➜  Bug1560 file Keyguard/res/drawable-nodpi-v4/right_card_preview_braca_exp.png 
Keyguard/res/drawable-nodpi-v4/right_card_preview_braca_exp.png: JPEG image data, JFIF standard 1.01, resolution (DPI), density 72x72, segment length 16, Exif Standard: [TIFF image data, big-endian, direntries=7, orientation=upper-left, xresolution=98, yresolution=106, resolutionunit=2, software=Adobe Photoshop CC 2015 (Windows), datetime=2015:08:27 12:45:18], baseline, precision 8, 858x1525, frames 3
```

So `right_card_preview_braca_exp.png` has the magic of a `jpeg`. Thats great. So lets check a `jpg` in this app.

```
➜  Bug1560 file Keyguard/res/drawable-nodpi-v4/unlock_demo_thumb.jpg 
Keyguard/res/drawable-nodpi-v4/unlock_demo_thumb.jpg: PNG image data, 332 x 576, 8-bit/color RGB, non-interlaced
```

You've got to me kidding me. The JPG is a PNG, and the PNGs are JPG (some of them)

```
➜  Bug1560 file Keyguard/res/drawable-nodpi-v4/unlock_demo_thumb_globe_exp.png 
Keyguard/res/drawable-nodpi-v4/unlock_demo_thumb_globe_exp.png: PNG image data, 428 x 761, 8-bit/color RGB, non-interlaced
```

At least that one is fine. As you can see here, there is not much apktool can do here. I fixed those 3 images

```
➜  Bug1560 apktool b Keyguard                                                  
I: Using Apktool 2.2.4-d0d84b-SNAPSHOT
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
W: warning: string 'change_setting_for_onenewsim' has no default translation.
W: warning: string 'change_setting_for_removesim' has no default translation.
... translation warnings
I: Building apk file...
I: Copying unknown files/dir...
➜  Bug1560 
```

However, I don't know if hidden away in the source is a reference to the PNGs, as they are JPEGs now. This is why apktool cannot automate something like this, unless it gained the ability to remap file references

**Comment by Nidiots** [comment]
install imagemagick https://www.imagemagick.org/script/index.php and run
magick mogrify *.png
in problem image folder.
