### ISSUE TITLE
ERROR WHILE DECOMPILING AND COMPILING.

### ISSUE THREAD

**Issue by pritamdstan** [iBotPeaches/Apktool#1562]
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.3
2. **Operating System (Mac, Linux, Windows)** - Windows 10
3. **APK From? (Playstore, ROM, Other)** - Rom

### Stacktrace/Logcat

**WHILE DECOMPILING:**
```
C:\not>java -jar apktool.jar if framework-res.apk
I: Framework installed to: C:\Users\PRITAM\AppData\Local\apktool\framework\1.apk

C:\not>java -jar apktool.jar if twframework-res.apk
I: Framework installed to: C:\Users\PRITAM\AppData\Local\apktool\framework\2.apk

C:\not>java -jar apktool.jar d SystemUI.apk
I: Using Apktool 2.2.3 on SystemUI.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\PRITAM\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/scrubber_primary_mtrl_alpha.9.pio
S: Could not decode file, replacing by FALSE value: drawable/tw_action_item_background_pressed_holo_dark.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/tw_divider_vertical_holo_light.9.pio
S: Could not decode file, replacing by FALSE value: drawable/tw_action_item_background_focused_holo_dark.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/status_background.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/recents_thumbnail_bg.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/ic_notification_overlay.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/tw_list_divider_holo_light.9.pio
S: Could not decode file, replacing by FALSE value: drawable-nodpi-v4/keyguard_carrierlockplus_unlock_btn_normal.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/screenshot_panel.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/scrubber_primary_holo.9.pio
S: Could not decode file, replacing by FALSE value: drawable-nodpi-v4/keyguard_carrierlockplus_emergency_btn_pressed.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/scrubber_secondary_holo.9.pio
S: Could not decode file, replacing by FALSE value: drawable/tw_divider_vertical_holo_light.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/spinner_default_holo_dark_am_no_underline.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/bg_protect.9.pio
S: Could not decode file, replacing by FALSE value: drawable-nodpi-v4/keyguard_carrierlockplus_call_btn_pressed.9.pio
S: Could not decode file, replacing by FALSE value: drawable-nodpi-v4/keyguard_carrierlockplus_unlock_btn_pressed.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/recents_status_gradient.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/gradation_indi_bg.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/tw_clear_button_bg_normal.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/nav_background.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/status_background_sma_xte.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/taskmanager_btn_default_transparency_mtrl.9.pio
S: Could not decode file, replacing by FALSE value: drawable-nodpi-v4/homescreen_menu_noti_bg.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/taskmanager_btn_default_mtrl.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/tw_quick_panel_sfinder_qconnect_button_bg.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/tw_quick_panel_sfinder_qconnect_button_pressed.9.pio
S: Could not decode file, replacing by FALSE value: drawable-nodpi-v4/bg_help_button_nor.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/tw_divider_vertical_holo_dark.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/tw_action_item_background_pressed_holo_dark.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/quick_setting_panel_bg_shadow_01.9.pio
S: Could not decode file, replacing by FALSE value: drawable/help_popup_picker_bg_w_01.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/security_btn_bg.9.pio
S: Could not decode file, replacing by FALSE value: drawable-nodpi-v4/keyguard_carrierlockplus_call_btn_normal.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/notification_panel_bg.9.pio
S: Could not decode file, replacing by FALSE value: drawable/focused_bg.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/tw_clear_button_bg_pressed.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/tw_action_item_background_focused_holo_dark.9.pio
S: Could not decode file, replacing by FALSE value: drawable-port-hdpi-v4/bg_protect.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/search_bg_transparent.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/scrubber_track_holo_light.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/tw_quick_panel_quick_setting_button_bg_normal.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/quick_setting_panel_bg_shadow_02.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/help_popup_picker_bg_w_01.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/recents_thumbnail_bg_press.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/lock_noticard_badge_bg_tilt.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/status_bar_close_on.9.pio
S: Could not decode file, replacing by FALSE value: drawable-nodpi-v4/bg_popup.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/kg_widget_bg_padded.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/recents_thumbnail_bg_normal.9.pio
S: Could not decode file, replacing by FALSE value: drawable/unfocused_bg.9.pio
S: Could not decode file, replacing by FALSE value: drawable-nodpi-v4/keyguard_carrierlockplus_emergency_btn_normal.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/tw_clear_button_bg_focussed.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/status_bar_close_off.9.pio
S: Could not decode file, replacing by FALSE value: drawable-land-hdpi-v4/bg_protect.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/keyguard_fmm_btn_pressed.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/setting_panel_bg_line.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/tw_list_divider_holo_dark.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/tw_quick_panel_sfinder_qconnect_button_normal.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/keyguard_fmm_btn_default.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/keyguard_signature_bg.9.pio
S: Could not decode file, replacing by FALSE value: drawable/scrubber_primary_mtrl_alpha.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/recents_task_shadow.9.pio
S: Could not decode file, replacing by FALSE value: drawable-hdpi-v4/recents_lower_gradient.9.pio
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
```

**WHILE COMPILING BACK (WITHOUT ANY CHANGES MADE)**
```
C:\not>java -jar apktool.jar b SystemUI
I: Using Apktool 2.2.3
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: C:\not\SystemUI\res\values\drawables.xml:10: error: Resource entry focused_bg is already defined.
W: res\drawable\focused_bg.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values\drawables.xml:11: error: Resource entry help_popup_picker_bg_w_01 is already defined.
W: res\drawable\help_popup_picker_bg_w_01.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values\drawables.xml:21: error: Resource entry scrubber_primary_mtrl_alpha is already defined.
W: res\drawable\scrubber_primary_mtrl_alpha.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values\drawables.xml:91: error: Resource entry tw_action_item_background_focused_holo_dark is already defined.
W: res\drawable\tw_action_item_background_focused_holo_dark.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values\drawables.xml:92: error: Resource entry tw_action_item_background_pressed_holo_dark is already defined.
W: res\drawable\tw_action_item_background_pressed_holo_dark.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values\drawables.xml:93: error: Resource entry tw_divider_vertical_holo_light is already defined.
W: res\drawable\tw_divider_vertical_holo_light.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values\drawables.xml:100: error: Resource entry unfocused_bg is already defined.
W: res\drawable\unfocused_bg.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:3: error: Resource entry gradation_indi_bg is already defined.
W: res\drawable-hdpi-v4\gradation_indi_bg.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:4: error: Resource entry keyguard_fmm_btn_default is already defined.
W: res\drawable-hdpi-v4\keyguard_fmm_btn_default.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:5: error: Resource entry keyguard_fmm_btn_pressed is already defined.
W: res\drawable-hdpi-v4\keyguard_fmm_btn_pressed.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:6: error: Resource entry keyguard_signature_bg is already defined.
W: res\drawable-hdpi-v4\keyguard_signature_bg.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:7: error: Resource entry kg_widget_bg_padded is already defined.
W: res\drawable-hdpi-v4\kg_widget_bg_padded.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:8: error: Resource entry scrubber_primary_holo is already defined.
W: res\drawable-hdpi-v4\scrubber_primary_holo.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:9: error: Resource entry scrubber_secondary_holo is already defined.
W: res\drawable-hdpi-v4\scrubber_secondary_holo.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:10: error: Resource entry scrubber_track_holo_light is already defined.
W: res\drawable-hdpi-v4\scrubber_track_holo_light.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:11: error: Resource entry security_btn_bg is already defined.
W: res\drawable-hdpi-v4\security_btn_bg.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:12: error: Resource entry help_popup_picker_bg_w_01 is already defined.
W: res\drawable-hdpi-v4\help_popup_picker_bg_w_01.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:13: error: Resource entry scrubber_primary_mtrl_alpha is already defined.
W: res\drawable-hdpi-v4\scrubber_primary_mtrl_alpha.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:14: error: Resource entry tw_action_item_background_focused_holo_dark is already defined.
W: res\drawable-hdpi-v4\tw_action_item_background_focused_holo_dark.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:15: error: Resource entry tw_action_item_background_pressed_holo_dark is already defined.
W: res\drawable-hdpi-v4\tw_action_item_background_pressed_holo_dark.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:16: error: Resource entry tw_divider_vertical_holo_light is already defined.
W: res\drawable-hdpi-v4\tw_divider_vertical_holo_light.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:17: error: Resource entry bg_protect is already defined.
W: res\drawable-hdpi-v4\bg_protect.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:18: error: Resource entry ic_notification_overlay is already defined.
W: res\drawable-hdpi-v4\ic_notification_overlay.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:19: error: Resource entry lock_noticard_badge_bg_tilt is already defined.
W: res\drawable-hdpi-v4\lock_noticard_badge_bg_tilt.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:20: error: Resource entry nav_background is already defined.
W: res\drawable-hdpi-v4\nav_background.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:21: error: Resource entry notification_panel_bg is already defined.
Exception in thread "main" W: res\drawable-hdpi-v4\notification_panel_bg.9.pio:0: Originally defined here.
brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\PRITAM\AppData\Local\Temp\brut_util_Jar_2455217956140909489.tmp, p, --forced-package-id, 127, --min-sdk-version, 22, --target-sdk-version, 22, --version-code, 22, --version-name, 5.1.1-J200GDDU2AQF3, --no-version-vectors, -F, C:\Users\PRITAM\AppData\Local\Temp\APKTOOL8139180529059477535.tmp, -0, arsc, -0, webp, -0, pio, -0, qmg, -0, arsc, -I, C:\Users\PRITAM\AppData\Local\apktool\framework\1.apk, -S, C:\not\SystemUI\res, -M, C:\not\SystemUI\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:493)
        at brut.androlib.Androlib.buildResources(Androlib.java:427)
        at brut.androlib.Androlib.build(Androlib.java:326)
        at brut.androlib.Androlib.build(Androlib.java:264)
        at brut.apktool.Main.cmdBuild(Main.java:231)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\PRITAM\AppData\Local\Temp\brut_util_Jar_2455217956140909489.tmp, p, --forced-package-id, 127, --min-sdk-version, 22, --target-sdk-version, 22, --version-code, 22, --version-name, 5.1.1-J200GDDU2AQF3, --no-version-vectors, -F, C:\Users\PRITAM\AppData\Local\Temp\APKTOOL8139180529059477535.tmp, -0, arsc, -0, webp, -0, pio, -0, qmg, -0, arsc, -I, C:\Users\PRITAM\AppData\Local\apktool\framework\1.apk, -S, C:\not\SystemUI\res, -M, C:\not\SystemUI\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:441)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:479)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\PRITAM\AppData\Local\Temp\brut_util_Jar_2455217956140909489.tmp, p, --forced-package-id, 127, --min-sdk-version, 22, --target-sdk-version, 22, --version-code, 22, --version-name, 5.1.1-J200GDDU2AQF3, --no-version-vectors, -F, C:\Users\PRITAM\AppData\Local\Temp\APKTOOL8139180529059477535.tmp, -0, arsc, -0, webp, -0, pio, -0, qmg, -0, arsc, -I, C:\Users\PRITAM\AppData\Local\apktool\framework\1.apk, -S, C:\not\SystemUI\res, -M, C:\not\SystemUI\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:435)
        ... 6 more
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:22: error: Resource entry quick_setting_panel_bg_shadow_01 is already defined.
W: res\drawable-hdpi-v4\quick_setting_panel_bg_shadow_01.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:23: error: Resource entry quick_setting_panel_bg_shadow_02 is already defined.
W: res\drawable-hdpi-v4\quick_setting_panel_bg_shadow_02.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:24: error: Resource entry recents_lower_gradient is already defined.
W: res\drawable-hdpi-v4\recents_lower_gradient.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:25: error: Resource entry recents_status_gradient is already defined.
W: res\drawable-hdpi-v4\recents_status_gradient.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:26: error: Resource entry recents_task_shadow is already defined.
W: res\drawable-hdpi-v4\recents_task_shadow.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:27: error: Resource entry recents_thumbnail_bg is already defined.
W: res\drawable-hdpi-v4\recents_thumbnail_bg.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:28: error: Resource entry recents_thumbnail_bg_normal is already defined.
W: res\drawable-hdpi-v4\recents_thumbnail_bg_normal.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:29: error: Resource entry recents_thumbnail_bg_press is already defined.
W: res\drawable-hdpi-v4\recents_thumbnail_bg_press.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:30: error: Resource entry screenshot_panel is already defined.
W: res\drawable-hdpi-v4\screenshot_panel.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:31: error: Resource entry search_bg_transparent is already defined.
W: res\drawable-hdpi-v4\search_bg_transparent.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:32: error: Resource entry setting_panel_bg_line is already defined.
W: res\drawable-hdpi-v4\setting_panel_bg_line.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:33: error: Resource entry spinner_default_holo_dark_am_no_underline is already defined.
W: res\drawable-hdpi-v4\spinner_default_holo_dark_am_no_underline.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:34: error: Resource entry status_background is already defined.
W: res\drawable-hdpi-v4\status_background.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:35: error: Resource entry status_background_sma_xte is already defined.
W: res\drawable-hdpi-v4\status_background_sma_xte.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:36: error: Resource entry status_bar_close_off is already defined.
W: res\drawable-hdpi-v4\status_bar_close_off.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:37: error: Resource entry status_bar_close_on is already defined.
W: res\drawable-hdpi-v4\status_bar_close_on.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:38: error: Resource entry taskmanager_btn_default_mtrl is already defined.
W: res\drawable-hdpi-v4\taskmanager_btn_default_mtrl.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:39: error: Resource entry taskmanager_btn_default_transparency_mtrl is already defined.
W: res\drawable-hdpi-v4\taskmanager_btn_default_transparency_mtrl.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:40: error: Resource entry tw_clear_button_bg_focussed is already defined.
W: res\drawable-hdpi-v4\tw_clear_button_bg_focussed.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:41: error: Resource entry tw_clear_button_bg_normal is already defined.
W: res\drawable-hdpi-v4\tw_clear_button_bg_normal.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:42: error: Resource entry tw_clear_button_bg_pressed is already defined.
W: res\drawable-hdpi-v4\tw_clear_button_bg_pressed.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:43: error: Resource entry tw_divider_vertical_holo_dark is already defined.
W: res\drawable-hdpi-v4\tw_divider_vertical_holo_dark.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:44: error: Resource entry tw_list_divider_holo_dark is already defined.
W: res\drawable-hdpi-v4\tw_list_divider_holo_dark.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:45: error: Resource entry tw_list_divider_holo_light is already defined.
W: res\drawable-hdpi-v4\tw_list_divider_holo_light.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:46: error: Resource entry tw_quick_panel_quick_setting_button_bg_normal is already defined.
W: res\drawable-hdpi-v4\tw_quick_panel_quick_setting_button_bg_normal.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:47: error: Resource entry tw_quick_panel_sfinder_qconnect_button_bg is already defined.
W: res\drawable-hdpi-v4\tw_quick_panel_sfinder_qconnect_button_bg.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:48: error: Resource entry tw_quick_panel_sfinder_qconnect_button_normal is already defined.
W: res\drawable-hdpi-v4\tw_quick_panel_sfinder_qconnect_button_normal.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-hdpi-v4\drawables.xml:49: error: Resource entry tw_quick_panel_sfinder_qconnect_button_pressed is already defined.
W: res\drawable-hdpi-v4\tw_quick_panel_sfinder_qconnect_button_pressed.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-port-hdpi-v4\drawables.xml:3: error: Resource entry bg_protect is already defined.
W: res\drawable-port-hdpi-v4\bg_protect.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-land-hdpi-v4\drawables.xml:3: error: Resource entry bg_protect is already defined.
W: res\drawable-land-hdpi-v4\bg_protect.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-nodpi-v4\drawables.xml:3: error: Resource entry bg_help_button_nor is already defined.
W: res\drawable-nodpi-v4\bg_help_button_nor.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-nodpi-v4\drawables.xml:4: error: Resource entry bg_popup is already defined.
W: res\drawable-nodpi-v4\bg_popup.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-nodpi-v4\drawables.xml:5: error: Resource entry homescreen_menu_noti_bg is already defined.
W: res\drawable-nodpi-v4\homescreen_menu_noti_bg.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-nodpi-v4\drawables.xml:6: error: Resource entry keyguard_carrierlockplus_call_btn_normal is already defined.
W: res\drawable-nodpi-v4\keyguard_carrierlockplus_call_btn_normal.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-nodpi-v4\drawables.xml:7: error: Resource entry keyguard_carrierlockplus_call_btn_pressed is already defined.
W: res\drawable-nodpi-v4\keyguard_carrierlockplus_call_btn_pressed.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-nodpi-v4\drawables.xml:8: error: Resource entry keyguard_carrierlockplus_emergency_btn_normal is already defined.
W: res\drawable-nodpi-v4\keyguard_carrierlockplus_emergency_btn_normal.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-nodpi-v4\drawables.xml:9: error: Resource entry keyguard_carrierlockplus_emergency_btn_pressed is already defined.
W: res\drawable-nodpi-v4\keyguard_carrierlockplus_emergency_btn_pressed.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-nodpi-v4\drawables.xml:10: error: Resource entry keyguard_carrierlockplus_unlock_btn_normal is already defined.
W: res\drawable-nodpi-v4\keyguard_carrierlockplus_unlock_btn_normal.9.pio:0: Originally defined here.
W:
W: C:\not\SystemUI\res\values-nodpi-v4\drawables.xml:11: error: Resource entry keyguard_carrierlockplus_unlock_btn_pressed is already defined.
W: res\drawable-nodpi-v4\keyguard_carrierlockplus_unlock_btn_pressed.9.pio:0: Originally defined here.
W:
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)
[frameworks TW.zip](https://github.com/iBotPeaches/Apktool/files/1148961/frameworks.TW.zip)

### APK
If this APK can be freely shared, please upload/attach a link to it.
[SystemUI.zip](https://github.com/iBotPeaches/Apktool/files/1148971/SystemUI.zip)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?:  YES
2. If you are trying to install a modified apk, did you resign it?: THE APK DOESNT EVEN BUILD.
3. Are you using the latest apktool version?: YES

I am using the latest version of apktool , with java path setup right. But the apk doesnt seem to compile or decompile correctly. I tried for a whole day, couldnt figure out anything.
Same happens when I try in Kali linux 64 bit...tried every solution mentioned from the ISSUEs..but nothing works,

Please advice.

**Comment by iBotPeaches** [comment]
`9.pio` files. Must be another samsung proprietary format, probably a variation on the 9patch.

**Comment by pritamdstan** [comment]
so is there anything to solve this issue? or will there be a fix ?

**Comment by iBotPeaches** [comment]
I just marked it as a bug. There is no work-around, unless you deleted all `9.pio` images. Generally bugs get fixed, unless they prove too difficult to patch. Apktool is open source so you are welcome to contribute any research/code/fixes you find.

**Comment by iBotPeaches** [comment]
4 years later. I don't have Samsung and as proof but this 3-4 year delay - this isn't going anywhere.

Closing for my sanity of this backlog.
