### ISSUE TITLE
Could not decode res(arsc)

### ISSUE THREAD

**Issue by mikusjelly** [iBotPeaches/Apktool#1564]
### Information
1. **Apktool Version (`2.2.3`)** -
2. **Operating System (Windows)** -
3. **APK From? I don't know.** -

### Stacktrace/Logcat
```
I: Using Apktool 2.2.3 on test.zip
I: Loading resource table...
W: null
Exception in thread "main" java.lang.NullPointerException
        at brut.androlib.res.data.value.ResValueFactory.factory(ResValueFactory.java:74)
        at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:315)
        at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:241)
        at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:226)
        at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:156)
        at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:118)
        at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:80)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:562)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:72)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:64)
        at brut.androlib.Androlib.getResTable(Androlib.java:68)
        at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:207)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:109)
        at brut.apktool.Main.cmdDecode(Main.java:166)
        at brut.apktool.Main.main(Main.java:81)
```

### Steps to Reproduce
1. `apktool d -s test.zip `

### APK
[test.zip](https://github.com/iBotPeaches/Apktool/files/1157951/test.zip)

**Comment by iBotPeaches** [comment]
Interesting mess of strings here. I don't know if Apktool can process these mess of strings, but for now I can treat them as `null` and survive decoding.

![1534](https://user-images.githubusercontent.com/611784/28667013-a84d52ba-7297-11e7-8c31-e30554e8cd10.png)

**Comment by mikusjelly** [comment]
Thanks.
