### ISSUE TITLE
Cannot build APK with Java 1.8.0.141 installed

### ISSUE THREAD

**Issue by s911415** [iBotPeaches/Apktool#1565]
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.3
2. **Operating System (Mac, Linux, Windows)** - Windows 10 x64 1607
3. **APK From? (Playstore, ROM, Other)** - Playstore
4. **Java version** - 1.8.0_141 x64

### Stacktrace/Logcat

```
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\user\AppData\Local\Temp\brut_util_Jar_1517260200812730885.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 23, --version-code, 16070803, --version-name, 7.8.2, --no-version-vectors, -F, C:\Users\user\AppData\Local\Temp\APKTOOL1235318122665025785.tmp, -0, arsc, -0, js, -0, dat, -0, bin, -0, arsc, -I, C:\Users\user\AppData\Local\apktool\framework\1.apk, -S, Y:\App_Dec\res, -M, Y:\App_Dec\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:493)
        at brut.androlib.Androlib.buildResources(Androlib.java:427)
        at brut.androlib.Androlib.build(Androlib.java:326)
        at brut.androlib.Androlib.build(Androlib.java:264)
        at brut.apktool.Main.cmdBuild(Main.java:231)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\user\AppData\Local\Temp\brut_util_Jar_1517260200812730885.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 23, --version-code, 16070803, --version-name, 7.8.2, --no-version-vectors, -F, C:\Users\user\AppData\Local\Temp\APKTOOL1235318122665025785.tmp, -0, arsc, -0, js, -0, dat, -0, bin, -0, arsc, -I, C:\Users\user\AppData\Local\apktool\framework\1.apk, -S, Y:\App_Dec\res, -M, Y:\App_Dec\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:441)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:479)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\user\AppData\Local\Temp\brut_util_Jar_1517260200812730885.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 23, --version-code, 16070803, --version-name, 7.8.2, --no-version-vectors, -F, C:\Users\user\AppData\Local\Temp\APKTOOL1235318122665025785.tmp, -0, arsc, -0, js, -0, dat, -0, bin, -0, arsc, -I, C:\Users\user\AppData\Local\apktool\framework\1.apk, -S, Y:\App_Dec\res, -M, Y:\App_Dec\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:435)
        ... 6 more
```

### Steps to Reproduce
1. `apktool d Path_To_APK_File.apk -o OutputPath`
2. `modify some .smali files`
3. `apktool b Pervious_Output_Path -o OutputPath.apk`

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Y
2. If you are trying to install a modified apk, did you resign it? Y
3. Are you using the latest apktool version? Y

Since I upgrade my java version to 1.8.0.141, i failed to build an apk file.
Same commands works if I run on a computer which java 1.8.0.131 installed.

**Comment by iBotPeaches** [comment]
Nothing in that stacktrace shows an error, besides that an error occurred. Please post link to exact apk or dump stacktrace in verbose mode (`-v`)

**Comment by s911415** [comment]
Following links are my stacktrace with verbose mode and apk file
[stacktrace.txt](https://github.com/iBotPeaches/Apktool/files/1167048/stacktrace.txt)
[apk.apk](https://gofile.io/?c=3ZXldT)

**Comment by iBotPeaches** [comment]
Could not duplicate on mac. Seeing how ticket was made for Windows, I'll wait till I can check on Windows to confirm.

```
➜  Bug1565 apktool d apk.apk 
I: Using Apktool 2.2.4-d0d84b-SNAPSHOT on apk.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/connortumbleson/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes4.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1565 apktool b apk
I: Using Apktool 2.2.4-d0d84b-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes4 folder into classes4.dex...
I: Checking whether resources has changed...
I: Building resources...
W: warning: string 'app_package_status_in_review_under_processing' has no default translation.
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
➜  Bug1565 
```

**Comment by iBotPeaches** [comment]
```
C:\Users\Connor\Desktop\bin>java -jar apktool-2.2.3-15c4f3-SNAPSHOT-small.jar d apk.apk
I: Using Apktool 2.2.3-15c4f3-SNAPSHOT on apk.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Connor\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes4.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

C:\Users\Connor\Desktop\bin>java -jar apktool-2.2.3-15c4f3-SNAPSHOT-small.jar b apk
I: Using Apktool 2.2.3-15c4f3-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes4 folder into classes4.dex...
I: Checking whether resources has changed...
I: Building resources...
W: warning: string 'app_package_status_in_review_under_processing' has no default translation.
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...

C:\Users\Connor\Desktop\bin>
```

Couldn't duplicate on Windows either.
