### ISSUE TITLE
APK: Attributes are garbled of public app

### ISSUE THREAD

**Issue by johnsmith39** [iBotPeaches/Apktool#1576]
### Information
1. Apktool 2.2.4
2. Windows
3. Playstore: https://play.google.com/store/apps/details?id=com.spacosa.android.famy.global&hl=de (or attached)

### Stacktrace/Logcat

```
I: Using Apktool 2.2.4 on com.spacosa.android.famy.global.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\john\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
[Fatal Error] :42:41: Element type "application" must be followed by either attribute specifications, ">" or "/>".
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
```
### Outputted Manifest:
```
<manifest package="com.spacosa.android.famy.global" android:versionCode="273" android:versionName="3.73" android:installLocation="internalOnly" xmlns:Liapp_Empty_00=""
  xmlns:android="http://schemas.android.com/apk/res/android">
...
<application OYG0l="@style/MyTheme" 3tAoS="@string/app_name" h8CpO="@drawable/famy_icon" 6Ollg="com.lockincomp.liapp.LiappCommon" mLSsB="locale" s5k5m="true">
```
### Exception on rebuild:
```
I: Using Apktool 2.2.4
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
[Fatal Error] :42:41: Element type "application" must be followed by either attribute specifications, ">" or "/>".
I: Checking whether resources has changed...
I: Building resources...
W: C:\Users\john\Desktop\com.spacosa.android.famy.global\AndroidManifest.xml:2: error: Error parsing XML: must not undeclare prefix
W:
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\john\AppData\Local\Temp\brut_util_Jar_3223905526957737575.tmp, p, --forced-package-id, 127, --min-sdk-version, 10, --target-sdk-version, 19, --version-code, 273, --version-name, 3.73, --no-version-vectors, -F, C:\Users\john\AppData\Local\Temp\APKTOOL590315764491848170.tmp, -0, arsc, -0, zip, -0, arsc, -I, C:\Users\john\AppData\Local\apktool\framework\1.apk, -S, C:\Users\john\Desktop\com.spacosa.android.famy.global\res, -M, C:\Users\john\Desktop\com.spacosa.android.famy.global\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:496)
        at brut.androlib.Androlib.buildResources(Androlib.java:430)
        at brut.androlib.Androlib.build(Androlib.java:329)
        at brut.androlib.Androlib.build(Androlib.java:267)
        at brut.apktool.Main.cmdBuild(Main.java:230)
        at brut.apktool.Main.main(Main.java:83)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\john\AppData\Local\Temp\brut_util_Jar_3223905526957737575.tmp, p, --forced-package-id, 127, --min-sdk-version, 10, --target-sdk-version, 19, --version-code, 273, --version-name, 3.73, --no-version-vectors, -F, C:\Users\john\AppData\Local\Temp\APKTOOL590315764491848170.tmp, -0, arsc, -0, zip, -0, arsc, -I, C:\Users\john\AppData\Local\apktool\framework\1.apk, -S, C:\Users\john\Desktop\com.spacosa.android.famy.global\res, -M, C:\Users\john\Desktop\com.spacosa.android.famy.global\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:441)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:482)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\john\AppData\Local\Temp\brut_util_Jar_3223905526957737575.tmp, p, --forced-package-id, 127, --min-sdk-version, 10, --target-sdk-version, 19, --version-code, 273, --version-name, 3.73, --no-version-vectors, -F, C:\Users\john\AppData\Local\Temp\APKTOOL590315764491848170.tmp, -0, arsc, -0, zip, -0, arsc, -I, C:\Users\john\AppData\Local\apktool\framework\1.apk, -S, C:\Users\john\Desktop\com.spacosa.android.famy.global\res, -M, C:\Users\john\Desktop\com.spacosa.android.famy.global\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:435)
        ... 6 more
```

### Steps to Reproduce
1. `apktool d com.spacosa.android.famy.global.apk`
2. `apktool b com.spacosa.android.famy.global`

### Frameworks
Not applicable

### APK
[com.spacosa.android.famy.global.zip](https://github.com/iBotPeaches/Apktool/files/1190562/com.spacosa.android.famy.global.zip)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Doesn't work
2. If you are trying to install a modified apk, did you resign it? --
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
Well this is something new.


```
aapt d xmltree application.apk AndroidManifest.xml
      E: application (line=54)
        A: Liapp_Empty_00:OYG0l(0x01010000)=@0x7f0b000b
```
When decoded
```
    <application OYG0l="@style/MyTheme" 3tAoS="@string/app_name" h8CpO="@drawable/famy_icon" 6Ollg="com.lockincomp.liapp.LiappCommon" mLSsB="locale" s5k5m="true">
```

I have no idea yet.

**Comment by iBotPeaches** [comment]
I'm not sure how Android parses this. Still unknown. Marking as bug though.
