### ISSUE TITLE
Resource identifier error "keyboardNavigationCluster" on build without changes to APK

### ISSUE THREAD

**Issue by seibelj** [iBotPeaches/Apktool#1579]
Might be related to https://stackoverflow.com/questions/45301203/no-resource-found-that-matches-the-given-name-attr-androidkeyboardnavigationc ? App installs and runs fine

### Information
1. **Apktool Version (`apktool -version`)** - 2.2.4
2. **Operating System (Mac, Linux, Windows)** - macOS
3. **APK From? (Playstore, ROM, Other)** - Other

### Stacktrace/Logcat

```
W: /path/to/decompiled/apk/res/layout-v26/abc_screen_toolbar.xml:5: error: No resource identifier found for attribute 'keyboardNavigationCluster' in package 'android'
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/7t/lmn4wjq90rl3v1xnpzd04fbw0000gn/T/brut_util_Jar_113986231575771865.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 25, --version-code, 4, --version-name, 1.0.3, --no-version-vectors, -F, /var/folders/7t/lmn4wjq90rl3v1xnpzd04fbw0000gn/T/APKTOOL1520297748076683938.tmp, -0, arsc, -0, arsc, -I, /path/to/Library/apktool/framework/1.apk, -S, /path/to/decompiled/apk/res, -M, /path/to/decompiled/apk/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:496)
	at brut.androlib.Androlib.buildResources(Androlib.java:430)
	at brut.androlib.Androlib.build(Androlib.java:329)
	at brut.androlib.Androlib.build(Androlib.java:267)
	at brut.apktool.Main.cmdBuild(Main.java:230)
	at brut.apktool.Main.main(Main.java:83)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/7t/lmn4wjq90rl3v1xnpzd04fbw0000gn/T/brut_util_Jar_113986231575771865.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 25, --version-code, 4, --version-name, 1.0.3, --no-version-vectors, -F, /var/folders/7t/lmn4wjq90rl3v1xnpzd04fbw0000gn/T/APKTOOL1520297748076683938.tmp, -0, arsc, -0, arsc, -I, /path/to/Library/apktool/framework/1.apk, -S, /path/to/decompiled/apk/res, -M, /path/to/decompiled/apk/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:441)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:482)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/7t/lmn4wjq90rl3v1xnpzd04fbw0000gn/T/brut_util_Jar_113986231575771865.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 25, --version-code, 4, --version-name, 1.0.3, --no-version-vectors, -F, /var/folders/7t/lmn4wjq90rl3v1xnpzd04fbw0000gn/T/APKTOOL1520297748076683938.tmp, -0, arsc, -0, arsc, -I, /path/to/Library/apktool/framework/1.apk, -S, /path/to/decompiled/apk/res, -M, /path/to/decompiled/apk/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:435)
	... 6 more

```

### Steps to Reproduce
1. `apktool d App.apk `
1. `apktool b App `

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? N/A
3. Are you using the latest apktool version? Yes

**Comment by seibelj** [comment]
Nevermind, had to remove the framework 1.apk file. Out of curiosity, is this regenerated from the android SDK on my path?

**Comment by iBotPeaches** [comment]
Generated from the internal framework inside apktool. It doesn't regenerate until its missing, which is why removing it forced the regeneration.

**Comment by AliGheibi** [comment]
How to fix it?
No resource identifier found for attribute 'keyboardNavigationCluster' in package 'android'

**Comment by ThePinkPanther** [comment]
Hey, so do you guys have a solution? How do I resolve this? I really need a fix for this

**Comment by iBotPeaches** [comment]
```
apktool empty-framework-dir --force
```

Retry.
