### ISSUE TITLE
"Case

### ISSUE THREAD

**Issue by evilwombat** [iBotPeaches/Apktool#1580]
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.4
2. **Operating System (Mac, Linux, Windows)** - Linux x86_64
3. **APK From? (Playstore, ROM, Other)** - Play Store

### Stacktrace/Logcat
When unpacking and repacking "Workplace By Facebook" (latest version as of 8/5/17) and making no other changes to the APK, I run into the following error.

Unpack command used:
apktool d -r -s $apk_file
apktool b $1 -o $directory

Dropping '-r' from the unpack command (to force a resource rebuild) resolves this, but I figure you might want to know anyway.

Thanks!
```
W: /home/steve/debullshification/other_apps/work-08052017/build/apk/res/-A.xml: error: File is case-insensitive equivalent to: /home/steve/debullshification/other_apps/work-08052017/build/apk/res/-a.xml
Exception in thread "main" brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_3502102805624701803.tmp, p, --no-version-vectors, -F, /home/steve/debullshification/other_apps/work-08052017-resigned.apk, -0, assets/ComponentScriptBundle.js.meta, -0, assets/InboxV2Query_MessengerInboxUnits_Nodes.fbs.md5, -0, txt, -0, js, -0, assets/js-modules/UNBUNDLE, -0, xzs, -0, webp, -0, fbfx, -0, json, -0, arsc, -A, /home/steve/debullshification/other_apps/work-08052017/assets, /home/steve/debullshification/other_apps/work-08052017/build/apk]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:441)
	at brut.androlib.Androlib.buildApk(Androlib.java:693)
	at brut.androlib.Androlib.build(Androlib.java:333)
	at brut.androlib.Androlib.build(Androlib.java:267)
	at brut.apktool.Main.cmdBuild(Main.java:230)
	at brut.apktool.Main.main(Main.java:83)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_3502102805624701803.tmp, p, --no-version-vectors, -F, /home/steve/debullshification/other_apps/work-08052017-resigned.apk, -0, assets/ComponentScriptBundle.js.meta, -0, assets/InboxV2Query_MessengerInboxUnits_Nodes.fbs.md5, -0, txt, -0, js, -0, assets/js-modules/UNBUNDLE, -0, xzs, -0, webp, -0, fbfx, -0, json, -0, arsc, -A, /home/steve/debullshification/other_apps/work-08052017/assets, /home/steve/debullshification/other_apps/work-08052017/build/apk]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:435)
	... 5 more
```

**Comment by iBotPeaches** [comment]
Latest version as of 8/5 must be this one - http://www.apkmirror.com/apk/facebook-2/work/work-133-0-0-19-83-release/

Leaving note for myself.

**Comment by iBotPeaches** [comment]
```
➜  Bug1580 apktool d work.apk -r -s
I: Using Apktool 2.2.4 on work.apk
I: Copying raw resources...
I: Copying raw classes.dex file...
I: Copying raw classes10.dex file...
I: Copying raw classes11.dex file...
I: Copying raw classes12.dex file...
I: Copying raw classes13.dex file...
I: Copying raw classes14.dex file...
I: Copying raw classes15.dex file...
I: Copying raw classes16.dex file...
I: Copying raw classes17.dex file...
I: Copying raw classes2.dex file...
I: Copying raw classes3.dex file...
I: Copying raw classes4.dex file...
I: Copying raw classes5.dex file...
I: Copying raw classes6.dex file...
I: Copying raw classes7.dex file...
I: Copying raw classes8.dex file...
I: Copying raw classes9.dex file...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1580 apktool b work
I: Using Apktool 2.2.4
I: Copying work classes.dex file...
I: Copying work classes8.dex file...
I: Copying work classes5.dex file...
I: Copying work classes6.dex file...
I: Copying work classes15.dex file...
I: Copying work classes17.dex file...
I: Copying work classes3.dex file...
I: Copying work classes11.dex file...
I: Copying work classes7.dex file...
I: Copying work classes10.dex file...
I: Copying work classes9.dex file...
I: Copying work classes13.dex file...
I: Copying work classes2.dex file...
I: Copying work classes12.dex file...
I: Copying work classes4.dex file...
I: Copying work classes16.dex file...
I: Copying work classes14.dex file...
I: Checking whether resources has changed...
I: Copying raw resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
➜  Bug1580 
```

I used both `-r & -s`. Did I do something wrong? I could not duplicate.

**Comment by evilwombat** [comment]
Hello. Sorry, behind on email. I am seeing this on the following APK:
https://www.dropbox.com/s/ot4x0w1pei0tfs9/work-08052017.apk?dl=0

This does not seem to match the most recently-available version on apkmirror from the given date. I'm confused as to where I actually got it from... too little sleep? Either way, there's a link if you're interested. If not, it's no problem. Thanks!

**Comment by iBotPeaches** [comment]
Just downloaded. I'll take another look when free.

**Comment by iBotPeaches** [comment]
Sorry for the delay.

```
➜  Bug1580 apktool d work-08052017.apk 
I: Using Apktool 2.2.5-0a1670-SNAPSHOT on work-08052017.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/connortumbleson/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes10.dex...
I: Baksmaling classes11.dex...
I: Baksmaling classes12.dex...
I: Baksmaling classes13.dex...
I: Baksmaling classes14.dex...
I: Baksmaling classes15.dex...
I: Baksmaling classes16.dex...
I: Baksmaling classes17.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes4.dex...
I: Baksmaling classes5.dex...
I: Baksmaling classes6.dex...
I: Baksmaling classes7.dex...
I: Baksmaling classes8.dex...
I: Baksmaling classes9.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1580 apktool b work-08052017
I: Using Apktool 2.2.5-0a1670-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes10 folder into classes10.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes11 folder into classes11.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes12 folder into classes12.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes13 folder into classes13.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes14 folder into classes14.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes15 folder into classes15.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes16 folder into classes16.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes17 folder into classes17.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes4 folder into classes4.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes5 folder into classes5.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes6 folder into classes6.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes7 folder into classes7.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes8 folder into classes8.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes9 folder into classes9.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
➜  Bug1580 
```

Couldn't duplicate even with that above linked application.
