### ISSUE TITLE
can't recompile a single apk, it always shows the same error

### ISSUE THREAD

**Issue by anilyadav851996** [iBotPeaches/Apktool#1583]
```
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec: [/data/data/per.pqy.apktool/apktool/openjdk/bin/aapt5.1, p, --min-sdk-version, 10, --target-sdk-version, 21, --version-code, 20, --version-name, 1.2.11, --no-version-vectors, -F, /data/data/per.pqy.apktool/APKTOOL6364707453993546091.tmp, -0, arsc, -0, arsc, -I, /data/data/per.pqy.apktool/1.apk, -S, /storage/emulated/0/backups/apps/Internet123_src/res, -M, /storage/emulated/0/backups/apps/Internet123_src/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:496)
	at brut.androlib.Androlib.buildResources(Androlib.java:430)
	at brut.androlib.Androlib.build(Androlib.java:329)
	at brut.androlib.Androlib.build(Androlib.java:267)
	at brut.apktool.Main.cmdBuild(Main.java:230)
	at brut.apktool.Main.main(Main.java:83)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec: [/data/data/per.pqy.apktool/apktool/openjdk/bin/aapt5.1, p, --min-sdk-version, 10, --target-sdk-version, 21, --version-code, 20, --version-name, 1.2.11, --no-version-vectors, -F, /data/data/per.pqy.apktool/APKTOOL6364707453993546091.tmp, -0, arsc, -0, arsc, -I, /data/data/per.pqy.apktool/1.apk, -S, /storage/emulated/0/backups/apps/Internet123_src/res, -M, /storage/emulated/0/backups/apps/Internet123_src/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:441)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:482)
	... 5 more
Caused by: brut.common.BrutException: could not exec: [/data/data/per.pqy.apktool/apktool/openjdk/bin/aapt5.1, p, --min-sdk-version, 10, --target-sdk-version, 21, --version-code, 20, --version-name, 1.2.11, --no-version-vectors, -F, /data/data/per.pqy.apktool/APKTOOL6364707453993546091.tmp, -0, arsc, -0, arsc, -I, /data/data/per.pqy.apktool/1.apk, -S, /storage/emulated/0/backups/apps/Internet123_src/res, -M, /storage/emulated/0/backups/apps/Internet123_src/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:97)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:435)
	... 6 more
Caused by: java.io.IOException: Cannot run program "/data/data/per.pqy.apktool/apktool/openjdk/bin/aapt5.1": error=13, Permission denied
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
	at brut.util.OS.exec(OS.java:90)
	... 7 more
Caused by: java.io.IOException: error=13, Permission denied
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:186)
	at java.lang.ProcessImpl.start(ProcessImpl.java:130)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
	... 8 more
I: Using Apktool 2.2.4
I: Smaling smali folder into classes.dex...
I: Building resources...
```

**Comment by iBotPeaches** [comment]
```
Caused by: java.io.IOException: Cannot run program "/data/data/per.pqy.apktool/apktool/openjdk/bin/aapt5.1": error=13, Permission denied
```

Apktool does not have permission to execute the aapt binary it was passed. It looks like you used the `-a` parameter, but provided a file that doesn't have executable permissions. Closing this as it looks like support instead of a bug report.
