### ISSUE TITLE
W: max res 23, skipping values-v24

### ISSUE THREAD

**Issue by bjethwan** [iBotPeaches/Apktool#1584]
### Information
1. **Apktool Version (`apktool -version`)** -Apktool 2.2.4
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Kony

### Stacktrace/Logcat

```
C:\>apktool -m b luavmandroid
I: Using Apktool 2.2.4
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: max res 23, skipping values-v24
W: max res 23, skipping values-v25
W: C:\Users\KH1783\Desktop\features implemented\failing to wrap\haidar\luavmandroid\res\values\public.xml:1026: error: Public symbol style/Platform.V25.AppCompat declared here is not defined.
W: C:\Users\KH1783\Desktop\features implemented\failing to wrap\haidar\luavmandroid\res\values\public.xml:1027: error: Public symbol style/Platform.V25.AppCompat.Light declared here is not defined.
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\KH1783\AppData\Local\Temp\brut_util_Jar_3394173615250981609.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 22, --max-sdk-version, 23, --max-res-version, 23, --version-code, 1, --version-name, 1.0.0, --no-version-vectors, -F, C:\Users\KH1783\AppData\Local\Temp\APKTOOL5920739064829364487.tmp, -0, arsc, -0, arsc, -I, C:\Users\KH1783\AppData\Local\apktool\framework\1.apk, -S, C:\Users\KH1783\Desktop\features implemented\failing to wrap\haidar\luavmandroid\res, -M, C:\Users\KH1783\Desktop\features implemented\failing to wrap\haidar\luavmandroid\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:496)
        at brut.androlib.Androlib.buildResources(Androlib.java:430)
        at brut.androlib.Androlib.build(Androlib.java:329)
        at brut.androlib.Androlib.build(Androlib.java:267)
        at brut.apktool.Main.cmdBuild(Main.java:230)
        at brut.apktool.Main.main(Main.java:83)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\KH1783\AppData\Local\Temp\brut_util_Jar_3394173615250981609.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 22, --max-sdk-version, 23, --max-res-version, 23, --version-code, 1, --version-name, 1.0.0, --no-version-vectors, -F, C:\Users\KH1783\AppData\Local\Temp\APKTOOL5920739064829364487.tmp, -0, arsc, -0, arsc, -I, C:\Users\KH1783\AppData\Local\apktool\framework\1.apk, -S, C:\Users\KH1783\Desktop\features implemented\failing to wrap\haidar\luavmandroid\res, -M, C:\Users\KH1783\Desktop\features implemented\failing to wrap\haidar\luavmandroid\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:441)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:482)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\KH1783\AppData\Local\Temp\brut_util_Jar_3394173615250981609.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 22, --max-sdk-version, 23, --max-res-version, 23, --version-code, 1, --version-name, 1.0.0, --no-version-vectors, -F, C:\Users\KH1783\AppData\Local\Temp\APKTOOL5920739064829364487.tmp, -0, arsc, -0, arsc, -I, C:\Users\KH1783\AppData\Local\apktool\framework\1.apk, -S, C:\Users\KH1783\Desktop\features implemented\failing to wrap\haidar\luavmandroid\res, -M, C:\Users\KH1783\Desktop\features implemented\failing to wrap\haidar\luavmandroid\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:435)
        ... 6 more
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by iBotPeaches** [comment]
This is intended - https://github.com/iBotPeaches/Apktool/blob/master/brut.apktool/apktool-lib/src/main/java/brut/androlib/res/AndrolibResources.java#L379

If you pass a `--max-sdk-version`, it will also use `--max-res-version`. 

https://developer.android.com/guide/topics/manifest/uses-sdk-element.html
> Warning: Declaring this attribute is not recommended. First, there is no need to set the attribute as means of blocking deployment of your application onto new versions of the Android platform as they are released. By design, new versions of the platform are fully backward-compatible. Your application should work properly on new versions, provided it uses only standard APIs and follows development best practices. Second, note that in some cases, declaring the attribute can result in your application being removed from users' devices after a system update to a higher API Level. Most devices on which your application is likely to be installed will receive periodic system updates over the air, so you should consider their effect on your application before setting this attribute.

Your problem is with the side effect of using `--max-sdk-version`. This is not a bug.

**Comment by bjethwan** [comment]
How to fix this? Is there a workaround?

I tried below but it failed.
apktool b --max-sdk-version 25 luavmandroid
Unrecognized option: --max-sdk-version

**Comment by bjethwan** [comment]
There should be some way in the command line to override that???

**Comment by iBotPeaches** [comment]
> How to fix this? Is there a workaround?
You can edit the source of apktool, remove the check, rebuild it and use that version.

> There should be some way in the command line to override that???
No there isn't.

**Comment by zicofish** [comment]
Got this error in  apktool 2.4.1.  Simply changing the `apktool.yml` file solves the problem:

From:
```
sdkInfo:
  minSdkVersion: '14'
  targetSdkVersion: '25'
  maxSdkVersion: '23'
```

To:
```
sdkInfo:
  minSdkVersion: '14'
  targetSdkVersion: '25'
  maxSdkVersion: '25'
```

Not sure why is this not mentioned as a solution. But it works for me: I can repack the apk and run it on a device.
