### ISSUE TITLE
brut.androlib.AndrolibException when recompiling apk

### ISSUE THREAD

**Issue by Dylan-halls** [iBotPeaches/Apktool#1591]
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.4
2. **Operating System (Mac, Linux, Windows)** - linux ubuntu
3. **APK From? (Playstore, ROM, Other)** - Playstore (youtube)

### Stacktrace/Logcat

```
I: Using Apktool 2.2.4
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: /home/dylan/Desktop/base/res/xml-v22/main_shortcuts.xml:4: error: No resource identifier found for attribute 'shortcutId' in package 'android'
W: 
W: /home/dylan/Desktop/base/res/xml-v22/main_shortcuts.xml:4: error: No resource identifier found for attribute 'shortcutShortLabel' in package 'android'
W: 
W: /home/dylan/Desktop/base/res/xml-v22/main_shortcuts.xml:7: error: No resource identifier found for attribute 'shortcutId' in package 'android'
W: 
W: /home/dylan/Desktop/base/res/xml-v22/main_shortcuts.xml:7: error: No resource identifier found for attribute 'shortcutShortLabel' in package 'android'
W: 
W: /home/dylan/Desktop/base/res/xml-v22/main_shortcuts.xml:10: error: No resource identifier found for attribute 'shortcutId' in package 'android'
W: 
W: /home/dylan/Desktop/base/res/xml-v22/main_shortcuts.xml:10: error: No resource identifier found for attribute 'shortcutShortLabel' in package 'android'
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_2155344058740848025.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 25, --version-code, 1229573400, --version-name, 12.29.57, --no-version-vectors, -F, /tmp/APKTOOL7532305205326095753.tmp, -0, arsc, -0, webp, -0, arsc, -I, /home/dylan/.local/share/apktool/framework/1.apk, -S, /home/dylan/Desktop/base/res, -M, /home/dylan/Desktop/base/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:496)
	at brut.androlib.Androlib.buildResources(Androlib.java:430)
	at brut.androlib.Androlib.build(Androlib.java:329)
	at brut.androlib.Androlib.build(Androlib.java:267)
	at brut.apktool.Main.cmdBuild(Main.java:230)
	at brut.apktool.Main.main(Main.java:83)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_2155344058740848025.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 25, --version-code, 1229573400, --version-name, 12.29.57, --no-version-vectors, -F, /tmp/APKTOOL7532305205326095753.tmp, -0, arsc, -0, webp, -0, arsc, -I, /home/dylan/.local/share/apktool/framework/1.apk, -S, /home/dylan/Desktop/base/res, -M, /home/dylan/Desktop/base/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:441)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:482)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_2155344058740848025.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 25, --version-code, 1229573400, --version-name, 12.29.57, --no-version-vectors, -F, /tmp/APKTOOL7532305205326095753.tmp, -0, arsc, -0, webp, -0, arsc, -I, /home/dylan/.local/share/apktool/framework/1.apk, -S, /home/dylan/Desktop/base/res, -M, /home/dylan/Desktop/base/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:435)
	... 6 more

```

### Steps to Reproduce
1. `java -jar apktool_2.2.4.jar b base `

I decompiled the .apk fine and in work perfectly then WITHOUT changing anything I tried to recompile in with the upove command and got the upove error.

**Comment by iBotPeaches** [comment]
```
apktool empty-framework-dir --force
```

Then try again, the 2.2.4 framework internally has these resources.
