### ISSUE TITLE
ception in thread "main" brut.androlib.AndrolibException

### ISSUE THREAD

**Issue by ocaner95** [iBotPeaches/Apktool#1596]
```
I: Using Apktool 2.2.4
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: /root/Desktop/newf/res/drawable-anydpi-v21/ic_fingerprint_error.xml:4: error: No resource identifier found for attribute 'fillColor' in package 'android'
W: 
W: /root/Desktop/newf/res/drawable-anydpi-v21/ic_fingerprint_error.xml:5: error: No resource identifier found for attribute 'fillColor' in package 'android'
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_7872174393451599343.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 25, --version-code, 104394, --version-name, T4.2.1-M10.0, --no-version-vectors, -F, /tmp/APKTOOL3015745064146101499.tmp, -0, arsc, -0, dict, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/Desktop/newf/res, -M, /root/Desktop/newf/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:496)
	at brut.androlib.Androlib.buildResources(Androlib.java:430)
	at brut.androlib.Androlib.build(Androlib.java:329)
	at brut.androlib.Androlib.build(Androlib.java:267)
	at brut.apktool.Main.cmdBuild(Main.java:230)
	at brut.apktool.Main.main(Main.java:83)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_7872174393451599343.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 25, --version-code, 104394, --version-name, T4.2.1-M10.0, --no-version-vectors, -F, /tmp/APKTOOL3015745064146101499.tmp, -0, arsc, -0, dict, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/Desktop/newf/res, -M, /root/Desktop/newf/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:441)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:482)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_7872174393451599343.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 25, --version-code, 104394, --version-name, T4.2.1-M10.0, --no-version-vectors, -F, /tmp/APKTOOL3015745064146101499.tmp, -0, arsc, -0, dict, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/Desktop/newf/res, -M, /root/Desktop/newf/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:435)
	... 6 more
```

i tried so solve mi issue by searching but i couldnt pleas help me

**Comment by iBotPeaches** [comment]
This is a valid attribute - https://developer.android.com/reference/android/graphics/drawable/VectorDrawable.html

Please run `apktool empty-framework-dir --force` and try again. This is not a bug.

**Comment by ocaner95** [comment]
Actually in some apps i can build the app with out any errors but in somes i have get  the above error
