### ISSUE TITLE
Error while recompiling APK

### ISSUE THREAD

**Issue by TheUllas** [iBotPeaches/Apktool#1600]
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.4
2. **Operating System (Mac, Linux, Windows)** - Mac
3. **APK From? (Playstore, ROM, Other)** - Other

### Stacktrace/Logcat

```
Last login: Fri Aug 25 14:23:54 on ttys002
Blah_MacBookPro:mdx Blah$ apktool d ~/Desktop/Apps/kms.apk  -o decompiledkms
I: Using Apktool 2.2.4 on kms.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/Blah/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes4.dex...
I: Baksmaling classes5.dex...
I: Baksmaling classes7.dex...
I: Baksmaling classes9.dex...
I: Baksmaling classes10.dex...
I: Baksmaling classes11.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
Blah_MacBookPro:mdx Blah$ apktool b decompiledkms -o recompiledkms.apk
I: Using Apktool 2.2.4
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes10 folder into classes10.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes11 folder into classes11.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes4 folder into classes4.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes5 folder into classes5.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes7 folder into classes7.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes9 folder into classes9.dex...
I: Checking whether resources has changed...
I: Building resources...
W: /Users/Blah/Git/decompiledkms/res/values-v23/styles.xml:3: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/WindowTitle'.
W: 
W: /Users/Blah/Git/decompiledkms/res/values-v23/styles.xml:6: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/WindowTitleBackground'.
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/t7/fs5y51gx597ff3wqsq5zq3v80000gn/T/brut_util_Jar_7951244023472414677.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 23, --version-code, 141, --version-name, 11.11.4.761, --no-version-vectors, -F, /var/folders/t7/fs5y51gx597ff3wqsq5zq3v80000gn/T/APKTOOL6465967518357879379.tmp, -0, arsc, -0, arsc, -I, /Users/Blah/Library/apktool/framework/1.apk, -S, /Users/Blah/Git/decompiledkms/res, -M, /Users/Blah/Git/decompiledkms/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:496)
	at brut.androlib.Androlib.buildResources(Androlib.java:430)
	at brut.androlib.Androlib.build(Androlib.java:329)
	at brut.androlib.Androlib.build(Androlib.java:267)
	at brut.apktool.Main.cmdBuild(Main.java:230)
	at brut.apktool.Main.main(Main.java:83)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/t7/fs5y51gx597ff3wqsq5zq3v80000gn/T/brut_util_Jar_7951244023472414677.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 23, --version-code, 141, --version-name, 11.11.4.761, --no-version-vectors, -F, /var/folders/t7/fs5y51gx597ff3wqsq5zq3v80000gn/T/APKTOOL6465967518357879379.tmp, -0, arsc, -0, arsc, -I, /Users/Blah/Library/apktool/framework/1.apk, -S, /Users/Blah/Git/decompiledkms/res, -M, /Users/Blah/Git/decompiledkms/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:441)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:482)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/t7/fs5y51gx597ff3wqsq5zq3v80000gn/T/brut_util_Jar_7951244023472414677.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 23, --version-code, 141, --version-name, 11.11.4.761, --no-version-vectors, -F, /var/folders/t7/fs5y51gx597ff3wqsq5zq3v80000gn/T/APKTOOL6465967518357879379.tmp, -0, arsc, -0, arsc, -I, /Users/Blah/Library/apktool/framework/1.apk, -S, /Users/Blah/mdx/decompiledkms/res, -M, /Users/Blah/Git/decompiledkms/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:435)
	... 6 more
Blah_MacBookPro:mdx Blah$ 



```

### Steps to Reproduce
1. apktool d <apk> -o <folder>
2. apktool b <folder> -o <newapk>

Step 2 fails

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
Can't.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Couldnt recompile the apk itself
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
This is not Apktool's fault. This application is using private platform resources, which cannot be confirmed to be there in future platforms. Old versions of aapt didn't enforce this, now it does.

You have to copy those resources into your own local styles file and reference them that way.

https://stackoverflow.com/a/20298168/455008

This should fix your first error for example:

```
<style name="WindowTitle">
        <item name="android:singleLine">true</item>
        <item name="android:textAppearance">@style/TextAppearance.WindowTitle</item>
        <item name="android:shadowColor">#BB000000</item>
        <item name="android:shadowRadius">2.75</item>
</style>
```
