### ISSUE TITLE
AndroidManifest.xml No resource identifier found for attribute 'protect' in package 'android' W

### ISSUE THREAD

**Issue by adrean1980** [iBotPeaches/Apktool#1606]
### Information
1. **Apktool Version (`apktool - 2.2.4`)** -
2. **Operating System (Mac)** -
3. **APK From? (Playstore)** -

hello, when i try recompile i get this error, is there any solution to fix it, thanks so much in advance

### Stacktrace/Logcat
```
AndroidManifest.xml:3: error: No resource identifier found for attribute 'protect' in package 'android'
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/3w/0d7ml5q54qb98x9g2lxvsxfm0000gn/T/brut_util_Jar_8993495130380390225.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 24, --version-code, 1000004, --version-name, 4.1.0, --no-version-vectors, -F, /var/folders/3w/0d7ml5q54qb98x9g2lxvsxfm0000gn/T/APKTOOL3556102301868877034.tmp, -0, arsc, -0, appkey, -0, assets/bin/Data/PlayerConnectionConfigFile, -0, arsc, -I, /Users/----/Library/apktool/framework/1.apk, -S, /Users/----/bin/MyAPK/res, -M, /Users/----/bin/MyAPK/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:496)
	at brut.androlib.Androlib.buildResources(Androlib.java:430)
	at brut.androlib.Androlib.build(Androlib.java:329)
	at brut.androlib.Androlib.build(Androlib.java:267)
	at brut.apktool.Main.cmdBuild(Main.java:230)
	at brut.apktool.Main.main(Main.java:83)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/3w/0d7ml5q54qb98x9g2lxvsxfm0000gn/T/brut_util_Jar_8993495130380390225.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 24, --version-code, 1000004, --version-name, 4.1.0, --no-version-vectors, -F, /var/folders/3w/0d7ml5q54qb98x9g2lxvsxfm0000gn/T/APKTOOL3556102301868877034.tmp, -0, arsc, -0, appkey, -0, assets/bin/Data/PlayerConnectionConfigFile, -0, arsc, -I, /Users/----/Library/apktool/framework/1.apk, -S, /Users/----/bin/MyAPK/res, -M, /Users/----/bin/MyAPK/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:441)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:482)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/3w/0d7ml5q54qb98x9g2lxvsxfm0000gn/T/brut_util_Jar_8993495130380390225.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 24, --version-code, 1000004, --version-name, 4.1.0, --no-version-vectors, -F, /var/folders/3w/0d7ml5q54qb98x9g2lxvsxfm0000gn/T/APKTOOL3556102301868877034.tmp, -0, arsc, -0, appkey, -0, assets/bin/Data/PlayerConnectionConfigFile, -0, arsc, -I, /Users/----/Library/apktool/framework/1.apk, -S, /Users/----/bin/MyAPK/res, -M, /Users/----/bin/MyAPK/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:435)
	... 6 more
```
### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
yes
2. If you are trying to install a modified apk, did you resign it?
no
3. Are you using the latest apktool version?
yes

**Comment by iBotPeaches** [comment]
Thanks for the report! Unfortunately there isn't enough information for me to triage this issue properly. Please be sure to either link/upload the affected apk. I can reopen this ticket if that is provided.

If this isn't possible. Please wait for the 2.3.0 release and do `apktool empty-framework-dir` and try again. 2.3.0 is expected to be released this week.
