### ISSUE TITLE
No support for 4 non-positional attributes

### ISSUE THREAD

**Issue by Maxhyt** [iBotPeaches/Apktool#1611]
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.4
2. **Operating System (Mac, Linux, Windows)** - Windows 10 Insider Preview
3. **APK From? (Playstore, ROM, Other)** - ApkMirror

### Stacktrace/Logcat

```
I: Using Apktool 2.2.4
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: D:\Program Files\Android\Mess\res\values\plurals.xml:352: error: Multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?
W:
W: D:\Program Files\Android\Mess\res\values\plurals.xml:352: error: Found tag </item> where </plurals> is expected
W:
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Maxhyt\AppData\Local\Temp\brut_util_Jar_92917592835360541.tmp, p, --forced-package-id, 127, --min-sdk-version, 23, --target-sdk-version, 23, --version-code, 70896137, --version-name, 134.0.0.18.91, --no-version-vectors, -F, C:\Users\Maxhyt\AppData\Local\Temp\APKTOOL3290510466342588556.tmp, -0, arsc, -0, assets/InboxV2Query_MessengerInboxUnits_Nodes.fbs.md5, -0, assets/MessengerBundle.js.meta, -0, xzs, -0, json, -0, bks, -0, arsc, -I, C:\Users\Maxhyt\AppData\Local\apktool\framework\1.apk, -S, D:\Program Files\Android\Mess\res, -M, D:\Program Files\Android\Mess\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:496)
        at brut.androlib.Androlib.buildResources(Androlib.java:430)
        at brut.androlib.Androlib.build(Androlib.java:329)
        at brut.androlib.Androlib.build(Androlib.java:267)
        at brut.apktool.Main.cmdBuild(Main.java:230)
        at brut.apktool.Main.main(Main.java:83)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Maxhyt\AppData\Local\Temp\brut_util_Jar_92917592835360541.tmp, p, --forced-package-id, 127, --min-sdk-version, 23, --target-sdk-version, 23, --version-code, 70896137, --version-name, 134.0.0.18.91, --no-version-vectors, -F, C:\Users\Maxhyt\AppData\Local\Temp\APKTOOL3290510466342588556.tmp, -0, arsc, -0, assets/InboxV2Query_MessengerInboxUnits_Nodes.fbs.md5, -0, assets/MessengerBundle.js.meta, -0, xzs, -0, json, -0, bks, -0, arsc, -I, C:\Users\Maxhyt\AppData\Local\apktool\framework\1.apk, -S, D:\Program Files\Android\Mess\res, -M, D:\Program Files\Android\Mess\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:441)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:482)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Maxhyt\AppData\Local\Temp\brut_util_Jar_92917592835360541.tmp, p, --forced-package-id, 127, --min-sdk-version, 23, --target-sdk-version, 23, --version-code, 70896137, --version-name, 134.0.0.18.91, --no-version-vectors, -F, C:\Users\Maxhyt\AppData\Local\Temp\APKTOOL3290510466342588556.tmp, -0, arsc, -0, assets/InboxV2Query_MessengerInboxUnits_Nodes.fbs.md5, -0, assets/MessengerBundle.js.meta, -0, xzs, -0, json, -0, bks, -0, arsc, -I, C:\Users\Maxhyt\AppData\Local\apktool\framework\1.apk, -S, D:\Program Files\Android\Mess\res, -M, D:\Program Files\Android\Mess\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:435)
        ... 6 more
```

### Steps to Reproduce
1. apktool d Mess.apk -o Mess
2. apktool b Mess -o ./Mess.apk

### Frameworks

[framework-res.zip](https://github.com/iBotPeaches/Apktool/files/1289377/framework-res.zip)

### APK
https://www.apkmirror.com/wp-content/themes/APKMirror/download.php?id=268696

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? No
2. If you are trying to install a modified apk, did you resign it? Yes
3. Are you using the latest apktool version? Yes

I have managed to fix it according to your help in #1405 .

**Comment by iBotPeaches** [comment]
Thanks for the report. This has been fixed.
