### ISSUE TITLE
 No resource found that matches the given name 

### ISSUE THREAD

**Issue by CunningLogic** [iBotPeaches/Apktool#1616]
### Information
1. **Apktool Version (`apktool -version`)** -Apktool v2.2.4 
2. **Operating System (Mac, Linux, Windows)** - osx 10.11.6
3. **APK From? (Playstore, ROM, Other)** -simple helloworld, see attached

### Stacktrace/Logcat
```
Jons-Mac-Pro:test jcase$ apktool d hello.apk 
I: Using Apktool 2.2.4 on hello.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/jcase/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
Jons-Mac-Pro:test jcase$ apktool b hello
I: Using Apktool 2.2.4
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: /Users/jcase/android/working/Concealer/test/hello/res/values-v24/styles.xml:7: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Animation.OptionsPanel'.
W: 
W: /Users/jcase/android/working/Concealer/test/hello/res/values-v24/styles.xml:8: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Animation.LockScreen'.
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/j6/hczx8zx139s9cbc0s7nq8shc0000gn/T/brut_util_Jar_8698522024412882631.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 25, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /var/folders/j6/hczx8zx139s9cbc0s7nq8shc0000gn/T/APKTOOL7490291614340390359.tmp, -0, arsc, -0, arsc, -I, /Users/jcase/Library/apktool/framework/1.apk, -S, /Users/jcase/android/working/Concealer/test/hello/res, -M, /Users/jcase/android/working/Concealer/test/hello/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:496)
	at brut.androlib.Androlib.buildResources(Androlib.java:430)
	at brut.androlib.Androlib.build(Androlib.java:329)
	at brut.androlib.Androlib.build(Androlib.java:267)
	at brut.apktool.Main.cmdBuild(Main.java:230)
	at brut.apktool.Main.main(Main.java:83)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/j6/hczx8zx139s9cbc0s7nq8shc0000gn/T/brut_util_Jar_8698522024412882631.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 25, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /var/folders/j6/hczx8zx139s9cbc0s7nq8shc0000gn/T/APKTOOL7490291614340390359.tmp, -0, arsc, -0, arsc, -I, /Users/jcase/Library/apktool/framework/1.apk, -S, /Users/jcase/android/working/Concealer/test/hello/res, -M, /Users/jcase/android/working/Concealer/test/hello/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:441)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:482)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/j6/hczx8zx139s9cbc0s7nq8shc0000gn/T/brut_util_Jar_8698522024412882631.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 25, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /var/folders/j6/hczx8zx139s9cbc0s7nq8shc0000gn/T/APKTOOL7490291614340390359.tmp, -0, arsc, -0, arsc, -I, /Users/jcase/Library/apktool/framework/1.apk, -S, /Users/jcase/android/working/Concealer/test/hello/res, -M, /Users/jcase/android/working/Concealer/test/hello/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:435)
	... 6 more
Jons-Mac-Pro:test jcase$ 
```
[hello.zip](https://github.com/iBotPeaches/Apktool/files/1315167/hello.zip)

### Steps to Reproduce
1. `apktool d hello.apk`
2. `apktool b hello`

### APK
Attached

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? n/a
3. Are you using the latest apktool version? i think so, 2.2.4

**Comment by iBotPeaches** [comment]
```
➜  Bug1616 apktool d hello.apk 
I: Using Apktool 2.2.4-98138b-SNAPSHOT on hello.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/connortumbleson/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1616 apktool b hello
I: Using Apktool 2.2.4-98138b-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Building apk file...
I: Copying unknown files/dir...
➜  Bug1616 
```

Give `apktool empty-framework-dir` a shot. I don't have a reliable way to detect framework version installed yet.

**Comment by strazzere** [comment]
Worked for me as expected FWIW;

```
rigby:Apktool diff$ java -jar ./brut.apktool/apktool-cli/build/libs/apktool-cli-all.jar d hello.zip 
I: Using Apktool 2.2.5-d00e60-SNAPSHOT on hello.zip
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
S: WARNING: Could not write to (/Users/diff/Library/apktool/framework), using /var/folders/29/g4wdlpzs17df5v8jbp88mnnc0000gn/T/ instead...
S: Please be aware this is a volatile directory and frameworks could go missing, please utilize --frame-path if the default storage directory is unavailable
I: Loading resource table from file: /var/folders/29/g4wdlpzs17df5v8jbp88mnnc0000gn/T/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
rigby:Apktool diff$ ls -l
total 2920
-rw-r--r--  1 diff  staff      513 Mar  6  2017 CONTRIBUTORS.md
-rw-r--r--  1 diff  staff    11236 Sep 19 10:15 INTERNAL.md
-rw-r--r--  1 diff  staff    11627 Mar  6  2017 LICENSE
-rw-r--r--  1 diff  staff     2564 Sep 19 10:15 README.md
drwxr-xr-x  4 diff  staff      136 Mar  6  2017 brut.apktool
drwxr-xr-x  5 diff  staff      170 Sep 19 10:22 brut.j.common
drwxr-xr-x  5 diff  staff      170 Sep 19 10:23 brut.j.dir
drwxr-xr-x  5 diff  staff      170 Sep 19 10:23 brut.j.util
-rw-r--r--  1 diff  staff     4267 Sep 19 10:15 build.gradle
drwxr-xr-x  2 diff  staff       68 Sep 19 10:23 build.gradle.out
drwxr-xr-x  4 diff  staff      136 Sep 19 10:15 gradle
-rwxr-xr-x  1 diff  staff     5296 Sep 19 10:15 gradlew
-rw-r--r--  1 diff  staff     2260 Sep 19 10:15 gradlew.bat
-rw-r--r--@ 1 diff  staff  1434381 Sep 19 10:15 hello.zip
drwxr-xr-x  7 diff  staff      238 Sep 19 10:23 hello.zip.out
drwxr-xr-x  6 diff  staff      204 Mar  6  2017 scripts
-rw-r--r--  1 diff  staff      140 Mar  6  2017 settings.gradle
drwxr-xr-x@ 7 diff  staff      238 Sep 19 10:17 test
rigby:Apktool diff$ java -jar ./brut.apktool/apktool-cli/build/libs/apktool-cli-all.jar b hello.zip.out/ -o derp.apk
I: Using Apktool 2.2.5-d00e60-SNAPSHOT
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building apk file...
I: Copying unknown files/dir...
rigby:Apktool diff$ ls -l
total 5544
-rw-r--r--  1 diff  staff      513 Mar  6  2017 CONTRIBUTORS.md
-rw-r--r--  1 diff  staff    11236 Sep 19 10:15 INTERNAL.md
-rw-r--r--  1 diff  staff    11627 Mar  6  2017 LICENSE
-rw-r--r--  1 diff  staff     2564 Sep 19 10:15 README.md
drwxr-xr-x  4 diff  staff      136 Mar  6  2017 brut.apktool
drwxr-xr-x  5 diff  staff      170 Sep 19 10:22 brut.j.common
drwxr-xr-x  5 diff  staff      170 Sep 19 10:23 brut.j.dir
drwxr-xr-x  5 diff  staff      170 Sep 19 10:23 brut.j.util
-rw-r--r--  1 diff  staff     4267 Sep 19 10:15 build.gradle
drwxr-xr-x  2 diff  staff       68 Sep 19 10:23 build.gradle.out
-rw-r--r--  1 diff  staff  1342082 Sep 19 10:26 derp.apk
drwxr-xr-x  4 diff  staff      136 Sep 19 10:15 gradle
-rwxr-xr-x  1 diff  staff     5296 Sep 19 10:15 gradlew
-rw-r--r--  1 diff  staff     2260 Sep 19 10:15 gradlew.bat
-rw-r--r--@ 1 diff  staff  1434381 Sep 19 10:15 hello.zip
drwxr-xr-x  9 diff  staff      306 Sep 19 10:26 hello.zip.out
drwxr-xr-x  6 diff  staff      204 Mar  6  2017 scripts
-rw-r--r--  1 diff  staff      140 Mar  6  2017 settings.gradle
drwxr-xr-x@ 7 diff  staff      238 Sep 19 10:17 test
```

This was with a fresh pull and build from ~minute ago.
