### ISSUE TITLE
AndrolibException: cannot repackage an app

### ISSUE THREAD

**Issue by DmitriyZaitsev** [iBotPeaches/Apktool#1617]
### Information
1. **Apktool Version** - 2.2.4, 2.3.0
2. **Operating System** - Mac
3. **APK From?** - Playstore

### Stacktrace/Logcat

```
W: /Users/username/path/to/my/apk/res/layout-v26/abc_screen_toolbar.xml:5: error: No resource identifier found for attribute 'keyboardNavigationCluster' in package 'android'
W:
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/gm/7k064gd96rz4_3jxc_swqbzm0000gq/T/brut_util_Jar_2805966671423169213.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 26, --version-code, 5, --version-name, 1.5, --no-version-vectors, -F, /var/folders/gm/7k064gd96rz4_3jxc_swqbzm0000gq/T/APKTOOL8513813933633188075.tmp, -0, arsc, -0, arsc, -I, /Users/username/Library/apktool/framework/1.apk, -S, /Users/username/path/to/my/apk/res, -M, /Users/username/path/to/my/apk/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:485)
	at brut.androlib.Androlib.buildResources(Androlib.java:419)
	at brut.androlib.Androlib.build(Androlib.java:318)
	at brut.androlib.Androlib.build(Androlib.java:270)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:75)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/gm/7k064gd96rz4_3jxc_swqbzm0000gq/T/brut_util_Jar_2805966671423169213.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 26, --version-code, 5, --version-name, 1.5, --no-version-vectors, -F, /var/folders/gm/7k064gd96rz4_3jxc_swqbzm0000gq/T/APKTOOL8513813933633188075.tmp, -0, arsc, -0, arsc, -I, /Users/username/Library/apktool/framework/1.apk, -S, /Users/username/path/to/my/apk/res, -M, /Users/username/path/to/my/apk/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:454)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:471)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/gm/7k064gd96rz4_3jxc_swqbzm0000gq/T/brut_util_Jar_2805966671423169213.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 26, --version-code, 5, --version-name, 1.5, --no-version-vectors, -F, /var/folders/gm/7k064gd96rz4_3jxc_swqbzm0000gq/T/APKTOOL8513813933633188075.tmp, -0, arsc, -0, arsc, -I, /Users/username/Library/apktool/framework/1.apk, -S, /Users/username/path/to/my/apk/res, -M, /Users/username/path/to/my/apk/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:448)
	... 6 more
```

### Steps to Reproduce
1. `$ apktool d my.apk `
2. `$ apktool b my`

### APK
cannot be shared

**Comment by iBotPeaches** [comment]
`keyboardNavigationCluster` is an API 26 property on the View object. Added in Android Oreo. Try running `apktool empty-framework-dir` and make sure you re-decode/rebuild the application.
