### ISSUE TITLE
Failure rebuilding Facebook due to duplicate property?

### ISSUE THREAD

**Issue by evilwombat** [iBotPeaches/Apktool#1618]
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.0
2. **Operating System (Mac, Linux, Windows)** - Linux x86_64
3. **APK From? (Playstore, ROM, Other)** - Playstore and apkmirror

### Steps to Reproduce
1. apktool d -s -o unpacked fb.apk 
2. apktool b unpacked -o repack.apk 
Deleting the duplicate entry (see below) works around this, but something seems fishy. Why would there be a duplicate entry in the first place?

### Backtrace
```
W: /tmp/apk/unpacked/res/values/styles.xml:11210: error: Resource entry nux_bubble_text already has bag item android:textColor.
W: /tmp/apk/unpacked/res/values/styles.xml:11209: Originally defined here.
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_6672774033549756676.tmp, p, --forced-package-id, 127, --min-sdk-version, 22, --target-sdk-version, 23, --version-code, 72571779, --version-name, 142.0.0.29.92, --no-version-vectors, -F, /tmp/APKTOOL6388440785028131837.tmp, -0, arsc, -0, assets/ComponentScriptBundle.js.bytecode.sha1, -0, assets/ComponentScriptBundle.js.meta, -0, assets/InboxV2Query_MessengerInboxUnits_Nodes.fbs.md5, -0, js, -0, assets/js-modules/UNBUNDLE, -0, xzs, -0, assets/xplat.rtc.librtc/libs.xzs, -0, fbfx, -0, webp, -0, json, -0, FBSIG, -0, arsc, -I, /home/steve/.local/share/apktool/framework/1.apk, -S, /tmp/apk/unpacked/res, -M, /tmp/apk/unpacked/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:485)
	at brut.androlib.Androlib.buildResources(Androlib.java:419)
	at brut.androlib.Androlib.build(Androlib.java:318)
	at brut.androlib.Androlib.build(Androlib.java:270)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:75)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_6672774033549756676.tmp, p, --forced-package-id, 127, --min-sdk-version, 22, --target-sdk-version, 23, --version-code, 72571779, --version-name, 142.0.0.29.92, --no-version-vectors, -F, /tmp/APKTOOL6388440785028131837.tmp, -0, arsc, -0, assets/ComponentScriptBundle.js.bytecode.sha1, -0, assets/ComponentScriptBundle.js.meta, -0, assets/InboxV2Query_MessengerInboxUnits_Nodes.fbs.md5, -0, js, -0, assets/js-modules/UNBUNDLE, -0, xzs, -0, assets/xplat.rtc.librtc/libs.xzs, -0, fbfx, -0, webp, -0, json, -0, FBSIG, -0, arsc, -I, /home/steve/.local/share/apktool/framework/1.apk, -S, /tmp/apk/unpacked/res, -M, /tmp/apk/unpacked/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:454)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:471)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_6672774033549756676.tmp, p, --forced-package-id, 127, --min-sdk-version, 22, --target-sdk-version, 23, --version-code, 72571779, --version-name, 142.0.0.29.92, --no-version-vectors, -F, /tmp/APKTOOL6388440785028131837.tmp, -0, arsc, -0, assets/ComponentScriptBundle.js.bytecode.sha1, -0, assets/ComponentScriptBundle.js.meta, -0, assets/InboxV2Query_MessengerInboxUnits_Nodes.fbs.md5, -0, js, -0, assets/js-modules/UNBUNDLE, -0, xzs, -0, assets/xplat.rtc.librtc/libs.xzs, -0, fbfx, -0, webp, -0, json, -0, FBSIG, -0, arsc, -I, /home/steve/.local/share/apktool/framework/1.apk, -S, /tmp/apk/unpacked/res, -M, /tmp/apk/unpacked/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:448)
	... 6 more
```

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://www.apkmirror.com/apk/facebook-2/facebook/facebook-142-0-0-29-92-release/facebook-142-0-0-29-92-android-apk-download/
MD5: c1c97d4b426e4804219fed2f40121f93

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yup.
2. If you are trying to install a modified apk, did you resign it? N/A
3. Are you using the latest apktool version? Yup

**Comment by Frayo44** [comment]
I had the same issue.
I fixed it by going to styles.xml at `res/values`, and replace this:

`<style name="nux_bubble_text">
        <item name="android:textSize">12.0dip</item>
        <item name="android:textColor">@android:color/white</item>
        <item name="android:textColor">@android:color/white</item>
        <item name="android:gravity">left</item>
        <item name="android:paddingLeft">8.0dip</item>
        <item name="android:paddingRight">8.0dip</item>
        <item name="android:shadowColor">@color/black25a</item>
        <item name="android:shadowDy">-1.0</item>
        <item name="android:shadowRadius">0.25</item>
    </style>`

With:

`<style name="nux_bubble_text">
        <item name="android:textSize">12.0dip</item>
        <item name="android:textColor">@android:color/white</item>
        <item name="android:gravity">left</item>
        <item name="android:paddingLeft">8.0dip</item>
        <item name="android:paddingRight">8.0dip</item>
        <item name="android:shadowColor">@color/black25a</item>
        <item name="android:shadowDy">-1.0</item>
        <item name="android:shadowRadius">0.25</item>
    </style>`

After the replacement all should be fine.

**Comment by iBotPeaches** [comment]
Thanks for looking into this @Frayo44, I guess Facebook has a pretty relaxed build system to allow duplicated properties like this.

I don't know if Apktool should be responsible for repairing invalid XML. Unless of course it was correct and Apktool caused the error. I will look into that and see if this was the cause of Apktool or original application.

**Comment by iBotPeaches** [comment]
Yep this is in the original application resource table. I don't know why or how. I think Apktool is doing the proper thing here. It isn't in the business of automatically repairing malformed applications.

I would just remove the duplicated property and continue. If this happens in more volume and applications, it must point to some bug in dev tools and we can take another look and possibly upstream something to AOSP.

**Comment by ttimasdf** [comment]
If you're not modifing resources, I notice apktool now has a flag `--force-manifest`, which is handy for repacking large apks. It only decompiles AndroidManifest.xml and don't touch other resources.

```bash
apktool d -s -m -r --force-manifest -f '.\com.android.vending_23.6.16.apk'
```
