### ISSUE TITLE
Decompile An Apk success,But Recompile fail

### ISSUE THREAD

**Issue by YuanYQ** [iBotPeaches/Apktool#1623]
### Information
1. **2.3.0** -
2. ** Windows** -
3. **Google Play Store** -

### Stacktrace/Logcat
```
.touxiang/2270700970.jst, -0, assets/jpg/UI_touxiang.touxiang/2271672316.jst, -0
, assets/jpg/UI_touxiang.touxiang/2278505330.jst, -0, assets/jpg/UI_touxiang.tou
xiang/2284399407.jst, -0, assets/jpg/UI_touxiang.touxiang/2294680647.jst, -0, as
sets/jpg/UI_touxiang.touxiang/2295726622.jst, -0, assets/jpg/UI_touxiang.touxian
g/2302914323.jst, -0, assets/jpg/UI_touxiang.touxiang/2312584940.jst, -0, assets
/jpg/UI_touxiang.touxiang/2315111800.jst, -0, assets/jpg/UI_touxiang.touxiang/23
26544537.jst, -0, assets/jpg/UI_touxiang.touxiang/233341632.jst, -0, assets/jpg/
UI_touxiang.touxiang/2335088552.jst, -0, assets/jpg/UI_touxiang.touxiang/2335353
230.jst, -0, assets/jpg/UI_touxiang.touxiang/2335987311.jst, -0, assets/jpg/UI_t
ouxiang.touxiang/2337317133.jst, -0, assets/jpg/UI_touxiang.touxiang/2340924410.
jst, -0, assets/jpg/UI_touxiang.touxiang/2341345414.jst, -0, assets/jpg/UI_touxi
ang.touxiang/2349022604.jst, -0, assets/jpg/UI_touxiang.touxiang/2352195660.jst,
 -0, assets/jpg/UI_touxiang.touxiang/2354761860.jst, -0, assets/jpg/UI_touxiang.
touxiang/2357305085.jst, -0, assets/jpg/UI_touxiang.touxiang/2362849519.jst, -0,
 assets/jpg/UI_touxiang.touxiang/2365100969.jst, -0, assets/jpg/UI_touxiang.toux
iang/2376265930.jst, -0, assets/jpg/UI_touxiang.touxiang/2383761129.jst, -0, ass
ets/jpg/UI_touxiang.touxiang/2384541475.jst, -0, assets/jpg/UI_touxiang.touxiang
/2399664035.jst, -0, assets/jpg/UI_touxiang.touxiang/240812277.jst, -0, assets/j
pg/UI_touxiang.touxiang/2410504580.jst, -0, assets/jpg/UI_touxiang.touxiang/2411
897572.jst, -0, assets/jpg/UI_touxiang.touxiang/241454981.jst, -0, assets/jpg/UI
_touxiang.touxiang/2420955663.jst, -0, assets/jpg/UI_touxiang.touxiang/24345362.
jst, -0, assets/jpg/UI_touxiang.touxiang/2440254616.jst, -0, assets/jpg/UI_touxi
ang.touxiang/2441425228.jst, -0, assets/jpg/UI_touxiang.touxiang/2448836176.jst,
 -0, assets/jpg/UI_touxiang.touxiang/2454378317.jst, -0, assets/jpg/UI_touxiang.
touxiang/2477903830.jst, -0, assets/jpg/UI_touxiang.touxiang/2481467274.jst, -0,
 assets/jpg/UI_touxiang.touxiang/2484817871.jst, -0, assets/jpg/UI_touxiang.toux
iang/2488137188.jst, -0, assets/jpg/UI_touxiang.touxiang/2493579268.jst, -0, ass
ets/jpg/UI_touxiang.touxiang/2498744716.jst, -0, assets/jpg/UI_touxiang.touxiang
/2500614930.jst, -0, assets/jpg/UI_touxiang.touxiang/2501047116.jst, -0, assets/
jpg/UI_touxiang.touxiang/2504406665.jst, -0, assets/jpg/UI_touxiang.touxiang/250
4494476.jst, -0, assets/jpg/UI_touxiang.touxiang/2505539695.jst, -0, assets/jpg/
UI_touxiang.touxiang/2522844802.jst, -0, assets/jpg/UI_touxiang.touxiang/2526355
37.jst, -0, assets/jpg/UI_touxiang.touxiang/2527192514.jst, -0, assets/jpg/UI_to
uxiang.touxiang/2542493960.jst, -0, assets/jpg/UI_touxiang.touxiang/2560928439.j
st, -0, assets/jpg/UI_touxiang.touxiang/2561935895.jst, -0, assets/jpg/UI_touxia
ng.touxiang/2563797385.jst, -0, assets/jpg/UI_touxiang.touxiang/2578105827.jst,
-0, assets/jpg/UI_touxiang.touxiang/2584345350.jst, -0, assets/jpg/UI_touxiang.t
ouxiang/2590968408.jst, -0, assets/jpg/UI_touxiang.touxiang/2594533019.jst, -0,
assets/jpg/UI_touxiang.touxiang/2614604168.jst, -0, assets/jpg/UI_touxiang.touxi
ang/2618024794.jst, -0, assets/jpg/UI_touxiang.touxiang/2618081915.jst, -0, asse
ts/jpg/UI_touxiang.touxiang/2626499650.jst, -0, assets/jpg/UI_touxiang.touxiang/
262798916.jst, -0, assets/jpg/UI_touxiang.touxiang/2634591977.jst, -0, assets/jp
g/UI_touxiang.touxiang/2635168976.jst, -0, assets/jpg/UI_touxiang.touxiang/26423
48703.jst, -0, assets/jpg/UI_touxiang.touxiang/2655956235.jst, -0, assets/jpg/UI
_touxiang.touxiang/2666629749.jst, -0, assets/jpg/UI_touxiang.touxiang/266951702
3.jst, -0, assets/jpg/UI_touxiang.touxiang/2681127547.jst, -0, assets/jpg/UI_tou
xiang.touxiang/2694496796.jst, -0, assets/jpg/UI_touxiang.touxiang/2694625982.js
t, -0, assets/jpg/UI_touxiang.touxiang/2695491545.jst, -0, assets/jpg/UI_touxian
g.touxiang/2695636084.jst, -0, assets/jpg/UI_touxiang.touxiang/2712819673.jst, -
0, assets/jpg/UI_touxiang.touxiang/2727243925.jst, -0, assets/jpg/UI_touxiang.to
uxiang/2732030402.jst, -0, assets/jpg/UI_touxiang.touxiang/2738072737.jst, -0, a
ssets/jpg/UI_touxiang.touxiang/2738983525.jst, -0, assets/jpg/UI_touxiang.touxia
ng/27399500.jst, -0, assets/jpg/UI_touxiang.touxiang/2755998369.jst, -0, assets/
jpg/UI_touxiang.touxiang/276453695.jst, -0, assets/jpg/UI_touxiang.touxiang/2765
666419.jst, -0, assets/jpg/UI_touxiang.touxiang/2768097408.jst, -0, assets/jpg/U
I_touxiang.touxiang/2776246409.jst, -0, assets/jpg/UI_touxiang.touxiang/27952640
16.jst, -0, assets/jpg/UI_touxiang.touxiang/2795872350.jst, -0, assets/jpg/UI_to
uxiang.touxiang/2803696479.jst, -0, assets/jpg/UI_touxiang.touxiang/2810213417.j
st, -0, assets/jpg/UI_touxiang.touxiang/2815326772.jst, -0, assets/jpg/UI_touxia
ng.touxiang/2820902577.jst, -0, assets/jpg/UI_touxiang.touxiang/2828919047.jst,
-0, assets/jpg/UI_touxiang.touxiang/2831910607.jst, -0, assets/jpg/UI_touxiang.t
ouxiang/2841349734.jst, -0, assets/jpg/UI_touxiang.touxiang/2848766199.jst, -0,
assets/jpg/UI_touxiang.touxiang/286420983.jst, -0, assets/jpg/UI_touxiang.touxia
ng/2865687254.jst, -0, assets/jpg/UI_touxiang.touxiang/2871506258.jst, -0, asset
s/jpg/UI_touxiang.touxiang/287360664.jst, -0, assets/jpg/UI_touxiang.touxiang/28
73770817.jst, -0, assets/jpg/UI_touxiang.touxiang/2889432196.jst, -0, assets/jpg
/UI_touxiang.touxiang/2902051082.jst, -0, assets/jpg/UI_touxiang.touxiang/291858
0099.jst, -0, assets/jpg/UI_touxiang.touxiang/2920092138.jst, -0, assets/jpg/UI_
touxiang.touxiang/2927873784.jst, -0, assets/jpg/UI_touxiang.touxiang/2929518052
.jst, -0, assets/jpg/UI_touxiang.touxiang/2933222120.jst, -0, assets/jpg/UI_toux
iang.touxiang/2935081034.jst, -0, assets/jpg/UI_touxiang.touxiang/2937238655.jst
, -0, assets/jpg/UI_touxiang.touxiang/2942586434.jst, -0, assets/jpg/UI_touxiang
.touxiang/2948655735.jst, -0, assets/jpg/UI_touxiang.touxiang/2948664035.jst, -0
, assets/jpg/UI_touxiang.touxiang/2951515649.jst, -0, assets/jpg/UI_touxiang.tou
xiang/2952080557.jst, -0, assets/jpg/UI_touxiang.touxiang/2966510014.jst, -0, as
sets/jpg/UI_touxiang.touxiang/2967038964.jst, -0, assets/jpg/UI_touxiang.touxian
g/2973561760.jst, -0, assets/jpg/UI_touxiang.touxiang/2978572274.jst, -0, assets
/jpg/UI_touxiang.touxiang/2979712082.jst, -0, assets/jpg/UI_touxiang.touxiang/29
85047818.jst, -0, assets/jpg/UI_touxiang.touxiang/2988180467.jst, -0, assets/jpg
/UI_touxiang.touxiang/2989889705.jst, -0, assets/jpg/UI_touxiang.touxiang/299053
0200.jst, -0, assets/jpg/UI_touxiang.touxiang/2990905691.jst, -0, assets/jpg/UI_
touxiang.touxiang/2993582575.jst, -0, assets/jpg/UI_touxiang.touxiang/2997962879
.jst, -0, assets/jpg/UI_touxiang.touxiang/3006249472.jst, -0, assets/jpg/UI_toux
iang.touxiang/3009697477.jst, -0, assets/jpg/UI_touxiang.touxiang/3025047649.jst
, -0, assets/jpg/UI_touxiang.touxiang/3031456907.jst, -0, assets/jpg/UI_touxiang
.touxiang/3040700482.jst, -0, assets/jpg/UI_touxiang.touxiang/3054718148.jst, -0
, assets/jpg/UI_touxiang.touxiang/3064522336.jst, -0, assets/jpg/UI_touxiang.tou
xiang/3065048100.jst, -0, assets/jpg/UI_touxiang.touxiang/3065350533.jst, -0, as
sets/jpg/UI_touxiang.touxiang/3066609517.jst, -0, assets/jpg/UI_touxiang.touxian
g/3069705034.jst, -0, assets/jpg/UI_touxiang.touxiang/3080275868.jst, -0, assets
/jpg/UI_touxiang.touxiang/3084800018.jst, -0, assets/jpg/UI_touxiang.touxiang/30
86040439.jst, -0, assets/jpg/UI_touxiang.touxiang/3095979811.jst, -0, assets/jpg
/UI_touxiang.touxiang/3096470786.jst, -0, assets/jpg/UI_touxiang.touxiang/309704
3206.jst, -0, assets/jpg/UI_touxiang.touxiang/3105061853.jst, -0, assets/jpg/UI_
touxiang.touxiang/3109892082.jst, -0, assets/jpg/UI_touxiang.touxiang/3113714361
.jst, -0, assets/jpg/UI_touxiang.touxiang/3114412290.jst, -0, assets/jpg/UI_toux
iang.touxiang/3132758849.jst, -0, assets/jpg/UI_touxiang.touxiang/3139905647.jst
, -0, assets/jpg/UI_touxiang.touxiang/3151109920.jst, -0, assets/jpg/UI_touxiang
.touxiang/3168386005.jst, -0, assets/jpg/UI_touxiang.touxiang/316987874.jst, -0,
 assets/jpg/UI_touxiang.touxiang/3171343481.jst, -0, assets/jpg/UI_touxiang.toux
iang/3173835805.jst, -0, assets/jpg/UI_touxiang.touxiang/3183193440.jst, -0, ass
ets/jpg/UI_touxiang.touxiang/3183397392.jst, -0, assets/jpg/UI_touxiang.touxiang
/3192181821.jst, -0, assets/jpg/UI_touxiang.touxiang/3194051759.jst, -0, assets/
jpg/UI_touxiang.touxiang/3200818038.jst, -0, assets/jpg/UI_touxiang.touxiang/320
3495304.jst, -0, assets/jpg/UI_touxiang.touxiang/3205443261.jst, -0, assets/jpg/
UI_touxiang.touxiang/3206642166.jst, -0, assets/jpg/UI_touxiang.touxiang/3210817
102.jst, -0, assets/jpg/UI_touxiang.touxiang/3219198591.jst, -0, assets/jpg/UI_t
ouxiang.touxiang/322802450.jst, -0, assets/jpg/UI_touxiang.touxiang/3236258680.j
st, -0, assets/jpg/UI_touxiang.touxiang/3248255008.jst, -0, assets/jpg/UI_touxia
ng.touxiang/3254608515.jst, -0, assets/jpg/UI_touxiang.touxiang/3266874493.jst,
-0, assets/jpg/UI_touxiang.touxiang/3267436833.jst, -0, assets/jpg/UI_touxiang.t
ouxiang/3285896054.jst, -0, assets/jpg/UI_touxiang.touxiang/3287858919.jst, -0,
assets/jpg/UI_touxiang.touxiang/328910630.jst, -0, assets/jpg/UI_touxiang.touxia
ng/3299474801.jst, -0, assets/jpg/UI_touxiang.touxiang/331362159.jst, -0, assets
/jpg/UI_touxiang.touxiang/3324870602.jst, -0, assets/jpg/UI_touxiang.touxiang/33
25852012.jst, -0, assets/jpg/UI_touxiang.touxiang/3326499398.jst, -0, assets/jpg
/UI_touxiang.touxiang/3327896920.jst, -0, assets/jpg/UI_touxiang.touxiang/333790
4973.jst, -0, assets/jpg/UI_touxiang.touxiang/3339158552.jst, -0, assets/jpg/UI_
touxiang.touxiang/3341006416.jst, -0, assets/jpg/UI_touxiang.touxiang/3341733622
.jst, -0, assets/jpg/UI_touxiang.touxiang/3345202691.jst, -0, assets/jpg/UI_toux
iang.touxiang/335313929.jst, -0, assets/jpg/UI_touxiang.touxiang/3354711025.jst,
 -0, assets/jpg/UI_touxiang.touxiang/3356494130.jst, -0, assets/jpg/UI_touxiang.
touxiang/3379605374.jst, -0, assets/jpg/UI_touxiang.touxiang/3389870994.jst, -0,
 assets/jpg/UI_touxiang.touxiang/3391128096.jst, -0, assets/jpg/UI_touxiang.toux
iang/339234129.jst, -0, assets/jpg/UI_touxiang.touxiang/3397482251.jst, -0, asse
ts/jpg/UI_touxiang.touxiang/3404197743.jst, -0, assets/jpg/UI_touxiang.touxiang/
3419383757.jst, -0, assets/jpg/UI_touxiang.touxiang/3423797083.jst, -0, assets/j
pg/UI_touxiang.touxiang/3434727088.jst, -0, assets/jpg/UI_touxiang.touxiang/3435
442598.jst, -0, assets/jpg/UI_touxiang.touxiang/3439686170.jst, -0, assets/jpg/U
I_touxiang.touxiang/3439852470.jst, -0, assets/jpg/UI_touxiang.touxiang/34412899
66.jst, -0, assets/jpg/UI_touxiang.touxiang/3447601932.jst, -0, assets/jpg/UI_to
uxiang.touxiang/3450375262.jst, -0, assets/jpg/UI_touxiang.touxiang/3456488334.j
st, -0, assets/jpg/UI_touxiang.touxiang/3463469789.jst, -0, assets/jpg/UI_touxia
ng.touxiang/3468051694.jst, -0, assets/jpg/UI_touxiang.touxiang/3485252742.jst,
-0, assets/jpg/UI_touxiang.touxiang/3486809045.jst, -0, assets/jpg/UI_touxiang.t
ouxiang/348889332.jst, -0, assets/jpg/UI_touxiang.touxiang/3489247313.jst, -0, a
ssets/jpg/UI_touxiang.touxiang/3492585071.jst, -0, assets/jpg/UI_touxiang.touxia
ng/3495651305.jst, -0, assets/jpg/UI_touxiang.touxiang/3507769092.jst, -0, asset
s/jpg/UI_touxiang.touxiang/3529871012.jst, -0, assets/jpg/UI_touxiang.touxiang/3
530259285.jst, -0, assets/jpg/UI_touxiang.touxiang/3530743709.jst, -0, assets/jp
g/UI_touxiang.touxiang/3539777733.jst, -0, assets/jpg/UI_touxiang.touxiang/35494
73518.jst, -0, assets/jpg/UI_touxiang.touxiang/3555535611.jst, -0, assets/jpg/UI
_touxiang.touxiang/3558481604.jst, -0, assets/jpg/UI_touxiang.touxiang/356853975
3.jst, -0, assets/jpg/UI_touxiang.touxiang/3570046486.jst, -0, assets/jpg/UI_tou
xiang.touxiang/3571909175.jst, -0, assets/jpg/UI_touxiang.touxiang/357326886.jst
, -0, assets/jpg/UI_touxiang.touxiang/3591799491.jst, -0, assets/jpg/UI_touxiang
.touxiang/3592510659.jst, -0, assets/jpg/UI_touxiang.touxiang/3603936106.jst, -0
, assets/jpg/UI_touxiang.touxiang/3608183391.jst, -0, assets/jpg/UI_touxiang.tou
xiang/3609697905.jst, -0, assets/jpg/UI_touxiang.touxiang/3617586205.jst, -0, as
sets/jpg/UI_touxiang.touxiang/3620188932.jst, -0, assets/jpg/UI_touxiang.touxian
g/3626849322.jst, -0, assets/jpg/UI_touxiang.touxiang/3629887412.jst, -0, assets
/jpg/UI_touxiang.touxiang/363092204.jst, -0, assets/jpg/UI_touxiang.touxiang/364
2682196.jst, -0, assets/jpg/UI_touxiang.touxiang/3649926132.jst, -0, assets/jpg/
UI_touxiang.touxiang/3650074807.jst, -0, assets/jpg/UI_touxiang.touxiang/3654452
001.jst, -0, assets/jpg/UI_touxiang.touxiang/3655710593.jst, -0, assets/jpg/UI_t
ouxiang.touxiang/3660379786.jst, -0, assets/jpg/UI_touxiang.touxiang/3665739335.
jst, -0, assets/jpg/UI_touxiang.touxiang/3668610909.jst, -0, assets/jpg/UI_touxi
ang.touxiang/3670838277.jst, -0, assets/jpg/UI_touxiang.touxiang/3687364692.jst,
 -0, assets/jpg/UI_touxiang.touxiang/3688446397.jst, -0, assets/jpg/UI_touxiang.
touxiang/3699100374.jst, -0, assets/jpg/UI_touxiang.touxiang/3713860660.jst, -0,
 assets/jpg/UI_touxiang.touxiang/3726168385.jst, -0, assets/jpg/UI_touxiang.toux
iang/372976052.jst, -0, assets/jpg/UI_touxiang.touxiang/3732661856.jst, -0, asse
ts/jpg/UI_touxiang.touxiang/3739913841.jst, -0, assets/jpg/UI_touxiang.touxiang/
374665761.jst, -0, assets/jpg/UI_touxiang.touxiang/375197566.jst, -0, assets/jpg
/UI_touxiang.touxiang/3755695241.jst, -0, assets/jpg/UI_touxiang.touxiang/375902
6789.jst, -0, assets/jpg/UI_touxiang.touxiang/3778752200.jst, -0, assets/jpg/UI_
touxiang.touxiang/3785730314.jst, -0, assets/jpg/UI_touxiang.touxiang/3788278835
.jst, -0, assets/jpg/UI_touxiang.touxiang/379177299.jst, -0, assets/jpg/UI_touxi
ang.touxiang/3803701258.jst, -0, assets/jpg/UI_touxiang.touxiang/3809175670.jst,
 -0, assets/jpg/UI_touxiang.touxiang/3815693891.jst, -0, assets/jpg/UI_touxiang.
touxiang/3816211877.jst, -0, assets/jpg/UI_touxiang.touxiang/382381785.jst, -0,
assets/jpg/UI_touxiang.touxiang/3831843167.jst, -0, assets/jpg/UI_touxiang.touxi
ang/3845040058.jst, -0, assets/jpg/UI_touxiang.touxiang/3854568110.jst, -0, asse
ts/jpg/UI_touxiang.touxiang/3855103888.jst, -0, assets/jpg/UI_touxiang.touxiang/
3855363923.jst, -0, assets/jpg/UI_touxiang.touxiang/3864632674.jst, -0, assets/j
pg/UI_touxiang.touxiang/3865235266.jst, -0, assets/jpg/UI_touxiang.touxiang/3887
811897.jst, -0, assets/jpg/UI_touxiang.touxiang/3894842597.jst, -0, assets/jpg/U
I_touxiang.touxiang/3902272755.jst, -0, assets/jpg/UI_touxiang.touxiang/39056805
3.jst, -0, assets/jpg/UI_touxiang.touxiang/391217910.jst, -0, assets/jpg/UI_toux
iang.touxiang/3920254618.jst, -0, assets/jpg/UI_touxiang.touxiang/3922815840.jst
, -0, assets/jpg/UI_touxiang.touxiang/3923924336.jst, -0, assets/jpg/UI_touxiang
.touxiang/3925208516.jst, -0, assets/jpg/UI_touxiang.touxiang/393022247.jst, -0,
 assets/jpg/UI_touxiang.touxiang/3930691486.jst, -0, assets/jpg/UI_touxiang.toux
iang/393956863.jst, -0, assets/jpg/UI_touxiang.touxiang/3956923283.jst, -0, asse
ts/jpg/UI_touxiang.touxiang/3960488150.jst, -0, assets/jpg/UI_touxiang.touxiang/
3967236909.jst, -0, assets/jpg/UI_touxiang.touxiang/3972809781.jst, -0, assets/j
pg/UI_touxiang.touxiang/3978359208.jst, -0, assets/jpg/UI_touxiang.touxiang/3986
284829.jst, -0, assets/jpg/UI_touxiang.touxiang/3990770555.jst, -0, assets/jpg/U
I_touxiang.touxiang/3994249206.jst, -0, assets/jpg/UI_touxiang.touxiang/39952147
63.jst, -0, assets/jpg/UI_touxiang.touxiang/3999874727.jst, -0, assets/jpg/UI_to
uxiang.touxiang/4011157630.jst, -0, assets/jpg/UI_touxiang.touxiang/4016549936.j
st, -0, assets/jpg/UI_touxiang.touxiang/40250815.jst, -0, assets/jpg/UI_touxiang
.touxiang/4030060630.jst, -0, assets/jpg/UI_touxiang.touxiang/4034109642.jst, -0
, assets/jpg/UI_touxiang.touxiang/4051811325.jst, -0, assets/jpg/UI_touxiang.tou
xiang/4054269853.jst, -0, assets/jpg/UI_touxiang.touxiang/4054818764.jst, -0, as
sets/jpg/UI_touxiang.touxiang/4059010676.jst, -0, assets/jpg/UI_touxiang.touxian
g/4061970995.jst, -0, assets/jpg/UI_touxiang.touxiang/4084743015.jst, -0, assets
/jpg/UI_touxiang.touxiang/4085450140.jst, -0, assets/jpg/UI_touxiang.touxiang/41
04490815.jst, -0, assets/jpg/UI_touxiang.touxiang/4109147202.jst, -0, assets/jpg
/UI_touxiang.touxiang/4112225093.jst, -0, assets/jpg/UI_touxiang.touxiang/411275
2364.jst, -0, assets/jpg/UI_touxiang.touxiang/4113219738.jst, -0, assets/jpg/UI_
touxiang.touxiang/4115281607.jst, -0, assets/jpg/UI_touxiang.touxiang/413907666.
jst, -0, assets/jpg/UI_touxiang.touxiang/4154146823.jst, -0, assets/jpg/UI_touxi
ang.touxiang/4159180820.jst, -0, assets/jpg/UI_touxiang.touxiang/4161630418.jst,
 -0, assets/jpg/UI_touxiang.touxiang/4162120958.jst, -0, assets/jpg/UI_touxiang.
touxiang/4165973579.jst, -0, assets/jpg/UI_touxiang.touxiang/417039531.jst, -0,
assets/jpg/UI_touxiang.touxiang/4172297299.jst, -0, assets/jpg/UI_touxiang.touxi
ang/4173245941.jst, -0, assets/jpg/UI_touxiang.touxiang/4173974013.jst, -0, asse
ts/jpg/UI_touxiang.touxiang/4180182301.jst, -0, assets/jpg/UI_touxiang.touxiang/
4181734610.jst, -0, assets/jpg/UI_touxiang.touxiang/4187603999.jst, -0, assets/j
pg/UI_touxiang.touxiang/418794071.jst, -0, assets/jpg/UI_touxiang.touxiang/42103
1527.jst, -0, assets/jpg/UI_touxiang.touxiang/4241533146.jst, -0, assets/jpg/UI_
touxiang.touxiang/4241719248.jst, -0, assets/jpg/UI_touxiang.touxiang/4247203689
.jst, -0, assets/jpg/UI_touxiang.touxiang/4247796813.jst, -0, assets/jpg/UI_toux
iang.touxiang/4259217382.jst, -0, assets/jpg/UI_touxiang.touxiang/4264496671.jst
, -0, assets/jpg/UI_touxiang.touxiang/4275799831.jst, -0, assets/jpg/UI_touxiang
.touxiang/4276525026.jst, -0, assets/jpg/UI_touxiang.touxiang/4279745081.jst, -0
, assets/jpg/UI_touxiang.touxiang/4280088924.jst, -0, assets/jpg/UI_touxiang.tou
xiang/4282055263.jst, -0, assets/jpg/UI_touxiang.touxiang/4288946545.jst, -0, as
sets/jpg/UI_touxiang.touxiang/438376409.jst, -0, assets/jpg/UI_touxiang.touxiang
/449065035.jst, -0, assets/jpg/UI_touxiang.touxiang/457662397.jst, -0, assets/jp
g/UI_touxiang.touxiang/461782459.jst, -0, assets/jpg/UI_touxiang.touxiang/468398
096.jst, -0, assets/jpg/UI_touxiang.touxiang/468425230.jst, -0, assets/jpg/UI_to
uxiang.touxiang/472736914.jst, -0, assets/jpg/UI_touxiang.touxiang/47757903.jst,
 -0, assets/jpg/UI_touxiang.touxiang/480915144.jst, -0, assets/jpg/UI_touxiang.t
ouxiang/483811314.jst, -0, assets/jpg/UI_touxiang.touxiang/492753770.jst, -0, as
sets/jpg/UI_touxiang.touxiang/494741721.jst, -0, assets/jpg/UI_touxiang.touxiang
/49518571.jst, -0, assets/jpg/UI_touxiang.touxiang/503656271.jst, -0, assets/jpg
/UI_touxiang.touxiang/504596694.jst, -0, assets/jpg/UI_touxiang.touxiang/5094155
93.jst, -0, assets/jpg/UI_touxiang.touxiang/509442335.jst, -0, assets/jpg/UI_tou
xiang.touxiang/51203834.jst, -0, assets/jpg/UI_touxiang.touxiang/515776342.jst,
-0, assets/jpg/UI_touxiang.touxiang/517748319.jst, -0, assets/jpg/UI_touxiang.to
uxiang/526300319.jst, -0, assets/jpg/UI_touxiang.touxiang/536808652.jst, -0, ass
ets/jpg/UI_touxiang.touxiang/537538748.jst, -0, assets/jpg/UI_touxiang.touxiang/
53781333.jst, -0, assets/jpg/UI_touxiang.touxiang/539066091.jst, -0, assets/jpg/
UI_touxiang.touxiang/544069485.jst, -0, assets/jpg/UI_touxiang.touxiang/55067861
3.jst, -0, assets/jpg/UI_touxiang.touxiang/55095229.jst, -0, assets/jpg/UI_touxi
ang.touxiang/552788047.jst, -0, assets/jpg/UI_touxiang.touxiang/566289003.jst, -
0, assets/jpg/UI_touxiang.touxiang/56726240.jst, -0, assets/jpg/UI_touxiang.toux
iang/570704920.jst, -0, assets/jpg/UI_touxiang.touxiang/579433777.jst, -0, asset
s/jpg/UI_touxiang.touxiang/594965429.jst, -0, assets/jpg/UI_touxiang.touxiang/60
4499571.jst, -0, assets/jpg/UI_touxiang.touxiang/604582107.jst, -0, assets/jpg/U
I_touxiang.touxiang/60695308.jst, -0, assets/jpg/UI_touxiang.touxiang/610900078.
jst, -0, assets/jpg/UI_touxiang.touxiang/630618182.jst, -0, assets/jpg/UI_touxia
ng.touxiang/634203331.jst, -0, assets/jpg/UI_touxiang.touxiang/66673015.jst, -0,
 assets/jpg/UI_touxiang.touxiang/677841761.jst, -0, assets/jpg/UI_touxiang.touxi
ang/679123357.jst, -0, assets/jpg/UI_touxiang.touxiang/681437731.jst, -0, assets
/jpg/UI_touxiang.touxiang/694500504.jst, -0, assets/jpg/UI_touxiang.touxiang/699
605480.jst, -0, assets/jpg/UI_touxiang.touxiang/706893057.jst, -0, assets/jpg/UI
_touxiang.touxiang/720180689.jst, -0, assets/jpg/UI_touxiang.touxiang/725391667.
jst, -0, assets/jpg/UI_touxiang.touxiang/729973142.jst, -0, assets/jpg/UI_touxia
ng.touxiang/730553228.jst, -0, assets/jpg/UI_touxiang.touxiang/750911248.jst, -0
, assets/jpg/UI_touxiang.touxiang/760183674.jst, -0, assets/jpg/UI_touxiang.toux
iang/760599968.jst, -0, assets/jpg/UI_touxiang.touxiang/761573776.jst, -0, asset
s/jpg/UI_touxiang.touxiang/766333496.jst, -0, assets/jpg/UI_touxiang.touxiang/77
8611906.jst, -0, assets/jpg/UI_touxiang.touxiang/787012832.jst, -0, assets/jpg/U
I_touxiang.touxiang/789477050.jst, -0, assets/jpg/UI_touxiang.touxiang/791603765
.jst, -0, assets/jpg/UI_touxiang.touxiang/79290761.jst, -0, assets/jpg/UI_touxia
ng.touxiang/807220307.jst, -0, assets/jpg/UI_touxiang.touxiang/811068805.jst, -0
, assets/jpg/UI_touxiang.touxiang/820275323.jst, -0, assets/jpg/UI_touxiang.toux
iang/820571132.jst, -0, assets/jpg/UI_touxiang.touxiang/820947857.jst, -0, asset
s/jpg/UI_touxiang.touxiang/833680422.jst, -0, assets/jpg/UI_touxiang.touxiang/85
6301553.jst, -0, assets/jpg/UI_touxiang.touxiang/875918615.jst, -0, assets/jpg/U
I_touxiang.touxiang/879590156.jst, -0, assets/jpg/UI_touxiang.touxiang/882340917
.jst, -0, assets/jpg/UI_touxiang.touxiang/891808474.jst, -0, assets/jpg/UI_touxi
ang.touxiang/896417836.jst, -0, assets/jpg/UI_touxiang.touxiang/898688816.jst, -
0, assets/jpg/UI_touxiang.touxiang/898885964.jst, -0, assets/jpg/UI_touxiang.tou
xiang/899659051.jst, -0, assets/jpg/UI_touxiang.touxiang/901324129.jst, -0, asse
ts/jpg/UI_touxiang.touxiang/902098650.jst, -0, assets/jpg/UI_touxiang.touxiang/9
07541773.jst, -0, assets/jpg/UI_touxiang.touxiang/91062.jst, -0, assets/jpg/UI_t
ouxiang.touxiang/911879535.jst, -0, assets/jpg/UI_touxiang.touxiang/914908512.js
t, -0, assets/jpg/UI_touxiang.touxiang/916911349.jst, -0, assets/jpg/UI_touxiang
.touxiang/930679720.jst, -0, assets/jpg/UI_touxiang.touxiang/937602262.jst, -0,
assets/jpg/UI_touxiang.touxiang/944688126.jst, -0, assets/jpg/UI_touxiang.touxia
ng/945513074.jst, -0, assets/jpg/UI_touxiang.touxiang/950056985.jst, -0, assets/
jpg/UI_touxiang.touxiang/966512751.jst, -0, assets/jpg/UI_touxiang.touxiang/9667
73709.jst, -0, assets/jpg/UI_touxiang.touxiang/968389715.jst, -0, assets/jpg/UI_
touxiang.touxiang/97417899.jst, -0, assets/jpg/UI_touxiang.touxiang/986327042.js
t, -0, assets/jpg/UI_touxiang.touxiang/9948075.jst, -0, webp, -0, arsc, -I, C:\U
sers\Administrator\AppData\Local\apktool\framework\1.apk, -S, C:\Users\Administr
ator\Desktop\apktool\apktool\aa\res, -M, C:\Users\Administrator\Desktop\apktool\
apktool\aa\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:97)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.jav
a:448)
        ... 6 more
Caused by: java.io.IOException: Cannot run program "C:\Users\ADMINI~1\AppData\Lo
cal\Temp\brut_util_Jar_4782812143300569273.tmp": CreateProcess error=206, 文件名
或扩展名太长。
        at java.lang.ProcessBuilder.start(Unknown Source)
        at brut.util.OS.exec(OS.java:90)
        ... 7 more
Caused by: java.io.IOException: CreateProcess error=206, 文件名或扩展名太长。
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
        ... 9 more
```
### Steps to Reproduce
1. `apktool  b aa`

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
yes

2. If you are trying to install a modified apk, did you resign it?
no
3. Are you using the latest apktool version?
yes

**Comment by LaoQi** [comment]
There is a really annoying issue with using command line tools on Windows: the maximum length of the command line passed to cmd.exe is 8192 characters (see [http://blogs.msdn.com/b/oldnewthing/archive/2003/12/10/56028.aspx](http://blogs.msdn.com/b/oldnewthing/archive/2003/12/10/56028.aspx))

just run it on linux or OSX.

The simple solution:
* edit the apktool.yml 
* set the  `doNotCompress` to `null`

The reason is [https://github.com/iBotPeaches/Apktool/issues/1244](https://github.com/iBotPeaches/Apktool/issues/1244)

**Comment by iBotPeaches** [comment]
Correct. Actual duplicate bug is #1272 . I am aware this is an issue affecting a lot of people, however the fix will require a good deal of rewriting.
