### ISSUE TITLE
error: No resource identifier found on Recompile

### ISSUE THREAD

**Issue by Deltafox79** [iBotPeaches/Apktool#1625]
### Information
1. **Apktool Version (`apktool -version`)** -
**2.3.0**
2. **Operating System (Mac, Linux, Windows)** -
**Windows**
3. **APK From? (Playstore, ROM, Other)** -
**PlayStore**
### Stacktrace/Logcat

```
Include stacktrace here

```
W: ...u.apk\res\layout-v26\abc_screen_toolbar.xml:5: error: No resource identifier found for attribute 'keyboardNavigationCluster' in package 'android'
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\xxx\AppData\Local\Temp\brut_util_Jar_1817709934826594116.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 26, --version-code, 434, --version-name, 4.3.0, --no-version-vectors, -F, C:\Users\xxx\AppData\Local\Temp\APKTOOL1976347694086715338.tmp, -0, arsc, -0, so, -0, arsc, -I, ...\Frameworks\1.apk, -S, ...u.apk\res, -M, ...u.apk\\AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:485)
	at brut.androlib.Androlib.buildResources(Androlib.java:419)
	at brut.androlib.Androlib.build(Androlib.java:318)
	at brut.androlib.Androlib.build(Androlib.java:270)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:75)
```

### Steps to Reproduce
1. `apktool `
**apktool.bat r ..apk**

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

**http://www101.zippyshare.com/v/Nbl8giYd/file.html**

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
yes
2. If you are trying to install a modified apk, did you resign it?
yes
3. Are you using the latest apktool version?
yes

**Comment by iBotPeaches** [comment]
```
➜  1626 apktool d u.apk
I: Using Apktool 2.3.0 on u.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  1626 apktool b u
I: Using Apktool 2.3.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
➜  1626 
```

`apktool empty-framework-dir`. Sounds like you have an out of date framework. Could not duplicate.
