### ISSUE TITLE
Fail when Recompile

### ISSUE THREAD

**Issue by madafaka255** [iBotPeaches/Apktool#1627]
```
I: Using Apktool 2.2.4
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: /root/Downloads/Instagram/res/layout/activity_main.xml:4: error: Error parsing XML: not well-formed (invalid token)
W: 
W: /root/Downloads/Instagram/res/layout-small-v4/activity_main.xml:4: error: Error parsing XML: not well-formed (invalid token)
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_2762439872227104552.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 21, --version-code, 15, --version-name, 3.2, --no-version-vectors, -F, /tmp/APKTOOL7367259663588091566.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/Downloads/Instagram/res, -M, /root/Downloads/Instagram/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:496)
	at brut.androlib.Androlib.buildResources(Androlib.java:430)
	at brut.androlib.Androlib.build(Androlib.java:329)
	at brut.androlib.Androlib.build(Androlib.java:267)
	at brut.apktool.Main.cmdBuild(Main.java:230)
	at brut.apktool.Main.main(Main.java:83)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_2762439872227104552.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 21, --version-code, 15, --version-name, 3.2, --no-version-vectors, -F, /tmp/APKTOOL7367259663588091566.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/Downloads/Instagram/res, -M, /root/Downloads/Instagram/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:441)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:482)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_2762439872227104552.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 21, --version-code, 15, --version-name, 3.2, --no-version-vectors, -F, /tmp/APKTOOL7367259663588091566.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/Downloads/Instagram/res, -M, /root/Downloads/Instagram/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:435)
	... 6 more
```

**Comment by iBotPeaches** [comment]
Duplicate of #1407
