### ISSUE TITLE
Apktool fails to create resource file due to unicode file names under Windows

### ISSUE THREAD

**Issue by MarcMil** [iBotPeaches/Apktool#1628]
### Information
1. **Apktool 2.3.0**
2. **Windows** -
3. **Playstore** -

### Problem
apktool fails to create special unicode named files. Maybe, apktool should rename such files on decode and restore the original names during recompilation.

### Stacktrace/Logcat

```
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: Error copying file: ?
.xml
        at brut.androlib.Androlib.decodeUnknownFiles(Androlib.java:224)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:165)
        at brut.apktool.Main.cmdDecode(Main.java:160)
        at brut.apktool.Main.main(Main.java:72)
Caused by: brut.directory.DirectoryException: Error copying file: ?    .xml
        at brut.directory.DirUtil.copyToDir(DirUtil.java:88)
        at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:208)
        at brut.androlib.Androlib.decodeUnknownFiles(Androlib.java:217)
        ... 3 more
Caused by: java.io.FileNotFoundException: cm.confide.android\unknown\? .xml (Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at brut.directory.DirUtil.copyToDir(DirUtil.java:84)
        ... 5 more
```

### Steps to Reproduce
1. `apktool d cm.confide.android.apk`

### Frameworks
No special Framework used

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://play.google.com/store/apps/details?id=cm.confide.android
md5: 8ec33e2a06b1504b869e1ccf80830f5d

### Questions to ask before submission
Are you using the latest apktool version?
Apktool 2.3.0

**Comment by iBotPeaches** [comment]
Yeah this a older bug I've yet to fix. Lots of work to build a lookup table for original naming - #1460
