### ISSUE TITLE
AAPT crashes during rebuild

### ISSUE THREAD

**Issue by MarcMil** [iBotPeaches/Apktool#1632]
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.0
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat

```
I: Using Apktool 2.3.0
I: Smaling smali folder into classes.dex...
I: Building resources...
W: warning: string 'textOff' has no default translation.
W: warning: string 'textOn' has no default translation.
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\footer_issues_status.xml:13: error: No resource identifier found for attribute 'cardBackgroundColor' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\footer_issues_status.xml:13: error: No resource identifier found for attribute 'cardElevation' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\kis_activity_main.xml:4: error: No resource identifier found for attribute 'slidingViewId' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\kis_activity_main.xml:4: error: No resource identifier found for attribute 'mainViewId' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\kis_activity_main.xml:4: error: No resource identifier found for attribute 'slidingViewStyle' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\kis_activity_main.xml:4: error: No resource identifier found for attribute 'slidingViewLedge' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\kis_activity_main.xml:4: error: No resource identifier found for attribute 'slidingViewPosition' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\kis_fragment_shield.xml:11: error: No resource identifier found for attribute 'wireframeDrawableId' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\kis_fragment_shield.xml:11: error: No resource identifier found for attribute 'infoDrawableId' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\kis_fragment_shield.xml:11: error: No resource identifier found for attribute 'warningDrawableId' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\kis_fragment_shield.xml:11: error: No resource identifier found for attribute 'errorDrawableId' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\kis_fragment_shield.xml:11: error: No resource identifier found for attribute 'progressDelimDrawableId' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\kis_fragment_shield.xml:11: error: No resource identifier found for attribute 'progressHiDrawableId' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\kis_fragment_shield.xml:11: error: No resource identifier found for attribute 'progressLowDrawableId' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\kis_fragment_shield.xml:11: error: No resource identifier found for attribute 'progressPaddingTopPercent' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\kis_fragment_shield.xml:11: error: No resource identifier found for attribute 'progressPaddingBottomPercent' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\kis_li_issue.xml:4: error: No resource identifier found for attribute 'cardElevation' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\kis_li_issue.xml:4: error: No resource identifier found for attribute 'cardUseCompatPadding' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\kis_li_issue.xml:4: error: No resource identifier found for attribute 'contentPadding' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\license_blocked.xml:4: error: No resource identifier found for attribute 'boundedWidthInches' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\license_info_control.xml:4: error: No resource identifier found for attribute 'remainingText' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\license_info_control.xml:4: error: No resource identifier found for attribute 'backgroundNoValue' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\license_info_control.xml:4: error: No resource identifier found for attribute 'backgroundValue' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\license_settings_general.xml:4: error: No resource identifier found for attribute 'boundedWidthInches' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\wizard_web_registration_kms.xml:8: error: No resource identifier found for attribute 'editHint' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\wizard_web_registration_kms.xml:9: error: No resource identifier found for attribute 'editHint' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\wizard_web_registration_kms.xml:9: error: No resource identifier found for attribute 'emptyPasswordHint' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\wizard_web_registration_kms.xml:9: error: No resource identifier found for attribute 'shortPasswordHint' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\wizard_web_registration_kms.xml:9: error: No resource identifier found for attribute 'weakPasswordHint' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\wizard_web_registration_kms.xml:9: error: No resource identifier found for attribute 'invalidPasswordHint' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\wizard_web_registration_kms.xml:11: error: No resource identifier found for attribute 'editHint' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\wizard_web_registration_kms.xml:12: error: No resource identifier found for attribute 'titleText' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\wizard_web_registration_kms.xml:23: error: No resource identifier found for attribute 'titleText' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\wizard_web_registration_kts.xml:8: error: No resource identifier found for attribute 'editHint' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\wizard_web_registration_kts.xml:9: error: No resource identifier found for attribute 'editHint' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\wizard_web_registration_kts.xml:9: error: No resource identifier found for attribute 'emptyPasswordHint' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\wizard_web_registration_kts.xml:9: error: No resource identifier found for attribute 'shortPasswordHint' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\wizard_web_registration_kts.xml:9: error: No resource identifier found for attribute 'weakPasswordHint' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\wizard_web_registration_kts.xml:9: error: No resource identifier found for attribute 'invalidPasswordHint' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\wizard_web_registration_kts.xml:11: error: No resource identifier found for attribute 'editHint' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\wizard_web_registration_kts.xml:12: error: No resource identifier found for attribute 'titleText' in package 'android'
W:
W: C:\Users\marc\Downloads\b\com.kms.free\res\layout\wizard_web_registration_kts.xml:24: error: No resource identifier found for attribute 'titleText' in package 'android'
W:
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\cygwin64\tmp\brut_util_Jar_1216407143768294297.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 22, --version-code, 97, --version-name, 11.9.4.1294, --no-version-vectors, -F, C:\cygwin64\tmp\APKTOOL4181187643853471594.tmp, -0, arsc, -0, arsc, -I, C:\Users\marc\AppData\Local\apktool\framework\1.apk, -S, C:\Users\marc\Downloads\b\com.kms.free\res, -M, C:\Users\marc\Downloads\b\com.kms.free\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:485)
        at brut.androlib.Androlib.buildResources(Androlib.java:419)
        at brut.androlib.Androlib.build(Androlib.java:318)
        at brut.androlib.Androlib.build(Androlib.java:270)
        at brut.apktool.Main.cmdBuild(Main.java:224)
        at brut.apktool.Main.main(Main.java:75)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\cygwin64\tmp\brut_util_Jar_1216407143768294297.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 22, --version-code, 97, --version-name, 11.9.4.1294, --no-version-vectors, -F, C:\cygwin64\tmp\APKTOOL4181187643853471594.tmp, -0, arsc, -0, arsc, -I, C:\Users\marc\AppData\Local\apktool\framework\1.apk, -S, C:\Users\marc\Downloads\b\com.kms.free\res, -M, C:\Users\marc\Downloads\b\com.kms.free\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:454)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:471)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\cygwin64\tmp\brut_util_Jar_1216407143768294297.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 22, --version-code, 97, --version-name, 11.9.4.1294, --no-version-vectors, -F, C:\cygwin64\tmp\APKTOOL4181187643853471594.tmp, -0, arsc, -0, arsc, -I, C:\Users\marc\AppData\Local\apktool\framework\1.apk, -S, C:\Users\marc\Downloads\b\com.kms.free\res, -M, C:\Users\marc\Downloads\b\com.kms.free\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:448)
        ... 6 more
```
aapt crashes although there are no error messages used by it.

### Steps to Reproduce
`apktool d com.kms.free.apk
apktool b -f com.kms.free`

### Frameworks
None used

### APK
https://drive.google.com/file/d/0B2XIcd5M5qKuYnlZZ1hJSGNBcU0/view?usp=sharing

**Comment by iBotPeaches** [comment]
Interesting. These are resources I believe from the android support v7 library. I remember the `cardview` ones. I think this might be related to the problem I discovered in https://github.com/iBotPeaches/Apktool/issues/1361 but even after lots of research on that one I could never pinpoint the exact reasoning. 

Perhaps a fresh look again will resolve that.

**Comment by MarcMil** [comment]
I am not sure, but maybe a tool like GDB or valgrind might give a stacktrace of AAPT which may help investigating why aapt crashed exactly.
Maybe this might give some insight?

I think I have seen `No resource identifier found for attribute` multiple times already with different APKs, but rebuilding never led to a crash of AAPT if I remember correctly.

**Comment by iBotPeaches** [comment]
```
➜  1632 apktool d com.kms.free.apk 
I: Using Apktool 2.4.2-f545c2-SNAPSHOT on com.kms.free.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
➜  1632
➜  1632 apktool b com.kms.free --use-aapt2
I: Using Apktool 2.4.2-f545c2-SNAPSHOT
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Copying libs... (/META-INF/services)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
➜  1632 
```

3 years later, sorry.

Not reproducible on latest (2.5.0)
