### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException version 2.3.0

### ISSUE THREAD

**Issue by elmasrya** [iBotPeaches/Apktool#1635]
### Information
1. **Version** - 2.3.0
2. **Operating System** - Mac
3. **APK From** - Playstore

### Stacktrace/Logcat

```
I: Using Apktool 2.3.0 on app-debug.apk
I: Loading resource table...
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 22178
	at java.lang.String.substring(String.java:1963)
	at brut.androlib.res.decoder.StringBlock.getHTML(StringBlock.java:171)
	at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:326)
	at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:252)
	at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:231)
	at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:156)
	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:118)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:80)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:575)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:72)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:64)
	at brut.androlib.Androlib.getResTable(Androlib.java:68)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:214)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:109)
	at brut.apktool.Main.cmdDecode(Main.java:160)
	at brut.apktool.Main.main(Main.java:72)
```

### Steps to Reproduce
1. Download Mac wrapper script (Right click, Save Link As apktool)
2. Download `apktool-2`
3. Rename downloaded jar to `apktool.jar`
4. Move both `apktool.jar` & `apktool` to /usr/local/bin
5. Verify that both files are executable
6. Open Terminal
7. Navigate to `/usr/local/bin`
8. Run command: `./apktool d app_name.apk`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
N/A

### APK
If this APK can be freely shared, please upload/attach a link to it.
It cannot be shared.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Answer: Yes
2. If you are trying to install a modified apk, did you resign it? Answer: No
3. Are you using the latest apktool version? Answer: Yes

**Comment by iBotPeaches** [comment]
Do you have the application you used for this? Generally HTML decode errors are some clever string that broke the HTML decoder. These can usually be patched quite easily with the affected string.

At this point, I know where the error occurred due to stacktrace but I don't know if this was because of an earlier failure so having the exact application would make this easier to track down and fix.

**Comment by elmasrya** [comment]
So I cant send you the apk because the data is sensitive.

**Comment by iBotPeaches** [comment]
Understood. 

In situations like this, I cannot fix this. I apologize, but Apktool issues especially like this are near next to impossible to fix without the affected application. If you want to work something out in private where the affected string(s) of application can provided we can do that.

**Comment by seaguest** [comment]
I got exactly the same error, but I tried with 2.2.0 and it works.
