### ISSUE TITLE
G900P 6.0 - apps not working after build

### ISSUE THREAD

**Issue by Eduardgur** [iBotPeaches/Apktool#1636]
I have the same issue for few apk that Ive tried so far on this model 
SBrowser_4_LATEST
SecContacts_M_OSup_Legacy
SecContactsProvider
SystemUI
TeleService

### Information
1. **Apktool Version (`apktool -version`)** - 2.3.0
2. **Operating System (Mac, Linux, Windows)** - W10 64B
3. **APK From? (Playstore, ROM, Other)** - Stock rom

### Stacktrace/Logcat

```
`01-01 12:44:59.450 3347-3347/? I/Timeline: Timeline: Activity_launch_request id:com.sec.android.app.sbrowser time:194466
01-01 12:44:59.460 1907-4052/? V/WindowManager: addAppToken: AppWindowToken{9fcf2d3 token=Token{4a624c2 ActivityRecord{1f43d0d u0 com.sec.android.app.sbrowser/.SBrowserMainActivity t16}}} to stack=1 task=16 at 0
01-01 12:44:59.460 1907-2234/? D/ISSUE_DEBUG: InputChannelName : 675e441 Starting com.sec.android.app.sbrowser
01-01 12:44:59.510 1907-3337/? I/ActivityManager: Start proc 9482:com.sec.android.app.sbrowser/u0a150 for activity com.sec.android.app.sbrowser/.SBrowserMainActivity
01-01 12:44:59.510 1907-2234/? V/WindowStateAnimator: Finishing drawing window Window{675e441 u0 d0 Starting com.sec.android.app.sbrowser}: mDrawState=DRAW_PENDING
01-01 12:44:59.510 9482-9482/? W/SELinux: SELinux: seapp_context_lookup: seinfo=platform, level=s0:c512,c768, pkgname=com.sec.android.app.sbrowser 
01-01 12:44:59.560 1907-4076/? D/ActivityManager:  Launching com.sec.android.app.sbrowser, updated priority
01-01 12:44:59.590 1907-2118/? D/StatusBarManagerService: manageDisableList userId=0 what=0x0 pkg=Window{675e441 u0 d0 Starting com.sec.android.app.sbrowser}
01-01 12:44:59.590 1907-2111/? V/MARsPolicyManager: updatePackagesScore PackageInfo name -- com.sec.android.app.sbrowser
01-01 12:44:59.590 9482-9482/? W/ResourcesManager: getTopLevelResources: /system/app/SBrowser_4_LATEST/SBrowser_4_LATEST.apk / 1.0 running in com.sec.android.app.sbrowser rsrc of package null
01-01 12:44:59.610 9482-9482/? W/System: ClassLoader referenced unknown path: /system/app/SBrowser_4_LATEST/lib/arm
01-01 12:44:59.620 9482-9482/? W/ResourcesManager: getTopLevelResources: /system/app/SBrowser_4_LATEST/SBrowser_4_LATEST.apk / 1.0 running in com.sec.android.app.sbrowser rsrc of package null
01-01 12:44:59.630 9482-9482/? I/SBrowserUtils: getSystemProperty of sales_code : SPR
01-01 12:44:59.630 9482-9482/? I/SBrowserUtils: getSystemProperty of country_code : USA
01-01 12:44:59.630 9482-9482/? I/SBrowserUtils: getSystemProperty of country_code : USA
01-01 12:44:59.630 9482-9482/? I/SBrowserUtils: getSystemProperty of countryiso_code : US
01-01 12:44:59.640 9482-9482/? V/SBrowserContentProviderUtility: enableSyncClientProivder is called!
01-01 12:44:59.640 9482-9482/? I/SBrowserContentProviderUtility: enableScloudSync is called!
01-01 12:44:59.660 9482-9482/? D/ApplicationStatus: initialize application (com.sec.android.app.sbrowser.common.SBrowserMobileApplication@7a0b11d)
01-01 12:44:59.670 9482-9482/? W/ResourcesManager: getTopLevelResources: /system/app/SBrowser_4_LATEST/SBrowser_4_LATEST.apk / 1.0 running in com.sec.android.app.sbrowser rsrc of package null
01-01 12:44:59.680 9482-9482/? W/ResourcesManager: getTopLevelResources: /system/app/SBrowser_4_LATEST/SBrowser_4_LATEST.apk / 1.0 running in com.sec.android.app.sbrowser rsrc of package null
01-01 12:44:59.690 9482-9482/? I/[APP_LAUNCH]VerificationLog: SBrowserMainActivity - onCreate - obj=com.sec.android.app.sbrowser.SBrowserMainActivity@8dbad60
01-01 12:44:59.700 9482-9482/? D/StubSBrowser: onCreate
01-01 12:44:59.700 9482-9482/? D/StubSBrowser: getToday() :20170101
01-01 12:44:59.700 9482-9482/? D/StubSBrowser: getLastCheckDate :0
01-01 12:44:59.710 9482-9482/? D/ApplicationStatus: onStateChange activity = com.sec.android.app.sbrowser.SBrowserMainActivity@8dbad60 newState = 1
01-01 12:44:59.710 9482-9502/? D/StubSBrowser: http://vas.samsungapps.com/stub/stubUpdateCheck.as?appId=com.sec.android.app.sbrowser&versionCode=403018030&deviceId=SM-G900P&mcc=310&mnc=120&csc=SPR&sdkVer=23&pd=0
01-01 12:44:59.720 9482-9482/? D/SBrowserFeatureFlag: initialize : initSupportedPkg() succeed! 
01-01 12:44:59.720 9482-9482/? D/SBrowserFeatureFlag: initialize : loadCscFeatureValue() succeed! 
01-01 12:44:59.720 9482-9482/? D/SBrowserMainActivity: onCreate, MainTheme : Not China VOC
01-01 12:44:59.720 9482-9482/? D/SBrowserMainActivity: FastSnapshot : Normal inflate process
01-01 12:44:59.720 9482-9482/? E/SBrowserMainActivity: inflate
01-01 12:44:59.730 9482-9502/? D/StubSBrowser: xml parsing error
01-01 12:44:59.740 9482-9482/? D/SBrowserMobileApplication: setTabManagerHashMapByContextID key =com.sec.android.app.sbrowser.SBrowserMainActivity@8dbad60 value =com.sec.android.app.sbrowser.tabmodel.sbr.TabManager@955c878
01-01 12:44:59.760 9482-9482/? E/VerificationLog: SbrowserCVHoler - onFinishInflate - start
01-01 12:44:59.760 9482-9482/? E/VerificationLog: SbrowserCVHoler - onFinishInflate - end
01-01 12:44:59.860 9482-9482/? E/SBrowserMainActivity: Unable to load native library.
                                                       com.sec.swebview.base.SwProcessInitException
                                                           at com.sec.swebview.content.browser.SwimBrowserStartupController.startBrowserProcessesAsync(SwimBrowserStartupController.java:99)
                                                           at com.sec.swebview.content.browser.SwBrowserStartupController.startBrowserProcessesAsync(SwBrowserStartupController.java:82)
                                                           at com.sec.android.app.sbrowser.SBrowserMainActivity.startBrowserProcessAsync(SBrowserMainActivity.java:1338)
                                                           at com.sec.android.app.sbrowser.SBrowserMainActivity.onCreate(SBrowserMainActivity.java:288)
                                                           at android.app.Activity.performCreate(Activity.java:6876)
                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
                                                           at android.app.ActivityThread.access$1100(ActivityThread.java:221)
                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                           at android.os.Looper.loop(Looper.java:158)
                                                           at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                        Caused by: org.chromium.base.library_loader.ProcessInitException
                                                           at org.chromium.base.library_loader.LibraryLoader.loadAlreadyLocked(LibraryLoader.java:358)
                                                           at org.chromium.base.library_loader.LibraryLoader.ensureInitialized(LibraryLoader.java:143)
                                                           at org.chromium.content.browser.BrowserStartupController.prepareToStartBrowserProcess(BrowserStartupController.java:285)
                                                           at org.chromium.content.browser.BrowserStartupController.startBrowserProcessesAsync(BrowserStartupController.java:170)
                                                           at com.sec.swebview.content.browser.SwimBrowserStartupController.startBrowserProcessesAsync(SwimBrowserStartupController.java:82)
                                                           at com.sec.swebview.content.browser.SwBrowserStartupController.startBrowserProcessesAsync(SwBrowserStartupController.java:82) 
                                                           at com.sec.android.app.sbrowser.SBrowserMainActivity.startBrowserProcessAsync(SBrowserMainActivity.java:1338) 
                                                           at com.sec.android.app.sbrowser.SBrowserMainActivity.onCreate(SBrowserMainActivity.java:288) 
                                                           at android.app.Activity.performCreate(Activity.java:6876) 
                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206) 
                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
                                                           at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                           at android.os.Looper.loop(Looper.java:158) 
                                                           at android.app.ActivityThread.main(ActivityThread.java:7224) 
                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                        Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/secvision.jar", zip file "/system/framework/allshare.jar", zip file "/system/framework/twframework.jar", zip file "/system/framework/secsmartcard.jar", zip file "/system/app/SBrowser_4_LATEST/SBrowser_4_LATEST.apk"],nativeLibraryDirectories=[/system/app/SBrowser_4_LATEST/lib/arm, /system/app/SBrowser_4_LATEST/SBrowser_4_LATEST.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find "libchromium_android_linker.cr.so"
                                                           at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                           at java.lang.System.loadLibrary(System.java:1076)
                                                           at org.chromium.base.library_loader.Linker.ensureInitializedLocked(Linker.java:237)
                                                           at org.chromium.base.library_loader.Linker.isUsed(Linker.java:372)
                                                           at org.chromium.base.library_loader.LibraryLoader.loadAlreadyLocked(LibraryLoader.java:232)
                                                           at org.chromium.base.library_loader.LibraryLoader.ensureInitialized(LibraryLoader.java:143) 
                                                           at org.chromium.content.browser.BrowserStartupController.prepareToStartBrowserProcess(BrowserStartupController.java:285) 
                                                           at org.chromium.content.browser.BrowserStartupController.startBrowserProcessesAsync(BrowserStartupController.java:170) 
                                                           at com.sec.swebview.content.browser.SwimBrowserStartupController.startBrowserProcessesAsync(SwimBrowserStartupController.java:82) 
                                                           at com.sec.swebview.content.browser.SwBrowserStartupController.startBrowserProcessesAsync(SwBrowserStartupController.java:82) 
                                                           at com.sec.android.app.sbrowser.SBrowserMainActivity.startBrowserProcessAsync(SBrowserMainActivity.java:1338) 
                                                           at com.sec.android.app.sbrowser.SBrowserMainActivity.onCreate(SBrowserMainActivity.java:288) 
                                                           at android.app.Activity.performCreate(Activity.java:6876) 
                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206) 
                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
                                                           at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                           at android.os.Looper.loop(Looper.java:158) 
                                                           at android.app.ActivityThread.main(ActivityThread.java:7224) 
                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) `
```

### Steps to Reproduce
just decompile and build

### Frameworks + APK
Attached
[https://drive.google.com/file/d/0BxMfSDXkEoBdOGJpeDF1X0tnRWM/view?usp=sharing](url)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
Yes, Ive tried just d+b, tried to sign , tried to zipalign

2. If you are trying to install a modified apk, did you resign it?
yes

3. Are you using the latest apktool version?
yes 2.3.0

**Comment by Eduardgur** [comment]
Hello, 
Any update please?

**Comment by iBotPeaches** [comment]
Nothing at the apktool level is going wrong. Tests confirm all binaries are in tact before and after build. This must be some new level of app verification in place on this Samsung device which is being tripped.

I can't find anything wrong from the time it takes apktool to decode & rebuild this. I don't have a Samsung device so cannot test this at the host level.
