### ISSUE TITLE
Error while recompiling

### ISSUE THREAD

**Issue by bamby5624** [iBotPeaches/Apktool#1638]
I'm getting the following error while trying to re compile WhatsApp apk. The APK was not modified. I was just trying to decompile and then tried to recompile. 

Any help would be much appreciated.

### Information
1. **Apktool Version (`apktool -version`)** -  Tried with 2 versions: (a)  2.2.4 dirty & (b) 2.3.0 dirty
2. **Operating System (Mac, Linux, Windows)** - Kali Linux
3. **APK From? (Playstore, ROM, Other)** - Embedded in kali linux distro

### Stacktrace/Logcat

```
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/usr/bin/aapt, p, --min-sdk-version, 15, --target-sdk-version, 25, --version-code, 452018, --version-name, 2.17.351, --no-version-vectors, -F, /tmp/APKTOOL4795504688867751851.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/wrkdir/payload/decompiled/original/res, -M, /root/wrkdir/payload/decompiled/original/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:485)
	at brut.androlib.Androlib.buildResources(Androlib.java:419)
	at brut.androlib.Androlib.build(Androlib.java:318)
	at brut.androlib.Androlib.build(Androlib.java:270)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:75)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/usr/bin/aapt, p, --min-sdk-version, 15, --target-sdk-version, 25, --version-code, 452018, --version-name, 2.17.351, --no-version-vectors, -F, /tmp/APKTOOL4795504688867751851.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/wrkdir/payload/decompiled/original/res, -M, /root/wrkdir/payload/decompiled/original/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:454)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:471)
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?  Yes
2. If you are trying to install a modified apk, did you resign it? Not applicable as I've not modified the original apk.
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
Sorry for the delay.

There actually isn't any error in that stack trace. That is the failure/crash, but the warning of "why" would be directly above that. I think we have a few tickets open in regards to WhatsApp so I might need to double check some tickets before marking this.

**Comment by iBotPeaches** [comment]
```
➜  Bug1638 apktool d com.whatsapp_2.17.403-452075_minAPI15\(armeabi,armeabi-v7a,mips,x86\)\(nodpi\)_apkmirror.com.apk 
I: Using Apktool 2.2.5-0a1670-SNAPSHOT on com.whatsapp_2.17.403-452075_minAPI15(armeabi,armeabi-v7a,mips,x86)(nodpi)_apkmirror.com.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/connortumbleson/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1638 apktool b com.whatsapp_2.17.403-452075_minAPI15\(armeabi,armeabi-v7a,mips,x86\)\(nodpi\)_apkmirror.com
I: Using Apktool 2.2.5-0a1670-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
➜  Bug1638 
```

Could not duplicate.
