### ISSUE TITLE
NullPointerException when decompiling Facebook 146.0.0.53.92

### ISSUE THREAD

**Issue by PerLycke** [iBotPeaches/Apktool#1647]
### Information
1. 2.3.1-f7a872-SNAPSHOT
2. Mac
3. Play Store

### Stacktrace/Logcat

```
I: Using Apktool 2.3.1-f7a872-SNAPSHOT on facebook.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/per/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
Exception in thread "main" java.lang.NullPointerException
	at brut.androlib.res.data.value.ResEnumAttr.serializeBody(ResEnumAttr.java:56)
	at brut.androlib.res.data.value.ResAttr.serializeToResValuesXml(ResAttr.java:64)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:555)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:269)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:132)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:115)
	at brut.apktool.Main.cmdDecode(Main.java:160)
	at brut.apktool.Main.main(Main.java:72)
```

### Steps to Reproduce
1. apktool d facebook.apk

### APK
https://goo.gl/GY4sXW

**Comment by iBotPeaches** [comment]
According to the link posted, I could not replicate this on my Mac computer.

```
➜  Bug1647 apktool d com.facebook.katana_146.0.0.53.92-75931115_minAPI22\(armeabi-v7a\)\(280,360,400,420,480,560,640dpi\)_apkmirror.com.apk 
I: Using Apktool 2.2.5-0a1670-SNAPSHOT on com.facebook.katana_146.0.0.53.92-75931115_minAPI22(armeabi-v7a)(280,360,400,420,480,560,640dpi)_apkmirror.com.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/connortumbleson/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes10.dex...
I: Baksmaling classes11.dex...
I: Baksmaling classes12.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes4.dex...
I: Baksmaling classes5.dex...
I: Baksmaling classes6.dex...
I: Baksmaling classes7.dex...
I: Baksmaling classes8.dex...
I: Baksmaling classes9.dex...
I: Baksmaling assets/java.com.facebook.account.twofac.codegenerator.ui/java.com.facebook.account.twofac.codegenerator.ui2.dex...
I: Baksmaling assets/java.com.facebook.katana.internsettingsactivity/java.com.facebook.katana.internsettingsactivity2.dex...
I: Baksmaling assets/java.com.facebook.pages.browser/java.com.facebook.pages.browser2.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
```

Closing as could not duplicate.
