### ISSUE TITLE
Failed to build Settings.apk

### ISSUE THREAD

**Issue by nazem-hariri** [iBotPeaches/Apktool#1649]
### Information
1. **Apktool Version (`apktool -version`)** - 2.3
2. **Operating System (Mac, Linux, Windows)** - Windows 10
3. **APK From? (Playstore, ROM, Other)** - Tried Settings.apk from stock rom of  both Samsung j510h and Samsung j500h using proper framework apks 

### Steps to Reproduce
1. decompile Settings.apk
2. Do nothing just  rebuild the apk
3 The resulting apk has issues: the app crashes when user tries to edit time in the Settings app, logcat says that a resource should be an integer but found a string, it means the file has problem is resources and is built wrongly

### Frameworks
included in the attachments 

### APK
included zip file has the apk

the files are huge so uploaded them to:
https://files.fm/u/at66ww66

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? yes
3. Are you using the latest apktool version? yes

**Comment by iBotPeaches** [comment]
Do you have a `logcat` to make this search for bad resource easier?

Otherwise I have to decode, build, decode and compare which will have lots of differences.

**Comment by nazem-hariri** [comment]
This is the logcat

01-30 04:18:33.726 6580-6580/com.android.settings E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.android.settings, PID: 6580
                                                                    android.view.InflateException: Binary XML file line #28: Binary XML file line #28: Error inflating class com.sec.android.touchwiz.widget.TwTimePicker
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:551)
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
                                                                        at com.sec.android.touchwiz.app.TwTimePickerDialog.<init>(TwTimePickerDialog.java:172)
                                                                        at com.android.settings.DateTimeSettings.onCreateDialog(DateTimeSettings.java:498)
                                                                        at com.android.settings.SettingsPreferenceFragment$SettingsDialogFragment.onCreateDialog(SettingsPreferenceFragment.java:889)
                                                                        at android.app.DialogFragment.getLayoutInflater(DialogFragment.java:407)
                                                                        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:984)
                                                                        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1164)
                                                                        at android.app.BackStackRecord.run(BackStackRecord.java:793)
                                                                        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1557)
                                                                        at android.app.FragmentManagerImpl$1.run(FragmentManager.java:488)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:7325)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                     Caused by: android.view.InflateException: Binary XML file line #28: Error inflating class com.sec.android.touchwiz.widget.TwTimePicker
                                                                        at android.view.LayoutInflater.createView(LayoutInflater.java:657)
                                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
                                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:847)
                                                                        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:527)
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
                                                                        at com.sec.android.touchwiz.app.TwTimePickerDialog.<init>(TwTimePickerDialog.java:172) 
                                                                        at com.android.settings.DateTimeSettings.onCreateDialog(DateTimeSettings.java:498) 
                                                                        at com.android.settings.SettingsPreferenceFragment$SettingsDialogFragment.onCreateDialog(SettingsPreferenceFragment.java:889) 
                                                                        at android.app.DialogFragment.getLayoutInflater(DialogFragment.java:407) 
                                                                        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:984) 
                                                                        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1164) 
                                                                        at android.app.BackStackRecord.run(BackStackRecord.java:793) 
                                                                        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1557) 
                                                                        at android.app.FragmentManagerImpl$1.run(FragmentManager.java:488) 
                                                                        at android.os.Handler.handleCallback(Handler.java:739) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                        at android.os.Looper.loop(Looper.java:148) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:7325) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                     Caused by: java.lang.reflect.InvocationTargetException
                                                                        at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                        at android.view.LayoutInflater.createView(LayoutInflater.java:631)
                                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776) 
                                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:847) 
                                                                        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:527) 
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
                                                                        at com.sec.android.touchwiz.app.TwTimePickerDialog.<init>(TwTimePickerDialog.java:172) 
                                                                        at com.android.settings.DateTimeSettings.onCreateDialog(DateTimeSettings.java:498) 
                                                                        at com.android.settings.SettingsPreferenceFragment$SettingsDialogFragment.onCreateDialog(SettingsPreferenceFragment.java:889) 
                                                                        at android.app.DialogFragment.getLayoutInflater(DialogFragment.java:407) 
                                                                        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:984) 
                                                                        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1164) 
                                                                        at android.app.BackStackRecord.run(BackStackRecord.java:793) 
                                                                        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1557) 
                                                                        at android.app.FragmentManagerImpl$1.run(FragmentManager.java:488) 
                                                                        at android.os.Handler.handleCallback(Handler.java:739) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                        at android.os.Looper.loop(Looper.java:148) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:7325) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                     Caused by: java.lang.NumberFormatException: Invalid int: "Network may be monitored"
                                                                        at java.lang.Integer.invalidInt(Integer.java:138)
                                                                        at java.lang.Integer.parse(Integer.java:410)
                                                                        at java.lang.Integer.parseInt(Integer.java:367)
                                                                        at com.android.internal.util.XmlUtils.convertValueToInt(XmlUtils.java:133)
                                                                        at android.content.res.TypedArray.getInt(TypedArray.java:357)
                                                                        at com.sec.android.touchwiz.widget.TwTimePicker.<init>(TwTimePicker.java:99)
                                                                        at com.sec.android.touchwiz.widget.TwTimePicker.<init>(TwTimePicker.java:91)
                                                                        at com.sec.android.touchwiz.widget.TwTimePicker.<init>(TwTimePicker.java:87)
                                                                        at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                        at android.view.LayoutInflater.createView(LayoutInflater.java:631) 
                                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776) 
                                                                        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
                                                                        at android.view.LayoutInflater.rInflate(LayoutInflater.java:847) 
                                                                        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:527) 
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                                                                        at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
                                                                        at com.sec.android.touchwiz.app.TwTimePickerDialog.<init>(TwTimePickerDialog.java:172) 
                                                                        at com.android.settings.DateTimeSettings.onCreateDialog(DateTimeSettings.java:498) 
                                                                        at com.android.settings.SettingsPreferenceFragment$SettingsDialogFragment.onCreateDialog(SettingsPreferenceFragment.java:889) 
                                                                        at android.app.DialogFragment.getLayoutInflater(DialogFragment.java:407) 
                                                                        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:984) 
                                                                        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1164) 
                                                                        at android.app.BackStackRecord.run(BackStackRecord.java:793) 
                                                                        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1557) 
                                                                        at android.app.FragmentManagerImpl$1.run(FragmentManager.java:488) 
                                                                        at android.os.Handler.handleCallback(Handler.java:739) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                        at android.os.Looper.loop(Looper.java:148) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:7325) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by iBotPeaches** [comment]
```
android.view.InflateException: Binary XML file line #28: Binary XML file line #28: Error inflating class com.sec.android.touchwiz.widget.TwTimePicker
   Caused by: java.lang.NumberFormatException: Invalid int: "Network may be monitored"
```

Thanks. I'll take a look at what went wrong.

**Comment by iBotPeaches** [comment]
Very late here.

I looked for the failing string, which was being classified as an int.

```
➜  SecSettings2 grep -r -i 'Network may be monitored' *   
res/values/strings.xml:    <string name="ssl_ca_cert_warning">Network may be monitored</string>
```

Yay, one resource.

```
➜  SecSettings2 grep -r -i 'ssl_ca_cert_warning' *        
res/values/public.xml:    <public type="string" name="ssl_ca_cert_warning" id="0x7f0e0d2d" />
res/values/public.xml:    <public type="string" name="ssl_ca_cert_warning_message" id="0x7f0e0d31" />
res/values/strings.xml:    <string name="ssl_ca_cert_warning">Network may be monitored</string>
res/values/strings.xml:    <string name="ssl_ca_cert_warning_message">A trusted certificate on your device is allowing a third party to monitor your network activity, including your emails, apps, and secure websites</string>
```

I could not find any layout file that referenced this string that caused the error. At a bit of a loss of how to continue this investigation.

**Comment by iBotPeaches** [comment]
Sorry, I don't have Samsung. I didn't get to this in the past 3-4 years so it isn't happening.

Closing.
