### ISSUE TITLE
Errors when decompiling HTC U11 Oreo services.jar

### ISSUE THREAD

**Issue by jtothe4n** [iBotPeaches/Apktool#1652]
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.0
2. **Operating System (Mac, Linux, Windows)** - Win10 64 Bit
3. **APK From? (Playstore, ROM, Other)** - services.jar HTC U11 Oreo

### Stacktrace/Logcat

```
apktool d -b -f services.jar
I: Using Apktool 2.3.0 on services.jar
I: Baksmaling classes.dex...


Error occurred while disassembling class Lcom.android.server.DeviceIdleController$Constants; - skipping class
org.jf.util.ExceptionWithContext: The last instruction in method Lcom/android/server/DeviceIdleController$Constants;->dump(Ljava/io/PrintWriter;)V is truncated
        at org.jf.dexlib2.dexbacked.DexBackedMethodImplementation$1$1.readNextItem(DexBackedMethodImplementation.java:88)
        at org.jf.dexlib2.dexbacked.DexBackedMethodImplementation$1$1.readNextItem(DexBackedMethodImplementation.java:76)
        at org.jf.dexlib2.dexbacked.util.VariableSizeLookaheadIterator.computeNext(VariableSizeLookaheadIterator.java:60)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
        at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:300)
        at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:691)
        at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:275)
        at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:226)
        at org.jf.baksmali.Adaptors.MethodDefinition.<init>(MethodDefinition.java:92)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeVirtualMethods(ClassDefinition.java:325)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:112)
        at org.jf.baksmali.Baksmali.disassembleClass(Baksmali.java:152)
        at org.jf.baksmali.Baksmali.access$000(Baksmali.java:46)
        at org.jf.baksmali.Baksmali$1.call(Baksmali.java:76)
        at org.jf.baksmali.Baksmali$1.call(Baksmali.java:74)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Error while processing method Lcom/android/server/DeviceIdleController$Constants;->dump(Ljava/io/PrintWriter;)V

Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.jf.util.ExceptionWithContext: The last instruction in method Lcom/android/server/policy/GlobalActionsCust;-><clinit>()V is truncated
        at org.jf.baksmali.Baksmali.disassembleDexFile(Baksmali.java:92)
        at org.jf.baksmali.Baksmali.disassembleDexFile(Baksmali.java:48)
        at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:83)
        at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:38)
        at brut.androlib.Androlib.decodeSourcesSmali(Androlib.java:98)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:140)
        at brut.apktool.Main.cmdDecode(Main.java:160)
        at brut.apktool.Main.main(Main.java:72)
Caused by: java.util.concurrent.ExecutionException: org.jf.util.ExceptionWithContext: The last instruction in method Lcom/android/server/policy/GlobalActionsCust;-><clinit>()V is truncated
        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at org.jf.baksmali.Baksmali.disassembleDexFile(Baksmali.java:86)
        ... 7 more
Caused by: org.jf.util.ExceptionWithContext: The last instruction in method Lcom/android/server/policy/GlobalActionsCust;-><clinit>()V is truncated
        at org.jf.dexlib2.dexbacked.DexBackedMethodImplementation$1$1.readNextItem(DexBackedMethodImplementation.java:88)
        at org.jf.dexlib2.dexbacked.DexBackedMethodImplementation$1$1.readNextItem(DexBackedMethodImplementation.java:76)
        at org.jf.dexlib2.dexbacked.util.VariableSizeLookaheadIterator.computeNext(VariableSizeLookaheadIterator.java:60)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
        at org.jf.baksmali.Adaptors.ClassDefinition.findFieldsSetInStaticConstructor(ClassDefinition.java:72)
        at org.jf.baksmali.Adaptors.ClassDefinition.<init>(ClassDefinition.java:57)
        at org.jf.baksmali.Baksmali.disassembleClass(Baksmali.java:124)
        at org.jf.baksmali.Baksmali.access$000(Baksmali.java:46)
        at org.jf.baksmali.Baksmali$1.call(Baksmali.java:76)
        at org.jf.baksmali.Baksmali$1.call(Baksmali.java:74)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

I used @anestisb vdexExtractor (https://github.com/anestisb/vdexExtractor) to deodex btw.
Could be also the deodexing breaking it?

**Comment by anestisb** [comment]
@jtothe4n it's very unlikely that the vdex decompiler implemented from vdexExtractor is breaking the bytecode. The decompilation process is fully reverting the optimized bytecode back to the original bytecode. It also uses checksum verification to verify that the checksum of the decompiled output matches the checksum of the original bytecode, as stored in header section.

So if no errors were reported from vdexExtractor you should have an output bytecode that is identical to the one provided in original APK.

At any case if you can upload the oat and the matching vdex file somewhere, I can double check.

**Comment by jtothe4n** [comment]
Thanks for the clarification @anestisb 
Here you go, attached the files
[services.jar.zip](https://github.com/iBotPeaches/Apktool/files/1440497/services.jar.zip)

**Comment by anestisb** [comment]
Might be a Windows thing. Everything works fine in my setup (macOS) with the same ApkTool version (2.3.0).

```text
anestisb at devbook in /tmp/services.jar [2.7] $
$ apktool d -b -f services.jar
I: Using Apktool 2.3.0 on services.jar
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

anestisb at devbook in /tmp/services.jar [2.7] $
$ cp services.jar services_from_odex.jar

anestisb at devbook in /tmp/services.jar [2.7] $
$ ~/Tools/Android/vdexExtractor/bin/vdexExtractor -i services.vdex -o . -u
[INFO] Processing 1 file(s) from services.vdex
[INFO] 1 out of 1 Vdex files have been processed
[INFO] 1 Dex files have been extracted in total
[INFO] Extracted Dex files are available in '.'

anestisb at devbook in /tmp/services.jar [2.7] $
$ mv services.apk_classes.dex classes.dex; jar -uf services_from_odex.jar classes.dex

anestisb at devbook in /tmp/services.jar [2.7] $
$ apktool d -b -f services_from_odex.jar
I: Using Apktool 2.3.0 on services_from_odex.jar
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

anestisb at devbook in /tmp/services.jar [2.7] $
$ md5 *.jar
MD5 (services.jar) = 14e9214eafb40500f05f29748c2911b1
MD5 (services_from_odex.jar) = cea9e30d796262d2f302b82aa8902235
```

**Comment by jtothe4n** [comment]
Oops, I attached the wrong services.jar. 
The previous one I attached containes the broken recompiled dex.

[services.zip](https://github.com/iBotPeaches/Apktool/files/1440725/services.zip)

**Comment by jtothe4n** [comment]
Should be an issue with baksmali though @JesusFreke ?
