### ISSUE TITLE
denbo additional qualifier - unknown oem

### ISSUE THREAD

**Issue by thelasthope4U** [iBotPeaches/Apktool#1665]
I see this issue submitted many times before, have not found solution in other posts.  I am able to decompile another apk from same phone/ROM  I will include both apks if it helps.

Thanks for your time.

### Information
1. **Apktool Version (`apktool -version`)** - 2.3.0
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - ROM

### Stacktrace/Logcat
```
I: Using Apktool 2.3.0 on Settings.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Multiple resources: spec=0x7f020061 drawable/gemini_data_connection, config=-hdpi-v4
        at brut.androlib.res.data.ResType.addResource(ResType.java:66)
        at brut.androlib.res.data.ResType.addResource(ResType.java:55)
        at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:281)
        at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:231)
        at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:156)
        at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:118)
        at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:80)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:575)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:72)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:64)
        at brut.androlib.Androlib.getResTable(Androlib.java:68)
        at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:214)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:109)
        at brut.apktool.Main.cmdDecode(Main.java:160)
        at brut.apktool.Main.main(Main.java:72)
```
### Steps to Reproduce
1. apktool d Settings.apk

### Frameworks
frameworks from original ROM, added .zip to end of filename remove this.

The apk below exhibits the problem:
[framework-res.apk.zip](https://github.com/iBotPeaches/Apktool/files/1480173/framework-res.apk.zip)
[mediatek-res.apk.zip](https://github.com/iBotPeaches/Apktool/files/1480174/mediatek-res.apk.zip)

The apk below decompiles without exception:
[SystemUI.apk.zip](https://github.com/iBotPeaches/Apktool/files/1480204/SystemUI.apk.zip)
[SystemUI.odex.zip](https://github.com/iBotPeaches/Apktool/files/1480205/SystemUI.odex.zip)

### APK
apk from original ROM, added .zip to end of filename remove this.  odex included too
[Settings.apk.zip](https://github.com/iBotPeaches/Apktool/files/1480177/Settings.apk.zip)
[Settings.odex.zip](https://github.com/iBotPeaches/Apktool/files/1480178/Settings.odex.zip)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? fails in apktool d
2. If you are trying to install a modified apk, did you resign it? n/a yet
3. Are you using the latest apktool version? yes

**Comment by iBotPeaches** [comment]
Thanks for the detailed bug report. I have downloaded the apks and will take a look this weekend. These issues are either a bug in Apktool's configuration decoder or an actual change by the OEM to the internals of the ResConfig header (In the case of Huawei, in which we usually close as no-fix)

**Comment by iBotPeaches** [comment]
These applications have invalid configurations. They are referencing a qualifier known as "denbo" at the quality level.

This is following the same path that Huawei applications took with the "otab" and "otaa" qualifiers. These are not supported currently as changes to the qualifiers require AAPT updates & apktool updates. If changes to these qualifiers are then inherited or used by AOSP at a later date, then Apktool has effectively broken support to AOSP for supporting 1 foreign OEM.

In order to proceed further here, we will need more details on the ROM. The company/organization responsible for this in order to continue.

**Comment by iBotPeaches** [comment]
We unfortunately cannot proceed here. Blackbox investigation of unknown OEMs is not a priority and without any of the requested information from Nov 2017, we cannot proceed.

Closing due to no response.
