### ISSUE TITLE
error

### ISSUE THREAD

**Issue by hooman-pro** [iBotPeaches/Apktool#1670]
when i use this and build successfully an app
afetr run it in my android device it not working and by connection by usb to android studio logcat, I see this error (i change pakcage name)

```
11-23 14:36:45.956 19037-19037/? E/WAZE: Error: Could not load library  - exiting! dlopen failed: empty/missing DT_HASH/DT_GNU_HASH in "/data/app/com.waze.navigator-1/lib/arm/libwaze.so" (new hash type from the future?)
11-23 14:36:46.106 1152-2561/? E/HsmCoreServiceImpl: onTransact in code is: 102
11-23 14:36:47.356 19097-19107/? E/hisync.STUtils: java.lang.IllegalArgumentException: input.length=0; inputOffset=16; inputLen=-16
                                                       at javax.crypto.Cipher.checkInputOffsetAndCount(Cipher.java:1203)
                                                       at javax.crypto.Cipher.doFinal(Cipher.java:1539)
                                                       at com.huawei.android.hicloud.b.a.a(Aes128Cbc.java:264)
                                                       at com.huawei.android.hicloud.b.a.b(Aes128Cbc.java:131)
                                                       at com.huawei.android.hicloud.b.l.c(STUtils.java:103)
                                                       at com.huawei.android.hicloud.common.account.a.b(AccountInfo.java:192)
                                                       at com.huawei.android.hicloud.common.account.a.a(AccountInfo.java:147)
                                                       at com.huawei.android.hicloud.common.account.b.d(HiSyncAccount.java:368)
                                                       at com.huawei.android.hicloud.common.provider.HicloudLoginProvider.query(HicloudLoginProvider.java:89)
                                                       at android.content.ContentProvider.query(ContentProvider.java:1017)
                                                       at android.content.ContentProvider$Transport.query(ContentProvider.java:238)
                                                       at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:112)
                                                       at android.os.Binder.execTransact(Binder.java:453)
11-23 14:36:47.356 19097-19107/? E/hisync.STUtils: java.lang.IllegalArgumentException: input.length=0; inputOffset=16; inputLen=-16
                                                       at javax.crypto.Cipher.checkInputOffsetAndCount(Cipher.java:1203)
                                                       at javax.crypto.Cipher.doFinal(Cipher.java:1539)
                                                       at com.huawei.android.hicloud.b.a.a(Aes128Cbc.java:264)
                                                       at com.huawei.android.hicloud.b.a.b(Aes128Cbc.java:131)
                                                       at com.huawei.android.hicloud.b.l.c(STUtils.java:103)
                                                       at com.huawei.android.hicloud.common.account.a.b(AccountInfo.java:193)
                                                       at com.huawei.android.hicloud.common.account.a.a(AccountInfo.java:147)
                                                       at com.huawei.android.hicloud.common.account.b.d(HiSyncAccount.java:368)
                                                       at com.huawei.android.hicloud.common.provider.HicloudLoginProvider.query(HicloudLoginProvider.java:89)
                                                       at android.content.ContentProvider.query(ContentProvider.java:1017)
                                                       at android.content.ContentProvider$Transport.query(ContentProvider.java:238)
                                                       at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:112)
                                                       at android.os.Binder.execTransact(Binder.java:453)
                                                   
                                                   
                                                   [ 11-23 14:36:47.356 18894:18894 D/         ]
                                                   Request Body = {}
```

**Comment by iBotPeaches** [comment]
Looks like some anti-modification security. Without a package name rebuild I gave this a shot and got a similar error.

```
11-26 12:54:11.470  7158  7158 E AndroidRuntime: FATAL EXCEPTION: main
11-26 12:54:11.470  7158  7158 E AndroidRuntime: Process: com.waze, PID: 7158
11-26 12:54:11.470  7158  7158 E AndroidRuntime: java.lang.SecurityException: Signature check failed for com.waze
11-26 12:54:11.470  7158  7158 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1620)
11-26 12:54:11.470  7158  7158 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1573)
11-26 12:54:11.470  7158  7158 E AndroidRuntime: 	at com.google.android.gms.common.internal.zzay.zza(Unknown Source)
11-26 12:54:11.470  7158  7158 E AndroidRuntime: 	at com.google.android.gms.common.internal.zzd.zza(Unknown Source)
11-26 12:54:11.470  7158  7158 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.zzax.zzakp(Unknown Source)
11-26 12:54:11.470  7158  7158 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.zzbb.run(Unknown Source)
11-26 12:54:11.470  7158  7158 E AndroidRuntime: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
11-26 12:54:11.470  7158  7158 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-26 12:54:11.470  7158  7158 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
11-26 12:54:11.470  7158  7158 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
11-26 12:54:11.470  7158  7158 E AndroidRuntime: 	at com.google.android.gms.internal.zzbhq.run(Unknown Source)
11-26 12:54:11.470  7158  7158 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
11-26 12:54:11.480   782  1778 W ActivityManager:   Force finishing activity com.waze/.MainActivity
```

As Android evolves, so do the authors in preventing applications from simply being decoded and rebuilt under a different package name. Apktool job is to not find whatever complicated native/java code hashes/checks application, so I am going to close this. You will have to investigate this application and look if you can remove the checks this application is running.
