### ISSUE TITLE
Error recompile framework-res.apk android 8.0.0 

### ISSUE THREAD

**Issue by ale8530** [iBotPeaches/Apktool#1672]
### Information
1. **Apktool Version 2.3.1 snapshot** -
2. **Operating System Linux** -
3. **APK From? MIUI 9 android 8.0** -

File-->[framework-res.zip](https://github.com/iBotPeaches/Apktool/files/1505769/framework-res.zip)

### Stacktrace/Logcat
```
java -jar apktool-2.3.1.jar b framework-res
I: Using Apktool 2.3.1-ef9be8-SNAPSHOT
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
W:/data/tools/lib/framework-res/res/values/styles.xml:979: error: Resource entry TextAppearance.StatusBar.EventContent already has bag item textColor.
W:/data/tools/lib/framework-res/res/values/styles.xml:978: Originally defined here.
W: 
W:/data/tools/lib/framework-res/res/values/styles.xml:984: error: Resource entry TextAppearance.StatusBar.EventContent.Title already has bag item textStyle.
W:/data/tools/lib/framework-res/res/values/styles.xml:983: Originally defined here.
W: 
W:/data/tools/lib/framework-res/res/values/styles.xml:986: error: Resource entry TextAppearance.StatusBar.EventContent.Title already has bag item textColor.
W:/data/tools/lib/framework-res/res/values/styles.xml:985: Originally defined here.
W:
W:/data/tools/lib/framework-res/res/values/styles.xml:988: error: Resource entry TextAppearance.StatusBar.EventContent.Title already has bag item fontFamily.
W:/data/tools/lib/framework-res/res/values/styles.xml:987: Originally defined here.
W: 
W:/data/tools/lib/framework-res/res/values/styles.xml:5002: error: Resource entry TextAppearance.StatusBar.EventContent.Emphasis already has bag item textColor.
W:/data/tools/lib/framework-res/res/values/styles.xml:5001: Originally defined here.
W: 
W:/data/tools/lib/framework-res/res/values/styles.xml:5007: error: Resource entry TextAppearance.StatusBar.EventContent.Info already has bag item textColor.
W:/data/tools/lib/framework-res/res/values/styles.xml:5006: Originally defined here.
W: 
W: /data/tools/lib/framework-res/res/values/styles.xml:5015: error: Resource entry TextAppearance.StatusBar.EventContent.Time already has bag item textColor.
W: /data/tools/lib/framework-res/res/values/styles.xml:5014: Originally defined here.
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_4785788580533700816.tmp, p, --forced-package-id, 1, --min-sdk-version, 26, --target-sdk-version, 26, --version-code, 26, --version-name, 8.0.0, --no-version-vectors, -F, /tmp/APKTOOL2975761935876221095.tmp, -x, -0, arsc, -0, arsc, -S, /home/ale8530/Scrivania/jBART-chiron_8.0/data/tools/lib/framework-res/res, -M, /home/ale8530/Scrivania/jBART-chiron_8.0/data/tools/lib/framework-res/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:485)
	at brut.androlib.Androlib.buildResources(Androlib.java:419)
	at brut.androlib.Androlib.build(Androlib.java:318)
	at brut.androlib.Androlib.build(Androlib.java:270)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:75)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_4785788580533700816.tmp, p, --forced-package-id, 1, --min-sdk-version, 26, --target-sdk-version, 26, --version-code, 26, --version-name, 8.0.0, --no-version-vectors, -F, /tmp/APKTOOL2975761935876221095.tmp, -x, -0, arsc, -0, arsc, -S, /home/ale8530/Scrivania/jBART-chiron_8.0/data/tools/lib/framework-res/res, -M, /home/ale8530/Scrivania/jBART-chiron_8.0/data/tools/lib/framework-res/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:456)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:471)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_4785788580533700816.tmp, p, --forced-package-id, 1, --min-sdk-version, 26, --target-sdk-version, 26, --version-code, 26, --version-name, 8.0.0, --no-version-vectors, -F, /tmp/APKTOOL2975761935876221095.tmp, -x, -0, arsc, -0, arsc, -S, /home/ale8530/Scrivania/jBART-chiron_8.0/data/tools/lib/framework-res/res, -M, /home/ale8530/Scrivania/jBART-chiron_8.0/data/tools/lib/framework-res/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:450)
	... 6 more
```

**Comment by ale8530** [comment]
I think the problem is due when installing the framework

java -jar apktool-2.3.1.jar if framework-res.apk
**W: null
W: null
W: null
W: null**
I: Framework installed to: /home/ale8530/.local/share/apktool/framework/1.apk

**Comment by ale8530** [comment]
I have checked problem , when decompile this framework apktool create double string

W: /data/tools/lib/framework-res/res/values/styles.xml:5015: error: Resource entry TextAppearance.StatusBar.EventContent.Time already has bag item textColor.
W: /data/tools/lib/framework-res/res/values/styles.xml:5014: Originally defined here.

**Comment by bshuy2003** [comment]
Did you resolve your problem? I have the same error when recompile file framework-res.apk of miui 9 android 8. After fixing styles.xml, framework-res was recompiled successfully. But this file doesn't work in the rom. My device is stucked on logo of botting.

**Comment by CunningLogic** [comment]
People need to relax on android 8, lots of changes to everything, smali doesnt even fully support it yet

**Comment by ale8530** [comment]
I have bootloop problem caused from MIUI not apktool

**Comment by talha1993** [comment]
have

**Comment by gsmmazhar** [comment]
how you do this
