### ISSUE TITLE
Error: Integer types not allowed (at 'autoSizeTextType' with value '1')

### ISSUE THREAD

**Issue by duanjason** [iBotPeaches/Apktool#1674]
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.0
2. **Operating System (Mac, Linux, Windows)** - Mac and Window. Not sure about Linux
3. **APK From? (Playstore, ROM, Other)** -  Compiled from the source

### Stacktrace/Logcat
```
..... AndroidStudioProjects/APKTool/app/build/outputs/apk/_Generated/TestApk/res/layout/content_main.xml:4: error: Error: Integer types not allowed (at 'autoSizeTextType' with value '1'). And failed.

brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\IBM_AD~1\AppData\Local\Temp\brut_util_Jar_780322057631553104.tmp, p, --forced-package-id, 127, --min-sdk-version, 26, --target-sdk-version, 26, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, C:\Users\IBM_AD~1\AppData\Local\Temp\APKTOOL4110286854525879315.tmp, -0, arsc, -0, arsc, -I, C:\Users\IBM_ADMIN\AndroidStudioProjects\WinCrash\app\build\outputs\apk\framework\1.apk, -S, C:\Users\IBM_ADMIN\AndroidStudioProjects\WinCrash\app\build\outputs\apk\_Generated\TestApk\res, -M, C:\Users\IBM_ADMIN\AndroidStudioProjects\WinCrash\app\build\outputs\apk\_Generated\TestApk\AndroidManifest.xml]
```

### Steps to Reproduce
1. `apktool `
Use Android Studio version 3.x to create a default project (target to Android 8) that has a text label. Add " android:autoSizeTextType="uniform" " to the TextView of the label in the content_main.xml. Note: android:autoSizeTextType is a new Android 8 attribute. My code runs the Apktools on the project and get the error above. If I don't add the autoSizeTextType attribute, my code runs fine.

The interesting part is I specify a "uniform" as the value, but it is translated to "1". I wonder where the translation happens and which file contains the defined values of the attribute. If I have the information, I may be able to figure out where the problem is.

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

The code is running on Mac/Windows machine. The problem occurred before the apk is run on a mobile device.

### APK
If this APK can be freely shared, please upload/attach a link to it.
It is just a plain default app from Android Studio new project.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
I do not modify anything apktool code

2. If you are trying to install a modified apk, did you resign it?
Not at that point yet.

3. Are you using the latest apktool version?
Yes

**Comment by duanjason** [comment]
I downloaded the apktool-2.3.0.jar from your site and run the decoding. I got the decoded section below:
TextView n1:layout_width="wrap_content" n1:layout_height="wrap_content" n1:text="Hello World!" n1:autoSizeTextType="1" n2:layout_constraintBottom_toBottomOf="parent"  ....

Should the n1:autoSizeTextType="1"  be decoded as n1:autoSizeTextType="uniform"  ?

**Comment by iBotPeaches** [comment]
Appears from my research that this should be a text value, which is probably tokenized as "1" internally. 

```
android:autoSizeTextType="uniform"
```

I will need to do some research to see what the proper solution is here. Either decoding is broken, or we need to untokenize these resources back to human readable values.

**Comment by duanjason** [comment]
@iBotPeaches thanks.

I ran the apktool b command to build the decoded source. I got the error below. It complains autoSizeTextType identifier not found. I got the same error if I use your jar in my code. However, if I compile the source and use the apktool-cli-all.jar in the Apktool-2.3.0/brut.apktool/apktool-cli/build/libs in my code, then I got the error in my original report. Am I using the right jar or the jar from the site doesn't have everything it needs?

my-mbp:decode myname$ ./apktool b app-debug
I: Using Apktool 2.3.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: /Users/myname/tmp/decode/app-debug/res/layout/abc_screen_toolbar.xml:5: error: No resource identifier found for attribute 'keyboardNavigationCluster' in package 'android'
W: 
W: /Users/myname/tmp/decode/app-debug/res/layout/content_main.xml:4: error: No resource identifier found for attribute 'autoSizeTextType' in package 'android'
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/rg/z171b2514hz5wjfmxx1lpj8w0000gn/T/brut_util_Jar_1777498077591960649.tmp, p, --forced-package-id, 127, --min-sdk-version, 26, --target-sdk-version, 26, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /var/folders/rg/z171b2514hz5wjfmxx1lpj8w0000gn/T/APKTOOL5162487692981055122.tmp, -0, arsc, -0, arsc, -I, /Users/myname/Library/apktool/framework/1.apk, -S, /Users/myname/tmp/decode/app-debug/res, -M, /Users/myname/tmp/decode/app-debug/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:485)
	at brut.androlib.Androlib.buildResources(Androlib.java:419)
	at brut.androlib.Androlib.build(Androlib.java:318)
	at brut.androlib.Androlib.build(Androlib.java:270)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:75)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/rg/z171b2514hz5wjfmxx1lpj8w0000gn/T/brut_util_Jar_1777498077591960649.tmp, p, --forced-package-id, 127, --min-sdk-version, 26, --target-sdk-version, 26, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /var/folders/rg/z171b2514hz5wjfmxx1lpj8w0000gn/T/APKTOOL5162487692981055122.tmp, -0, arsc, -0, arsc, -I, /Users/myname/Library/apktool/framework/1.apk, -S, /Users/myname/tmp/decode/app-debug/res, -M, /Users/myname/tmp/decode/app-debug/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:454)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:471)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/rg/z171b2514hz5wjfmxx1lpj8w0000gn/T/brut_util_Jar_1777498077591960649.tmp, p, --forced-package-id, 127, --min-sdk-version, 26, --target-sdk-version, 26, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /var/folders/rg/z171b2514hz5wjfmxx1lpj8w0000gn/T/APKTOOL5162487692981055122.tmp, -0, arsc, -0, arsc, -I, /Users/myname/Library/apktool/framework/1.apk, -S, /Users/myname/tmp/decode/app-debug/res, -M, /Users/myname/tmp/decode/app-debug/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:448)

**Comment by iBotPeaches** [comment]
If your application has any resources from 8.1 (Oreo API 27) it will fail, as there are new resources.

However, the two resources you listed failing are both from API 26

https://developer.android.com/reference/android/R.attr.html#keyboardNavigationCluster
https://developer.android.com/reference/android/R.attr.html#autoSizeTextType

As you can see both are added in API26.

Try

```
apktool empty-framework-dir

(if you have more than 1.apk)
apktool empty-framework-dir --force
```

**Comment by duanjason** [comment]
@iBotPeaches 
You are right. According to the doc below, the internal value is 0 or 1.

https://developer.android.com/reference/android/widget/TextView.html#attr_android:autoSizeTextType

**Comment by duanjason** [comment]
After I ran the "apktool empty-framework-dir" command, now I got the value not allowed error.

my-mbp:decode myname$ ./apktool b app-debug 
I: Using Apktool 2.3.0-dirty
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: /Users/myname/tmp/decode/app-debug/res/layout/content_main.xml:4: error: Error: Integer types not allowed (at 'autoSizeTextType' with value '1').
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/rg/z171b2514hz5wjfmxx1lpj8w0000gn/T/brut_util_Jar_759714114662609974.tmp, p, --forced-package-id, 127, --min-sdk-version, 26, --target-sdk-version, 26, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /var/folders/rg/z171b2514hz5wjfmxx1lpj8w0000gn/T/APKTOOL1026488455331632622.tmp, -0, arsc, -0, arsc, -I, /Users/myname/Library/apktool/framework/1.apk, -S, /Users/myname/tmp/decode/app-debug/res, -M, /Users/myname/tmp/decode/app-debug/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:485)
	at brut.androlib.Androlib.buildResources(Androlib.java:419)
	at brut.androlib.Androlib.build(Androlib.java:318)
	at brut.androlib.Androlib.build(Androlib.java:270)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:75)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/rg/z171b2514hz5wjfmxx1lpj8w0000gn/T/brut_util_Jar_759714114662609974.tmp, p, --forced-package-id, 127, --min-sdk-version, 26, --target-sdk-version, 26, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /var/folders/rg/z171b2514hz5wjfmxx1lpj8w0000gn/T/APKTOOL1026488455331632622.tmp, -0, arsc, -0, arsc, -I, /Users/myname/Library/apktool/framework/1.apk, -S, /Users/myname/tmp/decode/app-debug/res, -M, /Users/myname/tmp/decode/app-debug/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:454)

	... 6 more

**Comment by iBotPeaches** [comment]
Yep, that is the error I am investigating. So you are set just waiting at that point.

**Comment by duanjason** [comment]
@iBotPeaches great. thanks. I am using API 26, not 27.

**Comment by iBotPeaches** [comment]
I added a test for this and can't seem to find a problem. Commit above, passing tests - https://travis-ci.org/iBotPeaches/Apktool/builds/308950244

**Comment by duanjason** [comment]
hi @iBotPeaches I am not sure if I understand you comment above. Do you mean you can't recreate the issue with the test case? If so, I can upload my apk.  You can try and you will see the problem.

**Comment by iBotPeaches** [comment]
That is correct. I can not duplicate the issue. Test case above shows no problem.

**Comment by duanjason** [comment]
Can you give this apk a try? Git doesn't support apk file type. I zipped up the apk. You can unzip it back...

What I did was use apktool to decode it, then use apktool to build the decoded folder and you will see the issue.
[app-debug.apk.zip](https://github.com/iBotPeaches/Apktool/files/1514325/app-debug.apk.zip)

**Comment by duanjason** [comment]
Hi @iBotPeaches any luck to recreate the problem?

**Comment by iBotPeaches** [comment]
```
➜  1674 apktool d app-debug.apk 
I: Using Apktool 2.3.1-ef9be8-SNAPSHOT on app-debug.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  1674 apktool b app-debug
I: Using Apktool 2.3.1-ef9be8-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Building apk file...
I: Copying unknown files/dir...
➜  1674 
```

Could not duplicate sorry. I added a test and ensured all is working from my side so closing this.

**Comment by duanjason** [comment]
Hi @iBotPeaches,

I can recreate the problem on my macbook pro and my windows 7 laptop following the same steps all the time. Both machines have Android Studio 2.3.3/3 installed.

I got a windows 7 VM with no Android stuff on it. I download the apktool windows script and the 2.3.0 jar from your site to a tmp directory and I run the tool from that directory. I don't see the error. However, the apk is not generated at the end. 

Is the "I: Copying unknown files/dir..." an expected output?

What would be the possible cause of the problem? Does Apktool use libraries that are on the system already? What is the best way to debug this issue?

=========================
Below is the console from the VM

C:\tmp\decode>apktool.bat d app-debug.apk
I: Using Apktool 2.3.0 on app-debug.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\pttest\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

C:\tmp\decode>apktool.bat b app-debug
I: Using Apktool 2.3.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Building apk file...
I: Copying unknown files/dir...

C:\tmp\decode>dir
 Volume in drive C has no label.
 Volume Serial Number is 306B-8819

 Directory of C:\tmp\decode

11/29/2017  03:36 PM    <DIR>          .
11/29/2017  03:36 PM    <DIR>          ..
11/29/2017  03:24 PM               181 apktool.bat
11/29/2017  03:24 PM         5,882,586 apktool.jar
11/29/2017  03:37 PM    <DIR>          app-debug
11/29/2017  03:22 PM         2,008,394 app-debug-o.apk
               3 File(s)      7,891,161 bytes
               3 Dir(s)  27,060,617,216 bytes free

C:\tmp\decode>

**Comment by duanjason** [comment]
More information, on the VM, the decode value of the attribute is correct now. It is the "uniform", not the "1"

<TextView n1:layout_height="wrap_content" n1:layout_width="wrap_content" n2:layout_constraintTop_toTopOf="parent" n2:layout_constraintRight_toRightOf="parent" n2:layout_constraintLeft_toLeftOf="parent" n2:layout_constraintBottom_toBottomOf="parent" n1:autoSizeTextType="uniform" n1:text="Hello World!"/>

**Comment by duanjason** [comment]
@iBotPeaches 

The apktool empty-framework-dir command and a reboot of my machines fixed the problem. Thank you very much for your help.
