### ISSUE TITLE
can't recompile ... stuck in font.xml

### ISSUE THREAD

**Issue by SikAsik** [iBotPeaches/Apktool#1677]
### Information
1. **Apktool Version (2.3.0)** -
2. **Operating System (Linux)** -
3. **APK From? (Playstore)** -

### Stacktrace/Logcat
`xxx@xxx ~/xxx/Grab/5290 $ apktool d 5290.apk -o test
I: Using Apktool 2.3.0 on 5290.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/xxx/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
S: Could not decode file, replacing by FALSE value: font/sanomat_medium_normal.ttf
S: Could not decode file, replacing by FALSE value: font/sanomat_regular_normal.ttf
S: Could not decode file, replacing by FALSE value: font-km/notosans_khmer_bold.ttf
S: Could not decode file, replacing by FALSE value: font-my/notosans_myanmar_regular.ttf
S: Could not decode file, replacing by FALSE value: font-my/notosans_myanmar_bold.ttf
S: Could not decode file, replacing by FALSE value: font/sanomat_medium_italic.ttf
S: Could not decode file, replacing by FALSE value: font-km/notosans_khmer_regular.ttf
S: Could not decode file, replacing by FALSE value: font/grab_icon_driver.ttf
S: Could not decode file, replacing by FALSE value: font/uk_number_plate.ttf
S: Could not decode file, replacing by FALSE value: font/sanomat_light_normal.ttf
S: Could not decode file, replacing by FALSE value: font/sanomat_regular_italic.ttf
S: Could not decode file, replacing by FALSE value: font/sanomat_bold_normal.ttf
S: Could not decode file, replacing by FALSE value: font-zg/zawgyi_one.ttf
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

xxx@xxx ~/xxx/Grab/5290 $ apktool b test
I: Using Apktool 2.3.0
I: Checking whether resources has changed...
I: Building resources...
W: /home/xxx/xxx/Grab/5290/test/res/values/fonts.xml:3: error: Resource entry grab_icon_driver is already defined.
W: res/font/grab_icon_driver.ttf:0: Originally defined here.
W: 
W: /home/xxx/xxx/Grab/5290/test/res/values/fonts.xml:4: error: Resource entry sanomat_bold_normal is already defined.
W: res/font/sanomat_bold_normal.ttf:0: Originally defined here.
W: 
W: /home/xxx/xxx/Grab/5290/test/res/values/fonts.xml:5: error: Resource entry sanomat_light_normal is already defined.
W: res/font/sanomat_light_normal.ttf:0: Originally defined here.
W: 
W: /home/xxx/xxx/Grab/5290/test/res/values/fonts.xml:6: error: Resource entry sanomat_medium_italic is already defined.
W: res/font/sanomat_medium_italic.ttf:0: Originally defined here.
W: 
W: /home/xxx/xxx/Grab/5290/test/res/values/fonts.xml:7: error: Resource entry sanomat_medium_normal is already defined.
W: res/font/sanomat_medium_normal.ttf:0: Originally defined here.
W: 
W: /home/xxx/xxx/Grab/5290/test/res/values/fonts.xml:8: error: Resource entry sanomat_regular_italic is already defined.
W: res/font/sanomat_regular_italic.ttf:0: Originally defined here.
W: 
W: /home/xxx/xxx/Grab/5290/test/res/values/fonts.xml:9: error: Resource entry sanomat_regular_normal is already defined.
W: res/font/sanomat_regular_normal.ttf:0: Originally defined here.
W: 
W: /home/xxx/xxx/Grab/5290/test/res/values/fonts.xml:10: error: Resource entry uk_number_plate is already defined.
W: res/font/uk_number_plate.ttf:0: Originally defined here.
W: 
W: /home/xxx/xxx/Grab/5290/test/res/values-zg/fonts.xml:3: error: Resource entry zawgyi_one is already defined.
W: res/font-zg/zawgyi_one.ttf:0: Originally defined here.
W: 
W: /home/xxx/xxx/Grab/5290/test/res/values-km/fonts.xml:3: error: Resource entry notosans_khmer_bold is already defined.
W: res/font-km/notosans_khmer_bold.ttf:0: Originally defined here.
W: 
W: /home/xxx/xxx/Grab/5290/test/res/values-km/fonts.xml:4: error: Resource entry notosans_khmer_regular is already defined.
W: res/font-km/notosans_khmer_regular.ttf:0: Originally defined here.
W: 
W: /home/xxx/xxx/Grab/5290/test/res/values-my/fonts.xml:3: error: Resource entry notosans_myanmar_bold is already defined.
W: res/font-my/notosans_myanmar_bold.ttf:0: Originally defined here.
W: 
W: /home/xxx/xxx/Grab/5290/test/res/values-my/fonts.xml:4: error: Resource entry notosans_myanmar_regular is already defined.
W: res/font-my/notosans_myanmar_regular.ttf:0: Originally defined here.
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_125889574106645807.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 26, --version-code, 385, --version-name, 5.29.0, --no-version-vectors, -F, /tmp/APKTOOL11291662710544370107.tmp, -0, arsc, -0, res/raw/livenessmodel, -0, der, -0, res/raw/model, -0, arsc, -I, /home/xxx/.local/share/apktool/framework/1.apk, -S, /home/xxx/xxx/Grab/5290/test/res, -M, /home/xxx/xxx/Grab/5290/test/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:485)
	at brut.androlib.Androlib.buildResources(Androlib.java:419)
	at brut.androlib.Androlib.build(Androlib.java:318)
	at brut.androlib.Androlib.build(Androlib.java:270)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:75)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_125889574106645807.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 26, --version-code, 385, --version-name, 5.29.0, --no-version-vectors, -F, /tmp/APKTOOL11291662710544370107.tmp, -0, arsc, -0, res/raw/livenessmodel, -0, der, -0, res/raw/model, -0, arsc, -I, /home/xxx/.local/share/apktool/framework/1.apk, -S, /home/xxx/xxx/Grab/5290/test/res, -M, /home/xxx/xxx/Grab/5290/test/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:454)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:471)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_125889574106645807.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 26, --version-code, 385, --version-name, 5.29.0, --no-version-vectors, -F, /tmp/APKTOOL11291662710544370107.tmp, -0, arsc, -0, res/raw/livenessmodel, -0, der, -0, res/raw/model, -0, arsc, -I, /home/xxx/.local/share/apktool/framework/1.apk, -S, /home/xxx/xxx/Grab/5290/test/res, -M, /home/xxx/xxx/Grab/5290/test/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:448)
	... 6 more
`

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
Playstore : https://play.google.com/store/apps/details?id=com.grabtaxi.driver2&hl=in
alt : http://goo.gl/qpFkjn (version 2.9.0)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes,
2. If you are trying to install a modified apk, did you resign it? not yet, because can't recompile
3. Are you using the latest apktool version? sure, 2.3.0

**Comment by iBotPeaches** [comment]
This was recently fixed and will be in 2.3.1 - https://github.com/iBotPeaches/Apktool/commit/5e1a47a827032a082c4a9a6f33ef695dd6ef7019

**Comment by SikAsik** [comment]
when you release new version? can i get firstly, like beta file maybe..

**Comment by iBotPeaches** [comment]
@SikAsik Before the end of the year. You can always build it yourself from master.

**Comment by SikAsik** [comment]
thanks for respond.. i'll try...

**Comment by SikAsik** [comment]
it's magic.. :)

`xxx@xxx ~/xxx/Grab/5290 $ apktool d -s 5290_Ori.apk -o ORIFULL
I: Using Apktool 2.3.1-3264f1-SNAPSHOT on 5290_Ori.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/xxx/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying raw classes.dex file...
I: Copying raw classes2.dex file...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
xxx@xxx ~/xxx/Grab/5290 $ apktool b ORIFULL
I: Using Apktool 2.3.1-3264f1-SNAPSHOT
I: Copying ORIFULL classes.dex file...
I: Copying ORIFULL classes2.dex file...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...`

big thanks....
