### ISSUE TITLE
latest release of apktool (2.3.0) could not decompile apk from Huawei Mate10

### ISSUE THREAD

**Issue by NeoInChina** [iBotPeaches/Apktool#1682]
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.0
2. **Operating System (Mac, Linux, Windows)** - Mac
3. **APK From? (Playstore, ROM, Other)** - Huawei Mate10 Pro

### Stacktrace/Logcat

```


I: Decoding values */* XMLs...
Exception in thread "main" java.lang.NullPointerException
	at brut.androlib.res.data.value.ResEnumAttr.serializeBody(ResEnumAttr.java:56)
	at brut.androlib.res.data.value.ResAttr.serializeToResValuesXml(ResAttr.java:64)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:531)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:268)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:132)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:115)
	at brut.apktool.Main.cmdDecode(Main.java:160)
	at brut.apktool.Main.main(Main.java:72)
```

### Steps to Reproduce
1. `apktool ` if -p 1 framework-res.apk
2, apktool d -p 1 SystemUI.apk

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
[framework-res.apk.zip](https://github.com/iBotPeaches/Apktool/files/1543247/framework-res.apk.zip)
[SystemUI.apk.zip](https://github.com/iBotPeaches/Apktool/files/1543253/SystemUI.apk.zip)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? no
3. Are you using the latest apktool version? yes

**Comment by iBotPeaches** [comment]
Sorry for the long delay, this application is a Huawei application and like MIUI they have added custom qualifiers. There is no rebuild support, but you can use `--keep-broken-res` to at least complete the decode process.

We are tracking Huawei already at #1521

**Comment by Mouradif** [comment]
Same issue with `--keep-broken-res` too
