### ISSUE TITLE
Error while Decompiling an apk with no Res (type of Obfuscation)

### ISSUE THREAD

**Issue by parind** [iBotPeaches/Apktool#1684]
### Information
1. Apktool Version - 2.3.0
2. Operating System - Windows
3. APK From - Play Store

### Stacktrace/Logcat

```
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: Error copying file: ??
.xml
        at brut.androlib.Androlib.decodeUnknownFiles(Androlib.java:224)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:165)
        at brut.apktool.Main.cmdDecode(Main.java:160)
        at brut.apktool.Main.main(Main.java:72)
Caused by: brut.directory.DirectoryException: Error copying file: ??    .xml
        at brut.directory.DirUtil.copyToDir(DirUtil.java:88)
        at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:208)
        at brut.androlib.Androlib.decodeUnknownFiles(Androlib.java:217)
        ... 3 more
Caused by: java.io.FileNotFoundException: APK\unknown\??       .xml (The filename, directory name, or volume label syntax is incorrect)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at brut.directory.DirUtil.copyToDir(DirUtil.java:84)
        ... 5 more
```

### Steps to Reproduce
1. apktool d APK.apk 

### APK
https://my.pcloud.com/publink/show?code=XZQO5J7Z8R4EEfBmac5GkN15fKfaSpfyHdjX

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? - Yes, I have
2. If you are trying to install a modified apk, did you resign it? - No Point for this question as the apk wont get Decompiled First
3. Are you using the latest apktool version? - Yes, for sure I am, as on the date of this Post :- 2.3.0

The things I analyzed are - this apk has no "res" folder, and the files meant to be inside the "res" folder are located on the 'root' of the apk. Seems to be some form of Obfuscation. Only the values from the resources.arsc are decoding, nothing else. (also classes.dex, but this is regarding the resources 😄  )

**Comment by iBotPeaches** [comment]
Sorry for the delay, this is a Windows issue with strange filenames. Which is being tracked at #1460 

Closing as duplicate.
