### ISSUE TITLE
apktool b fails on non-ascii activity files

### ISSUE THREAD

**Issue by gilhartman** [iBotPeaches/Apktool#1688]
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.0
2. **Operating System (Mac, Linux, Windows)** - Mac
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat

```
/temp>apktool d /temp/MyING.be_2017-11-07.apk
I: Using Apktool 2.3.0 on MyING.be_2017-11-07.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /temp/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
/temp>apktool b MyING.be_2017-11-07/ -o out.apk
I: Using Apktool 2.3.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: /temp/MyING.be_2017-11-07/AndroidManifest.xml:18: Tag <application> attribute name has invalid character '"'. Ignoring...
W: /temp/MyING.be_2017-11-07/AndroidManifest.xml:40: Tag <activity> attribute name has invalid character '/'. Ignoring...
W: /temp/MyING.be_2017-11-07/AndroidManifest.xml:41: Tag <activity> attribute name has invalid character '�'. Ignoring...
W: /temp/MyING.be_2017-11-07/AndroidManifest.xml:43: Tag <activity> attribute name has invalid character 'U'. Ignoring...
W: /temp/MyING.be_2017-11-07/AndroidManifest.xml:44: Tag <activity> attribute name has invalid character '�'. Ignoring...
W: /temp/MyING.be_2017-11-07/AndroidManifest.xml:47: Tag <activity> attribute name has invalid character '�'. Ignoring...
W: /temp/MyING.be_2017-11-07/AndroidManifest.xml:48: Tag <activity> attribute name has invalid character 'D'. Ignoring...
W: /temp/MyING.be_2017-11-07/AndroidManifest.xml:49: Tag <activity> attribute name has invalid character ''. Ignoring...
W: /temp/MyING.be_2017-11-07/AndroidManifest.xml:50: Tag <activity> attribute name has invalid character '�'. Ignoring...
W: /temp/MyING.be_2017-11-07/AndroidManifest.xml:83: Tag <activity> attribute name has invalid character '�'. Ignoring...
W: /temp/MyING.be_2017-11-07/AndroidManifest.xml:84: Tag <activity> attribute name has invalid character 'y'. Ignoring...
W: /temp/MyING.be_2017-11-07/AndroidManifest.xml:93: Tag <activity> attribute name has invalid character '}'. Ignoring...
W: /temp/MyING.be_2017-11-07/AndroidManifest.xml:94: Tag <activity> attribute name has invalid character '�'. Ignoring...
W: /temp/MyING.be_2017-11-07/AndroidManifest.xml:95: Tag <activity> attribute name has invalid character '�'. Ignoring...
W: /temp/MyING.be_2017-11-07/AndroidManifest.xml:96: Tag <activity> attribute name has invalid character ':'. Ignoring...
W: /temp/MyING.be_2017-11-07/AndroidManifest.xml:97: Tag <activity> attribute name has invalid character 'F'. Ignoring...
W: /temp/MyING.be_2017-11-07/AndroidManifest.xml:98: Tag <activity> attribute name has invalid character '_'. Ignoring...
W: /temp/MyING.be_2017-11-07/AndroidManifest.xml:102: Tag <activity> attribute name has invalid character 'O'. Ignoring...
W: /temp/MyING.be_2017-11-07/AndroidManifest.xml:103: Tag <activity> attribute name has invalid character '�'. Ignoring...
W: /temp/MyING.be_2017-11-07/AndroidManifest.xml:104: Tag <activity> attribute name has invalid character '�'. Ignoring...
W: /temp/MyING.be_2017-11-07/AndroidManifest.xml:105: Tag <activity> attribute name has invalid character '+'. Ignoring...
W: /temp/MyING.be_2017-11-07/AndroidManifest.xml:116: Tag <activity> attribute name has invalid character '�'. Ignoring...
W: /temp/MyING.be_2017-11-07/AndroidManifest.xml:117: Tag <activity> attribute name has invalid character '�'. Ignoring...
W: /temp/MyING.be_2017-11-07/AndroidManifest.xml:118: Tag <activity> attribute name has invalid character '-'. Ignoring...
W: /temp/MyING.be_2017-11-07/AndroidManifest.xml:146: Tag <receiver> attribute name has invalid character '�'. Ignoring...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
Exception in thread "main" brut.androlib.AndrolibException: java.io.FileNotFoundException: MyING.be_2017-11-07/unknown/  	.xml (No such file or directory)
	at brut.androlib.Androlib.buildUnknownFiles(Androlib.java:610)
	at brut.androlib.Androlib.build(Androlib.java:326)
	at brut.androlib.Androlib.build(Androlib.java:270)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:75)
Caused by: java.io.FileNotFoundException: MyING.be_2017-11-07/unknown/  	.xml (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at brut.util.BrutIO.copy(BrutIO.java:102)
	at brut.androlib.Androlib.copyUnknownFiles(Androlib.java:663)
	at brut.androlib.Androlib.buildUnknownFiles(Androlib.java:608)
	... 4 more
```

### Steps to Reproduce
1. `apktool d`
2. `apktool b`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

https://www.apkfollow.com/download/apks_new_MyING.be_2017-11-07.apk/

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? yes
3. Are you using the latest apktool version? yes

**Comment by gilhartman** [comment]
might be the same issue as #1389

**Comment by herlon214** [comment]
Similar issue here...

```
I: Using Apktool 2.3.0
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: /home/herlon/dev/smali/AndroidManifest.xml:37: Tag <activity> attribute name has invalid character '/'. Ignoring...
W: /home/herlon/dev/smali/AndroidManifest.xml:42: Tag <application> attribute name has invalid character '�'. Ignoring...
W: /home/herlon/dev/smali/AndroidManifest.xml:43: Tag <provider> attribute name has invalid character '. Ignoring...
W: /home/herlon/dev/smali/AndroidManifest.xml:206: Tag <activity> attribute name has invalid character '/'. Ignoring...
W: /home/herlon/dev/smali/AndroidManifest.xml:223: Tag <activity> attribute name has invalid character '�'. Ignoring...
W: /home/herlon/dev/smali/AndroidManifest.xml:231: Tag <service> attribute name has invalid character '�'. Ignoring...
W: /home/herlon/dev/smali/AndroidManifest.xml:236: Tag <service> attribute name has invalid character '�'. Ignoring...
I: Building apk file...
```

**Comment by iBotPeaches** [comment]
I could not replicate this. 

```
➜  1688 apktool b MyING.be_2017-11-07
I: Using Apktool 2.3.1-ef9be8-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: /home/ibotpeaches/Downloads/Apktool/1688/MyING.be_2017-11-07/AndroidManifest.xml:18: Tag <application> attribute name has invalid character '"'. Ignoring...
W: /home/ibotpeaches/Downloads/Apktool/1688/MyING.be_2017-11-07/AndroidManifest.xml:40: Tag <activity> attribute name has invalid character '/'. Ignoring...
W: /home/ibotpeaches/Downloads/Apktool/1688/MyING.be_2017-11-07/AndroidManifest.xml:41: Tag <activity> attribute name has invalid character '�'. Ignoring...
W: /home/ibotpeaches/Downloads/Apktool/1688/MyING.be_2017-11-07/AndroidManifest.xml:43: Tag <activity> attribute name has invalid character 'U'. Ignoring...
W: /home/ibotpeaches/Downloads/Apktool/1688/MyING.be_2017-11-07/AndroidManifest.xml:44: Tag <activity> attribute name has invalid character '�'. Ignoring...
W: /home/ibotpeaches/Downloads/Apktool/1688/MyING.be_2017-11-07/AndroidManifest.xml:47: Tag <activity> attribute name has invalid character '�'. Ignoring...
W: /home/ibotpeaches/Downloads/Apktool/1688/MyING.be_2017-11-07/AndroidManifest.xml:48: Tag <activity> attribute name has invalid character 'D'. Ignoring...
W: /home/ibotpeaches/Downloads/Apktool/1688/MyING.be_2017-11-07/AndroidManifest.xml:49: Tag <activity> attribute name has invalid character ''. Ignoring...
W: /home/ibotpeaches/Downloads/Apktool/1688/MyING.be_2017-11-07/AndroidManifest.xml:50: Tag <activity> attribute name has invalid character '�'. Ignoring...
W: /home/ibotpeaches/Downloads/Apktool/1688/MyING.be_2017-11-07/AndroidManifest.xml:83: Tag <activity> attribute name has invalid character '�'. Ignoring...
W: /home/ibotpeaches/Downloads/Apktool/1688/MyING.be_2017-11-07/AndroidManifest.xml:84: Tag <activity> attribute name has invalid character 'y'. Ignoring...
W: /home/ibotpeaches/Downloads/Apktool/1688/MyING.be_2017-11-07/AndroidManifest.xml:93: Tag <activity> attribute name has invalid character '}'. Ignoring...
W: /home/ibotpeaches/Downloads/Apktool/1688/MyING.be_2017-11-07/AndroidManifest.xml:94: Tag <activity> attribute name has invalid character '�'. Ignoring...
W: /home/ibotpeaches/Downloads/Apktool/1688/MyING.be_2017-11-07/AndroidManifest.xml:95: Tag <activity> attribute name has invalid character '�'. Ignoring...
W: /home/ibotpeaches/Downloads/Apktool/1688/MyING.be_2017-11-07/AndroidManifest.xml:96: Tag <activity> attribute name has invalid character ':'. Ignoring...
W: /home/ibotpeaches/Downloads/Apktool/1688/MyING.be_2017-11-07/AndroidManifest.xml:97: Tag <activity> attribute name has invalid character 'F'. Ignoring...
W: /home/ibotpeaches/Downloads/Apktool/1688/MyING.be_2017-11-07/AndroidManifest.xml:98: Tag <activity> attribute name has invalid character '_'. Ignoring...
W: /home/ibotpeaches/Downloads/Apktool/1688/MyING.be_2017-11-07/AndroidManifest.xml:102: Tag <activity> attribute name has invalid character 'O'. Ignoring...
W: /home/ibotpeaches/Downloads/Apktool/1688/MyING.be_2017-11-07/AndroidManifest.xml:103: Tag <activity> attribute name has invalid character '�'. Ignoring...
W: /home/ibotpeaches/Downloads/Apktool/1688/MyING.be_2017-11-07/AndroidManifest.xml:104: Tag <activity> attribute name has invalid character '�'. Ignoring...
W: /home/ibotpeaches/Downloads/Apktool/1688/MyING.be_2017-11-07/AndroidManifest.xml:105: Tag <activity> attribute name has invalid character '+'. Ignoring...
W: /home/ibotpeaches/Downloads/Apktool/1688/MyING.be_2017-11-07/AndroidManifest.xml:116: Tag <activity> attribute name has invalid character '�'. Ignoring...
W: /home/ibotpeaches/Downloads/Apktool/1688/MyING.be_2017-11-07/AndroidManifest.xml:117: Tag <activity> attribute name has invalid character '�'. Ignoring...
W: /home/ibotpeaches/Downloads/Apktool/1688/MyING.be_2017-11-07/AndroidManifest.xml:118: Tag <activity> attribute name has invalid character '-'. Ignoring...
W: /home/ibotpeaches/Downloads/Apktool/1688/MyING.be_2017-11-07/AndroidManifest.xml:146: Tag <receiver> attribute name has invalid character '�'. Ignoring...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
➜  1688 
```

These issues are usually related the environment charset. There is an open bug somewhere for remapping these filenames, but that is a long time opened bug due to the work required.
