### ISSUE TITLE
Duplicate Resources error when using font folder in res

### ISSUE THREAD

**Issue by kbragupathy** [iBotPeaches/Apktool#1692]
### Information
1. **Apktool Version  - 2.3.0
2. **Operating System ** - Mac
3. **APK From? ** - Other

### Stacktrace/Logcat
```
apktool d /Users/user/Downloads/TestApplication/app/build/outputs/apk/debug/app-debug.apk 
I: Using Apktool 2.3.0 on app-debug.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/user/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
S: Could not decode file, replacing by FALSE value: font/proxima_nova_cond_semiboldit.otf
S: Could not decode file, replacing by FALSE value: font/proxima_nova_cond_lightit.otf
S: Could not decode file, replacing by FALSE value: font/proxima_nova_boldit.otf
S: Could not decode file, replacing by FALSE value: font/proxima_nova_regular_italic.otf
S: Could not decode file, replacing by FALSE value: font/proxima_nova_black.otf
S: Could not decode file, replacing by FALSE value: font/proxima_nova_regular_0.otf
S: Could not decode file, replacing by FALSE value: font/proxima_nova_light_italic.otf
S: Could not decode file, replacing by FALSE value: font/proxima_nova_semibold.otf
S: Could not decode file, replacing by FALSE value: font/proxima_nova_cond_regularit.otf
S: Could not decode file, replacing by FALSE value: font/proxima_nova_semibold_italic.otf
S: Could not decode file, replacing by FALSE value: font/proxima_nova_extrabold_webfont.ttf
S: Could not decode file, replacing by FALSE value: font/proxima_nova_cond_regular.otf
S: Could not decode file, replacing by FALSE value: font/proxima_nova_cond_light.otf
S: Could not decode file, replacing by FALSE value: font/proxima_nova_light.otf
S: Could not decode file, replacing by FALSE value: font/proxima_nova_extrabold.otf
S: Could not decode file, replacing by FALSE value: font/proxima_nova_cond_semibold.otf
S: Could not decode file, replacing by FALSE value: font/proxima_nova_bold.otf
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
-MacBook-Air:~ user$ apktool b app-debug
I: Using Apktool 2.3.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: /Users/user/app-debug/res/values/fonts.xml:3: error: Resource entry proxima_nova_black is already defined.
W: res/font/proxima_nova_black.otf:0: Originally defined here.
W: 
W: /Users/user/app-debug/res/values/fonts.xml:4: error: Resource entry proxima_nova_bold is already defined.
W: res/font/proxima_nova_bold.otf:0: Originally defined here.
W: 
W: /Users/user/app-debug/res/values/fonts.xml:5: error: Resource entry proxima_nova_boldit is already defined.
W: res/font/proxima_nova_boldit.otf:0: Originally defined here.
W: 
W: /Users/user/app-debug/res/values/fonts.xml:6: error: Resource entry proxima_nova_cond_light is already defined.
W: res/font/proxima_nova_cond_light.otf:0: Originally defined here.
W: 
W: /Users/user/app-debug/res/values/fonts.xml:7: error: Resource entry proxima_nova_cond_lightit is already defined.
W: res/font/proxima_nova_cond_lightit.otf:0: Originally defined here.
W: 
W: /Users/user/app-debug/res/values/fonts.xml:8: error: Resource entry proxima_nova_cond_regular is already defined.
W: res/font/proxima_nova_cond_regular.otf:0: Originally defined here.
W: 
W: /Users/user/app-debug/res/values/fonts.xml:9: error: Resource entry proxima_nova_cond_regularit is already defined.
W: res/font/proxima_nova_cond_regularit.otf:0: Originally defined here.
W: 
W: /Users/user/app-debug/res/values/fonts.xml:10: error: Resource entry proxima_nova_cond_semibold is already defined.
W: res/font/proxima_nova_cond_semibold.otf:0: Originally defined here.
W: 
W: /Users/user/app-debug/res/values/fonts.xml:11: error: Resource entry proxima_nova_cond_semiboldit is already defined.
W: res/font/proxima_nova_cond_semiboldit.otf:0: Originally defined here.
W: 
W: /Users/user/app-debug/res/values/fonts.xml:12: error: Resource entry proxima_nova_extrabold is already defined.
W: res/font/proxima_nova_extrabold.otf:0: Originally defined here.
W: 
W: /Users/user/app-debug/res/values/fonts.xml:13: error: Resource entry proxima_nova_extrabold_webfont is already defined.
W: res/font/proxima_nova_extrabold_webfont.ttf:0: Originally defined here.
W: 
W: /Users/user/app-debug/res/values/fonts.xml:14: error: Resource entry proxima_nova_light is already defined.
W: res/font/proxima_nova_light.otf:0: Originally defined here.
W: 
W: /Users/user/app-debug/res/values/fonts.xml:15: error: Resource entry proxima_nova_light_italic is already defined.
W: res/font/proxima_nova_light_italic.otf:0: Originally defined here.
W: 
W: /Users/user/app-debug/res/values/fonts.xml:16: error: Resource entry proxima_nova_regular_0 is already defined.
W: res/font/proxima_nova_regular_0.otf:0: Originally defined here.
W: 
W: /Users/user/app-debug/res/values/fonts.xml:17: error: Resource entry proxima_nova_regular_italic is already defined.
W: res/font/proxima_nova_regular_italic.otf:0: Originally defined here.
W: 
W: /Users/user/app-debug/res/values/fonts.xml:18: error: Resource entry proxima_nova_semibold is already defined.
W: res/font/proxima_nova_semibold.otf:0: Originally defined here.
W: 
W: /Users/user/app-debug/res/values/fonts.xml:19: error: Resource entry proxima_nova_semibold_italic is already defined.
W: res/font/proxima_nova_semibold_italic.otf:0: Originally defined here.
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/s6/b4zrp8ds679ff63jvfmv8hfm0000gq/T/brut_util_Jar_7584707886659549093.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 22, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /var/folders/s6/b4zrp8ds679ff63jvfmv8hfm0000gq/T/APKTOOL6347431646987506432.tmp, -0, arsc, -0, otf, -0, ttf, -0, arsc, -I, /Users/user/Library/apktool/framework/1.apk, -S, /Users/user/app-debug/res, -M, /Users/user/app-debug/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:485)
	at brut.androlib.Androlib.buildResources(Androlib.java:419)
	at brut.androlib.Androlib.build(Androlib.java:318)
	at brut.androlib.Androlib.build(Androlib.java:270)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:75)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/s6/b4zrp8ds679ff63jvfmv8hfm0000gq/T/brut_util_Jar_7584707886659549093.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 22, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /var/folders/s6/b4zrp8ds679ff63jvfmv8hfm0000gq/T/APKTOOL6347431646987506432.tmp, -0, arsc, -0, otf, -0, ttf, -0, arsc, -I, /Users/user/Library/apktool/framework/1.apk, -S, /Users/user/app-debug/res, -M, /Users/user/app-debug/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:454)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:471)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/s6/b4zrp8ds679ff63jvfmv8hfm0000gq/T/brut_util_Jar_7584707886659549093.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 22, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /var/folders/s6/b4zrp8ds679ff63jvfmv8hfm0000gq/T/APKTOOL6347431646987506432.tmp, -0, arsc, -0, otf, -0, ttf, -0, arsc, -I, /Users/user/Library/apktool/framework/1.apk, -S, /Users/user/app-debug/res, -M, /Users/user/app-debug/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:448)
	... 6 more
```

### Steps to Reproduce
1. `apktool ` d app-debug.apk
2. apktool b app-debug

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG).  NO

### APK
If this APK can be freely shared, please upload/attach a link to it.

[app-debug.apk.zip](https://github.com/iBotPeaches/Apktool/files/1559061/app-debug.apk.zip)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? no
3. Are you using the latest apktool version? yes

**Comment by iBotPeaches** [comment]
Thanks for the report. This has already been fixed in #1662 and will be in the upcoming 2.3.1 release. Set for next week.
