### ISSUE TITLE
References to another resource shows as (name removed)_APKTOOL_DUPLICATENAME

### ISSUE THREAD

**Issue by PerLycke** [iBotPeaches/Apktool#1695]
### Information
1. v2.3.1-48b40e-SNAPSHOT & v2.3.0
2. Mac
3. Play Store

### Stacktrace/Logcat

**With latest snapshot 48b40e:**

```

In the decompiled source, all internal references shows up as:

(name removed)_APKTOOL_DUPLICATENAME

For exempel in layouts, instead of referencing an id as normal id="@id/someId", it shows as id="@id/(name removed)_APKTOOL_DUPLICATENAME_0x7f0f0bcd"
```

**Same APK decompiled with latest stable gives an error instead of the scenario above:**

```

I: Using Apktool 2.3.0 on fbmess_1218.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:52)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:575)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:72)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:64)
	at brut.androlib.Androlib.getResTable(Androlib.java:68)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:214)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:109)
	at brut.apktool.Main.cmdDecode(Main.java:160)
	at brut.apktool.Main.main(Main.java:72)
Caused by: java.io.IOException: Expected: 0x00000008, got: 0x00000010
	at brut.util.ExtDataInput.skipCheckShort(ExtDataInput.java:56)
	at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:320)
	at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:252)
	at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:231)
	at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:156)
	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:118)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:80)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
	... 8 more
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
https://www.apkmirror.com/apk/facebook-2/messenger/messenger-147-0-0-25-86-release/facebook-messenger-147-0-0-25-86-android-apk-download/

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by iBotPeaches** [comment]
```
➜  1695 apktool d fbmess_1218.apk 
I: Using Apktool 2.3.1-ef9be8-SNAPSHOT on fbmess_1218.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes4.dex...
I: Baksmaling classes5.dex...
I: Baksmaling classes6.dex...
I: Baksmaling classes7.dex...
I: Baksmaling assets/java.com.facebook.messaging.particles.downloadableparticles/java.com.facebook.messaging.particles.downloadableparticles2.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
```

Fixed in upcoming 2.3.1

**Comment by PerLycke** [comment]
@iBotPeaches I can decompile it with the 2.3.1 snapshot. But I guess the @id/(name removed)_APKTOOL_DUPLICATENAME_0x7f0f0bcd is due to Facebook obfuscated their code, and there is nothing that can be done about it?

**Comment by iBotPeaches** [comment]
There is a form of obfuscation where the names of all resources are changed to the same name. This means that during the build phase you have hundreds of references to the resource called "foo". Android only cares about the resourceId, but the resourceId is assigned during the build process (Or static if `public.xml` is used).

This means that duplicate named resources were encountered and for Apktool to stay afloat and allow rebuild, it renamed the name of the affected resources to that string + resourceId

**Comment by elijahbal** [comment]
I am curious if this is not also totally failing the rebuild step.
