### ISSUE TITLE
Cannot recompile spotify modded

### ISSUE THREAD

**Issue by middlestreetwalker** [iBotPeaches/Apktool#1698]
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.0
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - ihackedit.com

### Stacktrace/Logcat

```
apktool b ~/Scripts/Decompiler/original -o Spotify.apk
I: Using Apktool 2.3.0-dirty
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
Exception in thread "main" brut.androlib.AndrolibException: java.io.FileNotFoundException: /home/n353p/Scripts/Decompiler/original/build/apk/classes.dex (No such file or directory)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:63)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:36)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:412)
	at brut.androlib.Androlib.buildSources(Androlib.java:343)
	at brut.androlib.Androlib.build(Androlib.java:299)
	at brut.androlib.Androlib.build(Androlib.java:270)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:75)
Caused by: java.io.FileNotFoundException: /home/n353p/Scripts/Decompiler/original/build/apk/classes.dex (No such file or directory)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at org.jf.dexlib2.writer.io.FileDataStore.<init>(FileDataStore.java:13)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:61)
	... 7 more

```

### Steps to Reproduce
1. apktool d -f
2. apktool b

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
http://ihackedit.com/spotify-music-beta-mega-mod-apk/

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? YES
2. If you are trying to install a modified apk, did you resign it? N/A
3. Are you using the latest apktool version? YES

**Comment by iBotPeaches** [comment]
Very strange stacktrace. This is like the assembling of the dex file failed, but produced no error messages.

**Comment by iBotPeaches** [comment]
I don't feel comfortable investigating an application that is clearing breaking laws and dismantling copyright protections. I am going to close this.
