### ISSUE TITLE
Apktool 2.3.1 cannot rebuild layout XMLs of Settings.apk from MIUI 9.1 (Android 6) correctly

### ISSUE THREAD

**Issue by S-trace** [iBotPeaches/Apktool#1701]
### Information
1. **Apktool Version (`apktool -version`)** `2.3.1`
2. **Operating System (Mac, Linux, Windows)** `Linux (Kubuntu 17.10 AMD64)`
3. **APK From? (Playstore, ROM, Other)** `ROM`

### Stacktrace/Logcat
```
Decoding:
I: Using Apktool 2.3.1 on Settings.apk
I: Loading resource table...
I: Decoding Shared Library (miui), pkgId: 16
I: Decoding Shared Library (android.miui), pkgId: 17
I: Decoding Shared Library (miui.system), pkgId: 18
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: frameworks/1.apk
I: Loading resource table from file: frameworks/16.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Loading resource table from file: frameworks/17.apk
I: Decoding values */* XMLs...
I: Loading resource table from file: frameworks/18.apk
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

Encoding without modifications:
I: Using Apktool 2.3.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
/* bunch of "W: warning: string 'sting_name' has no default translation." warnings */
W: W/ResourceType(29167): DynamicRefTable(0x10): No mapping for build-time package ID 0x10.
W: W/ResourceType(29167): e[0x01] -> 0x01
W: W/ResourceType(29167): e[0x7f] -> 0x7f
W: E/ResourceType(29167): Failed resolving ResTable_map name at 3340 with ident 0x100b000f
W: warning: Package not found for resource #1001004f
W: W/ResourceType(29167): Attempt to retrieve bag 0x1001004f which is invalid or in a cycle.
W: warning: Package not found for resource #1001004f
I: Building apk file...
I: Copying unknown files/dir...

Original xml tree: aapt d xmltree Settings.apk res/layout/device_name_edit_layout.xml
N: android=http://schemas.android.com/apk/res/android
  E: ScrollView (line=2)
    A: android:layout_width(0x010100f4)=(type 0x10)0xffffffff
    A: android:layout_height(0x010100f5)=(type 0x10)0xfffffffe
    E: LinearLayout (line=4)
      A: android:orientation(0x010100c4)=(type 0x10)0x1
      A: android:paddingLeft(0x010100d6)=?0x10103a3
      A: android:paddingTop(0x010100d7)=@0x7f0b00d1
      A: android:paddingRight(0x010100d8)=?0x10103a4
      A: android:paddingBottom(0x010100d9)=?0x1001006c
      A: android:layout_width(0x010100f4)=(type 0x10)0xffffffff
      A: android:layout_height(0x010100f5)=(type 0x10)0xfffffffe
      E: EditText (line=5)
        A: android:id(0x010100d0)=@0x7f1300fe
        A: android:paddingLeft(0x010100d6)=(type 0x5)0xa01
        A: android:paddingRight(0x010100d8)=(type 0x5)0xa01
        A: android:layout_width(0x010100f4)=(type 0x10)0xffffffff
        A: android:layout_height(0x010100f5)=(type 0x10)0xfffffffe
        A: android:hint(0x01010150)=@0x7f0a0e55
        A: android:inputType(0x01010220)=(type 0x11)0x80001
      E: TextView (line=6)
        A: android:paddingTop(0x010100d7)=(type 0x5)0x501
        A: android:layout_width(0x010100f4)=(type 0x10)0xffffffff
        A: android:layout_height(0x010100f5)=(type 0x10)0xfffffffe
        A: android:text(0x0101014f)=@0x7f0a0e56
        A: style=@0x100d0056 (Raw: "@miui:style/TextAppearance.PreferenceCategory")

Re-encoded original xml tree: aapt d xmltree Settings/dist/Settings.apk res/layout/device_name_edit_layout.xml
N: android=http://schemas.android.com/apk/res/android
  E: ScrollView (line=2)
    A: android:layout_width(0x010100f4)=(type 0x10)0xffffffff
    A: android:layout_height(0x010100f5)=(type 0x10)0xfffffffe
    E: LinearLayout (line=4)
      A: android:orientation(0x010100c4)=(type 0x10)0x1
      A: android:paddingLeft(0x010100d6)=?0x10103a3
      A: android:paddingTop(0x010100d7)=@0x7f0b00d1
      A: android:paddingRight(0x010100d8)=?0x10103a4
      A: android:paddingBottom(0x010100d9)=(type 0x8)0x1001006c
      A: android:layout_width(0x010100f4)=(type 0x10)0xffffffff
      A: android:layout_height(0x010100f5)=(type 0x10)0xfffffffe
      E: EditText (line=5)
        A: android:id(0x010100d0)=@0x7f1300fe
        A: android:paddingLeft(0x010100d6)=(type 0x5)0xa01
        A: android:paddingRight(0x010100d8)=(type 0x5)0xa01
        A: android:layout_width(0x010100f4)=(type 0x10)0xffffffff
        A: android:layout_height(0x010100f5)=(type 0x10)0xfffffffe
        A: android:hint(0x01010150)=@0x7f0a0e55
        A: android:inputType(0x01010220)=(type 0x11)0x80001
      E: TextView (line=6)
        A: android:paddingTop(0x010100d7)=(type 0x5)0x501
        A: android:layout_width(0x010100f4)=(type 0x10)0xffffffff
        A: android:layout_height(0x010100f5)=(type 0x10)0xfffffffe
        A: android:text(0x0101014f)=@0x7f0a0e56
        A: style=(type 0x7)0x100d0056 (Raw: "@miui:style/TextAppearance.PreferenceCategory")

Rebuilt Settings.apk crashes when opening Bluetooth settings and trying to change device name:
01-02 08:26:51.364 10241 10241 E AndroidRuntime: FATAL EXCEPTION: main
01-02 08:26:51.364 10241 10241 E AndroidRuntime: Process: com.android.settings, PID: 10241
01-02 08:26:51.364 10241 10241 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.android.settings.SubSettings}: android.view.InflateException: Binary XML file line #4: Binary XML file line #4: Error inflating class <unknown>
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at android.app.ActivityThread.access$1000(ActivityThread.java)
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java)
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at android.os.Looper.loop(Looper.java)
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java)
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
01-02 08:26:51.364 10241 10241 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #4: Binary XML file line #4: Error inflating class <unknown>
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java)
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at android.view.LayoutInflater.inflate(LayoutInflater.java)
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at com.android.settings.MiuiDeviceNameEditFragment.a(MiuiDeviceNameEditFragment.java)
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at com.android.settings.BaseFragment.onInflateView(BaseFragment.java)
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at com.miui.internal.app.FragmentDelegate.onCreateView(SourceFile)
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at miui.app.Fragment.onCreateView(SourceFile)
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at android.app.Fragment.performCreateView(Fragment.java)
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java)
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java)
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java)
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java)
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at android.app.FragmentController.dispatchActivityCreated(FragmentController.java)
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at android.app.Activity.performCreateCommon(Activity.java)
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java)
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java)
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        ... 10 more
01-02 08:26:51.364 10241 10241 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #4: Error inflating class <unknown>
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at android.view.LayoutInflater.createView(LayoutInflater.java)
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java)
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at android.view.LayoutInflater.onCreateView(LayoutInflater.java)
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at android.view.LayoutInflater.rInflate(LayoutInflater.java)
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java)
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        ... 25 more
01-02 08:26:51.364 10241 10241 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at java.lang.reflect.Constructor.newInstance(Native Method)
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        ... 32 more
01-02 08:26:51.364 10241 10241 E AndroidRuntime: Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x8
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java)
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at android.view.View.<init>(View.java)
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at com.miui.internal.variable.v21.Android_View_View_class.handle_init_(SourceFile)
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at android.view.ViewGroup.<init>(ViewGroup.java)
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at com.miui.internal.variable.v21.Android_View_ViewGroup_class.handle_init_(SourceFile)
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at android.widget.LinearLayout.<init>(LinearLayout.java)
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at android.widget.LinearLayout.<init>(LinearLayout.java)
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        at android.widget.LinearLayout.<init>(LinearLayout.java)
01-02 08:26:51.364 10241 10241 E AndroidRuntime:        ... 33 more
```

### Steps to Reproduce
1. `find system/ -name '*.apk' -exec apktool if -p frameworks {} \;`
2. `apktool d -p frameworks/ Settings.apk`
3. `apktool b -p frameworks/ Settings`
4. `java -jar /usr/bin/signapk platform.x509.pem platform.pk8 Settings/dist/Settings.apk Settings_rebuilt.apk`
5. `adb push Settings_rebuilt.apk /system/priv-app/Settings/Settings.apk`
6. Kill existing Settings process and start Settings
7. Open Bluetooth settings and try to change device name

### Frameworks
https://www.dropbox.com/s/h3wg68h25ed30u9/frameworks_full.7z?dl=1

### APK
https://www.dropbox.com/s/bzfuyq90du956ov/Settings.apk?dl=1

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? - yes, this report is from such kind of test
2. If you are trying to install a modified apk, did you resign it? - yes, resigned whole ROM with own keys, (including original Settings.apk) and then signed rebuilt Settings.apk using same key
3. Are you using the latest apktool version? - yes, latest released version (2.3.1)

Here we can see, the binary XML on line 4 have difference in android:paddingBottom attribute:
orig:      A: android:paddingBottom(0x010100d9)=?0x1001006c
bad:       A: android:paddingBottom(0x010100d9)=(type 0x8)0x1001006c
And on line 6 difference in style attribute:
orig:        A: style=@0x100d0056 (Raw: "@miui:style/TextAppearance.PreferenceCategory")
bad:        A: style=(type 0x7)0x100d0056 (Raw: "@miui:style/TextAppearance.PreferenceCategory")

But apktool still decodes bad and good binary XMLs in bytewise same text form:
```
<?xml version="1.0" encoding="utf-8"?>
<ScrollView android:layout_width="fill_parent" android:layout_height="wrap_content"
  xmlns:android="http://schemas.android.com/apk/res/android">
    <LinearLayout android:orientation="vertical" android:paddingLeft="?android:listPreferredItemPaddingLeft" android:paddingTop="@dimen/screen_padding_top" android:paddingRight="?android:listPreferredItemPaddingRight" android:paddingBottom="?miui:preferenceScreenPaddingBottom" android:layout_width="fill_parent" android:layout_height="wrap_content">
        <EditText android:id="@id/device_name" android:paddingLeft="10.0dip" android:paddingRight="10.0dip" android:layout_width="fill_parent" android:layout_height="wrap_content" android:hint="@string/device_name_input_hint" android:inputType="textNoSuggestions" />
        <TextView android:paddingTop="5.0dip" android:layout_width="fill_parent" android:layout_height="wrap_content" android:text="@string/device_name_usage_point" style="@miui:style/TextAppearance.PreferenceCategory" />
    </LinearLayout>
</ScrollView>
```

**Comment by iBotPeaches** [comment]
Thanks for the detailed report. While officially Apktool's motto is to ignore MIUI related bugs, I appreciate the amount of detail and research you put into this.

I've downloaded the applications and categorized them in my local environment for investigation. 

The difference you noticed with the resource IDs is an interesting one. 
```
orig: A: android:paddingBottom(0x010100d9)=?0x1001006c
bad: A: android:paddingBottom(0x010100d9)=(type 0x8)0x1001006c
```

```
?0x1001006c
```
Is a theme referencing. The `?` denotes the active theme, so you can reference a resource and whatever active theme will use its version of that resource. 

Type 8 is a `DYNAMIC_ATTRIBUTE`, which is correct in the scope of things. I believe behind the scenes a `?` property is resolved as a `DYNAMIC_ATTRIBUTE`, but I need to do some tests to confirm that.

**Comment by S-trace** [comment]
Any progress?

**Comment by iBotPeaches** [comment]
Its in roadmap now. Not seeing it fixed anytime soon, since it took 2-3 years to respond to this.

https://github.com/iBotPeaches/Apktool/blob/master/ROADMAP.md#qualifier-plugin-system

Closing.
