### ISSUE TITLE
Cannot build any APK w/ resources: brut.common.BrutException: could not exec (exit code = 1)

### ISSUE THREAD

**Issue by phlogistic** [iBotPeaches/Apktool#1704]
### Information
APKTOOL VERSION: 2.3.1
OS: Mac High Sierra
APK: Any APK from play store adb backup, picking on org.havenapp.main

### Stacktrace/Logcat

```
/jjjj/haven/work/havenFromGooglePlay $ apktool build -o havenRebuilt.apk
I: Using Apktool 2.3.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
W: /jjjj/haven/work/havenFromGooglePlay/./res/values-v24/styles.xml:3: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Animation.OptionsPanel'.
W: 
W: /jjjj/haven/work/havenFromGooglePlay/./res/values-v24/styles.xml:4: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Animation.LockScreen'.
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/bv/2xmvrjl51sq5q1b_ckwxd38r0000gn/T/brut_util_Jar_13283028417093462725.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 27, --version-code, 105, --version-name, 0.1.0-beta-5, --no-version-vectors, -F, /var/folders/bv/2xmvrjl51sq5q1b_ckwxd38r0000gn/T/APKTOOL10325566106247013325.tmp, -0, arsc, -0, META-INF/android.arch.lifecycle_runtime.version, -0, META-INF/com.android.support_animated-vector-drawable.version, -0, META-INF/com.android.support_appcompat-v7.version, -0, META-INF/com.android.support_cardview-v7.version, -0, META-INF/com.android.support_design.version, -0, META-INF/com.android.support_recyclerview-v7.version, -0, META-INF/com.android.support_support-compat.version, -0, META-INF/com.android.support_support-core-ui.version, -0, META-INF/com.android.support_support-core-utils.version, -0, META-INF/com.android.support_support-fragment.version, -0, META-INF/com.android.support_support-media-compat.version, -0, META-INF/com.android.support_support-v4.version, -0, META-INF/com.android.support_support-vector-drawable.version, -0, META-INF/com.android.support_transition.version, -0, META-INF/services/com.fasterxml.jackson.core.JsonFactory, -0, META-INF/services/com.fasterxml.jackson.core.ObjectCodec, -0, sql, -0, arsc, -I, /Users/jjjj/Library/apktool/framework/1.apk, -S, /jjjj/haven/work/havenFromGooglePlay/./res, -M, /jjjj/haven/work/havenFromGooglePlay/./AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:492)
	at brut.androlib.Androlib.buildResources(Androlib.java:426)
	at brut.androlib.Androlib.build(Androlib.java:305)
	at brut.androlib.Androlib.build(Androlib.java:270)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:75)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/bv/2xmvrjl51sq5q1b_ckwxd38r0000gn/T/brut_util_Jar_13283028417093462725.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 27, --version-code, 105, --version-name, 0.1.0-beta-5, --no-version-vectors, -F, /var/folders/bv/2xmvrjl51sq5q1b_ckwxd38r0000gn/T/APKTOOL10325566106247013325.tmp, -0, arsc, -0, META-INF/android.arch.lifecycle_runtime.version, -0, META-INF/com.android.support_animated-vector-drawable.version, -0, META-INF/com.android.support_appcompat-v7.version, -0, META-INF/com.android.support_cardview-v7.version, -0, META-INF/com.android.support_design.version, -0, META-INF/com.android.support_recyclerview-v7.version, -0, META-INF/com.android.support_support-compat.version, -0, META-INF/com.android.support_support-core-ui.version, -0, META-INF/com.android.support_support-core-utils.version, -0, META-INF/com.android.support_support-fragment.version, -0, META-INF/com.android.support_support-media-compat.version, -0, META-INF/com.android.support_support-v4.version, -0, META-INF/com.android.support_support-vector-drawable.version, -0, META-INF/com.android.support_transition.version, -0, META-INF/services/com.fasterxml.jackson.core.JsonFactory, -0, META-INF/services/com.fasterxml.jackson.core.ObjectCodec, -0, sql, -0, arsc, -I, /Users/jjjj/Library/apktool/framework/1.apk, -S, /jjjj/haven/work/havenFromGooglePlay/./res, -M, /jjjj/haven/work/havenFromGooglePlay/./AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:456)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:478)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/bv/2xmvrjl51sq5q1b_ckwxd38r0000gn/T/brut_util_Jar_13283028417093462725.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 27, --version-code, 105, --version-name, 0.1.0-beta-5, --no-version-vectors, -F, /var/folders/bv/2xmvrjl51sq5q1b_ckwxd38r0000gn/T/APKTOOL10325566106247013325.tmp, -0, arsc, -0, META-INF/android.arch.lifecycle_runtime.version, -0, META-INF/com.android.support_animated-vector-drawable.version, -0, META-INF/com.android.support_appcompat-v7.version, -0, META-INF/com.android.support_cardview-v7.version, -0, META-INF/com.android.support_design.version, -0, META-INF/com.android.support_recyclerview-v7.version, -0, META-INF/com.android.support_support-compat.version, -0, META-INF/com.android.support_support-core-ui.version, -0, META-INF/com.android.support_support-core-utils.version, -0, META-INF/com.android.support_support-fragment.version, -0, META-INF/com.android.support_support-media-compat.version, -0, META-INF/com.android.support_support-v4.version, -0, META-INF/com.android.support_support-vector-drawable.version, -0, META-INF/com.android.support_transition.version, -0, META-INF/services/com.fasterxml.jackson.core.JsonFactory, -0, META-INF/services/com.fasterxml.jackson.core.ObjectCodec, -0, sql, -0, arsc, -I, /Users/jjjj/Library/apktool/framework/1.apk, -S, /jjjj/haven/work/havenFromGooglePlay/./res, -M, /jjjj/haven/work/havenFromGooglePlay/./AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:450)
	... 6 more

```

### Steps to Reproduce
1. `apktool d havenFromGooglePlay.apk`
2. `apktool build -o havenRebuilt.apk`

### Frameworks

N/A

### APK

https://github.com/guardianproject/haven

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?

Yes. Does not work. 

However, `apktool d -r` does work

2. If you are trying to install a modified apk, did you resign it?

Yes. Resigned works if I use `apktool d -r`; every apk does not work if resources are decompiled.

3. Are you using the latest apktool version?

Yes

**Comment by iBotPeaches** [comment]
```
➜  Bug1704 apktool d Haven-0.1.0-beta-5-release.apk 
I: Using Apktool 2.3.1-18143c-SNAPSHOT on Haven-0.1.0-beta-5-release.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/connortumbleson/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1704 apktool b Haven-0.1.0-beta-5-release
I: Using Apktool 2.3.1-18143c-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
W: warning: string 'camera_label' has no default translation.
W: warning: string 'camera_sensitivity' has no default translation.
W: warning: string 'flash_label' has no default translation.
W: warning: string 'menu_remote_access' has no default translation.
W: warning: string 'menu_start' has no default translation.
W: warning: string 'menu_stop' has no default translation.
W: warning: string 'microphone_label' has no default translation.
W: warning: string 'secure_service_stopped' has no default translation.
W: warning: string 'sensor_setup_info' has no default translation.
W: warning: string 'start_button' has no default translation.
W: warning: string 'unlock_code_hint' has no default translation.
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
➜  Bug1704 
```

Couldn't duplicate. Try `apktool empty-framework-dir` and give that another shot.
