### ISSUE TITLE
Apktool won't rebuild back apk.

### ISSUE THREAD

**Issue by ProsAnon** [iBotPeaches/Apktool#1709]
### Information
1. **Apktool Version (`apktool -version`)** -2.3.1
2. **Operating System (Mac, Linux, Windows)** -Kali Linux
3. **APK From? (Playstore, ROM, Other)** - Other

### Stacktrace/Logcat
```
I: Using Apktool 2.3.1-dirty
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: /root/Desktop/original/res/layout-v26/abc_screen_toolbar.xml:5: error: No resource identifier found for attribute 'keyboardNavigationCluster' in package 'android'
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/usr/bin/aapt, p, --min-sdk-version, 15, --target-sdk-version, 25, --version-code, 452125, --version-name, 2.18.7, --no-version-vectors, -F, /tmp/APKTOOL5912685068185568065.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/Desktop/original/res, -M, /root/Desktop/original/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:492)
	at brut.androlib.Androlib.buildResources(Androlib.java:426)
	at brut.androlib.Androlib.build(Androlib.java:305)
	at brut.androlib.Androlib.build(Androlib.java:270)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:75)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/usr/bin/aapt, p, --min-sdk-version, 15, --target-sdk-version, 25, --version-code, 452125, --version-name, 2.18.7, --no-version-vectors, -F, /tmp/APKTOOL5912685068185568065.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/Desktop/original/res, -M, /root/Desktop/original/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:456)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:478)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/usr/bin/aapt, p, --min-sdk-version, 15, --target-sdk-version, 25, --version-code, 452125, --version-name, 2.18.7, --no-version-vectors, -F, /tmp/APKTOOL5912685068185568065.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/Desktop/original/res, -M, /root/Desktop/original/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:450)
	... 6 more
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

1. I typed apktool b /root/Desktop/
2. No.
3. Yes

**Comment by iBotPeaches** [comment]
Give `apktool empty-framework-dir --force` a try and try again. Thanks for getting the information required, but this is just an issue from not following upgrade notes.

**Comment by ProsAnon** [comment]
How can I update it properly?
