### ISSUE TITLE
'apktool b' is creating problem.

### ISSUE THREAD

**Issue by tohaidar2005** [iBotPeaches/Apktool#1711]
### Information
1. APKTOOL version 2.3.0
2. Using Linux Machine
3. Build the app from Android Studio App

### Include stacktrace here
```
Exception in thread "main" W: /tmp/brut_util_Jar_3633463298128253557.tmp: /tmp/../lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/brut_util_Jar_3633463298128253557.tmp)
brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_3633463298128253557.tmp, p, --forced-package-id, 127, --min-sdk-version, 17, --target-sdk-version, 26, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /tmp/APKTOOL1452296768427249159.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /mnt/emm_config/tools/apktool/app-debug/res, -M, /mnt/emm_config/tools/apktool/app-debug/AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:485)
        at brut.androlib.Androlib.buildResources(Androlib.java:419)
        at brut.androlib.Androlib.build(Androlib.java:318)
        at brut.androlib.Androlib.build(Androlib.java:270)
        at brut.apktool.Main.cmdBuild(Main.java:224)
        at brut.apktool.Main.main(Main.java:75)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_3633463298128253557.tmp, p, --forced-package-id, 127, --min-sdk-version, 17, --target-sdk-version, 26, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /tmp/APKTOOL1452296768427249159.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /mnt/emm_config/tools/apktool/app-debug/res, -M, /mnt/emm_config/tools/apktool/app-debug/AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:454)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:471)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_3633463298128253557.tmp, p, --forced-package-id, 127, --min-sdk-version, 17, --target-sdk-version, 26, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /tmp/APKTOOL1452296768427249159.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /mnt/emm_config/tools/apktool/app-debug/res, -M, /mnt/emm_config/tools/apktool/app-debug/AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:448)
        ... 6 more
```
### Steps to Reproduce

1. Using apktool 2.3.0
2. Build the android app with Android Studio
3. tried `apktool d` which was working fine 
4. whenever tried `apktool b` it is throwing above issue.

Also tried the same with latest APKTOOL version i.e. 2.3.1 but no luck.

Pls find full log for more details,

[apktoolLog.txt](https://github.com/iBotPeaches/Apktool/files/1638728/apktoolLog.txt)
APK : https://www.dropbox.com/s/5klj5wbr7db37wq/app-debug.apk?dl=0

Please check and let me know if you need any further information to debug this issue.

**Comment by iBotPeaches** [comment]
Doesn't look like Apktool is at fault here.

https://askubuntu.com/a/421795/119202

**Comment by tohaidar2005** [comment]
Thanks for the response.

This issue only observed for the Kotlin application. This is working fine for the other Android application.
