### ISSUE TITLE
Apktool 2.3.1 can't recompile apk

### ISSUE THREAD

**Issue by MineEric64** [iBotPeaches/Apktool#1712]
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.1
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Other (Youtube)

### Stacktrace/Logcat
D:\WorkSpace\Programs\Apktool>apktool b UniSkin
I: Using Apktool 2.3.1
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: D:\WorkSpace\Programs\Apktool\UniSkin\res\values-v11\styles.xml:47: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/ActiveWallpaperSettings'.
W:
W: D:\WorkSpace\Programs\Apktool\UniSkin\res\values-v11\styles.xml:48: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/PreviewWallpaperSettings'.
W:
W: D:\WorkSpace\Programs\Apktool\UniSkin\res\values\styles.xml:106: error: Error: No resource found that matches the given name: attr 'android:majorWeight'.
W:
W: D:\WorkSpace\Programs\Apktool\UniSkin\res\values\styles.xml:104: error: Error: No resource found that matches the given name: attr 'android:maxItems'.
Exception in thread "main" W:
W: D:\WorkSpace\Programs\Apktool\UniSkin\res\values\styles.xml:105: error: Error: No resource found that matches the given name: attr 'android:quickContactWindowSize'.
brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\SAMSUNG\AppData\Local\Temp\brut_util_Jar_8847931972564424708.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 25, --version-code, 1, --version-
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\SAMSUNG\AppData\Local\Temp\brut_util_Jar_8847931972564424708.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 25, --version-code, 1, --version-name, 1.0.0, --no-version-vectors, -F, C:\Users\SAMSUNG\AppData\Local\Temp\APKTOOL1348131219621382454.tmp, -0, arsc, -0, arsc, -I, C:\Users\SAMSUNG\AppData\Local\apktool\framework\1.apk, -S, D:\WorkSpace\Programs\Apktool\UniSkin\res, -M, D:\WorkSpace\Programs\Apktool\UniSkin\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:450)
        ... 6 more
W:
W: D:\WorkSpace\Programs\Apktool\UniSkin\res\values\styles.xml:141: error: Error: No resource found that matches the given name: attr 'android:majorWeight'.
W:
W: D:\WorkSpace\Programs\Apktool\UniSkin\res\values\styles.xml:139: error: Error: No resource found that matches the given name: attr 'android:maxItems'.
W:
W: D:\WorkSpace\Programs\Apktool\UniSkin\res\values\styles.xml:140: error: Error: No resource found that matches the given name: attr 'android:quickContactWindowSize'.
W:
W: D:\WorkSpace\Programs\Apktool\UniSkin\res\values-v11\styles.xml:55: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Animation.OptionsPanel'.
W:
W: D:\WorkSpace\Programs\Apktool\UniSkin\res\values-v11\styles.xml:87: error: Error: No resource found that matches the given name: attr 'android:majorWeight'.
W:
W: D:\WorkSpace\Programs\Apktool\UniSkin\res\values-v11\styles.xml:85: error: Error: No resource found that matches the given name: attr 'android:maxItems'.
W:
W: D:\WorkSpace\Programs\Apktool\UniSkin\res\values-v11\styles.xml:86: error: Error: No resource found that matches the given name: attr 'android:quickContactWindowSize'.
W:
W: D:\WorkSpace\Programs\Apktool\UniSkin\res\values-v11\styles.xml:89: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Animation.TypingFilterRestore'.
W:
W: D:\WorkSpace\Programs\Apktool\UniSkin\res\values-v11\styles.xml:122: error: Error: No resource found that matches the given name: attr 'android:majorWeight'.
W:
W: D:\WorkSpace\Programs\Apktool\UniSkin\res\values-v11\styles.xml:120: error: Error: No resource found that matches the given name: attr 'android:maxItems'.
W:
W: D:\WorkSpace\Programs\Apktool\UniSkin\res\values-v11\styles.xml:121: error: Error: No resource found that matches the given name: attr 'android:quickContactWindowSize'.
W:
W: D:\WorkSpace\Programs\Apktool\UniSkin\res\values-v14\styles.xml:9: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/DialogWindowTitle'.
W:
W: D:\WorkSpace\Programs\Apktool\UniSkin\res\values-v14\styles.xml:10: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/AlertDialog'.
W:
W: D:\WorkSpace\Programs\Apktool\UniSkin\res\values-v14\styles.xml:11: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/DialogWindowTitle'.
W:
W: D:\WorkSpace\Programs\Apktool\UniSkin\res\values-v14\styles.xml:17: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/AlertDialog'.

Include stacktrace here
```

### Steps to Reproduce
1. `apktool empty-framework-dir --force`
2. `apktool d -o UniSkin UniSkinK.apk`
3. `apktool b UniSkin`
### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? No
3. Are you using the latest apktool version? Yes

**Comment by MineEric64** [comment]
I fixed.
Because an apk Name has capital.
