### ISSUE TITLE
decompiling an APK using apkTool

### ISSUE THREAD

**Issue by Motaz-Al-Zoubi** [iBotPeaches/Apktool#1713]
### Information
1. **Apktool Version (`apktool_2.3.1.jar`)** -
2. **Operating System (Mac, Linux, Windows)** -
3. **APK From? (Playstore, ROM, Other)** -

### Stacktrace/Logcat
```
D:\Android tools\APktool>apktool d files/com.alameensoft.xPOS.apk --f
I: Using Apktool 2.0.0-RC4 on com.alameensoft.xPOS.apk
I: Loading resource table...
W: Config flags size > 38. Exceeding bytes: 0x746E00000000000000000000000000000000.
W: Invalid config flags detected. Dropping resources: string-sr-ERR0
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\MotazZ\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
Exception in thread "main" java.lang.ClassCastException: brut.androlib.res.data.value.ResStringValue cannot be cast to brut.androlib.res.data.value.ResAttr
        at brut.androlib.res.decoder.ResAttrDecoder.decode(ResAttrDecoder.java:36)
        at brut.androlib.res.decoder.AXmlResourceParser.getAttributeValue(AXmlResourceParser.java:369)
        at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValue(XmlPullParserDelegate.java:69)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
        at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:83)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:141)
        at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(ResStreamDecoderContainer.java:33)
        at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:114)
        at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:99)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:339)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:133)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:104)
        at brut.apktool.Main.cmdDecode(Main.java:165)
        at brut.apktool.Main.main(Main.java:81)
```
### Steps to Reproduce
apktool d files/com.alameensoft.xPOS.apk

**Comment by iBotPeaches** [comment]
You say you are using apktool2.3.1 in the issue, but the stacktrace says otherwise. Additionally, there is no link to any application for investigating.

**Comment by iBotPeaches** [comment]
Closing due to no response in months.
