### ISSUE TITLE
Failed when decompiling with apktool

### ISSUE THREAD

**Issue by lintcoder** [iBotPeaches/Apktool#1718]
When I'm trying to decompiling an apk with apktool version 2.3, I got error as follows:
......
I: Baksmaling classes.dex...
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.jf.util.ExceptionWithContext: Encountered small uint that is out of range at offset 0x9c90
	at org.jf.baksmali.Baksmali.disassembleDexFile(Baksmali.java:92)
	at org.jf.baksmali.Baksmali.disassembleDexFile(Baksmali.java:48)
	at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:83)
	at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:38)
	at brut.androlib.Androlib.decodeSourcesSmali(Androlib.java:98)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:140)
	at brut.apktool.Main.cmdDecode(Main.java:160)
	at brut.apktool.Main.main(Main.java:72)

**Comment by iBotPeaches** [comment]
Does the decode fail? This looks like it might be dead code intentionally added. See this report: https://github.com/JesusFreke/smali/issues/580 & https://github.com/JesusFreke/smali/issues/562

Closing as upstream.

**Comment by iBotPeaches** [comment]
The newest version v2.5.0 should have baksmali v2.4.0 in it, which will emit warnings, but not crash. Closing.

**Comment by Afsalmc** [comment]
```
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
Exception in thread "main" org.jf.util.ExceptionWithContext: Exception occurred while writing code_item for method Landroidx/annotation/InspectableProperty$ValueType;->values()[Landroidx/annotation/InspectableProperty$ValueType;
        at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1058)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:354)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:309)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:58)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:37)
        at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:437)
        at brut.androlib.Androlib.buildSources(Androlib.java:368)
        at brut.androlib.Androlib.build(Androlib.java:320)
        at brut.androlib.Androlib.build(Androlib.java:287)
        at brut.apktool.Main.cmdBuild(Main.java:263)
        at brut.apktool.Main.main(Main.java:82)
Caused by: org.jf.util.ExceptionWithContext: Error while writing instruction at code offset 0x2
        at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1331)
        at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1054)
        ... 10 more
Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65562
        at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
        at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:356)
        at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1291)


using apktool 2.70

```
