### ISSUE TITLE
Exception in thread "main" java.lang.IllegalArgumentException: MALFORMED

### ISSUE THREAD

**Issue by linyia01** [iBotPeaches/Apktool#1721]
```
I: Using Apktool 2.3.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
Exception in thread "main" java.lang.IllegalArgumentException: MALFORMED
        at java.util.zip.ZipCoder.toString(Unknown Source)
        at java.util.zip.ZipFile.getZipEntry(Unknown Source)
        at java.util.zip.ZipFile.access$900(Unknown Source)
        at java.util.zip.ZipFile$ZipEntryIterator.next(Unknown Source)
        at java.util.zip.ZipFile$ZipEntryIterator.nextElement(Unknown Source)
        at java.util.zip.ZipFile$ZipEntryIterator.nextElement(Unknown Source)
        at brut.androlib.Androlib.copyExistingFiles(Androlib.java:629)
        at brut.androlib.Androlib.buildUnknownFiles(Androlib.java:614)
        at brut.androlib.Androlib.build(Androlib.java:313)
        at brut.androlib.Androlib.build(Androlib.java:270)
        at brut.apktool.Main.cmdBuild(Main.java:227)
        at brut.apktool.Main.main(Main.java:75)
```

**Comment by iBotPeaches** [comment]
Must be related to some charsets. Do you have an application by chance at a downloadable location for me to investigate?

**Comment by cool-firer** [comment]
is this solved? I met the same question

**Comment by iBotPeaches** [comment]
I don't have an application of the original issue to triage. So closing. Sorry for 2-3 year delay.
