### ISSUE TITLE
Failed to build after decoding (v2.3.1)

### ISSUE THREAD

**Issue by Ghedeon** [iBotPeaches/Apktool#1722]
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.1
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat

```
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_6461121013153226369.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 25, --version-code, 897, --version-name, 2018.01.30-release, --no-version-vectors, -F, /tmp/APKTOOL1728417287348463949.tmp, -0, arsc, -0, txt, -0, arsc, -I, /home/ghedeon/.local/share/apktool/framework/1.apk, -S, /home/ghedeon/android/re/apktool/SoundCloud-com.soundcloud.android-2018.01.30-release-897/res, -M, /home/ghedeon/android/re/apktool/SoundCloud-com.soundcloud.android-2018.01.30-release-897/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:492)
	at brut.androlib.Androlib.buildResources(Androlib.java:426)
	at brut.androlib.Androlib.build(Androlib.java:305)
	at brut.androlib.Androlib.build(Androlib.java:270)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:75)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_6461121013153226369.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 25, --version-code, 897, --version-name, 2018.01.30-release, --no-version-vectors, -F, /tmp/APKTOOL1728417287348463949.tmp, -0, arsc, -0, txt, -0, arsc, -I, /home/ghedeon/.local/share/apktool/framework/1.apk, -S, /home/ghedeon/android/re/apktool/SoundCloud-com.soundcloud.android-2018.01.30-release-897/res, -M, /home/ghedeon/android/re/apktool/SoundCloud-com.soundcloud.android-2018.01.30-release-897/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:456)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:478)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_6461121013153226369.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 25, --version-code, 897, --version-name, 2018.01.30-release, --no-version-vectors, -F, /tmp/APKTOOL1728417287348463949.tmp, -0, arsc, -0, txt, -0, arsc, -I, /home/ghedeon/.local/share/apktool/framework/1.apk, -S, /home/ghedeon/android/re/apktool/SoundCloud-com.soundcloud.android-2018.01.30-release-897/res, -M, /home/ghedeon/android/re/apktool/SoundCloud-com.soundcloud.android-2018.01.30-release-897/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:450)
	... 6 more
```

### Steps to Reproduce
1. `apktool  d & apktool b`. No changes made in between.

### Frameworks
No

### APK
https://play.google.com/store/apps/details?id=com.soundcloud.android

**Comment by iBotPeaches** [comment]
```
➜  Bug1722 apktool b 0x1EC7DA75
I: Using Apktool 2.3.1-18143c-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
W: warning: string 'com_facebook_loginview_log_in_button_continue_f1gender' has no default translation.
W: warning: string 'com_facebook_loginview_log_in_button_continue_m2gender' has no default translation.
W: warning: string 'com_facebook_loginview_log_out_action_f1gender' has no default translation.
W: warning: string 'com_facebook_loginview_log_out_action_m2gender' has no default translation.
W: warning: string 'com_facebook_loginview_log_out_button_f1gender' has no default translation.
W: warning: string 'com_facebook_loginview_log_out_button_m2gender' has no default translation.
W: warning: string 'com_facebook_loginview_logged_in_as_f1gender' has no default translation.
W: warning: string 'com_facebook_loginview_logged_in_as_m2gender' has no default translation.
W: warning: string 'com_facebook_loginview_logged_in_using_facebook_f1gender' has no default translation.
W: warning: string 'com_facebook_loginview_logged_in_using_facebook_m2gender' has no default translation.
W: warning: string 'com_facebook_send_button_text_f1gender' has no default translation.
W: warning: string 'com_facebook_send_button_text_m2gender' has no default translation.
W: warning: string 'com_facebook_share_button_text_f1gender' has no default translation.
W: warning: string 'com_facebook_share_button_text_m2gender' has no default translation.
W: warning: string 'com_facebook_smart_login_confirmation_cancel_f1gender' has no default translation.
W: warning: string 'com_facebook_smart_login_confirmation_cancel_m2gender' has no default translation.
W: warning: string 'com_facebook_smart_login_confirmation_continue_as_f1gender' has no default translation.
W: warning: string 'com_facebook_smart_login_confirmation_continue_as_m2gender' has no default translation.
W: warning: string 'com_facebook_smart_login_confirmation_title_f1gender' has no default translation.
W: warning: string 'com_facebook_smart_login_confirmation_title_m2gender' has no default translation.
W: warning: string 'com_facebook_tooltip_default_f1gender' has no default translation.
W: warning: string 'com_facebook_tooltip_default_m2gender' has no default translation.
I: Copying libs... (/lib)
I: Copying libs... (/kotlin)
I: Building apk file...
I: Copying unknown files/dir...
➜  Bug1722 
```

Couldn't replicate and the error above is the exception, no stacktrace of the errors before.

**Comment by Ghedeon** [comment]
@iBotPeaches Could you point me to `2.3.1-18143c-SNAPSHOT` binary, please?

The warning before the exception is about styles:
`W: /home/ghedeon/android/re/apktool/SoundCloud-com.soundcloud.android-2018.01.30-release-897/res/values-v24/styles.xml:7: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Animation.OptionsPanel'.
W: 
W: /home/ghedeon/android/re/apktool/SoundCloud-com.soundcloud.android-2018.01.30-release-897/res/values-v24/styles.xml:8: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Animation.LockScreen'.
W: 
`

**Comment by iBotPeaches** [comment]
Snapshot won't make a difference. Its readme changes. Try running `apktool empty-framework-dir` and try again.

**Comment by Ghedeon** [comment]
Hurray, that was it! Must be a framework from an older version. Good to know, thanks for your time.
