### ISSUE TITLE
No resource identifier found for attribute 'keyboardNavigationCluster' in package 'android'

### ISSUE THREAD

**Issue by ALBARAA78** [iBotPeaches/Apktool#1725]
### Information
1. **Apktool Version (`Apktool 2.3.1-dirty`)** -
2. **Operating System (kali Linux)** -

### Stacktrace/Logcat

```
root@kali:~/Desktop/android# apktool b flud
I: Using Apktool 2.3.1-dirty
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: /root/Desktop/android/flud/res/layout-v26/abc_screen_toolbar.xml:5: error: No resource identifier found for attribute 'keyboardNavigationCluster' in package 'android'
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/usr/bin/aapt, p, --min-sdk-version, 16, --target-sdk-version, 26, --version-code, 2000063, --version-name, 1.4.9, --no-version-vectors, -F, /tmp/APKTOOL2425291836467112866.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/Desktop/android/flud/res, -M, /root/Desktop/android/flud/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:492)
	at brut.androlib.Androlib.buildResources(Androlib.java:426)
	at brut.androlib.Androlib.build(Androlib.java:305)
	at brut.androlib.Androlib.build(Androlib.java:270)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:75)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/usr/bin/aapt, p, --min-sdk-version, 16, --target-sdk-version, 26, --version-code, 2000063, --version-name, 1.4.9, --no-version-vectors, -F, /tmp/APKTOOL2425291836467112866.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/Desktop/android/flud/res, -M, /root/Desktop/android/flud/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:456)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:478)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/usr/bin/aapt, p, --min-sdk-version, 16, --target-sdk-version, 26, --version-code, 2000063, --version-name, 1.4.9, --no-version-vectors, -F, /tmp/APKTOOL2425291836467112866.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /root/Desktop/android/flud/res, -M, /root/Desktop/android/flud/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:450)
	... 6 more
```

### APK
https://drive.google.com/open?id=1_F4_3OlufFLu1N_wM8eUKgq_fzG6QtiF

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? YES
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version? YES

        I tried ( apktool empty-framework-dir --force ) and it didn't solve the issue

root@kali:~/Desktop/android# apktool empty-framework-dir --force
I: Removing 1.apk framework file...

**Comment by ALBARAA78** [comment]
NVM i solved it by editing '[ * ]/res/layout-v26/abc_screen_toolbar.xml' 


`<?xml version="1.0" encoding="utf-8"?>
<android.support.v7.widget.ActionBarOverlayLayout android:id="@id/decor_content_parent" android:fitsSystemWindows="true" android:layout_width="fill_parent" android:layout_height="fill_parent"
  xmlns:android="http://schemas.android.com/apk/res/android" xmlns:app="http://schemas.android.com/apk/res-auto">
    <include layout="@layout/abc_screen_content_include" />
        <android.support.v7.widget.ActionBarContextView android:theme="?actionBarTheme" android:id="@id/action_context_bar" android:visibility="gone" android:layout_width="fill_parent" android:layout_height="wrap_content" style="?attr/actionModeStyle" />
</android.support.v7.widget.ActionBarOverlayLayout>`

**Comment by iBotPeaches** [comment]
That property was added in the apktool 2.3.1 internal framework. So not a bug. See #1579

**Comment by JiaDuo** [comment]
I tried ( apktool empty-framework-dir --force ) and it solve the issue!!!!
@ALBARAA78
