### ISSUE TITLE
ApkTool Error

### ISSUE THREAD

**Issue by egymummy** [iBotPeaches/Apktool#1727]
```
C:\WINDOWS>apktool d 4.apk
I: Using Apktool 2.3.1 on 4.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.Direc
toryException: file must be a directory: 4
        at brut.androlib.res.AndrolibResources.decodeManifestWithResources(Andro
libResources.java:227)
        at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:137)

        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:122)
        at brut.apktool.Main.cmdDecode(Main.java:163)
        at brut.apktool.Main.main(Main.java:72)
Caused by: brut.directory.DirectoryException: file must be a directory: 4
        at brut.directory.FileDirectory.<init>(FileDirectory.java:38)
        at brut.androlib.res.AndrolibResources.decodeManifestWithResources(Andro
libResources.java:207)
        ... 4 more
```
### Information
1. **Apktool Version (`apktool -version`)** -  2.3.1 
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Android APK

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
that what i suspect that this APK use its Own framework , But I can't Locate It

### APK
http://apkleecher.com/com.nst.iptvsmarters/

Proceed Down To Download Page

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes , error
2. If you are trying to install a modified apk, did you resign it? No , I can't Correctly Decompile
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
```
➜  1727 apktool d com.nst.iptvsmarters_11.apk 
I: Using Apktool 2.3.1 on com.nst.iptvsmarters_11.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  1727 
```

Couldn't replicate. Looks like you might have a directory/file named "4" so it decode didn't work. Try using `-o` and select a different folder to decode too
