### ISSUE TITLE
Failed to build (v2.3.1)

### ISSUE THREAD

**Issue by lingyun0129** [iBotPeaches/Apktool#1732]
### Information
1.Apktool Version (apktool -version) - 2.3.1
2.Operating System (Mac, Linux, Windows) - windows
3.APK From? (Playstore, ROM, Other) - other

### Stacktrace/Logcat
```
I: Using Apktool 2.3.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: warning: string 'setup_complete_message' has no default translation.
W: warning: string 'tos_agreement_text' has no default translation.
W: warning: string 'walled_garden_check_text' has no default translation.
W: E:\tools\develop_tools\apkDecompiler\setupWizard_default\res\layout\settings_with_drawer.xml:6: error: Error: Resource is not public. (at 'navigationContentDescription' with value '@android:string/permlab_uninstall_shortcut').
Exception in thread "main" W:
brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\user\AppData\Local\Temp\brut_util_Jar_4838559093046371515.tmp, p, --forced-package-id, 127, --min-sdk-version, 23, --target-sdk-version, 24, --version-code, 224, --v
ersion-name, 224.3779664, --no-version-vectors, -F, C:\Users\user\AppData\Local\Temp\APKTOOL5416826374839581339.tmp, -0, arsc, -0, arsc, -I, C:\Users\user\AppData\Local\apktool\framework\1.apk, -S, E:\tools\develop_tools\apkDecompiler\setupWizard_default\res, -M, E:\tools\develop_tools\apkDecompiler
\setupWizard_default\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:492)
        at brut.androlib.Androlib.buildResources(Androlib.java:426)
        at brut.androlib.Androlib.build(Androlib.java:305)
        at brut.androlib.Androlib.build(Androlib.java:270)
        at brut.apktool.Main.cmdBuild(Main.java:227)
        at brut.apktool.Main.main(Main.java:75)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\user\AppData\Local\Temp\brut_util_Jar_4838559093046371515.tmp, p, --forced-package-id, 127, --min-sdk-version, 23, --target-sdk-version, 24, --version-code, 224, --version-name, 224.37796
64, --no-version-vectors, -F, C:\Users\user\AppData\Local\Temp\APKTOOL5416826374839581339.tmp, -0, arsc, -0, arsc, -I, C:\Users\user\AppData\Local\apktool\framework\1.apk, -S, E:\tools\develop_tools\apkDecompiler\setupWizard_default\res, -M, E:\tools\develop_tools\apkDecompiler\setupWizard_default\A
ndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:456)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:478)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\user\AppData\Local\Temp\brut_util_Jar_4838559093046371515.tmp, p, --forced-package-id, 127, --min-sdk-version, 23, --target-sdk-version, 24, --version-code, 224, --version-name, 224.3779664, --no-version-vectors, -F, C:\
Users\user\AppData\Local\Temp\APKTOOL5416826374839581339.tmp, -0, arsc, -0, arsc, -I, C:\Users\user\AppData\Local\apktool\framework\1.apk, -S, E:\tools\develop_tools\apkDecompiler\setupWizard_default\res, -M, E:\tools\develop_tools\apkDecompiler\setupWizard_default\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:450)
        ... 6 more
Include stacktrace here
```

### Steps to Reproduce
1. apktool empty-framework-dir 
2.apktool d setupWizard.apk
3.apktood b setupWizard -o new-setupWizard.apk
No changes made in between.
logcat like #1722, I try running apktool empty-framework-dir ,but it doesn't work!

**Comment by lingyun0129** [comment]
[setupWizard_default.zip](https://github.com/iBotPeaches/Apktool/files/1754151/setupWizard_default.zip)

**Comment by iBotPeaches** [comment]
```
➜  1732 unzip -l setupWizard_default.zip 
Archive:  setupWizard_default.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
```

**Comment by lingyun0129** [comment]
[setupWizard_default.zip](https://github.com/iBotPeaches/Apktool/files/1756933/setupWizard_default.zip)

**Comment by lingyun0129** [comment]
I'm so sorry ,Upload again setupWizard_default.zip

**Comment by iBotPeaches** [comment]
This is not a bug. AOSP maintains private/public resources. The recommend use-case is to copy any resource locally into your application, because at any point any private resource could change and in rare circumstances a public resource becomes private.

I don't think I know of any public string resources, which this application is using. It was probably built using an older version of aapt where this restriction wasn't in place.

```
    <!-- Title of an application permission, listed so the user can uninstall application shortcuts
    in their Launcher -->
    <string name="permlab_uninstall_shortcut">uninstall shortcuts</string>
```

That is the string in AOSP. Bring that string internal and reference it as such.
