### ISSUE TITLE
Stuck compiling

### ISSUE THREAD

**Issue by Octolus** [iBotPeaches/Apktool#1733]
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.1
2. **Operating System (Mac, Linux, Windows)** - Windows 10 64bit
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat

```
Include stacktrace here
`24.02.2018 16.13.18
Compiling APK file...

/c "java -Xmx1024m -jar "C:\Users\Octolus\Desktop\Avakin APK Research\Apktool\apktool_2.3.1.jar" b -f -o "C:\Users\Octolus\Documents\APK Easy Tool\2-Recompiled APKs\com.lockwoodpublishing.avakinlife-1014000200.apk" "C:\Users\Octolus\Documents\APK Easy Tool\1-Decompiled APKs\com.lockwoodpublishing.avakinlife-1014000200" "

I: Using Apktool 2.3.1
I: Smaling smali folder into classes.dex...
I: Smaling smali_assets folder into assets.dex...
I: Smaling smali_classes2 folder into classes2.dex...
I: Building resources...
Exception in thread "main" 
------------------------------------------
``


### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? ??
2. If you are trying to install a modified apk, did you resign it? ??
3. Are you using the latest apktool version? Yes

**Comment by Octolus** [comment]
Direct Download: http://down1.koplayer.com/autoapk/com.lockwoodpublishing.avakinlife/com.lockwoodpublishing.avakinlife-1014000200.apk

Please note: The software decompiled it fine, however I can't compile it back. I have not done any modifications whatsoever, just wanted to see if it can even compile it. The software is Unity game.

**Comment by iBotPeaches** [comment]
Unfortunately the log that would have been generated is not present in that stacktrace. There should be some lines after the `Exception in thread "main""`

**Comment by Octolus** [comment]
I used the GUI for it :(

**Comment by iBotPeaches** [comment]
Sorry, not really anything for me to go on here without that stacktrace. We can reopen if you can get that data.

**Comment by Octolus** [comment]
@iBotPeaches 

K Easy Tool\1-Decompiled APKs\Avakin Life 3D virtual world_v1.018.04_apkpure.com\build\apk]
        at brut.util.OS.exec(OS.java:97)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:450)
        ... 5 more
Caused by: java.io.IOException: Cannot run program "C:\Users\Octolus\AppData\Local\Temp\brut_util_Jar_9810829858454822265.tmp": CreateProcess error=206, Filnavnet eller filtypen er for lang
        at java.base/java.lang.ProcessBuilder.start(Unknown Source)
        at java.base/java.lang.ProcessBuilder.start(Unknown Source)
        at brut.util.OS.exec(OS.java:90)
        ... 6 more
Caused by: java.io.IOException: CreateProcess error=206, Filnavnet eller filtypen er for lang
        at java.base/java.lang.ProcessImpl.create(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
        at java.base/java.lang.ProcessImpl.start(Unknown Source)
        ... 9 more
