### ISSUE TITLE
bug in decompile some apks in version 2.3.1 that we can decompile in 2.2.0

### ISSUE THREAD

**Issue by mohamadk** [iBotPeaches/Apktool#1735]
### Information
1. **Apktool Version (v2.3.1 )** -
2. **Operating System ( Windows)** -
3. **APK From? (Other)** -

### Stacktrace/Logcat

```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 1544
        at java.lang.String.substring(Unknown Source)
        at brut.androlib.res.decoder.StringBlock.getHTML(StringBlock.java:171)
        at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:341)
        at brut.androlib.res.decoder.ARSCDecoder.readEntryData(ARSCDecoder.java:257)
        at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:233)
        at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:156)
        at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:118)
        at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:80)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:599)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:73)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:65)
        at brut.androlib.Androlib.getResTable(Androlib.java:68)
        at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:228)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:118)
        at brut.apktool.Main.cmdDecode(Main.java:163)
        at brut.apktool.Main.main(Main.java:72)
```

### Steps to Reproduce
1. `apktool d app_version.apk`

### APK
https://drive.google.com/file/d/1KNneUcSmQ2oJ9D03WmgityO5LdA4YHPl/view?usp=sharing

### Bug in version 2.3.1
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
.2. If you are trying to install a modified apk, did you resign it? I just want to decompile manifest. so I don't need to.
3. Are you using the latest apktool version? yes

If you decompile this apk with version 2.3.1 you get an error but if you use version 2.2.0 you don't get any error.

**Comment by iBotPeaches** [comment]
Confirmed. v2.2.0 is nearly 2 years old now, but thanks for the information. Regression that far can no longer just be reverted so a new patch will have to be made.

**Comment by iBotPeaches** [comment]
Merging this into https://github.com/iBotPeaches/Apktool/issues/2244
