### ISSUE TITLE
Kotlin response objects -> Caused by: java.lang.IllegalArgumentException: Unable to create converter for class <name-of-kotlin-class>

### ISSUE THREAD

**Issue by sahibjaspal** [iBotPeaches/Apktool#1736]
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.1
2. **Operating System (Mac, Linux, Windows)** - Mac
3. **APK From? (Playstore, ROM, Other)** -from AndroidStudio -> generate signed apk

### Stacktrace/Logcat

```
02-26 10:56:55.915 17987-17987/? E/UncaughtException: java.lang.RuntimeException: Unable to create application com.zappos.android.ZapposApplication: java.lang.IllegalArgumentException: Unable to create converter for class com.zappos.android.mafiamodel.s3.ForceUpgradeResponse
                                                          for method S3Service.getForceUpgradeVersion
                                                          at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4589)
                                                          at android.app.ActivityThread.access$1500(ActivityThread.java:145)
                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1276)
                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                          at android.os.Looper.loop(Looper.java:145)
                                                          at android.app.ActivityThread.main(ActivityThread.java:5266)
                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:826)
                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:642)
                                                          at dalvik.system.NativeStart.main(Native Method)
                                                       Caused by: java.lang.IllegalArgumentException: Unable to create converter for class com.zappos.android.mafiamodel.s3.ForceUpgradeResponse
                                                          for method S3Service.getForceUpgradeVersion
                                                          at retrofit2.ServiceMethod$Builder.methodError(ServiceMethod.java:720)
                                                          at retrofit2.ServiceMethod$Builder.createResponseConverter(ServiceMethod.java:706)
                                                          at retrofit2.ServiceMethod$Builder.build(ServiceMethod.java:167)
                                                          at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:166)
                                                          at retrofit2.Retrofit$1.invoke(Retrofit.java:145)
                                                          at $Proxy2.getForceUpgradeVersion(Native Method)
                                                          at com.zappos.android.ZapposApplication.checkForceUpgradeVersion(ZapposApplication.java:212)
                                                          at com.zappos.android.ZapposApplication.onCreate(ZapposApplication.java:189)
                                                          at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                          at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4586)
                                                          	... 10 more
                                                       Caused by: java.lang.IllegalStateException: Resource not found in classpath: kotlin/kotlin.kotlin_builtins
                                                          at kotlin.reflect.jvm.internal.impl.builtins.BuiltInsPackageFragmentProviderKt.a(builtInsPackageFragmentProvider.kt:39)
                                                          at kotlin.reflect.jvm.internal.impl.builtins.KotlinBuiltIns.c(KotlinBuiltIns.java:138)
                                                          at kotlin.reflect.jvm.internal.impl.platform.JvmBuiltIns.<init>(JvmBuiltIns.kt:56)
                                                          at kotlin.reflect.jvm.internal.impl.platform.JvmBuiltIns.<init>(JvmBuiltIns.kt:31)
                                                          at kotlin.reflect.jvm.internal.impl.load.kotlin.reflect.RuntimeModuleData$Companion.a(RuntimeModuleData.kt:50)
                                                          at kotlin.reflect.jvm.internal.ModuleByClassLoaderKt.a(moduleByClassLoader.kt:58)
                                                          at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data$moduleData$2.invoke(KDeclarationContainerImpl.kt:1036)
                                                          at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.a(ReflectProperties.java:93)
                                                          at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data.n(KDeclarationContainerImpl.kt:1032)
                                                          at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:1042)
                                                          at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.a(ReflectProperties.java:93)
                                                          at kotlin.reflect.jvm.internal.KClassImpl$Data.a(KClassImpl.kt:1032)
                                                          at kotlin.reflect.jvm.internal.KClassImpl.g(KClassImpl.kt:159)
                                                          at kotlin.reflect.jvm.internal.KClassImpl.i(KClassImpl.kt:165)
                                                          at kotlin.reflect.jvm.internal.KClassImpl$Data$declaredNonStaticMembers$2.invoke(KClassImpl.kt:1139)
                                                          at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.a(ReflectProperties.java:93)
                                                          at kotlin.reflect.jvm.internal.KClassImpl$Data.f(KClassImpl.kt:6032)
                                                          at kotlin.reflect.full.KClasses.f(KClasses.kt:163)
                                                          at com.fasterxml.jackson.module.kotlin.KotlinAnnotationIntrospector.getCorrespondingGetter(KotlinAnnotationIntrospector.kt:78)
                                                          at com.fasterxml.jackson.module.kotlin.KotlinAnnotationIntrospector.hasRequiredMarker(KotlinAnnotationIntrospector.kt:47)
                                                          at com.fasterxml.jackson.module.kotlin.KotlinAnnotationIntrospector.hasRequiredMarker(KotlinAnnotationIntrospector.kt:33)
                                                      	at com.fasterxml.jackson.databind.introspect.AnnotationIntrospectorPair.hasRequiredMarker(AnnotationIntrospectorPair.j
```

### Steps to Reproduce
1. apktool d <apk>
2. change the manifest and rebuild the signed apk
3. install the apk on a device - adb install <package-name>
4. Throws an exception only if the response object is a kotlin file, it works fine for java files

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? I changed the manifest file and resigned it using buildtools->zipalign and apksigner
3. Are you using the latest apktool version? yes

**Comment by iBotPeaches** [comment]
I think I fixed this already, upcoming in next release: https://github.com/iBotPeaches/Apktool/commit/bca474272eab6b5095c0c7ac6026bc6f24c4b676

**Comment by sahibjaspal** [comment]
@iBotPeaches Thank you for the prompt response. Any idea when the next release would be?

**Comment by iBotPeaches** [comment]
There is a release due in March, probably mid-month.

**Comment by sahibjaspal** [comment]
Thanks a lot! I'll close the issue
