### ISSUE TITLE
Simply decompile-build doesn't work

### ISSUE THREAD

**Issue by simonesessa** [iBotPeaches/Apktool#1740]
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.1
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore)** - Infostud Mobile (Sapienza)

### Stacktrace/Logcat

```
DECOMPILE:
I: Using Apktool 2.3.1 on infostud.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Simone\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
S: Could not decode file, replacing by FALSE value: drawable-hdpi/vpi__tab_unselected_pressed_holo.9.png
S: Could not decode file, replacing by FALSE value: drawable-hdpi/vpi__tab_selected_focused_holo.9.png
S: Could not decode file, replacing by FALSE value: drawable-mdpi/vpi__tab_unselected_holo.9.png
S: Could not decode file, replacing by FALSE value: drawable-mdpi/vpi__tab_unselected_pressed_holo.9.png
S: Could not decode file, replacing by FALSE value: drawable-hdpi/vpi__tab_unselected_holo.9.png
S: Could not decode file, replacing by FALSE value: drawable-xhdpi/vpi__tab_selected_holo.9.png
S: Could not decode file, replacing by FALSE value: drawable-hdpi/vpi__tab_selected_holo.9.png
S: Could not decode file, replacing by FALSE value: drawable-mdpi/vpi__tab_selected_focused_holo.9.png
S: Could not decode file, replacing by FALSE value: drawable-xhdpi/vpi__tab_selected_focused_holo.9.png
S: Could not decode file, replacing by FALSE value: drawable-xhdpi/vpi__tab_unselected_holo.9.png
S: Could not decode file, replacing by FALSE value: drawable-mdpi/vpi__tab_selected_pressed_holo.9.png
S: Could not decode file, replacing by FALSE value: drawable-xhdpi/vpi__tab_unselected_focused_holo.9.png
S: Could not decode file, replacing by FALSE value: drawable-hdpi/vpi__tab_unselected_focused_holo.9.png
S: Could not decode file, replacing by FALSE value: drawable-mdpi/vpi__tab_selected_holo.9.png
S: Could not decode file, replacing by FALSE value: drawable-xhdpi/vpi__tab_selected_pressed_holo.9.png
S: Could not decode file, replacing by FALSE value: drawable-mdpi/vpi__tab_unselected_focused_holo.9.png
S: Could not decode file, replacing by FALSE value: drawable-xhdpi/vpi__tab_unselected_pressed_holo.9.png
S: Could not decode file, replacing by FALSE value: drawable-hdpi/vpi__tab_selected_pressed_holo.9.png
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
```
BUILD
```
I: Using Apktool 2.3.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: libpng error: Read Error
W: ERROR: Failure processing PNG image I:\Dev\Android\Apktool\.\infostud\res\drawable-mdpi-v4\vpi__tab_selected_focused_holo.9.png
W: libpng error: Read Error
W: ERROR: Failure processing PNG image I:\Dev\Android\Apktool\.\infostud\res\drawable-hdpi-v4\vpi__tab_selected_focused_holo.9.png
W: libpng error: Read Error
W: ERROR: Failure processing PNG image I:\Dev\Android\Apktool\.\infostud\res\drawable-xhdpi-v4\vpi__tab_selected_focused_holo.9.png
W: libpng error: Read Error
W: ERROR: Failure processing PNG image I:\Dev\Android\Apktool\.\infostud\res\drawable-mdpi-v4\vpi__tab_selected_holo.9.png
W: libpng error: Read Error
W: ERROR: Failure processing PNG image I:\Dev\Android\Apktool\.\infostud\res\drawable-hdpi-v4\vpi__tab_selected_holo.9.png
Exception in thread "main" W: libpng error: Read Error
W: ERROR: Failure processing PNG image I:\Dev\Android\Apktool\.\infostud\res\drawable-xhdpi-v4\vpi__tab_selected_holo.9.png
brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Simone\AppData\Local\Temp\brut_util_Jar_6160882795394552955.tmp, p, --forced-package-id, 127, --min-sdk-version, 7, --version-code, 16, --version-name, 2.2.6, --no-version-vectors, -F, C:\Users\Simone\AppData\Local\Temp\APKTOOL8994566848640962709.tmp, -0, arsc, -0, PNG, -0, arsc, -I, C:\Users\Simone\AppData\Local\apktool\framework\1.apk, -S, I:\Dev\Android\Apktool\.\infostud\res, -M, I:\Dev\Android\Apktool\.\infostud\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:492)
        at brut.androlib.Androlib.buildResources(Androlib.java:426)
        at brut.androlib.Androlib.build(Androlib.java:305)
        at brut.androlib.Androlib.build(Androlib.java:270)
        at brut.apktool.Main.cmdBuild(Main.java:227)
        at brut.apktool.Main.main(Main.java:75)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Simone\AppData\Local\Temp\brut_util_Jar_6160882795394552955.tmp, p, --forced-package-id, 127, --min-sdk-version, 7, --version-code, 16, --version-name, 2.2.6, --no-version-vectors, -F, C:\Users\Simone\AppData\Local\Temp\APKTOOL8994566848640962709.tmp, -0, arsc, -0, PNG, -0, arsc, -I, C:\Users\Simone\AppData\Local\apktool\framework\1.apk, -S, I:\Dev\Android\Apktool\.\infostud\res, -M, I:\Dev\Android\Apktool\.\infostud\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:456)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:478)
        ... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Simone\AppData\Local\Temp\brut_util_Jar_6160882795394552955.tmp, p, --forced-package-id, 127, --min-sdk-version, 7, --version-code, 16, --version-name, 2.2.6, --no-version-vectors, -F, C:\Users\Simone\AppData\Local\Temp\APKTOOL8994566848640962709.tmp, -0, arsc, -0, PNG, -0, arsc, -I, C:\Users\Simone\AppData\Local\apktool\framework\1.apk, -S, I:\Dev\Android\Apktool\.\infostud\res, -M, I:\Dev\Android\Apktool\.\infostud\AndroidManifest.xml]
        at brut.util.OS.exec(OS.java:95)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:450)
        ... 6 more
W: libpng error: Read Error
W: ERROR: Failure processing PNG image I:\Dev\Android\Apktool\.\infostud\res\drawable-mdpi-v4\vpi__tab_selected_pressed_holo.9.png
W: libpng error: Read Error
W: ERROR: Failure processing PNG image I:\Dev\Android\Apktool\.\infostud\res\drawable-hdpi-v4\vpi__tab_selected_pressed_holo.9.png
W: libpng error: Read Error
W: ERROR: Failure processing PNG image I:\Dev\Android\Apktool\.\infostud\res\drawable-xhdpi-v4\vpi__tab_selected_pressed_holo.9.png
W: libpng error: Read Error
W: ERROR: Failure processing PNG image I:\Dev\Android\Apktool\.\infostud\res\drawable-mdpi-v4\vpi__tab_unselected_focused_holo.9.png
W: libpng error: Read Error
W: ERROR: Failure processing PNG image I:\Dev\Android\Apktool\.\infostud\res\drawable-hdpi-v4\vpi__tab_unselected_focused_holo.9.png
W: libpng error: Read Error
W: ERROR: Failure processing PNG image I:\Dev\Android\Apktool\.\infostud\res\drawable-xhdpi-v4\vpi__tab_unselected_focused_holo.9.png
W: libpng error: Read Error
W: ERROR: Failure processing PNG image I:\Dev\Android\Apktool\.\infostud\res\drawable-mdpi-v4\vpi__tab_unselected_holo.9.png
W: libpng error: Read Error
W: ERROR: Failure processing PNG image I:\Dev\Android\Apktool\.\infostud\res\drawable-hdpi-v4\vpi__tab_unselected_holo.9.png
W: libpng error: Read Error
W: ERROR: Failure processing PNG image I:\Dev\Android\Apktool\.\infostud\res\drawable-xhdpi-v4\vpi__tab_unselected_holo.9.png
W: libpng error: Read Error
W: ERROR: Failure processing PNG image I:\Dev\Android\Apktool\.\infostud\res\drawable-mdpi-v4\vpi__tab_unselected_pressed_holo.9.png
W: libpng error: Read Error
W: ERROR: Failure processing PNG image I:\Dev\Android\Apktool\.\infostud\res\drawable-hdpi-v4\vpi__tab_unselected_pressed_holo.9.png
W: libpng error: Read Error
W: ERROR: Failure processing PNG image I:\Dev\Android\Apktool\.\infostud\res\drawable-xhdpi-v4\vpi__tab_unselected_pressed_holo.9.png
```

### Steps to Reproduce
1. `apktool d infostud.apk`
2. `apktool b infostud`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
Download here: https://drive.google.com/file/d/1imFuUmrulXl3bEfczrct0xGVHU5F_bVs/view?usp=sharing

### Questions to ask before submission
**1. Have you tried `apktool d`, `apktool b` without changing anything? Yes, this is the main problem.**
2. If you are trying to install a modified apk, did you resign it? No.
3. Are you using the latest apktool version? Yes.

I would to decompile and then recompile this apk, but I have some errors with png. I searched the png online and I've replaced them, but I have this error (for each png):
```
W: I:\Dev\Android\Apktool\.\infostud-old2\res\values-xhdpi-v4\drawables.xml:8: error: Resource entry vpi__tab_unselected_pressed_holo is already defined.
W: res\drawable-xhdpi-v4\vpi__tab_unselected_pressed_holo.9.png:0: Originally defined here.
(you can download the missed png here: https://github.com/JakeWharton/ViewPagerIndicator - go in "library/res/")
```

**Comment by simonesessa** [comment]
Help please!

**Comment by iBotPeaches** [comment]
Sorry for the delay. In the case of the above images, they are all 0byte images. Apktool cannot decode or do anything with these images. The original application is built improperly. If you wish to rebuild this, you will have to fix these bad images.

There is nothing Apktool can really do here. Maybe a far off feature request is to detect 0byte image and replace them with dummy boolean values.
