### ISSUE TITLE
Erreur Recompling Apk on Advanced ApkTool v4.2.0 By BDFreak - Apktool Version 2.3.1

### ISSUE THREAD

**Issue by Eloko657** [iBotPeaches/Apktool#1745]
hello guys please help me ...
***  i had i problem with recompling apk on Advanced ApkTool v4.2.0 By BDFreak 
*** JAVA Version : 1.8.0-162

THIS Is erreur Message : 

Log For : Tv-Maroc.apk 

 Log Type : Recompiling 

 Log Recorded At : 14 2018-03- 4:59:24,90 

 Log Recorded By : Advanced ApkTool v4.2.0 By BDFreak 

------------------------------------------------------ 

W: C:\Users\super\Desktop\df\3-Out\Tv-Maroc.apk\res\values-v24\styles.xml:3: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Animation.OptionsPanel'.
W: 
W: C:\Users\super\Desktop\df\3-Out\Tv-Maroc.apk\res\values-v24\styles.xml:4: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Animation.LockScreen'.
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\super\AppData\Local\Temp\brut_util_Jar_4713352827354182897.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 27, --version-code, 9, --version-name, 3.2, --no-version-vectors, -F, C:\Users\super\AppData\Local\Temp\APKTOOL9204819879474388833.tmp, -0, arsc, -0, META-INF/android.arch.core_runtime.version, -0, META-INF/android.arch.lifecycle_livedata-core.version, -0, META-INF/android.arch.lifecycle_runtime.version, -0, META-INF/android.arch.lifecycle_viewmodel.version, -0, META-INF/com.android.support_animated-vector-drawable.version, -0, META-INF/com.android.support_appcompat-v7.version, -0, META-INF/com.android.support_cardview-v7.version, -0, META-INF/com.android.support_design.version, -0, META-INF/com.android.support_recyclerview-v7.version, -0, META-INF/com.android.support_support-compat.version, -0, META-INF/com.android.support_support-core-ui.version, -0, META-INF/com.android.support_support-core-utils.version, -0, META-INF/com.android.support_support-fragment.version, -0, META-INF/com.android.support_support-media-compat.version, -0, META-INF/com.android.support_support-v4.version, -0, META-INF/com.android.support_support-vector-drawable.version, -0, META-INF/com.android.support_transition.version, -0, arsc, -I, C:\Users\super\Desktop\df\1-BDFreak\Frameworks\1.apk, -S, C:\Users\super\Desktop\df\3-Out\Tv-Maroc.apk\res, -M, C:\Users\super\Desktop\df\3-Out\Tv-Maroc.apk\AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:492)
	at brut.androlib.Androlib.buildResources(Androlib.java:426)
	at brut.androlib.Androlib.build(Androlib.java:305)
	at brut.androlib.Androlib.build(Androlib.java:270)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:75)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\super\AppData\Local\Temp\brut_util_Jar_4713352827354182897.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 27, --version-code, 9, --version-name, 3.2, --no-version-vectors, -F, C:\Users\super\AppData\Local\Temp\APKTOOL9204819879474388833.tmp, -0, arsc, -0, META-INF/android.arch.core_runtime.version, -0, META-INF/android.arch.lifecycle_livedata-core.version, -0, META-INF/android.arch.lifecycle_runtime.version, -0, META-INF/android.arch.lifecycle_viewmodel.version, -0, META-INF/com.android.support_animated-vector-drawable.version, -0, META-INF/com.android.support_appcompat-v7.version, -0, META-INF/com.android.support_cardview-v7.version, -0, META-INF/com.android.support_design.version, -0, META-INF/com.android.support_recyclerview-v7.version, -0, META-INF/com.android.support_support-compat.version, -0, META-INF/com.android.support_support-core-ui.version, -0, META-INF/com.android.support_support-core-utils.version, -0, META-INF/com.android.support_support-fragment.version, -0, META-INF/com.android.support_support-media-compat.version, -0, META-INF/com.android.support_support-v4.version, -0, META-INF/com.android.support_support-vector-drawable.version, -0, META-INF/com.android.support_transition.version, -0, arsc, -I, C:\Users\super\Desktop\df\1-BDFreak\Frameworks\1.apk, -S, C:\Users\super\Desktop\df\3-Out\Tv-Maroc.apk\res, -M, C:\Users\super\Desktop\df\3-Out\Tv-Maroc.apk\AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:456)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:478)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\super\AppData\Local\Temp\brut_util_Jar_4713352827354182897.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 27, --version-code, 9, --version-name, 3.2, --no-version-vectors, -F, C:\Users\super\AppData\Local\Temp\APKTOOL9204819879474388833.tmp, -0, arsc, -0, META-INF/android.arch.core_runtime.version, -0, META-INF/android.arch.lifecycle_livedata-core.version, -0, META-INF/android.arch.lifecycle_runtime.version, -0, META-INF/android.arch.lifecycle_viewmodel.version, -0, META-INF/com.android.support_animated-vector-drawable.version, -0, META-INF/com.android.support_appcompat-v7.version, -0, META-INF/com.android.support_cardview-v7.version, -0, META-INF/com.android.support_design.version, -0, META-INF/com.android.support_recyclerview-v7.version, -0, META-INF/com.android.support_support-compat.version, -0, META-INF/com.android.support_support-core-ui.version, -0, META-INF/com.android.support_support-core-utils.version, -0, META-INF/com.android.support_support-fragment.version, -0, META-INF/com.android.support_support-media-compat.version, -0, META-INF/com.android.support_support-v4.version, -0, META-INF/com.android.support_support-vector-drawable.version, -0, META-INF/com.android.support_transition.version, -0, arsc, -I, C:\Users\super\Desktop\df\1-BDFreak\Frameworks\1.apk, -S, C:\Users\super\Desktop\df\3-Out\Tv-Maroc.apk\res, -M, C:\Users\super\Desktop\df\3-Out\Tv-Maroc.apk\AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:450)

**Comment by Eloko657** [comment]
Here is The Link of My Apk that i want to recompile ======https://drive.google.com/drive/folders/1ziLDdGJ_1CNjSk4GtOt53ZAjYq_7UJlg?usp=sharing

**Comment by iBotPeaches** [comment]
Looks like out of date framework. This is not an issue locally. Please try running: 
```
apktool empty-framework-dir --force
```
and try-again
