### ISSUE TITLE
App failed when decompiling and building with apktool

### ISSUE THREAD

**Issue by danypacf** [iBotPeaches/Apktool#1750]
### Information
1. **Apktool Version (`apktool -version`)** -  2.3.1
2. **Operating System (Mac, Linux, Windows)** - Windows 7 64-bit
3. **APK From? (Playstore, ROM, Other)** - Google Play or APKMirror

### Stacktrace/Logcat

**Decode:**

```
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: Error copying file: ??.xml
	at brut.androlib.Androlib.decodeUnknownFiles(Androlib.java:224)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:172)
	at brut.apktool.Main.cmdDecode(Main.java:163)
	at brut.apktool.Main.main(Main.java:72)
Caused by: brut.directory.DirectoryException: Error copying file: ??.xml
	at brut.directory.DirUtil.copyToDir(DirUtil.java:88)
	at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:208)
	at brut.androlib.Androlib.decodeUnknownFiles(Androlib.java:217)
	... 3 more
Caused by: java.io.FileNotFoundException: C:\Users\Sala ITSA\Downloads\AdvancedApkTool\3-Out\26545.apk\unknown\??.xml (El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:84)
	... 5 more
```
**Build:**
```
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.PathNotExist: apktool.yml
	at brut.androlib.Androlib.readMetaFile(Androlib.java:265)
	at brut.androlib.Androlib.build(Androlib.java:277)
	at brut.androlib.Androlib.build(Androlib.java:270)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:75)
Caused by: brut.directory.PathNotExist: apktool.yml
	at brut.directory.AbstractDirectory.getFileInput(AbstractDirectory.java:106)
	at brut.androlib.Androlib.readMetaFile(Androlib.java:261)
	... 4 more
```
### Steps to Reproduce
1. `apktool d netflix.apk
2. `apktool b netflix.apk

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

https://www.apkmirror.com/apk/netflix-inc/netflix/netflix-5-15-2-build-26545-release/netflix-5-15-2-build-26545-android-apk-download/

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes, I did
2. If you are trying to install a modified apk, did you resign it? No.
3. Are you using the latest apktool version? Yes, I do

**Comment by danypacf** [comment]
@iBotPeaches what is the problem?  I feel that the problems involving to AAPT2 or AAPT1

**Comment by iBotPeaches** [comment]
None actually. It is a known issue involving windows and unprintable characters. Chalk it up to another annoying Windows issue - #1460 

In the meantime, unix/mac should work.
