### ISSUE TITLE
Failure/crash at "copying unknown files" step

### ISSUE THREAD

**Issue by LFShark** [iBotPeaches/Apktool#1751]
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.1
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Other (built it myself)

### Stacktrace/Logcat
```
C:\DEVELOPMENT\Projects\<wokspace>\<project>\app>apktool.bat d myapp-release.apk --output decompiled
I: Using Apktool 2.3.1 on myapp-release.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Shark\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: Error copying file:       .xml.xml
        at brut.androlib.Androlib.decodeUnknownFiles(Androlib.java:224)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:172)
        at brut.apktool.Main.cmdDecode(Main.java:163)
        at brut.apktool.Main.main(Main.java:72)
Caused by: brut.directory.DirectoryException: Error copying file:        .xml.xml
        at brut.directory.DirUtil.copyToDir(DirUtil.java:88)
        at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:208)
        at brut.androlib.Androlib.decodeUnknownFiles(Androlib.java:217)
        ... 3 more
Caused by: java.io.FileNotFoundException: decompiled\unknown\    .xml (The filename, directory name, or volume label syntax is incorrect)ect)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at brut.directory.DirUtil.copyToDir(DirUtil.java:84)
        ... 5 more
```

### Steps to Reproduce
1. `apktool d myapp-release.apk --output decompiled`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
Unfortunatelly not.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? 
    Yes, fails without changing anything
2. If you are trying to install a modified apk, did you resign it? 
    That's not what I'm trying to do, I'm trying to verify that dexguard is actually doing it's job alright.
3. Are you using the latest apktool version? 
    Yes, provided that 2.3.1 is the latest (and it's the latest downloadable one)

Filing this to help out, am fine with it being ticked off as "could not repro" or ignored/backlogged.

**Comment by iBotPeaches** [comment]
Yep unfortunately its a known issue with Windows an unreadable characters. Filed as #1460, lots of duplicates for this so probably need to fixer sooner rather than later.
