### ISSUE TITLE
IndexOutOfBoundsException decodeString - StringBlock

### ISSUE THREAD

**Issue by hillz2** [iBotPeaches/Apktool#1754]
### Information
1. **Apktool Version 2.3.1**
2. **Operating System = Manjaro Linux**
3. **APK From Playstore**

### Logfile

```
[linux@x apk]$ apktool d myapp.apk 
I: Using Apktool 2.3.1 on myapp.apk 
I: Loading resource table...
Exception in thread "main" java.lang.IndexOutOfBoundsException
        at java.nio.ByteBuffer.wrap(ByteBuffer.java:375)
        at brut.androlib.res.decoder.StringBlock.decodeString(StringBlock.java:297)
        at brut.androlib.res.decoder.StringBlock.getString(StringBlock.java:110)
        at brut.androlib.res.decoder.StringBlock.getHTML(StringBlock.java:126)
        at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:341)
        at brut.androlib.res.decoder.ARSCDecoder.readEntryData(ARSCDecoder.java:257)
        at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:233)
        at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:156)
        at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:118)
        at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:80)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:599)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:73)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:65)
        at brut.androlib.Androlib.getResTable(Androlib.java:68)
        at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:228)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:118)
        at brut.apktool.Main.cmdDecode(Main.java:163)
        at brut.apktool.Main.main(Main.java:72)
```
Download the APK here: https://www.dropbox.com/s/fas9ni28tpt9gzx/myapp.apk?dl=0
How do I solve this ? I have tried other apks and they got extracted just fine, only this one that can't be extracted.

**Comment by iBotPeaches** [comment]
Confirmed.

**Comment by snotani** [comment]
I just encountered the same issue with [this](https://play.google.com/store/apps/details?id=com.bt.btsport) app using version 2.4.0.

```
Exception in thread "main" java.lang.IndexOutOfBoundsException
	at java.nio.ByteBuffer.wrap(ByteBuffer.java:375)
	at brut.androlib.res.decoder.StringBlock.decodeString(StringBlock.java:297)
	at brut.androlib.res.decoder.StringBlock.getString(StringBlock.java:110)
	at brut.androlib.res.decoder.AXmlResourceParser.getName(AXmlResourceParser.java:176)
	at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getName(XmlPullParserDelegate.java:57)
	at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:64)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:142)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:154)
	at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:161)
	at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:204)
	at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:136)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:122)
	at brut.apktool.Main.cmdDecode(Main.java:167)
	at brut.apktool.Main.main(Main.java:76)
```

**Comment by snotani** [comment]
Has there been any updates on this issue?

**Comment by ahmed-farhan** [comment]
Still waiting to see if there's been any resolutions to this issue...

**Comment by iBotPeaches** [comment]
Merging into https://github.com/iBotPeaches/Apktool/issues/2244
