### ISSUE TITLE
Lib not loading after recompile

### ISSUE THREAD

**Issue by zeroprobe** [iBotPeaches/Apktool#1775]
With SamsungCamera8 apk, if I simply recompile, the app crashes when loading an embedded library file. The location of which has not changed within the APK /lib.

A workaround has been pointed out to me. Copy the lib folder within the apk to /system/priv-app/SamsungCamera8/lib.

Rename /system/priv-app/SamsungCamera8/lib/arm64-v8a > arm64.

This works for apktool v2.3.1 and below. If I use the v2.3.2 and above I get a separate crash when taking a photo. What was compiled with v2.3.2 and above, if I copy the classes.dex to an original apk package the camera works. So it has to be resource related as the error below suggests.

Lib folder error

`--------- beginning of crash
04-19 09:01:15.631 16869-16897/? E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
Process: com.sec.android.app.camera, PID: 16869
java.lang.UnsatisfiedLinkError: dlopen failed: library "/system/priv-app/SamsungCamera8/SamsungCamera8.apk!/lib/arm64-v8a/libnode-jni.so" not found
at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
at java.lang.System.loadLibrary(System.java:1657)
at com.samsung.android.camera.core2.node.NativeNode.loadLibrary(Unknown Source:39)
at com.samsung.android.camera.core2.node.NativeNode.(Unknown Source:13)
at com.samsung.android.camera.core2.node.NativeNode.loadLibrary(Unknown Source:0)
at com.samsung.android.camera.core2.maker.MakerBase.(Unknown Source:0)
at java.lang.reflect.Constructor.newInstance0(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
at com.samsung.android.camera.core2.MakerFactory.create(Unknown Source:15)
at com.sec.android.app.camera.engine.request.InitializeMakerRequest.execute(Unknown Source:57)
at com.sec.android.app.camera.engine.request.Request.run(Unknown Source:39)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)`

Resources Error - apktool v2.3.2 and above
```
    --------- beginning of crash
05-17 08:15:15.030 18890-18925/? E/AndroidRuntime: FATAL EXCEPTION: pool-4-thread-1
    Process: com.sec.android.app.camera, PID: 18890
    android.content.res.Resources$NotFoundException: File res/raw/shutter.ogg from drawable resource ID #0x7f080008
        at android.content.res.ResourcesImpl.openRawResourceFd(ResourcesImpl.java:308)
        at android.content.res.Resources.openRawResourceFd(Resources.java:1307)
        at android.media.SoundPool.load(SoundPool.java:224)
        at com.sec.android.app.camera.SoundManager$LoadSoundRunnable.run(Unknown Source:52)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed
        at android.content.res.AssetManager.openNonAssetFdNative(Native Method)
        at android.content.res.AssetManager.openNonAssetFd(AssetManager.java:501)
        at android.content.res.ResourcesImpl.openRawResourceFd(ResourcesImpl.java:306)
        at android.content.res.Resources.openRawResourceFd(Resources.java:1307) 
        at android.media.SoundPool.load(SoundPool.java:224) 
        at com.sec.android.app.camera.SoundManager$LoadSoundRunnable.run(Unknown Source:52) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
05-17 08:15:15.042 4435-19461/? W/ExynosCameraParameters: [CAM_ID(0)][Back]-WARN(m_getReprocessing3aaIspOtf[3878]):Processed bayer must using 3AA-ISP M2M. but, Current mode(1)
05-17 08:15:15.042 4435-19461/? W/ExynosCameraParameters: [CAM_ID(0)][Back]-WARN(m_getReprocessing3aaIspOtf[3878]):Processed bayer must using 3AA-ISP M2M. but, Current mode(1)
05-17 08:15:15.048 4435-19464/? E/TUNING_BIN: load:180 [BIN_TEST] Load fname : /data/camera/libhifills_LSIFr_sak2l3.dat, lname : libhifills_sak2l3.so
    load:185 [BIN_TEST] No TUNING Binary Provided; Use default TUNING Header Files
05-17 08:15:15.074 4435-19474/? W/ExynosCameraParameters: [CAM_ID(0)][Back]-WARN(m_getReprocessing3aaIspOtf[3878]):Processed bayer must using 3AA-ISP M2M. but, Current mode(1)
05-17 08:15:15.086 4497-4987/? W/Camera3-OutputStream: A frame is dropped for stream 0
```

### Information
1. Apltool 2.3.2
2. Windows
3. Samsung Store

    --------- beginning of crash
04-19 09:01:15.631 16869-16897/? E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
    Process: com.sec.android.app.camera, PID: 16869
    java.lang.UnsatisfiedLinkError: dlopen failed: library "/system/priv-app/SamsungCamera8/SamsungCamera8.apk!/lib/arm64-v8a/libnode-jni.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1657)
        at com.samsung.android.camera.core2.node.NativeNode.loadLibrary(Unknown Source:39)
        at com.samsung.android.camera.core2.node.NativeNode.<clinit>(Unknown Source:13)
        at com.samsung.android.camera.core2.node.NativeNode.loadLibrary(Unknown Source:0)
        at com.samsung.android.camera.core2.maker.MakerBase.<clinit>(Unknown Source:0)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at com.samsung.android.camera.core2.MakerFactory.create(Unknown Source:15)
        at com.sec.android.app.camera.engine.request.InitializeMakerRequest.execute(Unknown Source:57)
        at com.sec.android.app.camera.engine.request.Request.run(Unknown Source:39)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

### Steps to Reproduce
Download SamsungCamera8.apk - Tested on v8.0.90 & 8.0.92

### Frameworks
/system/framework/framework-res.apk
https://drive.google.com/open?id=1hQhdFC-cz4WLoYP-6zmcLKlUDyzX0Sri

### APK
https://drive.google.com/open?id=1iDuYkmehV9b4Bs3Wet2TfPfiTddzgtiQ

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? - Yes
2. If you are trying to install a modified apk, did you resign it? - Tried with and without, system APK
3. Are you using the latest apktool version? - Yes

**Comment by edzamber** [comment]
Its not apktool issue.

Extract lib Folder from original apk then rename arm64-v8a into arm64 then push lib Folder into app/SamsungCamera8 Folder. Change perms for Folders lib and arm64 to 0755 and all libs.so files to 0644.
Reboot and it should working.

**Comment by zeroprobe** [comment]
Thank you this works. How very weird. Does the compilation break the reference in some way?

**Comment by edzamber** [comment]
I don't know. This is same with some others apks as far you put its into app Folder as SBrlwser or YouTube.

**Comment by iBotPeaches** [comment]
I'm confused on this. Renaming directories? Did apktool decode the lib into an invalid location that required fixing?

**Comment by zeroprobe** [comment]
The resources apktool v2.3.2 error seems to be somewhere between.

3c84590a1ab55b7b338989e3058230f83289fa37 - Feb 28 - Works

a84e3c56fdfccb1136ba6069357789baef7145c7 - Apr 5 - Not working

**Comment by zeroprobe** [comment]
Do you still need anything else from me for this, just says waiting for issuer?

**Comment by iBotPeaches** [comment]
I removed the tag. I haven't had time to dig into it, but looking at the difference of your investigation: https://github.com/iBotPeaches/Apktool/compare/3c84590a1ab55b7b338989e3058230f83289fa37...a84e3c56fdfccb1136ba6069357789baef7145c7

Is really all the aapt2 changes.

**Comment by iBotPeaches** [comment]
Sorry, I don't have Samsung and don't see myself after 2-3 years of being able to do anything here. You are welcome to push forward a pull request if you track this down. So many changes between 2.3.2 and v2.5.0 - nothing I can do.

**Comment by dtrunk90** [comment]
I'm facing the same issue with Sony Camera: https://www.apkmirror.com/apk/sony-mobile-communications/sony-camera/sony-camera-2-6-1-a-0-16-release/sony-camera-2-6-1-a-0-16-android-apk-download/

Using the workaround mentioned above fixes the issue somehow. I still don't know the reason. Maybe this should be reopened.
This is my current code: https://gitlab.com/xperiance/camera/

**Comment by SameerAlSahab** [comment]
The bug still resides in the latest version 2.12.0 if iam not wrong . But yeah this workaround works on Android 16 system apps.
