### ISSUE TITLE
Assets can't roundtrip properly with v2.3.2 (works in 2.3.1) java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed

### ISSUE THREAD

**Issue by minsko** [iBotPeaches/Apktool#1779]
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.2
2. **Operating System (Mac, Linux, Windows)** - Mac
3. **APK From? (Playstore, ROM, Other)** - Other, a sample on Github: <https://github.com/minsko/netsi>

### Stacktrace/Logcat

```
04-26 11:06:45.960 14206 14206 W System.err: java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed
04-26 11:06:45.960 14206 14206 W System.err: 	at android.content.res.AssetManager.openAssetFd(Native Method)
04-26 11:06:45.960 14206 14206 W System.err: 	at android.content.res.AssetManager.openFd(AssetManager.java:352)
04-26 11:06:45.960 14206 14206 W System.err: 	at com.mattinsko.netsi.MainActivity.onCreate(MainActivity.java:27)

```

### Steps to Reproduce
1. `apktool decode`
2. `apktool build`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)
no

### APK
If this APK can be freely shared, please upload/attach a link to it.
The sample can be built from <https://github.com/minsko/netsi>.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? Not modifed, but yes signed.
3. Are you using the latest apktool version? Yes.  It works in the previous 2.3.1 version.

**Comment by iBotPeaches** [comment]
Duplicate of regression - https://github.com/iBotPeaches/Apktool/issues/1769, will have binaries up later today. Hotfix (2.3.3)

**Comment by minsko** [comment]
Sorry for the duplication.  I should have searched more diligently through the issues.
