### ISSUE TITLE
Unable to extract an APK with multiple resource mcc-mnc values

### ISSUE THREAD

**Issue by robertgmelo** [iBotPeaches/Apktool#1798]
### Information
1. **Apktool Version (`apktool -version`)** - latest version (2.3.3)
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - ROM

### Stacktrace/Logcat

```
I: Using Apktool 2.3.3 on TeleService.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Multiple resources: spec=0x7f07005c array/enabled_networks_values, config=-mcc310-mnc00
        at brut.androlib.res.data.ResType.addResource(ResType.java:66)
        at brut.androlib.res.data.ResType.addResource(ResType.java:55)
        at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:315)
        at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:260)
        at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:175)
        at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:131)
        at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:82)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:48)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:741)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:67)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:59)
        at brut.androlib.Androlib.getResTable(Androlib.java:68)
        at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:228)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:118)
        at brut.apktool.Main.cmdDecode(Main.java:164)
        at brut.apktool.Main.main(Main.java:73)
```

### Steps to Reproduce
1. Run command "apktool d TeleService.apk"

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)
/system/priv-app/TeleService/TeleService.apk
### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by iBotPeaches** [comment]
There is probably a qualifier issue here. So it decodes without that special qualifier and then duplicate happens on the mnc/mcc qualifier. I'll need apk to investigate anywhere further on this one.

**Comment by iBotPeaches** [comment]
A month or more has passed here. Due to the ticket involving qualifiers. There is nothing I can do here without an application binary. Closing due to no response.
