### ISSUE TITLE
java.lang.RuntimeException: java.lang.ClassNotFoundException error

### ISSUE THREAD

**Issue by hanyelmehy** [iBotPeaches/Apktool#1803]
### Information
1. **Apktool Version (`apktool -version`)** -2.3.3
2. **Operating System (Mac, Linux, Windows)** -Windows 7
3. **APK From? (Playstore, ROM, Other)** - other

when i recompile to apk i get this error (it was work without problem when update to android 27 error shown)
```
java.lang.RuntimeException: java.lang.ClassNotFoundException: com.myapp.web2android.mainscreen
	at anywheresoftware.b4a.keywords.LayoutBuilder.loadLayout(LayoutBuilder.java:170)
	at anywheresoftware.b4a.objects.ActivityWrapper.LoadLayout(ActivityWrapper.java:209)
	at com.appsmaker.tool.mainscreen._activity_create(mainscreen.java:426)
	at java.lang.reflect.Method.invoke(Native Method)
	at anywheresoftware.b4a.BA.raiseEvent2(BA.java:186)
	at com.appsmaker.tool.mainscreen.afterFirstLayout(mainscreen.java:104)
	at com.appsmaker.tool.mainscreen.access$000(mainscreen.java:17)
	at com.appsmaker.tool.mainscreen$WaitForLayout.run(mainscreen.java:82)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5551)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
Caused by: java.lang.ClassNotFoundException: com.myapp.web2android.mainscreen
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:324)
	at java.lang.Class.forName(Class.java:285)
	at anywheresoftware.b4a.keywords.LayoutBuilder.loadLayoutHelper(LayoutBuilder.java:368)
	at anywheresoftware.b4a.keywords.LayoutBuilder.loadLayoutHelper(LayoutBuilder.java:454)
	at anywheresoftware.b4a.keywords.LayoutBuilder.loadLayout(LayoutBuilder.java:148)
	... 14 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.myapp.web2android.mainscreen" on path: DexPathList[[zip file "/data/app/com.appsmaker.tool-2/base.apk"],nativeLibraryDirectories=[/data/app/com.appsmaker.tool-2/lib/arm, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	... 20 more
	Suppressed: java.lang.ClassNotFoundException: com.myapp.web2android.mainscreen
		at java.lang.Class.classForName(Native Method)
		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 21 more
	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`) no

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?yes
2. If you are trying to install a modified apk, did you resign it?yes
3. Are you using the latest apktool version?yes

**Comment by MaskedMan2020** [comment]
I have the same problem，Please download APK to try. 
Link:https://play.google.com/store/apps/details?id=com.netflix.ninja

apk apktool -r -s d netflix.apk
apk apktool b netflix
apk jarsigner -keystore ~/Desktop/hook/keystore/test.keystore netflix/dist/netflix.apk test 
zipalign -p 4 netflix_h2_0/dist/netflix.apk ok.apk
adb install -r ok.apk

**Comment by MaskedMan2020** [comment]
> So a simple test application decoded and built on API 27 no longer works? Could you attach this sample application?

Hi, I have the same problem，Please download APK to try.
Link:https://play.google.com/store/apps/details?id=com.netflix.ninja

apk apktool -r -s d netflix.apk
apk apktool b netflix
apk jarsigner -keystore ~/Desktop/hook/keystore/test.keystore netflix/dist/netflix.apk test
zipalign -p 4 netflix_h2_0/dist/netflix.apk ok.apk
adb install -r ok.apk

**Comment by iBotPeaches** [comment]
> > So a simple test application decoded and built on API 27 no longer works? Could you attach this sample application?
> 
> Hi, I have the same problem，Please download APK to try.
> Link:https://play.google.com/store/apps/details?id=com.netflix.ninja
> 
> apk apktool -r -s d netflix.apk
> apk apktool b netflix
> apk jarsigner -keystore ~/Desktop/hook/keystore/test.keystore netflix/dist/netflix.apk test
> zipalign -p 4 netflix_h2_0/dist/netflix.apk ok.apk
> adb install -r ok.apk

That is not a simple application. Debugging large corporation applications like Netflix is too much, this original ticket never got a reply in over a year and your response is unrelated.

So closing this.
