### ISSUE TITLE
app instantly crashes after repackaging

### ISSUE THREAD

**Issue by ThePinkPanther** [iBotPeaches/Apktool#1806]
### Information
1. **Apktool Version (`apktool -version`)** - v2.3.3
2. **Operating System (Mac, Linux, Windows)** - Linux Ubuntu 17.10
3. **APK From? (Playstore, ROM, Other)** - Apkpure ( https://apkpure.com/perfect-piano/com.gamestar.perfectpiano/download/2100713-APK?from=details%2Fversion )

### Stacktrace/Logcat

```05-30 19:59:00.092 1254-1338/? D/hwcomposer: hw_composer sent 98 syncs in 60s
05-30 19:59:12.447 1691-2969/? I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.gamestar.perfectpiano/.Splash (has extras)} from uid 10009 on display 0
05-30 19:59:12.476 1691-1707/? W/BroadcastQueue: Permission Denial: broadcasting Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } from com.android.launcher3 (pid=2002, uid=10009) requires com.google.android.launcher.permission.RECEIVE_LAUNCH_BROADCASTS due to receiver com.google.android.gms/.icing.proxy.ApplicationLauncherReceiver
05-30 19:59:12.476 1691-1707/? W/BroadcastQueue: Permission Denial: receiving Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$GmsExternalReceiver requires com.android.launcher3.permission.RECEIVE_LAUNCH_BROADCASTS due to sender com.android.launcher3 (uid 10009)
05-30 19:59:12.476 1691-1707/? W/BroadcastQueue: Permission Denial: broadcasting Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } from com.android.launcher3 (pid=2002, uid=10009) requires com.google.android.launcher.permission.RECEIVE_LAUNCH_BROADCASTS due to receiver com.google.android.googlequicksearchbox/com.google.android.search.core.icingsync.ApplicationLaunchReceiver
05-30 19:59:12.578 1367-1660/? D/AudioFlinger: mixer(0xb4340000) throttle end: throttle time(11)
05-30 19:59:12.592 1691-1824/? I/ActivityManager: Start proc 7265:com.gamestar.perfectpiano/u0a93 for activity com.gamestar.perfectpiano/.Splash
05-30 19:59:12.720 1367-1659/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 7973938 , only wrote 7972982
05-30 19:59:12.720 1367-1659/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 7973013 , only wrote 7972982
05-30 19:59:12.736 2002-2235/? E/Surface: getSlotFromBufferLocked: unknown buffer: 0x97e3bb30
05-30 19:59:12.805 7265-7265/? D/FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
05-30 19:59:12.808 7265-7265/? D/FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
05-30 19:59:12.813 7265-7265/? I/FirebaseInitProvider: FirebaseApp initialization successful
05-30 19:59:12.825 1367-1659/? W/audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 661 frames
05-30 19:59:12.829 7265-7280/? I/FA: App measurement is starting up, version: 11910
05-30 19:59:12.829 7265-7280/? I/FA: To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
05-30 19:59:12.829 7265-7280/? I/FA: To enable faster debug mode event logging run:
                                       adb shell setprop debug.firebase.analytics.app com.gamestar.perfectpiano
05-30 19:59:12.940 1367-1659/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 7982672 , only wrote 7981575
05-30 19:59:12.940 1367-1659/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 7981580 , only wrote 7981575
05-30 19:59:13.030 1367-1659/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 7985539 , only wrote 7984880
05-30 19:59:13.030 1367-1659/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 7984885 , only wrote 7984880
05-30 19:59:13.120 1367-1659/? W/audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 661 frames
05-30 19:59:13.240 1367-1659/? W/audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 661 frames
05-30 19:59:13.309 7265-7265/? W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
05-30 19:59:13.333 1367-1659/? W/audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 661 frames
05-30 19:59:13.352 1367-1659/? W/audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 661 frames
05-30 19:59:13.360 1367-1659/? W/audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 661 frames
05-30 19:59:13.409 1367-1659/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 8001586 , only wrote 8001405
05-30 19:59:13.409 1367-1659/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 8001410 , only wrote 8001405
05-30 19:59:13.419 1691-2015/? I/MediaFocusControl:  AudioFocus  requestAudioFocus() from android.media.AudioManager@db502af req=1flags=0x0
05-30 19:59:13.419 7265-7265/? E/InstrumentSoundManager: Gain Audio Focus
05-30 19:59:13.419 7265-7280/? I/FA: Tag Manager is not found and thus will not be used
05-30 19:59:13.421 7265-7265/? I/art: System.exit called, status: 0
05-30 19:59:13.421 7265-7265/? I/AndroidRuntime: VM exiting with result code 0, cleanup skipped.
05-30 19:59:13.495 1691-1702/? W/MediaFocusControl:   AudioFocus   audio focus client died
05-30 19:59:13.495 1691-1702/? I/MediaFocusControl: AudioFocus  removeFocusStackEntry(): removing entry for android.os.BinderProxy@8b9887e
05-30 19:59:13.495 1691-2969/? I/ActivityManager: Process com.gamestar.perfectpiano (pid 7265) has died
05-30 19:59:13.503 1370-7269/? I/art: Starting a blocking GC HeapTrim
05-30 19:59:13.512 1691-2969/? I/ActivityManager: Start proc 7303:com.gamestar.perfectpiano/u0a93 for activity com.gamestar.perfectpiano/.Splash
05-30 19:59:13.533 7303-7303/? D/FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
05-30 19:59:13.535 7303-7303/? D/FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
05-30 19:59:13.540 7303-7303/? I/FirebaseInitProvider: FirebaseApp initialization successful
05-30 19:59:13.544 7303-7318/? I/FA: App measurement is starting up, version: 11910
05-30 19:59:13.544 7303-7318/? I/FA: To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
05-30 19:59:13.544 7303-7318/? I/FA: To enable faster debug mode event logging run:
                                       adb shell setprop debug.firebase.analytics.app com.gamestar.perfectpiano
05-30 19:59:13.560 7303-7303/? W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
05-30 19:59:13.577 1691-2963/? I/MediaFocusControl:  AudioFocus  requestAudioFocus() from android.media.AudioManager@bd5ca5c req=1flags=0x0
05-30 19:59:13.578 7303-7303/? E/InstrumentSoundManager: Gain Audio Focus
05-30 19:59:13.578 7303-7318/? I/FA: Tag Manager is not found and thus will not be used
05-30 19:59:13.579 7303-7303/? I/art: System.exit called, status: 0
05-30 19:59:13.579 7303-7303/? I/AndroidRuntime: VM exiting with result code 0, cleanup skipped.
05-30 19:59:13.615 1691-1703/? W/MediaFocusControl:   AudioFocus   audio focus client died
05-30 19:59:13.615 1691-1703/? I/MediaFocusControl: AudioFocus  removeFocusStackEntry(): removing entry for android.os.BinderProxy@fe184e2
05-30 19:59:13.616 1691-1702/? I/ActivityManager: Process com.gamestar.perfectpiano (pid 7303) has died
05-30 19:59:13.658 1691-1702/? I/ActivityManager: Start proc 7341:com.gamestar.perfectpiano/u0a93 for activity com.gamestar.perfectpiano/.Splash
05-30 19:59:13.687 7341-7341/? D/FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
05-30 19:59:13.689 7341-7341/? D/FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
05-30 19:59:13.696 7341-7341/? I/FirebaseInitProvider: FirebaseApp initialization successful
05-30 19:59:13.701 7341-7356/? I/FA: App measurement is starting up, version: 11910
05-30 19:59:13.701 7341-7356/? I/FA: To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
05-30 19:59:13.701 7341-7356/? I/FA: To enable faster debug mode event logging run:
                                       adb shell setprop debug.firebase.analytics.app com.gamestar.perfectpiano
05-30 19:59:13.719 7341-7341/? W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
05-30 19:59:13.735 1691-2168/? I/MediaFocusControl:  AudioFocus  requestAudioFocus() from android.media.AudioManager@bd5ca5c req=1flags=0x0
05-30 19:59:13.735 7341-7341/? E/InstrumentSoundManager: Gain Audio Focus
05-30 19:59:13.735 7341-7356/? I/FA: Tag Manager is not found and thus will not be used
05-30 19:59:13.737 7341-7341/? I/art: System.exit called, status: 0
05-30 19:59:13.737 7341-7341/? I/AndroidRuntime: VM exiting with result code 0, cleanup skipped.
05-30 19:59:13.774 1691-2221/? W/MediaFocusControl:   AudioFocus   audio focus client died
05-30 19:59:13.774 1691-2221/? I/MediaFocusControl: AudioFocus  removeFocusStackEntry(): removing entry for android.os.BinderProxy@5c79406
05-30 19:59:13.774 1691-2970/? I/ActivityManager: Process com.gamestar.perfectpiano (pid 7341) has died
05-30 19:59:13.777 1691-2970/? W/ActivityManager: Force removing ActivityRecord{5dca0cd u0 com.gamestar.perfectpiano/.Splash t177}: app died, no saved state
05-30 19:59:13.781 1691-1714/? W/WindowManager: Failed looking up window
                                                java.lang.IllegalArgumentException: Requested window android.view.ViewRootImpl$W@29a1c85 does not exist
                                                    at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8733)
                                                    at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8724)
                                                    at com.android.server.wm.WindowManagerService.removeWindow(WindowManagerService.java:2697)
                                                    at com.android.server.wm.Session.remove(Session.java:187)
                                                    at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3099)
                                                    at android.view.ViewRootImpl.doDie(ViewRootImpl.java:5606)
                                                    at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3409)
                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                    at android.os.Looper.loop(Looper.java:148)
                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
                                                    at com.android.server.ServiceThread.run(ServiceThread.java:46)
05-30 19:59:13.860 1367-1659/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 8021276 , only wrote 8021235
05-30 19:59:13.947 1367-1659/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 8025098 , only wrote 8024540
05-30 19:59:13.947 1367-1659/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 8024544 , only wrote 8024540
05-30 19:59:14.032 1367-1659/? W/audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 661 frames
05-30 19:59:14.041 1367-1659/? W/audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 661 frames
05-30 19:59:14.090 1367-1659/? W/audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 661 frames
05-30 19:59:14.090 1367-1659/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 8030828 , only wrote 8030489
05-30 19:59:14.090 1367-1659/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 8030492 , only wrote 8030489
05-30 19:59:14.144 1367-1659/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 8032828 , only wrote 8031150
05-30 19:59:14.144 1367-1659/? W/audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 661 frames
05-30 19:59:14.179 1367-1659/? W/audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 661 frames
05-30 19:59:14.191 1367-1659/? W/audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 661 frames
05-30 19:59:14.207 1367-1659/? W/audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 661 frames
05-30 19:59:14.243 1367-1659/? W/audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 661 frames
05-30 19:59:14.283 1367-1659/? W/audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 661 frames
05-30 19:59:14.295 1367-1659/? W/audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 661 frames
05-30 19:59:14.337 1367-1659/? W/audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 661 frames
05-30 19:59:14.359 1367-1659/? W/audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 661 frames
05-30 19:59:14.382 1367-1659/? W/audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 661 frames
05-30 19:59:14.397 1367-1659/? W/audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 661 frames
05-30 19:59:14.427 1367-1659/? W/audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 661 frames
05-30 19:59:14.437 1691-2963/? W/InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@98f68f4 attribute=null, token = android.os.BinderProxy@e682a36
05-30 19:59:14.437 2002-2002/? I/Choreographer: Skipped 33 frames!  The application may be doing too much work on its main thread.
05-30 19:59:14.442 1367-1659/? W/audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 661 frames
05-30 19:59:14.487 1367-1659/? W/audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 661 frames
05-30 19:59:14.577 1367-1659/? W/audio_hw_generic: Hardware backing HAL too slow, could only write 0 of 661 frames
05-30 19:59:14.749 1367-1659/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 8057875 , only wrote 8056929
05-30 19:59:14.749 1367-1659/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 8056935 , only wrote 8056929
05-30 19:59:15.619 1367-1660/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 8132314 , only wrote 8095267
```

### Steps to Reproduce
1. I use apktool as a library in java application. The equivalent command lines are:
```
apktool d -f --no-src Perfect_Piano_v7.1.3_apkpure.com.apk
rm Perfect_Piano_v7.1.3_apkpure.com.apk
apktool b -f Perfect_Piano_v7.1.3_apkpure.com
jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore my-release-key.keystore Perfect_Piano_v7.1.3_apkpure.com.apk alias_name
```

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://apkpure.com/perfect-piano/com.gamestar.perfectpiano/download/2100713-APK?from=details%2Fversion

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?  -
   Yes
2. If you are trying to install a modified apk, did you resign it?
   Yes
3. Are you using the latest apktool version?
   Yes

Please have a look at this quesion at SO: https://stackoverflow.com/questions/50610196/apktool-app-instantly-crashes-after-repackaging

**Comment by iBotPeaches** [comment]
```
05-30 19:59:13.421 7265-7265/? I/art: System.exit called, status: 0
```

For some reason the application is exiting itself. I think this is some tamper protection in the application. Which is being tripped and thus exiting immediately.  Doesn't unforunately look like anything that Apktool caused. Just the nature and danger of reverse engineering and rebuilding applications.
