### ISSUE TITLE
No resource found that matches the given name '@android:style/Animation.OptionsPanel'.

### ISSUE THREAD

**Issue by changcsw** [iBotPeaches/Apktool#1807]
```java 
Using Apktool 2.3.3
I: Copying /home/lakeba13/workspace/LakebaSecurityFrameworkMobile/SecureApk/debug/app-demo-release classes.dex file...
I: Building resources...
W: /home/lakeba13/workspace/LakebaSecurityFrameworkMobile/SecureApk/debug/app-demo-release/res/values-v24/styles.xml:7: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Animation.OptionsPanel'.
W: 
W: /home/lakeba13/workspace/LakebaSecurityFrameworkMobile/SecureApk/debug/app-demo-release/res/values-v24/styles.xml:8: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Animation.LockScreen'.
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_1478810839657812213.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 22, --version-code, 6, --version-name, 1.0.5-debug, -F, /tmp/APKTOOL7363633357993529625.tmp, -0, arsc, -0, woff2, -0, assets/io/michaelrocks/libphonenumber/android/data/PhoneNumberAlternateFormatsProto_66, -0, arsc, -I, /home/lakeba13/workspace/LakebaSecurityFrameworkMobile/SecureApk/debug/apktool/framework/1.apk, -S, /home/lakeba13/workspace/LakebaSecurityFrameworkMobile/SecureApk/debug/app-demo-release/res, -M, /home/lakeba13/workspace/LakebaSecurityFrameworkMobile/SecureApk/debug/app-demo-release/AndroidManifest.xml]
    at brut.androlib.Androlib.buildResourcesFull(Androlib.java:437)
    at brut.androlib.Androlib.buildResources(Androlib.java:371)
    at brut.androlib.Androlib.build(Androlib.java:281)
    at brut.androlib.Androlib.build(Androlib.java:254)
    at brut.apktool.Main.cmdBuild(Main.java:224)
    at brut.apktool.Main.main(Main.java:84)
```

#### I find values-v24/values-v24.xml from project, The content:
```java
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="Base.TextAppearance.AppCompat.Widget.Button.Borderless.Colored" parent="android:TextAppearance.Material.Widget.Button.Borderless.Colored"/>
    <style name="Base.TextAppearance.AppCompat.Widget.Button.Colored" parent="android:TextAppearance.Material.Widget.Button.Colored"/>
    <style name="TextAppearance.AppCompat.Notification.Info.Media"/>
    <style name="TextAppearance.AppCompat.Notification.Media"/>
    <style name="TextAppearance.AppCompat.Notification.Time.Media"/>
    <style name="TextAppearance.AppCompat.Notification.Title.Media"/>
</resources>
```
#### but decode xxx.apk generate xxx directory use apktool, find xxx/res/values-v24/values-v24.xml from xxx directory, The content:
``` java
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="TextAppearance.Compat.Notification.Info.Media" parent="@style/TextAppearance.Compat.Notification.Info" />
    <style name="TextAppearance.Compat.Notification.Media" parent="@style/TextAppearance.Compat.Notification" />
    <style name="TextAppearance.Compat.Notification.Time.Media" parent="@style/TextAppearance.Compat.Notification.Time" />
    <style name="TextAppearance.Compat.Notification.Title.Media" parent="@style/TextAppearance.Compat.Notification.Title" />
    <style name="TextAppearance.AppCompat.Notification.Info.Media" parent="@style/TextAppearance.AppCompat.Notification.Info" />
    <style name="TextAppearance.AppCompat.Notification.Media" parent="@style/TextAppearance.AppCompat.Notification" />
    <style name="TextAppearance.AppCompat.Notification.Time.Media" parent="@style/TextAppearance.AppCompat.Notification.Time" />
    <style name="TextAppearance.AppCompat.Notification.Title.Media" parent="@style/TextAppearance.AppCompat.Notification.Title" />
    <style name="Base.TextAppearance.AppCompat.Widget.Button.Borderless.Colored" parent="@android:style/Animation.OptionsPanel" />
    <style name="Base.TextAppearance.AppCompat.Widget.Button.Colored" parent="@android:style/Animation.LockScreen" />
</resources>
```

#### I don't know why
``` java
    <style name="Base.TextAppearance.AppCompat.Widget.Button.Borderless.Colored" parent="android:TextAppearance.Material.Widget.Button.Borderless.Colored"/>
    <style name="Base.TextAppearance.AppCompat.Widget.Button.Colored" parent="android:TextAppearance.Material.Widget.Button.Colored"/>
```
### change 
```java
    <style name="Base.TextAppearance.AppCompat.Widget.Button.Borderless.Colored" parent="@android:style/Animation.OptionsPanel" />
    <style name="Base.TextAppearance.AppCompat.Widget.Button.Colored" parent="@android:style/Animation.LockScreen" />
```

**Comment by iBotPeaches** [comment]
I do not know.

The parent reference seems to be changing, perhaps decoding in an invalid way. I would need to create a failing test to investigate this further as it seems to be a pretty specific failure.

**Comment by anagaf-tapcore** [comment]
Seems I've met the same problem. @changcsw have you found any workaround?

**Comment by assegaf** [comment]
@iBotPeaches is there any manual way fix this, like editting it manually its xml ? 
is this new method encrypted res /jpg /png etc 
 ?

**Comment by changcsw** [comment]
> Seems I've met the same problem. @changcsw have you found any workaround?



> Seems I've met the same problem. @changcsw have you found any workaround?

Delete xxx/res/values-v24/ directory  and recompile

**Comment by changcsw** [comment]
> Seems I've met the same problem. @changcsw have you found any workaround?

Delete xxx/res/values-v24/ directory and recompile.

**Comment by iBotPeaches** [comment]
Sorry, a few year old ticket here. No application to triage and memory bad.

Just going to close this.
