### ISSUE TITLE
Exception in thread "main" brut.androlib.AndrolibException: Multiple resources: spec=0x01040244 string/enablePin, config=[DEFAULT]

### ISSUE THREAD

**Issue by NeonDragon1909** [iBotPeaches/Apktool#1818]
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.3
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - ROM

### Stacktrace/Logcat

```
I: Using Apktool 2.3.3 on framework-res.apk
I: Loading resource table...
W: Config flags size > 56. Size = 60. Exceeding bytes: 0x24000000.
W: Invalid config flags detected. Dropping resources: string-ERR0
W: Config flags size > 56. Size = 60. Exceeding bytes: 0x9C000000.
W: Invalid config flags detected. Dropping resources: string-ERR1
W: Config flags size > 56. Size = 60. Exceeding bytes: 0x2A020000.
W: Invalid config flags detected. Dropping resources: string-ERR2
W: Config flags size > 56. Size = 60. Exceeding bytes: 0xD4020000.
W: Invalid config flags detected. Dropping resources: string-ERR3
W: Config flags size > 56. Size = 60. Exceeding bytes: 0x9C000000.
W: Invalid config flags detected. Dropping resources: string-ERR4
W: Config flags size > 56. Size = 60. Exceeding bytes: 0xE7030000.
W: Invalid config flags detected. Dropping resources: string-ERR5
W: Config flags size > 56. Size = 60. Exceeding bytes: 0x88010000.
W: Invalid config flags detected. Dropping resources: string-ERR6
W: Config flags size > 56. Size = 60. Exceeding bytes: 0xE7030000.
W: Invalid config flags detected. Dropping resources: string-ERR7
W: Config flags size > 56. Size = 60. Exceeding bytes: 0xDE000000.
W: Invalid config flags detected. Dropping resources: string-ERR8
W: Config flags size > 56. Size = 60. Exceeding bytes: 0x40010000.
W: Invalid config flags detected. Dropping resources: string-ERR9
W: Config flags size > 56. Size = 60. Exceeding bytes: 0x54010000.
W: Invalid config flags detected. Dropping resources: string-ERR10
W: Config flags size > 56. Size = 60. Exceeding bytes: 0x58020000.
W: Invalid config flags detected. Dropping resources: string-ERR11
W: Config flags size > 56. Size = 60. Exceeding bytes: 0xE4010000.
W: Invalid config flags detected. Dropping resources: string-ERR12
W: Config flags size > 56. Size = 60. Exceeding bytes: 0x4F000000.
W: Invalid config flags detected. Dropping resources: string-ERR13
W: Config flags size > 56. Size = 60. Exceeding bytes: 0x48030000.
W: Invalid config flags detected. Dropping resources: string-ERR14
W: Config flags size > 56. Size = 60. Exceeding bytes: 0x9C000000.
W: Invalid config flags detected. Dropping resources: string-ERR15
W: Config flags size > 56. Size = 60. Exceeding bytes: 0x58020000.
W: Invalid config flags detected. Dropping resources: string-ERR16
W: Config flags size > 56. Size = 60. Exceeding bytes: 0x48030000.
W: Invalid config flags detected. Dropping resources: string-ERR17
Exception in thread "main" brut.androlib.AndrolibException: Multiple resources: spec=0x01040244 string/enablePin, config=[DEFAULT]
	at brut.androlib.res.data.ResType.addResource(ResType.java:66)
	at brut.androlib.res.data.ResType.addResource(ResType.java:55)
	at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:315)
	at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:260)
	at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:175)
	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:131)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:82)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:48)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:741)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:67)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:59)
	at brut.androlib.Androlib.getResTable(Androlib.java:68)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:228)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:118)
	at brut.apktool.Main.cmdDecode(Main.java:164)
	at brut.apktool.Main.main(Main.java:73)

```

### Steps to Reproduce
1. `apktool d framework-res.apk`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

[framework-res.apk.zip](https://github.com/iBotPeaches/Apktool/files/2096315/framework-res.apk.zip)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
Yes
2. If you are trying to install a modified apk, did you resign it?
N/A
3. Are you using the latest apktool version?
Yes

**Comment by iBotPeaches** [comment]
This is unfortunately an Huawei apk, which is not supported as of now due to qualifier changes. - #1521
