### ISSUE TITLE
Apktool build from a `apktool d -s` output folder failed

### ISSUE THREAD

**Issue by wishma2013** [iBotPeaches/Apktool#1822]
### Information
1. **Apktool Version (`v2.0.3 `)** -
2. **Operating System (Mac)** -
3. **APK From? (build from Android studio)** -

### Stacktrace

```
res/drawable/$ic_launcher_foreground__0.xml: Invalid file name: must contain only [a-zA-Z0-9_.]
A/        ( 5614): First type is not attr!
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/var/folders/1x/rbs7f_y145qf3f9dbbzktwlw0000gn/T/brut_util_Jar_6655770474063448832.tmp, p, --forced-package-id, 127, --min-sdk-version, 27, --target-sdk-version, 27, --version-code, 1, --version-name, 1.0, -F, /var/folders/1x/rbs7f_y145qf3f9dbbzktwlw0000gn/T/APKTOOL2428216456422291333.tmp, -0, arsc, -0, version, -0, arsc, -I, /Users/eilir/Library/apktool/framework/1.apk, -S, /Users/eilir/work6/安卓/new3/res, -M, /Users/eilir/work6/安卓/new3/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:472)
	at brut.androlib.Androlib.buildResources(Androlib.java:410)
	at brut.androlib.Androlib.build(Androlib.java:298)
	at brut.androlib.Androlib.build(Androlib.java:268)
	at brut.apktool.Main.cmdBuild(Main.java:225)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/var/folders/1x/rbs7f_y145qf3f9dbbzktwlw0000gn/T/brut_util_Jar_6655770474063448832.tmp, p, --forced-package-id, 127, --min-sdk-version, 27, --target-sdk-version, 27, --version-code, 1, --version-name, 1.0, -F, /var/folders/1x/rbs7f_y145qf3f9dbbzktwlw0000gn/T/APKTOOL2428216456422291333.tmp, -0, arsc, -0, version, -0, arsc, -I, /Users/eilir/Library/apktool/framework/1.apk, -S, /Users/eilir/work6/安卓/new3/res, -M, /Users/eilir/work6/安卓/new3/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:425)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:458)
	... 5 more
Caused by: brut.common.BrutException: could not exec command: [/var/folders/1x/rbs7f_y145qf3f9dbbzktwlw0000gn/T/brut_util_Jar_6655770474063448832.tmp, p, --forced-package-id, 127, --min-sdk-version, 27, --target-sdk-version, 27, --version-code, 1, --version-name, 1.0, -F, /var/folders/1x/rbs7f_y145qf3f9dbbzktwlw0000gn/T/APKTOOL2428216456422291333.tmp, -0, arsc, -0, version, -0, arsc, -I, /Users/eilir/Library/apktool/framework/1.apk, -S, /Users/eilir/work6/安卓/new3/res, -M, /Users/eilir/work6/安卓/new3/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:89)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)
	... 6 more

```

### Steps to Reproduce
1. `apktool `

### Frameworks
I already install one that live in `/system/framework` in my avd of API level 27.

### APK
I changed the .apk to .zip.Download it and rename back.

[new3的副本.zip](https://github.com/iBotPeaches/Apktool/files/2113729/new3.zip)

**Comment by ibuprophen1** [comment]
@wishma2013, You need to change the name of the apk itself. Apktool cannot use the name "new3的副本.apk" because of the "的副本" characters within the name. 

Try changing it to "new3.apk" and you should be all set. 

Changing the name of the apk file itself will not affect the apk itself. You can always rename the apk name back after its compiled. 

Good Luck! 


~Ibuprophen

**Comment by itsmehacker** [comment]
this will not work i am now facing same issue with apktool latest version

**Comment by iBotPeaches** [comment]
Could not duplicate this on the latest version. Based on your report you are using v2.0.3 which is very old. 

Please try upgrading and try again.

```
I: Using Apktool 2.3.4-92bec5-SNAPSHOT on new3.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/connortumbleson/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1822 apktool b new3
I: Using Apktool 2.3.4-92bec5-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
➜  Bug1822    
```
