### ISSUE TITLE
Failed to build Error

### ISSUE THREAD

**Issue by JMilkan** [iBotPeaches/Apktool#1826]
### Information
1. **Apktool Version (`apktool 2.3.3`)** -
2. **Operating System (Linux)** -
3. **APK From? (Playstore, Other)** -

### Stacktrace/Logcat

```
Exception in thread "main" java.lang.NoSuchMethodError: brut.androlib.meta.StringExConstructor.constructScalar(Lorg/yaml/snakeyaml/nodes/ScalarNode;)Ljava/lang/Object;
	at brut.androlib.meta.StringExConstructor.access$100(StringExConstructor.java:25)
	at brut.androlib.meta.StringExConstructor$ConstructStringEx.construct(StringExConstructor.java:32)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193)
	at org.yaml.snakeyaml.constructor.SafeConstructor.processDuplicateKeys(SafeConstructor.java:85)
	at org.yaml.snakeyaml.constructor.SafeConstructor.flattenMapping(SafeConstructor.java:70)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:190)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:149)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:309)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:159)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:146)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:518)
	at brut.androlib.meta.MetaInfo.load(MetaInfo.java:70)
	at brut.androlib.Androlib.readMetaFile(Androlib.java:260)
	at brut.androlib.Androlib.build(Androlib.java:274)
	at brut.androlib.Androlib.build(Androlib.java:267)
	at brut.apktool.Main.cmdBuild(Main.java:238)
	at brut.apktool.Main.main(Main.java:76)
```

### Steps to Reproduce
1. `apktool d -o app2.apk app.apk `
2. `apktool b app2.apk`

### Frameworks

(`default 1.apk`)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? no
3. Are you using the latest apktool version? yes

**Comment by iBotPeaches** [comment]
Could you attach the `apktool.yml` file from the decoded application? Something in there is not right.

**Comment by JMilkan** [comment]
yes, sure.

[apktool.zip](https://github.com/iBotPeaches/Apktool/files/2129095/apktool.zip)

**Comment by iBotPeaches** [comment]
The version number on that build is `2.3.3-dirty`, not the official `2.3.3` release. This paired with a `methodNotFound` exception leads me to believe this application wasn't built right. If you re-try with official release - https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.3.3.jar

I can re-open if issue persists.
