### ISSUE TITLE
Recompiling error exception in thread "main" Java.lang.NosuchMethod error

### ISSUE THREAD

**Issue by sasuke1999** [iBotPeaches/Apktool#1831]
### Information
1. **Apktool Version (`apktool -version`)** -
2. **Operating System (Mac, Linux, Windows)** -
3. **APK From? (Playstore, ROM, Other)** -

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by sasuke1999** [comment]
root@localhost:/home/android# apt-get install aapt
Reading package lists... Done
Building dependency tree       
Reading state information... Done
aapt is already the newest version (1:7.0.0+r33-1).
aapt set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@localhost:/home/android# ls
Desktop  avast.apk  ngrok  original  payload  test.apk
root@localhost:/home/android# apktool b payload 
I: Using Apktool 2.3.3-dirty
Exception in thread "main" java.lang.NoSuchMethodError: brut.androlib.meta.StringExConstructor.constructScalar(Lorg/yaml/snakeyaml/nodes/ScalarNode;)Ljava/lang/Object;
	at brut.androlib.meta.StringExConstructor.access$100(StringExConstructor.java:25)
	at brut.androlib.meta.StringExConstructor$ConstructStringEx.construct(StringExConstructor.java:32)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193)
	at org.yaml.snakeyaml.constructor.SafeConstructor.processDuplicateKeys(SafeConstructor.java:85)
	at org.yaml.snakeyaml.constructor.SafeConstructor.flattenMapping(SafeConstructor.java:70)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:190)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:149)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:309)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:159)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:146)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:518)
	at brut.androlib.meta.MetaInfo.load(MetaInfo.java:70)
	at brut.androlib.Androlib.readMetaFile(Androlib.java:260)
	at brut.androlib.Androlib.build(Androlib.java:274)
	at brut.androlib.Androlib.build(Androlib.java:267)
	at brut.apktool.Main.cmdBuild(Main.java:238)
	at brut.apktool.Main.main(Main.java:76)

**Comment by iBotPeaches** [comment]
Tests are passing, can not replicate. Please ensure that you built apktool correctly, `2.3.3-dirty` is not official.
