### ISSUE TITLE
NumberFormatException

### ISSUE THREAD

**Issue by sup3rgiu** [iBotPeaches/Apktool#1841]
### Information
1. **Apktool Version (2.3.3)** -
2. **Operating System (Windows)** -
3. **APK From? (Other)** -

I'm trying to log some variables in this app, but first I tried to decompile and recompile it without changing anything. When I open the app, it crashes.

Also, I noticied that in some smali files, some methods are not decompiled correctly and they appear like:
```
/* Error */
  private javax.net.ssl.SSLSocketFactory b(Context paramContext)
  {
    // Byte code:
    //   0: ldc 76
    //   2: invokestatic 82	java/security/KeyStore:getInstance	(Ljava/lang/String;)Ljava/security/KeyStore;
    //   5: astore_2
    //   6: aload_1
    //   7: invokevirtual 88	android/content/Context:getResources	()Landroid/content/res/Resources;
    //   10: ldc 89
    //   12: invokevirtual 95	android/content/res/Resources:openRawResource	(I)Ljava/io/InputStream;
    //   15: astore_1
    //   16: new 97	java/lang/String
    //   19: astore_3
    //   20: aload_3
    //   21: invokestatic 102	com/live/taptv/TVTAP:b	()Landroid/content/Context;
    //   24: invokestatic 108	com/live/taptv/utils/e:g	(Landroid/content/Context;)Ljava/lang/String;
    //   27: invokestatic 102	com/live/taptv/TVTAP:b	()Landroid/content/Context;
    //   30: invokestatic 111	com/live/taptv/utils/e:f	(Landroid/content/Context;)Ljava/lang/String;
    //   33: invokestatic 102	com/live/taptv/TVTAP:b	()Landroid/content/Context;
    //   36: invokestatic 116	com/live/taptv/utils/Security:a	(Landroid/content/Context;)I
    //   39: invokestatic 120	com/live/taptv/utils/webservice/NetworkManager:getstore	(Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;
    //   42: invokestatic 123	com/live/taptv/utils/Security:a	(Ljava/lang/String;)Ljava/lang/String;
    //   45: iconst_0
    //   46: invokestatic 129	android/util/Base64:decode	(Ljava/lang/String;I)[B
    //   49: invokespecial 132	java/lang/String:<init>	([B)V
    //   52: aload_2
    //   53: aload_1
    //   54: aload_3
    //   55: invokevirtual 136	java/lang/String:toCharArray	()[C
    //   58: invokevirtual 140	java/security/KeyStore:load	(Ljava/io/InputStream;[C)V
    //   61: aload_1
    //   62: invokevirtual 145	java/io/InputStream:close	()V
    //   65: invokestatic 150	javax/net/ssl/TrustManagerFactory:getDefaultAlgorithm	()Ljava/lang/String;
    //   68: invokestatic 153	javax/net/ssl/TrustManagerFactory:getInstance	(Ljava/lang/String;)Ljavax/net/ssl/TrustManagerFactory;
    //   71: astore_1
    //   72: aload_1
    //   73: aload_2
    //   74: invokevirtual 157	javax/net/ssl/TrustManagerFactory:init	(Ljava/security/KeyStore;)V
    //   77: ldc -97
    //   79: invokestatic 164	javax/net/ssl/SSLContext:getInstance	(Ljava/lang/String;)Ljavax/net/ssl/SSLContext;
    //   82: astore_2
    //   83: aload_2
    //   84: aconst_null
    //   85: aload_1
    //   86: invokevirtual 168	javax/net/ssl/TrustManagerFactory:getTrustManagers	()[Ljavax/net/ssl/TrustManager;
    //   89: aconst_null
    //   90: invokevirtual 171	javax/net/ssl/SSLContext:init	([Ljavax/net/ssl/KeyManager;[Ljavax/net/ssl/TrustManager;Ljava/security/SecureRandom;)V
    //   93: aload_2
    //   94: invokevirtual 175	javax/net/ssl/SSLContext:getSocketFactory	()Ljavax/net/ssl/SSLSocketFactory;
    //   97: areturn
    //   98: astore_2
    //   99: aload_1
    //   100: invokevirtual 145	java/io/InputStream:close	()V
    //   103: aload_2
    //   104: athrow
    //   105: astore_1
    //   106: aload_1
    //   107: invokevirtual 178	java/lang/Exception:printStackTrace	()V
    //   110: new 180	java/lang/AssertionError
    //   113: dup
    //   114: aload_1
    //   115: invokespecial 183	java/lang/AssertionError:<init>	(Ljava/lang/Object;)V
    //   118: athrow
    // Local variable table:
    //   start	length	slot	name	signature
    //   0	119	0	this	NetworkManager
    //   0	119	1	paramContext	Context
    //   5	89	2	localObject1	Object
    //   98	6	2	localObject2	Object
    //   19	36	3	str	String
    // Exception table:
    //   from	to	target	type
    //   16	61	98	finally
    //   0	16	105	java/lang/Exception
    //   61	98	105	java/lang/Exception
    //   99	105	105	java/lang/Exception
  }
```

Also, this one method appears in the logcat below
```
at com.live.taptv.utils.webservice.NetworkManager.b(NetworkManager.java:160)
```

### Stacktrace/Logcat

```
Process: com.live.taptv, PID: 5650
java.lang.AssertionError: java.lang.NumberFormatException: For input string: "3s"
       at com.live.taptv.utils.webservice.NetworkManager.b(NetworkManager.java:160)
       at com.live.taptv.utils.webservice.NetworkManager.<init>(NetworkManager.java:52)
       at com.live.taptv.utils.webservice.NetworkManager.a(NetworkManager.java:59)
       at com.live.taptv.TVTAP.onCreate(TVTAP.java:70)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java)
       at android.app.ActivityThread.-wrap2(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
       at android.os.Handler.dispatchMessage(Handler.java)
       at android.os.Looper.loop(Looper.java)
       at android.app.ActivityThread.main(ActivityThread.java)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
Caused by: java.lang.NumberFormatException: For input string: "3s"
       at java.lang.Integer.parseInt(Integer.java:521)
       at com.live.taptv.utils.Security.a(Security.java:167)
       at com.live.taptv.utils.webservice.NetworkManager.b(NetworkManager.java:141)
       ... 13 more
ActivityManager:   Force finishing activity com.live.taptv/.ui.MainActivity
```

### Steps to Reproduce
1. `apktool d app.apk `
2. `apktool b app `

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://goo.gl/bVdnuf

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? **YES**
2. If you are trying to install a modified apk, did you resign it? **YES**
3. Are you using the latest apktool version? **YES**

**Comment by ibuprophen1** [comment]
@sup3rgiu, I believe that this is similar/same as the following 3 issues & could be helpful with the information provided within them OR may be an ongoing issue that iBotPeaches may not have resolved yet. 

https://github.com/iBotPeaches/Apktool/issues/1553 
https://github.com/iBotPeaches/Apktool/issues/1414 
https://github.com/iBotPeaches/Apktool/issues/1274 

Am I correct or incorrect with this @iBotPeaches? 


~Ibuprophen

**Comment by iBotPeaches** [comment]
Not sure tool was used, but Apktool in my knowledge (even with smali) cannot generate that output.

```
➜  TVTAP1.1 grep -r -i 'private javax.net.ssl.SSLSocketFactory' *
➜ 
```

No matches in my decoded application. 

```
➜  TVTAP1.1 apktool b .
I: Using Apktool 2.3.4-92bec5-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
➜  TVTAP1.1 
```

**Comment by sup3rgiu** [comment]
@iBotPeaches I'm not getting errors while decompiling or (re)building the app... 


```
A:\Orbit Download>apktool d TVTAP1.1.apk
I: Using Apktool 2.3.3 on TVTAP1.1.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\MeA\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

A:\Orbit Download>apktool b TVTAP1.1
I: Using Apktool 2.3.3
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...

```

The other log was taken with adb logcat while opening the app on my device.

You should try the decompile, recompile and install the app and you will see that is crashes at startup.

**Comment by iBotPeaches** [comment]
@sup3rgiu I unfortunately don't have the time to download, build, install and investigate issues that detailed these days. My small amount of time weekly (5 hours) is mainly taken up just triaging tickets, even which I'm behind in.

If you can do that investigation, discover the resource original value vs decoded/built value, that will allow me to skip the process of investigation and investigate a fix.
