### ISSUE TITLE
UndefinedResObject: resource spec: 0x7f000000

### ISSUE THREAD

**Issue by RedstoneEditor** [iBotPeaches/Apktool#1846]
### Information
1. ApkTool v2.3.3 (Latest)
2. Windows 10
3. Play Store APK, or even an APK Editor Pro rebuilt and signed APK file

### Stacktrace/Logcat

Stacktrace with Framework installed from device( Samsung Galaxy S 8+)

```
$ java -Xmx128m -jar C:/Users/jtrenaud1s/.apkstudio/vendor/apktool.jar -f d C:/Users/jtrenaud1s/Desktop/base.apk -o C:/Users/jtrenaud1s/Desktop/base
I: Using Apktool 2.0.2 on base.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\jtrenaud1s\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
Exception in thread "main" brut.androlib.err.UndefinedResObject: resource spec: 0x7f000000
	at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:65)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:61)
	at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferenceValue.java:57)
	at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:54)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:502)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:252)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:135)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
	at brut.apktool.Main.cmdDecode(Main.java:165)
	at brut.apktool.Main.main(Main.java:81)
```

Stacktrace with default framework files shows a different resource value such as 0x01010543

### Steps to Reproduce
1. Simply try and decode the apk file, no matter what, you get the error. APK Editor Pro works fine though, not sure if it uses apktool, but it's an app on the device that does the same thing apktool can do. The app is obfuscated (At least the Java Sources are, but it's simple to figure out) and the resource files are all raw, when decoded using the APK Editor Pro app

### Frameworks
[SM-g955U-framework.zip](https://github.com/iBotPeaches/Apktool/files/2216640/SM-g955U-framework.zip) ?

### APK
Play Store: Cargo Driver, https://play.google.com/store/apps/details?id=com.cargo.sp
### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? No, No
3. Are you using the latest apktool version? Yes

Notes: It works with other apk files, this specific one seems to not be working, and I'm wondering if it has been built on custom framework files, and if so, how to remap them.

**Comment by RedstoneEditor** [comment]
Please disregard, contrary to my own belief, I was not using the most up to date version, I had been using the wrong jar from my downloads the whole time.
