### ISSUE TITLE
java.util.zip.ZipException: invalid CEN header (encrypted entry), still works on Oreo

### ISSUE THREAD

**Issue by nguyenvulong** [iBotPeaches/Apktool#1851]
### Information
1. **Apktool Version (`apktool -version`)** -2.0.2-dirty
2. **Operating System (Mac, Linux, Windows)** - Linux (Ubuntu)
3. **APK From? (Playstore, ROM, Other)** - Other

###Disclaim: This apk is a malware
This stacktrace is quite similar to https://github.com/iBotPeaches/Apktool/issues/550 . 
As it is already locked, I create this issue for further discussion.

I have tested this APK with the one of the newest Android OS versions (Nexus 5X, Oreo 8.1.0, Security patch May 5 2018). **It is working fine.** 
So maybe it is a different problem with issues #550 (I am not sure though)

### Stacktrace/Logcat

```
I: Using Apktool 2.0.2-dirty on 9183aba0aea1ad5608f2b1795a3c6d28.apk
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: java.util.zip.ZipException: invalid CEN header (encrypted entry)
	at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:281)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:90)
	at brut.apktool.Main.cmdDecode(Main.java:165)
	at brut.apktool.Main.main(Main.java:81)
Caused by: brut.directory.DirectoryException: java.util.zip.ZipException: invalid CEN header (encrypted entry)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:55)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:38)
	at brut.androlib.res.util.ExtFile.getDirectory(ExtFile.java:55)
	at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:279)
	... 3 more
Caused by: java.util.zip.ZipException: invalid CEN header (encrypted entry)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:53)

```

### Steps to Reproduce
1. `apktool  d 9183aba0aea1ad5608f2b1795a3c6d28.apk`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK: please change  *zip extension to *apk
[9183aba0aea1ad5608f2b1795a3c6d28.zip](https://github.com/iBotPeaches/Apktool/files/2223754/9183aba0aea1ad5608f2b1795a3c6d28.zip)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes, I have
2. If you are trying to install a modified apk, did you resign it? N/A
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
Interesting. I reverted these patches, because AOSP patched it (https://android.googlesource.com/platform/libcore/+/25681be69e19a834b00cfbf54cd99ac13f12b9ff)

 - https://github.com/iBotPeaches/Apktool/commit/81e6af093b9584f5bd34f24cc5a9cb1c45a66b6d#diff-ac42123fbe1bbc1292afcdffc87d521a

I'll have to do some digging. Thanks for a new report

**Comment by vvizz19** [comment]
change 'PK' xxxx  01 -> 00, not work.  focus on it, zz~~

**Comment by iBotPeaches** [comment]
I reverted this and not bringing it back. Use older Apktool if you need it. This doesn't work on newer Android.
