### ISSUE TITLE
U able to dcompile

### ISSUE THREAD

**Issue by BalaKeelapudi** [iBotPeaches/Apktool#1871]
### Information
1. **Apktool Version (`apktool -version`)** -
2. **Operating System (Windows 10)** -
3. **APK From? (XDA: https://forum.xda-developers.com/lg-g5/themes/help-google-camera-port-cstark27-google-t3751224)** -

### Stacktrace/Logcat

```C:\Users\balak\Desktop\Apktool>apktool d cstark27_GCam_5.1.018_24_v3.6.apk
I: Using Apktool 2.0.0-RC4 on cstark27_GCam_5.1.018_24_v3.6.apk
I: Loading resource table...
W: Config flags size > 38. Exceeding bytes: 0x746E00000000000000000000000000000000.
W: Invalid config flags detected. Dropping resources: array-sr-ERR0
W: Config flags size > 38. Exceeding bytes: 0x746E00000000000000000000000000000000.
W: Invalid config flags detected. Dropping resources: plurals-sr-ERR1
W: Config flags size > 38. Exceeding bytes: 0x746E00000000000000000000000000000000.
W: Invalid config flags detected. Dropping resources: string-sr-ERR2
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\balak\apktool\framework\1.apk
Exception in thread "main" java.lang.ClassCastException: brut.androlib.res.data.value.ResStringValue cannot be cast to brut.androlib.res.data.value.ResAttr
        at brut.androlib.res.decoder.ResAttrDecoder.decode(ResAttrDecoder.java:36)
        at brut.androlib.res.decoder.AXmlResourceParser.getAttributeValue(AXmlResourceParser.java:369)
        at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValue(XmlPullParserDelegate.java:69)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
        at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:83)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:141)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:153)
        at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:134)
        at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:294)
        at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:138)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
        at brut.apktool.Main.cmdDecode(Main.java:165)
        at brut.apktool.Main.main(Main.java:81)
```

### Steps to Reproduce
1. C:\Users\balak\Desktop\Apktool>apktool d cstark27_GCam_5.1.018_24_v3.6.apk

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by iBotPeaches** [comment]
```
➜  1871 apktool d cstark27_GCam_5.1.018_24_v3.6.apk 
I: Using Apktool 2.3.3 on cstark27_GCam_5.1.018_24_v3.6.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
```

I couldn't duplicate this. You are using a version that is nearly 3-4 years old. Please try upgrading Apktool.
