### ISSUE TITLE
Failed To build an apk

### ISSUE THREAD

**Issue by V3rB0se** [iBotPeaches/Apktool#1873]
sudo apktool b /home/parrot/Desktop/Closet
```
I: Using Apktool 2.3.3-dirty
Exception in thread "main" java.lang.NoSuchMethodError: brut.androlib.meta.StringExConstructor.constructScalar(Lorg/yaml/snakeyaml/nodes/ScalarNode;)Ljava/lang/String;
	at brut.androlib.meta.StringExConstructor.access$100(StringExConstructor.java:25)
	at brut.androlib.meta.StringExConstructor$ConstructStringEx.construct(StringExConstructor.java:32)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:207)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:196)
	at org.yaml.snakeyaml.constructor.SafeConstructor.processDuplicateKeys(SafeConstructor.java:85)
	at org.yaml.snakeyaml.constructor.SafeConstructor.flattenMapping(SafeConstructor.java:70)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:190)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:149)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:310)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:207)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:196)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:161)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:147)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:518)
	at brut.androlib.meta.MetaInfo.load(MetaInfo.java:70)
	at brut.androlib.Androlib.readMetaFile(Androlib.java:260)
	at brut.androlib.Androlib.build(Androlib.java:274)
	at brut.androlib.Androlib.build(Androlib.java:267)
	at brut.apktool.Main.cmdBuild(Main.java:238)
	at brut.apktool.Main.main(Main.java:76)
```

**Comment by iBotPeaches** [comment]
It seems based on the stacktrace that this is a "dirty" build. Test suite is currently passing and due to lack of information and following issue template, there isn't anything I can do here.
