### ISSUE TITLE
Bug Apktool 

### ISSUE THREAD

**Issue by Adityaindra1212** [iBotPeaches/Apktool#1877]
### Information
1. **apktool 2.3.3-dirty** 
2. **Linux localhost 4.17.0-kali1-amd64 #1 SMP Debian 4.17.8-1kali1 (2018-07-24) x86_64 GNU/Linux** 

### Stacktrace/Logcat

[Desktop] apktool b rolli -o roli.apk                                          
I: Using Apktool 2.3.3-dirty
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
	at org.jf.dexlib2.writer.DexWriter.writeAnnotationDirectories(DexWriter.java:698)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:267)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:246)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:61)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:36)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:417)
	at brut.androlib.Androlib.buildNonDefaultSources(Androlib.java:363)
	at brut.androlib.Androlib.build(Androlib.java:301)
	at brut.androlib.Androlib.build(Androlib.java:267)
	at brut.apktool.Main.cmdBuild(Main.java:238)
	at brut.apktool.Main.main(Main.java:76)

Help me

**Comment by iBotPeaches** [comment]
I can't replicate this. Make sure you are using official releases. The `-dirty` tag in the version makes it look it was a modified build and/or built in custom.

**Comment by JulianVolodia** [comment]
It is closed, but could be caused not because of `-dirty` tag (many Debian-like distros) but because wrong java alternative (see: `update-alternatives --config java` ).

**Comment by nubuntu** [comment]
> It is closed, but could be caused not because of `-dirty` tag (many Debian-like distros) but because wrong java alternative (see: `update-alternatives --config java` ).

thanks, you save my life
