### ISSUE TITLE
Could not decode arsc file

### ISSUE THREAD

**Issue by evildog1** [iBotPeaches/Apktool#1881]
### Information
1. **Apktool Version (`apktool -version`)** 2.3.3
2. **Operating System (Mac, Linux, Windows)** Windows 10 64-bit 
3. **APK From? (Playstore, ROM, Other)** https://play.google.com/store/apps/details?id=com.alibaba.aliexpresshd

### Stacktrace/Logcat

```
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:53)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:741)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:67)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:59)
	at brut.androlib.Androlib.getResTable(Androlib.java:68)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:228)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:118)
	at brut.apktool.Main.cmdDecode(Main.java:164)
	at brut.apktool.Main.main(Main.java:73)
Caused by: java.io.IOException: Expected: 0x001c0001, got: 0x00000000
	at brut.util.ExtDataInput.skipCheckInt(ExtDataInput.java:48)
	at brut.androlib.res.decoder.StringBlock.read(StringBlock.java:44)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:76)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:48)
	... 8 more
```

### Steps to Reproduce
1. Decompile the APK file `apktool d `

### Frameworks
No framework

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://mega.nz/#!rV5FSbiS!6dPTuEjASIwu5dZl29tEqMB2vNPg2jMotZ3e8rGhm10

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? N/A
2. If you are trying to install a modified apk, did you resign it? N/A
3. Are you using the latest apktool version? Yes

### Note
It works with apktool 2.3.1 but not 2.3.3. I don't know why

**Comment by iBotPeaches** [comment]
Looks like this might need some investigation. I reverted a commit to make a less-hacky codebase and seems this regressed. I'd rather find the proper fix for this instead of the hacky solution I previously had. See #1876 for the duplicate.

**Comment by snjjay** [comment]
Apktool is required to decode the.ARSC file and obtain the original source code. Apktool is a tool for reversing the resources of Android apps (APK). https://kodlogs.net/207/could-not-decode-arsc-file
