### ISSUE TITLE
apktool unknown issue with first type not attr

### ISSUE THREAD

**Issue by harshkuttu** [iBotPeaches/Apktool#1885]
### Information
1. **Apktool Version (`apktool x 7.2.2a black
2. **Operating System (Mac, Linux, Windows)** - android
3. **APK From? (Playstore, ROM, Other)** -playstore

### Stacktrace/Logcat

```W: res/drawable-v21/$avd_hide_password__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable-v21/$avd_hide_password__1.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable-v21/$avd_hide_password__2.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable-v21/$avd_show_password__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable-v21/$avd_show_password__1.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable-v21/$avd_show_password__2.xml: Invalid file name: must contain only [a-z0-9_.]
W: A/        (15329): First type is not attr!
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 134): [/data/data/per.pqy.apktool/apktool/openjdk/bin/aapt6.0, p, --min-sdk-version, 17, --target-sdk-version, 27, --version-code, 33, --version-name, 1.0.59.3 b, -F, /data/data/per.pqy.apktool/APKTOOL2210248185479348882.tmp, -0, arsc, -0, arsc, -I, /data/data/per.pqy.apktool/1.apk, -S, /storage/emulated/0/Documents/BeatBox_1.0.59.3 b_src/res, -M, /storage/emulated/0/Documents/BeatBox_1.0.59.3 b_src/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:478)
	at brut.androlib.Androlib.buildResources(Androlib.java:412)
	at brut.androlib.Androlib.build(Androlib.java:311)
	at brut.androlib.Androlib.build(Androlib.java:264)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 134): [/data/data/per.pqy.apktool/apktool/openjdk/bin/aapt6.0, p, --min-sdk-version, 17, --target-sdk-version, 27, --version-code, 33, --version-name, 1.0.59.3 b, -F, /data/data/per.pqy.apktool/APKTOOL2210248185479348882.tmp, -0, arsc, -0, arsc, -I, /data/data/per.pqy.apktool/1.apk, -S, /storage/emulated/0/Documents/BeatBox_1.0.59.3 b_src/res, -M, /storage/emulated/0/Documents/BeatBox_1.0.59.3 b_src/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:439)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:464)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 134): [/data/data/per.pqy.apktool/apktool/openjdk/bin/aapt6.0, p, --min-sdk-version, 17, --target-sdk-version, 27, --version-code, 33, --version-name, 1.0.59.3 b, -F, /data/data/per.pqy.apktool/APKTOOL2210248185479348882.tmp, -0, arsc, -0, arsc, -I, /data/data/per.pqy.apktool/1.apk, -S, /storage/emulated/0/Documents/BeatBox_1.0.59.3 b_src/res, -M, /storage/emulated/0/Documents/BeatBox_1.0.59.3 b_src/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:433)
	... 6 more
I: Using Apktool 2.2.2-Black
I: Smaling smali folder into classes.dex...
I: Building resources...

Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version? yes 2.3.3

**Comment by iBotPeaches** [comment]
Both of these issues have been fixed. One requires `aapt2` and the other requires newest Apktool.

Based on the release notes of "apktool x 7.2.2a", I have no idea what version that is. So going to close this.

**Comment by harshkuttu** [comment]
this is an andro black apktool

**Comment by ibuprophen1** [comment]
@harshkuttu, there's an Apktool X v7.3.3 Andro Black had released last year. 

Also, Apktool X versions don't correspond with iBotPeaches Apktool.jar versions. 


~Ibuprophen
