### ISSUE TITLE
xx/original/META-INF/license/LICENSE.base64.txt (Not a directory)

### ISSUE THREAD

**Issue by zjinpeng** [iBotPeaches/Apktool#1900]
### Information
1. **Apktool Version (`2.3.4`)** -
2. **Operating System (Mac)** -
3. **APK From? (Playstore)** -

### Stacktrace/Logcat

```
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: Error copying file: META-INF
	at brut.androlib.Androlib.writeOriginalFiles(Androlib.java:245)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:175)
	at brut.apktool.Main.cmdDecode(Main.java:163)
	at brut.apktool.Main.main(Main.java:72)
Caused by: brut.directory.DirectoryException: Error copying file: META-INF
	at brut.directory.DirUtil.copyToDir(DirUtil.java:91)
	at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:208)
	at brut.androlib.Androlib.writeOriginalFiles(Androlib.java:242)
	... 3 more
Caused by: brut.directory.DirectoryException: Error copying file: license/LICENSE.base64.txt
	at brut.directory.DirUtil.copyToDir(DirUtil.java:88)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:61)
	at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:198)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:77)
	... 5 more
Caused by: java.io.FileNotFoundException: xx/original/META-INF/license/LICENSE.base64.txt (Not a directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:84)
	... 8 more
```

### Steps to Reproduce
1. `java -jar apktool_2.3.4.jar d xx.apk`

### APK
If this APK can be freely shared, please upload/attach a link to it.
GooglePlay serch  `com.more.dayzsurvival.gp`

**Comment by zjinpeng** [comment]
I found the path is `xx/original/META-INF/license-1/LICENSE.base64.txt`

**Comment by iBotPeaches** [comment]
Sorry, let this sit for too many years without triage. I don't have apk.

Closing as not triagable.
