### ISSUE TITLE
brut.directory.DirectoryException: Error copying file: assets

### ISSUE THREAD

**Issue by toby624** [iBotPeaches/Apktool#1907]
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.4
2. **Operating System (Mac, Linux, Windows)** - Windows 7 64bit
3. **APK From? (Playstore, ROM, Other)** - Other 

### Stacktrace/Logcat
```
System.Exception: Failed to decompile the APK file. See details for more information: Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: Error copying file: assets
	at brut.androlib.Androlib.decodeRawFiles(Androlib.java:160)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:171)
	at brut.apktool.Main.cmdDecode(Main.java:164)
	at brut.apktool.Main.main(Main.java:73)
Caused by: brut.directory.DirectoryException: Error copying file: assets
	at brut.directory.DirUtil.copyToDir(DirUtil.java:91)
	at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:208)
	at brut.androlib.Androlib.decodeRawFiles(Androlib.java:147)
	... 3 more
Caused by: brut.directory.DirectoryException: Error copying file: certificates/*.***marks***.com
	at brut.directory.DirUtil.copyToDir(DirUtil.java:88)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:61)
	at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:198)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:77)
	... 5 more
Caused by: java.io.FileNotFoundException: C:\Users\***\AppData\Local\RANORE~1\RxEnv\Android\temp\decomp\assets\certificates\*.***marks***.com (The filename, directory name, or volume label syntax is incorrect)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:84)
	... 8 more

   at Ranorex.Plugin.Mobile.Tools.Android.Instrumentation.ApkFileInstrumenter.DecompileApkFile(String apkFilePath, Boolean showProcessWindows, IPathService pathService, InstrumentApkOptions deployOptions)
   at Ranorex.Plugin.Mobile.Tools.Android.Instrumentation.ApkFileInstrumenter.Instrument(String apkFilePath, Int32 port, InstrumentApkOptions deployOptions, BackgroundWorker bgw)
   at Ranorex.Plugin.Mobile.RxIntegration.Instrumentation.AndroidWorker.Run()
   at Ranorex.Controls.AndroidInstrumentProgressPage.bgw_DoWork(Object sender, DoWorkEventArgs e)
```
### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

**Comment by iBotPeaches** [comment]
Looks like you are hitting a reserved filename on WIndows.

**Comment by toby624** [comment]
you mean the certificates file or apk name? thanks
anything can i do?

**Comment by toby624** [comment]
Thanks for your reply,
Do you mean the file in asset folder or the apk name? And any suggestion without edit the apk? Thanks again!

**Comment by iBotPeaches** [comment]
This will have to be fixed in https://github.com/iBotPeaches/Apktool/issues/1460 during remapping. Closing as duplicate.
