### ISSUE TITLE
APK Crash 

### ISSUE THREAD

**Issue by AlleSchonWeg** [iBotPeaches/Apktool#1908]
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.4
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - apkmonk

### Stacktrace/Logcat

```
09-28 14:56:03.867 13058 13390 E AndroidRuntime: java.lang.NoClassDefFoundError: kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at kotlin.reflect.jvm.internal.impl.builtins.KotlinBuiltIns.createBuiltInsModule(SourceFile:148)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at kotlin.reflect.jvm.internal.impl.platform.JvmBuiltIns.<init>(SourceFile:56)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at kotlin.reflect.jvm.internal.impl.platform.JvmBuiltIns.<init>(SourceFile:31)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at kotlin.reflect.jvm.internal.components.RuntimeModuleData$Companion.create(SourceFile:57)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at kotlin.reflect.jvm.internal.ModuleByClassLoaderKt.getOrCreateModule(SourceFile:58)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data$moduleData$2.invoke(SourceFile:35)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data$moduleData$2.invoke(SourceFile:32)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(SourceFile:93)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(SourceFile:32)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data.getModuleData(SourceFile)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(SourceFile:46)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(SourceFile:43)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(SourceFile:93)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(SourceFile:32)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at kotlin.reflect.jvm.internal.KClassImpl$Data.getDescriptor(SourceFile)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at kotlin.reflect.jvm.internal.KClassImpl.getDescriptor(SourceFile:172)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at kotlin.reflect.jvm.internal.KClassImpl.isAbstract(SourceFile:250)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at com.squareup.moshi.b.a.b.create(SourceFile:184)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at com.squareup.moshi.k.create(SourceFile)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at com.squareup.moshi.m.a(SourceFile:130)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at retrofit2.converter.moshi.MoshiConverterFactory.requestBodyConverter(SourceFile:106)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at retrofit2.Retrofit.nextRequestBodyConverter(SourceFile:282)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at retrofit2.Retrofit.requestBodyConverter(SourceFile:262)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at retrofit2.ServiceMethod$Builder.parseParameterAnnotation(SourceFile:710)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at retrofit2.ServiceMethod$Builder.parseParameter(SourceFile:336)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at retrofit2.ServiceMethod$Builder.build(SourceFile:204)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at retrofit2.Retrofit.loadServiceMethod(SourceFile:170)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at retrofit2.Retrofit$1.invoke(SourceFile:147)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at java.lang.reflect.Proxy.invoke(Proxy.java:813)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at com.tinder.api.retrofit.$Proxy4.notifyPushServerAppOpen(Unknown Source)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at com.tinder.api.retrofit.TinderRetrofitApi.notifyPushServerAppOpen(SourceFile:755)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at com.tinder.pushnotifications.usecase.NotifyPushServer.a(SourceFile:52)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at com.tinder.utils.AppLifeCycleTracker.b(SourceFile:117)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at com.tinder.utils.AppLifeCycleTracker.a(SourceFile:149)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at com.tinder.utils.AppLifeCycleTracker.b(SourceFile:90)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at com.tinder.utils.f.a(Unknown Source)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at com.tinder.utils.AppLifeCycleTracker$b$1.run(SourceFile:257)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at java.util.TimerThread.mainLoop(Timer.java:555)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at java.util.TimerThread.run(Timer.java:505)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: Caused by: java.lang.ExceptionInInitializerError
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader.<clinit>(SourceFile)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at kotlin.reflect.jvm.internal.impl.builtins.KotlinBuiltIns.createBuiltInsModule(SourceFile:148)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at kotlin.reflect.jvm.internal.impl.platform.JvmBuiltIns.<init>(SourceFile:56)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at kotlin.reflect.jvm.internal.impl.platform.JvmBuiltIns.<init>(SourceFile:31)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at kotlin.reflect.jvm.internal.components.RuntimeModuleData$Companion.create(SourceFile:57)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at kotlin.reflect.jvm.internal.ModuleByClassLoaderKt.getOrCreateModule(SourceFile:58)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data$moduleData$2.invoke(SourceFile:35)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data$moduleData$2.invoke(SourceFile:32)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(SourceFile:93)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(SourceFile:32)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data.getModuleData(SourceFile)
09-28 14:56:03.867 13058 13390 E AndroidRuntime: 	at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(SourceFile:46)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(SourceFile:43)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(SourceFile:93)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(SourceFile:32)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at kotlin.reflect.jvm.internal.KClassImpl$Data.getDescriptor(SourceFile)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at kotlin.reflect.jvm.internal.KClassImpl.getDescriptor(SourceFile:172)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at kotlin.reflect.jvm.internal.KClassImpl.isAbstract(SourceFile:250)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at com.squareup.moshi.b.a.b.create(SourceFile:184)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at com.squareup.moshi.k.create(SourceFile)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at com.squareup.moshi.m.a(SourceFile:130)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at com.squareup.moshi.m.a(SourceFile:64)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at com.squareup.moshi.d.a(SourceFile:52)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at com.squareup.moshi.d$1.create(SourceFile:36)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at com.squareup.moshi.m.a(SourceFile:130)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at com.squareup.moshi.m.a(SourceFile:64)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at com.tinder.api.model.meta.Meta_ClientResources_RateCardJsonAdapter.<init>(SourceFile:18)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at com.squareup.moshi.n.a(SourceFile:246)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at com.squareup.moshi.n$1.create(SourceFile:62)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at com.squareup.moshi.m.a(SourceFile:130)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at com.squareup.moshi.m.a(SourceFile:68)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at com.tinder.api.model.meta.Meta_ClientResourcesJsonAdapter.<init>(SourceFile:18)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at com.squareup.moshi.n.a(SourceFile:246)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at com.squareup.moshi.n$1.create(SourceFile:62)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at com.squareup.moshi.m.a(SourceFile:130)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at com.squareup.moshi.m.a(SourceFile:68)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at com.tinder.api.model.meta.MetaJsonAdapter.<init>(SourceFile:29)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at com.squareup.moshi.n.a(SourceFile:246)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at com.squareup.moshi.n$1.create(SourceFile:62)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at com.squareup.moshi.m.a(SourceFile:130)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at retrofit2.converter.moshi.MoshiConverterFactory.responseBodyConverter(SourceFile:91)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at retrofit2.Retrofit.nextResponseBodyConverter(SourceFile:330)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at retrofit2.Retrofit.responseBodyConverter(SourceFile:313)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at retrofit2.ServiceMethod$Builder.createResponseConverter(SourceFile:736)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at retrofit2.ServiceMethod$Builder.build(SourceFile:169)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at retrofit2.Retrofit.loadServiceMethod(SourceFile:170)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at retrofit2.Retrofit$1.invoke(SourceFile:147)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at java.lang.reflect.Proxy.invoke(Proxy.java:813)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at com.tinder.api.retrofit.$Proxy4.getMeta(Unknown Source)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at com.tinder.api.retrofit.TinderRetrofitApi.getMeta(SourceFile:267)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at com.tinder.data.meta.b.a.fetchMeta(SourceFile:153)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at com.tinder.domain.meta.usecase.FetchMeta.execute(SourceFile:29)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at com.tinder.managers.bm.a(SourceFile:61)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at com.tinder.managers.bm.a(SourceFile:91)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at com.tinder.managers.bo.call(Unknown Source)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at rx.internal.operators.OnSubscribeCreate.a(SourceFile:72)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at rx.internal.operators.OnSubscribeCreate.call(SourceFile:32)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at rx.internal.operators.n.a(SourceFile:48)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at rx.internal.operators.n.call(SourceFile:30)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at rx.Observable.a(SourceFile:10256)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at rx.internal.operators.j.a(SourceFile:41)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at rx.internal.operators.j.call(SourceFile:30)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at rx.Observable.a(SourceFile:10352)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at rx.Observable.b(SourceFile:10319)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at rx.Observable.a(SourceFile:10159)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at com.tinder.session.usecase.f.a(SourceFile:55)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at com.tinder.presenters.bv.a(SourceFile:184)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at com.tinder.presenters.bv.a(SourceFile:374)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at com.tinder.presenters.bv.a(SourceFile:58)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at com.tinder.presenters.bv$a.a(SourceFile:492)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at com.tinder.presenters.bv$a.onNext(SourceFile:482)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at rx.internal.util.d.onNext(SourceFile:34)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at rx.observers.c.onNext(SourceFile:134)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at rx.internal.operators.j$a.onNext(SourceFile:101)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at rx.internal.operators.al$a.call(SourceFile:224)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at rx.a.b.b$b.run(SourceFile:107)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: Caused by: java.util.NoSuchElementException: Collection is empty.
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at kotlin.collections.w.c(SourceFile:172)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	at kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader$Companion.<clinit>(SourceFile:38)
09-28 14:56:03.869 13058 13390 E AndroidRuntime: 	... 89 more
```

### Steps to Reproduce
1. `java -jar apktool_2.3.4.jar d com.tinder.apk`
2, `java -jar apktool_2.3.4.jar b com.tinder`
3. `java -jar uber-apk-signer.jar --apks <folder>\com.tinder.apk`

### APK
https://www.apkmonk.com/download-app/com.tinder/5_com.tinder_2018-09-05.apk/

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? yes
3. Are you using the latest apktool version? yes

App crashes without changes. Login to facebook works, but  after allow location permission it stops working.

**Comment by AlleSchonWeg** [comment]
Thank you. Any ideas to bypass this?

**Comment by iBotPeaches** [comment]
I have no idea, 2+ years later. Anti-tamper/magic apps will continue to get smarter, powered by companies and people. I am, but one person.

Closing.
