### ISSUE TITLE
Nokia Oreo 8.1 Settings.apk cant decompile "StringIndexOutOfBoundsException" error

### ISSUE THREAD

**Issue by null4n** [iBotPeaches/Apktool#1923]
### Information
1. **Apktool Version ( 2.3.4 )** -
2. **Operating System ( Linux )** -
3. **APK From? ( ROM )** -

### Stacktrace/Logcat

```
$ apktool -d Settings.apk
I: Using Apktool 2.3.4 on Settings.apk
I: Loading resource table...
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 2690
	at java.lang.String.substring(String.java:1963)
	at brut.androlib.res.decoder.StringBlock.getHTML(StringBlock.java:171)
	at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:360)
	at brut.androlib.res.decoder.ARSCDecoder.readEntryData(ARSCDecoder.java:276)
	at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:252)
	at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:175)
	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:131)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:82)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:48)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:741)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:67)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:59)
	at brut.androlib.Androlib.getResTable(Androlib.java:68)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:228)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:118)
	at brut.apktool.Main.cmdDecode(Main.java:164)
	at brut.apktool.Main.main(Main.java:73)
```

### Steps to Reproduce
1. `apktool `

### Frameworks
``https://github.com/noname8964/Nokia_apk``

### APK
If this APK can be freely shared, please upload/attach a link to it.
``https://github.com/noname8964/Nokia_apk``

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by iBotPeaches** [comment]
Looks to be slightly related to #1838, but crashed at a different part. Looks like I need to figure out what is breaking these strings out of the container and patch.

**Comment by iBotPeaches** [comment]
Closing as duplicate - https://github.com/iBotPeaches/Apktool/issues/1735
