### ISSUE TITLE
NoSuchMethodError when decompiling framework-res.apk (8.1)

### ISSUE THREAD

**Issue by andyrozman** [iBotPeaches/Apktool#1930]
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.4
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - Phone - OnePlus 5T 

### Stacktrace/Logcat

```
I: Using Apktool 2.3.4 on framework-res.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying assets and libs...
I: Copying unknown files...
Exception in thread "main" java.lang.NoSuchMethodError: brut.directory.Directory.getSize(Ljava/lang/String;)J
	at brut.androlib.Androlib.recordUncompressedFiles(Androlib.java:173)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:174)
	at brut.apktool.Main.cmdDecode(Main.java:164)
	at brut.apktool.Main.main(Main.java:73)

```
java version "1.8.0_181"

### Steps to Reproduce
1. `apktool d framework-res.apk`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)
Trying to decompile main framework-res.apk (android 8.1), attached.
[framework-res.zip](https://github.com/iBotPeaches/Apktool/files/2529499/framework-res.zip)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Fails at first step...
2. If you are trying to install a modified apk, did you resign it? ---
3. Are you using the latest apktool version? Yes

**Comment by andyrozman** [comment]
I retried with 1.7 java - 1.7.0_80 and same error.

**Comment by andyrozman** [comment]
OK. Closing this issue... It seems that problem was with my instalation.. I had an old installation there  with old wrapper script, which used whole /usr/share/apktool directory as library, which actually had some old files/libraries there, and it seems that some implementation conflicted with new one. 
After installing new wrapper and following instructions I got it working...
