### ISSUE TITLE
NullPointerException when Decoding values */* XMLs

### ISSUE THREAD

**Issue by maldiva** [iBotPeaches/Apktool#1945]
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.4
2. **Operating System (Mac, Linux, Windows)** - Windows 10
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat
```
I: Using Apktool 2.3.4 on base.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\PC\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
Exception in thread "main" java.lang.NullPointerException
            at brut.androlib.res.data.value.ResEnumAttr.serializeBody(ResEnumAttr.java:56)
           at brut.androlib.res.data.value.ResAttr.serializeToResValuesXml(ResAttr.java:64)
           at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:697)
           at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:263)
           at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:131)
           at brut.androlib.ApkDecoder.decode(ApkDecoder.java:124)
           at brut.apktool.Main.cmdDecode(Main.java:164)
           at brut.apktool.Main.main(Main.java:73)
```
### Steps to Reproduce
1. `apktool d base.apk`

### APK
https://github.com/navigante/base

**Comment by tprochazka** [comment]
Exactly the same issue just line numbers are differend

c:\PJazyky\_Android\Tools\APKTool>apktool.bat d -f ActionDash_1.8.apk
I: Using Apktool 2.3.4 on ActionDash_1.8.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
S: WARNING: Could not write to (C:\Users\tomas\AppData\Local\apktool\framework), using C:\Users\tomas\AppData\Local\Temp\ instead...
S: Please be aware this is a volatile directory and frameworks could go missing, please utilize --frame-path if the default storage directory is unavailable
I: Loading resource table from file: C:\Users\tomas\AppData\Local\Temp\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
Exception in thread "main" java.lang.NullPointerException
        at brut.androlib.res.data.value.ResEnumAttr.decodeValue(ResEnumAttr.java:73)
        at brut.androlib.res.data.value.ResEnumAttr.convertToResXmlFormat(ResEnumAttr.java:41)
        at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:71)
        at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:697)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:263)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:131)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:124)
        at brut.apktool.Main.cmdDecode(Main.java:164)
        at brut.apktool.Main.main(Main.java:73)

**Comment by KAlO2** [comment]
Hello, I come here for the same issue.
Exception in thread "main" java.lang.NullPointerException
        at brut.androlib.res.data.value.ResEnumAttr.serializeBody(ResEnumAttr.java:56)

https://github.com/iBotPeaches/Apktool/blob/master/brut.apktool/apktool-lib/src/main/java/brut/androlib/res/data/value/ResEnumAttr.java#L56

**Comment by Exadra37** [comment]
So this issue keeps being ignored?

I have the same issue:

```
apktool decode -f ../../app/release/app-release.apk
I: Using Apktool 2.2.1-dirty on app-release.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/java/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
Exception in thread "main" java.lang.NullPointerException
	at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:58)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:516)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:267)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:132)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:108)
	at brut.apktool.Main.cmdDecode(Main.java:166)
	at brut.apktool.Main.main(Main.java:81)
```

I am on:

```
$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

apktool was indtalled with `apt`.

**Comment by iBotPeaches** [comment]
@Exadra37 Your build is 2+ years old and dirty and it isn't relevant to this issue.

**Comment by goodguysoft** [comment]
apktool d tiktok.apk
I: Using Apktool 2.4.0 on tiktok.apk
I: Loading resource table...
W: Unknown data detected. Skipping: 192 byte(s)
W: Unknown data detected. Skipping: 32 byte(s)
W: Unknown data detected. Skipping: 2032 byte(s)
W: Unknown data detected. Skipping: 2448 byte(s)
I: Decoding AndroidManifest.xml with resources...
S: WARNING: Could not write to (C:\Users\User\AppData\Local\apktool\framework), using C:\Users\User\AppData\Local\Temp\ instead...
S: Please be aware this is a volatile directory and frameworks could go missing, please utilize --frame-path if the default storage directory is unavailable
I: Loading resource table from file: C:\Users\User\AppData\Local\Temp\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
Exception in thread "main" java.lang.NullPointerException
        at brut.androlib.res.data.value.ResEnumAttr.serializeBody(ResEnumAttr.java:56)
        at brut.androlib.res.data.value.ResAttr.serializeToResValuesXml(ResAttr.java:64)
        at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:704)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:263)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:131)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:124)
        at brut.apktool.Main.cmdDecode(Main.java:167)
        at brut.apktool.Main.main(Main.java:76)

**Comment by goodguysoft** [comment]
Is there any idea what to do?

**Comment by MIkeeJY** [comment]
Is there any idea what to do?

**Comment by gilhartman** [comment]
Same issue on 
https://www.apkmonk.com/download-app/com.safaricom.android.subreg/5_com.safaricom.android.subreg_2019-09-09.apk/

I: Using Apktool 2.4.1-75e4c6-SNAPSHOT on com.safaricom.android.subreg_2019-09-09.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/gil/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
Exception in thread "main" java.lang.NullPointerException
	at brut.androlib.res.data.value.ResEnumAttr.serializeBody(ResEnumAttr.java:56)
	at brut.androlib.res.data.value.ResAttr.serializeToResValuesXml(ResAttr.java:64)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:703)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:260)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:131)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:124)
	at brut.apktool.Main.cmdDecode(Main.java:170)
	at brut.apktool.Main.main(Main.java:76)


Tested on apktool 2.4.0 and latest apktool compiled from top of master

**Comment by Mouradif** [comment]
Same issue here trying to decompile latest Airbnb APK downloaded from 
https://www.apk4fun.com/apk/7005/

**Comment by iBotPeaches** [comment]
Rebuilding isn't going to happen, but I'll fix the NPE for now.

```
➜  1945 aapt d resources com.safaricom.android.subreg_2019-09-09.apk | grep '0x7F0903E1'
➜  1945 
```

This is is reference a parent resource that does not exist. So not really sure at all. Its not even a resource that we can make a dummy resource for. PR linked above for NPE, once merged this will close.

**Comment by apksall-creator** [comment]
Sniffies is a great app to find what you are looking for in very less amount of time. For more information and similar apps, visit apksall.
[https://www.apksall.com/](url)
[https://www.apksall.com/download-sniffies-apk/](url)

**Comment by apksall-creator** [comment]
The GBWhatApp APK is an updated version of WhatsApp. It consists all the features provided by the original WhatsApp along with many more. For more information and similar apps, visit apksall.
[https://www.apksall.com/gbwhatsapp-apk-download-latest-version/](url)
[https://www.apksall.com/](url)

**Comment by apksall-creator** [comment]
The Lulubox APK is an application for gamers that want to achieve a greater gaming reach. It is one of the best applications for aspiring gamers. For more information and similar apps, visit apksall.
https://www.apksall.com/lulubox-latest-apk/
https://www.apksall.com/

**Comment by apksall-creator** [comment]
The Google pay APK is a safe and secure app designed by Google to manage your bank accounts and payments. For more information and similar apps, visit apksall.
https://www.apksall.com/google-pay-apk/
https://www.apksall.com/

**Comment by apksall-creator** [comment]
Moj apk is an entertainment app just like TikTok. If you are a short video content creator and love to share your short videos with the public then the Moj apk app will make you happy. For more information and similar apps, visit apksall.
https://www.apksall.com/moj-app-apk/
https://www.apksall.com/

**Comment by apksall-creator** [comment]
Zao is a face-swapping app that helps to change the person’s face in the video with your face or other people’s face. You can create all kinds of ‘deep fakes’ that are fairly realistic with the app’s help. For more information and similar apps, visit apksall.
https://www.apksall.com/zao-app-apk/
https://www.apksall.com/

**Comment by apksall-creator** [comment]
SnackVideo is an Asian social network video application, similar to TIKTOK where you can post your video and can follow others users. This APK is the newest app for short funny videos, where you can post short videos ,and can swipe up to watch other videos and if you do not like any video can just swipe to new video.
For more information and similar apps, visit apksall.
https://www.apksall.com/snackvideo-apk/
https://www.apksall.com/

**Comment by hennyhoney** [comment]
Hello, I am also facing the same issue
Here is the link
http://carromapk.com/

**Comment by georgedenial** [comment]
Well I was working on a clients project and faced the same issue. 
I am not sure If its safe to share the link here.
The Link in given below. 
https://carrompoolapk.com[https://carrompoolapk.com](url)

**Comment by georgedenial** [comment]
> Is there any idea what to do?


Same Issue with me. 
The Link in given below.
https://carrompoolapk.com/
