### ISSUE TITLE
Cant decode apk

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#195]
Original [issue 84](https://code.google.com/p/android-apktool/issues/detail?id=84) created by fpadia30 on 2010-08-24T11:50:17.000Z:

> <b>What steps will reproduce the problem?</b>
> 1. Trying to decode an apk with apktool d &lt;apk file name&gt; &lt;target dir&gt;
> <b>2.</b>
> <b>3.</b>

<b>What is the expected output? What do you see instead?</b>
expect to see decoded apk. I see:
Exception in thread &quot;main&quot; brut.androlib.AndrolibException: brut.directory.DirectoryException: java.util.zip.ZipException: error in opening zip file
    at brut.androlib.ApkDecoder.hasSources(Unknown Source)
    at brut.androlib.ApkDecoder.decode(Unknown Source)
    at brut.apktool.Main.cmdDecode(Unknown Source)
    at brut.apktool.Main.main(Unknown Source)
Caused by: brut.directory.DirectoryException: java.util.zip.ZipException: error in opening zip file
    at brut.directory.ZipRODirectory.&lt;init&gt;(Unknown Source)
    at brut.directory.ZipRODirectory.&lt;init&gt;(Unknown Source)
    at brut.androlib.res.util.ExtFile.getDirectory(Unknown Source)
    ... 4 more
Caused by: java.util.zip.ZipException: error in opening zip file
    at java.util.zip.ZipFile.open(Native Method)
    at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:131)
    at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:148)
    ... 7 more

<b>What version of the product are you using? On what operating system?</b>
using apktool 1.3.1

<b>Please provide any additional information below.</b>
I dont have much knowledge of java coding so it may well be because I dont have the right thing installed. any help with be appreciated.

Thanks

**Comment by Sadox04** [comment]
Hi!!
When I use apktool I write this comand on terminal "apktool d -f -r test.apk" 
and it show me this :
I: Using Apktool 2.2.2 on test.apk
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: java.util.zip.ZipException: error in opening zip file
	at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:272)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:96)
	at brut.apktool.Main.cmdDecode(Main.java:166)
	at brut.apktool.Main.main(Main.java:81)
Caused by: brut.directory.DirectoryException: java.util.zip.ZipException: error in opening zip file
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:55)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:38)
	at brut.directory.ExtFile.getDirectory(ExtFile.java:51)
	at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:270)
	... 3 more
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:53)
	... 6 more
and I think that java is installed correctly 
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)
Any suggestion?
Thanks in advence!!!

**Comment by Her0Mark** [comment]
I have the same issue
