### ISSUE TITLE
Could not decode XML while decompiling aar

### ISSUE THREAD

**Issue by nic-vera** [iBotPeaches/Apktool#1956]
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.4
2. **Operating System (Mac, Linux, Windows)** - Mac
3. **APK From? (Playstore, ROM, Other)** - .aar sdk from vendor

### Stacktrace/Logcat

apktool d polaris-sdk.aar 
```
I: Using Apktool 2.3.4 on polaris-sdk.aar
I: Decoding AndroidManifest.xml with only framework resources...
Exception in thread "main" brut.androlib.AndrolibException: Could not decode XML
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:147)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:153)
	at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:155)
	at brut.androlib.res.AndrolibResources.decodeManifest(AndrolibResources.java:158)
	at brut.androlib.Androlib.decodeManifestFull(Androlib.java:116)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:133)
	at brut.apktool.Main.cmdDecode(Main.java:164)
	at brut.apktool.Main.main(Main.java:73)
Caused by: java.io.IOException: Expected: 0x00080003, got: 0x6d783f3c
	at brut.util.ExtDataInput.skipCheckInt(ExtDataInput.java:48)
	at brut.androlib.res.decoder.AXmlResourceParser.doNext(AXmlResourceParser.java:855)
	at brut.androlib.res.decoder.AXmlResourceParser.next(AXmlResourceParser.java:102)
	at brut.androlib.res.decoder.AXmlResourceParser.nextToken(AXmlResourceParser.java:112)
	at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.nextToken(XmlPullParserDelegate.java:105)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:140)
	... 7 more
```
### Steps to Reproduce
1. apktool d polaris-sdk.aar 

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

https://www.dropbox.com/s/i2apsfaornk74kp/polaris-sdk.aar?dl=0

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? no
3. Are you using the latest apktool version? yes

**Comment by iBotPeaches** [comment]
I don't know what the proper format of aar files are, or even if Apktool supports them. In this case, Apktool correctly determine that it couldn't find a `resources.arsc` file, so it went to a manual (framework) decode of the Manifest file and thus failed.

However, the `AndroidManifest.xml` file is a plain text in this aar. It didn't need to be decoded, because it wasn't AXML. Along with all the files in the `/res` folder that were also plain-text (XML). So Apktool isn't needed. Just unzip and use these files.

Closing.

**Comment by nic-vera** [comment]
Thanks for the response Connor. If I do as you suggested and unzip the lib and add a view to a layout the id of the layout will not be available to look up the view handle, for example R.id.addedView
