### ISSUE TITLE
Error trying to rename device in settings after recompiling Settings.apk MiuiPro 8.11.8

### ISSUE THREAD

**Issue by gss200610** [iBotPeaches/Apktool#1963]
### Information
1. **Apktool Version (`apktool -version`)** -
apktool-2.3.4.jar ,  apktool-2.2.1-93a51c-SNAPSHOT.jar, apktool-3.0.9-bz-small.jar
2. **Operating System (Mac, Linux, Windows)** -
Ubuntu 18.10
3. **APK From? (Playstore, ROM, Other)** -
Miui Pro 8.11.8
### Stacktrace/Logcat
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.android.settings.SubSettings}: android.view.InflateException: Binary XML file line #4: Binary XML file line #4: Error inflating class <unknown>
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2487)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2547)
	at android.app.ActivityThread.access$1100(ActivityThread.java:151)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:157)
	at android.app.ActivityThread.main(ActivityThread.java:5603)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
Caused by: android.view.InflateException: Binary XML file line #4: Binary XML file line #4: Error inflating class <unknown>
	at android.view.LayoutInflater.inflate(LayoutInflater.java:543)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
	at com.android.settings.MiuiDeviceNameEditFragment.a(MiuiDeviceNameEditFragment.java:29)
	at com.android.settings.BaseFragment.onInflateView(BaseFragment.java:72)
	at com.miui.internal.app.FragmentDelegate.onCreateView(SourceFile:137)
	at miui.app.Fragment.onCreateView(SourceFile:62)
	at android.app.Fragment.performCreateView(Fragment.java:2220)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:973)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1130)
	at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1955)
	at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:152)
	at android.app.Activity.performCreateCommon(Activity.java:6349)
	at android.app.Activity.performCreate(Activity.java:6357)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2440)
	... 9 more
Caused by: android.view.InflateException: Binary XML file line #4: Error inflating class <unknown>
	at android.view.LayoutInflater.createView(LayoutInflater.java:649)
	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:698)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:766)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:708)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:839)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
	... 24 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance(Native Method)
	at android.view.LayoutInflater.createView(LayoutInflater.java:623)
	... 31 more
Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x8
	at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:668)
	at android.view.View.<init>(View.java:3986)
	at com.miui.internal.variable.v21.Android_View_View_class.handle_init_(SourceFile:41)
	at android.view.ViewGroup.<init>(ViewGroup.java:574)
	at com.miui.internal.variable.v21.Android_View_ViewGroup_class.handle_init_(SourceFile:70)
	at android.widget.LinearLayout.<init>(LinearLayout.java:203)
	at android.widget.LinearLayout.<init>(LinearLayout.java:199)
	at android.widget.LinearLayout.<init>(LinearLayout.java:195)
	... 33 more
```

### Steps to Reproduce
1. `apktool -xxx -d Settings.apkk
2 - apktool-xxx b Setting, apktool-xxx b Setting -aapt ./aapt , apktool-xxx b Setting -aapt ./aapt_miui_v7

### Frameworks
framework-res.apk
framework-ext-res.apk
miui.apk
MiuiSystemUI.apk

If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
yes
2. If you are trying to install a modified apk, did you resign it?
no
3. Are you using the latest apktool version?
too

I can compile apk without error after correcting string error -values-bg, values-el, but when trying to rename the device apk closes unexpectedly

**Comment by iBotPeaches** [comment]
MIUI isn't officially supported due to the massive amount of resource changes they make. You want to look towards this error
```
Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x8
	at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:668)
```
There is a resource/attribute somewhere that was incorrectly decoded or set to an invalid value.
