### ISSUE TITLE
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: file must be a directory

### ISSUE THREAD

**Issue by SamHoque** [iBotPeaches/Apktool#1970]
### Information
1. **Apktool Version (`apktool -version`)** - 2.3.4
2. **Operating System (Mac, Linux, Windows)** - Windows 10
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat

```
I: Using Apktool 2.3.4 on kik.android-15.2.0.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: file must be a directory: Decompiled-Apks\kik.android-15.2.0.apk
    at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:221)
    at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:136)
    at brut.androlib.ApkDecoder.decode(ApkDecoder.java:122)
    at brut.apktool.Main.cmdDecode(Main.java:164)
    at brut.apktool.Main.main(Main.java:73)
Caused by: brut.directory.DirectoryException: file must be a directory: Decompiled-Apks\kik.android-15.2.0.apk
    at brut.directory.FileDirectory.<init>(FileDirectory.java:38)
    at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:201)
    ... 4 more
```

### Steps to Reproduce
1. `decompile apk`
2. `decompile apk again`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.  https://play.google.com/store/apps/details?id=kik.android&hl=en

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Yes
3. Are you using the latest apktool version? Yes

Side not: I don't think this is apk depended, This happens when apktool tries to delete the already decompiled apk before decompiling again. I have a really high end PC, I doubt it has anything to do with my PC.

**Comment by iBotPeaches** [comment]
```
➜  Bug1970 apktool d Kik_v15.2.0.18651_apkpure.com.apk 
I: Using Apktool 2.4.0-f997e0-SNAPSHOT on Kik_v15.2.0.18651_apkpure.com.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/connortumbleson/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug1970 apktool b Kik_v15.2.0.18651_apkpure.com
I: Using Apktool 2.4.0-f997e0-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
W: warning: string 'kinecosystem_info_menu' has no default translation.
W: warning: string 'privacy_control_turn_on_direct_messages_format' has no default translation.
I: Copying libs... (/lib)
I: Copying libs... (/kotlin)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
➜  Bug1970 
```

No issue on linux. Will check with Windows

**Comment by iBotPeaches** [comment]
This now has a warning message.

```
➜  2100 apktool d com.ing.mobile_2020230001.apk 
Destination directory (/home/ibotpeaches/Downloads/Apktool/2100/com.ing.mobile_2020230001) already exists. Use -f switch if you want to overwrite it.
➜  2100 
```

Closing

**Comment by Zubair2019** [comment]
Check the permission of the destination directory
