### ISSUE TITLE
Error  

### ISSUE THREAD

**Issue by seisdr** [iBotPeaches/Apktool#1986]
### Information
1. **Apktool Version (`apktool -version`)** -
2. **Operating System (Mac, Linux, Windows)** -
3. **APK From? (Playstore, ROM, Other)** -

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by seisdr** [comment]
Which details you want

**Comment by iBotPeaches** [comment]
None. This isn't a bug.

**Comment by seisdr** [comment]
lol check this 
https://transfer.sh/wlfXZ/Screenshot_2019-01-12-22-42-11.png

**Comment by seisdr** [comment]
in past I was able to decompile apk over termux now I can't 
Is there anything changes?

**Comment by seisdr** [comment]
also here 
```
$ apktool b  .
I: Using Apktool 2.2.0-Black
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
Exception in thread "main" brut.androlib.AndrolibException: java.io.IOException: No such file or directory
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:473)
        at brut.androlib.Androlib.buildResources(Androlib.java:407)
        at brut.androlib.Androlib.build(Androlib.java:306)
        at brut.androlib.Androlib.build(Androlib.java:263)
        at brut.apktool.Main.cmdBuild(Main.java:224)
        at brut.apktool.Main.main(Main.java:84)
Caused by: java.io.IOException: No such file or directory
        at java.io.UnixFileSystem.createFileExclusively(Native Method)
        at java.io.File.createTempFile(File.java:2024)
        at java.io.File.createTempFile(File.java:2070)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:452)
        ... 5 more
```
