### ISSUE TITLE
compile source code fail

### ISSUE THREAD

**Issue by mrxuenhong** [iBotPeaches/Apktool#1987]
### Information
I didn't change any code, but when compile the code, comes up many test cases fail information.

### Stacktrace/Logcat

Include stacktrace here
brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 4198400): [C:\Users\RESET\AppData\Local\Temp\brut_util_Jar_7157469869184026244.tmp, p, --forced-package-id, 127, --no-version-vectors, -F, C:\Users\RESET\AppData\Local\Temp\APKTOOL2705690849498025460.tmp, -0, arsc, -0, arsc, -S, C:\Users\RESET\AppData\Local\Temp\BRUT8327745448690514948.tmp\issue1594-new\res, -M, C:\Users\RESET\AppData\Local\Temp\BRUT8327745448690514948.tmp\issue1594-new\AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:503)
	at brut.androlib.Androlib.buildResources(Androlib.java:426)
	at brut.androlib.Androlib.build(Androlib.java:305)
	at brut.androlib.aapt1.AndroidOreoNotSparseTest.beforeClass(AndroidOreoNotSparseTest.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:106)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 4198400): [C:\Users\RESET\AppData\Local\Temp\brut_util_Jar_7157469869184026244.tmp, p, --forced-package-id, 127, --no-version-vectors, -F, C:\Users\RESET\AppData\Local\Temp\APKTOOL2705690849498025460.tmp, -0, arsc, -0, arsc, -S, C:\Users\RESET\AppData\Local\Temp\BRUT8327745448690514948.tmp\issue1594-new\res, -M, C:\Users\RESET\AppData\Local\Temp\BRUT8327745448690514948.tmp\issue1594-new\AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aapt1Package(AndrolibResources.java:581)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:604)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:481)
	... 43 more
Caused by: brut.common.BrutException: could not exec (exit code = 4198400): [C:\Users\RESET\AppData\Local\Temp\brut_util_Jar_7157469869184026244.tmp, p, --forced-package-id, 127, --no-version-vectors, -F, C:\Users\RESET\AppData\Local\Temp\APKTOOL2705690849498025460.tmp, -0, arsc, -0, arsc, -S, C:\Users\RESET\AppData\Local\Temp\BRUT8327745448690514948.tmp\issue1594-new\res, -M, C:\Users\RESET\AppData\Local\Temp\BRUT8327745448690514948.tmp\issue1594-new\AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:98)
	at brut.androlib.res.AndrolibResources.aapt1Package(AndrolibResources.java:577)
	... 45 more

### Steps to Reproduce
gradlew.bat build shadowJar --info >compile_fail_log.txt

### Questions to ask before submission
Could you help figure out what cause the compile error? 

The full compile logs are attached.

Thanks a lot!

[compile_fail_log.txt](https://github.com/iBotPeaches/Apktool/files/2760101/compile_fail_log.txt)
[test.zip](https://github.com/iBotPeaches/Apktool/files/2760103/test.zip)

**Comment by iBotPeaches** [comment]
Windows is currently broken. See #1975
