### ISSUE TITLE
Failing to decode resource

### ISSUE THREAD

**Issue by sebras** [iBotPeaches/Apktool#1990]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.0-261e16-SNAPSHOT
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - [Xiaomi store](http://app.mi.com)

### Stacktrace/Logcat

```
I: Using Apktool 2.4.0-261e16-SNAPSHOT on com.autonavi.minimap.apk
I: Loading resource table...
W: Multiple types detected! attr ignored!
W: Multiple types detected! attr ignored!
W: Multiple types detected! drawable ignored!
W: Multiple types detected! layout ignored!
W: Multiple types detected! style ignored!
W: Multiple types detected! id ignored!
Exception in thread "main" brut.androlib.AndrolibException: Invalid chunk type: expected=0x00000200, got=0x00000203
        at brut.androlib.res.decoder.ARSCDecoder.checkChunkType(ARSCDecoder.java:542)
        at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:88)
        at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:82)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:48)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:748)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:67)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:59)
        at brut.androlib.Androlib.getResTable(Androlib.java:68)
        at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:228)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:118)
        at brut.apktool.Main.cmdDecode(Main.java:164)
        at brut.apktool.Main.main(Main.java:73)
```

### Steps to Reproduce
`apktool d com.autonavi.minimap.apk`

### Frameworks
This APK is not from an OEM ROM.

### APK
* [Xiaomi store page](http://app.mi.com/details?id=com.autonavi.minimap)
* [Xiaomi store download link](http://app.mi.com/download/1338) 

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
Yes, the very first step fails.
2. If you are trying to install a modified apk, did you resign it?
No, the APK has not been modified.
3. Are you using the latest apktool version?
Yes, the very latest I can get from git, 29355f876dc1383bd7d7a8f0840aa36840e73063.

A brief analysis appears to show that the resource starts with [RES_TABLE_LIBRARY_TYPE](https://android.googlesource.com/platform/frameworks/base/+/master/libs/androidfw/include/androidfw/ResourceTypes.h#237) but apktool expects [RES_TABLE_PACKAGE_TYPE](https://android.googlesource.com/platform/frameworks/base/+/master/libs/androidfw/include/androidfw/ResourceTypes.h#234) at this location.

I have not yet delved into how the [aapt source code](https://android.googlesource.com/platform/frameworks/base/+/master/tools/aapt) actually create these resources so I have no proposed patch.

**Comment by iBotPeaches** [comment]
I wonder if this has anything to do with the recent patch you made here? https://github.com/iBotPeaches/Apktool/issues/1976

My thought process is this application is getting further along the process and crashing in a different location.

**Comment by sebras** [comment]
Even if the source of the .apk is the same, Xiaomi store, we are talking about different apks. So it is not immediately obvious that these issues are related. Since I don't understand what was the cause of the .apk to look like it did in #1976, I can't be sure whether the same has happened to this file. Perhaps there is some tool that Xiaomi runs on all of their apps and it misbehaves sometimes?

**Comment by iBotPeaches** [comment]
Xiaomi does more and more stuff, I wouldn't be surprised if they did.

**Comment by sebras** [comment]
I did notice that Google Play Store also carried [the app](https://play.google.com/store/apps/details?id=com.autonavi.minimap). I'll get that one and see if it has the same issues.

**Comment by sebras** [comment]
I can verify that apktool has no issues with that Google Play Store version of the apk.

**Comment by abdihaikal** [comment]
Is there anything to do with ProGuard, obfuscated-codes, and multi dex? (Just one of my assumption)

**Comment by omeh2003** [comment]
In [Imo](https://play.google.com/store/apps/details?id=com.imo.android.imoim)  similar error: 
```
Exception in thread "main" brut.androlib.AndrolibException: Invalid chunk type: expected=0x00000200, got=0x00000203
        at brut.androlib.res.decoder.ARSCDecoder.checkChunkType(ARSCDecoder.java:542)
        at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:88)
        at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:82)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:48)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:747)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:67)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:59)
        at brut.androlib.Androlib.getResTable(Androlib.java:68)
        at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:236)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:118)
        at brut.apktool.Main.cmdDecode(Main.java:170)
        at brut.apktool.Main.main(Main.java:76)
```
2.4.1-c4e227-SNAPSHOT

**Comment by iBotPeaches** [comment]
Closing as duplicate - https://github.com/iBotPeaches/Apktool/issues/2099

**Comment by hierarchicall** [comment]
use this apktool: https://4pda.ru/forum/index.php?showtopic=557858&st=7400#entry102370162

mirror 1: https://www.sendspace.com/file/23yb7o

mirror 2: https://www.mediafire.com/file/nzeansvuhsxytgk/apktool_2.5.1-6d4e503_tilks_2020-12-08.jar/file

**Comment by sebras** [comment]
@hierarchicall 
> use this apktool: https://4pda.ru/forum/index.php?showtopic=557858&st=7400#entry102370162

Do you mind linking to the patch you've made instead of the compiled .jar file?
I try to avoid downloading and running binaries from random forums. :)

**Comment by iBotPeaches** [comment]
> use this apktool: https://4pda.ru/forum/index.php?showtopic=557858&st=7400#entry102370162
> 
> mirror 1: x
> 
> mirror 2: x

I redacted the binaries. I don't really like binaries posted as we can't see the source associated with it, source changes and PRs are appreciated though. I know the author of that build has put up a few that I'm grateful for. Still debating the latest which I see is a feature on that build.

**Comment by hierarchicall** [comment]
I am not the developer of this patch. But this solution helped me.

**Comment by iBotPeaches** [comment]
> I am not the developer of this patch. But this solution helped me.

That is good, but we exist in a kinda sketchy world these days. Your GitHub account is quite empty and new, you don't look recognized in this repo and your comments are just copy pasted into multiple threads to "try this binary and provide multiple links to the download like you are expecting them to be taken offline"

All in all, it looks extremely sketchy like you are trying to infect the crowd here with something. You may be perfectly innocent and just trying to help, but I've been burned many many times by the alternative.
