### ISSUE TITLE
Error decoding apk with latest java version

### ISSUE THREAD

**Issue by KaustubhPatange** [iBotPeaches/Apktool#1999]
The latest Java update **1.8.0_191** shows error while decompiling any apk. I was trying Apktool version **2.3.4** to decompile my [Quick Url](https://play.google.com/store/apps/details?id=com.kpstv.quickurl) with java **1.8.0_191** installed and this following exception occurred.

```
C:\Users\Dell\Documents\Visual Studio 2017>apktool d quickurl.apk -f
I: Using Apktool 2.3.3 on quickurl.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Dell\AppData\Local\apktool\framework\1.ap k
I: Regular manifest package...
Exception in thread "main" com.sun.org.apache.xml.internal.serializer.utils.W rappedRuntimeException: Could not load the propery file 'output_xml.properties' for output method 'xml' (check CLASSPATH)
at com.sun.org.apache.xml.internal.serializer.OutputP ropertiesFactory.getDefaultMethodProperties(Unknow n Source)
at com.sun.org.apache.xalan.internal.xsltc.trax.Trans formerImpl.setDefaults(Unknown Source)
at com.sun.org.apache.xalan.internal.xsltc.trax.Trans formerImpl.createOutputProperties(Unknown Source)
at com.sun.org.apache.xalan.internal.xsltc.trax.Trans formerImpl.<init>(Unknown Source)
at com.sun.org.apache.xalan.internal.xsltc.trax.Trans formerImpl.<init>(Unknown Source)
at com.sun.org.apache.xalan.internal.xsltc.trax.Trans formerFactoryImpl.newTransformer(Unknown Source)
at brut.androlib.res.xml.ResXmlPatcher.saveDocument(R esXmlPatcher.java:298)
at brut.androlib.res.xml.ResXmlPatcher.removeManifest Versions(ResXmlPatcher.java:221)
at brut.androlib.res.AndrolibResources.decodeManifest WithResources(AndrolibResources.java:215)
at brut.androlib.Androlib.decodeManifestWithResources (Androlib.java:136)
at brut.androlib.ApkDecoder.decode(ApkDecoder.java:12 2)
at brut.apktool.Main.cmdDecode(Main.java:164)
at brut.apktool.Main.main(Main.java:73)

```

However when I try using old java version for eg: **1.8.1_122** it decompiles like a charm. What is the cause of this issue?

**Comment by iBotPeaches** [comment]
Have you tried restarting your computer?

This looks related to some JVM updating as per Hadoop tickets - http://permalink.gmane.org/gmane.comp.java.hadoop.hbase.user/38331

**Comment by iBotPeaches** [comment]
Yeah can't duplicate this on windows. I think its an environment issue.
