### ISSUE TITLE
Multiple resources Exception on framework-res.apk from Motorola Pie ROM

### ISSUE THREAD

**Issue by milankragujevic** [iBotPeaches/Apktool#2026]
### Information
1. **Apktool Version (`apktool -version`)** -2.4.0-dirty
2. **Operating System (Mac, Linux, Windows)** -Windows
3. **APK From? (Playstore, ROM, Other)** -ROM

### Stacktrace/Logcat

```
I: Using Apktool 2.4.0-dirty on framework-res.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Multiple resources: spec=0x0104002d string/HD_call_creteria, config=-mcc310-mnc00
        at brut.androlib.res.data.ResType.addResource(ResType.java:66)
        at brut.androlib.res.data.ResType.addResource(ResType.java:55)
        at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:315)
        at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:260)
        at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:175)
        at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:131)
        at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:82)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:48)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:748)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:67)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:59)
        at brut.androlib.Androlib.getResTable(Androlib.java:68)
        at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:228)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:118)
        at brut.apktool.Main.cmdDecode(Main.java:167)
        at brut.apktool.Main.main(Main.java:76)
```

### Steps to Reproduce
1. `java -jar apktool-cli-all.jar d framework-res.apk `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

N/A

### APK
If this APK can be freely shared, please upload/attach a link to it.

http://51.15.181.24/public/framework-res.apk

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? N/A
2. If you are trying to install a modified apk, did you resign it? N/A
3. Are you using the latest apktool version? Yes, built 2.4.0 from source

**Comment by iBotPeaches** [comment]
Yep my bad here. Left the ticket for a year, link is dead (thats on me) and these are usually just a simple qualifier check. Closing since I can't really do anything here.

Thanks for following template n such, sorry dropped the ball.
