### ISSUE TITLE
NullPointerException decoding Gboard 8.2.2

### ISSUE THREAD

**Issue by Skylled** [iBotPeaches/Apktool#2063]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.0
2. **Operating System (Mac, Linux, Windows)** - Linux & Windows
3. **APK From? (Playstore, ROM, Other)** - Play Store

### Stacktrace/Logcat

```S: WARNING: Could not write to (/home/skull/.local/share/apktool/framework), using /tmp instead...
S: Please be aware this is a volatile directory and frameworks could go missing, please utilize --frame-path if the default storage directory is unavailable
Exception in thread "main" java.lang.NullPointerException
        at org.xmlpull.renamed.MXSerializer.writeElementContent(MXSerializer.java:1016)
        at org.xmlpull.renamed.MXSerializer.text(MXSerializer.java:848)
        at org.xmlpull.v1.wrapper.classic.XmlSerializerDelegate.text(XmlSerializerDelegate.java:98)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:226)
        at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:83)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:141)
        at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(ResStreamDecoderContainer.java:33)
        at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:135)
        at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:120)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:258)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:131)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:124)
        at brut.apktool.Main.cmdDecode(Main.java:164)
        at brut.apktool.Main.main(Main.java:73)
```

### Steps to Reproduce
1. `apktool d com.google.android.inputmethod.latin_8.2.2.244669451-beta-arm64-v8a.apk`

### APK
https://www.apkmirror.com/apk/google-inc/gboard/gboard-8-2-2-244669451-release/gboard-the-google-keyboard-8-2-2-244669451-beta-arm64-v8a-android-apk-download/

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? N/A
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
Confirmed
