### ISSUE TITLE
Error copying file: assets

### ISSUE THREAD

**Issue by evildog1** [iBotPeaches/Apktool#2082]
### Information
1. **Apktool Version** 2.4.0
2. **Operating System** Windows 10
3. **APK From?** https://www.apkmonk.com/app/com.geico.mobile/

### Stacktrace/Logcat

```
I: Using Apktool 2.4.0 on com.geico.mobile_2019-05-11.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
S: WARNING: Could not write to (C:\Users\quocd\AppData\Local\apktool\framework), using C:\Users\quocd\AppData\Local\Temp\ instead...
S: Please be aware this is a volatile directory and frameworks could go missing, please utilize --frame-path if the default storage directory is unavailable
I: Loading resource table from file: C:\Users\quocd\AppData\Local\Temp\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Copying assets and libs...
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: Error copying file: assets
	at brut.androlib.Androlib.decodeRawFiles(Androlib.java:160)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:171)
	at brut.apktool.Main.cmdDecode(Main.java:167)
	at brut.apktool.Main.main(Main.java:76)
Caused by: brut.directory.DirectoryException: Error copying file: assets
	at brut.directory.DirUtil.copyToDir(DirUtil.java:91)
	at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:208)
	at brut.androlib.Androlib.decodeRawFiles(Androlib.java:147)
	... 3 more
Caused by: brut.directory.DirectoryException: Error copying file: ?	 
	at brut.directory.DirUtil.copyToDir(DirUtil.java:88)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:61)
	at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:198)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:77)
	... 5 more
Caused by: java.io.FileNotFoundException: E:\APK Easy Tool\1-Decompiled APKs\com.geico.mobile_2019-05-11\assets\?	  (Syntaksen i filnavnet, mappen eller diskenhedsnavnet er forkert)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:84)
	... 8 more

```

### Steps to Reproduce
1. `apktool d -f -o "E:\com.geico.mobile_2019-05-11" 
 "E:\com.geico.mobile_2019-05-11.apk"`

### Frameworks
No

### APK
https://www.apkmonk.com/app/com.geico.mobile/

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? No. App isn't fully decompiled due to error
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
Looks like a known issue on Windows. Some un-renderable characters, which during the phase of writing is unable to complete on Windows. It works on linux and produces some strange filenames.

```
    24392  2019-05-09 09:04   assets/тАБ^I 
     1082  2019-05-09 09:04   assets/ADBMobileConfig.json
       16  2019-05-09 09:04   assets/тАЖтБЯтАЖ
      348  2019-05-09 09:04   assets/crashlytics-build.properties
```

Looks intentional. Existing ticket for mapping is #1460, closing as duplicate.
