### ISSUE TITLE
cannot successfully decompile apk

### ISSUE THREAD

**Issue by ghost** [iBotPeaches/Apktool#2100]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.0 / 2.3.0
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - https://apkpure.co/ing-bankieren

```
C:\Users\Admin\AppData\Local\JDownloader v2.0\jre\bin>java.exe -jar apktool_2.4.0.jar d -f com.ing.mobile_30450100.apk
I: Using Apktool 2.4.0 on com.ing.mobile_30450100.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
S: WARNING: Could not write to (C:\Users\Admin\AppData\Local\apktool\framework), using C:\Users\Admin\AppData\Local\Temp\ instead...
S: Please be aware this is a volatile directory and frameworks could go missing, please utilize --frame-path if the default storage directory is unavailable
I: Loading resource table from file: C:\Users\Admin\AppData\Local\Temp\1.apk
I: Regular manifest package...
I: Decoding file-resources...
Exception in thread "main" java.lang.NullPointerException
        at brut.androlib.res.decoder.AXmlResourceParser.getNonDefaultNamespaceUri(AXmlResourceParser.java:312)
        at brut.androlib.res.decoder.AXmlResourceParser.getAttributeNamespace(AXmlResourceParser.java:299)
        at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeNamespace(XmlPullParserDelegate.java:176)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
        at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:84)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:142)
        at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(ResStreamDecoderContainer.java:33)
        at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:141)
        at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:121)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:258)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:131)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:124)
        at brut.apktool.Main.cmdDecode(Main.java:167)
        at brut.apktool.Main.main(Main.java:76)

C:\Users\Admin\AppData\Local\JDownloader v2.0\jre\bin>

C:\Users\Admin\AppData\Local\JDownloader v2.0\jre\bin>java.exe -jar apktool_2.3.0.jar d -f com.ing.mobile_30450100.apk
I: Using Apktool 2.3.0 on com.ing.mobile_30450100.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
S: WARNING: Could not write to (C:\Users\Admin\AppData\Local\apktool\framework), using C:\Users\Admin\AppData\Local\Temp\ instead...
S: Please be aware this is a volatile directory and frameworks could go missing, please utilize --frame-path if the default storage directory is unavailable
I: Loading resource table from file: C:\Users\Admin\AppData\Local\Temp\1.apk
I: Regular manifest package...
I: Decoding file-resources...
S: Could not decode file, replacing by FALSE value: ??á
S: Could not decode file, replacing by FALSE value: ???
S: Could not decode file, replacing by FALSE value: ? ?
S: Could not decode file, replacing by FALSE value: ???
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

C:\Users\Admin\AppData\Local\JDownloader v2.0\jre\bin>
```
I need to decompile/recompile to change minSdkVersion from 21 to 19 
With 2.4.0 I cannot decompile it at all. With 2.3.0, it can be decompiled but with some corrupted xml's.

**Comment by iBotPeaches** [comment]
No NPE on decode anymore.

```
➜  2100 apktool d com.ing.mobile_2020230001.apk 
I: Using Apktool 2.4.2-f545c2-SNAPSHOT on com.ing.mobile_2020230001.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
➜  2100 
```

Closing as resolved.
