### ISSUE TITLE
Issues when decompiling APK (framework-res.apk)

### ISSUE THREAD

**Issue by GodcraftPlata** [iBotPeaches/Apktool#2103]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.0
2. **Operating System (Mac, Linux, Windows)** - Windows 10 x64
3. **APK From? (Playstore, ROM, Other)** - ROM (Moto E5 Plus, Stock, 8.0)

### Stacktrace/Logcat

```
I: Using Apktool 2.4.0 on framework-res.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Multiple resources: spec=0x0104002a string/HD_call_creteria, config=-mcc310-mnc00
        at brut.androlib.res.data.ResType.addResource(ResType.java:66)
        at brut.androlib.res.data.ResType.addResource(ResType.java:55)
        at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:315)
        at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:260)
        at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:175)
        at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:131)
        at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:82)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:48)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:748)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:67)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:59)
        at brut.androlib.Androlib.getResTable(Androlib.java:68)
        at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:228)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:118)
        at brut.apktool.Main.cmdDecode(Main.java:167)
        at brut.apktool.Main.main(Main.java:76)
```

### Steps to Reproduce
1. `apktool d framework-res.apk`

[APK File](http://www.mediafire.com/file/h317qsy338782ea/framework-res.apk/file)

**Comment by Dunedan** [comment]
Same issue with the attached APK from stock Moto G7 Play Android 9.0 ROM as well (using `apktool` 2.4.0 under Linux).

[framework-res.zip](https://github.com/iBotPeaches/Apktool/files/4189889/framework-res.zip)

**Comment by ModHatter6811** [comment]
@Dunedan 

I have the same device Moto G7 Play (xt1952-4), and I found a workaround. Open the apk with a zip editor and delete the assets folder. Then try to decompile. If it throws an error, sign the app with a test signature then try again. I can't remember if I had to sign it or not, but you definitely have to delete the assets folder to make it work.

**Comment by GodcraftPlata** [comment]
> @Dunedan
> 
> I have the same device Moto G7 Play (xt1952-4), and I found a workaround. Open the apk with a zip editor and delete the assets folder. Then try to decompile. If it throws an error, sign the app with a test signature then try again. I can't remember if I had to sign it or not, but you definitely have to delete the assets folder to make it work.

No, you don't need to do that. I found a solution.

Just use `apktool -advance d -k framework-res.apk`

**Comment by dingshaohua-com** [comment]
> > [@Dunedan](https://github.com/Dunedan)
> > 我有同样的 Moto G7 Play (xt1952-4) 设备，我找到了一个解决方法。用 zip 编辑器打开 apk 文件，删除 assets 文件夹。然后尝试反编译。如果出现错误，请使用测试签名对应用进行签名，然后重试。我不记得是否需要签名，但肯定需要删除 assets 文件夹才能使其正常工作。
> 
> 不，你不需要这么做。我找到了解决办法。
> 
> 只需使用`apktool -advance d -k framework-res.apk`
```
apktool.jar -advance d -k xxx.apk
[Java ERR]: Unrecognized command: -advance
```
