### ISSUE TITLE
ApkTool Java problem

### ISSUE THREAD

**Issue by Sadox04** [iBotPeaches/Apktool#2108]
Hi!!
When I use apktool to sign an apk file, I write this comand on terminal "apktool d -f -r test.apk"
and it show me this :
```
I: Using Apktool 2.2.2 on test.apk
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: java.util.zip.ZipException: error in opening zip file
at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:272)
at brut.androlib.ApkDecoder.decode(ApkDecoder.java:96)
at brut.apktool.Main.cmdDecode(Main.java:166)
at brut.apktool.Main.main(Main.java:81)
Caused by: brut.directory.DirectoryException: java.util.zip.ZipException: error in opening zip file
at brut.directory.ZipRODirectory.(ZipRODirectory.java:55)
at brut.directory.ZipRODirectory.(ZipRODirectory.java:38)
at brut.directory.ExtFile.getDirectory(ExtFile.java:51)
at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:270)
... 3 more
Caused by: java.util.zip.ZipException: error in opening zip file
at java.util.zip.ZipFile.open(Native Method)
at java.util.zip.ZipFile.(ZipFile.java:225)
at java.util.zip.ZipFile.(ZipFile.java:155)
at java.util.zip.ZipFile.(ZipFile.java:169)
at brut.directory.ZipRODirectory.(ZipRODirectory.java:53)
... 6 more
```
and I think that java is installed correctly
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)
Any suggestion?
Thanks in advence!!!

**Comment by iBotPeaches** [comment]
Can't replicate this and you are using a very old build of Apktool (2+ years old). So closing as non-reproducible.
