### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by lt82654993** [iBotPeaches/Apktool#2111]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** -  https://www.douyin.com

### Stacktrace/Logcat

```
Include stacktrace here
Exception in thread "main" java.lang.NullPointerException
	at brut.androlib.res.data.value.ResEnumAttr.serializeBody(ResEnumAttr.java:61)
	at brut.androlib.res.data.value.ResAttr.serializeToResValuesXml(ResAttr.java:64)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:704)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:263)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:131)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:124)
	at brut.apktool.Main.cmdDecode(Main.java:168)
	at brut.apktool.Main.main(Main.java:77)
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?  `apktool d`
2. If you are trying to install a modified apk, did you resign it?  Yes
3. Are you using the latest apktool version?  Yes

**Comment by ktnrg45** [comment]
I get this error as well. Debian Stretch ARM64, Java = openjdk version "1.8.0_212"

**Comment by ktnrg45** [comment]
NVM I was using Version 2.2.1

**Comment by iBotPeaches** [comment]
Sorry for the delay. I just triaged another issue that matches this one. I know this one was submitted before, but the other has apk and already triaged.

So closing this one as duplicate against - https://github.com/iBotPeaches/Apktool/issues/2146
