### ISSUE TITLE
getting stuck at signing the apk with latest kodi 18.3.apk

### ISSUE THREAD

**Issue by twisted-fire-starter** [iBotPeaches/Apktool#2116]
### Information
1. **Apktool Version (`2.4.0`)** -
2. **Operating System (Windows)** -
3. **APK From? (Other :- Kodi website)** -

### Stacktrace/Logcat

Key "fladnag" password for signer #1: 
Failed to load signer "signer #1"
java.io.IOException: Failed to obtain key with alias "fladnag" from D:\MSI\Documents\APK Easy Tool\fladnag.keystore. Wrong password?
	at com.android.apksigner.ApkSignerTool$SignerParams.loadPrivateKeyAndCertsFromKeyStore(ApkSignerTool.java:803)
	at com.android.apksigner.ApkSignerTool$SignerParams.loadPrivateKeyAndCerts(ApkSignerTool.java:663)
	at com.android.apksigner.ApkSignerTool$SignerParams.access$500(ApkSignerTool.java:615)
	at com.android.apksigner.ApkSignerTool.sign(ApkSignerTool.java:269)
	at com.android.apksigner.ApkSignerTool.main(ApkSignerTool.java:89)
Caused by: java.security.UnrecoverableKeyException: Cannot recover key
	at sun.security.provider.KeyProtector.recover(KeyProtector.java:315)
	at sun.security.provider.JavaKeyStore.engineGetKey(JavaKeyStore.java:141)
	at sun.security.provider.JavaKeyStore$JKS.engineGetKey(JavaKeyStore.java:56)
	at sun.security.provider.KeyStoreDelegator.engineGetKey(KeyStoreDelegator.java:96)
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineGetKey(JavaKeyStore.java:70)
	at java.security.KeyStore.getKey(KeyStore.java:1023)
	at com.android.apksigner.ApkSignerTool$SignerParams.getKeyStoreKey(ApkSignerTool.java:855)
	at com.android.apksigner.ApkSignerTool$SignerParams.loadPrivateKeyAndCertsFromKeyStore(ApkSignerTool.java:788)
	... 4 more

```
### Steps to Reproduce
1. `apktool compiles ok and then gets stuck at signing the latest kodi 18.3.apk.`

### APK
https://kodi.tv/download

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? no unable to resign it
3. Are you using the latest apktool version? yes

**Comment by iBotPeaches** [comment]
Apktool doesn't have a signing tool. I think you have the wrong repo here.
