### ISSUE TITLE
Error: Unable to rebuild apk with apktool

### ISSUE THREAD

**Issue by king-ckm007** [iBotPeaches/Apktool#2123]
```
Exception in thread "main" org.jf.util.ExceptionWithContext: Exception occurred while writing code_item for method Landroid/support/v4/util/LongSparseArray;->clone()Landroid/support/v4/util/LongSparseArray;
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:917)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:341)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:297)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:61)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:36)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:419)
	at brut.androlib.Androlib.buildSources(Androlib.java:350)
	at brut.androlib.Androlib.build(Androlib.java:302)
	at brut.androlib.Androlib.build(Androlib.java:269)
	at brut.apktool.Main.cmdBuild(Main.java:247)
	at brut.apktool.Main.main(Main.java:79)
Caused by: org.jf.util.ExceptionWithContext: Error while writing instruction at code offset 0x13
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1190)
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:913)
	... 10 more
Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65544
	at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
	at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:356)
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1150)
	... 11 more
Error: Unable to rebuild apk with apktool
```

**Comment by iBotPeaches** [comment]
You have too many methods. The max value of an unsigned short is 65,535. You have 65,544. This is not a bug.

**Comment by VENUROCKS** [comment]
how to fix that too many method ,would you help
