### ISSUE TITLE
Can't decompile an apk on "Loading resource table..." process

### ISSUE THREAD

**Issue by H0rUsGoD** [iBotPeaches/Apktool#2136]
I don't know but it can be an obfuscated apk?

### Information
1. **Apktool Version (`apktool -version`)** - 2.4.0
2. **Operating System (Mac, Linux, Windows)** - Windows 10
3. **APK From? (Playstore, ROM, Other)** - Playstore(but i downloaded from ApkPure)

### Stacktrace/Logcat

```
I: Using Apktool 2.4.0 on autoguidovie.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Multiple resources: spec=0x7f070013 string/common_google_play_services_enable_button, config=-sr
        at brut.androlib.res.data.ResType.addResource(ResType.java:66)
        at brut.androlib.res.data.ResType.addResource(ResType.java:55)
        at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:315)
        at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:260)
        at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:175)
        at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:131)
        at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:82)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:48)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:748)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:67)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:59)
        at brut.androlib.Androlib.getResTable(Androlib.java:68)
        at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:228)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:118)
        at brut.apktool.Main.cmdDecode(Main.java:167)
        at brut.apktool.Main.main(Main.java:76)
```

### Steps to Reproduce
apktool d autoguidovie.apk

### APK
https://apkpure.com/it/autoguidovie/net.pluservice.Autoguidovie

**Comment by iBotPeaches** [comment]
```
➜  2136 apktool d Autoguidovie_v7.7.0_apkpure.com.apk 
I: Using Apktool 2.4.2-f545c2-SNAPSHOT on Autoguidovie_v7.7.0_apkpure.com.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
➜  2136 
```

Sorry for delay. I can't replicate on latest.
