### ISSUE TITLE
Package Id mismatch when decoding an APK with dynamic feature

### ISSUE THREAD

**Issue by benjaminRomano** [iBotPeaches/Apktool#2140]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.0
2. **Operating System (Mac, Linux, Windows)** - Mac
3. **APK From? (Playstore, ROM, Other)** - Locally built APK

```
I: Loading resource table from file: /var/folders/vr/qld59qyn19x565jfw9k1n6mr0000gq/T/127.apk
Exception in thread "main" brut.androlib.AndrolibException: Expected pkg of id: 127, got: 126
	at brut.androlib.res.AndrolibResources.loadFrameworkPkg(AndrolibResources.java:132)
	at brut.androlib.res.data.ResTable.getPackage(ResTable.java:84)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:67)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:63)
	at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferenceValue.java:62)
	at brut.androlib.res.data.value.ResReferenceValue.encodeAsResXml(ResReferenceValue.java:48)
	at brut.androlib.res.data.value.ResScalarValue.encodeAsResXmlValue(ResScalarValue.java:58)
	at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:78)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:704)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:263)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:131)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:124)
	at brut.apktool.Main.cmdDecode(Main.java:167)
	at brut.apktool.Main.main(Main.java:76)
```

### Steps to Reproduce
1. `apktool d <apk>`

I unfortunately cannot provide the APK is there any debugging information I can provide to help triage this issue?

**Comment by iBotPeaches** [comment]
> I unfortunately cannot provide the APK is there any debugging information I can provide to help triage this issue?

Unfortunately not. Due to the complexity of issues and time shortage it just isn't possible to investigate. You are welcome to investigate and put forward a fix however :)
