### ISSUE TITLE
Error "Exception in thread "main" brut.androlib.AndrolibException:"On windows

### ISSUE THREAD

**Issue by htq110219891** [iBotPeaches/Apktool#2150]
### Information
1. **Apktool Version (`apktool -version`)** -2.4.0
2. **Operating System (Mac, Linux, Windows)** -windows
3. **APK From? (Playstore, ROM, Other)** -playstore

### Stacktrace/Logcat
```
I: Using Apktool 2.4.0 on gdzzyb.apk
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: java.util.zip.ZipException: error in opening zip file
	at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:307)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:103)
	at brut.apktool.Main.cmdDecode(Main.java:167)
	at brut.apktool.Main.main(Main.java:76)
Caused by: brut.directory.DirectoryException: java.util.zip.ZipException: error in opening zip file
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:55)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:38)
	at brut.directory.ExtFile.getDirectory(ExtFile.java:52)
	at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:305)
	... 3 more
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:53)
	... 6 more
```

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://www.taptap.com/app/134346

**Comment by iBotPeaches** [comment]
I can't seem to download a binary from that location. Do you have another uploaded area I can take a look at?

**Comment by yankarinRG** [comment]
I see the user hasn't yet replied, and since I'm having the **exact same issue**, [here](https://mega.nz/#!NU5kEKjD!qNmxucGFgVK_r_OUjheeN9dWDludKLNMl7rX2EohLt4)'s the file I'm trying to decompile, which comes from MIUI.

**Comment by iBotPeaches** [comment]
> The file you are trying to download is no longer available.

Sorry I never got to it. Closing.
