### ISSUE TITLE
zip END header not found

### ISSUE THREAD

**Issue by abhay-channe** [iBotPeaches/Apktool#2173]
### Information
1. **Apktool Version (`apktool -version`)** - Apktool 2.4.0
2. **Operating System (Mac, Linux, Windows)** - Linux (Debian)
3. **APK From? (Playstore, ROM, Other)** - Other

### Stacktrace/Logcat

```
$sudo apktool d -f -r -o testApk test.apk
I: Using Apktool 2.4.0 on test.apk
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: java.util.zip.ZipException: zip END header not found
	at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:307)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:103)
	at brut.apktool.Main.cmdDecode(Main.java:167)
	at brut.apktool.Main.main(Main.java:76)
Caused by: brut.directory.DirectoryException: java.util.zip.ZipException: zip END header not found
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:55)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:38)
	at brut.directory.ExtFile.getDirectory(ExtFile.java:52)
	at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:305)
	... 3 more
Caused by: java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1535)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1436)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1443)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1274)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1237)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:844)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:191)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:53)
	... 6 more

```

### Steps to Reproduce
1. apktool d -f -r -o testApk test.apk

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
    Yes
2. If you are trying to install a modified apk, did you resign it? 
    NA
3. Are you using the latest apktool version? 
    Yes

**Comment by iBotPeaches** [comment]
Hmm corrupted file? Haven't seen this before and without APK - can't investigate.

**Comment by Katabii** [comment]
Hello! I've had the same problem and in my case it was because I had the apk corrupted. I tried to copy the original apk again and I managed to solve the problem.
