### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by AhmadKahlid** [iBotPeaches/Apktool#2184]
### Information
1. **Apktool Version (`apktool -version`)** -2.4.0
2. **Operating System (Mac, Linux, Windows)** -Mac 10.14.6
3. **APK From? (Playstore, ROM, Other)** -Other

### Stacktrace/Logcat

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.myapp, PID: 18270
    java.lang.NoClassDefFoundError: Failed resolution of: Lo/ιɨ;
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1173)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2708)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.ClassNotFoundException: o.ιɨ
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.newInstance(Native Method) 
        at android.app.Instrumentation.newActivity(Instrumentation.java:1173) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2708) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lo/Κ;
        at java.lang.Class.newInstance(Native Method) 
        at android.app.Instrumentation.newActivity(Instrumentation.java:1173) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2708) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "o.Κ" on path: DexPathList[[zip file "/data/app/com.myapp-7AZevSvPG9qTJDYH49CXGQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.myapp-7AZevSvPG9qTJDYH49CXGQ==/lib/x86, /data/app/com.myapp-7AZevSvPG9qTJDYH49CXGQ==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.newInstance(Native Method) 
        at android.app.Instrumentation.newActivity(Instrumentation.java:1173) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2708) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
```

### Steps to Reproduce
`$ apktool d -r myappV1.0.8.apk`
`I: Using Apktool 2.4.0 on myappV1.0.8.apk`
`I: Copying raw resources...`
`I: Baksmaling classes.dex...`
`I: Baksmaling classes2.dex...`
`I: Copying assets and libs...`
`I: Copying unknown files...`
`I: Copying original files...`
`$ apktool b myappV1.0.8`
`I: Using Apktool 2.4.0`
`I: Checking whether sources has changed...`
`I: Smaling smali folder into classes.dex...`
`I: Checking whether sources has changed...`
`I: Smaling smali_classes2 folder into classes2.dex...`
`I: Checking whether resources has changed...`
`I: Copying raw resources...`
`I: Copying libs... (/lib)`
`I: Copying libs... (/kotlin)`
`I: Building apk file...`
`I: Copying unknown files/dir...`
`I: Built apk...`

### APK
https://drive.google.com/open?id=1BI4U2iO3IiJKeCHexCb1TTrzEfQ06pJY

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Yes
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
Not sure. Looks source related and I updated v2.5.0 to use latest smali/baksmali v2.4.0. So give that a shot on release. If not, might have to upstream this to smali project.
