### ISSUE TITLE
java.lang.IllegalArgumentException: the salt parameter must not be empty

### ISSUE THREAD

**Issue by bphown** [iBotPeaches/Apktool#2197]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.0
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.naturalmotion.csrracing, PID: 31118
    java.lang.IllegalArgumentException: the salt parameter must not be empty
        at javax.crypto.spec.PBEKeySpec.<init>(PBEKeySpec.java:118)
        at com.google.android.vending.licensing.a.<init>(Unknown Source:36)
        at com.google.android.vending.expansion.downloader.impl.DownloaderService$b.run(Unknown Source:44)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7000)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
```

### Steps to Reproduce
1. `apktool d com.naturalmotion.csrracing-5.0.1.apk`
2. `apktool b com.naturalmotion.csrracing-5.0.1`
3. Install it on an android 8 device and it will crash

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Yes
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
The stacktrace is entirely Android/PlayStore. I'd recommend decompiling app, building/decompiling again and comparing those in some diff tool. It will help spot mistakes Apktool made, otherwise this looks like anti-tamper behavior.
