### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by PrinceAnuj7** [iBotPeaches/Apktool#2216]
### Information
1. **Apktool Version (`apktool -version`)** -
2. **Operating System (Mac, Linux, Windows)** -
3. **APK From? (Playstore, ROM, Other)** -

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?
# apktool d /root/uc.apk
I: Using Apktool 2.4.0-dirty on uc.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /root/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
Exception in thread "main" java.lang.IllegalArgumentException: bad utf-8 byte 00 at offset 0000411d
	at org.jf.util.Utf8Utils.throwBadUtf8(Utf8Utils.java:284)
	at org.jf.util.Utf8Utils.utf8BytesWithUtf16LengthToString(Utf8Utils.java:210)
	at org.jf.dexlib2.dexbacked.BaseDexReader.readString(BaseDexReader.java:611)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile.getString(DexBackedDexFile.java:261)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile.getType(DexBackedDexFile.java:276)
	at org.jf.dexlib2.dexbacked.DexBackedClassDef.getType(DexBackedClassDef.java:98)
	at org.jf.dexlib2.base.reference.BaseTypeReference.compareTo(BaseTypeReference.java:59)
	at org.jf.dexlib2.base.reference.BaseTypeReference.compareTo(BaseTypeReference.java:38)
	at com.google.common.collect.NaturalOrdering.compare(NaturalOrdering.java:35)
	at com.google.common.collect.NaturalOrdering.compare(NaturalOrdering.java:26)
	at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.base/java.util.TimSort.sort(TimSort.java:220)
	at java.base/java.util.Arrays.sort(Arrays.java:1441)
	at com.google.common.collect.Ordering.sortedCopy(Ordering.java:860)
	at org.jf.baksmali.Baksmali.disassembleDexFile(Baksmali.java:58)
	at org.jf.baksmali.Baksmali.disassembleDexFile(Baksmali.java:48)
	at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:83)
	at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:38)
	at brut.androlib.Androlib.decodeSourcesSmali(Androlib.java:98)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:147)
	at brut.apktool.Main.cmdDecode(Main.java:167)
	at brut.apktool.Main.main(Main.java:76)

**Comment by iBotPeaches** [comment]
This will be resolved in next release. It was already fixed: https://github.com/JesusFreke/smali/issues/688

and Apktool v2.4.1 has smali 2.3.4
