### ISSUE TITLE
Exception in thread "main" java.lang.AssertionError: Unable to configure default providers

### ISSUE THREAD

**Issue by qidiso** [iBotPeaches/Apktool#2236]
when i use command:
`apktool b dirname
I: Using Apktool 2.3.4
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...`

Exception in thread "main" java.lang.AssertionError: Unable to configure default providers
        at sun.security.jca.Providers.<clinit>(Providers.java:74)
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:156)
        at java.security.Security.getImpl(Security.java:628)
        at java.security.MessageDigest.getInstance(MessageDigest.java:197)
        at org.jf.dexlib2.writer.DexWriter.updateSignature(DexWriter.java:287)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:277)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:246)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:61)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:36)
        at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:419)
        at brut.androlib.Androlib.buildSources(Androlib.java:350)
        at brut.androlib.Androlib.build(Androlib.java:302)
        at brut.androlib.Androlib.build(Androlib.java:269)
        at brut.apktool.Main.cmdBuild(Main.java:238)
        at brut.apktool.Main.main(Main.java:76)
how i can solve this ?? pls ....

**Comment by qidiso** [comment]
i run in the termux and  my android version is :android Q(android 10)

**Comment by iBotPeaches** [comment]
I can't replicate this. Looks to me like Apktool is running on something non-standard that doesn't have needed environment security related classes.

The template was wiped anyway, so can't see OS to triage.

Closing.
