### ISSUE TITLE
Building error: Resource entry already has bag item

### ISSUE THREAD

**Issue by cyagit** [iBotPeaches/Apktool#2240]
Sorry if this covered already. Thanks for taking a look into this.

### Information
1. **Apktool Version** - (`Apktool 2.4.1-b05f19-SNAPSHOT`)
2. **Operating System** - (`Linux`)
3. **APK From?** - (`built from source`)

### Stacktrace/Logcat

```
java -jar apktool-cli-all.jar b Dialer
I: Using Apktool 2.4.1-b05f19-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: /abc/testapk/Dialer/res/values/styles.xml:25: error: Resource entry AlertDialogTheme already has bag item android:textColorPrimary.
W: /abc/testapk/Dialer/res/values/styles.xml:24: Originally defined here.
W: 
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_6356615135546023705.tmp, p, --forced-package-id, 127, --min-sdk-version, 29, --target-sdk-version, 29, --version-code, 2900000, --version-name, 23.0, --no-version-vectors, -F, /tmp/APKTOOL4422094949664317222.tmp, -e, /tmp/APKTOOL1327188246627751388.tmp, -0, arsc, -I, /abc/.local/share/apktool/framework/1.apk, -S, /abc/testapk/Dialer/res, -M, /abc/testapk/Dialer/AndroidManifest.xml]

```

### Steps to Reproduce
1. `java -jar apktool-cli-all.jar d Dialer.apk`
2. `java -jar apktool-cli-all.jar b Dialer`

### Frameworks
`Lineageos 17`

### APK
[Dialer.zip](https://github.com/iBotPeaches/Apktool/files/3891519/Dialer.zip)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? - Yes
2. If you are trying to install a modified apk, did you resign it? - Does not get this far
3. Are you using the latest apktool version? - Yes

**Comment by Ticklefish** [comment]
I tried your APK with a build of apktool 2.4.1. and it compiled without that issue. I did install a framework-res.apk from AOSP first though, which might have helped.

The APK didn't recompile cleanly. I got a lot of invalid entry name warnings like this:

> "Dialer.apk\res\values\public.xml:1453: error: resource 'drawable/$asd_hd_icon__0' has invalid entry name '$asd_hd_icon__0'. Invalid character '$asd_hd_icon__0'."

This isn't an apktool issue - it's the way the APK's been put together by the developer.

**Comment by cyagit** [comment]
I see. Yes, might be a framework-specific problem. I tried a few and couldn't get it to work. Which framework-res.apk did you use to recompile?

**Comment by Ticklefish** [comment]
It's from an AOSP build of Android 10. You can download it from here: [https://www.androidfilehost.com/?fid=4349826312261650364](url)

**Comment by cyagit** [comment]
> It's from an AOSP build of Android 10. You can download it from here: [https://www.androidfilehost.com/?fid=4349826312261650364](url)

Thanks. That's interesting. I can't even use that framework apk.

Get this error:
’’’’I: Loading resource table from file: /android/.local/share/apktool/framework/AOSP10.apk
Exception in thread "main" brut.androlib.AndrolibException: Could not load resources.arsc from file: /android/.local/share/apktool/framework/AOSP10.apk
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:793)
	at brut.androlib.res.AndrolibResources.loadFrameworkPkg(AndrolibResources.java:123)
	at brut.androlib.res.data.ResTable.getPackage(ResTable.java:84)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:67)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:63)
	at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferenceValue.java:62)
	at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:55)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:742)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:263)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:129)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:124)
	at brut.apktool.Main.cmdDecode(Main.java:170)
	at brut.apktool.Main.main(Main.java:76)
Caused by: brut.directory.DirectoryException: java.util.zip.ZipException: zip file is empty
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:55)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:38)
	at brut.directory.ExtFile.getDirectory(ExtFile.java:52)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:783)
	... 12 more
Caused by: java.util.zip.ZipException: zip file is empty
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:53)
	... 15 more’’’’

Which version of Apktool do you use? Or might this be a Java version problem? Which version do you use for Java?

**Comment by Ticklefish** [comment]
I'm using apktool 2.4.1 (and it works with 2.3.0 as well) and I'm on Java 8 build 201.

**Comment by cyagit** [comment]
Ok, thanks for your support. I just can't get it to work (tried different apktool and java versions) and will build the Dialer from source instead.

**Comment by XMB5** [comment]
Add `--use-aapt2` to the build command, for example `apktool b --use-aapt2 Dialer -o out.apk`

**Comment by danivit** [comment]
> Add `--use-aapt2` to the build command, for example `apktool b --use-aapt2 Dialer -o out.apk`

Great! it worked: you saved my day. Thanks ;-)

**Comment by miaotaoii** [comment]
succeed!  I trid use apktool jar 2.6.1 and added --use-aapt2 to command "apktool b ",it worked
