### ISSUE TITLE
Decompiling error: Invalid chunk type

### ISSUE THREAD

**Issue by disco-mayhem** [iBotPeaches/Apktool#2249]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.0/2.4.1
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Other (website)

### Stacktrace/Logcat

```
PS C:\Users\User\Documents\android\apktool> ./apktool d 1415.apk
I: Using Apktool 2.4.1 on 1415.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Invalid chunk type: expected=0x00000200, got=0x00000203
        at brut.androlib.res.decoder.ARSCDecoder.checkChunkType(ARSCDecoder.java:542)
        at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:88)
        at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:82)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:48)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:786)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:67)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:59)
        at brut.androlib.Androlib.getResTable(Androlib.java:66)
        at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:236)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:118)
        at brut.apktool.Main.cmdDecode(Main.java:170)
        at brut.apktool.Main.main(Main.java:76)
Press any key to continue . . .
```

### APK
https://apkpure.com/tiktok-musically/com.zhiliaoapp.musically

### Question
Is there any solution to the problem? Can I manually patch an APK file to avoid this error?

**Comment by iBotPeaches** [comment]
Hmm, `0x203` is LIBRARY if my memory is right. I thought our ARSC parser was smart enough to just read chunk, identify chunk, parse chunk. So this should not be happening.

**Comment by CesarTrigo** [comment]
Hi @iBotPeaches,
we are facing exactly the same error with another APK:

**Exception in thread "main" brut.androlib.AndrolibException: Invalid chunk type: expected=0x00000200, got=0x00000203**
```
➜  test java -jar apktool_2.4.1.jar -f d prod.apk  -m -s -o output/prod
I: Using Apktool 2.4.1 on prod.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Invalid chunk type: expected=0x00000200, got=0x00000203
	at brut.androlib.res.decoder.ARSCDecoder.checkChunkType(ARSCDecoder.java:542)
	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:88)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:82)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:48)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:786)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:67)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:59)
	at brut.androlib.Androlib.getResTable(Androlib.java:66)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:236)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:118)
	at brut.apktool.Main.cmdDecode(Main.java:170)
	at brut.apktool.Main.main(Main.java:76)
```
Do you have any update?
Thank you in adavance,
C.

**Comment by 1azunna** [comment]
Have you fixed this? @iBotPeaches

**Comment by iBotPeaches** [comment]
@1azunna not yet.

**Comment by victorvhpg** [comment]
same here

**Comment by poveu** [comment]
Same issue with this old task.
Is this tool still maintained?
@iBotPeaches

**Comment by iBotPeaches** [comment]
> Same issue with this old task.
> Is this tool still maintained?
> @iBotPeaches

Yes.

**Comment by poveu** [comment]
Great to hear @iBotPeaches 😎

**Comment by sadachi** [comment]
issue still remains with this Gym App..

https://play.google.com/store/apps/details?id=com.technogym.mywellness&hl=en_US&gl=US

**Comment by AndnixSH** [comment]
Same with mobile legends, they just applied same protection. I wonder if it's related to Andresguard protection because i heard about it

https://apkcombo.com/en-dk/mobile-legends-bang-bang/com.mobile.legends/download/apk

**Comment by iBotPeaches** [comment]
Closing as duplicate - https://github.com/iBotPeaches/Apktool/issues/2099

**Comment by jokerart06** [comment]
> Same with mobile legends, they just applied same protection. I wonder if it's related to Andresguard protection because i heard about it
> 
> https://apkcombo.com/en-dk/mobile-legends-bang-bang/com.mobile.legends/download/apk

hope author will add this on his fix list. thank you

**Comment by iBotPeaches** [comment]
> > Same with mobile legends, they just applied same protection. I wonder if it's related to Andresguard protection because i heard about it
> > https://apkcombo.com/en-dk/mobile-legends-bang-bang/com.mobile.legends/download/apk
> 
> hope author will add this on his fix list. thank you

Added into my local folder for bug 2099.

**Comment by hierarchicall** [comment]
use this apktool: https://4pda.ru/forum/index.php?showtopic=557858&st=7400#entry102370162

mirror 1: https://www.sendspace.com/file/23yb7o

mirror 2: https://www.mediafire.com/file/nzeansvuhsxytgk/apktool_2.5.1-6d4e503_tilks_2020-12-08.jar/file

**Comment by ducheharsh** [comment]
Bro, u might have pasted the .bin and .jar file in the windows folder and using another version

**Comment by Nogias9x** [comment]
Since 2.5.1 has not released, I worked-around with this tutorial. Hope it helps someone.
https://platinmods.com/threads/how-to-fix-apktool-decompile-error-using-mt-manager-app-arscdecoder-error.121708/

**Comment by AndnixSH** [comment]
@Nogias9x you can download unstable build here https://github.com/iBotPeaches/Apktool/actions
View latest workflow runs and click on apktool.jar inside Artifacts section (Requires a Github account to be logged in to download)

**Comment by Nogias9x** [comment]
Thank you @AndnixSH

I followed your help but no luck. This is what I did. Do you have any clue?

1. Download [the latest unstable apktool.jar.zip](https://github.com/iBotPeaches/Apktool/actions/runs/931952388)
2. Rename `apktool.jar.zip` to `apktool.jar`
3. Move `apktool.jar` to `/usr/local/bin`
4. Test by `apktool --version`
And I got `Error: Invalid or corrupt jarfile /usr/local/bin/apktool.jar`

**Comment by shroudedcode** [comment]
> Rename `apktool.jar.zip` to `apktool.jar`
> And I got `Error: Invalid or corrupt jarfile /usr/local/bin/apktool.jar`

Renaming doesn't magically turn a `.zip` file into a `.jar` file, you have to unpack it and then use the `.apk` file that's in there.

**Comment by Nogias9x** [comment]
Silly me!
Thank you so much @shroudedcode  @AndnixSH

**Comment by StingraySA** [comment]
Can confirm the new patch is working like a charm. Just compile apktool from source and all works 👍

**Comment by dimaslanjaka** [comment]
i bypass this error by

- create file `apktool-decompile.bat`
```bat
@echo off
apktool d -f -r -s %*
```
then when i want to decompile apk file
```bash
apktool-decompile namefile.apk
```
![image](https://github.com/iBotPeaches/Apktool/assets/12471057/313e2df7-85b1-4e37-8881-0c0a617cb979)
