### ISSUE TITLE
X windows problem

### ISSUE THREAD

**Issue by carr123** [iBotPeaches/Apktool#2272]
### Information
1. **Apktool Version (`apktool -version`)** -
2.3.4-dirty
2. **Operating System (Mac, Linux, Windows)** -
Ubuntu

I run apktool on an ubuntu server, which doesn't hava a GUI.
then apktool run failed.
if i open a ssh terminal to the ubuntu server from my windows client machine, apktool runs success.
if i shut down the ssh terminal, again apktool runs fail.
(apktool command is called by my program running on the ubuntu server)
below is the error info:

out:I: Using Apktool 2.3.4-dirty on 1578361944048812032.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /root/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...

errout:Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using 'localhost:10.0' as the value of the DISPLAY variable.
	at java.desktop/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
	at java.desktop/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:102)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:61)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at java.desktop/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:101)
	at java.desktop/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:83)
	at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:129)
	at java.desktop/java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1181)
	at brut.androlib.res.decoder.Res9patchStreamDecoder.decode(Res9patchStreamDecoder.java:60)
	at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(ResStreamDecoderContainer.java:33)
	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:135)
	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:93)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:258)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:131)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:124)
	at brut.apktool.Main.cmdDecode(Main.java:164)
	at brut.apktool.Main.main(Main.java:73)

**Comment by nnelas** [comment]
Hi @carr123, can you please update to latest version of apktool (2.4.1) and see if the problem still persist?

**Comment by iBotPeaches** [comment]
> I run apktool on an ubuntu server, which doesn't hava a GUI.

I run Apktool on ubuntu and centos servers. I've never experienced this. I would check your environmental settings.
