### ISSUE TITLE
Continued from #2279. Unable to decompile apps by this developer.

### ISSUE THREAD

**Issue by testesleah84** [iBotPeaches/Apktool#2280]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.1
2. **Operating System (Mac, Linux, Windows)** - Windows 10 Pro
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat

```
I: Using Apktool 2.4.1 on base2.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\chenj\AppData\Local\apktool\framework\1.apk
Exception in thread "main" java.lang.IndexOutOfBoundsException
        at java.nio.ByteBuffer.wrap(Unknown Source)
        at brut.androlib.res.decoder.StringBlock.decodeString(StringBlock.java:297)
        at brut.androlib.res.decoder.StringBlock.getString(StringBlock.java:110)
        at brut.androlib.res.decoder.AXmlResourceParser.getName(AXmlResourceParser.java:176)
        at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getName(XmlPullParserDelegate.java:57)
        at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:64)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:142)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:154)
        at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:162)
        at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:204)
        at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:134)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:122)
        at brut.apktool.Main.cmdDecode(Main.java:170)
        at brut.apktool.Main.main(Main.java:76)
```

### Steps to Reproduce
1. `apktool `d base2.apk

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://play.google.com/store/apps/details?id=com.gojek.driver.sg.car&hl=en_SG
https://apkpure.com/gojek-driver-singapore/com.gojek.driver.sg.car

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Still attempting to decompile.
2. If you are trying to install a modified apk, did you resign it? Not modified.
3. Are you using the latest apktool version? Yes

**Comment by testesleah84** [comment]
The DUMMYVAL resources and more are there to allow decode. There has been 0 success of recovering any human readable name. Android doesn't care about resource names, it cares about resource IDs. Dexguard strips the human readable name, so remaking the APK back to human readable format is nearly impossible.
