### ISSUE TITLE
Google VR Services APK fails to start after d/b

### ISSUE THREAD

**Issue by OrByR** [iBotPeaches/Apktool#2301]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.1
2. **Operating System (Mac, Linux, Windows)** - Windows 10 x64 on PC, Android 10 on phone
3. **APK From? (Playstore, ROM, Other)** - https://www.apkmirror.com/apk/google-inc/google-vr-services/google-vr-services-1-23-265693388-release/google-vr-services-1-23-265693388-2-android-apk-download/

(used with https://www.apkmirror.com/apk/google-inc/daydream-daydream/daydream-daydream-1-23-190812026-release/ and https://www.apkmirror.com/apk/google-inc/daydream-keyboard-daydream/daydream-keyboard-daydream-1-23-190812016-release/ )

### Stacktrace/Logcat
I tried to pull a logcat but ended up with 3000 lines of stuff that didn't look that helpful - if you have a suggestion to get something more specific - I will try again.
```
Include stacktrace here
Sorry I was unable to obtain.
```

### Steps to Reproduce
1. `apktool ` apktool d file /apktool b dir / sign and install. No d or b errors and -v is clear as well. Installs fine - but when you launch daydream app that hooks it - it says VR services failed to start. 

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)
N/A

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://www.apkmirror.com/apk/google-inc/google-vr-services/google-vr-services-1-23-265693388-release/google-vr-services-1-23-265693388-2-android-apk-download/

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Yes
3. Are you using the latest apktool version? Yes

If some one could duplicate my issue and confirm if I am crazy or just really screwing something up?

**Comment by peret** [comment]
I can confirm that this happens. Here's the relevant part of the logs:

```
2020-04-24 17:06:35.431 15033-15033/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.vr.vrcore, PID: 15033
    java.lang.SecurityException: GoogleCertificatesRslt: not whitelisted: pkg=com.google.vr.vrcore, sha1=9b5dc4e83df7cd8f174c3f5be31fcb3684f8a854, atk=false, ver=201216030.true (go/gsrlt)
        at android.os.Parcel.createException(Parcel.java:1950)
        at android.os.Parcel.readException(Parcel.java:1918)
        at android.os.Parcel.readException(Parcel.java:1868)
        at att.a(PG:14)
        at arz.a(PG:248)
        at apo.a(PG:29)
        at aps.run(PG:10)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at auz.run(PG:6)
        at java.lang.Thread.run(Thread.java:764)
2020-04-24 17:06:35.527 15017-15017/? W/native: commandlineflags.cc:976 Ignoring RegisterValidateFunction() for flag pointer 0xd5470d60: no flag found at that address
2020-04-24 17:06:35.541 1260-10770/? W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1005 com.android.server.am.ActivityManagerService.handleApplicationCrashInner:15582 com.android.server.am.ActivityManagerService.handleApplicationCrash:15560 android.app.IActivityManager$Stub.onTransact:116 com.android.server.am.ActivityManagerService.onTransact:3323 
2020-04-24 17:06:35.541 1260-10770/? E/ActivityManager: Sending non-protected broadcast com.arima.oem.SYSTEM_CRASH from system 1260:system/1000 pkg android
    java.lang.Throwable
        at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:21388)
        at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:21992)
        at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:22134)
        at android.app.ContextImpl.sendBroadcast(ContextImpl.java:1009)
        at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:15582)
        at com.android.server.am.ActivityManagerService.handleApplicationCrash(ActivityManagerService.java:15560)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:116)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3323)
        at android.os.Binder.execTransact(Binder.java:731)
```

Looks to me like Google is simply checking whether the APK bundle was signed with a known certificate, which, of course, it is not anymore :/

As far as I can see, there's also no way around this?

**Comment by peret** [comment]
At the very least I'm fairly sure this is not a bug in apktool, but just an issue that arises from re-signing the APK.

**Comment by iBotPeaches** [comment]
>     java.lang.SecurityException: GoogleCertificatesRslt: not whitelisted: pkg=com.google.vr.vrcore, sha1=9b5dc4e83df7cd8f174c3f5be31fcb3684f8a854, atk=false, ver=201216030.true (go/gsrlt)


This is your sad line. Many SDKs (especially Google) will cross check the sha hash of the uploaded binary when using some services. This prevents changing the APK, pushing a malformed/hacked build out and still getting the benefit of OAUTH, SDKs, etc. 

There is sadly nothing Apktool can do here. Welcome to reverse-engineering and the side-affect of signing APKs over.
