### ISSUE TITLE
Unsupported res type name, cannot get SDK version

### ISSUE THREAD

**Issue by adrianTNT** [iBotPeaches/Apktool#2310]
Using latest version `2.4.1.jar`;
With this test file: [apkfiles.com/temp/com.facebook.orca_255.0.0.14.126.apk](https://www.apkfiles.com/temp/com.facebook.orca_255.0.0.14.126.apk)
I am getting these errors, it does unpack with `--no-res` but then I see no sdk and file version in the `apktool.yml` file:
```
java -jar 'apktool_2.4.1.jar' decode 'com.facebook.orca_255.0.0.14.126.apk' -f -o 'temp/'                    I: Using Apktool 2.4.1 on com.facebook.orca_255.0.0.14.126.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: unsupported res type name for bags. Found: style2
        at brut.androlib.res.data.value.ResValueFactory.bagFactory(ResValueFactory.java:119)
        at brut.androlib.res.decoder.ARSCDecoder.readComplexEntry(ARSCDecoder.java:350)
        at brut.androlib.res.decoder.ARSCDecoder.readEntryData(ARSCDecoder.java:276)
        at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:252)
        at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:175)
        at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:131)
        at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:82)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:48)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:786)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:67)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:59)
        at brut.androlib.Androlib.getResTable(Androlib.java:66)
        at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:236)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:118)
        at brut.apktool.Main.cmdDecode(Main.java:170)
        at brut.apktool.Main.main(Main.java:76)
```
It unpacks with `--no-res` 
```
java -jar '/var/www/html/apkfiles.com/scripts/apktool_ibotpeaches/apktool_2.4.1.jar' --no-res decode 'com.facebook.orca_255.0.0.14.126.apk' -f -o '3/'
I: Using Apktool 2.4.1 on com.facebook.orca_255.0.0.14.126.apk
I: Copying raw resources...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
[...]
I: Baksmaling classes7.dex...
I: Baksmaling assets/effects/effects2.dex...
I: Baksmaling assets/instantgamesads/instantgamesads2.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Using Apktool 2.4.1 on com.facebook.orca_255.0.0.14.126.apk
I: Copying raw resources...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
[...]
I: Baksmaling classes7.dex...
I: Baksmaling assets/effects/effects2.dex...
I: Baksmaling assets/instantgamesads/instantgamesads2.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
``` 
but I **cannot get file version and sdk version**, this is the only thing I wanted to find in the `apktool.yml` file:
```
!!brut.androlib.meta.MetaInfo
apkFileName: com.facebook.orca_255.0.0.14.126.apk
compressionType: false
doNotCompress:
- assets/FBMMontageMessageInfo.fbs.md5
- assets/OmnistoreSampleContact.fbs.md5
- assets/graph_metadata.bin.xzs
- assets/qe_lookup.bin
- assets/dsp/p1000763609098242277.p
[...]
- assets/dsp/p9196765937687508663.p
- assets/lib/libs.xzs
- assets/openh264/libs.xzs
- png
- m4a
- ogg
- r/bd-.kf
- r/d0c.json.gz
- r/d66.kf
isFrameworkApk: false
packageInfo: null
sdkInfo: null
sharedLibrary: false
sparseResources: false
unknownFiles:
  firebase-common.properties: '8'
  firebase-iid-interop.properties: '8'
  firebase-iid.properties: '8'
  firebase-measurement-connector.properties: '8'
  firebase-messaging.properties: '8'
  play-services-ads-identifier.properties: '8'
  play-services-analytics-impl.properties: '8'
  play-services-analytics.properties: '8'
  play-services-auth-api-phone.properties: '8'
  play-services-auth-base.properties: '8'
  play-services-auth.properties: '8'
  play-services-base.properties: '8'
  play-services-basement.properties: '8'
  play-services-cast.properties: '8'
  play-services-drive.properties: '8'
  play-services-flags.properties: '8'
  play-services-instantapps.properties: '8'
  play-services-location.properties: '8'
  play-services-places-placereport.properties: '8'
  play-services-places.properties: '8'
  play-services-safetynet.properties: '8'
  play-services-stats.properties: '8'
  play-services-tagmanager-v4-impl.properties: '8'
  play-services-tasks.properties: '8'
  play-services-wearable.properties: '8'
usesFramework: null
version: 2.4.1
versionInfo: null
```

**Comment by iBotPeaches** [comment]
The important thing to note is this line.
```
Exception in thread "main" brut.androlib.AndrolibException: unsupported res type name for bags. Found: style2
```

That is the issue and being tracked at #1719, so closing due to duplicate. Thanks for the report.
