### ISSUE TITLE
Unable to Decompile APK

### ISSUE THREAD

**Issue by HiteshPatelD11** [iBotPeaches/Apktool#2311]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.1 and 2.4.0
2. **Operating System (Mac, Linux, Windows)** - MacOs Mojave 10.14
3. **APK From? (Playstore, ROM, Other)** - APK

### Stacktrace/Logcat

```
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/hitesh.patel/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
Exception in thread "main" java.lang.NullPointerException
	at brut.androlib.res.data.value.ResEnumAttr.serializeBody(ResEnumAttr.java:56)
	at brut.androlib.res.data.value.ResAttr.serializeToResValuesXml(ResAttr.java:64)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:742)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:263)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:129)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:124)
	at brut.apktool.Main.cmdDecode(Main.java:170)
	at brut.apktool.Main.main(Main.java:76)```


### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? - Unable to decompile
2. If you are trying to install a modified apk, did you resign it? - Unable to decompile
3. Are you using the latest apktool version? - Yes

**Comment by iBotPeaches** [comment]
Thanks for report. This has an existing issue here - https://github.com/iBotPeaches/Apktool/issues/2146

So closing this one as a duplicate. You are welcome to subscribe to the above issue for updates to it.
