### ISSUE TITLE
Ayuda! No puedo descompilar ninguna apk

### ISSUE THREAD

**Issue by josue7754** [iBotPeaches/Apktool#2332]
Buenas! Soy nuevo en el foro!

Me descargue el apktool para windows y estoy intentando descompilar una apk pero me aparece el siguiente error

Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_2155344058740848025.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 25, --version-code, 1229573400, --version-name, 12.29.57, --no-version-vectors, -F, /tmp/APKTOOL7532305205326095753.tmp, -0, arsc, -0, webp, -0, arsc, -I, /home/dylan/.local/share/apktool/framework/1.apk, -S, /home/dylan/Desktop/base/res, -M, /home/dylan/Desktop/base/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:496)
	at brut.androlib.Androlib.buildResources(Androlib.java:430)
	at brut.androlib.Androlib.build(Androlib.java:329)
	at brut.androlib.Androlib.build(Androlib.java:267)
	at brut.apktool.Main.cmdBuild(Main.java:230)
	at brut.apktool.Main.main(Main.java:83)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_2155344058740848025.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 25, --version-code, 1229573400, --version-name, 12.29.57, --no-version-vectors, -F, /tmp/APKTOOL7532305205326095753.tmp, -0, arsc, -0, webp, -0, arsc, -I, /home/dylan/.local/share/apktool/framework/1.apk, -S, /home/dylan/Desktop/base/res, -M, /home/dylan/Desktop/base/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:441)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:482)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_2155344058740848025.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 25, --version-code, 1229573400, --version-name, 12.29.57, --no-version-vectors, -F, /tmp/APKTOOL7532305205326095753.tmp, -0, arsc, -0, webp, -0, arsc, -I, /home/dylan/.local/share/apktool/framework/1.apk, -S, /home/dylan/Desktop/base/res, -M, /home/dylan/Desktop/base/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:435)
	... 6 more
He probado con diferentes versiones y nada ayuda!! 

instale el framework como 30 veces y aun lanza el mismo error ayuda!

**Comment by iBotPeaches** [comment]
Sorry. There is not enough details to go on here.
