### ISSUE TITLE
Crashes as it fails writing to home directory

### ISSUE THREAD

**Issue by Giszmo** [iBotPeaches/Apktool#2343]
### Information
1. **Apktool Version 2.4.1** -
2. **Operating System Linux** -
3. **APK From? Playstore** -

### Stacktrace/Logcat

```
Exception in thread "main" brut.androlib.AndrolibException: Can't create directory: /var/lib/tomcat8/.local/share/apktool/framework
	at brut.androlib.res.AndrolibResources.getFrameworkDir(AndrolibResources.java:982)
	at brut.androlib.res.AndrolibResources.getFrameworkApk(AndrolibResources.java:799)
	at brut.androlib.res.AndrolibResources.loadFrameworkPkg(AndrolibResources.java:119)
	at brut.androlib.res.data.ResTable.getPackage(ResTable.java:84)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:67)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:63)
	at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferenceValue.java:62)
	at brut.androlib.res.data.value.ResReferenceValue.referentIsNull(ResReferenceValue.java:73)
	at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:49)
	at brut.androlib.res.data.value.ResBagValue.serializeToResValuesXml(ResBagValue.java:42)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:742)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:263)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:129)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:124)
	at brut.apktool.Main.cmdDecode(Main.java:170)
	at brut.apktool.Main.main(Main.java:76)```
```

### Steps to Reproduce

Execute apktool from tomcat8 with no permission to write in its home directory

This is related to #1586 but it does not fall back to `/tmp/`.

**Comment by Giszmo** [comment]
So if anybody else is blocked by this, the workaround is to provide any writable folder with the `--frame-path` option.

**Comment by iBotPeaches** [comment]
I could probably enhance this logic to fallback properly. Marking as bug.

**Comment by Giszmo** [comment]
I think it should just provide a more helpful error message. Instead of stacktrace, show some "Error: Can't write to folder X. Use --frame-path option to provide a writable folder".
