### ISSUE TITLE
App crash after decompiling and building with no changes

### ISSUE THREAD

**Issue by firefinchdev** [iBotPeaches/Apktool#2344]
### Information
1. **Apktool Version (`apktool -version`)** - 2.4.1
2. **Operating System (Mac, Linux, Windows)** - macOS 10.15.4
3. **APK From? (Playstore, ROM, Other)** - Play Store(exact apk can be downloaded alternatively from https://apkpure.com/handwriter-%D1%81onverter-to-handwritten-text/com.woiandforgmail.handwriter/) I have verified hash of both play store apk and from this link and they are same. Link provided for easy download.

### Stacktrace/Logcat

```
time: 1588542376809
msg: android.content.res.Resources$NotFoundException: Resource ID #0x7f070096
stacktrace: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.woiandforgmail.handwriter/com.woiandforgmail.handwriter.main.MainActivity}: android.view.InflateException: Binary XML file line #53 in com.woiandforgmail.handwriter:layout/activity_main: Binary XML file line #53 in com.woiandforgmail.handwriter:layout/activity_main: Error inflating class com.google.android.material.bottomnavigation.BottomNavigationView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:915)
Caused by: android.view.InflateException: Binary XML file line #53 in com.woiandforgmail.handwriter:layout/activity_main: Binary XML file line #53 in com.woiandforgmail.handwriter:layout/activity_main: Error inflating class com.google.android.material.bottomnavigation.BottomNavigationView
Caused by: android.view.InflateException: Binary XML file line #53 in com.woiandforgmail.handwriter:layout/activity_main: Error inflating class com.google.android.material.bottomnavigation.BottomNavigationView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:854)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
	at com.woiandforgmail.handwriter.main.MainActivity.onCreate(MainActivity.java:100)
	at android.app.Activity.performCreate(Activity.java:7824)
	at android.app.Activity.performCreate(Activity.java:7813)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:915)
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f070096
	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:237)
	at android.content.res.Resources.getValue(Resources.java:1351)
	at androidx.appcompat.widget.ResourceManagerInternal.createDrawableIfNeeded(ResourceManagerInternal.java:176)
	at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:141)
	at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:132)
	at androidx.appcompat.content.res.AppCompatResources.getDrawable(AppCompatResources.java:104)
	at androidx.appcompat.view.menu.MenuItemImpl.getIcon(MenuItemImpl.java:505)
	at com.google.android.material.bottomnavigation.BottomNavigationItemView.initialize(BottomNavigationItemView.java:138)
	at com.google.android.material.bottomnavigation.BottomNavigationMenuView.buildMenuView(BottomNavigationMenuView.java:554)
	at com.google.android.material.bottomnavigation.BottomNavigationPresenter.updateMenuView(BottomNavigationPresenter.java:67)
	at com.google.android.material.bottomnavigation.BottomNavigationView.inflateMenu(BottomNavigationView.java:344)
	at com.google.android.material.bottomnavigation.BottomNavigationView.<init>(BottomNavigationView.java:226)
	at com.google.android.material.bottomnavigation.BottomNavigationView.<init>(BottomNavigationView.java:133)
	... 28 more
```

### Steps to Reproduce
```
unzip com.woiandforgmail.handwriter.xapk
cd output_folder
apktool d -r com.woiandforgmail.handwriter.apk
cd com.woiandforgmail.handwriter
apktool b .
After this, copy the generated apk (./dist/com.woiandforgmail.handwriter.apk) to output_folder (replacing original apk)
Perform adb install com.woiandforgmail.handwriter.apk
```

### Frameworks
Not from any OEM

### APK
https://apkpure.com/handwriter-%D1%81onverter-to-handwritten-text/com.woiandforgmail.handwriter/

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Yes
3. Are you using the latest apktool version? Yes

**Comment by firefinchdev** [comment]
There was no error while decompiling and building using apktool. The operations were successful. 
### Output for apktool d -r app.apk
```
I: Using Apktool 2.4.1 on com.woiandforgmail.handwriter.apk
I: Copying raw resources...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
```

## Output for apktool b .
```
I: Using Apktool 2.4.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
W: Unknown file type, ignoring: ./smali/.DS_Store
W: Unknown file type, ignoring: ./smali/com/.DS_Store
W: Unknown file type, ignoring: ./smali/com/anjlab/.DS_Store
W: Unknown file type, ignoring: ./smali/com/anjlab/android/.DS_Store
W: Unknown file type, ignoring: ./smali/com/anjlab/android/iab/.DS_Store
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Copying raw resources...
I: Copying libs... (/kotlin)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
```

**Comment by firefinchdev** [comment]
The generated apk crashes as soon as open from android launcher. According to stacktrace, there is some problem with resource ids, etc.

**Comment by bensh** [comment]
I have also been experiencing this, immediate app crash as soon as the resource is required. 
This is the same with or without -r flag

**Comment by iBotPeaches** [comment]
I would recommend doing a diff report between original application (zip list) and then a decoded and rebuilt application. That will narrow the search down to something that may be missing.

I don't have much time right now due to pandemic, so if you can do that investigation. That will help me. Thanks!

**Comment by firefinchdev** [comment]
Okay, will do and report back...

**Comment by tenbits** [comment]
@firefinchdev Any news on this?

**Comment by giacomoferretti** [comment]
@firefinchdev did you install the base APK only? Have you tried to install the splits too?

Assuming you used version 1.4.0, the resource id `0x7f070096` it's `ic_edit_property` and it's only contained in `config.xxxhdpi.apk`.

**Comment by helloworld10010** [comment]
> I would recommend doing a diff report between original application (zip list) and then a decoded and rebuilt application. That will narrow the search down to something that may be missing.
> 
> I don't have much time right now due to pandemic, so if you can do that investigation. That will help me. Thanks!

Be careful

**Comment by iBotPeaches** [comment]
Sorry, looks like there isn't enough information to keep this ticket after a few months of triage. Closing.

**Comment by industral** [comment]
have the same exact issue. No changes, just decompile, compile, signing, and it crashes
