### ISSUE TITLE
Dealing with long file names when decompiling

### ISSUE THREAD

**Issue by kamikazechaser** [iBotPeaches/Apktool#2372]
Could this be some obfuscuation protection to prevent decompiling? I have attached the apk. 

### Information
1. **Apktool Version (`apktool -version`)** - 2.4.1
2. **Operating System (Mac, Linux, Windows)** - Ubuntu 18.04
3. **APK From? (Playstore, ROM, Other)** - Other (Custom)

### Stacktrace/Logcat

```
I: Using Apktool 2.4.1 on latest.apk
I: Copying raw resources...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: Error copying file: META-INF
	at brut.androlib.Androlib.writeOriginalFiles(Androlib.java:243)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:183)
	at brut.apktool.Main.cmdDecode(Main.java:170)
	at brut.apktool.Main.main(Main.java:76)
Caused by: brut.directory.DirectoryException: Error copying file: META-INF
	at brut.directory.DirUtil.copyToDir(DirUtil.java:94)
	at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:208)
	at brut.androlib.Androlib.writeOriginalFiles(Androlib.java:232)
	... 3 more
Caused by: brut.directory.DirectoryException: Error copying file: services/O0OOo0oOoOoO00oOO0000OO0o0ooOO0oo0O0OO0oOOoo0O00OO.OooOoO0O0oooooo0OO0ooOOooooo00O00OO000OOOo0OOO0ooO.OoOo0000oo0oo00Oo0000OOO0OO000000oo0OOooo00oo0OoOo.oOoo00OOOoOOOo00O0oO00o0ooOOoooooooOOoO0O0OOoooooo.Oo0OoO00oOo0oOo00o00OO0O0OOo0oOOo00o0oOOO00o0OOOOO.oo0O0oOoOOoOoOoOOo0o0o0OOOoo000oOOo0OO0OO0oOoOOO0o.O0O0ooOOO0O0oo0OOOoO0O0000OOO0OooO00OO0000o0o0000O
	at brut.directory.DirUtil.copyToDir(DirUtil.java:91)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:63)
	at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:198)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:79)
	... 5 more
Caused by: java.io.FileNotFoundException: latest/original/META-INF/services/O0OOo0oOoOoO00oOO0000OO0o0ooOO0oo0O0OO0oOOoo0O00OO.OooOoO0O0oooooo0OO0ooOOooooo00O00OO000OOOo0OOO0ooO.OoOo0000oo0oo00Oo0000OOO0OO000000oo0OOooo00oo0OoOo.oOoo00OOOoOOOo00O0oO00o0ooOOoooooooOOoO0O0OOoooooo.Oo0OoO00oOo0oOo00o00OO0O0OOo0oOOo00o0oOOO00o0OOOOO.oo0O0oOoOOoOoOoOOo0o0o0OOOoo000oOOo0OO0OO0oOoOOO0o.O0O0ooOOO0O0oo0OOOoO0O0000OOO0OooO00OO0000o0o0000O (File name too long)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:87)
	... 8 more

```

### Steps to Reproduce
1. `apktool d latest.apk` (tried both --no-res --no-assets flags)

### APK
~Google Drive~ (Check comment below)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? **Yes**
2. If you are trying to install a modified apk, did you resign it? **N/A**
3. Are you using the latest apktool version? **Yes**

**Comment by Ticklefish** [comment]
I wouldn't be at all surprised..

I can't access your file though. Google Drive says:

> We're sorry. You can't access this item because it is in violation of our Terms of Service.

**Comment by kamikazechaser** [comment]
Yeah, seems like the new way of beating de-compiling. I'll leave you a copy on some backup links below. Maybe you could use it for research purposes in the future.

[Firefox send](https://send.firefox.com/download/852c46e1edfd1003/#5covreHgnH-8jhbHZ-KWQA) / [MEGA](https://mega.nz/file/gMUSwApS#XYKZELJ1QFZ9FYYFQO9xTmL9mjjABS6wL85WzkbtRQc)

**Comment by AndnixSH** [comment]
Usally open APK using Winrar/7zip (Windows) and delete the long file names from APK file should let you decompile it. Not sure what tools to use on Ubuntu.
But the dex file is protected/packed by jiagu. Need to fully unpack it

**Comment by kamikazechaser** [comment]
Yup, you are right. The dex is protected with Jiagu (Qihoo 360). I'll close this issue for now since it is outside the scope of this tool. Removal of those files break the app btw, so I am aassuming they play an important role.
