### ISSUE TITLE
An error occurs when unpacking the application

### ISSUE THREAD

**Issue by TBYoOffical** [iBotPeaches/Apktool#2405]
### Information
1. **Apktool Version (`2.4.1`)** -
2. **Operating System (Windows)** -
3. **APK From? (YoWhatsApp)** -

### Stacktrace/Logcat

```

Exception in thread "main" java.lang.ClassCastException: brut.androlib.res.data.value.ResStringValue cannot be cast to brut.androlib.res.data.value.ResIntValue
	at brut.androlib.res.data.value.ResAttr.factory(ResAttr.java:72)
	at brut.androlib.res.data.value.ResValueFactory.bagFactory(ResValueFactory.java:95)
	at brut.androlib.res.decoder.ARSCDecoder.readComplexEntry(ARSCDecoder.java:350)
	at brut.androlib.res.decoder.ARSCDecoder.readEntryData(ARSCDecoder.java:276)
	at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:252)
	at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:175)
	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:131)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:82)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:48)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:786)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:67)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:59)
	at brut.androlib.Androlib.getResTable(Androlib.java:66)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:236)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:118)
	at brut.apktool.Main.cmdDecode(Main.java:170)
	at brut.apktool.Main.main(Main.java:76)

```

### Steps to Reproduce
1. `apktool `

### APK
http://www.mediafire.com/file/d2c836enofsu0vm/YOWA.8.45F_By_FouadMODS.apk/file

**Comment by TBYoOffical** [comment]
Please, I want a solution

**Comment by iBotPeaches** [comment]
I could not reproduce this on the soon to be next release.

```
➜  2405 apktool d YOWA.8.45F_By_FouadMODS.apk 
I: Using Apktool 2.4.2-987220-SNAPSHOT on YOWA.8.45F_By_FouadMODS.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  2405 
```
