### ISSUE TITLE
[BUG v2.5.0] - NullPointerException (OS.rmdir)

### ISSUE THREAD

**Issue by enovella** [iBotPeaches/Apktool#2455]
### Information
1. **Apktool Version (`apktool -version`)** - v2.5.0
2. **Operating System (Mac, Linux, Windows)** - Linux Ubu18.04
3. **APK From? (Playstore, ROM, Other)** - https://play.google.com/store/apps/details?id=com.bt.btsport&hl=en&gl=US

### Stacktrace/Logcat

```sh
>  apktool d -f --no-src -o /tmp/ /home/edu/apks/skyuk/com.bt.btsport.apk
Exception in thread "main" java.lang.NullPointerException
	at brut.util.OS.rmdir(OS.java:41)
	at brut.util.OS.rmdir(OS.java:44)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:95)
	at brut.apktool.Main.cmdDecode(Main.java:179)
	at brut.apktool.Main.main(Main.java:82)
```

**Comment by iBotPeaches** [comment]
Thanks for the report. The first issue is an issue we are tracking here: https://github.com/iBotPeaches/Apktool/issues/1719 for those multiple duplicate res types.

The 2nd issue looks caused by first.

**Comment by iBotPeaches** [comment]
Re-opening for 2nd error and removing 1st

**Comment by iBotPeaches** [comment]
```
➜  2446 apktool d -f --no-src -o /tmp/ PlayStation\ App_v20.9.5_apkpure.com.apk 
I: Using Apktool 2.5.0 on PlayStation App_v20.9.5_apkpure.com.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying raw classes.dex file...
I: Copying raw classes2.dex file...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  2446 
```
