### ISSUE TITLE
[BUG] Directory Traversal is not allowed

### ISSUE THREAD

**Issue by amspeople** [iBotPeaches/Apktool#2465]
### Information
1. **Apktool Version (`apktool -version`)** - apktool_2.5.1_20201204
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat

```
[*] Декомпиляция huawei-health_10.1.1.312.apk
I: Using Apktool 2.5.1-dirty-20201204 on huawei-health_10.1.1.312.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: ..\bin\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes4.dex...
I: Baksmaling classes5.dex...
I: Baksmaling classes6.dex...
I: Baksmaling classes7.dex...
I: Baksmaling classes8.dex...
I: Baksmaling classes9.dex...
I: Baksmaling classes10.dex...
I: Baksmaling classes11.dex...
I: Baksmaling classes12.dex...
I: Baksmaling classes13.dex...
I: Copying assets and libs...
I: Copying unknown files...
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: Error copying file: aux
	at brut.androlib.Androlib.decodeUnknownFiles(Androlib.java:216)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:180)
	at brut.apktool.Main.cmdDecode(Main.java:179)
	at brut.apktool.Main.main(Main.java:82)
Caused by: brut.directory.DirectoryException: Error copying file: aux
	at brut.directory.DirUtil.copyToDir(DirUtil.java:94)
	at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:208)
	at brut.androlib.Androlib.decodeUnknownFiles(Androlib.java:209)
	... 3 more
Caused by: brut.common.TraversalUnknownFileException: Directory Traversal is not allowed - aux
	at brut.util.BrutIO.sanitizeUnknownFile(BrutIO.java:93)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:84)
	... 5 more
[*] ---> Ошибка декомпиляции huawei-health_10.1.1.312.apk
```

### Download: https://play.google.com/store/apps/details?id=com.huawei.health

**Comment by iBotPeaches** [comment]
Not really a bug. It is a security feature. I can see about making it a warning and ignoring the file vs dying out.

See #2201 as a duplicate.

**Comment by amspeople** [comment]
To be honest, I didn't understand how can I decompile the apk without error? At the moment I have the latest version of apktool and it cannot decompile the apk.

**Comment by iBotPeaches** [comment]
> To be honest, I didn't understand how can I decompile the apk without error? At the moment I have the latest version of apktool and it cannot decompile the apk.

Looks like you could leave Windows for a quick fix. Appears to be a reserved filename (aux) leading to your issues.
