### ISSUE TITLE
APKTOOL D tiktok_app.apk Crashes

### ISSUE THREAD

**Issue by fmresearchnovak** [iBotPeaches/Apktool#2469]
$ apktool d TikTok_v17.8.4_apkpure.com.apk 
I: Using Apktool 2.4.1 on TikTok_v17.8.4_apkpure.com.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Invalid chunk type: expected=0x00000200, got=0x00000203
        at brut.androlib.res.decoder.ARSCDecoder.checkChunkType(ARSCDecoder.java:542)
        at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:88)
        at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:82)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:48)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:786)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:67)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:59)
        at brut.androlib.Androlib.getResTable(Androlib.java:66)
        at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:236)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:118)
        at brut.apktool.Main.cmdDecode(Main.java:170)
        at brut.apktool.Main.main(Main.java:76)

$ apktool --version
2.4.1

APK obtained from here: https://apkpure.com/tiktok/com.ss.android.ugc.trill

**Comment by iBotPeaches** [comment]
Closing as duplicate - https://github.com/iBotPeaches/Apktool/issues/2099
