### ISSUE TITLE
[BUG] FileHandle not properly released

### ISSUE THREAD

**Issue by auermich93** [iBotPeaches/Apktool#2473]
### Information
1. **Apktool Version (`apktool -version`)** - 2.5.0
2. **Operating System (Mac, Linux, Windows)** - Windows, Linux
3. **APK From? (Playstore, ROM, Other)** - https://apkpure.com/rt-360/com.rt.RT360

### Stacktrace/Logcat

```
INFO: Building apk file...
Dez. 11, 2020 11:48:00 VORM. brut.androlib.Androlib buildUnknownFiles
INFO: Copying unknown files/dir...
Dez. 11, 2020 11:48:02 VORM. brut.androlib.Androlib build
INFO: Built apk...
Exception in thread "main" org.apache.commons.io.IOExceptionList: 1 exceptions: [java.io.IOException: Unable to delete file: <decoded apk path>\unknown]
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:345)
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1206)
	at <my-library code>
Caused by: java.io.IOException: Unable to delete file: <decoded apk path>\unknown
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1425)
	at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:338)
	... 2 more
Caused by: java.nio.file.FileSystemException: <decoded apk path>\unknown\publicsuffixes.gz: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.

	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:270)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
	at java.base/java.nio.file.Files.deleteIfExists(Files.java:1180)
	at org.apache.commons.io.file.DeletingPathVisitor.visitFile(DeletingPathVisitor.java:142)
	at org.apache.commons.io.file.DeletingPathVisitor.visitFile(DeletingPathVisitor.java:36)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2724)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2796)
	at org.apache.commons.io.file.PathUtils.visitFileTree(PathUtils.java:687)
	at org.apache.commons.io.file.PathUtils.deleteDirectory(PathUtils.java:328)
	at org.apache.commons.io.file.PathUtils.delete(PathUtils.java:303)
	at org.apache.commons.io.file.PathUtils.delete(PathUtils.java:280)
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1423)
	... 3 more
```

### Steps to Reproduce
I am using apktool as a 3rd party library within my code. I have updated apktool to use commons-io version 2.8.0. It remains
the same error, just the stack trace is more descriptive. I basically call `apktool b` and then try to delete the folder obtained
from calling `apktool d`. The code looks as follows:
```
Utility.buildAPK(decodedAPKPath, outputAPKFile); 
FileUtils.deleteDirectory(new File(decodedAPKPath));
```
where the build APK functionality looks as follows:
`new Androlib(apkOptions).build(new ExtFile(new File(decodedAPKPath)), outputFile);`

As you can observe from above logs, `FileUtils.deleteDirectory()` fails because another process has still  a handle/lock
on some file/folder within the folder I would like to delete. In particular, it is some file within the 'unknown' folder.
I assume `apktool b` is not properly releasing resources and thus removal fails. Maybe `buildUnknownFiles()` contains
the bug, since it touches the 'unknown' folder? This failure is not appearing with all APKs and is not Windows-specific.

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://apkpure.com/rt-360/com.rt.RT360

Thanks in advance!

**Comment by MarcMil** [comment]
You can try out whether apktool is the culprit using the java agent from Kohsuke. It is sort of an "add on" for the JVM and shows stacktraces of currently opened files. You can check after running apktool.
https://file-leak-detector.kohsuke.org/
```
java -javaagent:path/to/file-leak-detector.jar=http=19999
```
You can access the stack traces at http://127.0.0.1:19999

**Comment by auermich93** [comment]
@MarcMil: I tried to use it, both with my application and `apktool` directly. None showed any stack trace nor any open file descriptor, but the issue still remains, i.e. above mentioned stack trace appears on the console.

**Comment by MarcMil** [comment]
Hmm... Maybe some other software has the file open? A virus scanner perhaps?

**Comment by auermich93** [comment]
Good idea, but that's not the problem. I turned off the virus scanner and re-ran it. I still suspect it is the apktool, being quite sure a lock on the `unknown` folder is not properly released. The folder is generated by decoding the APK, so I don't see any other process involved.

**Comment by iBotPeaches** [comment]
I took a look and everything looks closed to me, I even ran the tool above to follow traces of opened files.

```
➜  2473 java -javaagent:file-leak-detector-1.13-jar-with-dependencies.jar -jar apktool.jar d RT\ 360_v3.1.6_apkpure.com.apk -f
File leak detector installed
I: Using Apktool 2.5.1-45c91e-SNAPSHOT on RT 360_v3.1.6_apkpure.com.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  2473 java -javaagent:file-leak-detector-1.13-jar-with-dependencies.jar -jar apktool.jar b RT\ 360_v3.1.6_apkpure.com   
File leak detector installed
I: Using Apktool 2.5.1-45c91e-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...
```
Sorry, couldn't find an issue and couldn't replicate. Closing.

**Comment by auermich93** [comment]
@iBotPeaches: I know you tried to replicate this issue, but this freaking bug gets on my nerves. Here my latest try:

```
    public void decodeAPK() {

        LOGGER.debug("Creating first tmp dir!");
        File tmp = new File("tmp");
        tmp.mkdir();

        try {
            LOGGER.debug("Deleting first tmp dir!");
            FileUtils.forceDelete(tmp);
        } catch (IOException e) {
            LOGGER.debug("Deleting first tmp dir failed!");
            throw new UncheckedIOException(e);
        }

        try {
            ApkDecoder decoder = new ApkDecoder(apkFile);
            decoder.setFrameworkDir("tmp");
            decodingOutputPath = new File(apkFile.getParent(), DEFAULT_DECODING_DIR);
            decoder.setOutDir(decodingOutputPath);
            decoder.setDecodeSources(ApkDecoder.DECODE_SOURCES_NONE);
            decoder.setForceDelete(true);
            decoder.decode();
        } catch (BrutException | IOException e) {
            LOGGER.error("Failed to decode APK file!");
        } finally {
            try {
                LOGGER.debug("Deleting second tmp dir!");
                FileUtils.forceDelete(new File("tmp"));
            } catch (IOException e) {
                LOGGER.debug("Deleting second tmp dir failed!");
                throw new UncheckedIOException(e);
            }
        }
    }
```
I had to use a different framework directory, because the default location is not available. Afterwards, I wanted to clean up the `tmp` directory. However, the clean up operation failed. To show that this is specific to `apktool`, I created another tmp directory prior to that. Here the clean up works as the following logs show:

```
21:01:31.879 [main] DEBUG de.uni_passau.fim.auermich.android_graphs.core.app.APK - Creating first tmp dir!
21:01:31.879 [main] DEBUG de.uni_passau.fim.auermich.android_graphs.core.app.APK - Deleting first tmp dir!
21:01:37.834 [main] DEBUG de.uni_passau.fim.auermich.android_graphs.core.app.APK - Deleting second tmp dir!
21:01:37.836 [main] DEBUG de.uni_passau.fim.auermich.android_graphs.core.app.APK - Deleting second tmp dir failed!
Exception in thread "main" java.io.UncheckedIOException: java.io.IOException: Cannot delete file: tmp
	at de.uni_passau.fim.auermich.android_graphs.core.app.APK.decodeAPK(APK.java:140)
	at de.uni_passau.fim.auermich.android_graphs.core.graphs.cfg.InterCFG.constructCFG(InterCFG.java:94)
	at de.uni_passau.fim.auermich.android_graphs.core.graphs.cfg.InterCFG.<init>(InterCFG.java:88)
	at de.uni_passau.fim.auermich.android_graphs.core.graphs.BaseGraphBuilder.build(BaseGraphBuilder.java:83)
	at de.uni_passau.fim.auermich.android_graphs.cli.Main.run(Main.java:221)
	at de.uni_passau.fim.auermich.android_graphs.cli.Main.main(Main.java:115)
Caused by: java.io.IOException: Cannot delete file: tmp
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1344)
Caused by: java.io.IOException: Cannot delete file: tmp

	at de.uni_passau.fim.auermich.android_graphs.core.app.APK.decodeAPK(APK.java:137)
	... 5 more
Caused by: java.nio.file.FileSystemException: tmp\1.apk: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird
Caused by: java.nio.file.FileSystemException: tmp\1.apk: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird

	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:274)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
	at java.base/java.nio.file.Files.deleteIfExists(Files.java:1185)
	at org.apache.commons.io.file.DeletingPathVisitor.visitFile(DeletingPathVisitor.java:161)
	at org.apache.commons.io.file.DeletingPathVisitor.visitFile(DeletingPathVisitor.java:37)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2804)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2876)
	at org.apache.commons.io.file.PathUtils.visitFileTree(PathUtils.java:971)
	at org.apache.commons.io.file.PathUtils.deleteDirectory(PathUtils.java:434)
	at org.apache.commons.io.file.PathUtils.delete(PathUtils.java:391)
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1341)
```
The german log just says that another process has a lock on / is still accessing the file. The final call to `decoder.decode();` must be responsible for this. One further note here. Constructing the example this way, let the bug show up in any case, while in the previous post the exception appeared now and then, and depending on the APK to be decoded.
