### ISSUE TITLE
[BUG] NullPointerException installing APK after recompiling with no changes

### ISSUE THREAD

**Issue by DroidFreak32** [iBotPeaches/Apktool#2488]
### Information
1. **Apktool Version (`apktool -version`)** - 2.5.0
2. **Operating System (Mac, Linux, Windows)** - MacOS Mojave
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat

```
12-27 18:26:28.916 27824 29070 I FA      : App measurement is starting up, version: 11910
12-27 18:26:28.916 27824 29070 I FA      : To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
12-27 18:26:28.916 27824 29070 I FA      : To enable faster debug mode event logging run:
12-27 18:26:28.916 27824 29070 I FA      :   adb shell setprop debug.firebase.analytics.app com.snapwork.hdfc
12-27 18:26:28.921 27824 29070 E FA      : AppMeasurementReceiver not registered/enabled
12-27 18:26:28.922 27824 29070 E FA      : AppMeasurementService not registered/enabled
12-27 18:26:28.922 27824 27824 I m.snapwork.hdf: The ClassLoaderContext is a special shared library.
12-27 18:26:28.922 27824 29070 E FA      : Uploading is not possible. App measurement disabled
12-27 18:26:28.944 27824 27824 V NativeCrypto: Registering com/google/android/gms/org/conscrypt/NativeCrypto's 288 native methods...
12-27 18:26:28.952 27824 27824 I ProviderInstaller: Installed default security provider GmsCore_OpenSSL
12-27 18:26:28.954 27824 27824 I BBConfigurationManager: Reading configuration from backbase/static/configs/configs_prod_ssl.json
12-27 18:26:28.960 27824 27824 I BBConfigurationManager: Configuration successfully read
12-27 18:26:28.963 27824 27824 D a       : Plugin: PersistentStorage registered
12-27 18:26:28.964 27824 27824 D a       : Plugin: EncryptedStorage registered
12-27 18:26:28.965 27824 27824 D a       : Plugin: InMemoryStorage registered
12-27 18:26:29.032 27824 27824 D AndroidRuntime: Shutting down VM
12-27 18:26:29.032 27824 27824 E AndroidRuntime: FATAL EXCEPTION: main
12-27 18:26:29.032 27824 27824 E AndroidRuntime: Process: com.snapwork.hdfc, PID: 27824
12-27 18:26:29.032 27824 27824 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {com.snapwork.hdfc/com.hdfc.retail.netbanking.HDFCBank}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.backbase.android.Backbase.a(android.content.BroadcastReceiver)' on a null object reference
12-27 18:26:29.032 27824 27824 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4206)
12-27 18:26:29.032 27824 27824 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4238)
12-27 18:26:29.032 27824 27824 E AndroidRuntime: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
12-27 18:26:29.032 27824 27824 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
12-27 18:26:29.032 27824 27824 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
12-27 18:26:29.032 27824 27824 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
12-27 18:26:29.032 27824 27824 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
12-27 18:26:29.032 27824 27824 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
12-27 18:26:29.032 27824 27824 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7398)
12-27 18:26:29.032 27824 27824 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-27 18:26:29.032 27824 27824 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
12-27 18:26:29.032 27824 27824 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
12-27 18:26:29.032 27824 27824 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.backbase.android.Backbase.a(android.content.BroadcastReceiver)' on a null object reference
12-27 18:26:29.032 27824 27824 E AndroidRuntime: 	at com.hdfc.retail.netbanking.HDFCBank.m(SourceFile:708)
12-27 18:26:29.032 27824 27824 E AndroidRuntime: 	at com.hdfc.retail.netbanking.HDFCBank.onResume(SourceFile:649)
12-27 18:26:29.032 27824 27824 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1454)
12-27 18:26:29.032 27824 27824 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:7958)
12-27 18:26:29.032 27824 27824 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4196)
12-27 18:26:29.032 27824 27824 E AndroidRuntime: 	... 11 more
12-27 18:26:29.035  1718  5659 W ActivityTaskManager:   Force finishing activity com.snapwork.hdfc/com.hdfc.retail.netbanking.HDFCBank
```

### Steps to Reproduce
1. `apktool d -r --no-assets -s APPLICATION.apk `
2. `apktool b APPLICATION -o APPLICATION_unsigned.apk` OR using aap2, same result
3. Re-sign via signapk.jar

### Frameworks
Not a framework app

### APK
If this APK can be freely shared, please upload/attach a link to it.

https://drive.google.com/uc?id=1oRpc1oDba9UAcFkWRRssiHnr_2un8H5P&export=download

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes, even with specifying 
2. If you are trying to install a modified apk, did you resign it? Did not modify. Just decompiled and recompiled
3. Are you using the latest apktool version? Yes

### Additional comments
I've looked at the other issues (Ex #2146) however thay are related to the decompiling process. In my case decompiling and recompiling has no issues whatsoever (I used the flags -r --no-assets -s to eliminate possible reasons of decompiling failures)

**Comment by pashamcr** [comment]
@DroidFreak32 - is a banking app, are you sure it is not protected against signature change?

**Comment by DroidFreak32** [comment]
@pashamcr Yeah you are right.  i did some more digging and i think they have added obfuscation and signature protection. Closing this issue.
