### ISSUE TITLE
[BUG] Native library not found on android pie

### ISSUE THREAD

**Issue by blackfa1con** [iBotPeaches/Apktool#2490]
### Information
1. **Apktool Version (`2.5.0`)** -
2. **Operating System (Linux, Windows)** -
3. **APK From? (Other)** -

### Stacktrace/Logcat

```
2021-01-01 16:25:05.626 3760-3760/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xxx.xxxx, PID: 3760
    java.lang.UnsatisfiedLinkError: dlopen failed: library "/system/priv-app/xxxx/xxxxx.apk!/lib/arm64-v8a/xxxxx.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1669)


```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
yes
2. If you are trying to install a modified apk, did you resign it?
yes
3. Are you using the latest apktool version?
 yes

**Comment by iBotPeaches** [comment]
> We find that the order when packing files into apk is important.

How did you come to this conclusion? We leverage aapt/aapt2 to package the application and if order mattered - it would do it.

**Comment by blackfa1con** [comment]
> > We find that the order when packing files into apk is important.
> 
> How did you come to this conclusion? We leverage aapt/aapt2 to package the application and if order mattered - it would do it.

When i resign the package only in windows, this break the native lib and the system give the error "dlopen failed".
then i moved to linux and used the apksigner, the error doesn't appear.

After compare the two files, original and resigned package i see the order difference.
Anyway i try to use apktool in linux, without resign package, the error back again and i can't use the new package after resign with apksigner/linux.

**Comment by Comnir** [comment]
@blackfa1con , maybe it's related to [extractNativeLibs](https://developer.android.com/studio/releases/gradle-plugin#extractNativeLibs) in AndroidManifest.xml? It is set to "false" by default since Android Gradle plugin 3.6.0.
If it's compressed by Apktool, it might be related. 

But you also say "When i resign the package only in windows, this break the native lib", so it means this problem occurs also without Apktool being involved?

**Comment by pashamcr** [comment]
@blackfa1con this is not an apktool bug
1) The application is not installed correctly in /system/priv-app, the native library can be put next to it, i.e. So:
`/system/priv-app/xxxx/lib/arm64/xxxxx.so`
2) The application is not compiled correctly for installation in /system/priv-app, add to apktool.yml:
```
doNotCompress:
- lib/arm64-v8a/xxxxx.so
```
in addition, it is desirable to include classes.dex here
