### ISSUE TITLE
[BUG] Issue faced after repackiagng the apk with baksmali/smali on my own and running "apktool d" with my new repackaged apk

### ISSUE THREAD

**Issue by SoulXHades** [iBotPeaches/Apktool#2492]
### Information
1. **Apktool Version (`apktool -version`)** - 2.5.0
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** -Other

### Stacktrace/Logcat
I: Using Apktool 2.5.0 on a.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\haoji\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
Exception in thread "main" java.lang.NullPointerException
        at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:138)
        at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:116)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:258)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:129)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:124)
        at brut.apktool.Main.cmdDecode(Main.java:179)
        at brut.apktool.Main.main(Main.java:82)

### Steps to Reproduce
1. apktool  d  a.apk

This error occurs regardless of whatever APKs I used. I previously repackaged APKs using baksmali/smali before signing and zipalign the APKs. I can install the manually repackaged APKs into the Android emulator successfully. However, if I try to disassemble those repackaged APKs using Apktool, the issue above will always occur.

**Comment by iBotPeaches** [comment]
I can't replicate with a tiny application I made and without an application to replicate from - nothing I can do here. Sorry!
