### ISSUE TITLE
Exception occurred while writing code_item for method return of #1834 - think its not #1718

### ISSUE THREAD

**Issue by beaumontk** [iBotPeaches/Apktool#2496]
### Information
1. **Apktool Version (`apktool -version`)** - 2.5.0
2. **Operating System (Mac, Linux, Windows)** - Windows 7
3. **APK From? (Playstore, ROM, Other)** - https://bitbucket.org/iBotPeaches/apktool/downloads/

### Stacktrace/Logcat

C:\kb\java_myApps\android\apktool_jadx\garmin_connect\apktool>"C:\Program Files\Java\jre1.8.0_181\bin\java.exe" -Xmx512m -jar C:\kb\apktool_2.3.4\apktool_2.5.0.jar -f b C:\kb\java_myApps\android\apktool_jadx\garmin_connect\apktool\Connect_v
4_38_1_b5720_SAP -o C:\kb\java_myApps\android\apktool_jadx\garmin_connect\apktool\KB_garmin_connect.apk
I: Using Apktool 2.5.0
I: Smaling smali folder into classes.dex...
Exception in thread "main" org.jf.util.ExceptionWithContext: Exception occurred while writing code_item for method Lk2/a/a/a/v/e/c;->values()[Lk2/a/a/a/v/e/c;
        at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1046)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:345)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:300)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:61)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:36)
        at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:420)
        at brut.androlib.Androlib.buildSources(Androlib.java:351)
        at brut.androlib.Androlib.build(Androlib.java:303)
        at brut.androlib.Androlib.build(Androlib.java:270)
        at brut.apktool.Main.cmdBuild(Main.java:259)
        at brut.apktool.Main.main(Main.java:85)
Caused by: org.jf.util.ExceptionWithContext: Error while writing instruction at code offset 0x2
        at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1319)
        at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java
:1042)
        ... 10 more
Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65536
        at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
        at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:356)
        at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1279)
        ... 11 more
---

C:\kb\java_myApps\android\apktool_jadx\garmin_connect\apktool>"C:\Program Files\Java\jre1.8.0_181\bin\java.exe" -Xmx512m -jar C:\kb\apktool_2.3.4\apktool_2.4.1.jar -f --verbose b C:\kb\java_myApps\android\apktool_jadx\garmin_connect\apktool
\Connect_v4_38_1_b5720_SAP -o C:\kb\java_myApps\android\apktool_jadx\garmin_connect\apktool\KB_garmin_connect.apk
Jan 15, 2021 1:53:20 PM brut.androlib.Androlib build
INFO: Using Apktool 2.4.1
Jan 15, 2021 1:53:21 PM brut.androlib.Androlib buildSourcesSmali
INFO: Smaling smali folder into classes.dex...
Exception in thread "main" org.jf.util.ExceptionWithContext: Exception occurred while writing code_item for method Lk2/a/a/a/v/e/c;->values()[Lk2/a/a/a/v/e/c;
        at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:917)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:341)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:297)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:61)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:36)
        at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:418)
        at brut.androlib.Androlib.buildSources(Androlib.java:349)
        at brut.androlib.Androlib.build(Androlib.java:301)
        at brut.androlib.Androlib.build(Androlib.java:268)
        at brut.apktool.Main.cmdBuild(Main.java:251)
        at brut.apktool.Main.main(Main.java:79)
Caused by: org.jf.util.ExceptionWithContext: Error while writing instruction at code offset 0x2
        at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1190)
        at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:913)
        ... 10 more
Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range:65536
        at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
        at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:356)
        at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1150)
        ... 11 more

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? no
3. Are you using the latest apktool version? yes

**Comment by beaumontk** [comment]
Building split APK generated by https://www.andnixsh.com/2020/06/sap-split-apks-packer-by-kirlif-windows.html
apktool decoded ok and then Built ok. Crashed only when re-built after small change in unrelated smali

**Comment by pashamcr** [comment]
@beaumontk
`Unsigned short value out of range: 65536`
https://developer.android.com/studio/build/multidex
transfer the modified smali to another dex

**Comment by beaumontk** [comment]
So move eg. XXX.smal from smali folder to smali_classes2 folder?
Had no idea that this was possible!
Thanks a lot

**Comment by iBotPeaches** [comment]
As mentioned, the method limit was hit (unsigned short max) and thus moving files to a new dex file resolved it.

Closing.

**Comment by iBotPeaches** [comment]
> @beaumontk
> 
> brother what did you do to solve this ? I'm using kali linux and same problem.

The solve was in the answer you quoted.
