### ISSUE TITLE
[BUG] brut.directory.DirectoryException (only on windows works fine for linux)

### ISSUE THREAD

**Issue by joshua-612** [iBotPeaches/Apktool#2509]
### Information
1. **Apktool Version (`apktool -version`)** -  2.5.0
2. **Operating System** - Windows
3. **APK From? (Playstore)** - Apkmirror

Decompiling the Gboard works if used without any options but I am Unable to recompile Gboard 
There are many errors in resources. 

Also trying to decompile Gboard with -r option (java -jar apktool_2.5.0.jar d -r gboard.apk)  
also fails it shows these errors 

`Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: Error copying file: res
        at brut.androlib.Androlib.decodeResourcesRaw(Androlib.java:123)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:106)
        at brut.apktool.Main.cmdDecode(Main.java:179)
        at brut.apktool.Main.main(Main.java:82)`

`Caused by: brut.directory.DirectoryException: Error copying file: res
        at brut.directory.DirUtil.copyToDir(DirUtil.java:94)
        at brut.directory.DirUtil.copyToDir(DirUtil.java:70)
        at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:203)
        at brut.androlib.Androlib.decodeResourcesRaw(Androlib.java:121)
        ... 3 more`

`Caused by: brut.directory.DirectoryException: Error copying file: pRN.xml
        at brut.directory.DirUtil.copyToDir(DirUtil.java:94)
        at brut.directory.DirUtil.copyToDir(DirUtil.java:63)
        at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:198)
        at brut.directory.DirUtil.copyToDir(DirUtil.java:79)
        ... 6 more`

`Caused by: brut.common.TraversalUnknownFileException: Directory Traversal is not allowed - pRN.xml
        at brut.util.BrutIO.sanitizeUnknownFile(BrutIO.java:93)
        at brut.directory.DirUtil.copyToDir(DirUtil.java:84)
        ... 9 more`

**Comment by joshua-612** [comment]
Also I would like to add that, the decompilation with ”-r” works in linux (WSL)

**Comment by iBotPeaches** [comment]
> Directory Traversal is not allowed - pRN.xml

This is intended and security mechanism to prevent writing files outside of the intended directory.
