### ISSUE TITLE
Unable to decompile apk

### ISSUE THREAD

**Issue by peterpt** [iBotPeaches/Apktool#2513]
Using apktool 2.5.0

Log : 
I: Using Apktool 2.5.0 on facebook.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: unsupported res type name for bags. Found: style2
	at brut.androlib.res.data.value.ResValueFactory.bagFactory(ResValueFactory.java:118)
	at brut.androlib.res.decoder.ARSCDecoder.readComplexEntry(ARSCDecoder.java:350)
	at brut.androlib.res.decoder.ARSCDecoder.readEntryData(ARSCDecoder.java:276)
	at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:252)
	at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:175)
	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:131)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:82)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:48)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:790)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:67)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:59)
	at brut.androlib.Androlib.getResTable(Androlib.java:66)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:236)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:118)
	at brut.apktool.Main.cmdDecode(Main.java:179)
	at brut.apktool.Main.main(Main.java:82)

Download test apk file here : 
http://www.mediafire.com/file/ais53kk763g8zw1/facebook.apk/file

**Comment by AndnixSH** [comment]
Facebook app is protected

Duplicate: https://github.com/iBotPeaches/Apktool/issues/1719

**Comment by peterpt** [comment]
yup , i realised that 1 day after this post , it looks they are using proguard to protect the apk

**Comment by iBotPeaches** [comment]
As mentioned above, tracking in #1719 - https://github.com/iBotPeaches/Apktool/issues/1719

Closing.
