### ISSUE TITLE
decompiler error [BUG]

### ISSUE THREAD

**Issue by kalmen26** [iBotPeaches/Apktool#2537]
### Information
1. **Apktool Version (`apktool -version`)*2.5.0* -
2. **Operating System (Windows)** -
3. **APK From? (ROM)** -

### Stacktrace/Logcat
```
C:\Users\Kalmen\Desktop\LG-Classic-Flip>apktool d LGSystemUI.apk
I: Using Apktool 2.5.0 on LGSystemUI.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Kalmen\AppData\Local\apktool\framework\1.apk
I: Loading resource table from file: C:\Users\Kalmen\AppData\Local\apktool\framework\2.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Loading resource table from file: C:\Users\Kalmen\AppData\Local\apktool\framework\3.apk
I: Decoding Shared Library (com.lge), pkgId: 2
W: Could not decode attr value, using undecoded value instead: ns=android, name=textColor, value=0x03050036
I: Loading resource table from file: C:\Users\Kalmen\AppData\Local\apktool\framework\3.apk
I: Decoding Shared Library (com.lge), pkgId: 2
W: Could not decode attr value, using undecoded value instead: ns=android, name=tint, value=0x03050036
I: Loading resource table from file: C:\Users\Kalmen\AppData\Local\apktool\framework\3.apk
I: Decoding Shared Library (com.lge), pkgId: 2
W: Could not decode attr value, using undecoded value instead: ns=android, name=tint, value=0x03050036
I: Loading resource table from file: C:\Users\Kalmen\AppData\Local\apktool\framework\3.apk
I: Decoding Shared Library (com.lge), pkgId: 2
W: Could not decode attr value, using undecoded value instead: ns=android, name=textColor, value=0x03050036
I: Decoding values */* XMLs...
I: Loading resource table from file: C:\Users\Kalmen\AppData\Local\apktool\framework\3.apk
I: Decoding Shared Library (com.lge), pkgId: 2
Exception in thread "main" brut.androlib.AndrolibException: Expected pkg of id: 3, got: 2
        at brut.androlib.res.AndrolibResources.loadFrameworkPkg(AndrolibResources.java:135)
        at brut.androlib.res.data.ResTable.getPackage(ResTable.java:84)
        at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:67)
        at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:63)
        at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferenceValue.java:62)
        at brut.androlib.res.data.value.ResReferenceValue.referentIsNull(ResReferenceValue.java:73)
        at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:49)
        at brut.androlib.res.data.value.ResBagValue.serializeToResValuesXml(ResBagValue.java:42)
        at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:746)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:263)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:129)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:124)
        at brut.apktool.Main.cmdDecode(Main.java:179)
        at brut.apktool.Main.main(Main.java:82)
```

### Frameworks
If this APK is from an OEM ROM (LG). Please attach framework files 
in framework i have:   framework-res.apk  // lge-res.apk // com.lge.leap.apk // com.lge.sui.widget.apk

**Comment by iBotPeaches** [comment]
It looks like this is a by-product of same issue as #2514 - Marking as duplicate.
