### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by andres915Ycard** [iBotPeaches/Apktool#2541]
The bug is in `apktool b`
Picked up _JAVA_OPTIONS: -Xmx4900m
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
	at org.jf.dexlib2.writer.DexWriter.writeAnnotationDirectories(DexWriter.java:919)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:344)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:300)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:61)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:36)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:420)
	at brut.androlib.Androlib.buildSources(Androlib.java:351)
	at brut.androlib.Androlib.build(Androlib.java:303)
	at brut.androlib.Androlib.build(Androlib.java:270)
	at brut.apktool.Main.cmdBuild(Main.java:259)
	at brut.apktool.Main.main(Main.java:85)

Sorry i am noob

**Comment by MrIkso** [comment]
use jdk 11+

**Comment by andres915Ycard** [comment]
> use jdk 11+

thank you, it was helpful

**Comment by iBotPeaches** [comment]
The upcoming release has this fixed anyway regardless of JDK version. Dumb covariance fix that led to requiring a force cast of Buffer.
