### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by negativelol** [iBotPeaches/Apktool#2573]
### Information
1. **Apktool Version (`apktool -2.5.0`)**
2. **Operating System (Windows)**
take almost any apk here https://m.apkpure.com
many errors during reassembly .

**Compile apk C:\Users\111\Desktop\APK/tmp/3.apk
I: Using Apktool 2.5.0
I: Smaling smali folder into classes.dex...
Exception in thread "main" org.jf.util.ExceptionWithContext: Exception occurred
while writing code_item for method Landroid/support/constraint/a/a/a$a;->values(
)[Landroid/support/constraint/a/a/a$a;
        at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java
:1047)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:346)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:301)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:61)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:36)
        at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:420)
        at brut.androlib.Androlib.buildSources(Androlib.java:351)
        at brut.androlib.Androlib.build(Androlib.java:303)
        at brut.androlib.Androlib.build(Androlib.java:270)
        at brut.apktool.Main.cmdBuild(Main.java:255)
        at brut.apktool.Main.main(Main.java:81)
Caused by: org.jf.util.ExceptionWithContext: Error while writing instruction at
code offset 0x2
        at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1320)
        at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java
:1043)
        ... 10 more
Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range:
66428
        at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:11
6)
        at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:
356)
        at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1280)
        ... 11 more
**

**Comment by negativelol** [comment]
Also more errors ->
**
I: Smaling smali folder into classes.dex...
I: Building resources...
W: C:\Users\111\Desktop\APK\tmp\2\AndroidManifest.xml:1: error: No resource iden
tifier found for attribute 'compileSdkVersion' in package 'android'
W:
W: C:\Users\111\Desktop\APK\tmp\2\AndroidManifest.xml:1: error: No resource iden
tifier found for attribute 'compileSdkVersionCodename' in package 'android'
W:
**
AndroidManifest.xml
**<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:compileSdkVersion="28" android:compileSdkVersionCodename="9" package="nanana.ru" platformBuildVersionCode="28" platformBuildVersionName="9">**

**Comment by iBotPeaches** [comment]
> Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range:66428

You don't have enough methods in this dex file.

> W: C:\Users\111\Desktop\APK\tmp\2\AndroidManifest.xml:1: error: No resource identifier found for attribute 'compileSdkVersion' in package 'android'

Frameworks are not up to date.
