### ISSUE TITLE
Disassemble-build-disassemble fails

### ISSUE THREAD

**Issue by RenateUSB** [iBotPeaches/Apktool#2582]
With Windows 10, Apktool 2.5.0

http://www.temblast.com/download/framework.jar

    apktool.bat d framework.jar -o FWPoke1 -api 29
    apktool.bat b FWPoke1 -o fwpoke1.jar -api 29
    apktool.bat d fwpoke1.jar -o FWPoke2 -api 29

apktool.bat d framework.jar -o FWPoke1 -api 29
I: Using Apktool 2.5.0 on framework.jar
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

apktool.bat b FWPoke1 -o fwpoke1.jar -api 29
I: Using Apktool 2.5.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
W: Could not find resources
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk...

apktool.bat d fwpoke1.jar -o FWPoke2 -api 29
I: Using Apktool 2.5.0 on fwpoke1.jar
I: Baksmaling classes.dex...

Error occurred while disassembling class Landroid.util.proto.ProtoOutputStream; - skipping class
java.lang.ArrayIndexOutOfBoundsException: 1
        at org.jf.dexlib2.HiddenApiRestriction.getAllFlags(HiddenApiRestriction.java:111)
        at org.jf.dexlib2.dexbacked.DexBackedMethod.getHiddenApiRestrictions(DexBackedMethod.java:204)
        at org.jf.baksmali.Adaptors.MethodDefinition.writeTo(MethodDefinition.java:196)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeVirtualMethods(ClassDefinition.java:327)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:113)
        at org.jf.baksmali.Baksmali.disassembleClass(Baksmali.java:152)
        at org.jf.baksmali.Baksmali.access$000(Baksmali.java:46)
        at org.jf.baksmali.Baksmali$1.call(Baksmali.java:76)
        at org.jf.baksmali.Baksmali$1.call(Baksmali.java:74)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...

Error occurred while disassembling class Lorg.apache.http.conn.ssl.SSLSocketFactory; - skipping class
java.lang.ArrayIndexOutOfBoundsException
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

Note also that the build in the second step takes about 30 seconds/classes.dex, longer than expected.
If I strip all black/grey/whitelist before building it runs 5 seconds/classes.dex
It still gets the same error.

**Comment by iBotPeaches** [comment]
This is already fixed in the upcoming 2.5.1 release. This just needs the new baksmali/smali 2.5.2, which is on master already.
