### ISSUE TITLE
[BUG] dlopen failed: library [...] not found

### ISSUE THREAD

**Issue by Luffitys** [iBotPeaches/Apktool#2589]
### Information
1. **Apktool Version (`apktool -version`)** - Compiled myself from master branch
2. **Operating System (Mac, Linux, Windows)** - Windows 10
3. **APK From? (Playstore, ROM, Other)** - OEM (Xiaomi)

### Stacktrace/Logcat

```
FATAL EXCEPTION: main
Process: com.android.camera, PID: 8347
java.lang.UnsatisfiedLinkError: dlopen failed: library "/system/priv-app/ANXCamera/ANXCamera.apk!/lib/arm64-v8a/libmiuinative.so" not found
	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
	at java.lang.System.loadLibrary(System.java:1664)
	at com.miui.internal.os.Native.<clinit>(Unknown Source:2)
	at com.miui.internal.os.Native.getPropertyNative(Native Method)
	at miui.os.SystemProperties.get(Unknown Source:8)
	at miui.os.Build.<clinit>(Unknown Source:900)
	at com.android.camera.Util.<clinit>(Unknown Source:152)
	at OooO0O0.OooO0o0.OooO00o.OooO0O0.<clinit>(Unknown Source:0)
	at OooO0O0.OooO0o0.OooO00o.OooO0O0.o0O0O0Oo(Unknown Source:0)
	at com.android.camera.aftersales.AftersalesManager.checkSelf(Unknown Source:0)
	at com.android.camera.CameraAppImpl.attachBaseContext(Unknown Source:30)
	at android.app.Application.attach(Application.java:351)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1160)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1260)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6705)
	at android.app.ActivityThread.access$1300(ActivityThread.java:238)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1914)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7701)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
```

### Steps to Reproduce
1. `apktool `

### Frameworks
See APK section

### APK
Modded, the one I'm trying to make it work:
https://drive.google.com/drive/folders/1M487LGWNzQ0ltjUDIqb2Atspde_Yu2TN?usp=sharing
Original, has a dlopen error too:

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? - Yes.
2. If you are trying to install a modified apk, did you resign it? - Yes
3. Are you using the latest apktool version? - Yes

Addition:
The said library does exist in APK/lib/arm64-v8a/
I tried many things already, and found out following things. I took the original APK and had no crash. I zipaligned and resigned it and still no crashes were present. After decompilation and recompilation, the library (and other ones too) can't be found. Even when not decompiling the classes.dex and resources.arsc, the recompilation makes the APK not find the library

**Comment by iBotPeaches** [comment]
```
	at OooO0O0.OooO0o0.OooO00o.OooO0O0.<clinit>(Unknown Source:0)
	at OooO0O0.OooO0o0.OooO00o.OooO0O0.o0O0O0Oo(Unknown Source:0)
```

My guess with something like that in the stacktrace is some anti-tamper mechanism going on.
