### ISSUE TITLE
Error messages when decompiling, unsure about cause

### ISSUE THREAD

**Issue by Thrud-U** [iBotPeaches/Apktool#2592]
Hello, I tried to decompile a app and got these errors.
I am not quite sure why I would have no access since it's the download folder or why it cannot copy a file.
Not sure if I should even put this in issues or where else, but I thought, you might be able to help with this.

C:\Users\OMITTED\Downloads>apktool d -o c:\users\OMITTED\downloads\project -f por_mrg.apk
I: Using Apktool 2.5.0 on por_mrg.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\OMITTED\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: Error copying file: assets
        at brut.androlib.Androlib.decodeRawFiles(Androlib.java:158)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:179)
        at brut.apktool.Main.cmdDecode(Main.java:179)
        at brut.apktool.Main.main(Main.java:82)
Caused by: brut.directory.DirectoryException: Error copying file: assets
        at brut.directory.DirUtil.copyToDir(DirUtil.java:94)
        at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:208)
        at brut.androlib.Androlib.decodeRawFiles(Androlib.java:145)
        ... 3 more
Caused by: brut.directory.DirectoryException: Error copying file:
        at brut.directory.DirUtil.copyToDir(DirUtil.java:91)
        at brut.directory.DirUtil.copyToDir(DirUtil.java:63)
        at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:198)
        at brut.directory.DirUtil.copyToDir(DirUtil.java:79)
        ... 5 more
Caused by: java.io.FileNotFoundException: c:\users\OMITTED\downloads\project\assets (Access is denied)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at brut.directory.DirUtil.copyToDir(DirUtil.java:87)
        ... 8 more

**Comment by iBotPeaches** [comment]
I'm not sure, but it looks related to #2574 which is basically the assets folder acting weird on anything that isn't linux.
