### ISSUE TITLE
[BUG]Recompile APK success but run failed for java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity

### ISSUE THREAD

**Issue by kirin521** [iBotPeaches/Apktool#2597]
### Information
1. **Apktool Version (`2.5.0`)** -
2. **Operating System (Windows)** -
3. **APK From? (Official website.)** -

### Stacktrace/Logcat

```
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.test.mockup/org.test.mockup.activity.MainActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3863)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4042)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2450)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8285)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1052)
     Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(SourceFile:555)
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(SourceFile:518)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(SourceFile:466)
        at androidx.appcompat.app.AppCompatActivity.setContentView(SourceFile:140)
        at org.test.mockup.activity.MainActivity.onCreate(SourceFile:21)
        at android.app.Activity.performCreate(Activity.java:8085)
        at android.app.Activity.performCreate(Activity.java:8073)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3836)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4042) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2450) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:219) 
        at android.app.ActivityThread.main(ActivityThread.java:8285) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1052) 
```

### Steps to Reproduce
1. apktool d xx.apk
2. apktool b xx
3. jarsign
4. adb puhs xx_recompile.apk

### Frameworks
default framework.
### APK
sorry cannot share.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
    Yes,I have tried change nothing between apktool d and apktool b.
2. If you are trying to install a modified apk, did you resign it?
    Yes.I resign it.
3. Are you using the latest apktool version?
   Yes.I used the 2.5.0 version.

I want to know what is the probable cause of the error? thank u very much.

**Comment by iBotPeaches** [comment]
> I want to know what is the probable cause of the error? thank u very much.

I do not


> sorry cannot share.
Sorry, I cannot help.

**Comment by kirin521** [comment]
thanks for your reply. @iBotPeaches Can I send the apk to your email?
