### ISSUE TITLE
App getting crashed when an apk is disassembled and rebuild the apk without any modification

### ISSUE THREAD

**Issue by Nikhil1212** [iBotPeaches/Apktool#2627]
Apktool version: 2.4.1
This is the apk https://play.google.com/store/apps/details?id=com.axis.mobile and when I am running the repackaged version after following steps:
```
apktool d base.apk
apktool b base -o modified.apk

```
The app is getting crashed.
How I fetched the apk?
1. Install the app from PlayStore 
2. used `adb pull` to fetch the apk and store it to PC.
When I launch the app, the app is immediately getting crashed, the moment I clicked on the launcher icon.

Apktool version 2.4.1
So, this is the logs that was generated using `adb shell logcat | findstr "com.axis.mobile"`

```
`adb shell logcat | findstr "com.axis.mobile"
08-15 19:15:53.580  1920  4823 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.axis.mobile/.MainActivity bnds=[439,334][640,661]} from uid 10239
08-15 19:15:53.614  1920  2084 I ActivityManager: Start proc 8904:com.axis.mobile/u0a3915 for pre-top-activity {com.axis.mobile/com.axis.mobile.MainActivity}
08-15 19:15:53.795  8904  8904 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "com.axis.mobile.whateverString" on path: DexPathList[[zip file "/data/app/~~4k2zgxWD4Udds1uMGbHNvg==/com.axis.mobile-spO5e-Jo3VhtRPgiGZrmOA==/base.apk"],nativeLibraryDirectories=[/data/app/~~4k2zgxWD4Udds1uMGbHNvg==/com.axis.mobile-spO5e-Jo3VhtRPgiGZrmOA==/lib/arm64, /data/app/~~4k2zgxWD4Udds1uMGbHNvg==/com.axis.mobile-spO5e-Jo3VhtRPgiGZrmOA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64, /product/lib64]]
08-15 19:15:54.043  8904  8904 E Report  :      at com.axis.mobile.google.analytics.GoogleAnalyticsAppTracker.<clinit>(Unknown Source:0)
08-15 19:15:54.043  8904  8904 E AndroidRuntime: Process: com.axis.mobile, PID: 8904
08-15 19:15:54.043  8904  8904 E AndroidRuntime:        at com.axis.mobile.google.analytics.GoogleAnalyticsAppTracker.<clinit>(Unknown Source:0)
08-15 19:15:54.045  1920  4822 W ActivityTaskManager:   Force finishing activity com.axis.mobile/.MainActivity
08-15 19:15:54.546  1920  2063 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{48d300a u0 com.axis.mobile/.MainActivity t3862 f}}
08-15 19:15:54.561  1920  2063 W ActivityTaskManager: Activity pause timeout for ActivityRecord{48d300a u0 com.axis.mobile/.MainActivity t3862 f}}
^C^C
C:\Users\Nikhil Agrawal>adb shell logcat --pid 8904
--------- beginning of main
08-15 19:15:53.610  8904  8904 I libc    : SetHeapTaggingLevel: tag level set to 0
08-15 19:15:53.614  8904  8904 E com.axis.mobil: Not starting debugger since process cannot load the jdwp agent.
08-15 19:15:53.634  8904  8904 D ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
08-15 19:15:53.636  8904  8904 I com.axis.mobil: The ClassLoaderContext is a special shared library.
--------- beginning of system
08-15 19:15:53.795  8904  8904 E LoadedApk: Unable to instantiate appComponentFactory
08-15 19:15:53.795  8904  8904 E LoadedApk: java.lang.ClassNotFoundException: Didn't find class "com.axis.mobile.whateverString" on path: DexPathList[[zip file "/data/app/~~4k2zgxWD4Udds1uMGbHNvg==/com.axis.mobile-spO5e-Jo3VhtRPgiGZrmOA==/base.apk"],nativeLibraryDirectories=[/data/app/~~4k2zgxWD4Udds1uMGbHNvg==/com.axis.mobile-spO5e-Jo3VhtRPgiGZrmOA==/lib/arm64, /data/app/~~4k2zgxWD4Udds1uMGbHNvg==/com.axis.mobile-spO5e-Jo3VhtRPgiGZrmOA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64, /product/lib64]]
08-15 19:15:53.795  8904  8904 E LoadedApk:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
08-15 19:15:53.795  8904  8904 E LoadedApk:     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
08-15 19:15:53.795  8904  8904 E LoadedApk:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
08-15 19:15:53.795  8904  8904 E LoadedApk:     at android.app.LoadedApk.createAppFactory(LoadedApk.java:260)
08-15 19:15:53.795  8904  8904 E LoadedApk:     at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:902)
08-15 19:15:53.795  8904  8904 E LoadedApk:     at android.app.LoadedApk.getClassLoader(LoadedApk.java:982)
08-15 19:15:53.795  8904  8904 E LoadedApk:     at android.app.LoadedApk.getResources(LoadedApk.java:1214)
08-15 19:15:53.795  8904  8904 E LoadedApk:     at android.app.ContextImpl.createAppContext(ContextImpl.java:2663)
08-15 19:15:53.795  8904  8904 E LoadedApk:     at android.app.ContextImpl.createAppContext(ContextImpl.java:2655)
08-15 19:15:53.795  8904  8904 E LoadedApk:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6598)
08-15 19:15:53.795  8904  8904 E LoadedApk:     at android.app.ActivityThread.access$1300(ActivityThread.java:237)
08-15 19:15:53.795  8904  8904 E LoadedApk:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
08-15 19:15:53.795  8904  8904 E LoadedApk:     at android.os.Handler.dispatchMessage(Handler.java:106)
08-15 19:15:53.795  8904  8904 E LoadedApk:     at android.os.Looper.loop(Looper.java:223)
08-15 19:15:53.795  8904  8904 E LoadedApk:     at android.app.ActivityThread.main(ActivityThread.java:7660)
08-15 19:15:53.795  8904  8904 E LoadedApk:     at java.lang.reflect.Method.invoke(Native Method)
08-15 19:15:53.795  8904  8904 E LoadedApk:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
08-15 19:15:53.795  8904  8904 E LoadedApk:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
08-15 19:15:53.802  8904  8904 D NetworkSecurityConfig: No Network Security Config specified, using platform default
08-15 19:15:53.802  8904  8904 D NetworkSecurityConfig: No Network Security Config specified, using platform default
08-15 19:15:54.043  8904  8904 E Report  : Exiting:
08-15 19:15:54.043  8904  8904 E Report  : wmzlgt.ah: 01
08-15 19:15:54.043  8904  8904 E Report  :      at wmzlgt.r.b(Unknown Source:164)
08-15 19:15:54.043  8904  8904 E Report  :      at wmzlgt.r.a(Unknown Source:0)
08-15 19:15:54.043  8904  8904 E Report  :      at java.lang.Runtime.nativeLoad(Native Method)
08-15 19:15:54.043  8904  8904 E Report  :      at java.lang.Runtime.nativeLoad(Runtime.java:1131)
08-15 19:15:54.043  8904  8904 E Report  :      at java.lang.Runtime.loadLibrary0(Runtime.java:1085)
08-15 19:15:54.043  8904  8904 E Report  :      at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
08-15 19:15:54.043  8904  8904 E Report  :      at java.lang.System.loadLibrary(System.java:1664)
08-15 19:15:54.043  8904  8904 E Report  :      at wmzlgt.S.b(Unknown Source:8)
08-15 19:15:54.043  8904  8904 E Report  :      at wmzlgt.L.b(Unknown Source:13)
08-15 19:15:54.043  8904  8904 E Report  :      at wmzlgt.L.c(Unknown Source:24)
08-15 19:15:54.043  8904  8904 E Report  :      at wmzlgt.L.a(Unknown Source:6)
08-15 19:15:54.043  8904  8904 E Report  :      at wmzlgt.L.<clinit>(Unknown Source:0)
08-15 19:15:54.043  8904  8904 E Report  :      at wmzlgt.L.a(Unknown Source:0)
08-15 19:15:54.043  8904  8904 E Report  :      at com.axis.mobile.google.analytics.GoogleAnalyticsAppTracker.<clinit>(Unknown Source:0)
08-15 19:15:54.043  8904  8904 E Report  :      at java.lang.Class.newInstance(Native Method)
08-15 19:15:54.043  8904  8904 E Report  :      at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
08-15 19:15:54.043  8904  8904 E Report  :      at android.app.Instrumentation.newApplication(Instrumentation.java:1158)
08-15 19:15:54.043  8904  8904 E Report  :      at android.app.LoadedApk.makeApplication(LoadedApk.java:1260)
08-15 19:15:54.043  8904  8904 E Report  :      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6686)
08-15 19:15:54.043  8904  8904 E Report  :      at android.app.ActivityThread.access$1300(ActivityThread.java:237)
08-15 19:15:54.043  8904  8904 E Report  :      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
08-15 19:15:54.043  8904  8904 E Report  :      at android.os.Handler.dispatchMessage(Handler.java:106)
08-15 19:15:54.043  8904  8904 E Report  :      at android.os.Looper.loop(Looper.java:223)
08-15 19:15:54.043  8904  8904 E Report  :      at android.app.ActivityThread.main(ActivityThread.java:7660)
08-15 19:15:54.043  8904  8904 E Report  :      at java.lang.reflect.Method.invoke(Native Method)
08-15 19:15:54.043  8904  8904 E Report  :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
08-15 19:15:54.043  8904  8904 E Report  :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
--------- beginning of crash
08-15 19:15:54.043  8904  8904 E AndroidRuntime: FATAL EXCEPTION: main
08-15 19:15:54.043  8904  8904 E AndroidRuntime: Process: com.axis.mobile, PID: 8904
08-15 19:15:54.043  8904  8904 E AndroidRuntime: wmzlgt.ah: 01
08-15 19:15:54.043  8904  8904 E AndroidRuntime:        at wmzlgt.r.b(Unknown Source:164)
08-15 19:15:54.043  8904  8904 E AndroidRuntime:        at wmzlgt.r.a(Unknown Source:0)
08-15 19:15:54.043  8904  8904 E AndroidRuntime:        at java.lang.Runtime.nativeLoad(Native Method)
08-15 19:15:54.043  8904  8904 E AndroidRuntime:        at java.lang.Runtime.nativeLoad(Runtime.java:1131)
08-15 19:15:54.043  8904  8904 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1085)
08-15 19:15:54.043  8904  8904 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
08-15 19:15:54.043  8904  8904 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1664)
08-15 19:15:54.043  8904  8904 E AndroidRuntime:        at wmzlgt.S.b(Unknown Source:8)
08-15 19:15:54.043  8904  8904 E AndroidRuntime:        at wmzlgt.L.b(Unknown Source:13)
08-15 19:15:54.043  8904  8904 E AndroidRuntime:        at wmzlgt.L.c(Unknown Source:24)
08-15 19:15:54.043  8904  8904 E AndroidRuntime:        at wmzlgt.L.a(Unknown Source:6)
08-15 19:15:54.043  8904  8904 E AndroidRuntime:        at wmzlgt.L.<clinit>(Unknown Source:0)
08-15 19:15:54.043  8904  8904 E AndroidRuntime:        at wmzlgt.L.a(Unknown Source:0)
08-15 19:15:54.043  8904  8904 E AndroidRuntime:        at com.axis.mobile.google.analytics.GoogleAnalyticsAppTracker.<clinit>(Unknown Source:0)
08-15 19:15:54.043  8904  8904 E AndroidRuntime:        at java.lang.Class.newInstance(Native Method)
08-15 19:15:54.043  8904  8904 E AndroidRuntime:        at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
08-15 19:15:54.043  8904  8904 E AndroidRuntime:        at android.app.Instrumentation.newApplication(Instrumentation.java:1158)
08-15 19:15:54.043  8904  8904 E AndroidRuntime:        at android.app.LoadedApk.makeApplication(LoadedApk.java:1260)
08-15 19:15:54.043  8904  8904 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6686)
08-15 19:15:54.043  8904  8904 E AndroidRuntime:        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
08-15 19:15:54.043  8904  8904 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
08-15 19:15:54.043  8904  8904 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
08-15 19:15:54.043  8904  8904 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
08-15 19:15:54.043  8904  8904 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7660)
08-15 19:15:54.043  8904  8904 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-15 19:15:54.043  8904  8904 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
08-15 19:15:54.043  8904  8904 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

`
```

Does anyone knows what is the reasons for the Exceptions like `java.lang.ClassNotFoundException`,_process cannot load the jdwp agent_?

For others apps, I am able to disassemble, reassemble and the app is working perfectly, but it is not getting crashed.
I am also unable to decompile this apk using the jadx tool.

Is it because the app has some protections against tools like apktool, jadx? Or is it like there is a shortcoming from apktool that needs to be improved?

PS: The original apk which I am using for disassembling is perfectly fine. I have already installed the original apk using adb and the app is working perfectly fine.
   
Thanks a lot for the help.

**Comment by HenryQuan** [comment]
I had similar issues with one app. It also crashes with the app tries to call System.loadLibrary() but it is the same library. It is very strange because I didn't change anything at all.

**Comment by iBotPeaches** [comment]
> Is it because the app has some protections against tools like apktool, jadx? Or is it like there is a shortcoming from apktool that needs to be improved?

Presumably protections against this exact effort of RE. Which I get you classify as a shortcoming, but I call it "magic" as building in automated support to recover from every type of protection effort is not feasible.

You are welcome to run some tests. Try your process but skip the assets, then try it again and skip the sources. If one of those are left untouched - does the output change? Diff the disassembled application to the disassembled/rebuilt application - does anything stand out?

Those can help you pinpoint what you need to patch. If it looks like something obvious that Apktool may have messed up - we can take another look.
