### ISSUE TITLE
[BUG] NullPointerException

### ISSUE THREAD

**Issue by Inchworm333** [iBotPeaches/Apktool#2669]
### Information
1. **Apktool Version (`apktool -version`)** - 2.6.0
2. **Operating System (Mac, Linux, Windows)** - Linux (Debian 11)
3. **APK From? (Playstore, ROM, Other)** - Playstore 

### Stacktrace/Logcat

```
I: Using Apktool 2.6.0 on TP-Link Tether_3.4.28_apk-dl.com.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionCode, value=0x000000ac
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionName, value=0x00000030
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionCode, value=0x000000ac
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionName, value=0x00000030
W: Could not decode attr value, using undecoded value instead: ns=android, name=installLocation, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=compileSdkVersion, value=0x0000001d
W: Could not decode attr value, using undecoded value instead: ns=android, name=compileSdkVersionCodename, value=0x0000002e
W: Could not decode attr value, using undecoded value instead: ns=android, name=minSdkVersion, value=0x00000013
W: Could not decode attr value, using undecoded value instead: ns=android, name=targetSdkVersion, value=0x0000001d
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000004f
W: Could not decode attr value, using undecoded value instead: ns=android, name=maxSdkVersion, value=0x0000001c
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000004d
W: Could not decode attr value, using undecoded value instead: ns=android, name=maxSdkVersion, value=0x0000001c
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000004c
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000043
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000042
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000049
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000004b
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000004e
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000048
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000045
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000046
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000005b
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000003a
W: Could not decode attr value, using undecoded value instead: ns=android, name=required, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000040
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000041
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000183
W: Could not decode attr value, using undecoded value instead: ns=android, name=value, value=0x00000036
Exception in thread "main" java.lang.NullPointerException
	at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1770)
	at java.base/java.util.regex.Matcher.reset(Matcher.java:416)
	at java.base/java.util.regex.Matcher.<init>(Matcher.java:253)
	at java.base/java.util.regex.Pattern.matcher(Pattern.java:1133)
	at brut.androlib.res.decoder.AndroidManifestResourceParser.isNumericStringMetadataAttributeValue(AndroidManifestResourceParser.java:56)
	at brut.androlib.res.decoder.AndroidManifestResourceParser.getAttributeValue(AndroidManifestResourceParser.java:41)
	at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValue(XmlPullParserDelegate.java:69)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
	at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:80)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:139)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:151)
	at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:159)
	at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:193)
	at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:140)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:109)
	at brut.apktool.Main.cmdDecode(Main.java:175)
	at brut.apktool.Main.main(Main.java:78)

```

### Steps to Reproduce
1. `apktool d TP-Link\ Tether_3.4.28_apk-dl.com.apk`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)
N/A

### APK
If this APK can be freely shared, please upload/attach a link to it.

[TpLink Teather](http://apkfind.com/dl5/apk/2021/9/22/com.tplink.tether_172.apk?id=com.tplink.tether&f=TP-Link%20Tether_3.4.28_apk-dl.com.apk)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

**Comment by iBotPeaches** [comment]
Well that was the most unpleasant site of ads/shit to see at 6 in the morning. I have the application and confirm the issue.

**Comment by Inchworm333** [comment]
Oof yeah, I would have never used it if it weren't for uBlock Origin

**Comment by pokonski** [comment]
I can report the same issue with 2.6.0 and APK https://apkcombo.com/pl/smart-tc/com.bdrthermea.roomunitapplication.dedietrich/download/apk, tried both from here and pulling from phone.


```
I: Using Apktool 2.6.0 on playstore.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionCode, value=0x019f8fa4
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionName, value=0x00000026
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionCode, value=0x019f8fa4
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionName, value=0x00000026
W: Could not decode attr value, using undecoded value instead: ns=android, name=hardwareAccelerated, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=compileSdkVersion, value=0x0000001c
W: Could not decode attr value, using undecoded value instead: ns=android, name=compileSdkVersionCodename, value=0x00000027
W: Could not decode attr value, using undecoded value instead: ns=android, name=minSdkVersion, value=0x00000018
W: Could not decode attr value, using undecoded value instead: ns=android, name=targetSdkVersion, value=0x0000001d
W: Could not decode attr value, using undecoded value instead: ns=android, name=anyDensity, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=smallScreens, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=normalScreens, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=largeScreens, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=resizeable, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=xlargeScreens, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000003d
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000003c
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000037
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000040
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000039
W: Could not decode attr value, using undecoded value instead: ns=android, name=maxSdkVersion, value=0x00000012
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000003f
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000035
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000036
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000031
W: Could not decode attr value, using undecoded value instead: ns=android, name=glEsVersion, value=0x00020000
W: Could not decode attr value, using undecoded value instead: ns=android, name=required, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000030
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000003e
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000003a
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000003b
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000002f
W: Could not decode attr value, using undecoded value instead: ns=android, name=required, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000050
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000055
W: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f0c0001
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0a0000
W: Could not decode attr value, using undecoded value instead: ns=android, name=hardwareAccelerated, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=supportsRtl, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=appComponentFactory, value=0x00000042
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x01030129
W: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f0c0000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000048
W: Could not decode attr value, using undecoded value instead: ns=android, name=launchMode, value=0x00000001
W: Could not decode attr value, using undecoded value instead: ns=android, name=screenOrientation, value=0x00000001
W: Could not decode attr value, using undecoded value instead: ns=android, name=configChanges, value=0x000004b4
W: Could not decode attr value, using undecoded value instead: ns=android, name=windowSoftInputMode, value=0x00000010
W: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f0c0045
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000032
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000034
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000074
W: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7f050026
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000075
W: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7f050028
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000004e
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000002d
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000002e
W: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7f0f0000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000004c
W: Could not decode attr value, using undecoded value instead: ns=android, name=enabled, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=exported, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000004d
W: Could not decode attr value, using undecoded value instead: ns=android, name=permission, value=0x00000038
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000005d
W: Could not decode attr value, using undecoded value instead: ns=android, name=enabled, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=exported, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000083
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000005f
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000084
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000073
W: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7f030000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000072
W: Could not decode attr value, using undecoded value instead: ns=android, name=value, value=0x7f0c0034
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000007a
W: Could not decode attr value, using undecoded value instead: ns=android, name=value, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000007c
W: Could not decode attr value, using undecoded value instead: ns=android, name=value, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000007b
W: Could not decode attr value, using undecoded value instead: ns=android, name=value, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000056
W: Could not decode attr value, using undecoded value instead: ns=android, name=value, value=0x00000028
Exception in thread "main" java.lang.NullPointerException
	at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1770)
	at java.base/java.util.regex.Matcher.reset(Matcher.java:416)
	at java.base/java.util.regex.Matcher.<init>(Matcher.java:253)
	at java.base/java.util.regex.Pattern.matcher(Pattern.java:1133)
	at brut.androlib.res.decoder.AndroidManifestResourceParser.isNumericStringMetadataAttributeValue(AndroidManifestResourceParser.java:56)
	at brut.androlib.res.decoder.AndroidManifestResourceParser.getAttributeValue(AndroidManifestResourceParser.java:41)
	at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValue(XmlPullParserDelegate.java:69)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
	at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:80)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:139)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:151)
	at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:159)
	at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:193)
	at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:140)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:109)
	at brut.apktool.Main.cmdDecode(Main.java:175)
	at brut.apktool.Main.main(Main.java:78)
```

**Comment by iBotPeaches** [comment]
Looks like I forgot about this issue. Apologies. It was fixed here: https://github.com/iBotPeaches/Apktool/pull/2889 after this issue came in: https://github.com/iBotPeaches/Apktool/issues/2878

So closing as resolved.

```
➜  2669 apktool d 2669.apk 
I: Using Apktool 2.8.1-c744dd-SNAPSHOT on 2669.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes4.dex...
I: Baksmaling classes5.dex...
I: Baksmaling classes6.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
➜  2669 
```
