### ISSUE TITLE
[BUG] Error: Unable to rebuild apk with apktool

### ISSUE THREAD

**Issue by Salman-Farid** [iBotPeaches/Apktool#2672]
### Information
1. **Apktool Version (`apktool -version`)** -2.6.0
2. **Operating System (Mac, Linux, Windows)** -Linux
3. **APK From? (Playstore, ROM, Other)** -Playstore

### Stacktrace/Logcat
```
Exception in thread "main" org.jf.util.ExceptionWithContext: Exception occurred while writing code_item for method Lkotlin/annotation/AnnotationTarget;->values()[Lkotlin/annotation/AnnotationTarget;
        at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1047)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:346)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:301)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:58)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:37)
        at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:426)
        at brut.androlib.Androlib.buildSources(Androlib.java:357)
        at brut.androlib.Androlib.build(Androlib.java:309)
        at brut.androlib.Androlib.build(Androlib.java:276)
        at brut.apktool.Main.cmdBuild(Main.java:255)
        at brut.apktool.Main.main(Main.java:81)
Caused by: org.jf.util.ExceptionWithContext: Error while writing instruction at code offset 0x2
        at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1320)
        at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1043)
        ... 10 more
Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65536
        at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
        at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:356)
        at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1280)
        ... 11 more
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://play.google.com/store/apps/details?id=com.portonics.mygp&hl=en&gl=US

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? no
3. Are you using the latest apktool version? yes

**Comment by marutichintan** [comment]
Error Occure when added new smali file to decompile apk folder.

Solution: my issue solve by adding new smali file to last smali_classes folder (in my case smali_classes4).
