### ISSUE TITLE
[BUG]If there are two resoureces dirs(/res and /r )  in apk,it will only choose res,but what i really need is "/r".  

### ISSUE THREAD

**Issue by TheJokerW** [iBotPeaches/Apktool#2673]
### Information
1. **Apktool Version (`apktool -version`)** - 2.6.0
2. **Operating System (Mac, Linux, Windows)** - mac os big sur 11.1
3. **APK From? (Playstore, ROM, Other)** - tiktok.apk

### Stacktrace/Logcat
S: Could not decode file, replacing by FALSE value: czv.xml
 error:brut.directory.PathNotExist: czv.xml
S: inDir:brut.directory.ZipRODirectory@4cd4c999
brut.androlib.AndrolibException: brut.directory.PathNotExist: czv.xml
	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:144)
	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:119)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:247)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:136)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:111)
	at brut.apktool.Main.cmdDecode(Main.java:175)
	at brut.apktool.Main.main(Main.java:79)
Caused by: brut.directory.PathNotExist: czv.xml
	at brut.directory.AbstractDirectory.getFileInput(AbstractDirectory.java:110)
	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:139)
	... 6 more
```
Include stacktrace here
```

### Steps to Reproduce
java -Xmx2048m  -jar ./apktool-cli-all.jar d base.apk -o base

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
adb pull from google play
### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? just decode
3. Are you using the latest apktool version? yes

**Comment by TheJokerW** [comment]
> Quite a lot of information here, but I would urge you to push up a PR if you feel you've encountered something that can be resolved. Have not had time to dig into this yet.

ok,i will dig it up
