### ISSUE TITLE
[BUG] Chunk [amp] is not a valid entry

### ISSUE THREAD

**Issue by pashamcr** [iBotPeaches/Apktool#2675]
### Information
1. **Apktool Version (`apktool -version`)** - 2.6.0
2. **Operating System (Mac, Linux, Windows)** - win
3. **APK From? (Playstore, ROM, Other)** - rom

### Stacktrace/Logcat

```
I: Using Apktool 2.6.0 on Settings.apk
I: Loading resource table...
I: Decoding Shared Library (miui), pkgId: 16
I: Decoding Shared Library (android.miui), pkgId: 17
I: Decoding Shared Library (miui.system), pkgId: 18
Exception in thread "main" java.lang.IllegalArgumentException: Chunk [amp] is not a valid entry
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:219)
        at com.google.common.base.Splitter$MapSplitter.split(Splitter.java:526)
        at brut.androlib.res.decoder.StringBlock$Tag.toString(StringBlock.java:167)
        at java.base/java.lang.String.valueOf(String.java:2951)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:168)
        at brut.androlib.res.decoder.StringBlock.processStyledString(StringBlock.java:260)
        at brut.androlib.res.decoder.StringBlock.getHTML(StringBlock.java:288)
        at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:366)
        at brut.androlib.res.decoder.ARSCDecoder.readEntryData(ARSCDecoder.java:285)
        at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:261)
        at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:184)
        at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:135)
        at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:84)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:50)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:783)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:64)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:56)
        at brut.androlib.Androlib.getResTable(Androlib.java:69)
        at brut.androlib.ApkDecoder.getResTable(ApkDecoder.java:247)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:109)
        at brut.apktool.Main.cmdDecode(Main.java:175)
        at brut.apktool.Main.main(Main.java:78)
```

### Steps to Reproduce
1. `java -jar apktool_2.6.0.jar d -p frameworks Settings.apk`

### APK & Frameworks
https://drive.google.com/file/d/1pHBX9k4_lAhchdXMTJSfeMYiDWklTH94/view?usp=sharing

### Issue:
The commit https://github.com/iBotPeaches/Apktool/commit/087142d4cf9cc43f91c9034ee05c9cf020e6b368 messed up the Settings.apk decompilation from the MIUI ROM.

**Comment by pashamcr** [comment]
It has something to do with the string divider ';' ? Division after &amp ?

**Comment by pashamcr** [comment]
@iBotPeaches, I changed the code even further:
```
import org.unbescape.xml.XmlEscape;
import org.unbescape.html.HtmlEscape;

public final class ResXmlEncoders {

    public static String escapeXmlChars(String str) {
        str = XmlEscape.unescapeXml(str);
        str = HtmlEscape.unescapeHtml(str);

        str = StringUtils.replace(str, "&", "&amp;");
        str = StringUtils.replace(str, "<", "&lt;");
        return str;
    }
```
I can say for sure that apktool is complaining about amp inside the http address, so compare the two lines received by apktool 2.5.1:
`    <string name="privacy_authorize_dialog_message"><Data>"In order to use the basic features of this service, you must agree that Xiaomi will collect, process, and use your personal data. Refer to our Privacy Policy to learn how we collect and process personal data. Selecting \"Agree\" means that you've read and agreed to our &lt;a href=\"https://privacy.mi.com/all/%1$s_%2$s\">Privacy Policy&lt;/a> and &lt;a href=\"http://www.miui.com/res/doc/eula.html?region=%3$s&amp;lang=%4$s\">User Agreement&lt;/a>."</Data></string>`
de
`    <string name="privacy_authorize_dialog_message">&lt;Data>Um grundlegende Funktionen dieses Dienstes nutzen zu können, müssen Sie zustimmen, dass Xiaomi Ihre persönlichen Daten erhebt, verarbeitet und nutzt. In unserer Datenschutzerklärung erfahren Sie, wie wir personenbezogene Daten erheben und verarbeiten. \"Zustimmen\" wählen bedeutet, dass Sie unsere &lt;a href=\"https://privacy.mi.com/all/%1$s_%2$s\">Datenschutzerklärung&lt;/a> und &lt;a href=\"http://www.miui.com/res/doc/eula.html?region=%3$s&amp;amp;lang=%4$s\">Nutzervereinbarung&lt;/a> gelesen und akzeptiert haben.&lt;/Data></string>`
In the second case, we have `&amp;amp;` 
`str = XmlEscape.unescapeXml(str);` will bring lines of this type back to normal (apktool 2.6.1 latest snapshot with addition):
`    <string name="privacy_authorize_dialog_message">&lt;Data>Um grundlegende Funktionen dieses Dienstes nutzen zu können, müssen Sie zustimmen, dass Xiaomi Ihre persönlichen Daten erhebt, verarbeitet und nutzt. In unserer Datenschutzerklärung erfahren Sie, wie wir personenbezogene Daten erheben und verarbeiten. \"Zustimmen\" wählen bedeutet, dass Sie unsere &lt;a href=\"https://privacy.mi.com/all/%1$s_%2$s\">Datenschutzerklärung&lt;/a> und &lt;a href=\"http://www.miui.com/res/doc/eula.html?region=%3$s&amp;lang=%4$s\">Nutzervereinbarung&lt;/a> gelesen und akzeptiert haben.&lt;/Data></string>`
`str = HtmlEscape.unescapeHtml(str)` will make the lines readable:
![Snap2](https://user-images.githubusercontent.com/36408873/137645992-9e3d46d5-6269-4d01-9e5e-371f8102aac6.png)
![Snap3](https://user-images.githubusercontent.com/36408873/137645999-0ab9e065-869a-41ea-9b39-6c16e370d7b2.png)
![Snap4](https://user-images.githubusercontent.com/36408873/137646007-5b726a44-1410-4416-b8f6-d8dec53c836a.png)
:
After this change, apktool 2.6.1 latest snapshot began to decompile Settings.apk
If you or anyone likes it, please create Pull Requests.

**Comment by iBotPeaches** [comment]
thank @pashamcr for the detailed breakdown. It looks like the issue is somewhere prior where we are improperly encoding resources (or just picking a few) while we could probably just use a proper XML encoding process.

**Comment by iBotPeaches** [comment]
Going to close this one for https://github.com/iBotPeaches/Apktool/issues/2890

I believe the path on this is wrong as the root issue is the new attribute splitter we introduced and not related to escaping/unescaping.
