### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by hosseinkhojany** [iBotPeaches/Apktool#2680]
### Information
1. **Apktool Version (`2.6.0`)** -
2. **Operating System (Linux)** -
3. **APK From? (Other/apkpure)** -

### Stacktrace/Logcat
```
I: Using Apktool 2.5.0-dirty on instamod.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /root/.local/share/apktool/framework/1.apk
Exception in thread "main" brut.androlib.err.RawXmlEncounteredException: Could not decode XML
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:149)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:155)
	at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:162)
	at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:204)
	at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:134)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:122)
	at brut.apktool.Main.cmdDecode(Main.java:179)
	at brut.apktool.Main.main(Main.java:82)
Caused by: java.io.EOFException
	at com.google.common.io.LittleEndianDataInputStream.readAndCheckByte(LittleEndianDataInputStream.java:232)
	at com.google.common.io.LittleEndianDataInputStream.readInt(LittleEndianDataInputStream.java:115)
	at brut.util.DataInputDelegate.readInt(DataInputDelegate.java:61)
	at brut.androlib.res.decoder.AXmlResourceParser.doNext(AXmlResourceParser.java:893)
	at brut.androlib.res.decoder.AXmlResourceParser.next(AXmlResourceParser.java:102)
	at brut.androlib.res.decoder.AXmlResourceParser.nextToken(AXmlResourceParser.java:112)
	at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.nextToken(XmlPullParserDelegate.java:105)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:142)
	... 7 more
```

### Steps to Reproduce
1. `sudo apktool d -f /home/khoujani/android/SEC/test/instamod.apk -o smali`

### Frameworks
My Java Version = {
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2, mixed mode)
}
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://www.dl.farsroid.com/ap/Instagram-Pro-8.55(www.Farsroid.com).apk

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? no
3. Are you using the latest apktool version? yes

**Comment by loserq** [comment]
Cause by java.io.EOFException you need check the permission of the application or  command.
