### ISSUE TITLE
[BUG] Can't convert value at index 4 to dimension: type=0x3

### ISSUE THREAD

**Issue by bitk0der** [iBotPeaches/Apktool#2684]
### Information
1. **Apktool Version (`apktool -version`)** - 2.6.0
2. **Operating System (Mac, Linux, Windows)** - Mac
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat

```
10-18 13:35:14.657 31780 31780 E AndroidRuntime: android.view.InflateException: Binary XML file line #14 in com.brandd.app:layout/fragment_login: Can't convert value at index 4 to dimension: type=0x3
10-18 13:35:14.657 31780 31780 E AndroidRuntime: Caused by: java.lang.UnsupportedOperationException: Can't convert value at index 4 to dimension: type=0x3
10-18 13:35:14.657 31780 31780 E AndroidRuntime: 	at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:786)
10-18 13:35:14.657 31780 31780 E AndroidRuntime: 	at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:9195)
10-18 13:35:14.657 31780 31780 E AndroidRuntime: 	at android.widget.LinearLayout$LayoutParams.<init>(LinearLayout.java:2023)
10-18 13:35:14.657 31780 31780 E AndroidRuntime: 	at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:1917)
10-18 13:35:14.657 31780 31780 E AndroidRuntime: 	at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:89)
10-18 13:35:14.657 31780 31780 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1125)
10-18 13:35:14.657 31780 31780 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
10-18 13:35:14.657 31780 31780 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
10-18 13:35:14.657 31780 31780 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
10-18 13:35:14.657 31780 31780 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
10-18 13:35:14.657 31780 31780 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
10-18 13:35:14.657 31780 31780 E AndroidRuntime: 	at e.o.g.d(DataBindingUtil.java:2)
10-18 13:35:14.657 31780 31780 E AndroidRuntime: 	at e.o.g.c(DataBindingUtil.java:1)
10-18 13:35:14.657 31780 31780 E AndroidRuntime: 	at ru.minsvyaz.core.presentation.view.BaseFragment.onCreateView(BaseFragment.kt:1)
10-18 13:35:14.657 31780 31780 E AndroidRuntime: 	at ru.minsvyaz.core.presentation.view.BaseFragmentScreen.onCreateView(BaseFragmentScreen.kt:5)
10-18 13:35:14.657 31780 31780 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:4)
10-18 13:35:14.657 31780 31780 E AndroidRuntime: 	at e.r.d.d0.f(FragmentStateManager.java:16)
10-18 13:35:14.657 31780 31780 E AndroidRuntime: 	at e.r.d.d0.k(FragmentStateManager.java:30)
10-18 13:35:14.657 31780 31780 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.E(FragmentManager.java:68)
10-18 13:35:14.657 31780 31780 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.g0(FragmentManager.java:11)
10-18 13:35:14.657 31780 31780 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.C(FragmentManager.java:14)
10-18 13:35:14.657 31780 31780 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager$g.run(FragmentManager.java:1)
10-18 13:35:14.657 31780 31780 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
10-18 13:35:14.657 31780 31780 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
10-18 13:35:14.657 31780 31780 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:237)
10-18 13:35:14.657 31780 31780 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8167)
10-18 13:35:14.657 31780 31780 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-18 13:35:14.657 31780 31780 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
10-18 13:35:14.657 31780 31780 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

### Steps to Reproduce
1. `java -jar apktool_2.6.0.jar d gavto.apk`
2. `java -jar apktool_2.6.0.jar b gavto -o gavto_patched.apk`
3. `java -jar uber-apk-signer.jar --verbose --ks keys --ksAlias keys --apks gavto_patched.apk -o signed --allowResign`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it. - NO

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? - YES
2. If you are trying to install a modified apk, did you resign it? - YES
3. Are you using the latest apktool version? - YES

**Comment by iBotPeaches** [comment]
Sorry for delay. For issues like this normally have to work backward from a disassembled and rebuilt/disassembled applications to examine resources looking for differences that might cause this.

However without an application - the effort is too difficult. Closing.
