### ISSUE TITLE
[BUG] Exception in thread "main" brut.androlib.err.RawXmlEncounteredException: Could not decode XML

### ISSUE THREAD

**Issue by omarabedyaseen** [iBotPeaches/Apktool#2689]
Hello, my problem is that I cannot decompile the hacked Instagram Pro application
I get this problem:
Exception in thread "main" brut.androlib.err.RawXmlEncounteredException: Could not decode XML
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:145)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:151)
        at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:159)
        at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:193)
        at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:140)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:109)
        at brut.apktool.Main.cmdDecode(Main.java:175)
        at brut.apktool.Main.main(Main.java:78)
Caused by: java.io.EOFException
        at com.google.common.io.LittleEndianDataInputStream.readAndCheckByte(LittleEndianDataInputStream.java:234)
        at com.google.common.io.LittleEndianDataInputStream.readInt(LittleEndianDataInputStream.java:117)
        at brut.util.DataInputDelegate.readInt(DataInputDelegate.java:58)
        at brut.androlib.res.decoder.AXmlResourceParser.doNext(AXmlResourceParser.java:843)
        at brut.androlib.res.decoder.AXmlResourceParser.next(AXmlResourceParser.java:98)
        at brut.androlib.res.decoder.AXmlResourceParser.nextToken(AXmlResourceParser.java:108)
        at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.nextToken(XmlPullParserDelegate.java:105)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:138)
link download apk : https://www.mediafire.com/file/sao5bejpjv9mji0/InstaPro_v8.55.apk/file

**Comment by iBotPeaches** [comment]
O how Mediafire has fallen. Can't even download without certificate warnings.

However, I see this application is a mod really meant to break ToS. That paired with me unable to download this, I'm just going to close this. I don't feel comfortable triaging an issue with an application that is clearly trying to get around some rules.
