### ISSUE TITLE
[BUG] Cannot run recompiled application

### ISSUE THREAD

**Issue by lumaaaaaa** [iBotPeaches/Apktool#2692]
### Information
1. **Apktool Version (`apktool -version`)** - 2.6.0
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat

```
ERR: stack=java.lang.RuntimeException: Unable to start activity ComponentInfo{com.bestbuy.android/com.bestbuy.android.activity.HomeScreen}: android.view.InflateException: Binary XML file line #127: Binary XML file line #127: Error inflating class com.bestbuy.android.view.FloatingButtonComponent
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2666)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6121)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
Caused by: android.view.InflateException: Binary XML file line #127: Binary XML file line #127: Error inflating class com.bestbuy.android.view.FloatingButtonComponent
Caused by: android.view.InflateException: Binary XML file line #127: Error inflating class com.bestbuy.android.view.FloatingButtonComponent
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
	at android.view.LayoutInflater.inflate(<Xposed>)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(:9)
	at androidx.appcompat.app.AppCompatActivity.setContentView(:1)
	at com.bestbuy.android.activity.v2.D0(:1)
	at com.bestbuy.android.activity.v2.setContentView(:3)
	at com.bestbuy.android.activity.ApplicationBar.P1(:1)
	at com.bestbuy.android.activity.ApplicationBar.setContentView(:1)
	at com.bestbuy.android.activity.HomeScreen.onCreate(:15)
	at android.app.Activity.performCreate(Activity.java:6739)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6121)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
Caused by: android.view.InflateException: Binary XML file line #6: Binary XML file line #6: Error inflating class com.bestbuy.android.view.SuperFAB
Caused by: android.view.InflateException: Binary XML file line #6: Error inflating cla
```

### Steps to Reproduce
1. Decompile the apk using apktool
2. Recompile the apk using apktool
3. Sign and install on device
4. Attempt to open the application

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
I believe it was taken down off of apkmirror and other links are a bit sketchy.
https://play.google.com/store/apps/details?id=com.bestbuy.android

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
Yes, that is when this error occurs.

2. If you are trying to install a modified apk, did you resign it?
It was not modified, install just fine.

3. Are you using the latest apktool version?
Yes I am.

### Additional Info
I think that somewhere in the process of decompiling and recompiling some of the files get corrupt or something else, was wondering if anyone else knew what the issue could be? Thanks in advance for taking a look!

**Comment by iBotPeaches** [comment]
None of this is stuff is particularly easy to triage, but seeing Xposed in the stacktrace for sure makes this is hundreds of more variables to check. Haven't checked anything yet though, so leaving it open.

**Comment by iBotPeaches** [comment]
Yeah going to close. I don't have the time for large investigations like this and seeing Xposed in the trace introduces hundreds of other variables to consider.

Unable to confirm.
