### ISSUE TITLE
[BUG] bad utf-8 byte f4 at offset 000000eb

### ISSUE THREAD

**Issue by hkatzdev** [iBotPeaches/Apktool#2695]
### Information
1. **Apktool Version (`apktool -version`)** - 2.6.0
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat

```
I: Baksmaling assets/.910158a220731172f91f5cf7031d24bd.dex...
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: bad utf-8 byte f4 at offset 000000eb
	at org.jf.baksmali.Baksmali.disassembleDexFile(Baksmali.java:92)
	at org.jf.baksmali.Baksmali.disassembleDexFile(Baksmali.java:48)
	at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:100)
	at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:37)
	at brut.androlib.Androlib.decodeSourcesSmali(Androlib.java:98)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:151)
	at brut.apktool.Main.cmdDecode(Main.java:175)
	at brut.apktool.Main.main(Main.java:78)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: bad utf-8 byte f4 at offset 000000eb
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.jf.baksmali.Baksmali.disassembleDexFile(Baksmali.java:86)
	... 7 more
Caused by: java.lang.IllegalArgumentException: bad utf-8 byte f4 at offset 000000eb
	at org.jf.util.Utf8Utils.throwBadUtf8(Utf8Utils.java:284)
	at org.jf.util.Utf8Utils.utf8BytesWithUtf16LengthToString(Utf8Utils.java:220)
	at org.jf.dexlib2.dexbacked.DexReader.readString(DexReader.java:611)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile$5.get(DexBackedDexFile.java:315)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile$5.get(DexBackedDexFile.java:308)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile$6.get(DexBackedDexFile.java:351)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile$6.get(DexBackedDexFile.java:346)
	at org.jf.dexlib2.dexbacked.DexBackedClassDef.getType(DexBackedClassDef.java:110)
	at org.jf.baksmali.Baksmali.disassembleClass(Baksmali.java:112)
	at org.jf.baksmali.Baksmali.access$000(Baksmali.java:46)
	at org.jf.baksmali.Baksmali$1.call(Baksmali.java:76)
	at org.jf.baksmali.Baksmali$1.call(Baksmali.java:74)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### Steps to Reproduce
1. `apktool d base.apk`

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
- Yes
2. Are you using the latest apktool version?
- Yes

It seems to be getting stuck on `assets/.910158a220731172f91f5cf7031d24bd.dex`. All that file says is
```
dex
035
```

**Comment by iBotPeaches** [comment]
This will fixed way back in smali 2.3, so I'm inclined to believe it is corrupted or some form of modification to unpack at runtime and run, since not often to have dex files with random characters stored in /assets.

https://github.com/JesusFreke/smali/issues/688

I could revisit with the file.
