### ISSUE TITLE
[FEAT] Please update ARSCDecoder

### ISSUE THREAD

**Issue by pashamcr** [iBotPeaches/Apktool#2714]
When decompiling a new api 32 framework, I get an error:
`Exception in thread "main" brut.androlib.AndrolibException: Invalid chunk type: expected=0x00000200, got=0x00000206`
Added resources to this framework: `PUBLIC STAGED_ID = 0x01fe0000`
This type is not present in ARSCDecoder
```
        public final static short TYPE_NONE = -1, TYPE_TABLE = 0x0002,
                TYPE_PACKAGE = 0x0200, TYPE_TYPE = 0x0201, TYPE_SPEC_TYPE = 0x0202, TYPE_LIBRARY = 0x0203;
```
It is probably worth updating the types as in ResourceTypes.h https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/libs/androidfw/include/androidfw/ResourceTypes.h#250
for example add TYPE_STAGED_ALIAS = 0x0206

[android.zip](https://github.com/iBotPeaches/Apktool/files/7706540/android.zip)

**Comment by iBotPeaches** [comment]
O god. Spec changes.

Will need the exact commits that introduced all the new properties which I can grab when free.

**Comment by iBotPeaches** [comment]
Commits of interest:

 * https://github.com/aosp-mirror/platform_frameworks_base/commit/7c5f4337fd0b1fbcfe94b035601c67b1e7f47a2e#diff-6cf6553843dc1f76f1db16648195e76c26dbe9b9e661a86ec38fe4f7454a05fc
 * https://github.com/aosp-mirror/platform_frameworks_base/commit/2fedba9a32d9e92344eaf6e9faf5b43e1bc2ae70#diff-629104f2d28f0654d8ca78b0eb588ac4514fbbcfe76b4ad17d223bda40a3e377
 *

**Comment by budsz** [comment]
```
$ apktool d -s Fouad.Whats9.25_By_FouadMODS.apk -f
I: Using Apktool 2.6.1-dirty on Fouad.Whats9.25_By_FouadMODS.apk
I: Loading resource table...
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index -64261 out of bounds for length 22
        at brut.androlib.res.decoder.StringBlock.getStyle(StringBlock.java:344)
        at brut.androlib.res.decoder.StringBlock.getHTML(StringBlock.java:277)
        at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:366)
        at brut.androlib.res.decoder.ARSCDecoder.readEntryData(ARSCDecoder.java:285)
        at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:261)
        at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:184)
        at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:135)
        at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:84)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:50)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:783)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:64)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:56)
        at brut.androlib.Androlib.getResTable(Androlib.java:70)
        at brut.androlib.ApkDecoder.getResTable(ApkDecoder.java:247)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:109)
        at brut.apktool.Main.cmdDecode(Main.java:175)
        at brut.apktool.Main.main(Main.java:79)

$ java -version
openjdk version "17-internal" 2021-09-14
OpenJDK Runtime Environment (build 17-internal+0-adhoc..src)
OpenJDK 64-Bit Server VM (build 17-internal+0-adhoc..src, mixed mode)
```

Could be same issues?

**Comment by PatrykMis** [comment]
@budsz already fixed in master. Just [Build it yourself](https://ibotpeaches.github.io/Apktool/build/)
