### ISSUE TITLE
error while decompiling app

### ISSUE THREAD

**Issue by Mostafa-001** [iBotPeaches/Apktool#2731]
### Information
1. **Apktool Version (`apktool -version`)** -2.5.0-dirty
2. **Operating System (Mac, Linux, Windows)** -Kali Linux
3. **APK From? (Playstore, ROM, Other)** -Other
### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
apktool d Repainter.apk
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool 2.5.0-dirty on Repainter.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/cola/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
Exception in thread "main" java.lang.NullPointerException
        at brut.androlib.res.data.value.ResEnumAttr.decodeValue(ResEnumAttr.java:77)
        at brut.androlib.res.data.value.ResEnumAttr.convertToResXmlFormat(ResEnumAttr.java:42)
        at brut.androlib.res.decoder.ResAttrDecoder.decode(ResAttrDecoder.java:41)
        at brut.androlib.res.decoder.AXmlResourceParser.getAttributeValue(AXmlResourceParser.java:388)
        at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValue(XmlPullParserDelegate.java:69)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:270)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
        at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:84)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:143)
        at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(ResStreamDecoderContainer.java:33)
        at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:141)
        at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:121)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:258)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:129)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:124)
        at brut.apktool.Main.cmdDecode(Main.java:179)
        at brut.apktool.Main.main(Main.java:82)

### APK
sorry app is developed by someone i can still give the apk

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?YEA
2. If you are trying to install a modified apk, did you resign it?NA
3. Are you using the latest apktool version?YEA

**Comment by HamzehTamimi** [comment]
can you send the apk?

**Comment by HamzehTamimi** [comment]
from where did you get repainter.apk?

**Comment by Mostafa-001** [comment]
> 



> from where did you get repainter.apk?

I got from telegram iam trying to edit it

**Comment by HamzehTamimi** [comment]
ca

> > 
> 
> > from where did you get repainter.apk?
> 
> I got from telegram iam trying to edit it

can you send a link?

**Comment by Mostafa-001** [comment]
> ca
> 
> > > 
> > 
> > 
> > > from where did you get repainter.apk?
> > 
> > 
> > I got from telegram iam trying to edit it
> 
> can you send a link?

contact me on telegram

**Comment by HamzehTamimi** [comment]
What is your name on telegram?

**Comment by Schoemiees666** [comment]
Got it in github was looking for nazebuild files

**Comment by iBotPeaches** [comment]
Apologies. Can't really dig into an application without a source app. If you want to send it along (ibotpeaches) (at) gmail (d0t) com

Closing for now.
