### ISSUE TITLE
Can't launch app after building [java.lang.IllegalStateException: This app has been built with an incorrect configuration]

### ISSUE THREAD

**Issue by AbdulrhmanBeatz** [iBotPeaches/Apktool#2781]
### Information
1. **Apktool Version (`apktool -version`)** - 2.6.1
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Play Store

### Stacktrace/Logcat

```
03-13 23:09:00.398  3582  3582 E AndroidRuntime: FATAL EXCEPTION: main
03-13 23:09:00.398  3582  3582 E AndroidRuntime: Process: com.mada.madapay, PID: 3582
03-13 23:09:00.398  3582  3582 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mada.madapay/com.emcrey.app.activities.SupportActivity}: java.lang.IllegalStateException: This app has been built with an incorrect configuration. Please configure your build for VectorDrawableCompat.
03-13 23:09:00.398  3582  3582 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3456)
03-13 23:09:00.398  3582  3582 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3612)
03-13 23:09:00.398  3582  3582 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
03-13 23:09:00.398  3582  3582 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
03-13 23:09:00.398  3582  3582 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
03-13 23:09:00.398  3582  3582 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2073)
03-13 23:09:00.398  3582  3582 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
03-13 23:09:00.398  3582  3582 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:246)
03-13 23:09:00.398  3582  3582 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7690)
03-13 23:09:00.398  3582  3582 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-13 23:09:00.398  3582  3582 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
03-13 23:09:00.398  3582  3582 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
03-13 23:09:00.398  3582  3582 E AndroidRuntime: Caused by: java.lang.IllegalStateException: This app has been built with an incorrect configuration. Please configure your build for VectorDrawableCompat.
03-13 23:09:00.398  3582  3582 E AndroidRuntime:        at o.setFirstBaselineToTopHeight.RemoteActionCompatParcelizer(Unknown Source:6492)
03-13 23:09:00.398  3582  3582 E AndroidRuntime:        at o.setTextAppearance.read(Unknown Source:411)
03-13 23:09:00.398  3582  3582 E AndroidRuntime:        at o.PlaybackStateCompat$CustomAction$MediaBrowserCompat$MediaItem.IconCompatParcelizer(Unknown Source:2093)
03-13 23:09:00.398  3582  3582 E AndroidRuntime:        at o.setHasDecor.MediaBrowserCompat$CustomActionResultReceiver(Unknown Source:794)
03-13 23:09:00.398  3582  3582 E AndroidRuntime:        at o.setHasDecor.setExpandedFormat(Unknown Source:770)
03-13 23:09:00.398  3582  3582 E AndroidRuntime:        at o.setHasDecor.write(Unknown Source:498)
03-13 23:09:00.398  3582  3582 E AndroidRuntime:        at o.ParcelableVolumeInfo.onCreate(Unknown Source:114)
03-13 23:09:00.398  3582  3582 E AndroidRuntime:        at com.emcrey.app.activities.SupportActivity.onCreate(Unknown Source:16)
03-13 23:09:00.398  3582  3582 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8013)
03-13 23:09:00.398  3582  3582 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7993)
03-13 23:09:00.398  3582  3582 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
03-13 23:09:00.398  3582  3582 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3429)
03-13 23:09:00.398  3582  3582 E AndroidRuntime:        ... 11 more
```

### Steps to Reproduce
1. `apktool d .\mada.apk`
2. `apktool b .\mada`
3. `zipalign -p -f 4 .\dist\mada.apk mada_zipaligned.apk`
4. Signing the apk and installing

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
5. If you are trying to install a modified apk, did you resign it? yes
6. Are you using the latest apktool version? yes

**Comment by AbdulrhmanBeatz** [comment]
Link might be useful:
https://stackoverflow.com/a/39531237

**Comment by iBotPeaches** [comment]
Afraid I'm not sure what Apktool can do here. We already attach `--no-version-vectors` during assemble. Without an application source/binary to mess with - can't go further here.

You could try `--use-aapt2` during build and see if that helps out.

**Comment by ductai230894** [comment]
I have same problem, any have update for this
