### ISSUE TITLE
[BUG] ApkTool Res9Patch

### ISSUE THREAD

**Issue by TimScriptov** [iBotPeaches/Apktool#2792]
### Information
1. **Apktool Version (`2.6.1+)** -
2. **Operating System (Android)** -
3. **Apk from? (Other)** -

### Stacktrace/Logcat
2022-03-31 21:44:16.177 15022-7022/com.mcal.apkeditor.pro W/System.err: brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/user/0/com.mcal.apkeditor.pro/files/bin/aapt2, link, -o, /data/user/0/com.mcal.apkeditor.pro/cache/APKTOOL7965496635369529243.tmp, --package-id, 127, --min-sdk-version, 16, --target-sdk-version, 23, --version-code, 5314201, --version-name, 5.31.1.5314201, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -0, assets/channel.mf, -0, assets/meishesdk.lic, -0, META-INF/services/kotlinx.coroutines.CoroutineExceptionHandler, -0, META-INF/services/kotlinx.coroutines.internal.MainDispatcherFactory, -0, META-INF/services/org.xmlpull.v1.XmlPullParserFactory, -0, webp, -0, png, -0, r/a2/b2z.webp, -0, r/a2/b31.webp, -0, r/a2/b32.webp, -0, r/a2/b37.webp, -0, r/a2/b38.webp, -0, r/a7/am9.webp, -0, r/a7/am_.webp, -0, r/a7/anz.webp, -0, r/a7/aos.webp, -0, r/a7/ap5.webp, -0, r/a7/apc.webp, -0, r/a7/apf.webp, -0, r/a7/apk.webp, -0, r/a7/apl.webp, -0, r/a7/apn.webp, -0, r/a7/apo.webp, -0, r/a7/apu.webp, -0, r/a7/apw.webp, -0, r/a7/ap_.webp, -0, r/a7/asb.webp, -0, r/a7/at4.webp, -0, r/a7/at5.webp, -0, r/a7/atf.webp, -0, r/a7/au1.webp, -0, r/a7/auq.webp, -0, r/a7/auw.webp, -0, r/a7/auy.webp, -0, r/a7/auz.webp, -0, r/a7/au_.webp, -0, r/a7/av8.webp, -0, r/a7/ava.webp, -0, r/a7/avd.webp, -0, r/a7/avh.webp, -0, r/a7/avl.webp, -0, r/a7/avq.webp, -0, r/a7/a_c.webp, -0, r/a7/ic_loading_motion.gif, -0, r/a7/pz.webp, -0, r/a8/atf.webp, -0, r/a8/av8.webp, -0, r/a8/axp.webp, -0, r/a8/axq.webp, -0, r/a8/axr.webp, -0, r/a8/axv.webp, -0, r/a8/axz.webp, -0, r/ao/d.webp, -0, r/ao/e.webp, -0, r/ao/f.webp, -0, r/ap/v.json, -0, r/m/a19.webp, -0, r/m/am9.webp, -0, r/m/am_.webp, -0, r/m/anz.webp, -0, r/m/aos.webp, -0, r/m/ap5.webp, -0, r/m/apc.webp, -0, r/m/apf.webp, -0, r/m/apk.webp, -0, r/m/apl.webp, -0, r/m/apm.webp, -0, r/m/apn.webp, -0, r/m/apo.webp, -0, r/m/apu.webp, -0, r/m/apw.webp, -0, r/m/apy.webp, -0, r/m/ap_.webp, -0, r/m/as8.webp, -0, r/m/asa.webp, -0, r/m/asb.webp, -0, r/m/a_c.webp, -0, r/m/pz.webp, -0, r/n/am9.webp, -0, r/n/am_.webp, -0, r/v/am9.webp, -0, r/v/am_.webp, -0, r/v/anz.webp, -0, r/v/aos.webp, -0, r/v/ap5.webp, -0, r/v/apc.webp, -0, r/v/apf.webp, -0, r/v/apk.webp, -0, r/v/apl.webp, -0, r/v/apn.webp, -0, r/v/apo.webp, -0, r/v/apu.webp, -0, r/v/apw.webp, -0, r/v/ap_.webp, -0, r/v/a_c.webp, -0, r/v/pz.webp, -0, r/w/asb.webp, -0, r/z/asb.webp, -0, arsc, -I, /data/user/0/com.mcal.apkeditor.pro/files/bin/1.apk, --manifest, /data/user/0/com.mcal.apkeditor.pro/files/Snaptube/AndroidManifest.xml, /data/user/0/com.mcal.apkeditor.pro/files/Snaptube/build/resources.zip]
2022-03-31 21:44:16.177 15022-7022/com.mcal.apkeditor.pro W/System.err:     at brut.androlib.Androlib.buildResourcesFull(Androlib.java:524)
2022-03-31 21:44:16.178 15022-7022/com.mcal.apkeditor.pro W/System.err:     at brut.androlib.Androlib.buildResources(Androlib.java:439)
2022-03-31 21:44:16.178 15022-7022/com.mcal.apkeditor.pro W/System.err:     at brut.androlib.Androlib.build(Androlib.java:318)
2022-03-31 21:44:16.178 15022-7022/com.mcal.apkeditor.pro W/System.err:     at brut.androlib.Androlib.build(Androlib.java:282)
2022-03-31 21:44:16.178 15022-7022/com.mcal.apkeditor.pro W/System.err:     at com.mcal.apkeditor.ApkComposeThreadNew.run(ApkComposeThreadNew.java:146)
2022-03-31 21:44:16.181 15022-7022/com.mcal.apkeditor.pro W/System.err: Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/user/0/com.mcal.apkeditor.pro/files/bin/aapt2, link, -o, /data/user/0/com.mcal.apkeditor.pro/cache/APKTOOL7965496635369529243.tmp, --package-id, 127, --min-sdk-version, 16, --target-sdk-version, 23, --version-code, 5314201, --version-name, 5.31.1.5314201, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -0, assets/channel.mf, -0, assets/meishesdk.lic, -0, META-INF/services/kotlinx.coroutines.CoroutineExceptionHandler, -0, META-INF/services/kotlinx.coroutines.internal.MainDispatcherFactory, -0, META-INF/services/org.xmlpull.v1.XmlPullParserFactory, -0, webp, -0, png, -0, r/a2/b2z.webp, -0, r/a2/b31.webp, -0, r/a2/b32.webp, -0, r/a2/b37.webp, -0, r/a2/b38.webp, -0, r/a7/am9.webp, -0, r/a7/am_.webp, -0, r/a7/anz.webp, -0, r/a7/aos.webp, -0, r/a7/ap5.webp, -0, r/a7/apc.webp, -0, r/a7/apf.webp, -0, r/a7/apk.webp, -0, r/a7/apl.webp, -0, r/a7/apn.webp, -0, r/a7/apo.webp, -0, r/a7/apu.webp, -0, r/a7/apw.webp, -0, r/a7/ap_.webp, -0, r/a7/asb.webp, -0, r/a7/at4.webp, -0, r/a7/at5.webp, -0, r/a7/atf.webp, -0, r/a7/au1.webp, -0, r/a7/auq.webp, -0, r/a7/auw.webp, -0, r/a7/auy.webp, -0, r/a7/auz.webp, -0, r/a7/au_.webp, -0, r/a7/av8.webp, -0, r/a7/ava.webp, -0, r/a7/avd.webp, -0, r/a7/avh.webp, -0, r/a7/avl.webp, -0, r/a7/avq.webp, -0, r/a7/a_c.webp, -0, r/a7/ic_loading_motion.gif, -0, r/a7/pz.webp, -0, r/a8/atf.webp, -0, r/a8/av8.webp, -0, r/a8/axp.webp, -0, r/a8/axq.webp, -0, r/a8/axr.webp, -0, r/a8/axv.webp, -0, r/a8/axz.webp, -0, r/ao/d.webp, -0, r/ao/e.webp, -0, r/ao/f.webp, -0, r/ap/v.json, -0, r/m/a19.webp, -0, r/m/am9.webp, -0, r/m/am_.webp, -0, r/m/anz.webp, -0, r/m/aos.webp, -0, r/m/ap5.webp, -0, r/m/apc.webp, -0, r/m/apf.webp, -0, r/m/apk.webp, -0, r/m/apl.webp, -0, r/m/apm.webp, -0, r/m/apn.webp, -0, r/m/apo.webp, -0, r/m/apu.webp, -0, r/m/apw.webp, -0, r/m/apy.webp, -0, r/m/ap_.webp, -0, r/m/as8.webp, -0, r/m/asa.webp, -0, r/m/asb.webp, -0, r/m/a_c.webp, -0, r/m/pz.webp, -0, r/n/am9.webp, -0, r/n/am_.webp, -0, r/v/am9.webp, -0, r/v/am_.webp, -0, r/v/anz.webp, -0, r/v/aos.webp, -0, r/v/ap5.webp, -0, r/v/apc.webp, -0, r/v/apf.webp, -0, r/v/apk.webp, -0, r/v/apl.webp, -0, r/v/apn.webp, -0, r/v/apo.webp, -0, r/v/apu.webp, -0, r/v/apw.webp, -0, r/v/ap_.webp, -0, r/v/a_c.webp, -0, r/v/pz.webp, -0, r/w/asb.webp, -0, r/z/asb.webp, -0, arsc, -I, /data/user/0/com.mcal.apkeditor.pro/files/bin/1.apk, --manifest, /data/user/0/com.mcal.apkeditor.pro/files/Snaptube/AndroidManifest.xml, /data/user/0/com.mcal.apkeditor.pro/files/Snaptube/build/resources.zip]
2022-03-31 21:44:16.182 15022-7022/com.mcal.apkeditor.pro W/System.err:     at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:500)
2022-03-31 21:44:16.182 15022-7022/com.mcal.apkeditor.pro W/System.err:     at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:635)
2022-03-31 21:44:16.182 15022-7022/com.mcal.apkeditor.pro W/System.err:     at brut.androlib.Androlib.buildResourcesFull(Androlib.java:499)
2022-03-31 21:44:16.182 15022-7022/com.mcal.apkeditor.pro W/System.err: 	... 4 more
2022-03-31 21:44:16.183 15022-7022/com.mcal.apkeditor.pro W/System.err: Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/user/0/com.mcal.apkeditor.pro/files/bin/aapt2, link, -o, /data/user/0/com.mcal.apkeditor.pro/cache/APKTOOL7965496635369529243.tmp, --package-id, 127, --min-sdk-version, 16, --target-sdk-version, 23, --version-code, 5314201, --version-name, 5.31.1.5314201, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -0, assets/channel.mf, -0, assets/meishesdk.lic, -0, META-INF/services/kotlinx.coroutines.CoroutineExceptionHandler, -0, META-INF/services/kotlinx.coroutines.internal.MainDispatcherFactory, -0, META-INF/services/org.xmlpull.v1.XmlPullParserFactory, -0, webp, -0, png, -0, r/a2/b2z.webp, -0, r/a2/b31.webp, -0, r/a2/b32.webp, -0, r/a2/b37.webp, -0, r/a2/b38.webp, -0, r/a7/am9.webp, -0, r/a7/am_.webp, -0, r/a7/anz.webp, -0, r/a7/aos.webp, -0, r/a7/ap5.webp, -0, r/a7/apc.webp, -0, r/a7/apf.webp, -0, r/a7/apk.webp, -0, r/a7/apl.webp, -0, r/a7/apn.webp, -0, r/a7/apo.webp, -0, r/a7/apu.webp, -0, r/a7/apw.webp, -0, r/a7/ap_.webp, -0, r/a7/asb.webp, -0, r/a7/at4.webp, -0, r/a7/at5.webp, -0, r/a7/atf.webp, -0, r/a7/au1.webp, -0, r/a7/auq.webp, -0, r/a7/auw.webp, -0, r/a7/auy.webp, -0, r/a7/auz.webp, -0, r/a7/au_.webp, -0, r/a7/av8.webp, -0, r/a7/ava.webp, -0, r/a7/avd.webp, -0, r/a7/avh.webp, -0, r/a7/avl.webp, -0, r/a7/avq.webp, -0, r/a7/a_c.webp, -0, r/a7/ic_loading_motion.gif, -0, r/a7/pz.webp, -0, r/a8/atf.webp, -0, r/a8/av8.webp, -0, r/a8/axp.webp, -0, r/a8/axq.webp, -0, r/a8/axr.webp, -0, r/a8/axv.webp, -0, r/a8/axz.webp, -0, r/ao/d.webp, -0, r/ao/e.webp, -0, r/ao/f.webp, -0, r/ap/v.json, -0, r/m/a19.webp, -0, r/m/am9.webp, -0, r/m/am_.webp, -0, r/m/anz.webp, -0, r/m/aos.webp, -0, r/m/ap5.webp, -0, r/m/apc.webp, -0, r/m/apf.webp, -0, r/m/apk.webp, -0, r/m/apl.webp, -0, r/m/apm.webp, -0, r/m/apn.webp, -0, r/m/apo.webp, -0, r/m/apu.webp, -0, r/m/apw.webp, -0, r/m/apy.webp, -0, r/m/ap_.webp, -0, r/m/as8.webp, -0, r/m/asa.webp, -0, r/m/asb.webp, -0, r/m/a_c.webp, -0, r/m/pz.webp, -0, r/n/am9.webp, -0, r/n/am_.webp, -0, r/v/am9.webp, -0, r/v/am_.webp, -0, r/v/anz.webp, -0, r/v/aos.webp, -0, r/v/ap5.webp, -0, r/v/apc.webp, -0, r/v/apf.webp, -0, r/v/apk.webp, -0, r/v/apl.webp, -0, r/v/apn.webp, -0, r/v/apo.webp, -0, r/v/apu.webp, -0, r/v/apw.webp, -0, r/v/ap_.webp, -0, r/v/a_c.webp, -0, r/v/pz.webp, -0, r/w/asb.webp, -0, r/z/asb.webp, -0, arsc, -I, /data/user/0/com.mcal.apkeditor.pro/files/bin/1.apk, --manifest, /data/user/0/com.mcal.apkeditor.pro/files/Snaptube/AndroidManifest.xml, /data/user/0/com.mcal.apkeditor.pro/files/Snaptube/build/resources.zip]
2022-03-31 21:44:16.183 15022-7022/com.mcal.apkeditor.pro W/System.err:     at brut.util.OS.exec(OS.java:99)
2022-03-31 21:44:16.183 15022-7022/com.mcal.apkeditor.pro W/System.err:     at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:496)
2022-03-31 21:44:16.183 15022-7022/com.mcal.apkeditor.pro W/System.err: 	... 6 more
2022-03-31 21:44:16.202 15022-15022/com.mcal.apkeditor.pro E/DEBUG: notification hided.
2022-03-31 21:44:16.209 15022-15022/com.mcal.apkeditor.pro D/error: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/user/0/com.mcal.apkeditor.pro/files/bin/aapt2, link, -o, /data/user/0/com.mcal.apkeditor.pro/cache/APKTOOL7965496635369529243.tmp, --package-id, 127, --min-sdk-version, 16, --target-sdk-version, 23, --version-code, 5314201, --version-name, 5.31.1.5314201, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -0, assets/channel.mf, -0, assets/meishesdk.lic, -0, META-INF/services/kotlinx.coroutines.CoroutineExceptionHandler, -0, META-INF/services/kotlinx.coroutines.internal.MainDispatcherFactory, -0, META-INF/services/org.xmlpull.v1.XmlPullParserFactory, -0, webp, -0, png, -0, r/a2/b2z.webp, -0, r/a2/b31.webp, -0, r/a2/b32.webp, -0, r/a2/b37.webp, -0, r/a2/b38.webp, -0, r/a7/am9.webp, -0, r/a7/am_.webp, -0, r/a7/anz.webp, -0, r/a7/aos.webp, -0, r/a7/ap5.webp, -0, r/a7/apc.webp, -0, r/a7/apf.webp, -0, r/a7/apk.webp, -0, r/a7/apl.webp, -0, r/a7/apn.webp, -0, r/a7/apo.webp, -0, r/a7/apu.webp, -0, r/a7/apw.webp, -0, r/a7/ap_.webp, -0, r/a7/asb.webp, -0, r/a7/at4.webp, -0, r/a7/at5.webp, -0, r/a7/atf.webp, -0, r/a7/au1.webp, -0, r/a7/auq.webp, -0, r/a7/auw.webp, -0, r/a7/auy.webp, -0, r/a7/auz.webp, -0, r/a7/au_.webp, -0, r/a7/av8.webp, -0, r/a7/ava.webp, -0, r/a7/avd.webp, -0, r/a7/avh.webp, -0, r/a7/avl.webp, -0, r/a7/avq.webp, -0, r/a7/a_c.webp, -0, r/a7/ic_loading_motion.gif, -0, r/a7/pz.webp, -0, r/a8/atf.webp, -0, r/a8/av8.webp, -0, r/a8/axp.webp, -0, r/a8/axq.webp, -0, r/a8/axr.webp, -0, r/a8/axv.webp, -0, r/a8/axz.webp, -0, r/ao/d.webp, -0, r/ao/e.webp, -0, r/ao/f.webp, -0, r/ap/v.json, -0, r/m/a19.webp, -0, r/m/am9.webp, -0, r/m/am_.webp, -0, r/m/anz.webp, -0, r/m/aos.webp, -0, r/m/ap5.webp, -0, r/m/apc.webp, -0, r/m/apf.webp, -0, r/m/apk.webp, -0, r/m/apl.webp, -0, r/m/apm.webp, -0, r/m/apn.webp, -0, r/m/apo.webp, -0, r/m/apu.webp, -0, r/m/apw.webp, -0, r/m/apy.webp, -0, r/m/ap_.webp, -0, r/m/as8.webp, -0, r/m/asa.webp, -0, r/m/asb.webp, -0, r/m/a_c.webp, -0, r/m/pz.webp, -0, r/n/am9.webp, -0, r/n/am_.webp, -0, r/v/am9.webp, -0, r/v/am_.webp, -0, r/v/anz.webp, -0, r/v/aos.webp, -0, r/v/ap5.webp, -0, r/v/apc.webp, -0, r/v/apf.webp, -0, r/v/apk.webp, -0, r/v/apl.webp, -0, r/v/apn.webp, -0, r/v/apo.webp, -0, r/v/apu.webp, -0, r/v/apw.webp, -0, r/v/ap_.webp, -0, r/v/a_c.webp, -0, r/v/pz.webp, -0, r/w/asb.webp, -0, r/z/asb.webp, -0, arsc, -I, /data/user/0/com.mcal.apkeditor.pro/files/bin/1.apk, --manifest, /data/user/0/com.mcal.apkeditor.pro/files/Snaptube/AndroidManifest.xml, /data/user/0/com.mcal.apkeditor.pro/files/Snaptube/build/resources.zip]

```

### Steps to Reproduce
1. `apktool `

### Frameworks
frame v31

### APK
Snaptube.apk

### Questions to ask before submission
Help me please fix it

**Comment by TimScriptov** [comment]
Snaptube.apk have name.webp resources - file length 0kb

**Comment by TimScriptov** [comment]
Probably embedded fake files through resource encryption

**Comment by iBotPeaches** [comment]
That might be possible, but a few things here.

* This looks like its running via Android - never been officially supported.
* I don't see an application so not really possible to investigate.

Thanks for the report - closing.
