### ISSUE TITLE
[BUG] Crash when using apktool to decompile & then recompile (possibly apktool unable to parse a resource)

### ISSUE THREAD

**Issue by Macmee** [iBotPeaches/Apktool#2800]
I'm trying to decompile the instagram apk with apktool. Right now for leaning I'm literally just decompiling, recompiling and resigning without any other changes just to test to see if it works:

    apktool d -f -r ~/Downloads/Instagram_v230.0.0.20.108_apkpure.com.apk
    apktool b ~/Downloads/Instagram_v230.0.0.20.108_apkpure.com -o ~/modified.apk
    java -jar ./uber-apk-signer.jar --apks ~/modified.apk

(sourcing the APK from here https://apkpure.com/instagram-android/com.instagram.android/download?from=details)

but when I install this onto my device I always get this cash:

    04-15 10:38:58.394 25598 25598 E AndroidRuntime: FATAL EXCEPTION: main
    04-15 10:38:58.394 25598 25598 E AndroidRuntime: Process: com.instagram.android, PID: 25598
    04-15 10:38:58.394 25598 25598 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate application com.instagram.app.InstagramAppShell package com.instagram.android: java.lang.RuntimeException: Failed to parse XML configuration from fb_network_security_config
    04-15 10:38:58.394 25598 25598 E AndroidRuntime:     at android.app.LoadedApk.makeApplication(LoadedApk.java:1464)
    04-15 10:38:58.394 25598 25598 E AndroidRuntime:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7441)
    04-15 10:38:58.394 25598 25598 E AndroidRuntime:     at android.app.ActivityThread.access$1700(ActivityThread.java:310)
    04-15 10:38:58.394 25598 25598 E AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2281)
    04-15 10:38:58.394 25598 25598 E AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:106)
    04-15 10:38:58.394 25598 25598 E AndroidRuntime:     at android.os.Looper.loopOnce(Looper.java:226)
    04-15 10:38:58.394 25598 25598 E AndroidRuntime:     at android.os.Looper.loop(Looper.java:313)
    04-15 10:38:58.394 25598 25598 E AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:8646)
    04-15 10:38:58.394 25598 25598 E AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
    04-15 10:38:58.394 25598 25598 E AndroidRuntime:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
    04-15 10:38:58.394 25598 25598 E AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
    04-15 10:38:58.394 25598 25598 E AndroidRuntime: Caused by: java.lang.RuntimeException: Failed to parse XML configuration from fb_network_security_config
    04-15 10:38:58.394 25598 25598 E AndroidRuntime:     at android.security.net.config.XmlConfigSource.ensureInitialized(XmlConfigSource.java:89)
    04-15 10:38:58.394 25598 25598 E AndroidRuntime:     at android.security.net.config.XmlConfigSource.getPerDomainConfigs(XmlConfigSource.java:55)
    04-15 10:38:58.394 25598 25598 E AndroidRuntime:     at android.security.net.config.ManifestConfigSource.getPerDomainConfigs(ManifestConfigSource.java:45)
    04-15 10:38:58.394 25598 25598 E AndroidRuntime:     at android.security.net.config.ApplicationConfig.ensureInitialized(ApplicationConfig.java:175)
    04-15 10:38:58.394 25598 25598 E AndroidRuntime:     at android.security.net.config.ApplicationConfig.isCleartextTrafficPermitted(ApplicationConfig.java:130)
    04-15 10:38:58.394 25598 25598 E AndroidRuntime:     at android.security.net.config.NetworkSecurityConfigProvider.handleNewApplication(NetworkSecurityConfigProvider.java:60)
    04-15 10:38:58.394 25598 25598 E AndroidRuntime:     at android.app.LoadedApk.makeApplication(LoadedApk.java:1455)
    04-15 10:38:58.394 25598 25598 E AndroidRuntime:     ... 10 more
    04-15 10:38:58.394 25598 25598 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: File r/chp.xml from xml type xml resource ID #0x7f150001
    04-15 10:38:58.394 25598 25598 E AndroidRuntime:     at android.content.res.ResourcesImpl.loadXmlResourceParser(ResourcesImpl.java:1381)
    04-15 10:38:58.394 25598 25598 E AndroidRuntime:     at android.content.res.Resources.loadXmlResourceParser(Resources.java:2555)
    04-15 10:38:58.394 25598 25598 E AndroidRuntime:     at android.content.res.Resources.loadXmlResourceParser(Resources.java:2531)
    04-15 10:38:58.394 25598 25598 E AndroidRuntime:     at android.content.res.Resources.getXml(Resources.java:1386)
    04-15 10:38:58.394 25598 25598 E AndroidRuntime:     at android.security.net.config.XmlConfigSource.ensureInitialized(XmlConfigSource.java:82)
    04-15 10:38:58.394 25598 25598 E AndroidRuntime:     ... 16 more

I'm not modifying the apk at all and yet I get this crash when I try to run it. It looks like a resource file isn't found to me -- maybe I need to use a different flag when decompiling, or perhaps apktool is unable to handle one of the resources in the api?

**Comment by Macmee** [comment]
update:

My apologies, after searching through more issues here I encountered this https://github.com/iBotPeaches/Apktool/issues/2670

and @MartinDupont's comments on march 10 were the solution. If anyone else finds this issue apparently instagram is doing some creative things when it comes to their resource loading, you have to:

1. delete assets/drawables.bin
2. in `/res/values/styles.xml` remove any duplicate attributes should you receive an error about them when running `apktool b`.
