### ISSUE TITLE
[BUG] APKTool invalid chunk type error

### ISSUE THREAD

**Issue by Squareheron942** [iBotPeaches/Apktool#2809]
When decompiling a system file (/system/framework/framework-res.apk), it fails and gives this message:

I: Using Apktool 2.6.1 on framework-res.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Invalid chunk type: expected=0x00000200, got=0x00000206
	at brut.androlib.res.decoder.ARSCDecoder.checkChunkType(ARSCDecoder.java:549)
	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:90)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:84)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:50)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:783)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:64)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:56)
	at brut.androlib.Androlib.getResTable(Androlib.java:70)
	at brut.androlib.ApkDecoder.getResTable(ApkDecoder.java:247)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:109)
	at brut.apktool.Main.cmdDecode(Main.java:175)
	at brut.apktool.Main.main(Main.java:79)

Is there any way to fix this and decompile the APK?

**Comment by iBotPeaches** [comment]
This support for staged aliases (`0x0206`) is on bleeding edge master right now attempting to be stabilized. So I'm closing as resolved in https://github.com/iBotPeaches/Apktool/pull/2743/files
