### ISSUE TITLE
[BUG] Error: attribute android:dataExtractionRules not found

### ISSUE THREAD

**Issue by swetasamasti2310** [iBotPeaches/Apktool#2834]
Compiling Apk with attribute dataExtractionRules fails. DataExtractionRules attribute got added in android 12 i.e. app targetting android 12 (https://developer.android.com/guide/topics/data/autobackup)
Information
Apktool Version (apktool -version) - 2.6.1
Operating System (Mac, Linux, Windows) - All
APK From? (Playstore, ROM, Other) - Any app having manifest of android:dataExtractionRules
Stacktrace/Logcat
main | ApkUtils | E | Compiling apk encountered error. Apk : 
W: /decompiled/AndroidManifest.xml:3: error: attribute android:dataExtractionRules not found.
W: error: failed processing manifest.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/z9/lmrnq8rs7r11ryfnksxbtr1w0000gn/T/brut_util_Jar_75538096012336025693464185194562265035.tmp, link, -o, /var/folders/z9/lmrnq8rs7r11ryfnksxbtr1w0000gn/T/APKTOOL6219217766914248629.tmp, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 31, --version-code, 109, --version-name, 109.0, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, -e, /var/folders/z9/lmrnq8rs7r11ryfnksxbtr1w0000gn/T/APKTOOL560981117956261954.tmp, -0, arsc, -I, /Users/swetakumari/Library/apktool/framework/1.apk, --manifest, 

Steps to Reproduce
apktool
Add android:dataExtractionRules in the apk and try to recompile.

Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(.apks that live in /system/framework or /system/priv-app)

APK
Any apk with dataExtractionRules attribute enabled in AndroidManifest file will have this error. PFA for the sample apk.
[SwetaSampleApp.zip](https://github.com/iBotPeaches/Apktool/files/8908655/SwetaSampleApp.zip)

Questions to ask before submission
Have you tried apktool d, apktool b without changing anything? - Yes
If you are trying to install a modified apk, did you reassign it? - Yes
Are you using the latest apktool version? - Yes

**Comment by swetasamasti2310** [comment]
Do we have any tentative date when the 2.6.2v will get released with this data extraction attribute fix involved ?

**Comment by biopsin** [comment]
Im just adding myself to the issue as Ive hit this with berrybrowser, to get notified if I can help in testing..
```
I: Using Apktool 2.6.1
I: Smaling smali folder into classes.dex...
I: Building resources...
W: /home/userx/build/ADTools/decompiled/berry.apk/AndroidManifest.xml:42: error: No resource identifier found for attribute 'dataExtractionRules' in package 'android'
W:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_14654990548826782454827711967953891264.tmp, p, --forced-package-id, 127, --min-sdk-version, 25, --target-sdk-version, 29, --version-code, 359030, --version-name, 3.59.3,
--no-version-vectors, -F, /tmp/APKTOOL13464032806987482991.tmp, -0, arsc, -I, /home/userx/.local/share/apktool/framework/1.apk, -S, /home/userx/build/ADTools/decompiled/berry.apk/res, -M,
/home/userx/build/ADTools/decompiled/berry.apk/AndroidManifest.xml]

```

**Comment by iBotPeaches** [comment]
aapt binaries + latest framework were added to master. So I will revisit this now.

**Comment by TimScriptov** [comment]
@iBotPeaches Hello, please add the build aapt, aapt2 and for Android arm7, arm64, x86, x64

**Comment by hackermondev** [comment]
@iBotPeaches when will a fix be complete?

**Comment by iBotPeaches** [comment]
> @iBotPeaches when will a fix be complete?

I don't know - accepting any fixes or research.

**Comment by takeh1k0** [comment]
FYI:

For me, the following method worked fine:
```
$ git clone https://github.com/iBotPeaches/Apktool.git
$ cd Apktool
$ ./gradlew build shadowJar
$ cp brut.apktool/apktool-cli/build/libs/apktool-cli-all.jar apktool.jar
$ java -jar apktool.jar empty-framework-dir --force
$ # and use the apktool.jar instead of one I used..
```

**Comment by guplem** [comment]
I am facing the same issue here...

**Comment by swetasamasti2310** [comment]
Hi
@iBotPeaches Please confirm if this bug "attribute android:dataExtractionRules not found" is fixed in the latest apktool which is 2.7.0

**Comment by dhd0004** [comment]
Same problem with last version
```
java -jar /opt/tools/10_Android/apktool/apktool_2.7.0.jar b --use-aapt2 MiO2_resources



Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool 2.7.0
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: <APK>_resources/AndroidManifest.xml:17: error: attribute android:dataExtractionRules not found.
```

**Comment by Schwartzblat** [comment]
Same with apktool 2.7.0

**Comment by krzys-h** [comment]
For me the solution turned out to be
```
rm -rf ~/.local/share/apktool
```
as recommended in https://github.com/iBotPeaches/Apktool/issues/2712#issuecomment-1100296423

**Comment by RichardHoOoOo** [comment]
> For me the solution turned out to be
> 
> ```
> rm -rf ~/.local/share/apktool
> ```
> 
> as recommended in [#2712 (comment)](https://github.com/iBotPeaches/Apktool/issues/2712#issuecomment-1100296423)

This also works for me.

**Comment by RenzoPH** [comment]
Hi everyone - I would like to ask, if this issue are already resolve?

Also, I encountering this issue right now in my android build. I am using hybrid app which is the ionic capacitor


	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
	at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:63)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
	at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:60)
	at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:200)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
	... 3 more


* Get more help at https://help.gradle.org/

BUILD FAILED in 2m 11s
40 actionable tasks: 40 executed

**Comment by iBotPeaches** [comment]
Was probably fixed when we updated the internal frameworks, but upcoming release (if it isn't) will resolve this.

```
➜  2834 apktool d sweta-tracks-debug.apk -r -f
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool 2.7.1-7a22af-SNAPSHOT on sweta-tracks-debug.apk
I: Copying raw manifest...
I: Copying raw resources...
I: Baksmaling classes.dex...
I: Baksmaling classes4.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes2.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  2834 apktool b sweta-tracks-debug --use-aapt2
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool 2.7.1-7a22af-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes4 folder into classes4.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether resources has changed...
I: Copying raw resources...
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk into: sweta-tracks-debug/dist/sweta-tracks-debug.apk
➜  2834 
```

**Comment by Owyn** [comment]
I'm using 2.9.0 and it's still there?
![image](https://github.com/iBotPeaches/Apktool/assets/1309656/63b22c26-a398-47e8-951d-5575a35b3bc
[example_app.zip](https://github.com/iBotPeaches/Apktool/files/13243504/example_app.zip)
4)

````
$ S:\ProgramData\Oracle\Java\javapath\java.exe -Xmx512m -jar V:\Data\apktool_2.9.0.jar b V:\Downloads\com.evgeniysharafan.tabatatimer_org.apk-decompiled --use-aapt2
I: Using Apktool 2.9.0
I: Checking whether sources has changed...
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: V:\Downloads\com.evgeniysharafan.tabatatimer_org.apk-decompiled\AndroidManifest.xml:35: error: attribute android:dataExtractionRules not found.
W: V:\Downloads\com.evgeniysharafan.tabatatimer_org.apk-decompiled\AndroidManifest.xml:35: error: attribute android:enableOnBackInvokedCallback not found.
W: V:\Downloads\com.evgeniysharafan.tabatatimer_org.apk-decompiled\AndroidManifest.xml:35: error: attribute android:localeConfig not found.
W: error: failed processing manifest.
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [S:\Users\owyn\AppData\Local\Temp\brut_util_Jar_62898018191614175125414952401869359530.tmp, link, -o, S:\Users\owyn\AppData\Local\Temp\APKTOOL2595703900026841314.tmp, --package-id, 127, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 502004, --version-name, 5.2.4, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --no-compile-sdk-metadata, -e, S:\Users\owyn\AppData\Local\Temp\APKTOOL1676057706290569081.tmp, -0, arsc, -I, S:\Users\owyn\AppData\Local\apktool\framework\1.apk, --manifest, V:\Downloads\com.evgeniysharafan.tabatatimer_org.apk-decompiled\AndroidManifest.xml, V:\Downloads\com.evgeniysharafan.tabatatimer_org.apk-decompiled\build\resources.zip]
Process exited with code 1.
````

**Comment by iBotPeaches** [comment]
@Owyn - Can you run `apktool empty-framework-dir` and try again?

**Comment by Owyn** [comment]
> @Owyn - Can you run `apktool empty-framework-dir` and try again?

````
S:\Users\owyn>apktool empty-framework-dir
W: Can't empty framework directory, no file found at: S:\Users\owyn\AppData\Local\apktool\framework\1.apk
````

**Comment by RedStoneMatt** [comment]
Still erroring on this with v2.9.3

Trying to rebuild the discord app (v167.21) after no edits throws:
```
W: <Apk>\res\values-v31\colors.xml:3: error: resource android:color/Teal_800 not found.
W: <Apk>\res\values-v31\colors.xml:4: error: resource android:color/Teal_700 not found.
W: <Apk>\res\values-v31\colors.xml:5: error: resource android:color/Blue_700 not found.
W: <Apk>\res\values-v31\colors.xml:6: error: resource android:color/Red_800 not found.
W: <Apk>\res\values-v31\colors.xml:7: error: resource android:color/Red_700 not found.
W: <Apk>\res\values-v31\colors.xml:8: error: resource android:color/Purple_800 not found.
W: <Apk>\res\values-v31\colors.xml:9: error: resource android:color/Purple_700 not found.
W: <Apk>\res\values-v31\colors.xml:10: error: resource android:color/Pink_800 not found.
W: <Apk>\res\values-v31\colors.xml:11: error: resource android:color/Pink_700 not found.
W: <Apk>\res\values-v31\colors.xml:12: error: resource android:color/Indigo_800 not found.
W: <Apk>\res\values-v31\colors.xml:13: error: resource android:color/Indigo_700 not found.
W: <Apk>\res\values-v31\colors.xml:15: error: resource android:color/Blue_800 not found.
W: <Apk>\res\values-v31\colors.xml:21: error: resource android:color/accessibility_focus_highlight not found.
W: <Apk>\res\values-v31\colors.xml:44: error: resource android:color/background_leanback_light not found.
```

Changing ``@android`` to ``@*android`` on the mentionned resources didn't change a thing. Running ``apktool empty-framework-dir`` didn't either.
