### ISSUE TITLE
[BUG] Recompilation breaks app

### ISSUE THREAD

**Issue by Luffitys** [iBotPeaches/Apktool#2848]
### Information
1. **Apktool Version (`apktool -version`)** - latest Actions binary
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - gcam ports website, see below

### Stacktrace/Logcat

```
E libprotobuf-native: [libprotobuf ERROR external/protobuf/src/google/protobuf/message_lite.cc:123] Can't parse message of type "sns_flicker_event" because it is missing required fields: (cannot determine missing fields for lite message)
E libprotobuf-native: [libprotobuf ERROR external/protobuf/src/google/protobuf/message_lite.cc:123] Can't parse message of type "sns_flicker_event" because it is missing required fields: (cannot determine missing fields for lite message)
W CAM_A   : OneCamera failed to open, closing lifetime.
W CAM_A   : java.lang.IllegalStateException: Error updating preview surfaceview
W CAM_A   : 	at ewo.a(Unknown Source:175)
W CAM_A   : 	at pfc.f(Unknown Source:29)
W CAM_A   : 	at pfe.run(Unknown Source:483)
W CAM_A   : 	at pgm.DIorozrreOKMQoKk(Unknown Source:0)
W CAM_A   : 	at pgm.execute(Unknown Source:8)
W CAM_A   : 	at pfs.q(Unknown Source:15)
W CAM_A   : 	at pfs.l(Unknown Source:257)
W CAM_A   : 	at pfs.a(Unknown Source:144)
W CAM_A   : 	at pfw.run(Unknown Source:129)
W CAM_A   : 	at bwx.run(Unknown Source:166)
W CAM_A   : 	at android.os.Handler.handleCallback(Unknown Source:2)
W CAM_A   : 	at android.os.Handler.dispatchMessage(Unknown Source:4)
W CAM_A   : 	at android.os.Looper.loopOnce(Unknown Source:176)
W CAM_A   : 	at android.os.Looper.loop(Unknown Source:76)
W CAM_A   : 	at android.app.ActivityThread.main(Unknown Source:138)
W CAM_A   : 	at java.lang.reflect.Method.invoke(Native Method)
W CAM_A   : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
W CAM_A   : 	at com.android.internal.os.ZygoteInit.main(Unknown Source:309)
W CAM_A   : Caused by: java.lang.NullPointerException
W CAM_A   : 	at jmy.<init>(Unknown Source:1352)
W CAM_A   : 	at hct.get(Unknown Source:1316)
W CAM_A   : 	at pym.get(Unknown Source:49)
W CAM_A   : 	at jne.f(Unknown Source:392)
W CAM_A   : 	at ghn.a(Unknown Source:46)
W CAM_A   : 	at pfu.f(Unknown Source:14)
W CAM_A   : 	at pfw.run(Unknown Source:256)
W CAM_A   : 	... 9 more
```

### Steps to Reproduce
1. `apktool  b`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://www.celsoazevedo.com/files/android/google-camera/dev-bsg/f/dl93/

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? - yes
3. If you are trying to install a modified apk, did you resign it? - yes
4. Are you using the latest apktool version? - yes

**Comment by iBotPeaches** [comment]
Well not sure, that stacktrace is mostly redacted and the warnings at the top look to be from within AOSP itself. So not sure we yet have a pinpoint to what file in the re-assembly could be malformed.

**Comment by eladkarako** [comment]
I've got 

```txt
WARNING: error: failed linking references.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Temp\brut_util_Jar_157670865398957361001280479851670459114.tmp, link, -o, C:\Temp\APKTOOL7945945504967592048.tmp, --package-id, 127, --min-sdk-version, 29, --target-sdk-version, 29, --version-code, 65075802, --version-name, 8.5.300.450594193.08, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, C:\Temp\APKTOOL11210941466764324706.tmp, -0, arsc, -I, C:\Users\Elad\AppData\Local\apktool\framework\1.apk, --manifest, D:\DOS\android\project_MGC_8_5_300_A10_V1_MGC\AndroidManifest.xml, -v, D:\DOS\android\project_MGC_8_5_300_A10_V1_MGC\build\resources.zip]

[log_last_decode.log](https://github.com/iBotPeaches/Apktool/files/9483563/log_last_decode.log)

- delete `unknown/stamp-cert-sha256`  
- remove `stamp-cert-sha256: '8'` from `apktool.yml`  

[log_last_build.log](https://github.com/iBotPeaches/Apktool/files/9483564/log_last_build.log)

**Comment by iBotPeaches** [comment]
Sorry - just going to close. Have no insight into this, so chalking it up as a "magic apk".

```
➜  2848 apktool d MGC_8.5.300_A10_V1_MGC.apk -f
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool 2.6.2-eb105f-SNAPSHOT on MGC_8.5.300_A10_V1_MGC.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
```
