### ISSUE TITLE
[Suspection of a bug] Crash (exception) on startup

### ISSUE THREAD

**Issue by mdziczkowski** [iBotPeaches/Apktool#2861]
### Information
1. **Apktool Version (`apktool -version`)** - v2.6.1
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - Sourceforge.net (as *.jar)

### Stacktrace/Logcat

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: brut/apktool/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:808)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:443)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:65)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:349)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:348)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:430)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:323)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
```

### Steps to Reproduce
1. `apktool ` <file_name.apk>

### Frameworks
n/a

### APK
any

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?

no, it's first use

2. If you are trying to install a modified apk, did you resign it?

no

3. Are you using the latest apktool version?

yes

**Comment by iBotPeaches** [comment]
This error commonly means you are on a lower java version than needed. We require Java8.

**Comment by mdziczkowski** [comment]
I have a question: why have you decided that the Java 8 is the minimum instead of Java 7 ?

Many still use (for example as crash recovery systems) Linux that has only Java 6 and 7 avaliable to install and due various reasons cannot upgrade it to a later version to get Java 8 (and above)

**Comment by iBotPeaches** [comment]
I've got a few reasons.

* AOSP moved to java8 during like Nougat if I remember right.
* I really like the NIO library, which was added in 7/8.
* Java8 came out in like 2014.
* I made this change in 2018.
* It made my developer experience painful working against 6 (then 7).
