### ISSUE TITLE
lose layout_width attribute?

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#287]
Original [issue 176](https://code.google.com/p/android-apktool/issues/detail?id=176) created by coolfree on 2011-06-12T02:33:45.000Z:

> 1.decompile mms.apk
> 2.recompile (nothing chang)
> 3.put into mobile
> mms FC
> logcat

E/AndroidRuntime( 2668): FATAL EXCEPTION: main
E/AndroidRuntime( 2668): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.mms/com.android.mms.ui.ConversationList}: java.lang.Runt
imeException: Binary XML file line #&nbsp;4: You must supply a layout_width attribute.

**Comment by eriklu** [comment]
this error again on 2.40 version

```
08-03 18:07:17.321: E/AndroidRuntime(23727): Caused by: java.lang.UnsupportedOperationException: Binary XML file line #4: You must supply a layout_width attribute.
08-03 18:07:17.321: E/AndroidRuntime(23727): 	at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:711)
08-03 18:07:17.321: E/AndroidRuntime(23727): 	at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:7095)
08-03 18:07:17.321: E/AndroidRuntime(23727): 	at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:7277)
08-03 18:07:17.321: E/AndroidRuntime(23727): 	at android.widget.FrameLayout$LayoutParams.<init>(FrameLayout.java:506)
08-03 18:07:17.321: E/AndroidRuntime(23727): 	at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:446)
08-03 18:07:17.321: E/AndroidRuntime(23727): 	at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:68)
08-03 18:07:17.321: E/AndroidRuntime(23727): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:841)
08-03 18:07:17.321: E/AndroidRuntime(23727): 	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:943)
08-03 18:07:17.321: E/AndroidRuntime(23727): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
08-03 18:07:17.321: E/AndroidRuntime(23727): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:802)
08-03 18:07:17.321: E/AndroidRuntime(23727): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
08-03 18:07:17.321: E/AndroidRuntime(23727): 	... 19 more
```
