### ISSUE TITLE
[BUG] recompiled app crash immediately UnsatisfiedLinkError "libmapbox-common.so"

### ISSUE THREAD

**Issue by joihn** [iBotPeaches/Apktool#2877]
### Information
I'm trying to decompile/recompile a popular app from playstore (strava).
I managed to decompile` .\apktool.bat d -r -s .\strava.apk`, recompile `.\apktool.bat b -f -d .\strava\ --use-aapt2`, sign, install

However the app immediatly crash, any idea why ? Looks like some dependance are ommited 
### Stacktrace/Logcat

```
08-31 19:51:10.136   988 32545 I vendor.qti.hardware.servicetracker@1.2-service: startService() is called for servicecom.google.android.gms/.gcm.PushMessagingRegistrarProxy
08-31 19:51:10.136 10063 10063 D AndroidRuntime: Shutting down VM
08-31 19:51:10.137 10063 10063 E AndroidRuntime: FATAL EXCEPTION: main
08-31 19:51:10.137 10063 10063 E AndroidRuntime: Process: com.strava, PID: 10063
08-31 19:51:10.137 10063 10063 E AndroidRuntime: java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: u1.c: u1.c: java.lang.UnsatisfiedLinkError: dlopen failed: library "libmapbox-common.so" not found
08-31 19:51:10.137 10063 10063 E AndroidRuntime:        at android.app.ActivityThread.installProvider(ActivityThread.java:7578)
08-31 19:51:10.137 10063 10063 E AndroidRuntime:        at android.app.ActivityThread.installContentProviders(ActivityThread.java:7096)
08-31 19:51:10.137 10063 10063 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6985)
08-31 19:51:10.137 10063 10063 E AndroidRuntime:        at android.app.ActivityThread.access$1800(ActivityThread.java:270)
08-31 19:51:10.137 10063 10063 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2100)
08-31 19:51:10.137 10063 10063 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
08-31 19:51:10.137 10063 10063 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:245)
08-31 19:51:10.137 10063 10063 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8024)
08-31 19:51:10.137 10063 10063 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-31 19:51:10.137 10063 10063 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
08-31 19:51:10.137 10063 10063 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
08-31 19:51:10.137 10063 10063 E AndroidRuntime: Caused by: u1.c: u1.c: java.lang.UnsatisfiedLinkError: dlopen failed: library "libmapbox-common.so" not found
08-31 19:51:10.137 10063 10063 E AndroidRuntime:        at u1.a.b(ProGuard:17)
08-31 19:51:10.137 10063 10063 E AndroidRuntime:        at u1.a.a(ProGuard:11)
08-31 19:51:10.137 10063 10063 E AndroidRuntime:        at androidx.startup.InitializationProvider.onCreate(ProGuard:10)
08-31 19:51:10.137 10063 10063 E AndroidRuntime:        at android.content.ContentProvider.attachInfo(ContentProvider.java:2451)
08-31 19:51:10.137 10063 10063 E AndroidRuntime:        at android.content.ContentProvider.attachInfo(ContentProvider.java:2421)
08-31 19:51:10.137 10063 10063 E AndroidRuntime:        at android.app.ActivityThread.installProvider(ActivityThread.java:7573)
08-31 19:51:10.137 10063 10063 E AndroidRuntime:        ... 10 more
08-31 19:51:10.137 10063 10063 E AndroidRuntime: Caused by: u1.c: java.lang.UnsatisfiedLinkError: dlopen failed: library "libmapbox-common.so" not found
08-31 19:51:10.137 10063 10063 E AndroidRuntime:        at u1.a.b(ProGuard:17)
08-31 19:51:10.137 10063 10063 E AndroidRuntime:        at u1.a.b(ProGuard:13)
08-31 19:51:10.137 10063 10063 E AndroidRuntime:        ... 15 more
08-31 19:51:10.137 10063 10063 E AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libmapbox-common.so" not found
08-31 19:51:10.137 10063 10063 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
08-31 19:51:10.137 10063 10063 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
08-31 19:51:10.137 10063 10063 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1664)
08-31 19:51:10.137 10063 10063 E AndroidRuntime:        at com.mapbox.common.loader.MapboxLibraryLoader.load(Unknown Source:5)
08-31 19:51:10.137 10063 10063 E AndroidRuntime:        at com.mapbox.common.CoreInitializer.create(ProGuard:2)
08-31 19:51:10.137 10063 10063 E AndroidRuntime:        at com.mapbox.common.CoreInitializer.create(ProGuard:1)
08-31 19:51:10.137 10063 10063 E AndroidRuntime:        at u1.a.b(ProGuard:14)
08-31 19:51:10.137 10063 10063 E AndroidRuntime:        ... 16 more
```

### APK
[link to it.](https://play.google.com/store/apps/details?id=com.strava&hl=en&gl=US)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
yes
3. If you are trying to install a modified apk, did you resign it?
yes
5. Are you using the latest apktool version?
yes

**Comment by eladkarako** [comment]
try again with this non-bundle version from apkmirror  
https://www.apkmirror.com/apk/strava-inc/strava-running-and-cycling-gps/strava-running-and-cycling-gps-270-9-release/strava-run-ride-hike-270-9-android-apk-download/

**Comment by joihn** [comment]
working ! thanks :)

**Comment by eladkarako** [comment]
I assume the cause was that you've backed up a apk which was installed using google play, and the backup program (it's name?) only took 'some' of the bundled packages and packed them up to apk?

**Comment by joihn** [comment]
I installed the app via GPLAY and manually extracted the apk from my storage using a file explorer app (solid explorer)(I'm rooted, but i'm not sure wether that was a root only operation)

**Comment by eladkarako** [comment]
interesting. might be [Magisk](https://github.com/topjohnwu/Magisk/releases) has another mount of part of the system elsewhere (and APK w/ extractNativeLibs). searching `*com.strava*` (or `*libmapbox*`) right from `/` might find the other parts.  
I favor [X-Plore](https://play.google.com/store/apps/details?id=com.lonelycatgames.Xplore) for those kind of tasks.

**Comment by vi11ain** [comment]
> working ! thanks :)

Mind sharing how did you manage to get it working?

**Comment by joihn** [comment]
apparently the answer from another poster got deleted.
The issue was that my app was from playstore and was somewhat not fully bundled with all dependency


I downloaded the apk from apk mirror instead and got it to work :)
