### ISSUE TITLE
[BUG] Could not decode attr value, using undecoded value

### ISSUE THREAD

**Issue by jujuo0o** [iBotPeaches/Apktool#2878]
### Information
1. **Apktool Version (`2.6.1`)** -
2. **Operating System (Linux)** -
3. **APK From? (Playstore)** -

### Stacktrace/Logcat

```
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool 2.6.1 on APK_NAME.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionCode, value=0x00000005
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionName, value=0x0000001e
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionCode, value=0x00000005
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionName, value=0x0000001e
W: Could not decode attr value, using undecoded value instead: ns=android, name=compileSdkVersion, value=0x0000001e
W: Could not decode attr value, using undecoded value instead: ns=android, name=compileSdkVersionCodename, value=0x0000001f
W: Could not decode attr value, using undecoded value instead: ns=android, name=minSdkVersion, value=0x00000017
W: Could not decode attr value, using undecoded value instead: ns=android, name=targetSdkVersion, value=0x0000001e
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000031
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000002e
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000002d
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000030
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000002b
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000002f
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000032
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000029
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000002a
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000044
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000003c
W: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x00000022
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0d0000
W: Could not decode attr value, using undecoded value instead: ns=android, name=allowBackup, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=supportsRtl, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=extractNativeLibs, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=roundIcon, value=0x7f0d0001
W: Could not decode attr value, using undecoded value instead: ns=android, name=appComponentFactory, value=0x00000033
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000059
W: Could not decode attr value, using undecoded value instead: ns=android, name=value, value=0x00000023
Exception in thread "main" java.lang.NullPointerException
        at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1770)
        at java.base/java.util.regex.Matcher.reset(Matcher.java:416)
        at java.base/java.util.regex.Matcher.<init>(Matcher.java:253)
        at java.base/java.util.regex.Pattern.matcher(Pattern.java:1133)
        at brut.androlib.res.decoder.AndroidManifestResourceParser.isNumericStringMetadataAttributeValue(AndroidManifestResourceParser.java:56)
        at brut.androlib.res.decoder.AndroidManifestResourceParser.getAttributeValue(AndroidManifestResourceParser.java:41)
        at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValue(XmlPullParserDelegate.java:69)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
        at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:80)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:139)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:151)
        at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:159)
        at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:193)
        at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:141)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:109)
        at brut.apktool.Main.cmdDecode(Main.java:175)
        at brut.apktool.Main.main(Main.java:79)
```

### Steps to Reproduce
1. `apktool d APK_NAME.apk`

### Frameworks
APK is not from an OEM ROM

### APK
I cannot share the link, as it is a QA build.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?. Yes
2. If you are trying to install a modified apk, did you resign it?. I did, it was working before.
3. Are you using the latest apktool version? Yes, also tested on previous versions.

### Extra Info
I update my linux, and now its giving me this error on all previously tested APK's too, so i'm guessing is not a problem in the APK.

**Comment by iBotPeaches** [comment]
It's probably a bug in Apktool as we easily changed that resource parsing code, but I'm just going to blindly fix the NPE and call it fixed, since I have no way to confirm.

**Comment by jujuo0o** [comment]
I'm still having this issue. I don't know what the problem. Maybe because of java. I've observed that when I use MobSF for static analysis, it decodes properly, whereas manually doesn't work anymore. Please refer to the error log file I've generated on a test application.  The main error is at the bottom. Thanks.

[log.txt](https://github.com/iBotPeaches/Apktool/files/10189283/log.txt)

**Comment by jujuo0o** [comment]
Ok. ive found the problem just after the above comment.
With the current low privilege user its not working but when i run the following command it works:
`sudo java -jar /home/{CURRENT_USER}/.local/bin/apktool.jar d {APK_FILE}`
Hopefully it helps someone.

**Comment by juanbomfim22** [comment]
Jeez, never in a million years I'd guess the problem was in with the privileges. HUGE Thanks, @jujuo0o been suck for several days!!!!

> Ok. ive found the problem just after the above comment. With the current low privilege user its not working but when i run the following command it works: `sudo java -jar /home/{CURRENT_USER}/.local/bin/apktool.jar d {APK_FILE}` Hopefully it helps someone.

**Comment by maanich** [comment]
how i can do this in windows shell if any one can help regarding apk decompile  I tries apk easy too 1.60 and  apk tool both faild
