### ISSUE TITLE
[BUG] Apk Crashes on startup

### ISSUE THREAD

**Issue by Noice75** [iBotPeaches/Apktool#2896]
### Information
1. **Apktool Version (`apktool -version`)** - Apktool v2.6.1
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Apkpure

### Stacktrace/Logcat

`LoadedApk               pid-22833                            E  Unable to instantiate appComponentFactory
                                                                                                    java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[zip file "/data/app/~~pbq-G2XP1YDL551Y4MtMWw==/com.sma.smartv3-8yMZg3ZH0BNYndxsbY1d6w==/base.apk"],nativeLibraryDirectories=[/data/app/~~pbq-G2XP1YDL551Y4MtMWw==/com.sma.smartv3-8yMZg3ZH0BNYndxsbY1d6w==/lib/arm64, /data/app/~~pbq-G2XP1YDL551Y4MtMWw==/com.sma.smartv3-8yMZg3ZH0BNYndxsbY1d6w==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at android.app.LoadedApk.createAppFactory(LoadedApk.java:284)
                                                                                                    	at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:1016)
                                                                                                    	at android.app.LoadedApk.getClassLoader(LoadedApk.java:1103)
                                                                                                    	at android.app.LoadedApk.getResources(LoadedApk.java:1397)
                                                                                                    	at android.app.ContextImpl.createAppContext(ContextImpl.java:3157)
                                                                                                    	at android.app.ContextImpl.createAppContext(ContextImpl.java:3149)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7389)
                                                                                                    	at android.app.ActivityThread.access$1600(ActivityThread.java:310)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2281)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8663)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
2022-09-26 12:01:41.708 22833-22833 GraphicsEnvironment     pid-22833                            V  ANGLE Developer option for 'com.sma.smartv3' set to: 'default'
2022-09-26 12:01:41.709 22833-22833 GraphicsEnvironment     pid-22833                            V  Updatable production driver is not supported on the device.
2022-09-26 12:01:41.710 22833-22833 LoadedApk               pid-22833                            D  LoadedApk::makeApplication() appContext.mOpPackageName=com.sma.smartv3 appContext.mBasePackageName=com.sma.smartv3
2022-09-26 12:01:41.711 22833-22833 NetworkSecurityConfig   pid-22833                            D  Using Network Security Config from resource network_config debugBuild: false
2022-09-26 12:01:41.716 22833-22833 NetworkSecurityConfig   pid-22833                            D  Using Network Security Config from resource network_config debugBuild: false
2022-09-26 12:01:41.762   840-840   audit                   pid-840                              E  type=1400 audit(1664173901.748:481803): avc:  granted  { execute } for  pid=22833 comm="com.sma.smartv3" path="/data/data/com.sma.smartv3/.jiagu/libjiagu_64.so" dev="sda32" ino=1536971 scontext=u:r:untrusted_app:s0:c231,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c231,c257,c512,c768 tclass=file SEPF_SM-M515F_12_0001 audit_filtered
2022-09-26 12:01:41.762   840-840   audit                   pid-840                              E  type=1300 audit(1664173901.748:481803): arch=c00000b7 syscall=222 success=yes exit=514157953024 a0=77b633c000 a1=1c630 a2=5 a3=12 items=0 ppid=24649 pid=22833 auid=4294967295 uid=10487 gid=10487 euid=10487 suid=10487 fsuid=10487 egid=10487 sgid=10487 fsgid=10487 tty=(none) ses=4294967295 comm="com.sma.smartv3" exe="/system/bin/app_process64" subj=u:r:untrusted_app:s0:c231,c257,c512,c768 key=(null)
2022-09-26 12:01:41.762   840-840   audit                   pid-840                              E  type=1327 audit(1664173901.748:481803): proctitle="com.sma.smartv3"
2022-09-26 12:01:41.838 24669-17355 sensors-hal             pid-24669                            I  handle_sns_client_event:123, auto_rotation_event_2: mode:255, type:1:0/-0.072,0.208,9.833, ar:0
2022-09-26 12:01:41.863 22833-22833 AndroidRuntime          pid-22833                            D  Shutting down VM
2022-09-26 12:01:41.863 22833-22833 AndroidRuntime          pid-22833                            E  FATAL EXCEPTION: main
                                                                                                    Process: com.sma.smartv3, PID: 22833
                                                                                                    java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/data/com.sma.smartv3/.jiagu/libjiagu_64.so"
                                                                                                    	at java.lang.Runtime.load0(Runtime.java:929)
                                                                                                    	at java.lang.System.load(System.java:1625)
                                                                                                    	at com.stub.StubApp.attachBaseContext(Unknown Source:954)
                                                                                                    	at android.app.Application.attach(Application.java:350)
                                                                                                    	at android.app.Instrumentation.newApplication(Instrumentation.java:1178)
                                                                                                    	at android.app.LoadedApk.makeApplication(LoadedApk.java:1456)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7458)
                                                                                                    	at android.app.ActivityThread.access$1600(ActivityThread.java:310)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2281)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8663)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)`

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool d AppName.apk`
2. `apktool b --use-aapt2 AppNameFolder`
3. Sign apk with [https://github.com/patrickfav/uber-apk-signer](url) *Note*- I tried using jarsigner but android gave parsing error, Using `uber-apk-signer` i was able to install the app.
4. Install the app.

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)
NA

### APK
If this APK can be freely shared, please upload/attach a link to it.
[https://m.apkpure.com/smart-time-pro/com.sma.smartv3](url)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
5. If you are trying to install a modified apk, did you resign it? yes
6. Are you using the latest apktool version? yes

**Comment by Noice75** [comment]
It may or maynot be due to internal protection
But it is a linking error so idk

**Comment by auermich93** [comment]
I tried to reproduce this issue on a Nexus 5 x86_64 emulator. First the original APK:

```
2022-10-10 22:25:06.332 2836-2836/com.sma.smartv3 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sma.smartv3, PID: 2836
    java.lang.RuntimeException: Unable to create application com.stub.StubApp: java.lang.NullPointerException: getDefaultAdapter() must not be null
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5406)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: java.lang.NullPointerException: getDefaultAdapter() must not be null
        at com.bestmafen.baseble.scanner.AbsBleScanner.<init>(AbsBleScanner.kt:30)
        at com.bestmafen.baseble.scanner.BleScanner21.<init>(BleScanner21.kt:19)
        at com.bestmafen.baseble.scanner.ScannerFactory.newInstance(ScannerFactory.kt:15)
        at com.bestmafen.baseble.scanner.ScannerFactory.newInstance$default(ScannerFactory.kt:11)
        at com.bestmafen.baseble.connector.AbsBleConnector.init(AbsBleConnector.kt:263)
        at com.szabh.smable3.component.BleConnector.init(BleConnector.kt:164)
        at com.szabh.smable3.component.BleConnector.access$init(BleConnector.kt:43)
        at com.szabh.smable3.component.BleConnector$Builder.build(BleConnector.kt:1814)
        at com.sma.smartv3.initializer.BleInitializer.init(BleInitializer.kt:292)
        at com.bestmafen.androidbase.base.BaseApplication.onCreate(BaseApplication.kt:14)
        at com.stub.StubApp.onCreate(Unknown Source)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
        at android.app.ActivityThread.-wrap2(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6119)
```

Then on the repackaged APK I obtained the same logs as @Noice75:

```
2022-10-10 22:28:34.751 3136-3136/com.sma.smartv3 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sma.smartv3, PID: 3136
    java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/data/com.sma.smartv3/.jiagu/libjiagu_64.so"
        at java.lang.Runtime.load0(Runtime.java:908)
        at java.lang.System.load(System.java:1505)
        at com.stub.StubApp.attachBaseContext(Unknown Source)
        at android.app.Application.attach(Application.java:189)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1008)
        at android.app.Instrumentation.newApplication(Instrumentation.java:992)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:796)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5377)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

It seems like the original APK is already broken, but after repackaging some error in the native code appears. @iBotPeaches, is the native code touched at all by `apktool`?

**Comment by iBotPeaches** [comment]
> @iBotPeaches, is the native code touched at all by `apktool`?

Negative in the sense of disassembling. We've had bugs at storing them improperly though, like expected deflated/stored/etc. For the most part they are just copied along for the ride.

**Comment by Noice75** [comment]
> I tried to reproduce this issue on a Nexus 5 x86_64 emulator. First the original APK:
> 
> ```
> 2022-10-10 22:25:06.332 2836-2836/com.sma.smartv3 E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.sma.smartv3, PID: 2836
>     java.lang.RuntimeException: Unable to create application com.stub.StubApp: java.lang.NullPointerException: getDefaultAdapter() must not be null
>         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5406)
>         at android.app.ActivityThread.-wrap2(ActivityThread.java)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
>         at android.os.Handler.dispatchMessage(Handler.java:102)
>         at android.os.Looper.loop(Looper.java:154)
>         at android.app.ActivityThread.main(ActivityThread.java:6119)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
>      Caused by: java.lang.NullPointerException: getDefaultAdapter() must not be null
>         at com.bestmafen.baseble.scanner.AbsBleScanner.<init>(AbsBleScanner.kt:30)
>         at com.bestmafen.baseble.scanner.BleScanner21.<init>(BleScanner21.kt:19)
>         at com.bestmafen.baseble.scanner.ScannerFactory.newInstance(ScannerFactory.kt:15)
>         at com.bestmafen.baseble.scanner.ScannerFactory.newInstance$default(ScannerFactory.kt:11)
>         at com.bestmafen.baseble.connector.AbsBleConnector.init(AbsBleConnector.kt:263)
>         at com.szabh.smable3.component.BleConnector.init(BleConnector.kt:164)
>         at com.szabh.smable3.component.BleConnector.access$init(BleConnector.kt:43)
>         at com.szabh.smable3.component.BleConnector$Builder.build(BleConnector.kt:1814)
>         at com.sma.smartv3.initializer.BleInitializer.init(BleInitializer.kt:292)
>         at com.bestmafen.androidbase.base.BaseApplication.onCreate(BaseApplication.kt:14)
>         at com.stub.StubApp.onCreate(Unknown Source)
>         at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
>         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
>         at android.app.ActivityThread.-wrap2(ActivityThread.java) 
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545) 
>         at android.os.Handler.dispatchMessage(Handler.java:102) 
>         at android.os.Looper.loop(Looper.java:154) 
>         at android.app.ActivityThread.main(ActivityThread.java:6119)
> ```
> 
> Then on the repackaged APK I obtained the same logs as @Noice75:
> 
> ```
> 2022-10-10 22:28:34.751 3136-3136/com.sma.smartv3 E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.sma.smartv3, PID: 3136
>     java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/data/com.sma.smartv3/.jiagu/libjiagu_64.so"
>         at java.lang.Runtime.load0(Runtime.java:908)
>         at java.lang.System.load(System.java:1505)
>         at com.stub.StubApp.attachBaseContext(Unknown Source)
>         at android.app.Application.attach(Application.java:189)
>         at android.app.Instrumentation.newApplication(Instrumentation.java:1008)
>         at android.app.Instrumentation.newApplication(Instrumentation.java:992)
>         at android.app.LoadedApk.makeApplication(LoadedApk.java:796)
>         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5377)
>         at android.app.ActivityThread.-wrap2(ActivityThread.java)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
>         at android.os.Handler.dispatchMessage(Handler.java:102)
>         at android.os.Looper.loop(Looper.java:154)
>         at android.app.ActivityThread.main(ActivityThread.java:6119)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
> ```
> 
> It seems like the original APK is already broken, but after repackaging some error in the native code appears. @iBotPeaches, is the native code touched at all by `apktool`?

Any clue on what caused the error?

**Comment by iBotPeaches** [comment]
Before
```
➜  2986 unzip -lv SMART-TIME\ PRO_1.6.9.0_Apkpure.apk | grep '.so$' | sort
   10064  Defl:N     3537  65% 1981-01-01 01:01 a0a6e9f2  lib/arm64-v8a/libsmawatchface.so
   10336  Defl:N     3939  62% 1981-01-01 01:01 c44e262e  lib/x86_64/libsmawatchface.so
 1104416  Defl:N   328749  70% 1981-01-01 01:01 de2494f5  lib/arm64-v8a/libgnustl_shared.so
 1117104  Defl:N   337084  70% 1981-01-01 01:01 175597bb  lib/x86_64/libgnustl_shared.so
  133052  Defl:N    63651  52% 1981-01-01 01:01 dde8d7e8  lib/armeabi-v7a/liblocSDK8b.so
   13916  Defl:N     6641  52% 1981-01-01 01:01 220a6d15  lib/armeabi-v7a/libjl_crc.so
   14088  Defl:N     6169  56% 1981-01-01 01:01 27486421  lib/arm64-v8a/libchipsea_bias_v235.so
   14344  Defl:N     5617  61% 1981-01-01 01:01 923707fa  lib/arm64-v8a/libjl_ota_auth.so
   14344  Defl:N     5711  60% 1981-01-01 01:01 be872c21  lib/arm64-v8a/libjl_auth.so
   14360  Defl:N     5975  58% 1981-01-01 01:01 31dd0a93  lib/x86_64/libchipsea_bias_v235.so
   16768  Defl:N    10933  35% 1981-01-01 01:01 c8fa101e  lib/armeabi-v7a/libRtkAesJni.so
  177692  Defl:N    98448  45% 1981-01-01 01:01 9b17bd7b  lib/armeabi-v7a/libindoor.so
   18000  Defl:N     7945  56% 1981-01-01 01:01 7e7bdee5  lib/armeabi-v7a/libsmawatchface.so
   18072  Defl:N     9119  50% 1981-01-01 01:01 103ab5fd  lib/armeabi-v7a/libjl_ota_auth.so
   18072  Defl:N     9200  49% 1981-01-01 01:01 5817f586  lib/armeabi-v7a/libjl_auth.so
   18256  Defl:N     7081  61% 1981-01-01 01:01 47fa3bcc  lib/arm64-v8a/libjl_enc.so
   18552  Defl:N    10965  41% 1981-01-01 01:01 daaa8ee1  lib/arm64-v8a/libRtkAesJni.so
   19016  Defl:N    11677  39% 1981-01-01 01:01 c89177f3  lib/x86_64/libRtkAesJni.so
  215312  Defl:N    88847  59% 1981-01-01 01:01 25cf9ce8  lib/arm64-v8a/liblocSDK8b.so
  215664  Defl:N    90931  58% 1981-01-01 01:01 2f3744e0  lib/x86_64/liblocSDK8b.so
   21752  Defl:N    11889  45% 1981-01-01 01:01 9621fc2f  lib/armeabi-v7a/libweibosdkcore.so
   21984  Defl:N     9794  55% 1981-01-01 01:01 d5c25359  lib/armeabi-v7a/libchipsea_bias_v235.so
   22096  Defl:N    11648  47% 1981-01-01 01:01 8117f980  lib/armeabi-v7a/libjl_enc.so
   22640  Defl:N     7613  66% 1981-01-01 01:01 5ff14ff2  lib/x86_64/libBSBiaAlg.so
  255960  Defl:N   116118  55% 1981-01-01 01:01 c9fef3ac  lib/arm64-v8a/libindoor.so
   26136  Defl:N    11026  58% 1981-01-01 01:01 d1d95408  lib/arm64-v8a/libweibosdkcore.so
   26376  Defl:N     6291  76% 1981-01-01 01:01 c58db2b5  lib/arm64-v8a/libSenHe_BodyFat.so
   26464  Defl:N     8702  67% 1981-01-01 01:01 3be8455d  lib/arm64-v8a/libBSBiaAlg.so
   26648  Defl:N     6648  75% 1981-01-01 01:01 c37f1138  lib/x86_64/libSenHe_BodyFat.so
  272616  Defl:N   121360  56% 1981-01-01 01:01 816d6b37  lib/x86_64/libindoor.so
   30288  Defl:N    10965  64% 1981-01-01 01:01 2c90fecc  lib/armeabi-v7a/libSenHe_BodyFat.so
   30380  Defl:N    13697  55% 1981-01-01 01:01 a9eecfcc  lib/armeabi-v7a/libBSBiaAlg.so
 3819664  Defl:N  2211632  42% 1981-01-01 01:01 49ff177d  lib/armeabi-v7a/libBaiduMapSDK_map_v7_5_3.so
  382708  Defl:N   226289  41% 1981-01-01 01:01 c6b0c8e0  lib/armeabi-v7a/libBaiduMapSDK_base_v7_5_3.so
   47024  Defl:N    13309  72% 1981-01-01 01:01 9e661df9  lib/arm64-v8a/libTjHwBiaAlgAC4003.so
   47296  Defl:N    15402  67% 1981-01-01 01:01 3c8b3d06  lib/x86_64/libTjHwBiaAlgAC4003.so
   50876  Defl:N    20714  59% 1981-01-01 01:01 e263b745  lib/armeabi-v7a/libTjHwBiaAlgAC4003.so
   52880  Defl:N    14637  72% 1981-01-01 01:01 74855526  lib/arm64-v8a/libBodyfat_SDK.so
   53160  Defl:N    15162  72% 1981-01-01 01:01 8e8815a9  lib/x86_64/libBodyfat_SDK.so
   56704  Defl:N    16837  70% 1981-01-01 01:01 e355b664  lib/armeabi-v7a/libBodyfat_SDK.so
  567416  Defl:N   272484  52% 1981-01-01 01:01 4738a8ef  lib/arm64-v8a/libBaiduMapSDK_base_v7_5_3.so
  576040  Defl:N   277369  52% 1981-01-01 01:01 b2c412a3  lib/x86_64/libBaiduMapSDK_base_v7_5_3.so
    5992  Defl:N     2026  66% 1981-01-01 01:01 0fe7ac8a  lib/arm64-v8a/libjl_crc.so
  675544  Defl:N   618501   8% 2022-11-07 14:54 f32eff0d  assets/libjiagu.so
  717276  Defl:N   638513  11% 2022-11-07 14:54 4472ba07  assets/libjiagu_x86.so
  718696  Defl:N   263891  63% 1981-01-01 01:01 ba71541c  lib/armeabi-v7a/libgnustl_shared.so
 7990528  Defl:N  3453527  57% 1981-01-01 01:01 5d6234f0  lib/arm64-v8a/libBaiduMapSDK_map_v7_5_3.so
  840392  Defl:N   763085   9% 2022-11-07 14:54 bfe5320e  assets/libjiagu_x64.so
  865392  Defl:N   800761   8% 2022-11-07 14:54 4930a355  assets/libjiagu_a64.so
 8783120  Defl:N  3715537  58% 1981-01-01 01:01 7c31e7c4  lib/x86_64/libBaiduMapSDK_map_v7_5_3.so

```

After
```
➜  2986 unzip -lv SMART-TIME\ PRO_1.6.9.0_Apkpure/dist/SMART-TIME\ PRO_1.6.9.0_Apkpure.apk | grep '.so$' | sort
   10064  Defl:N     3537  65% 2022-11-21 06:53 a0a6e9f2  lib/arm64-v8a/libsmawatchface.so
   10336  Defl:N     3939  62% 2022-11-21 06:53 c44e262e  lib/x86_64/libsmawatchface.so
 1104416  Defl:N   328749  70% 2022-11-21 06:53 de2494f5  lib/arm64-v8a/libgnustl_shared.so
 1117104  Defl:N   337084  70% 2022-11-21 06:53 175597bb  lib/x86_64/libgnustl_shared.so
  133052  Defl:N    63651  52% 2022-11-21 06:53 dde8d7e8  lib/armeabi-v7a/liblocSDK8b.so
   13916  Defl:N     6641  52% 2022-11-21 06:53 220a6d15  lib/armeabi-v7a/libjl_crc.so
   14088  Defl:N     6169  56% 2022-11-21 06:53 27486421  lib/arm64-v8a/libchipsea_bias_v235.so
   14344  Defl:N     5617  61% 2022-11-21 06:53 923707fa  lib/arm64-v8a/libjl_ota_auth.so
   14344  Defl:N     5711  60% 2022-11-21 06:53 be872c21  lib/arm64-v8a/libjl_auth.so
   14360  Defl:N     5975  58% 2022-11-21 06:53 31dd0a93  lib/x86_64/libchipsea_bias_v235.so
   16768  Defl:N    10933  35% 2022-11-21 06:53 c8fa101e  lib/armeabi-v7a/libRtkAesJni.so
  177692  Defl:N    98448  45% 2022-11-21 06:53 9b17bd7b  lib/armeabi-v7a/libindoor.so
   18000  Defl:N     7945  56% 2022-11-21 06:53 7e7bdee5  lib/armeabi-v7a/libsmawatchface.so
   18072  Defl:N     9119  50% 2022-11-21 06:53 103ab5fd  lib/armeabi-v7a/libjl_ota_auth.so
   18072  Defl:N     9200  49% 2022-11-21 06:53 5817f586  lib/armeabi-v7a/libjl_auth.so
   18256  Defl:N     7081  61% 2022-11-21 06:53 47fa3bcc  lib/arm64-v8a/libjl_enc.so
   18552  Defl:N    10965  41% 2022-11-21 06:53 daaa8ee1  lib/arm64-v8a/libRtkAesJni.so
   19016  Defl:N    11677  39% 2022-11-21 06:53 c89177f3  lib/x86_64/libRtkAesJni.so
  215312  Defl:N    88847  59% 2022-11-21 06:53 25cf9ce8  lib/arm64-v8a/liblocSDK8b.so
  215664  Defl:N    90931  58% 2022-11-21 06:53 2f3744e0  lib/x86_64/liblocSDK8b.so
   21752  Defl:N    11889  45% 2022-11-21 06:53 9621fc2f  lib/armeabi-v7a/libweibosdkcore.so
   21984  Defl:N     9794  55% 2022-11-21 06:53 d5c25359  lib/armeabi-v7a/libchipsea_bias_v235.so
   22096  Defl:N    11648  47% 2022-11-21 06:53 8117f980  lib/armeabi-v7a/libjl_enc.so
   22640  Defl:N     7613  66% 2022-11-21 06:53 5ff14ff2  lib/x86_64/libBSBiaAlg.so
  255960  Defl:N   116118  55% 2022-11-21 06:53 c9fef3ac  lib/arm64-v8a/libindoor.so
   26136  Defl:N    11026  58% 2022-11-21 06:53 d1d95408  lib/arm64-v8a/libweibosdkcore.so
   26376  Defl:N     6291  76% 2022-11-21 06:53 c58db2b5  lib/arm64-v8a/libSenHe_BodyFat.so
   26464  Defl:N     8702  67% 2022-11-21 06:53 3be8455d  lib/arm64-v8a/libBSBiaAlg.so
   26648  Defl:N     6648  75% 2022-11-21 06:53 c37f1138  lib/x86_64/libSenHe_BodyFat.so
  272616  Defl:N   121360  56% 2022-11-21 06:53 816d6b37  lib/x86_64/libindoor.so
   30288  Defl:N    10965  64% 2022-11-21 06:53 2c90fecc  lib/armeabi-v7a/libSenHe_BodyFat.so
   30380  Defl:N    13697  55% 2022-11-21 06:53 a9eecfcc  lib/armeabi-v7a/libBSBiaAlg.so
 3819664  Defl:N  2211632  42% 2022-11-21 06:53 49ff177d  lib/armeabi-v7a/libBaiduMapSDK_map_v7_5_3.so
  382708  Defl:N   226289  41% 2022-11-21 06:53 c6b0c8e0  lib/armeabi-v7a/libBaiduMapSDK_base_v7_5_3.so
   47024  Defl:N    13309  72% 2022-11-21 06:53 9e661df9  lib/arm64-v8a/libTjHwBiaAlgAC4003.so
   47296  Defl:N    15402  67% 2022-11-21 06:53 3c8b3d06  lib/x86_64/libTjHwBiaAlgAC4003.so
   50876  Defl:N    20714  59% 2022-11-21 06:53 e263b745  lib/armeabi-v7a/libTjHwBiaAlgAC4003.so
   52880  Defl:N    14637  72% 2022-11-21 06:53 74855526  lib/arm64-v8a/libBodyfat_SDK.so
   53160  Defl:N    15162  72% 2022-11-21 06:53 8e8815a9  lib/x86_64/libBodyfat_SDK.so
   56704  Defl:N    16837  70% 2022-11-21 06:53 e355b664  lib/armeabi-v7a/libBodyfat_SDK.so
  567416  Defl:N   272484  52% 2022-11-21 06:53 4738a8ef  lib/arm64-v8a/libBaiduMapSDK_base_v7_5_3.so
  576040  Defl:N   277369  52% 2022-11-21 06:53 b2c412a3  lib/x86_64/libBaiduMapSDK_base_v7_5_3.so
    5992  Defl:N     2026  66% 2022-11-21 06:53 0fe7ac8a  lib/arm64-v8a/libjl_crc.so
  675544  Defl:N   619990   8% 2022-11-21 06:53 f32eff0d  assets/libjiagu.so
  717276  Defl:N   639615  11% 2022-11-21 06:53 4472ba07  assets/libjiagu_x86.so
  718696  Defl:N   263891  63% 2022-11-21 06:53 ba71541c  lib/armeabi-v7a/libgnustl_shared.so
 7990528  Defl:N  3453527  57% 2022-11-21 06:53 5d6234f0  lib/arm64-v8a/libBaiduMapSDK_map_v7_5_3.so
  840392  Defl:N   764469   9% 2022-11-21 06:53 bfe5320e  assets/libjiagu_x64.so
  865392  Defl:N   801690   7% 2022-11-21 06:53 4930a355  assets/libjiagu_a64.so
 8783120  Defl:N  3715537  58% 2022-11-21 06:53 7c31e7c4  lib/x86_64/libBaiduMapSDK_map_v7_5_3.so
```

The shared object files in `assets` have compression changed. They are treated differently, because they are an improper location than expect of like lib/libs.

I'm guessing that might be related, but honestly just a guess. So I'm changing this ticket into the bug/request/feature of

 * Keeping compression consistent with `.so` objects regardless of location within apk.

**Comment by lyxxman** [comment]
> It may or maynot be due to internal protection But it is a linking error so idk

I have the same problem. Have you solved this problem？
