### ISSUE TITLE
[BUG] W: Could not decode attr value, using undecoded value instead: ns=android, name=versionCode, value=0x056c0ae2

### ISSUE THREAD

**Issue by BREBION-Mathis** [iBotPeaches/Apktool#2899]
### Information
1. **Apktool Version (`apktool 2.6.1`)** -
2. **Operating System (Linux)** -
3. **APK From? (Other)** -

### Stacktrace/Logcat
```bash
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool 2.6.1 on spot.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionCode, value=0x056c0ae2
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionName, value=0x0000006a
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionCode, value=0x056c0ae2
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionName, value=0x0000006a
W: Could not decode attr value, using undecoded value instead: ns=android, name=compileSdkVersion, value=0x00000017
W: Could not decode attr value, using undecoded value instead: ns=android, name=compileSdkVersionCodename, value=0x00000069
W: Could not decode attr value, using undecoded value instead: ns=android, name=minSdkVersion, value=0x00000015
W: Could not decode attr value, using undecoded value instead: ns=android, name=targetSdkVersion, value=0x0000001f
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000b0
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000098
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000099
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000a0
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000a6
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000a7
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000a8
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000a4
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000ab
W: Could not decode attr value, using undecoded value instead: ns=android, name=maxSdkVersion, value=0x00000016
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000b1
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000a9
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000aa
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000b2
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000a2
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000ac
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000192
W: Could not decode attr value, using undecoded value instead: ns=android, name=protectionLevel, value=0x00000002
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000193
W: Could not decode attr value, using undecoded value instead: ns=android, name=protectionLevel, value=0x00000002
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000192
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000193
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000009c
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000009d
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000009e
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000009f
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000194
W: Could not decode attr value, using undecoded value instead: ns=android, name=protectionLevel, value=0x00000002
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000194
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000af
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000a5
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000128
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000e0
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000120
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000a1
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000007d
W: Could not decode attr value, using undecoded value instead: ns=android, name=required, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000007c
W: Could not decode attr value, using undecoded value instead: ns=android, name=required, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=anyDensity, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=smallScreens, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=normalScreens, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=largeScreens, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001ec
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000092
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000008c
W: Could not decode attr value, using undecoded value instead: ns=android, name=scheme, value=0x000001fd
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000093
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000008c
W: Could not decode attr value, using undecoded value instead: ns=android, name=scheme, value=0x000001e5
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000008c
W: Could not decode attr value, using undecoded value instead: ns=android, name=scheme, value=0x000001e7
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000de
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000ef
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001dc
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000011f
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001da
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001de
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001ee
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000011e
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000ea
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000127
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000011d
W: Could not decode attr value, using undecoded value instead: ns=android, name=mimeType, value=0x000001e9
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000ee
W: Could not decode attr value, using undecoded value instead: ns=android, name=mimeType, value=0x000001e9
W: Could not decode attr value, using undecoded value instead: ns=android, name=authorities, value=0x000000b8
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000f0
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000fa
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000f2
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001ed
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001db
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000008c
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000108
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000b5
W: Could not decode attr value, using undecoded value instead: ns=android, name=required, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000ae
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000ad
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000122
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000f1
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000b0
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000098
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000f4
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000f9
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000123
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1503fa
W: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f1400c0
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f100000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000185
W: Could not decode attr value, using undecoded value instead: ns=android, name=allowBackup, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=largeHeap, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=supportsRtl, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=networkSecurityConfig, value=0x7f18000e
W: Could not decode attr value, using undecoded value instead: ns=android, name=appComponentFactory, value=0x00000137
W: Could not decode attr value, using undecoded value instead: ns=android, name=allowAudioPlaybackCapture, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=requestLegacyExternalStorage, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000001e3
W: Could not decode attr value, using undecoded value instead: ns=android, name=value, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000018d
W: Could not decode attr value, using undecoded value instead: ns=android, name=value, value=0x000001e4
Exception in thread "main" java.lang.NullPointerException
        at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1770)
        at java.base/java.util.regex.Matcher.reset(Matcher.java:416)
        at java.base/java.util.regex.Matcher.<init>(Matcher.java:253)
        at java.base/java.util.regex.Pattern.matcher(Pattern.java:1133)
        at brut.androlib.res.decoder.AndroidManifestResourceParser.isNumericStringMetadataAttributeValue(AndroidManifestResourceParser.java:56)
        at brut.androlib.res.decoder.AndroidManifestResourceParser.getAttributeValue(AndroidManifestResourceParser.java:41)
        at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValue(XmlPullParserDelegate.java:69)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
        at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:80)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:139)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:151)
        at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:159)
        at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:193)
        at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:141)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:109)
        at brut.apktool.Main.cmdDecode(Main.java:175)
        at brut.apktool.Main.main(Main.java:79)
```
### Steps to Reproduce
1. `apktool d spot.apk `

### Download apk
https://spotify.fr.uptodown.com/android/telecharger

Hello, I am trying to decompile a spotify apk but I get this error and it also happens on a facebook or deezer apk with other types of errors. If anyone knows anything about this, please let me know!
Thanks in advance

**Comment by iBotPeaches** [comment]
Already resolved in upcoming release.

```
➜  2893 apktool d spotify-8-7-72-546.apk 
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool 2.6.2-eb105f-SNAPSHOT on spotify-8-7-72-546.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes4.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
➜  2893 
```
