### ISSUE TITLE
Android 13 invalid chunk type error 

### ISSUE THREAD

**Issue by Hak-Init** [iBotPeaches/Apktool#2916]
It seems that this arsc bug has reappeared in Android 13. Please see the below error log. It is not clear whether this is an APK issue or an apktool issue.

TAG: 2.11.9(22101970)
ROOT: false
ABI: arm64-v8a
MODEL: Pixel 6a
SDK: 33
RELEASE: 13
---StackTrace---
java.io.IOException: Invalid chunk type: expected=0x0001, got=0x0000, offset=0x21bd
 at l.ۚۦ۫.۟(L19O:23)
 at l.ۢۧ۫.<init>(Q4OE:58)
 at l.ۧۗ۫.<init>(74MS:49)
 at l.ۧۗ۫.<init>(74MS:27)
 at l.ۙ۟ۚ.<init>(I60S:79)
 at l.۬۬ۚ.ۘ(E5ZU:98)
 at l.ۦۨۙ.۟(A4WF:75)
 at l.ۚۨۙ.run(2ATI:0)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
 at java.lang.Thread.run(Thread.java:1012)

Thanks for your time.

**Comment by Hak-Init** [comment]
Checked in newest np manager also.
Same error.
Appears to be apktool bug.

**Comment by iBotPeaches** [comment]
Sorry I don't see anything I can do with this information.
