### ISSUE TITLE
I am getting error when placing a payload inside an apk file with msfvenom

### ISSUE THREAD

**Issue by aykutmehmetd** [iBotPeaches/Apktool#2920]
Hello, When placing a payload inside an apk file with msfvenom, I get the following error:

```
[-] I: Using Apktool 2.6.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
Exception in thread "main" org.jf.util.ExceptionWithContext: Exception occurred while writing code_item for method Lcom/google/android/exoplayer2/d;-><init>(Lp/v8w;[II[Z)V
        at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1047)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:346)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:301)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:58)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:37)
        at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:430)
        at brut.androlib.Androlib.buildSources(Androlib.java:361)
        at brut.androlib.Androlib.build(Androlib.java:313)
        at brut.androlib.Androlib.build(Androlib.java:280)
        at brut.apktool.Main.cmdBuild(Main.java:255)
        at brut.apktool.Main.main(Main.java:82)
Caused by: org.jf.util.ExceptionWithContext: Error while writing instruction at code offset 0x24
        at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1320)
        at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1043)
        ... 10 more
Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65569
        at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
        at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:356)
        at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1280)
        ... 11 more

Error: apktool execution failed
```

Before this error i was getting an error about apache commons text. I fixed that error. You set the commons text version to 1.9 but I had version 1.10. I was getting an error about this but i fixed it. Then i started getting this error.

**Comment by iBotPeaches** [comment]
Looks like your injected payload has exceeded the amount of methods allowed per dex file.

> Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65569

So not really a bug.
