### ISSUE TITLE
[BUG] not decodeApk

### ISSUE THREAD

**Issue by Arashvscode** [iBotPeaches/Apktool#2928]
```









java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/imageio/ImageIO;
	at brut.androlib.res.decoder.Res9patchStreamDecoder.decode(Res9patchStreamDecoder.java:44)
	at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(ResStreamDecoderContainer.java:30)
	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:138)
	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:91)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:247)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:136)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:111)
	at com.modscreator.apktool.MainActivity$2$1.run(MainActivity.java:134)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.ClassNotFoundException: javax.imageio.ImageIO
	... 12 more
```

Hi Error library not DecodeApk file 

my java code using 

```java

path = input.getText().toString().trim();
output = edittext_output.getText().toString().trim();
final ProgressDialog p = new ProgressDialog(MainActivity.this);
p.setMessage("Decompiling...");
p.setIndeterminate(true);
p.setCancelable(false);
p.setCanceledOnTouchOutside(false);
p.show();
AsyncTask.execute(new Runnable() {
		@Override
		public void run() {
		try {
				brut.androlib.ApkDecoder decoder = new brut.androlib.ApkDecoder();
				
				decoder.setFrameworkDir("/data/data/com.modscreator.apktool/files/framework/");
				
				decoder.setApkFile(new java.io.File(path));
				
				decoder.setOutDir(new java.io.File(output));
				short NotDeCodeClass = 0x000;
				decoder.setDecodeSources(NotDeCodeClass);
			    short FORCE_DECODE_MANIFEST_NONE = 0x000;
			    decoder.setForceDecodeManifest(FORCE_DECODE_MANIFEST_NONE);
			    short DECODE_ASSETS_NONE = 0x000;
			    decoder.setDecodeAssets(DECODE_ASSETS_NONE);
				
				decoder.decode();
		} catch (final brut.androlib.AndrolibException e) {
				p.dismiss();
				t = new TimerTask() { 
						@Override public void run() { runOnUiThread(new Runnable() { @Override public void run() {
												SketchwareUtil.showMessage(getApplicationContext(), e.toString());
										}
								});
						}
				};
				_timer.schedule(t, (int)(0));
		} catch (brut.directory.DirectoryException e) {
		} catch (java.io.IOException e) {
		}
		
		if(FileUtil.isDirectory(output + "/original")) {
				p.dismiss();
				t = new TimerTask() { 
						@Override 
						public void run() { runOnUiThread(new Runnable() { @Override public void run() {
												SketchwareUtil.showMessage(getApplicationContext(), "Decompiled complete!");
										}
								});
						}
				};
				_timer.schedule(t, (int)(0));
		}
	}
});
 
```

**Comment by iBotPeaches** [comment]
My guess is you are running this on Android and Android does not support

> javax.imageio.ImageIO

**Comment by Arashvscode** [comment]
> 

I request you to open this issue again. The previous version I used was well supported. You just need to add the javax library in the results because an Apktool M program was made by a Russian person from the same source, so it supports  Android we just have to hope

**Comment by iBotPeaches** [comment]
Sorry, not supporting Android.
