### ISSUE TITLE
[BUG] XmlPullParserException: resource not found: /META-INF/services/org.xmlpull.v1.XmlPullParserFactory make sure that parser implementing XmlPull API is available

### ISSUE THREAD

**Issue by pathikrit** [iBotPeaches/Apktool#2929]
### Information
1. **Apktool Version (`apktool -version`)** - 2.6.1
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat

```
brut.androlib.err.AXmlDecodingException: Could not decode XML
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:143)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:151)
	at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:159)
	at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:193)
	at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:141)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:109)
	.....
Caused by: org.xmlpull.v1.XmlPullParserException: caused by: org.xmlpull.v1.XmlPullParserException: resource not found: /META-INF/services/org.xmlpull.v1.XmlPullParserFactory make sure that parser implementing XmlPull API is available
	at org.xmlpull.v1.XmlPullParserFactory.newInstance(XmlPullParserFactory.java:294)
	at org.xmlpull.v1.XmlPullParserFactory.newInstance(XmlPullParserFactory.java:259)
	at org.xmlpull.v1.wrapper.XmlPullWrapperFactory.<init>(XmlPullWrapperFactory.java:52)
	at org.xmlpull.v1.wrapper.XmlPullWrapperFactory.newInstance(XmlPullWrapperFactory.java:29)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:46)
	... 39 more
```

### Steps to Reproduce
1. Trying programmatically from Java main method by adding `apktool` maven dependency:
```
<dependency>
    <groupId>org.apktool</groupId>
    <artifactId>apktool-lib</artifactId>
    <version>2.6.1</version>
</dependency>
```

**Comment by pathikrit** [comment]
Actually, nvm, it was getting shaded by my jar builder and I managed to fix it.
