### ISSUE TITLE
[BUG] Null pointer on text while decoding

### ISSUE THREAD

**Issue by Taknok** [iBotPeaches/Apktool#2934]
### Information
While trying to decode the firefox apk, the following exception is raised:
```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
```
1. **Apktool Version (`apktool -version`)** - 2.6.1
2. **Operating System (Mac, Linux, Windows)** - Linux (Debian) 5.19.11
3. **APK From? (Playstore, ROM, Other)** - Github: [Firefox.apk](https://github.com/mozilla-mobile/fenix/releases/download/v106.1.0/fenix-106.1.0-arm64-v8a.apk)

### Stacktrace/Logcat

```
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool 2.6.1 on fenix-106.1.0-arm64-v8a.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionCode, value=0x7828550b
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionName, value=0x00000030
W: Could not decode attr value, using undecoded value instead: ns=android, name=sharedUserId, value=0x00000111
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionCode, value=0x7828550b
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionName, value=0x00000030
W: Could not decode attr value, using undecoded value instead: ns=android, name=compileSdkVersion, value=0x00000020
W: Could not decode attr value, using undecoded value instead: ns=android, name=compileSdkVersionCodename, value=0x00000031
W: Could not decode attr value, using undecoded value instead: ns=android, name=minSdkVersion, value=0x00000015
W: Could not decode attr value, using undecoded value instead: ns=android, name=targetSdkVersion, value=0x00000020
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000094
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000008c
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000098
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000a0
W: Could not decode attr value, using undecoded value instead: ns=android, name=maxSdkVersion, value=0x0000001c
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000008a
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000008b
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000008f
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000009a
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000c1
W: Could not decode attr value, using undecoded value instead: ns=android, name=maxSdkVersion, value=0x0000001a
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000009e
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000009c
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000009b
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000097
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000092
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000090
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000007f
W: Could not decode attr value, using undecoded value instead: ns=android, name=mimeType, value=0x00000156
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000093
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000009f
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000095
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000071
W: Could not decode attr value, using undecoded value instead: ns=android, name=required, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000072
W: Could not decode attr value, using undecoded value instead: ns=android, name=required, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000074
W: Could not decode attr value, using undecoded value instead: ns=android, name=required, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000006e
W: Could not decode attr value, using undecoded value instead: ns=android, name=required, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000070
W: Could not decode attr value, using undecoded value instead: ns=android, name=required, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000006d
W: Could not decode attr value, using undecoded value instead: ns=android, name=required, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000073
W: Could not decode attr value, using undecoded value instead: ns=android, name=required, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000006f
W: Could not decode attr value, using undecoded value instead: ns=android, name=required, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=glEsVersion, value=0x00020000
W: Could not decode attr value, using undecoded value instead: ns=android, name=required, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000009d
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000096
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000c4
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000099
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000c9
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f13013a
W: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f120056
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f0e0000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000f8
W: Could not decode attr value, using undecoded value instead: ns=android, name=allowBackup, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=supportsRtl, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=extractNativeLibs, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=usesCleartextTraffic, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=roundIcon, value=0x7f0e0003
W: Could not decode attr value, using undecoded value instead: ns=android, name=appComponentFactory, value=0x000000a6
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000f9
W: Could not decode attr value, using undecoded value instead: ns=android, name=exported, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=launchMode, value=0x00000002
W: Could not decode attr value, using undecoded value instead: ns=android, name=configChanges, value=0x00002db3
W: Could not decode attr value, using undecoded value instead: ns=android, name=windowSoftInputMode, value=0x00000010
W: Could not decode attr value, using undecoded value instead: ns=android, name=resizeableActivity, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=supportsPictureInPicture, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000082
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000085
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000086
W: Could not decode attr value, using undecoded value instead: ns=android, name=scheme, value=0x000000da
W: Could not decode attr value, using undecoded value instead: ns=android, name=host, value=0x000000d9
W: Could not decode attr value, using undecoded value instead: ns=android, name=scheme, value=0x000000da
W: Could not decode attr value, using undecoded value instead: ns=android, name=host, value=0x000000de
W: Could not decode attr value, using undecoded value instead: ns=android, name=scheme, value=0x000000da
W: Could not decode attr value, using undecoded value instead: ns=android, name=host, value=0x000000df
W: Could not decode attr value, using undecoded value instead: ns=android, name=scheme, value=0x000000da
W: Could not decode attr value, using undecoded value instead: ns=android, name=host, value=0x000000e3
W: Could not decode attr value, using undecoded value instead: ns=android, name=scheme, value=0x000000da
W: Could not decode attr value, using undecoded value instead: ns=android, name=host, value=0x000000e8
W: Could not decode attr value, using undecoded value instead: ns=android, name=scheme, value=0x000000da
W: Could not decode attr value, using undecoded value instead: ns=android, name=host, value=0x000000f7
W: Could not decode attr value, using undecoded value instead: ns=android, name=scheme, value=0x000000da
W: Could not decode attr value, using undecoded value instead: ns=android, name=host, value=0x0000014b
W: Could not decode attr value, using undecoded value instead: ns=android, name=scheme, value=0x000000da
W: Could not decode attr value, using undecoded value instead: ns=android, name=host, value=0x0000014c
W: Could not decode attr value, using undecoded value instead: ns=android, name=scheme, value=0x000000da
W: Could not decode attr value, using undecoded value instead: ns=android, name=host, value=0x0000014d
W: Could not decode attr value, using undecoded value instead: ns=android, name=scheme, value=0x000000da
W: Could not decode attr value, using undecoded value instead: ns=android, name=host, value=0x0000014e
W: Could not decode attr value, using undecoded value instead: ns=android, name=scheme, value=0x000000da
W: Could not decode attr value, using undecoded value instead: ns=android, name=host, value=0x0000014f
W: Could not decode attr value, using undecoded value instead: ns=android, name=scheme, value=0x000000da
W: Could not decode attr value, using undecoded value instead: ns=android, name=host, value=0x00000150
W: Could not decode attr value, using undecoded value instead: ns=android, name=scheme, value=0x000000da
W: Could not decode attr value, using undecoded value instead: ns=android, name=host, value=0x00000151
W: Could not decode attr value, using undecoded value instead: ns=android, name=scheme, value=0x000000da
W: Could not decode attr value, using undecoded value instead: ns=android, name=host, value=0x00000152
W: Could not decode attr value, using undecoded value instead: ns=android, name=scheme, value=0x000000da
W: Could not decode attr value, using undecoded value instead: ns=android, name=host, value=0x00000153
W: Could not decode attr value, using undecoded value instead: ns=android, name=scheme, value=0x000000da
W: Could not decode attr value, using undecoded value instead: ns=android, name=host, value=0x00000157
W: Could not decode attr value, using undecoded value instead: ns=android, name=scheme, value=0x000000da
W: Could not decode attr value, using undecoded value instead: ns=android, name=host, value=0x00000158
W: Could not decode attr value, using undecoded value instead: ns=android, name=scheme, value=0x000000da
W: Could not decode attr value, using undecoded value instead: ns=android, name=host, value=0x00000159
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000010b
W: Could not decode attr value, using undecoded value instead: ns=android, name=exported, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=targetActivity, value=0x000000f9
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000007d
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000087
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000069
W: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7f150014
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000103
W: Could not decode attr value, using undecoded value instead: ns=android, name=exported, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f120056
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000101
W: Could not decode attr value, using undecoded value instead: ns=android, name=exported, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=taskAffinity, value=0x0000002f
W: Could not decode attr value, using undecoded value instead: ns=android, name=configChanges, value=0x00002db3
W: Could not decode attr value, using undecoded value instead: ns=android, name=windowSoftInputMode, value=0x00000013
W: Could not decode attr value, using undecoded value instead: ns=android, name=persistableMode, value=0x00000001
W: Could not decode attr value, using undecoded value instead: ns=android, name=autoRemoveFromRecents, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=resizeableActivity, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=supportsPictureInPicture, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f13025f
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000fa
W: Could not decode attr value, using undecoded value instead: ns=android, name=exported, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=taskAffinity, value=0x0000002f
W: Could not decode attr value, using undecoded value instead: ns=android, name=excludeFromRecents, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=relinquishTaskIdentity, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000007d
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000084
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000086
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000082
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000086
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000085
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000f5
W: Could not decode attr value, using undecoded value instead: ns=android, name=scheme, value=0x000000e0
W: Could not decode attr value, using undecoded value instead: ns=android, name=scheme, value=0x000000e2
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000082
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000085
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000086
W: Could not decode attr value, using undecoded value instead: ns=android, name=scheme, value=0x000000da
W: Could not decode attr value, using undecoded value instead: ns=android, name=host, value=0x00000154
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000082
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000085
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000086
W: Could not decode attr value, using undecoded value instead: ns=android, name=scheme, value=0x000000e0
W: Could not decode attr value, using undecoded value instead: ns=android, name=scheme, value=0x000000e2
W: Could not decode attr value, using undecoded value instead: ns=android, name=mimeType, value=0x00000155
W: Could not decode attr value, using undecoded value instead: ns=android, name=mimeType, value=0x00000156
W: Could not decode attr value, using undecoded value instead: ns=android, name=mimeType, value=0x000000bd
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000007f
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000086
W: Could not decode attr value, using undecoded value instead: ns=android, name=mimeType, value=0x00000156
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000007e
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000086
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000068
W: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7f150012
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000083
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000086
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000ef
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000086
W: Could not decode attr value, using undecoded value instead: ns=android, name=scheme, value=0x000000e2
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000077
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000086
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000089
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000086
W: Could not decode attr value, using undecoded value instead: ns=android, name=scheme, value=0x000000e0
W: Could not decode attr value, using undecoded value instead: ns=android, name=scheme, value=0x000000e2
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000c2
W: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7f0e0000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000112
W: Could not decode attr value, using undecoded value instead: ns=android, name=exported, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=targetActivity, value=0x000000fa
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000113
W: Could not decode attr value, using undecoded value instead: ns=android, name=exported, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=targetActivity, value=0x000000fa
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000114
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000ff
W: Could not decode attr value, using undecoded value instead: ns=android, name=exported, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f130224
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000109
W: Could not decode attr value, using undecoded value instead: ns=android, name=taskAffinity, value=0x0000002f
W: Could not decode attr value, using undecoded value instead: ns=android, name=excludeFromRecents, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000107
W: Could not decode attr value, using undecoded value instead: ns=android, name=exported, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=taskAffinity, value=0x0000002f
W: Could not decode attr value, using undecoded value instead: ns=android, name=configChanges, value=0x00002db3
W: Could not decode attr value, using undecoded value instead: ns=android, name=windowSoftInputMode, value=0x00000013
W: Could not decode attr value, using undecoded value instead: ns=android, name=autoRemoveFromRecents, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000108
W: Could not decode attr value, using undecoded value instead: ns=android, name=exported, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f130224
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000fe
W: Could not decode attr value, using undecoded value instead: ns=android, name=exported, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f130224
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000fb
W: Could not decode attr value, using undecoded value instead: ns=android, name=exported, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7f1300f7
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000fc
W: Could not decode attr value, using undecoded value instead: ns=android, name=exported, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f120056
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000fd
W: Could not decode attr value, using undecoded value instead: ns=android, name=permission, value=0x0000008d
W: Could not decode attr value, using undecoded value instead: ns=android, name=exported, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000a1
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000006c
W: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7f150002
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000104
W: Could not decode attr value, using undecoded value instead: ns=android, name=exported, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000100
W: Could not decode attr value, using undecoded value instead: ns=android, name=exported, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000a3
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000a4
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000102
W: Could not decode attr value, using undecoded value instead: ns=android, name=exported, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000143
W: Could not decode attr value, using undecoded value instead: ns=android, name=exported, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000006a
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000006b
W: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7f150011
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000106
W: Could not decode attr value, using undecoded value instead: ns=android, name=exported, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000105
W: Could not decode attr value, using undecoded value instead: ns=android, name=exported, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000cf
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000dd
W: Could not decode attr value, using undecoded value instead: ns=android, name=value, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000dc
W: Could not decode attr value, using undecoded value instead: ns=android, name=value, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000db
W: Could not decode attr value, using undecoded value instead: ns=android, name=value, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000ae
W: Could not decode attr value, using undecoded value instead: ns=android, name=exported, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=authorities, value=0x0000010d
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x000000a7
W: Could not decode attr value, using undecoded value instead: ns=android, name=value, value=0x000000ad
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
        at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1769)
        at java.base/java.util.regex.Matcher.reset(Matcher.java:415)
        at java.base/java.util.regex.Matcher.<init>(Matcher.java:252)
        at java.base/java.util.regex.Pattern.matcher(Pattern.java:1134)
        at brut.androlib.res.decoder.AndroidManifestResourceParser.isNumericStringMetadataAttributeValue(AndroidManifestResourceParser.java:56)
        at brut.androlib.res.decoder.AndroidManifestResourceParser.getAttributeValue(AndroidManifestResourceParser.java:41)
        at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValue(XmlPullParserDelegate.java:69)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
        at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:80)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:139)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:151)
        at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:159)
        at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:193)
        at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:141)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:109)
        at brut.apktool.Main.cmdDecode(Main.java:175)
        at brut.apktool.Main.main(Main.java:79)
```

### Steps to Reproduce
1. `wget wget https://github.com/mozilla-mobile/fenix/releases/download/v106.1.0/fenix-106.1.0-arm64-v8a.apk`
2. `apktool decode fenix-106.1.0-arm64-v8a.apk`

### Framework
No.

### APK
Download link: https://github.com/mozilla-mobile/fenix/releases/download/v106.1.0/fenix-106.1.0-arm64-v8a.apk

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Not applicable.
3. If you are trying to install a modified apk, did you resign it? Not applicable.
4. Are you using the latest apktool version? Yes, installed following this: https://ibotpeaches.github.io/Apktool/install/

**Comment by iBotPeaches** [comment]
Looks like not an issue on the upcoming 2.6.2 release

```
➜  2934 apktool d fenix-106.1.0-arm64-v8a.apk 
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool 2.6.2-eb105f-SNAPSHOT on fenix-106.1.0-arm64-v8a.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
➜  2934 
```

You could pull the latest bleeding edge build from here and confirm on your side - https://github.com/iBotPeaches/Apktool/actions/runs/3451698250

Otherwise I'll close this in a few days as I believe already resolved.

**Comment by Taknok** [comment]
The 2.6.2 solve the issue. Thank you !
