### ISSUE TITLE
Seeing a similar issue across Contacts, Maps, Helath Connect, Speech Services w/ 2.6.1 release build.

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#2945]
Seeing a similar issue across [Google Contacts](https://www.apkmirror.com/apk/google-inc/google-contacts/google-contacts-3-77-23-476182297-release/google-contacts-3-77-23-476182297-3-android-apk-download/), [Google Maps](https://www.apkmirror.com/apk/google-inc/maps/maps-11-49-0700-release/google-maps-11-49-0700-2-android-apk-download/), [Health Connect by Android](https://www.apkmirror.com/apk/google-inc/health-connect-by-android/health-connect-by-android-0-1-1049-474628858-0-open_beta-release/health-connect-by-android-0-1-1049-474628858-0-open_beta-android-apk-download/), and [Google Speech Services](https://www.apkmirror.com/apk/google-inc/google-text-to-speech-engine/google-text-to-speech-engine-googletts-google-speech-apk_20220905-02_p0-472335477-release/speech-services-by-google-googletts-google-speech-apk_20220905-02_p0-472335477-2-android-apk-download/). Verified all four apps work as expected w/ 2.6.1 release build.

Identical error across all four apps:

```
I: Using Apktool 2.6.2-87223d-SNAPSHOT on contacts.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:56)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:790)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:64)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:56)
	at brut.androlib.Androlib.getResTable(Androlib.java:74)
	at brut.androlib.ApkDecoder.getResTable(ApkDecoder.java:247)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:109)
	at brut.apktool.Main.cmdDecode(Main.java:175)
	at brut.apktool.Main.main(Main.java:79)
Caused by: java.io.EOFException
	at com.google.common.io.LittleEndianDataInputStream.readAndCheckByte(LittleEndianDataInputStream.java:235)
	at com.google.common.io.LittleEndianDataInputStream.readInt(LittleEndianDataInputStream.java:118)
	at brut.util.DataInputDelegate.readInt(DataInputDelegate.java:58)
	at brut.androlib.res.decoder.ARSCDecoder.readOverlaySpec(ARSCDecoder.java:186)
	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:139)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:85)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:51)
	... 8 more
```

_Originally posted by @Skylled in https://github.com/iBotPeaches/Apktool/issues/2893#issuecomment-1258240266_

**Comment by iBotPeaches** [comment]
```
➜  2893 apktool d contacts.apk 
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool 2.6.2-eb105f-SNAPSHOT on contacts.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
➜  2893   
```

This indeed works now, so closing.
