### ISSUE TITLE
[BUG] Exception in thread "main" brut.androlib.AndrolibException: Can't create directory: (/.local/share/apktool/framework). Pass a writable path with --frame-path {DIR}.

### ISSUE THREAD

**Issue by vramasam** [iBotPeaches/Apktool#2957]
@iBotPeaches Please let us know what can be the reason for this exception. It will be really helpful to proceed.

Information
1. **Apktool Version (`apktool -version`)** - 2.7.0
2. **Operating System (Mac, Linux, Windows)** - RHEL (Linux)  
3. **APK From? (Playstore, ROM, Other)** - Sample apk (Just a normal apk)

Stacktrace/Logcat
sh-4.2$ ./apktool d -s -f ../../Sample.apk -o ../../decompiledDirPath/
I: Using Apktool 2.7.0 on Sample.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionCode, value=0x00000005
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionName, value=0x0000000b
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionCode, value=0x00000005
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionName, value=0x0000000b
W: Could not decode attr value, using undecoded value instead: ns=android, name=compileSdkVersion, value=0x0000001d
W: Could not decode attr value, using undecoded value instead: ns=android, name=compileSdkVersionCodename, value=0x0000000a
W: Could not decode attr value, using undecoded value instead: ns=android, name=minSdkVersion, value=0x00000010
W: Could not decode attr value, using undecoded value instead: ns=android, name=targetSdkVersion, value=0x0000001d
W: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f040000
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f010000
W: Could not decode attr value, using undecoded value instead: ns=android, name=allowBackup, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000014
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000000f
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000010
I: Regular manifest package...
I: Decoding file-resources...
W: Could not decode attr value, using undecoded value instead: ns=android, name=layout_width, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=layout_height, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=id, value=0x7f020000
W: Could not decode attr value, using undecoded value instead: ns=android, name=layout_width, value=0xfffffffe
W: Could not decode attr value, using undecoded value instead: ns=android, name=layout_height, value=0xfffffffe
W: Could not decode attr value, using undecoded value instead: ns=android, name=text, value=0x7f040001
I: Decoding values */* XMLs...
Exception in thread "main" brut.androlib.AndrolibException: Can't create directory: (/.local/share/apktool/framework). Pass a writable path with --frame-path {DIR}.
	at brut.androlib.res.AndrolibResources.getFrameworkDir(AndrolibResources.java:991)
	at brut.androlib.res.AndrolibResources.getFrameworkApk(AndrolibResources.java:789)
	at brut.androlib.res.AndrolibResources.loadFrameworkPkg(AndrolibResources.java:111)
	at brut.androlib.res.data.ResTable.getPackage(ResTable.java:81)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:64)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:60)
	at brut.androlib.res.decoder.ResAttrDecoder.decode(ResAttrDecoder.java:37)
	at brut.androlib.res.decoder.AXmlResourceParser.getAttributeValue(AXmlResourceParser.java:409)
	at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValue(XmlPullParserDelegate.java:69)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
	at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:80)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:139)
	at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(ResStreamDecoderContainer.java:30)
	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:143)
	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:123)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:240)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:140)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:111)
	at brut.apktool.Main.cmdDecode(Main.java:175)
	at brut.apktool.Main.main(Main.java:79)
sh-4.2$

```
sh-4.2$ ./apktool d -s -f ../../Sample.apk -o ../../decompiledDirPath/
I: Using Apktool 2.7.0 on Sample.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionCode, value=0x00000005
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionName, value=0x0000000b
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionCode, value=0x00000005
W: Could not decode attr value, using undecoded value instead: ns=android, name=versionName, value=0x0000000b
W: Could not decode attr value, using undecoded value instead: ns=android, name=compileSdkVersion, value=0x0000001d
W: Could not decode attr value, using undecoded value instead: ns=android, name=compileSdkVersionCodename, value=0x0000000a
W: Could not decode attr value, using undecoded value instead: ns=android, name=minSdkVersion, value=0x00000010
W: Could not decode attr value, using undecoded value instead: ns=android, name=targetSdkVersion, value=0x0000001d
W: Could not decode attr value, using undecoded value instead: ns=android, name=label, value=0x7f040000
W: Could not decode attr value, using undecoded value instead: ns=android, name=icon, value=0x7f010000
W: Could not decode attr value, using undecoded value instead: ns=android, name=allowBackup, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000014
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x0000000f
W: Could not decode attr value, using undecoded value instead: ns=android, name=name, value=0x00000010
I: Regular manifest package...
I: Decoding file-resources...
W: Could not decode attr value, using undecoded value instead: ns=android, name=layout_width, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=layout_height, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=id, value=0x7f020000
W: Could not decode attr value, using undecoded value instead: ns=android, name=layout_width, value=0xfffffffe
W: Could not decode attr value, using undecoded value instead: ns=android, name=layout_height, value=0xfffffffe
W: Could not decode attr value, using undecoded value instead: ns=android, name=text, value=0x7f040001
I: Decoding values */* XMLs...
Exception in thread "main" brut.androlib.AndrolibException: Can't create directory: (/.local/share/apktool/framework). Pass a writable path with --frame-path {DIR}.
	at brut.androlib.res.AndrolibResources.getFrameworkDir(AndrolibResources.java:991)
	at brut.androlib.res.AndrolibResources.getFrameworkApk(AndrolibResources.java:789)
	at brut.androlib.res.AndrolibResources.loadFrameworkPkg(AndrolibResources.java:111)
	at brut.androlib.res.data.ResTable.getPackage(ResTable.java:81)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:64)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:60)
	at brut.androlib.res.decoder.ResAttrDecoder.decode(ResAttrDecoder.java:37)
	at brut.androlib.res.decoder.AXmlResourceParser.getAttributeValue(AXmlResourceParser.java:409)
	at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValue(XmlPullParserDelegate.java:69)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
	at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:80)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:139)
	at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(ResStreamDecoderContainer.java:30)
	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:143)
	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:123)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:240)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:140)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:111)
	at brut.apktool.Main.cmdDecode(Main.java:175)
	at brut.apktool.Main.main(Main.java:79)
```

### Steps to Reproduce
1. ran this command ./apktool d -s -f ../../Sample.apk -o ../../decompiledDirPath/

### Frameworks
Normal apk

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
3. If you are trying to install a modified apk, did you resign it? N/A
4. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
How much more helpful could the error be?

> Exception in thread "main" brut.androlib.AndrolibException: Can't create directory: (/.local/share/apktool/framework). Pass a writable path with --frame-path {DIR}.
