### ISSUE TITLE
[BUG] Another UnsatisfiedLinkError: dlopen failed.

### ISSUE THREAD

**Issue by HikaruFox** [iBotPeaches/Apktool#2962]
### Information
1. **Apktool Version (`apktool -version`)** - Latest
2. **Operating System (Mac, Linux, Windows)** - Linux and Android 12.
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat

```
12-10 20:11:50.179 32496 10252 E OSCrashHandler: java.lang.UnsatisfiedLinkError: dlopen failed: library "libsqlc-native-driver.so" not found
12-10 20:11:50.179 32496 10252 E OSCrashHandler: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
12-10 20:11:50.179 32496 10252 E OSCrashHandler: 	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
12-10 20:11:50.179 32496 10252 E OSCrashHandler: 	at java.lang.System.loadLibrary(System.java:1656)
12-10 20:11:50.179 32496 10252 E OSCrashHandler: 	at io.liteglue.SQLiteConnector.<init>(SQLiteConnector.java:8)
12-10 20:11:50.179 32496 10252 E OSCrashHandler: 	at io.sqlc.SQLiteConnectorDatabase.<clinit>(SQLiteConnectorDatabase.java:39)
12-10 20:11:50.179 32496 10252 E OSCrashHandler: 	at io.sqlc.SQLitePlugin.openDatabase(SQLitePlugin.java:217)
12-10 20:11:50.179 32496 10252 E OSCrashHandler: 	at io.sqlc.SQLitePlugin.access$000(SQLitePlugin.java:28)
12-10 20:11:50.179 32496 10252 E OSCrashHandler: 	at io.sqlc.SQLitePlugin$DBRunner.run(SQLitePlugin.java:344)
12-10 20:11:50.179 32496 10252 E OSCrashHandler: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-10 20:11:50.179 32496 10252 E OSCrashHandler: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-10 20:11:50.179 32496 10252 E OSCrashHandler: 	at java.lang.Thread.run(Thread.java:1013)
```

### Steps to Reproduce
1. Decode and build without changing anything.
2. Sign the apk.
3. Install and launch.

### Frameworks
None

### APK
[pl.jmpolska.clos0.mojabiedronka](https://play.google.com/store/apps/details?id=pl.jmpolska.clos0.mojabiedronka)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? **Yes.**
4. If you are trying to install a modified apk, did you resign it? **Yes.**
5. Are you using the latest apktool version? **Yes.**

**Comment by HikaruFox** [comment]
EDIT: 

all i needed to do is to convert all 4 apks inside to a 1 apk, because it was a splitted apk! Thank you for your awesome work
