### ISSUE TITLE
[BUG] java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by EgorSigolaev** [iBotPeaches/Apktool#2963]
### Information
1. **Apktool Version (`apktool -version`)** - 2.7.0
2. **Operating System (Mac, Linux, Windows)** - Android, Kotlin app
3. **APK From? (Playstore, ROM, Other)** - Created by me

### Stacktrace/Logcat

```
java.lang.ExceptionInInitializerError
        at brut.util.OSDetection.isMacOSX(OSDetection.java:28)
        at brut.androlib.res.AndrolibResources.getFrameworkDir(AndrolibResources.java:965)
        at brut.androlib.res.AndrolibResources.getFrameworkApk(AndrolibResources.java:792)
        at brut.androlib.res.AndrolibResources.loadFrameworkPkg(AndrolibResources.java:108)
        at brut.androlib.res.data.ResTable.getPackage(ResTable.java:81)
        at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:64)
        at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:60)
        at brut.androlib.res.decoder.ResAttrDecoder.decodeManifestAttr(ResAttrDecoder.java:51)
        at brut.androlib.res.decoder.AXmlResourceParser.getAttributeName(AXmlResourceParser.java:346)
        at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeName(XmlPullParserDelegate.java:53)
        at brut.androlib.res.decoder.XmlPullStreamDecoder$1.parseManifest(XmlPullStreamDecoder.java:89)
        at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:62)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:139)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:151)
        at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:159)
        at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:193)
        at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:141)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:109)
        at com.freshappsua.sdkdetector.MainActivity.onCreate(MainActivity.kt:36)
        at android.app.Activity.performCreate(Activity.java:8207)
        at android.app.Activity.performCreate(Activity.java:8191)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3819)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4022)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8653)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toLowerCase()' on a null object reference
        at brut.util.OSDetection.<clinit>(OSDetection.java:21)
        at brut.util.OSDetection.isMacOSX(OSDetection.java:28) 
        at brut.androlib.res.AndrolibResources.getFrameworkDir(AndrolibResources.java:965) 
        at brut.androlib.res.AndrolibResources.getFrameworkApk(AndrolibResources.java:792) 
        at brut.androlib.res.AndrolibResources.loadFrameworkPkg(AndrolibResources.java:108) 
        at brut.androlib.res.data.ResTable.getPackage(ResTable.java:81) 
        at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:64) 
        at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:60) 
        at brut.androlib.res.decoder.ResAttrDecoder.decodeManifestAttr(ResAttrDecoder.java:51) 
        at brut.androlib.res.decoder.AXmlResourceParser.getAttributeName(AXmlResourceParser.java:346) 
        at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeName(XmlPullParserDelegate.java:53) 
        at brut.androlib.res.decoder.XmlPullStreamDecoder$1.parseManifest(XmlPullStreamDecoder.java:89) 
        at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:62) 
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:139) 
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:151) 
        at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:159) 
        at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:193) 
        at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:141) 
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:109) 
        at com.freshappsua.sdkdetector.MainActivity.onCreate(MainActivity.kt:36) 
        at android.app.Activity.performCreate(Activity.java:8207) 
        at android.app.Activity.performCreate(Activity.java:8191) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3819) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4022) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.app.ActivityThread.main(ActivityThread.java:8653) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 
```

### Steps to Reproduce
1. Add jar library to a new android project
2. Set all read/write permissions in the manifest.xml and grant them in the phone settings.
3. Run code
`val apkFile = File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS), "test.apk")
        val outDir = File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS), "TestApkTarget")
        val apkDecoder = ApkDecoder()
        apkDecoder.setApkFile(apkFile)
        apkDecoder.setOutDir(outDir)
        apkDecoder.setForceDelete(true)
        apkDecoder.decode()`
Replace apkFile and outDir with your values.

### Logcat screenshot
<img width="1479" alt="screenshot_apktool" src="https://user-images.githubusercontent.com/44138374/207136513-e293c549-a4d2-4d39-b116-b81c643173b9.png">

### Frameworks
Android Studio, Kotlin, apktool_2.7.0.jar (added as library).

It seems that the crash is caused because of `System.getProperty("os.name")` that returns null and tries to call toLowerCase() method on a null object.

**Comment by iBotPeaches** [comment]
Apologies - I don't support running on Android.
