### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by eiki07** [iBotPeaches/Apktool#2964]
### Information
1. **Apktool Version (`apktool -version`)** - Latest
2. **Operating System (Mac, Linux, Windows)** - linux/ubuntu 20
3. **APK From? (Playstore, ROM, Other)** - Other

### Stacktrace/Logcat

```Exception in thread "main" org.jf.util.ExceptionWithContext: Exception occurred while writing code_item for method Landroidx/collection/LongSparseArray;->clone()Landroidx/collection/LongSparseArray;
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1058)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:354)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:309)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:58)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:37)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:437)
	at brut.androlib.Androlib.buildSources(Androlib.java:368)
	at brut.androlib.Androlib.build(Androlib.java:320)
	at brut.androlib.Androlib.build(Androlib.java:287)
	at brut.apktool.Main.cmdBuild(Main.java:263)
	at brut.apktool.Main.main(Main.java:82)
Caused by: org.jf.util.ExceptionWithContext: Error while writing instruction at code offset 0x35
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1331)
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1054)
	... 10 more
Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65540
	at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
	at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:356)
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1291)
	... 11 more

Include stacktrace here
```

### Steps to Reproduce
1. `apktool `
2. running from acvtool 

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
yes, shows apktool.yml path not exists error while trying to run apktool -b
3. If you are trying to install a modified apk, did you resign it?
yes
5. Are you using the latest apktool version?
yes

If the problem is because of the dex, could you also help with how to resolve it? New here

**Comment by iBotPeaches** [comment]
> If the problem is because of the dex, could you also help with how to resolve it? New here

Its because you've exceeded the amount of allowed methods per dex. You've hit that unsigned short limit of ~65k
