### ISSUE TITLE
IDK what is wrong I am a complete newbie and this is happening

### ISSUE THREAD

**Issue by UnknownRover** [iBotPeaches/Apktool#2967]
Using APK template: /home/WhiteDevil/Desktop/Pikashow_v82_Latest.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package com.offshore.pikachu.rdaeh
[*] Loading /tmp/d20221219-15590-sikv13/original/smali/com/offshore/pikachu/App.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Adding <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
[*] Adding <uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS"/>
[*] Adding <uses-permission android:name="android.permission.READ_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.SET_WALLPAPER"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.CALL_PHONE"/>
[*] Adding <uses-permission android:name="android.permission.RECORD_AUDIO"/>
[*] Adding <uses-permission android:name="android.permission.SEND_SMS"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
[*] Adding <uses-permission android:name="android.permission.RECEIVE_SMS"/>
[*] Adding <uses-permission android:name="android.permission.READ_SMS"/>
[*] Adding <uses-permission android:name="android.permission.CAMERA"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.READ_CONTACTS"/>
[*] Rebuilding apk with meterpreter injection as /tmp/d20221219-15590-sikv13/output.apk
[-] I: Using Apktool 2.7.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
Exception in thread "main" org.jf.util.ExceptionWithContext: Exception occurred while writing code_item for method Lda3$Wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww;-><init>(Lg93;Z[I[Z)V
        at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1058)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:354)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:309)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:58)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:37)
        at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:437)
        at brut.androlib.Androlib.buildSources(Androlib.java:368)
        at brut.androlib.Androlib.build(Androlib.java:320)
        at brut.androlib.Androlib.build(Androlib.java:287)
        at brut.apktool.Main.cmdBuild(Main.java:263)
        at brut.apktool.Main.main(Main.java:82)
Caused by: org.jf.util.ExceptionWithContext: Error while writing instruction at code offset 0x26
        at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1331)
        at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1054)
        ... 10 more
Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65584
        at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
        at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:356)
        at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1291)
        ... 11 more

Error: apktool execution failed
1. **Apktool Version (`apktool -2.7.0`)** -
2. **Operating System (Linux,)** -
3. **APK From? (Other)** -

**Comment by iBotPeaches** [comment]
You've exceeded methods allowed per dex. I believe thats a unsigned short at ~65k
