### ISSUE TITLE
[BUG] org.jf.util.ExceptionWithContext: Exception occurred while writing code_item for method Landroidx/annotation/InspectableProperty$ValueType

### ISSUE THREAD

**Issue by Drjacky** [iBotPeaches/Apktool#3005]
### Information
1. **Apktool Version (`apktool -version`)** - 2.7.0
2. **Operating System (Mac, Linux, Windows)** - macOS
3. **APK From? (Playstore, ROM, Other)** - Other

### Stacktrace/Logcat

```groovy
Exception in thread "main" org.jf.util.ExceptionWithContext: Exception occurred while writing code_item for method Landroidx/annotation/InspectableProperty$ValueType;->values()[Landroidx/annotation/InspectableProperty$ValueType;
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1058)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:354)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:309)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:58)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:37)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:437)
	at brut.androlib.Androlib.buildSources(Androlib.java:368)
	at brut.androlib.Androlib.build(Androlib.java:320)
	at brut.androlib.Androlib.build(Androlib.java:287)
	at brut.apktool.Main.cmdBuild(Main.java:263)
	at brut.apktool.Main.main(Main.java:82)
Caused by: org.jf.util.ExceptionWithContext: Error while writing instruction at code offset 0x2
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1331)
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1054)
	... 10 more
Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65538
	at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
	at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:356)
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1291)
	... 11 more

Error: apktool execution failed
```

### Steps to Reproduce
https://github.com/rapid7/metasploit-framework/issues/17610#issuecomment-1444037360
https://github.com/rapid7/metasploit-framework/blob/bf88b7f6184cef7c3aa725b56fd52d93b4bce0dd/lib/msf/core/payload/apk.rb#L297-L303

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? YES
2. If you are trying to install a modified apk, did you resign it? N/A
3. Are you using the latest apktool version? YES

The same as
https://github.com/iBotPeaches/Apktool/issues/1718
https://github.com/rapid7/metasploit-framework/issues/16338

**Comment by iBotPeaches** [comment]
```
Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65538
	at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
```

Looks like you exceeded the amount of methods per dex, ushort I believe at 65k~

**Comment by Drjacky** [comment]
But the Application class is extended to the MultiDexApplication. Is it related to that? or it's on the Apktool side? @iBotPeaches

**Comment by bcoles** [comment]
> But the Application class is extended to the MultiDexApplication.

Metasploit `msfvenom` does not support MultiDex. It tries to modify the existing DEX which in this case already contains a lot of methods (close to the DEX limit). Injection causes the DEX limit to be exceeded.

**Comment by hoper21** [comment]
hello @iBotPeaches i have same issue in another thread. so thats apktool mean broken or something?

**Comment by iBotPeaches** [comment]
> hello @iBotPeaches i have same issue in another thread. so thats apktool mean broken or something?

Apktool is not broken. You have exceeded the allowed methods in a dex file.
