### ISSUE TITLE
[BUG] The incoming YAML document exceeds the limit: 3145728 code points.

### ISSUE THREAD

**Issue by AndnixSH** [iBotPeaches/Apktool#3008]
### Information
1. **Apktool Version (`apktool -version`)** 2.7.0
2. **Operating System (Mac, Linux, Windows)** Windows
3. **APK From? (Playstore, ROM, Other)** Other

### Stacktrace/Logcat
```
I: Using Apktool 2.7.0
Exception in thread "main" org.yaml.snakeyaml.error.YAMLException: The incoming YAML document exceeds the limit: 3145728 code points.
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:335)
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:256)
        at org.yaml.snakeyaml.parser.ParserImpl$ParseIndentlessSequenceEntryKey.produce(ParserImpl.java:597)
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:171)
        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:57)
        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:43)
        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:136)
        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:116)
        at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:221)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:190)
        at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:252)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:192)
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:321)
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:312)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:293)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:194)
        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:116)
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:142)
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:155)
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:477)
        at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:470)
        at brut.androlib.meta.MetaInfo.load(MetaInfo.java:70)
        at brut.androlib.Androlib.readMetaFile(Androlib.java:280)
        at brut.androlib.Androlib.build(Androlib.java:294)
        at brut.androlib.Androlib.build(Androlib.java:287)
        at brut.apktool.Main.cmdBuild(Main.java:263)
        at brut.apktool.Main.main(Main.java:82)
```

### Steps to Reproduce
1. `apktool d`
2. `apktool b`

This bug can't be reproduced on 2.6.1

### Frameworks
N/A

### APK
https://apkpure.com/fairy-tail%EF%BC%88%E9%AD%94%E5%B0%8E%E5%B0%91%E5%B9%B4%EF%BC%89%EF%BC%9A%E6%BF%80%E9%AC%A5/com.skymoons.ftsm.gp

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
I've got a fix pr up to fix this.

```
➜  3008 apktool b 3008 --use-aapt2
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool 2.7.1-875fea-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Copying libs... (/kotlin)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk into: 3008/dist/3008.apk
➜  3008 
```
