### ISSUE TITLE
[BUG] Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: bad utf-8 byte d5 at offset 000000eb

### ISSUE THREAD

**Issue by MatiasMunk** [iBotPeaches/Apktool#3027]
### Information
1. **Apktool Version (`apktool -version`)** - 2.7.0
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Playstore

### Stacktrace/Logcat
```
I: Using Apktool 2.7.0 on xxxx.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\mmp\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes4.dex...
I: Baksmaling classes5.dex...
I: Baksmaling classes6.dex...
I: Baksmaling assets/.fwazyv.dex...
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: bad utf-8 byte d5 at offset 000000eb
        at org.jf.baksmali.Baksmali.disassembleDexFile(Baksmali.java:92)
        at org.jf.baksmali.Baksmali.disassembleDexFile(Baksmali.java:48)
        at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:100)
        at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:37)
        at brut.androlib.Androlib.decodeSourcesSmali(Androlib.java:103)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:151)
        at brut.apktool.Main.cmdDecode(Main.java:175)
        at brut.apktool.Main.main(Main.java:79)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: bad utf-8 byte d5 at offset 000000eb
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at org.jf.baksmali.Baksmali.disassembleDexFile(Baksmali.java:86)
        ... 7 more
Caused by: java.lang.IllegalArgumentException: bad utf-8 byte d5 at offset 000000eb
        at org.jf.util.Utf8Utils.throwBadUtf8(Utf8Utils.java:284)
        at org.jf.util.Utf8Utils.utf8BytesWithUtf16LengthToString(Utf8Utils.java:220)
        at org.jf.dexlib2.dexbacked.DexReader.readString(DexReader.java:611)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile$5.get(DexBackedDexFile.java:315)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile$5.get(DexBackedDexFile.java:308)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile$6.get(DexBackedDexFile.java:351)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile$6.get(DexBackedDexFile.java:346)
        at org.jf.dexlib2.dexbacked.DexBackedClassDef.getType(DexBackedClassDef.java:110)
        at org.jf.baksmali.Baksmali.disassembleClass(Baksmali.java:112)
        at org.jf.baksmali.Baksmali.access$000(Baksmali.java:46)
        at org.jf.baksmali.Baksmali$1.call(Baksmali.java:76)
        at org.jf.baksmali.Baksmali$1.call(Baksmali.java:74)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

### Steps to Reproduce
1. `apktool.bat d -f "xxxx.apk"`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://play.google.com/store/apps/details?id=com.loadcomplete.slimeidle

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version? Latest release, yes.

**Comment by qyzhaojinxi** [comment]
I met the same problem. Version 2.7.0 and on mac.

**Comment by MatiasMunk** [comment]
I think maybe the game's protected. I think the only way around the protection (without cracking it, which would be harder) is to dump the game at runtime maybe?

Or maybe developer can tell us if this error is indeed a bug or if it's protected.

**Comment by iBotPeaches** [comment]
Its probably corrupted/protected as mentioned. You can follow this trail of older reports on smali's repo - https://github.com/JesusFreke/smali/issues/688

Since Apktool just leverages the smali library - I'll close this.

**Comment by qyzhaojinxi** [comment]
I have solved my problem. What I met is the game's protected. I just removed the files that caused errors. And then it worked. I'm not sure if this solution applies to your problem.
