### ISSUE TITLE
[BUG] Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file

### ISSUE THREAD

**Issue by nianxiongdi** [iBotPeaches/Apktool#3039]
I: Using Apktool 2.7.0 on ______3D.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:56)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:780)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:64)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:56)
	at brut.androlib.Androlib.getResTable(Androlib.java:74)
	at brut.androlib.ApkDecoder.getResTable(ApkDecoder.java:251)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:109)
	at brut.apktool.Main.cmdDecode(Main.java:175)
	at brut.apktool.Main.main(Main.java:79)
Caused by: java.io.IOException: Expected: 0x00000008, got: 0x00000003
	at brut.util.ExtDataInput.skipCheckShort(ExtDataInput.java:53)
	at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:399)
	at brut.androlib.res.decoder.ARSCDecoder.readEntryData(ARSCDecoder.java:324)
	at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:309)
	at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:224)
	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:133)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:85)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:51)
	... 8 more

**Comment by iBotPeaches** [comment]
Thanks for the report, but I am closing for this duplicate which has the same crash - https://github.com/iBotPeaches/Apktool/issues/2824
