### ISSUE TITLE
Not decode

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#3042]
### Discussed in https://github.com/iBotPeaches/Apktool/discussions/3040

<div type='discussions-op-text'>

<sup>Originally posted by **ya158** April 13, 2023</sup>
Hello. I can't decode some apks with the latest version of apktool. Some apks can be decode using Apktool 2.5.1-dirty-201211, but some are not decode using it either. Here is the log:
I: Using Apktool 2.5.1-dirty-201211 on MiuiBiometricResOverlay.apk
I: Loading resource table...
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
at brut.android.rus.Android Resources.selectPkgWithMostResSpecs(Android Resources.java:114)
at butt.android.rus.Android Resources.loadMainPkg(Android Resources.java:86)
at brut.android.rus.Android Resources.get Res Table(Android Resources.java:59)
at brut.android.Androlib.getResTable(Androlib.java:69)
at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:236)
at brut.androlib.ApkDecoder.decode(ApkDecoder.java:118)
at brut.apktool.Main.cmdDecode(Main.java:179)
at brut.apktool.Main.main(Main.java:82)
[MiuiBiometricResOverlay.zip](https://github.com/iBotPeaches/Apktool/files/11220936/MiuiBiometricResOverlay.zip)
</div>

**Comment by iBotPeaches** [comment]
Couldn't replicate on latest. Closing.

```
➜  3042 java -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005 -jar /usr/local/bin/apktool.jar d MiuiBiometricResOverlay.apk 
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Listening for transport dt_socket at address: 5005
I: Using Apktool 2.7.1-603e52-SNAPSHOT on MiuiBiometricResOverlay.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  3042 
```
