### ISSUE TITLE
[BUG][2.7.0] StringIndexOutOfBoundsException when decompiling large APK

### ISSUE THREAD

**Issue by megaacheyounes** [iBotPeaches/Apktool#3095]
### Information
1. **Apktool Version (`apktool -version`)** - 2.7.0
2. **Operating System (Mac, Linux, Windows)**  windows and linux (centOs)
3. **APK From? (Playstore, ROM, Other)** - playstore: https://play.google.com/store/apps/details?id=com.Etisalat.ETIDA (ver 9.3.3)
4. **Java Version (`java --version`)** - openjdk 11

### Stacktrace/Logcat

```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: begin 101, end 124, length 105
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
        at java.base/java.lang.String.substring(String.java:1874)
        at brut.androlib.res.decoder.StyledString$Decoder.decodeIterate(StyledString.java:161)
        at brut.androlib.res.decoder.StyledString$Decoder.decode(StyledString.java:116)
        at brut.androlib.res.decoder.StyledString.toString(StyledString.java:48)
        at brut.androlib.res.decoder.StringBlock.getHTML(StringBlock.java:131)
        at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:405)
        at brut.androlib.res.decoder.ARSCDecoder.readEntryData(ARSCDecoder.java:324)
        at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:309)
        at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:224)
        at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:133)
        at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:85)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:51)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:780)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:64)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:56)
        at brut.androlib.Androlib.getResTable(Androlib.java:74)
        at brut.androlib.ApkDecoder.getResTable(ApkDecoder.java:251)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:109)
        at brut.apktool.Main.cmdDecode(Main.java:175)
        at brut.apktool.Main.main(Main.java:79)
I: Using Apktool 2.7.0 on com-etisalat-etida_9.3.3_arm64-v8a_merge.apk
I: Loading resource table...
```

### Steps to Reproduce
1. `java -jar lib/apktool.jar d --no-assets --only-main-classes -f -o decompile\filename.apk filename.apk`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)
-not applicable

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://play.google.com/store/apps/details?id=com.Etisalat.ETIDA (downloaded merged APK using : https://apk.support/apk-downloader)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? -yes, same-error
2. If you are trying to install a modified apk, did you resign it? -not trying to install it
3. Are you using the latest apktool version? -yes ver 2.7.0

**Comment by iBotPeaches** [comment]
Thanks, going to merge this into #2829 where I'm tracking NPEs with this new string/style parser.
