### ISSUE TITLE
[BUG] java.lang.NullPointerException: Cannot invoke "String.length()" because "value" is null error

### ISSUE THREAD

**Issue by jakanaka** [iBotPeaches/Apktool#3104]
### Information
1. **Apktool Version (`apktool -version`)** - 2.7.0
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Other
4. **Java Version (`java --version`)** - java 20.0.1 2023-04-18

### Stacktrace/Logcat

```
I: Using Apktool 2.7.0 on Emby_v3.3.07_b00003073_arm_K.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\user\Desktop\APK Editor Studio v1.7.1\data\frameworks\1.apk
I: Regular manifest package...
I: Decoding file-resources...
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.length()" because "value" is null
	at brut.androlib.res.decoder.AXmlResourceParser.getAttributeNamespace(AXmlResourceParser.java:292)
	at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeNamespace(XmlPullParserDelegate.java:176)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
	at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:80)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:139)
	at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(ResStreamDecoderContainer.java:30)
	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:143)
	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:123)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:240)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:140)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:111)
	at brut.apktool.Main.cmdDecode(Main.java:175)
	at brut.apktool.Main.main(Main.java:79)
```

### Steps to Reproduce
1. `apktool d -f -s Emby_v3.3.07_b00003073_arm_K.apk`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? 
3. Are you using the latest apktool version? yes

**Comment by zareiramin** [comment]
@iBotPeaches  i will try it, thank you.
