### ISSUE TITLE
[BUG] Crash on launch: android.content.res.Resources$NotFoundException

### ISSUE THREAD

**Issue by bushev** [iBotPeaches/Apktool#3110]
### Information
1. **Apktool Version (`apktool -version`)** - 2.7.0
2. **Operating System (Mac, Linux, Windows)** - Mac
3. **APK From? (Playstore, ROM, Other)** - Playstore
4. **Java Version (`java --version`)** - 1.8.0_371

### Stacktrace/Logcat

```
2023-06-29 17:50:33.104 19575-19575/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ru.the-app.android, PID: 19575
    java.lang.RuntimeException: Unable to start activity ComponentInfo{ru.the-app.android/ru.the-app.android.full.ui.screen.intro.activity.IntroActivityView}: android.content.res.Resources$NotFoundException: Resource ID #0x7e090013
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3685)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3842)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7e090013
        at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:225)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2446)
        at android.content.res.Resources.getLayout(Resources.java:1252)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
        at androidx.appcompat.app.AppCompatDelegateImpl.A(AppCompatDelegateImpl.java:4)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:2)
        at ru.surfstudio.android.core.ui.activity.CoreActivity.onCreate(CoreActivity.java:5)
        at android.app.Activity.performCreate(Activity.java:8054)
        at android.app.Activity.performCreate(Activity.java:8034)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3666)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3842) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7842) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
2023-06-29 17:50:33.113 19575-19575/? E/[AGC_LOG]AGConnectCrashHandler: exception catch:'java.lang.RuntimeException: Unable to start activity ComponentInfo{ru.the-app.android/ru.the-app.android.full.ui.screen.intro.activity.IntroActivityView}: android.content.res.Resources$NotFoundException: Resource ID #0x7e090013' from thread main
```

### Steps to Reproduce
1. apktool d  -f  -o the-app/ the-app.apk
2. apktool b -f --use-aapt2 -o the-app-unsigned.apk the-app/
3. ~/Library/Android/sdk/build-tools/30.0.2/apksigner sign --ks resign.keystore --ks-pass pass:123456 --out the-app-signed.apk the-app-unsigned.apk
4. Run in Android emulator

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Yes
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
Thanks - closing for existing issue - https://github.com/iBotPeaches/Apktool/issues/2849
