### ISSUE TITLE
bad utf-8 byte f0 at offset 000000ea Issue on Decompile [BUG]

### ISSUE THREAD

**Issue by swished** [iBotPeaches/Apktool#3127]
PS V:\test> apktool d test.apk -f
I: Using Apktool 2.7.0 on test.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\t\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling assets/.uutxxvwc.dex...
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: bad utf-8 byte f0 at offset 000000ea
        at org.jf.baksmali.Baksmali.disassembleDexFile(Baksmali.java:92)
        at org.jf.baksmali.Baksmali.disassembleDexFile(Baksmali.java:48)
        at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:100)
        at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:37)
        at brut.androlib.Androlib.decodeSourcesSmali(Androlib.java:103)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:151)
        at brut.apktool.Main.cmdDecode(Main.java:175)
        at brut.apktool.Main.main(Main.java:79)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: bad utf-8 byte f0 at offset 000000ea
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at org.jf.baksmali.Baksmali.disassembleDexFile(Baksmali.java:86)
        ... 7 more
Caused by: java.lang.IllegalArgumentException: bad utf-8 byte f0 at offset 000000ea
        at org.jf.util.Utf8Utils.throwBadUtf8(Utf8Utils.java:284)
        at org.jf.util.Utf8Utils.utf8BytesWithUtf16LengthToString(Utf8Utils.java:259)
        at org.jf.dexlib2.dexbacked.DexReader.readString(DexReader.java:611)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile$5.get(DexBackedDexFile.java:315)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile$5.get(DexBackedDexFile.java:308)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile$6.get(DexBackedDexFile.java:351)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile$6.get(DexBackedDexFile.java:346)
        at org.jf.dexlib2.dexbacked.DexBackedClassDef.getType(DexBackedClassDef.java:110)
        at org.jf.baksmali.Baksmali.disassembleClass(Baksmali.java:112)
        at org.jf.baksmali.Baksmali.access$000(Baksmali.java:46)
        at org.jf.baksmali.Baksmali$1.call(Baksmali.java:76)
        at org.jf.baksmali.Baksmali$1.call(Baksmali.java:74)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1623)

**Comment by iBotPeaches** [comment]
Applications tend to put bogus dex files in there (or even encrypted ones) to unpack at runtime. This is why `--only-main-classes` was invented so you can instruct Apktool to not attempt disassembly of those.
