### ISSUE TITLE
[BUG] Can't decompile modified version of Yo-Kai Watch Puni Puni

### ISSUE THREAD

**Issue by SuperTavor** [iBotPeaches/Apktool#3170]
### Information
1. **Apktool Version (`apktool -version`)** - Custom built from latest github code
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Other
4. **Java Version (`java --version`)** - 8 I think

### Stacktrace/Logcat
I: Using Apktool 2.8.1-dirty on app.apk
Exception in thread "main" brut.androlib.exceptions.AndrolibException: brut.directory.DirectoryException: java.util.zip.ZipException: Invalid CEN header (invalid zip64 extra data field size)
        at brut.androlib.res.ResourcesDecoder.hasManifest(ResourcesDecoder.java:72)
        at brut.androlib.res.ResourcesDecoder.decodeManifest(ResourcesDecoder.java:104)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:95)
        at brut.apktool.Main.cmdDecode(Main.java:183)
        at brut.apktool.Main.main(Main.java:87)
Caused by: brut.directory.DirectoryException: java.util.zip.ZipException: Invalid CEN header (invalid zip64 extra data field size)
        at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:55)
        at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:38)
        at brut.directory.ExtFile.getDirectory(ExtFile.java:49)
        at brut.androlib.res.ResourcesDecoder.hasManifest(ResourcesDecoder.java:70)
        ... 4 more
Caused by: java.util.zip.ZipException: Invalid CEN header (invalid zip64 extra data field size)
        at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1750)
        at java.base/java.util.zip.ZipFile$Source.checkExtraFields(ZipFile.java:1276)
        at java.base/java.util.zip.ZipFile$Source.checkAndAddEntry(ZipFile.java:1219)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1689)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1464)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1427)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:723)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:250)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:179)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:193)
        at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:53)
        ... 7 more

### Steps to Reproduce
1. Download my custom built apktool: https://cdn.discordapp.com/attachments/1118600746515038310/1130951410205331516/apktool-cli-all.jar

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
[If this APK can be freely shared, please upload/attach a link to it.
](https://www.mediafire.com/file/4ui5si97hssvut7/yokai-watch-puni-puni-4-98-0+(1).apk/file)
### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it? 
3. Are you using the latest apktool version?

**Comment by iBotPeaches** [comment]
Thanks - guess I improperly assumed it was an unknown file and it might have been a relic of the Zip64 format.

I couldn't replicate with a bleeding edge build, so it must be related to Windows. Will take me a bit to be in front of Windows again, won't have a Windows computer till next week.

Will probably need to revert - https://github.com/iBotPeaches/Apktool/commit/3fdc06a46f56d674864f6e425b778f5dfb86f1f7

**Comment by SuperTavor** [comment]
Yup, worked on my friend's mac. Windows is goofy

**Comment by iBotPeaches** [comment]
Actually all builds (even old) are failing now - so this might be larger than this ticket. Tracking also here: https://github.com/iBotPeaches/Apktool/issues/3174

Not quite sure what to think yet. Actions bug? Java update?

Haven't had enough time to dig. I'm off to work, will look tonight.

**Comment by SuperTavor** [comment]
Tysm for all your incredible work

**Comment by iBotPeaches** [comment]
@SuperTavor - Are you able to build a branch and give a patch a shot? https://github.com/iBotPeaches/Apktool/pull/3178

I believe the system.property changes we invoke during execution in that patch will fix your above issue.
