### ISSUE TITLE
Exception in thread "main" brut.androlib.err.UndefinedResObject: resource spec: 0x010102cd

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#320]
Original [issue 209](https://code.google.com/p/android-apktool/issues/detail?id=209) created by joel@eyrie.in on 2011-08-25T05:09:50.000Z:

> <b>What steps will reproduce the problem?</b>
> 1.Decompile the apk Tweetcaster.apk
> <b>2.</b>
> <b>3.</b>

<b>What is the expected output? What do you see instead?</b>
I: Baksmaling...
I: Loading resource table...
I: Loaded.
I: Loading resource table from file: C:\Users\Joel\apktool\framework\1.apk
I: Loaded.
W: Could not decode attr value, using undecoded value instead: ns=android, name=
hardwareAccelerated, value=0xffffffff
I: Decoding file-resources...
W: Could not decode attr value, using undecoded value instead: ns=android, name=
exitFadeDuration, value=0x010e0001
W: Could not decode attr value, using undecoded value instead: ns=android, name=
state_activated, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=
exitFadeDuration, value=0x010e0001
W: Could not decode attr value, using undecoded value instead: ns=android, name=
state_activated, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=
exitFadeDuration, value=0x010e0001
W: Could not decode attr value, using undecoded value instead: ns=android, name=
state_activated, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=
state_activated, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=
state_activated, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=
state_activated, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=
exitFadeDuration, value=0x010e0001
W: Could not decode attr value, using undecoded value instead: ns=android, name=
state_activated, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=
state_activated, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=
exitFadeDuration, value=0x010e0001
W: Could not decode attr value, using undecoded value instead: ns=android, name=
state_activated, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=
showAsAction, value=0x00000005
W: Could not decode attr value, using undecoded value instead: ns=android, name=
showAsAction, value=0x00000005
W: Could not decode attr value, using undecoded value instead: ns=android, name=
showAsAction, value=0x00000005
W: Could not decode attr value, using undecoded value instead: ns=android, name=
showAsAction, value=0x00000005
W: Could not decode attr value, using undecoded value instead: ns=android, name=
showAsAction, value=0x00000005
W: Could not decode attr value, using undecoded value instead: ns=android, name=
W: Could not decode attr value, using undecoded value instead: ns=android, name=
exitFadeDuration, value=0x010e0001
W: Could not decode attr value, using undecoded value instead: ns=android, name=
state_activated, value=0xffffffff
I: Decoding values_/_ XMLs...
Exception in thread &quot;main&quot; brut.androlib.err.UndefinedResObject: resource spec:
0x010102cd
        at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:61)
        at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:55)
        at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:51)
        at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferen
ceValue.java:59)
        at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(Re
sStyleValue.java:51)
        at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResour
ces.java:264)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:137
)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:93)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:98)
        at brut.apktool.Main.cmdDecode(Main.java:120)
        at brut.apktool.Main.main(Main.java:57)

<b>What version of the product are you using? On what operating system?</b>
1.4.1

<b>Please provide any additional information below.</b>
Can be reproduced by simply decompiling the apk Tweetcaster.apk

**Comment by bash197793** [comment]
Exception in thread "main" brut.androlib.err.UndefinedResObject: resource spec:
0x0104052e
        at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
        at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:65)
        at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:61)
        at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferen
ceValue.java:57)
        at brut.androlib.res.data.value.ResReferenceValue.encodeAsResXml(ResRefe
renceValue.java:47)
        at brut.androlib.res.data.value.ResScalarValue.encodeAsResXmlValue(ResSc
alarValue.java:58)
        at brut.androlib.res.data.value.ResScalarValue.encodeAsResXmlItemValue(R
esScalarValue.java:50)
        at brut.androlib.res.data.value.ResArrayValue.getType(ResArrayValue.java
:80)
        at brut.androlib.res.data.value.ResArrayValue.serializeToResValuesXml(Re
sArrayValue.java:52)
        at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResour
ces.java:502)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:252
)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:135)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
        at brut.apktool.Main.cmdDecode(Main.java:165)
        at brut.apktool.Main.main(Main.java:81)
