### ISSUE TITLE
Android 14 Framework Support

### ISSUE THREAD

**Issue by kaloresanket** [iBotPeaches/Apktool#3202]
### Information
1. **Apktool Version 2.8.1 ** -
2. **Windows ** -
3. **Motorola Stock ROM Android 13** -
4. **Java Version 20.0.2** -

### Stacktrace/Logcat
```
I: Using Apktool 2.8.1 on SystemUI.apk
I: Loading resource table...
W: Config flags size > 64. Size = 72. Exceeding bytes: 0x10000000.
W: Invalid data detected. Skipping: -8 byte(s)
W: Invalid config flags detected. Dropping resources: anim-ERR0
Exception in thread "main" brut.androlib.exceptions.AndrolibException: Could not decode arsc file
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:55)
        at brut.androlib.res.data.ResTable.loadResPackagesFromApk(ResTable.java:176)
        at brut.androlib.res.data.ResTable.loadMainPkg(ResTable.java:126)
        at brut.androlib.res.ResourcesDecoder.getResTable(ResourcesDecoder.java:88)
        at brut.androlib.res.ResourcesDecoder.decodeManifest(ResourcesDecoder.java:106)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:95)
        at brut.apktool.Main.cmdDecode(Main.java:190)
        at brut.apktool.Main.main(Main.java:93)
Caused by: java.io.IOException: Expected: 0x00000008, got: 0x00000201
        at brut.util.ExtDataInput.skipCheckShort(ExtDataInput.java:49)
        at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:414)
        at brut.androlib.res.decoder.ARSCDecoder.readEntryData(ARSCDecoder.java:339)
        at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:318)
        at brut.androlib.res.decoder.ARSCDecoder.readResourceTable(ARSCDecoder.java:99)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:50)
```

### Steps to Reproduce
1. `apktool d SystemUI.apk`

[SystemUI.zip](https://github.com/iBotPeaches/Apktool/files/12138510/SystemUI.zip)
[framework-res.zip](https://github.com/iBotPeaches/Apktool/files/12138509/framework-res.zip)

**Comment by iBotPeaches** [comment]
Thanks. I'll take a look. Odd that Motorola configs are exceeding the known current AOSP max of 64.

**Comment by iBotPeaches** [comment]
Looks like the Locale Numbering System at play here. I hadn't had a sample yet so was unsure how to patch it. I see the configuration now - `mcc262-mnc1-es-r419`

Marking as bug.

**Comment by iBotPeaches** [comment]
Okay, this might stay open for a bit until Android 14 officially drops. It appears this is a new qualifier that isn't yet documented online. It appears to be related to gender.

> Returns the user preference for the grammatical gender. Will be [GRAMMATICAL_GENDER_NOT_SPECIFIED](https://developer.android.com/reference/android/content/res/Configuration#GRAMMATICAL_GENDER_NOT_SPECIFIED) or [GRAMMATICAL_GENDER_NEUTRAL](https://developer.android.com/reference/android/content/res/Configuration#GRAMMATICAL_GENDER_NEUTRAL) or [GRAMMATICAL_GENDER_FEMININE](https://developer.android.com/reference/android/content/res/Configuration#GRAMMATICAL_GENDER_FEMININE) or [GRAMMATICAL_GENDER_MASCULINE](https://developer.android.com/reference/android/content/res/Configuration#GRAMMATICAL_GENDER_MASCULINE).

**Comment by kaloresanket** [comment]
Alright

**Comment by iBotPeaches** [comment]
Android 14 is quite large. I'm treating this issue as the internal framework updates, then I have:

 * #3366 
 * #3366 
 * #3369

**Comment by kaloresanket** [comment]
Hey sir it still not extracting

**Comment by iBotPeaches** [comment]
@kaloresanket - It is. Please open a new bug.
