### ISSUE TITLE
android.view.InflateException: Binary XML file line #19: Binary XML file line #19: Error inflating class androidx.appcompat.widget.AppCompatImageView

### ISSUE THREAD

**Issue by Alireza-Razavi** [iBotPeaches/Apktool#3224]
### Information
1. **Apktool Version (`apktool -version`)** - 2.8.1
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Other
4. **Java Version (`java --version`)** - java version "20.0.2" 2023-07-18

### Stacktrace/Logcat

```

2023-07-26 06:10:37.827 8018-8018/com.example E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example, PID: 8018
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example/com.example.features.tour.IntroLogoActivity}: android.view.InflateException: Binary XML file line #19: Binary XML file line #19: Error inflating class androidx.appcompat.widget.AppCompatImageView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:533)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:861)
     Caused by: android.view.InflateException: Binary XML file line #19: Binary XML file line #19: Error inflating class androidx.appcompat.widget.AppCompatImageView
     Caused by: android.view.InflateException: Binary XML file line #19: Error inflating class androidx.appcompat.widget.AppCompatImageView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at fr.d.d(Unknown Source:3)
```

### Steps to Reproduce
1. `apktool d -r file.apk`
2. `apktool b dir`

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
3. If you are trying to install a modified apk, did you resign it? Yes, i'm signing the output apk with signapk.jar
4. Are you using the latest apktool version? Yes

I'm just running `apktool d -r file.apk` and then rebuild it using `apktool b folder` and also tested with `apktool b --use-aapt2 folder` and then sign it using `signapk.jar`.
When i install resigned apk, the app crashes that i have included the stack trace.

Note: When i try to decompile it normally without `-r` switch (`apktool d file.apk`), it gives me an error while rebuilding the apk (`apktool b folder`):
```
I: Using Apktool 2.8.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes3 folder into classes3.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes4 folder into classes4.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes5 folder into classes5.dex...
I: Checking whether resources has changed...
I: Building resources...
W: D:\CyberSEC\Tools\APKTool\1\res\layout-v22\context_menu_message.xml:5: error: No resource identifier found for attribute 'clipToOutline' in package 'android'
W:
W: D:\CyberSEC\Tools\APKTool\1\res\layout-v22\item_chat_location.xml:7: error: No resource identifier found for attribute 'clipToOutline' in package 'android'
W:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\FX506HC\AppData\Local\Temp\brut_util_Jar_50133639988196842702000627428840880921.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 31, --version-code, 32649, --version-name, 8.8.15 (32649), --no-version-vectors, -F, C:\Users\FX506HC\AppData\Local\Temp\APKTOOL1531009010840672621.tmp, -e, C:\Users\FX506HC\AppData\Local\Temp\APKTOOL3773170569863015713.tmp, -0, arsc, -I, C:\Users\FX506HC\AppData\Local\apktool\framework\1.apk, -S, D:\CyberSEC\Tools\APKTool\1\res, -M, D:\CyberSEC\Tools\APKTool\1\AndroidManifest.xml]
```

**Comment by iBotPeaches** [comment]
Thanks for the report. This issue of basically a failure to inflate a class has been happening for a few years and its always difficult to pinpoint why.

A different user produce some samples and has some good research between #1948 and #2032 so I'm going to close this to merge into those existing tickets.
