### ISSUE TITLE
Invalid chunk type (1402) - AndroidManifest

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#3236]
```bash
I: Using Apktool 2.7.0 on Env145-Vip.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
Exception in thread "main" brut.androlib.err.RawXmlEncounteredException: Could not decode XML
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:145)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:151)
	at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:164)
	at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:196)
	at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:145)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:109)
	at brut.apktool.Main.cmdDecode(Main.java:175)
	at brut.apktool.Main.main(Main.java:79)
Caused by: java.io.IOException: Expected: 0x00080003 or 0x00080001, got: 0x0008b800
	at brut.util.ExtDataInput.skipCheckInt(ExtDataInput.java:45)
	at brut.androlib.res.decoder.AXmlResourceParser.doNext(AXmlResourceParser.java:834)
	at brut.androlib.res.decoder.AXmlResourceParser.next(AXmlResourceParser.java:98)
	at brut.androlib.res.decoder.AXmlResourceParser.nextToken(AXmlResourceParser.java:108)
	at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.nextToken(XmlPullParserDelegate.java:105)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:138)
	... 7 more
```
### apk
https://drive.google.com/file/d/1RqHKPlc_lQSQpgC5o8zU4p1ErWdM-eNQ/view

7z pass: apktool

_Originally posted by @4ft35t in https://github.com/iBotPeaches/Apktool/issues/2863#issuecomment-1515601225_

**Comment by iBotPeaches** [comment]
This is one mega odd APK. It triggered so many obfuscation workarounds.

```
➜  3236 apktool d Env145-Vip.apk -s -f
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool 2.8.2-22eb80-SNAPSHOT on Env145-Vip.apk
I: Loading resource table...
I: Decoding file-resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Decoding values */* XMLs...
I: Decoding AndroidManifest.xml with resources...
W: Unknown chunk type at: (0x0000cf18) skipping...
W: AXML hit unexpected end of file at byte: 0xCF18
I: Regular manifest package...
[Fatal Error] :1:1: Premature end of file.
I: Copying raw classes.dex file...
I: Copying raw classes2.dex file...
I: Copying raw classes3.dex file...
I: Copying raw classes4.dex file...
I: Copying assets and libs...
W: Skipping file VTwFsRjHTdAsemfqAdGAOlSqIOKGVybLMWZGfWHKMxNnHlKPBICHKcOBgvdVGCfUsQWAAhrtNCEnlzWayIVJrkUlSgOeIfIRvaDRmvtzmqwtQNbokPAmHbVjWnjHJsBiErhdNclptzFumnKpSBBwiNSbzeRTYFpINZrWDuIgcLqjhaXDiPDKPpomNJisobZMMoccqHQqAmBrmelrYTVVGxqIhHpbaYdDiOaZnAhEjnFbwlHdjcNNrHqoahzQJGeGQJdWQkSBqihqMFWFNuDEqnLYcLLqolhhkJuxihDLHpVpdiTWMXUmasaObRqjhQZVIFOIHl (File name too long)
W: Skipping file ¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½/ۦۖ۫t/ۦۖ۫/ۦۖ۫/ۦۖ۫/ۦۖ۫/ۦۖ۫/ۦۖ۫/ۦۖ۫/ۦۖ۫ۦۖ۫/ۦۖ۫/ۦۖ۫/ۦۖ۫/ۦۖ۫/ۦۖ۫/ۦۖ۫/ۦۖ۫/ۦۖ۫/est/aasdfsfs/fdsafa/sadfsa/addsfsdd/a/asfsf/sfdsa/adddddd/dddd/asfa/a/dddddda/dsafsa/sfasdfsfds/sadfs/a/sdfs/dsfdsasdafsda/fasdfsa//a/a/a/a/a//a/a/a/a//a/a//a/a/a/a/a/a//a/a/a/a//a/a/a//a/a/a/a///a/a/a///a/a//a/a/a/a//a//a///a/a/a/a/a/a/a/a//a/a/adddddd/dddddddddddddddd/ddddda/a/gKQgpAUzeNjQKfEJdzPYnOxVULdVsITUcrChjirQSheiTxJUoCqNFzPaqpKEUjPdHygzrFwkdOCaPkBqLRJXIhDilUNaPBNxwXmlGKseyACFKdtantYXcHTxWQkvubEY (File name too long)
I: Copying unknown files...
I: Copying original files...
➜  3236 
```

It has:

 * Unknown chunk in AXML
 * AXML missing the ending namespaces
 * Files too long in filename

**Comment by iBotPeaches** [comment]
Okay, now its perfect. We can handle the modified string block.

```
➜  3236 apktool d Env145-Vip.apk -f -s
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool 2.8.2-22eb80-SNAPSHOT on Env145-Vip.apk
I: Loading resource table...
I: Decoding file-resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Decoding values */* XMLs...
I: Decoding AndroidManifest.xml with resources...
W: Bad string block: string entry is at 1300, past end at 1300
I: Regular manifest package...
I: Copying raw classes.dex file...
I: Copying raw classes2.dex file...
I: Copying raw classes3.dex file...
I: Copying raw classes4.dex file...
I: Copying assets and libs...
W: Skipping file VTwFsRjHTdAsemfqAdGAOlSqIOKGVybLMWZGfWHKMxNnHlKPBICHKcOBgvdVGCfUsQWAAhrtNCEnlzWayIVJrkUlSgOeIfIRvaDRmvtzmqwtQNbokPAmHbVjWnjHJsBiErhdNclptzFumnKpSBBwiNSbzeRTYFpINZrWDuIgcLqjhaXDiPDKPpomNJisobZMMoccqHQqAmBrmelrYTVVGxqIhHpbaYdDiOaZnAhEjnFbwlHdjcNNrHqoahzQJGeGQJdWQkSBqihqMFWFNuDEqnLYcLLqolhhkJuxihDLHpVpdiTWMXUmasaObRqjhQZVIFOIHl (File name too long)
W: Skipping file ¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½//¦ª¦û¦½/¦ª¦û¦½/ۦۖ۫t/ۦۖ۫/ۦۖ۫/ۦۖ۫/ۦۖ۫/ۦۖ۫/ۦۖ۫/ۦۖ۫/ۦۖ۫ۦۖ۫/ۦۖ۫/ۦۖ۫/ۦۖ۫/ۦۖ۫/ۦۖ۫/ۦۖ۫/ۦۖ۫/ۦۖ۫/est/aasdfsfs/fdsafa/sadfsa/addsfsdd/a/asfsf/sfdsa/adddddd/dddd/asfa/a/dddddda/dsafsa/sfasdfsfds/sadfs/a/sdfs/dsfdsasdafsda/fasdfsa//a/a/a/a/a//a/a/a/a//a/a//a/a/a/a/a/a//a/a/a/a//a/a/a//a/a/a/a///a/a/a///a/a//a/a/a/a//a//a///a/a/a/a/a/a/a/a//a/a/adddddd/dddddddddddddddd/ddddda/a/gKQgpAUzeNjQKfEJdzPYnOxVULdVsITUcrChjirQSheiTxJUoCqNFzPaqpKEUjPdHygzrFwkdOCaPkBqLRJXIhDilUNaPBNxwXmlGKseyACFKdtantYXcHTxWQkvubEY (File name too long)
I: Copying unknown files...
I: Copying original files...
➜  3236 
```
