### ISSUE TITLE
[BUG] Peculiar error when decompiling an app

### ISSUE THREAD

**Issue by SuperTavor** [iBotPeaches/Apktool#3253]
### Information
1. **Apktool Version (`apktool -version`)** - 2.8.1
2. **Operating System (Mac, Linux, Windows)** - Win11
3. **APK From? (Playstore, ROM, Other)** - other
4. **Java Version (`java --version`)** - 8

### Stacktrace/Logcat
```
Exception in thread "main" brut.androlib.exceptions.AndrolibException: brut.directory.DirectoryException: Error copying file: assets
	at brut.androlib.ApkDecoder.copyRawFiles(ApkDecoder.java:243)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:142)
	at brut.apktool.Main.cmdDecode(Main.java:190)
	at brut.apktool.Main.main(Main.java:93)
Caused by: brut.directory.DirectoryException: Error copying file: assets
	at brut.directory.DirUtil.copyToDir(DirUtil.java:102)
	at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:208)
	at brut.androlib.ApkDecoder.copyRawFiles(ApkDecoder.java:230)
	... 3 more
Caused by: brut.directory.DirectoryException: Error copying file: assets/664
	at brut.directory.DirUtil.copyToDir(DirUtil.java:102)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:71)
	at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:198)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:87)
	... 5 more
Caused by: java.nio.file.NoSuchFileException: cache\assets\assets\664
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:235)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
	at java.base/java.nio.file.Files.newOutputStream(Files.java:220)
	at brut.directory.DirUtil.copyToDir(DirUtil.java:96)
	... 8 more
```
### Steps to Reproduce
1. `apktool d apk`

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://www.mediafire.com/file/57c4qva4pytjzj9/gen_signed.apk/file

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? ye
2. If you are trying to install a modified apk, did you resign it? ye
3. Are you using the latest apktool version? ye

**Comment by iBotPeaches** [comment]
I couldn't replicate on my side - granted I'm not on Windows.

```
➜  3253 apktool d gen_signed.apk -s -f
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool v2.8.1-54-7405e504-SNAPSHOT on gen_signed.apk
I: Loading resource table...
I: Decoding file-resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Decoding values */* XMLs...
I: Decoding AndroidManifest.xml with resources...
I: Regular manifest package...
I: Copying raw classes.dex file...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
➜  3253 
```

So this is 1 of two things.

1. Its already fixed from the large pending changes in 2.8.2
2. This is some charset issue on Windows or reserved character or something, which we are tracking already in #1460

So I'm closing.
