### ISSUE TITLE
[BUG] Error when decompiling one of the Yo-Kai Watch 1 Mobile apks (it's a split apk)

### ISSUE THREAD

**Issue by SuperTavor** [iBotPeaches/Apktool#3266]
### Information
1. **Apktool Version (`apktool -version`)** - 2.8.1
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Other
4. **Java Version (`java --version`)** - 8

### Stacktrace/Logcat
I: Using Apktool 2.8.1 on split_config.xxhdpi.apk
I: Loading resource table...
Exception in thread "main" java.lang.NullPointerException
        at brut.androlib.res.decoder.ARSCDecoder.readResourceTable(ARSCDecoder.java:125)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:50)
        at brut.androlib.res.data.ResTable.loadResPackagesFromApk(ResTable.java:176)
        at brut.androlib.res.data.ResTable.loadMainPkg(ResTable.java:126)
        at brut.androlib.res.ResourcesDecoder.getResTable(ResourcesDecoder.java:88)
        at brut.androlib.res.ResourcesDecoder.decodeManifest(ResourcesDecoder.java:106)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:95)
        at brut.apktool.Main.cmdDecode(Main.java:190)
        at brut.apktool.Main.main(Main.java:93)
Press any key to continue . . .

### Steps to Reproduce
1. `apktool d  `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
[If this APK can be freely shared, please upload/attach a link to it.
](https://drive.google.com/file/d/16WI5RX75G-dXddPB0LBjjDUG2dRIIdLE/view?usp=sharing)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?

# it's worth mentioning this is only a part of the apk, the full app is an app bundle (apks)

**Comment by iBotPeaches** [comment]
This is resolved already (the empty resource table) in 2.8.2.

```
➜  3266 apktool d split_config.xxhdpi.apk 
I: Using Apktool v2.8.1-41-0e226928-SNAPSHOT on split_config.xxhdpi.apk
I: Loading resource table...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Sparsely packed resources detected.
I: Regular manifest package...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  3266 
```

Closing.
