### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ben5858** [iBotPeaches/Apktool#3270]
### Information
1. **Apktool Version 2.8.1
2. **Operating System Windows
3. **APK From? Other
4. **Java Version jdk20 or jdk1.8 or jdk 11

### Stacktrace/Logcat

C:\Users\17290>apktool -version
2.8.1

C:\Users\17290>apktool d -f E:\apk\base.apk
I: Using Apktool 2.8.1 on base.apk
I: Loading resource table...
W: Skipping unknown chunk data of size 264
I: Decoding AndroidManifest.xml with resources...
Exception in thread "main" brut.androlib.exceptions.RawXmlEncounteredException: Could not decode XML
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:145)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:151)
        at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:166)
        at brut.androlib.res.ResourcesDecoder.decodeManifestWithResources(ResourcesDecoder.java:166)
        at brut.androlib.res.ResourcesDecoder.decodeManifest(ResourcesDecoder.java:106)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:95)
        at brut.apktool.Main.cmdDecode(Main.java:190)
        at brut.apktool.Main.main(Main.java:93)
Caused by: java.io.EOFException: reached end of stream after reading 13320 bytes; 1790034188 bytes expected
        at com.google.common.io.ByteStreams.readFully(ByteStreams.java:799)
        at com.google.common.io.ByteStreams.readFully(ByteStreams.java:781)
        at com.google.common.io.LittleEndianDataInputStream.readFully(LittleEndianDataInputStream.java:66)
        at brut.util.DataInputDelegate.readFully(DataInputDelegate.java:66)
        at brut.androlib.res.decoder.StringBlock.readWithoutChunk(StringBlock.java:59)
        at brut.androlib.res.decoder.StringBlock.readWithChunk(StringBlock.java:38)
        at brut.androlib.res.decoder.AXmlResourceParser.doNext(AXmlResourceParser.java:654)
        at brut.androlib.res.decoder.AXmlResourceParser.next(AXmlResourceParser.java:92)
        at brut.androlib.res.decoder.AXmlResourceParser.nextToken(AXmlResourceParser.java:102)
        at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.nextToken(XmlPullParserDelegate.java:105)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:138)
        ... 7 more

C:\Users\17290>
### Steps to Reproduce
1.apktool d -f E:\apk\base.apk

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? yes
3. Are you using the latest apktool version? yes

**Comment by ben5858** [comment]
please help me，every teacher

**Comment by iBotPeaches** [comment]
Sorry, I don't see a sample and I'm fairly sure this is patched anyway. If its having more string entries reported than actually exist.

**Comment by leqnam** [comment]
I faced same issue. if need I can attach the sample
