### ISSUE TITLE
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by tejasnikumbh1432** [iBotPeaches/Apktool#3284]
### Information
1. **Apktool Version (`apktool -version`)** -
2. **Operating System (Mac, Linux, Windows)** -
3. **APK From? (Playstore, ROM, Other)** -
4. **Java Version (`java --version`)** -

### Stacktrace/Logcat

```
Include stacktrace here
```

### Steps to Reproduce
1. `apktool `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
2. If you are trying to install a modified apk, did you resign it?
3. Are you using the latest apktool version?
4.  Using Apktool 2.6.1
I: Smaling smali folder into classes.dex...
I: Smaling smali_classes2 folder into classes2.dex...
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at org.jf.smali.smaliFlexLexer.newToken(smaliFlexLexer.java:3255)
	at org.jf.smali.smaliFlexLexer.newToken(smaliFlexLexer.java:3276)
	at org.jf.smali.smaliFlexLexer.yylex(smaliFlexLexer.java:3943)
	at org.jf.smali.smaliFlexLexer.nextToken(smaliFlexLexer.java:3198)
	at org.antlr.runtime.BufferedTokenStream.fetch(BufferedTokenStream.java:143)
	at org.antlr.runtime.BufferedTokenStream.sync(BufferedTokenStream.java:137)
	at org.antlr.runtime.CommonTokenStream.consume(CommonTokenStream.java:71)
	at org.antlr.runtime.BaseRecognizer.match(BaseRecognizer.java:106)
	at org.jf.smali.smaliParser.insn_format22c_field(smaliParser.java:13224)
	at org.jf.smali.smaliParser.instruction(smaliParser.java:11012)
	at org.jf.smali.smaliParser.ordered_method_item(smaliParser.java:2195)
	at org.jf.smali.smaliParser.statements_and_directives(smaliParser.java:1915)
	at org.jf.smali.smaliParser.method(smaliParser.java:1711)
	at org.jf.smali.smaliParser.smali_file(smaliParser.java:624)
	at brut.androlib.mod.SmaliMod.assembleSmaliFile(SmaliMod.java:63)
	at brut.androlib.src.SmaliBuilder.buildFile(SmaliBuilder.java:71)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:56)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:37)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:430)
	at brut.androlib.Androlib.buildNonDefaultSources(Androlib.java:376)
	at brut.androlib.Androlib.build(Androlib.java:314)
	at brut.androlib.Androlib.build(Androlib.java:280)
	at brut.apktool.Main.cmdBuild(Main.java:255)
	at brut.apktool.Main.main(Main.java:82)

**Comment by tejasnikumbh1432** [comment]
plz help me
