### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by GoldenBoot2** [iBotPeaches/Apktool#3290]
### Information
1. **Apktool Version (`2.8.1`)**
2. **Operating System (Linux, Windows)**
3. **APK From? (Playstore)**
4. **Java Version (`17.0.8 2023-07-18 LTS`)**

### Stacktrace/Logcat

```
Exception in thread "main" brut.androlib.exceptions.AndrolibException: brut.directory.DirectoryException: java.util.zip.ZipException: Invalid CEN header (invalid zip64 extra data field size)
        at brut.androlib.res.ResourcesDecoder.hasManifest(ResourcesDecoder.java:70)
        at brut.androlib.res.ResourcesDecoder.decodeManifest(ResourcesDecoder.java:102)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:95)
        at brut.apktool.Main.cmdDecode(Main.java:190)
        at brut.apktool.Main.main(Main.java:93)
Caused by: brut.directory.DirectoryException: java.util.zip.ZipException: Invalid CEN header (invalid zip64 extra data field size)
        at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:55)
        at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:38)
        at brut.directory.ExtFile.getDirectory(ExtFile.java:49)
        at brut.androlib.res.ResourcesDecoder.hasManifest(ResourcesDecoder.java:68)
        ... 4 more
Caused by: java.util.zip.ZipException: Invalid CEN header (invalid zip64 extra data field size)
        at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1730)
        at java.base/java.util.zip.ZipFile$Source.checkExtraFields(ZipFile.java:1262)
        at java.base/java.util.zip.ZipFile$Source.checkAndAddEntry(ZipFile.java:1213)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1669)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1447)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1409)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:717)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:251)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:180)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:194)
        at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:53)
        ... 7 more
```

### APK
https://play.google.com/store/apps/details?id=gman.vedicastro

**Comment by iBotPeaches** [comment]
You'll want to update your helper scripts to opt-out of this increased Java ZIP validation.

https://github.com/iBotPeaches/Apktool/issues/3198

It may be fixed anyway once this patch is released to various versions - https://github.com/openjdk/jdk/pull/15273

**Comment by iBotPeaches** [comment]
> how to do this?

Grab respective helper script from here - https://github.com/iBotPeaches/Apktool/tree/master/scripts
