### ISSUE TITLE
[BUG] Recompiling Instagram without touching anything does not work

### ISSUE THREAD

**Issue by vasll** [iBotPeaches/Apktool#3293]
### Information
1. **Apktool Version (`apktool -version`)** - 2.8.1
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - Playstore
4. **Java Version (`java --version`)** - openjdk 17.0.8

### Stacktrace/Logcat
```java
Java.lang.RuntimeException: Unable to start activity ComponentInfo{com.instagram.android/com.instagram.mainactivity.MainActivity}: android.view.InflateException: Binary XML file line #41: Binary XML file line #47: Error inflating class com.instagram.common.ui.base.IgSimpleImageView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3822)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3968)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8252)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
	at Z.init(1692965439227-ac94b427-2fc6-56bf-bfe7-427d02d3bdff)
Caused by: android.view.InflateException: Binary XML file line #41: Binary XML file line #47: Error inflating class com.instagram.common.ui.base.IgSimpleImageView
Caused by: android.view.InflateException: Binary XML file line #47: Error inflating class com.instagram.common.ui.base.IgSimpleImageView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:883)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1035)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:990)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1152)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1113)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1155)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1113)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1155)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1113)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1155)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1113)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1297)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1148)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1113)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1155)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1265)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1148)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1113)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1155)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1113)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:711)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:548)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:486)
	at X.21p.A0I(:23)
	at androidx.appcompat.app.AppCompatActivity.setContentView(:268435463)
	at com.instagram.base.activity.BaseFragmentActivity.onCreate(:22)
	at com.instagram.mainactivity.MainActivity.onCreate(:640)
	at android.app.Activity.performCreate(Activity.java:8516)
	at android.app.Activity.performCreate(Activity.java:8480)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1418)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3803)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3968)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8252)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: android.content.res.Resources$NotFoundException: Drawable com.instagram.android:drawable/instagram_arrow_left_pano_outline_24 with resource ID #0x7f080676
Caused by: android.content.res.Resources$NotFoundException: File I1801A4 from drawable resource ID #0x7f080676
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:901)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:692)
	at android.content.res.MiuiResourcesImpl.loadDrawable(MiuiResourcesImpl.java:307)
	at android.content.res.Resources.loadDrawable(Resources.java:1026)
	at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:1020)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:994)
	at android.widget.ImageView.<init>(ImageView.java:210)
	at android.widget.ImageView.<init>(ImageView.java:196)
	at android.widget.ImageView.<init>(ImageView.java:192)
	at com.instagram.common.ui.base.IgSimpleImageView.<init>(:0)
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:883)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1035)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:990)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1152)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1113)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1155)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1113)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1155)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1113)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1155)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1113)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1297)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1148)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1113)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1155)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1265)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1148)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1113)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1155)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1113)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:711)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:548)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:486)
	at X.21p.A0I(:23)
	at androidx.appcompat.app.AppCompatActivity.setContentView(:268435463)
	at com.instagram.base.activity.BaseFragmentActivity.onCreate(:22)
	at com.instagram.mainactivity.MainActivity.onCreate(:640)
	at android.app.Activity.performCreate(Activity.java:8516)
	at android.app.Activity.performCreate(Activity.java:8480)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1418)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3803)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3968)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8252)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: java.io.FileNotFoundException: I1801A4
	at android.content.res.AssetManager.nativeOpenNonAsset(Native Method)
	at android.content.res.AssetManager.openNonAsset(AssetManager.java:1031)
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:887)
	... 54 more
```

### Steps to Reproduce
0. Download any latest Instagram .apk
1. `apktool d instagram.apk`
2. `apktool b .` (in the generated folder)
3. Sign apk with `apksigner`
4. Install the apk
5. Start it, it will crash

### APK
I tested the latest 5 Instagram versions from various websites, none of them worked. 
I tried an older version (192.x) and it worked well.

### Questions to ask before submission
1. [x] Have you tried `apktool d`, `apktool b` without changing anything?
6. [x] If you are trying to install a modified apk, did you resign it?
7. [x] Are you using the latest apktool version?

**Comment by iBotPeaches** [comment]
Thanks for the report.

This is a tricky known issue we are tracking here - https://github.com/iBotPeaches/Apktool/issues/2670
