### ISSUE TITLE
i have faced new lssue from apk easy tool not compile apk

### ISSUE THREAD

**Issue by tejasnikumbh1432** [iBotPeaches/Apktool#3304]
I: Using Apktool 2.8.1
I: Smaling smali folder into classes.dex...
I: Smaling smali_classes2 folder into classes2.dex...
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at org.antlr.runtime.tree.CommonTreeAdaptor.create(CommonTreeAdaptor.java:58)
	at org.antlr.runtime.tree.BaseTreeAdaptor.nil(BaseTreeAdaptor.java:48)
	at com.android.tools.smali.smali.smaliParser.insn_format22x(smaliParser.java:13861)
	at com.android.tools.smali.smali.smaliParser.instruction(smaliParser.java:11096)
	at com.android.tools.smali.smali.smaliParser.ordered_method_item(smaliParser.java:2195)
	at com.android.tools.smali.smali.smaliParser.statements_and_directives(smaliParser.java:1915)
	at com.android.tools.smali.smali.smaliParser.method(smaliParser.java:1711)
	at com.android.tools.smali.smali.smaliParser.smali_file(smaliParser.java:624)
	at brut.androlib.mod.SmaliMod.assembleSmaliFile(SmaliMod.java:64)
	at brut.androlib.src.SmaliBuilder.buildFile(SmaliBuilder.java:71)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:56)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:37)
	at brut.androlib.ApkBuilder.buildSourcesSmali(ApkBuilder.java:217)
	at brut.androlib.ApkBuilder.buildNonDefaultSources(ApkBuilder.java:163)
	at brut.androlib.ApkBuilder.build(ApkBuilder.java:100)
	at brut.apktool.Main.cmdBuild(Main.java:268)
	at brut.apktool.Main.main(Main.java:96)
Compile failed. Please read the log

Click here for more infomation about Apktool issues
https://forum.xda-developers.com/t/tool-windows-apk-easy-tool-v1-58-3-dec-2020.3333960/#post-65775601

**Comment by tejasnikumbh1432** [comment]
i create changers but show this problem as itis
