### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by wolaitoudaima** [iBotPeaches/Apktool#3306]
### Information
1. **Apktool Version (`apktool -version`)** - 2.8.1 and git master
2. **Operating System (Mac, Linux, Windows)** - mac
3. **APK From? (Playstore, ROM, Other)** - other
4. **Java Version (`java --version`)** - 11

### Stacktrace/Logcat

```
I: Using Apktool 2.8.1 on xx.apk
I: Loading resource table...
S: Unknown chunk type: 0fff
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "brut.androlib.res.data.ResPackage.getResSpecCount()" because "this.mPkg" is null
	at brut.androlib.res.decoder.ARSCDecoder.readResourceTable(ARSCDecoder.java:125)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:50)
	at brut.androlib.res.data.ResTable.loadResPackagesFromApk(ResTable.java:176)
	at brut.androlib.res.data.ResTable.loadMainPkg(ResTable.java:126)
	at brut.androlib.res.ResourcesDecoder.getResTable(ResourcesDecoder.java:88)
	at brut.androlib.res.ResourcesDecoder.decodeManifest(ResourcesDecoder.java:106)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:95)
	at brut.apktool.Main.cmdDecode(Main.java:190)
	at brut.apktool.Main.main(Main.java:93)
```

### Steps to Reproduce
1. `apktool d`

https://github.com/iBotPeaches/Apktool/issues/3266
I saw on the issue that this problem has been solved, so I downloaded the latest version of master, and the following exception occurred:
apktool d
```
I: Using Apktool v2.8.1-56-c7915cd6-SNAPSHOT on xx.apk
I: Loading resource table...
S: Unknown chunk type: 0fff
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/mt/Library/apktool/framework/1.apk
W: Could not decode attr value, using undecoded value instead: ns=qusdqz, name=theme, value=0x7f0f01d2
W: Could not decode attr value, using undecoded value instead: ns=, name=, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=, name=http://schemas.android.com/apk/res/android, value=0x1200000c
W: Could not decode attr value, using undecoded value instead: ns=, name=, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=qusdqz, name=theme, value=0x7f0f01d3
W: Could not decode attr value, using undecoded value instead: ns=qusdqz, name=theme, value=0x7f0f01d3
I: Regular manifest package...
[Fatal Error] :2:42: 与元素类型 "manifest" 相关联的属性名 "n1:http:" 必须后跟 ' = ' 字符。
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
```
Then I don't make any changes and run the 'java -jar apktool-v2.8.1-56-c7915cd6-SNAPSHOT.jar b xx' command directly：
```
I: Using Apktool v2.8.1-56-c7915cd6-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether sources has changed...
I: Smaling smali_classes2 folder into classes2.dex...
[Fatal Error] :2:42: 与元素类型 "manifest" 相关联的属性名 "n1:http:" 必须后跟 ' = ' 字符。
I: Checking whether resources has changed...
I: Building resources...
W: /opt/android_key/xx/AndroidManifest.xml:2: error: Error parsing XML: not well-formed (invalid token)
W:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/h4/5_djqwgd6mx1wk3g805htzsr0000gn/T/brut_util_Jar_148220882399602723583602462776515045073.tmp, p, --forced-package-id, 0, --version-code, 1, --no-version-vectors, -F, /var/folders/h4/5_djqwgd6mx1wk3g805htzsr0000gn/T/APKTOOL3177177387482612892.tmp, -e, /var/folders/h4/5_djqwgd6mx1wk3g805htzsr0000gn/T/APKTOOL2340416440425213989.tmp, -0, arsc, -I, /Users/mt/Library/apktool/framework/1.apk, -S, /opt/android_key/xx/res, -M, /opt/android_key/xx/AndroidManifest.xml]
```

@iBotPeaches

**Comment by iBotPeaches** [comment]
Hmm following the updates in here:

 * not well-formed, known bug here: https://github.com/iBotPeaches/Apktool/issues/1407
 * mPkg is null fixed here: https://github.com/iBotPeaches/Apktool/pull/3230
 * undecoded value known here: https://github.com/iBotPeaches/Apktool/issues/3183#issuecomment-1644070864
 
 Thanks for the report. I'll close to track in the existing issues.

**Comment by wolaitoudaima** [comment]
Do you have a plan for how long it will take to fix these issues?
