### ISSUE TITLE
Error: Apk execution failed[BUG]

### ISSUE THREAD

**Issue by Hunterz72** [iBotPeaches/Apktool#3320]
```
[-] I: Using Apktool 2.8.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
Exception in thread "main" com.android.tools.smali.util.ExceptionWithContext: Exception occurred while writing code_item for method Landroidx/compose/runtime/InvalidationResult;->values()[Landroidx/compose/runtime/InvalidationResult;
        at com.android.tools.smali.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1119)
        at com.android.tools.smali.dexlib2.writer.DexWriter.writeTo(DexWriter.java:415)
        at com.android.tools.smali.dexlib2.writer.DexWriter.writeTo(DexWriter.java:370)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:58)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:37)
        at brut.androlib.ApkBuilder.buildSourcesSmali(ApkBuilder.java:217)
        at brut.androlib.ApkBuilder.buildSources(ApkBuilder.java:148)
        at brut.androlib.ApkBuilder.build(ApkBuilder.java:99)
        at brut.apktool.Main.cmdBuild(Main.java:268)
        at brut.apktool.Main.main(Main.java:96)
Caused by: com.android.tools.smali.util.ExceptionWithContext: Error while writing instruction at code offset 0x2
        at com.android.tools.smali.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1392)
        at com.android.tools.smali.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1115)
        ... 9 more
Caused by: com.android.tools.smali.util.ExceptionWithContext: Unsigned short value out of range: 65566
        at com.android.tools.smali.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:115)
        at com.android.tools.smali.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:397)
        at com.android.tools.smali.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1352)
        ... 10 more

Error: apktool execution failed
```

This error occurs when embedding payload using msfvenom. Could anyone help with this??

**Comment by iBotPeaches** [comment]
> Caused by: com.android.tools.smali.util.ExceptionWithContext: Unsigned short value out of range: 65566

The payload packing you've done has exceeded the amount of methods allowed in a dex file (unsigned short). There is no bug here and that is a limitation of the dex format.

**Comment by Hunterz72** [comment]
> > Caused by: com.android.tools.smali.util.ExceptionWithContext: Unsigned short value out of range: 65566
> 
> The payload packing you've done has exceeded the amount of methods allowed in a dex file (unsigned short). There is no bug here and that is a limitation of the dex format.

But how do i resolve this error?? Do i have to do it manually??

**Comment by cyber-wing7** [comment]
hey hunter if your problem is solved then plz tell me the solution cauz i am facing same issue

**Comment by cyber-wing7** [comment]
![Uploading Screenshot 2023-12-18 184513.png…]()

**Comment by cyber-wing7** [comment]
![Screenshot 2023-12-18 184513](https://github.com/iBotPeaches/Apktool/assets/154236510/015bb813-151d-43d3-a891-4cb3e774b7d8)

**Comment by evilhackersai** [comment]
please say how to resolve it and if there is any other alternative than say me that also

**Comment by yahu1031** [comment]
any update here @iBotPeaches ?

**Comment by iBotPeaches** [comment]
> any update here @iBotPeaches ?

What is there to update? Isn't my request the answer here https://github.com/iBotPeaches/Apktool/issues/3320#issuecomment-1708370514 ?

**Comment by yahu1031** [comment]
But this is happening in metaplsoit which is automated :( felt scared that may ruin up the flow if I do manually. Is there any other way out? @iBotPeaches
