### ISSUE TITLE
[BUG]apk encode by 2.8.1 will crash at Android7.1.1

### ISSUE THREAD

**Issue by 37syljq** [iBotPeaches/Apktool#3329]
when using `--use-aapt2` to build a apk, then apk can not be installed at  Android7.1.1
### Information
1. **Apktool Version (`apktool -version`)** - 2.8.1
2. **Operating System (Mac, Linux, Windows)** - Mac, Linux
3. **APK From? (Playstore, ROM, Other)** - Other
4. **Java Version (`java --version`)** - `openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9)
OpenJDK 64-Bit Server VM (build 11.0.10+9, mixed mode)`

### Stacktrace/Logcat

```
FATAL EXCEPTION: main
Process: com.demo.flamingo, PID: 7212
java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: android.content.res.Resources$NotFoundException: String resource ID #0x7f090000
 at android.app.ActivityThread.installProvider(ActivityThread.java:6029)
 at android.app.ActivityThread.installContentProviders(ActivityThread.java:5592)
 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5531)
 at android.app.ActivityThread.-wrap2(ActivityThread.java)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1599)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:154)
 at android.app.ActivityThread.main(ActivityThread.java:6292)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:906)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796)
Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x7f090000
 at android.content.res.Resources.getText(Resources.java:352)
 at android.content.res.Resources.getString(Resources.java:398)
 at android.content.Context.getString(Context.java:481)
 at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:216)
 at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206)
 at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45)
 at android.content.ContentProvider.attachInfo(ContentProvider.java:1908)
 at android.content.ContentProvider.attachInfo(ContentProvider.java:1883)
 at android.app.ActivityThread.installProvider(ActivityThread.java:6026)
 at android.app.ActivityThread.installContentProviders(ActivityThread.java:5592) 
 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5531) 
 at android.app.ActivityThread.-wrap2(ActivityThread.java) 
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1599) 
 at android.os.Handler.dispatchMessage(Handler.java:102) 
 at android.os.Looper.loop(Looper.java:154) 
 at android.app.ActivityThread.main(ActivityThread.java:6292) 
 at java.lang.reflect.Method.invoke(Native Method) 
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:906) 
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796) 
```

### Steps to Reproduce
1. `apktool --only-main-classes --use-aapt2 d demo.apk -o ./demo`
2. `apktool b --use-aapt2 ./demo`
3. sign apk and install

### APK
[demo_apk.zip](https://github.com/iBotPeaches/Apktool/files/12594060/demo_apk.zip)

**Comment by user0-tb** [comment]
Have you tried without `--use-aapt2` flag?

**Comment by iBotPeaches** [comment]
Thanks for report. Closing for the various tickets we have for this type of issue so I can correlate them.

 * https://github.com/iBotPeaches/Apktool/issues/2849
 * https://github.com/iBotPeaches/Apktool/issues/2670
 * https://github.com/iBotPeaches/Apktool/issues/2598
 * https://github.com/iBotPeaches/Apktool/issues/1948
 
 Thanks for the sample.

**Comment by 37syljq** [comment]
> Have you tried without `--use-aapt2` flag?

yes, without `--use-aapt2`, it will not crash, but it is still a bug, I think

**Comment by user0-tb** [comment]
@37syljq It's Not actually a Bug, i think.
