### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by beaumontk** [iBotPeaches/Apktool#3343]
### Information
1. **Apktool Version (`apktool -version`)** - 2.7.0
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - Other
4. **Java Version (`java --version`)** - 1.8.0_111

### Stacktrace/Logcat

```
Include stacktrace here
```
/home/kb/apktool/apktool b -f BorrowBox_3_01_10 -o KB_BorrowBox.apk
32 bit support is deprecated. Apktool will not support 32bit on v3.0.0.
I: Using Apktool 2.7.0
I: Smaling smali folder into classes.dex...
Exception in thread "main" org.jf.util.ExceptionWithContext: 
Exception occurred while writing code_item for method Landroidx/collection/LongSparseArray;->clone()Landroidx/collection/LongSparseArray;
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1058)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:354)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:309)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:58)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:37)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:437)
	at brut.androlib.Androlib.buildSources(Androlib.java:368)
	at brut.androlib.Androlib.build(Androlib.java:320)
	at brut.androlib.Androlib.build(Androlib.java:287)
	at brut.apktool.Main.cmdBuild(Main.java:263)
	at brut.apktool.Main.main(Main.java:82)
Caused by: org.jf.util.ExceptionWithContext: Error while writing instruction at code offset 0x12
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1331)
	at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1054)
	... 10 more
Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65540
	at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
	at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:356)
	at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1291)
	... 11 more
### Steps to Reproduce
1. `apktool `

    #@12
    invoke-virtual {v1}, [Ljava/lang/Object;->clone()Ljava/lang/Object;

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? yes
2. If you are trying to install a modified apk, did you resign it? 
3. Are you using the latest apktool version? No

**Comment by beaumontk** [comment]
Trying to edit, but not working on my laptop! I did make some changes to the apk, but not connected to the crash.
So I just tried building the original and it turns out that there are other issues with this apk.
Best to close the issue. Sorry!

**Comment by iBotPeaches** [comment]
>  Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65540

This means you've extended the amount of methods (unsigned short) allowed in a dex file. So there is nothing Apktool can do here.

**Comment by beaumontk** [comment]
Mystery solved! Thanks
    On Sunday, 24 September 2023 at 14:44:07 BST, Connor Tumbleson ***@***.***> wrote:  
 
 



Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65540


This means you've extended the amount of methods (unsigned short) allowed in a dex file. So there is nothing Apktool can do here.
