### ISSUE TITLE
[BUG] Aapt2 vs Aapt1: error: invalid value for type 'raw'. Expected a reference.

### ISSUE THREAD

**Issue by auermich93** [iBotPeaches/Apktool#3388]
### Information
1. **Apktool Version (`apktool -version`)** - 2.9.0
2. **Operating System (Mac, Linux, Windows)** - Windows, Linux
3. **APK From? (Playstore, ROM, Other)** - FDroid
4. **Java Version (`java --version`)** - 15.0.2

### Steps to Reproduce

```
apktool d ch.deletescape.lawnchair.plah.apk -f (Linux)
I: Using Apktool 2.7.0 on ch.deletescape.lawnchair.plah.apk
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: java.util.zip.ZipException: Invalid CEN header (invalid zip64 extra data field size)
        at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:294)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:96)
        at brut.apktool.Main.cmdDecode(Main.java:175)
        at brut.apktool.Main.main(Main.java:79)
Caused by: brut.directory.DirectoryException: java.util.zip.ZipException: Invalid CEN header (invalid zip64 extra data field size)
        at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:55)
        at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:38)
        at brut.directory.ExtFile.getDirectory(ExtFile.java:49)
        at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:292)

// I have even some logs where decoding with 2.7.0 succeeds on Linux but fails upon building.

$ java -jar ~/scripts/apktool_2.7.0.jar d ch.deletescape.lawnchair.plah.apk -f (Windows)
I: Using Apktool 2.7.0 on ch.deletescape.lawnchair.plah.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Michael\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/notification_bg_low_normal.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/notification_bg_normal.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/notification_bg_low_normal.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/notification_bg_normal_pressed.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/notification_bg_low_pressed.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/notification_bg_low_pressed.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/notification_bg_low_normal.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/notification_bg_normal.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/notification_bg_normal_pressed.9.png". Renaming it to *.png.
S: Could not decode file, replacing by FALSE value: raw/keep.xml
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/notification_bg_low_pressed.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/notification_bg_normal_pressed.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/notification_bg_normal.9.png". Renaming it to *.png.
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

$ java -jar ~/scripts/apktool_2.7.0.jar b
I: Using Apktool 2.7.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: warning: string 'show_hidden_pref_off' has no default translation.
W: warning: string 'show_hidden_pref_on' has no default translation.
W: warning: string 'show_hidden_pref_title' has no default translation.
I: Copying libs... (/kotlin)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk into: .\dist\ch.deletescape.lawnchair.plah.apk

$ apktool d ch.deletescape.lawnchair.plah.apk -f
I: Using Apktool 2.8.0 on ch.deletescape.lawnchair.plah.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Michael\AppData\Local\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/notification_bg_normal_pressed.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/notification_bg_normal.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/notification_bg_normal_pressed.9.png". Renaming it to *.png.
S: Could not decode file, replacing by FALSE value: raw/keep.xml
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/notification_bg_normal.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/notification_bg_low_normal.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/notification_bg_normal_pressed.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/notification_bg_low_normal.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/notification_bg_low_pressed.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/notification_bg_low_pressed.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/notification_bg_normal.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/notification_bg_low_pressed.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/notification_bg_low_normal.9.png". Renaming it to *.png.
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

$ apktool b
I: Using Apktool 2.8.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: warning: string 'show_hidden_pref_off' has no default translation.
W: warning: string 'show_hidden_pref_on' has no default translation.
W: warning: string 'show_hidden_pref_title' has no default translation.
I: Copying libs... (/kotlin)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk into: .\dist\ch.deletescape.lawnchair.plah.apk

$ apktool d ch.deletescape.lawnchair.plah.apk -f
I: Using Apktool 2.8.1 on ch.deletescape.lawnchair.plah.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/auermich/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
S: Could not decode file, replacing by FALSE value: raw/keep.xml
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/notification_bg_normal_pressed.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/notification_bg_low_normal.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/notification_bg_low_normal.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/notification_bg_normal_pressed.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/notification_bg_low_pressed.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/notification_bg_normal.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/notification_bg_normal.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/notification_bg_normal_pressed.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/notification_bg_low_pressed.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/notification_bg_low_normal.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/notification_bg_normal.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/notification_bg_low_pressed.9.png". Renaming it to *.png.
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

$ apktool b
I: Using Apktool 2.8.1
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: warning: string 'show_hidden_pref_off' has no default translation.
W: warning: string 'show_hidden_pref_on' has no default translation.
W: warning: string 'show_hidden_pref_title' has no default translation.
I: Copying libs... (/kotlin)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk into: ./dist/ch.deletescape.lawnchair.plah.apk

$ java -jar ~/Downloads/apktool_2.9.0.jar d ch.deletescape.lawnchair.plah.apk -f
I: Using Apktool 2.9.0 on ch.deletescape.lawnchair.plah.apk
I: Loading resource table...
I: Decoding file-resources...
I: Loading resource table from file: C:\Users\Michael\AppData\Local\apktool\framework\1.apk
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/notification_bg_low_pressed.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/notification_bg_normal_pressed.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/notification_bg_normal_pressed.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/notification_bg_normal.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/notification_bg_normal_pressed.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/notification_bg_low_normal.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/notification_bg_low_normal.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/notification_bg_low_normal.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/notification_bg_low_pressed.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/notification_bg_normal.9.png". Renaming it to *.png.
S: Could not decode file, replacing by FALSE value: raw/keep.xml
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/notification_bg_normal.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/notification_bg_low_pressed.9.png". Renaming it to *.png.
I: Decoding values */* XMLs...
I: Decoding AndroidManifest.xml with resources...
I: Regular manifest package...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...

$ java -jar ~/Downloads/apktool_2.9.0.jar b
I: Using Apktool 2.9.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: C:\Users\Michael\git\mate-commander\ch.deletescape.lawnchair.plah\.\res\values\raws.xml:3: error: invalid value for type 'raw'. Expected a reference.
W: C:\Users\Michael\git\mate-commander\ch.deletescape.lawnchair.plah\.\res\values\raws.xml: error: file failed to compile.
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Michael\AppData\Local\Temp\brut_util_Jar_175463778699945487344527534542173488235.tmp, compile, --dir, C:\Users\Michael\git\mate-commander\ch.deletescape.lawnchair.plah\.\res, --legacy, -o, C:\Users\Michael\git\mate-commander\ch.deletescape.lawnchair.plah\.\build\resources.zip]

$ java -jar ~/Downloads/apktool_2.9.0.jar b --use-aapt1
I: Using Apktool 2.9.0
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: warning: string 'show_hidden_pref_off' has no default translation.
W: warning: string 'show_hidden_pref_on' has no default translation.
W: warning: string 'show_hidden_pref_title' has no default translation.
I: Copying libs... (/kotlin)
I: Building apk file...
I: Copying unknown files/dir...
I: Built apk into: .\dist\ch.deletescape.lawnchair.plah.apk
```

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://f-droid.org/de/packages/ch.deletescape.lawnchair.plah/

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? YES.
3. If you are trying to install a modified apk, did you resign it? YES.
4. Are you using the latest apktool version? YES.

As you can observe from the above logs, the APK can be successfully unpacked and repackaged depending on the used apktool version and whether we use `aapt1` or `aapt2` or even which OS we use. I may have missed on some executions to reset the framework dir (`apktool empty-framework-dir --force`) and this may cause the issue? Moreover, the original APK seems to crash on an emulator, so it might be even an app issue.  I am just wondering whether `aapt1` can handle cases where `aapt2` fails?

**Comment by iBotPeaches** [comment]
aapt2 is more strict - yes. So that is a possibility.

Whether that difference is a bug or just a stricter build time validation remains to be known in this case.

**Comment by auermich93** [comment]
@iBotPeaches Another fault I noticed in combination with this app. I am using your tool (currently 2.8.1) as a library within my java application. The decoding routine looks as follows:

```
    public static File decodeAPK(File apkPath) {

        // set 3rd party library (apktool) logging to 'SEVERE'
        java.util.logging.Logger rootLogger = java.util.logging.Logger.getLogger("");
        rootLogger.setLevel(Level.SEVERE);
        for (Handler h : rootLogger.getHandlers()) {
            h.setLevel(Level.SEVERE);
        }

        final Config config = Config.getDefaultConfig();
        config.forceDelete = true; // overwrites existing dir: -f

        try {
            // do not decode dex classes to smali: -s
            config.setDecodeSources(Config.DECODE_SOURCES_NONE);

            File parentDir = apkPath.getParentFile();
            File outputDir = new File(parentDir, "decodedAPK");

            LOGGER.debug("Decoding Output Dir: " + outputDir);

            final ApkDecoder decoder = new ApkDecoder(config, apkPath);
            decoder.decode(outputDir);
            return outputDir;
        } catch (AndrolibException | IOException | DirectoryException e) {
            e.printStackTrace();
            LOGGER.error("Failed to decode APK file!");
            return null;
        }
    }
```
Although I get the following logs that the decoding essentially failed, it looks like the exception is swallowed within the `ApkDecoder#decode()` method as my application proceeds and does not jump into the catch block above:

```
Okt. 09, 2023 8:15:28 PM brut.androlib.res.decoder.ResFileDecoder decode
SEVERE: Could not decode file, replacing by FALSE value: raw/keep.xml
brut.androlib.exceptions.AndrolibException: brut.directory.PathNotExist: raw/keep.xml
	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:147)
	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:69)
	at brut.androlib.res.ResourcesDecoder.decodeResources(ResourcesDecoder.java:271)
	at brut.androlib.res.ResourcesDecoder.decodeResources(ResourcesDecoder.java:242)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:96)
	at utility.Utility.decodeAPK(Utility.java:236)
	at Test.main(Test.java:113)
Caused by: brut.directory.PathNotExist: raw/keep.xml
	at brut.directory.AbstractDirectory.getSubPath(AbstractDirectory.java:250)
	at brut.directory.AbstractDirectory.getFileInput(AbstractDirectory.java:101)
	at brut.directory.AbstractDirectory.getFileInput(AbstractDirectory.java:103)
	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:142)
	... 6 more
```

My application then reports the error when it invokes `apktool b` but that's a bit late. I would prefer `ApkDecoder` not to swallow the exception. Would you mind adapting that?

**Comment by Schoemiees666** [comment]
Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by iBotPeaches** [comment]
@auermich93 - We have to do that for that specific chunk of code. It remains so in case we decode a Samsung blob or proprietary asset we can fallback after the crash to a native raw copy, which as that point crashed.

That seems acceptable and intended in my eyes. Its just crashing in directory sub-project, which probably means it might not extend AndrolibException so misses your try-catch.

**Comment by auermich93** [comment]
I climbed through the stack trace and noticed that the `AndrolibException` is caught but not re-thrown in some internal method of the `ResFileDecoder` class. This prevents the decoding procedure from failing completely but as such gives me no information
that decoding had some severe troubles. I can see the use case for this.
