### ISSUE TITLE
Exception in thread "main" brut.androlib.AndrolibException

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#339]
Original [issue 228](https://code.google.com/p/android-apktool/issues/detail?id=228) created by iamnanduu on 2011-10-13T09:31:48.000Z:

> <b>What steps will reproduce the problem?</b>
> 1. For some apks, while I try to decompile using the command apktool d &lt;name of apk&quot;, I am getting this error.
> 2. I tried apktool on so many apks and success rate is around 60%. Is there any known limitation for apktool?
> <b>3.</b>

<b>What is the expected output? What do you see instead?</b>

Expected out is a folder with Manifest file, res folder and smali files. Now we get a blank folder with the following error message

apktool d a.apk 
Exception in thread &quot;main&quot; brut.androlib.AndrolibException: brut.directory.DirectoryException: java.util.zip.ZipException: error in opening zip file
    at brut.androlib.ApkDecoder.hasSources(ApkDecoder.java:158)
    at brut.androlib.ApkDecoder.decode(ApkDecoder.java:79)
    at brut.apktool.Main.cmdDecode(Main.java:120)
    at brut.apktool.Main.main(Main.java:57)
Caused by: brut.directory.DirectoryException: java.util.zip.ZipException: error in opening zip file
    at brut.directory.ZipRODirectory.&lt;init&gt;(ZipRODirectory.java:55)
    at brut.directory.ZipRODirectory.&lt;init&gt;(ZipRODirectory.java:38)
    at brut.androlib.res.util.ExtFile.getDirectory(ExtFile.java:55)
    at brut.androlib.ApkDecoder.hasSources(ApkDecoder.java:156)
    ... 3 more
Caused by: java.util.zip.ZipException: error in opening zip file
    at java.util.zip.ZipFile.open(Native Method)
    at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:127)
    at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:144)
    at brut.directory.ZipRODirectory.&lt;init&gt;(ZipRODirectory.java:53)
    ... 6 more

<b>What version of the product are you using? On what operating system?</b>

v1.4.2.269870b

<b>Please provide any additional information below.</b>

I am trying some of the apk's I downloaded from app store.

**Comment by samchuc** [comment]
hello I am trying to decompile latest Whatsapp  beta version with no sucess and this is the log:
============================================================


Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: java.util.zip.ZipException: error in opening zip file
	at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:272)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:96)
	at brut.apktool.Main.cmdDecode(Main.java:166)
	at brut.apktool.Main.main(Main.java:81)
Caused by: brut.directory.DirectoryException: java.util.zip.ZipException: error in opening zip file
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:55)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:38)
	at brut.androlib.res.util.ExtFile.getDirectory(ExtFile.java:55)
	at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:270)
	... 3 more
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:53)
	... 6 more

**Comment by sushantyelpale** [comment]
**I am trying to decompile APK following Error Occurs**
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: java.util.zip.ZipException: error in opening zip file
        at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:293)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:103)
        at brut.apktool.Main.cmdDecode(Main.java:160)
        at brut.apktool.Main.main(Main.java:72)
Caused by: brut.directory.DirectoryException: java.util.zip.ZipException: error in opening zip file
        at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:55)
        at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:38)
        at brut.directory.ExtFile.getDirectory(ExtFile.java:52)
        at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:291)
        ... 3 more
Caused by: java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:53)
        ... 6 more

**After that i tried to zipAllign these APK but issue is**
Unable to open 'Sample.apk' as zip archive.
