### ISSUE TITLE
[BUG] Some Android 14 QPR2 APKs not supported

### ISSUE THREAD

**Issue by evowizz** [iBotPeaches/Apktool#3428]
It looks like [Android 14 QPR2](https://developer.android.com/about/versions/14/release-notes) (released yesterday) changed the way APKs are compiled. Apktool is unable to decode the `resources.arsc` file. 2 different errors may be printed as shared under the Stacktrace section below.

### Information
1. **Apktool Version (`apktool -version`)** - 2.9.0 / also tested with a manually built snapshot based on 44416481
2. **Operating System (Mac, Linux, Windows)** - Mac
3. **APK From? (Playstore, ROM, Other)** - System app, pulled from device
4. **Java Version (`java --version`)** - java 17.0.8 2023-07-18 LTS

### Stacktrace

**First error:**
```
I: Using Apktool 2.9.0 on example.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.exceptions.AndrolibException: Could not decode arsc file
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:49)
	at brut.androlib.res.data.ResTable.loadResPackagesFromApk(ResTable.java:182)
	at brut.androlib.res.data.ResTable.loadMainPkg(ResTable.java:134)
	at brut.androlib.res.ResourcesDecoder.decodeResources(ResourcesDecoder.java:147)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:104)
	at brut.apktool.Main.cmdDecode(Main.java:217)
	at brut.apktool.Main.main(Main.java:92)
Caused by: java.io.IOException: Expected: 0x00000000, got: 0x00000002
	at brut.util.ExtDataInput.skipCheckByte(ExtDataInput.java:56)
	at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:469)
	at brut.androlib.res.decoder.ARSCDecoder.readComplexEntry(ARSCDecoder.java:440)
	at brut.androlib.res.decoder.ARSCDecoder.readEntryData(ARSCDecoder.java:375)
	at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:332)
	at brut.androlib.res.decoder.ARSCDecoder.readResourceTable(ARSCDecoder.java:95)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:44)
	... 6 more
```
> [!NOTE]
> The value `0x00000002` may be different depending on which APK is being decompiled. The APK causing this exact error is within the attached zip.

**Second error, less common:**
```
I: Using Apktool 2.9.0 on other_example.apk
I: Loading resource table...
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at brut.androlib.res.decoder.ARSCDecoder.readComplexEntry(ARSCDecoder.java:434)
	at brut.androlib.res.decoder.ARSCDecoder.readEntryData(ARSCDecoder.java:375)
	at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:332)
	at brut.androlib.res.decoder.ARSCDecoder.readResourceTable(ARSCDecoder.java:95)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:44)
	at brut.androlib.res.data.ResTable.loadResPackagesFromApk(ResTable.java:182)
	at brut.androlib.res.data.ResTable.loadMainPkg(ResTable.java:134)
	at brut.androlib.res.ResourcesDecoder.decodeResources(ResourcesDecoder.java:147)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:104)
	at brut.apktool.Main.cmdDecode(Main.java:217)
	at brut.apktool.Main.main(Main.java:92)
```
> [!IMPORTANT]
> This second error may also be caused by the first error. I got in on a specific APK from the QPR2 of a specific device, but the same APK on the QPR2 of another device didn't cause that second error, but the first error.

### Steps to Reproduce
1. `apktool d example.apk`

### Frameworks
The `framework-res.apk`file is attached in the zip file.

### APK
An `example.apk` file is attached in the zip file.

### Attachments:
[qpr2_bug.zip](https://github.com/iBotPeaches/Apktool/files/13375996/qpr2_bug.zip)

**Comment by iBotPeaches** [comment]
The heap size error is unrelated. Apps are just getting bigger and Apktool does some things inefficiently, we bumped to 1g here  https://github.com/iBotPeaches/Apktool/commit/8477d996dbc768d5df6aefd89fb61910188434cf

The first error is real and odd. Confirmed.

**Comment by evowizz** [comment]
Ah I see, thanks. Updating the script fixed what I called the "second error", my bad. Will edit the original comment to only mention the real issue.

**Comment by iBotPeaches** [comment]
Have some time this morning, not to really solve but to research.

```
➜  3428 java -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005 -jar /usr/local/bin/apktool.jar d example.apk -s -f -v
Listening for transport dt_socket at address: 5005
I: Using Apktool v2.9.0-17-44416481-SNAPSHOT on example.apk
I: Loading resource table...
F: Chunk #1 start=0x00000008 type=0x0002 chunkSize=0x00016f24
F: Chunk #2 start=0x00000014 type=0x0001 chunkSize=0x0000d9e8
F: Chunk #3 start=0x0000d9fc type=0x0200 chunkSize=0x00009530
F: Chunk #4 start=0x0000f638 type=0x0202 chunkSize=0x00000018
F: Chunk #5 start=0x0000f650 type=0x0201 chunkSize=0x00000068
F: Chunk #6 start=0x0000f6b8 type=0x0202 chunkSize=0x00000054
F: Chunk #7 start=0x0000f70c type=0x0201 chunkSize=0x00000290
```

We crash on chunk 7, so lets dump aapt2 inspection of it.

```
    [ResTable_type] chunkSize: 656 headerSize: 84 id: 0x02 name: attr flags: 0x02 entryCount: 17 entryStart: 120 config: 
      [ResTable_map_entry] id: 0x0000 name: alpha keyIndex: 2 size: 16 flags: 0x0001 count: 0x0001 parent: 0x00000000
        [Res_value] size: 8 dataType: 0x10 data: 0x00000020 (32)
         name:  name-id:16777216
      [ResTable_map_entry] id: 0x0001 name: font keyIndex: 3 size: 16 flags: 0x0001 count: 0x0001 parent: 0x00000000
        [Res_value] size: 8 dataType: 0x10 data: 0x00000001 (1)
         name:  name-id:16777216
      [ResTable_map_entry] id: 0x0002 name: fontProviderAuthority keyIndex: 4 size: 16 flags: 0x0001 count: 0x0001 parent: 0x00000000
        [Res_value] size: 8 dataType: 0x10 data: 0x00000002 (2)
         name:  name-id:16777216
      [ResTable_map_entry] id: 0x0003 name: fontProviderCerts keyIndex: 5 size: 16 flags: 0x0001 count: 0x0001 parent: 0x00000000
        [Res_value] size: 8 dataType: 0x10 data: 0x00000001 (1)
         name:  name-id:16777216
      [ResTable_map_entry] id: 0x0004 name: fontProviderFetchStrategy keyIndex: 6 size: 16 flags: 0x0001 count: 0x0003 parent: 0x00000000
        [Res_value] size: 8 dataType: 0x10 data: 0x00010000 (65536)
         name:  name-id:16777216
        [Res_value] size: 8 dataType: 0x10 data: 0x00000001 (1)
         name:  name-id:2131099694
        [Res_value] size: 8 dataType: 0x10 data: 0x00000000 (0)
         name:  name-id:2131099695
      [ResTable_map_entry] id: 0x0005 name: fontProviderFetchTimeout keyIndex: 7 size: 16 flags: 0x0001 count: 0x0002 parent: 0x00000000
        [Res_value] size: 8 dataType: 0x10 data: 0x00010004 (65540)
         name:  name-id:16777216
        [Res_value] size: 8 dataType: 0x10 data: 0xffffffff (-1)
         name:  name-id:2131099699
      [ResTable_map_entry] id: 0x0006 name: fontProviderPackage keyIndex: 8 size: 16 flags: 0x0001 count: 0x0001 parent: 0x00000000
        [Res_value] size: 8 dataType: 0x10 data: 0x00000002 (2)
         name:  name-id:16777216
      [ResTable_map_entry] id: 0x0007 name: fontProviderQuery keyIndex: 9 size: 16 flags: 0x0001 count: 0x0001 parent: 0x00000000
        [Res_value] size: 8 dataType: 0x10 data: 0x00000002 (2)
         name:  name-id:16777216
      [ResTable_map_entry] id: 0x0008 name: fontProviderSystemFontFamily keyIndex: 10 size: 16 flags: 0x0001 count: 0x0001 parent: 0x00000000
        [Res_value] size: 8 dataType: 0x10 data: 0x00000002 (2)
         name:  name-id:16777216
      [ResTable_map_entry] id: 0x0009 name: fontStyle keyIndex: 11 size: 16 flags: 0x0001 count: 0x0003 parent: 0x00000000
        [Res_value] size: 8 dataType: 0x10 data: 0x00010000 (65536)
         name:  name-id:16777216
        [Res_value] size: 8 dataType: 0x10 data: 0x00000001 (1)
         name:  name-id:2131099704
        [Res_value] size: 8 dataType: 0x10 data: 0x00000000 (0)
         name:  name-id:2131099707
      [ResTable_map_entry] id: 0x000a name: fontVariationSettings keyIndex: 12 size: 16 flags: 0x0001 count: 0x0001 parent: 0x00000000
        [Res_value] size: 8 dataType: 0x10 data: 0x00000002 (2)
         name:  name-id:16777216
      [ResTable_map_entry] id: 0x000b name: fontWeight keyIndex: 13 size: 16 flags: 0x0001 count: 0x0001 parent: 0x00000000
        [Res_value] size: 8 dataType: 0x10 data: 0x00000004 (4)
         name:  name-id:16777216
      [ResTable_map_entry] id: 0x000c name: lStar keyIndex: 14 size: 16 flags: 0x0001 count: 0x0001 parent: 0x00000000
        [Res_value] size: 8 dataType: 0x10 data: 0x00000020 (32)
         name:  name-id:16777216
      [ResTable_map_entry] id: 0x000d name: nestedScrollViewStyle keyIndex: 15 size: 16 flags: 0x0001 count: 0x0001 parent: 0x00000000
        [Res_value] size: 8 dataType: 0x10 data: 0x00000001 (1)
         name:  name-id:16777216
      [ResTable_map_entry] id: 0x000e name: queryPatterns keyIndex: 16 size: 16 flags: 0x0001 count: 0x0001 parent: 0x00000000
        [Res_value] size: 8 dataType: 0x10 data: 0x00000001 (1)
         name:  name-id:16777216
      [ResTable_map_entry] id: 0x000f name: shortcutMatchRequired keyIndex: 17 size: 16 flags: 0x0001 count: 0x0001 parent: 0x00000000
        [Res_value] size: 8 dataType: 0x10 data: 0x00000008 (8)
         name:  name-id:16777216
      [ResTable_map_entry] id: 0x0010 name: ttcIndex keyIndex: 18 size: 16 flags: 0x0001 count: 0x0001 parent: 0x00000000
        [Res_value] size: 8 dataType: 0x10 data: 0x00000004 (4)
         name:  name-id:16777216
```

Best I can tell is this sample is reporting as the set of resources are offset16, but in fact are not. You can see this by expanding my search to the surrounding chunks.

```
    [RES_TABLE_TYPE_SPEC_TYPE] chunkSize: 24 headerSize: 16
    [ResTable_type] chunkSize: 104 headerSize: 84 id: 0x01 name: anim flags: 0x02 entryCount: 2 entryStart: 88 config: 
      [ResTable_entry_compact] id: 0x0000 name: launch_dialog_enter keyIndex: 0 size: 8 flags: 0x0308
        [Res_value] size: 8 dataType: 0x03 data: 0x00000000 ((file) res/anim/launch_dialog_enter.xml type=XML)
      [ResTable_entry_compact] id: 0x0001 name: launch_dialog_exit keyIndex: 1 size: 8 flags: 0x0308
        [Res_value] size: 8 dataType: 0x03 data: 0x00000001 ((file) res/anim/launch_dialog_exit.xml type=XML)
    [RES_TABLE_TYPE_SPEC_TYPE] chunkSize: 84 headerSize: 16
    [ResTable_type] chunkSize: 656 headerSize: 84 id: 0x02 name: attr flags: 0x02 entryCount: 17 entryStart: 120 config: 
      [ResTable_map_entry] id: 0x0000 name: alpha keyIndex: 2 size: 16 flags: 0x0001 count: 0x0001 parent: 0x00000000
        [Res_value] size: 8 dataType: 0x10 data: 0x00000020 (32)
         name:  name-id:16777216
      [ResTable_map_entry] id: 0x0001 name: font keyIndex: 3 size: 16 flags: 0x0001 count: 0x0001 parent: 0x00000000
        [Res_value] size: 8 dataType: 0x10 data: 0x00000001 (1)
         name:  name-id:16777216
    [RES_TABLE_TYPE_SPEC_TYPE] chunkSize: 40 headerSize: 16
    [ResTable_type] chunkSize: 144 headerSize: 84 id: 0x03 name: color flags: 0x02 entryCount: 6 entryStart: 96 config: 
      [ResTable_entry_compact] id: 0x0000 name: androidx_core_ripple_material_light keyIndex: 19 size: 8 flags: 0x1c08
        [Res_value] size: 8 dataType: 0x1c data: 0x1f000000 (#1f000000)
      [ResTable_entry_compact] id: 0x0001 name: androidx_core_secondary_text_default_material_light keyIndex: 20 size: 8 flags: 0x1c08
        [Res_value] size: 8 dataType: 0x1c data: 0x8a000000 (#8a000000)
```

So as you can see the first chunk has flag 2 (offset16), as well as 2nd and 3rd. However, only the 1st and 3rd are actually packed. I've never seen this before - the chunk is lying on about its packing.

**Comment by iBotPeaches** [comment]
I see Beta 1.1 came out - https://developer.android.com/about/versions/14/release-notes#beta1.1

Interesting to note the changelog item

> Fixed an issue that sometimes caused some apps to be removed after a system update was installed and then prevented those apps from being installed again. In other cases, affected apps couldn't be installed on a device even if they hadn't been installed previously.

This seems like malformed applications to me, but want to check the latest beta to confirm.

**Comment by iBotPeaches** [comment]
Okay, I'll have to go slower and see if I misunderstood the spec for compact resources.

**Comment by iBotPeaches** [comment]
```
    [ResTable_type] chunkSize: 656 headerSize: 84 id: 0x02 name: attr flags: 0x02 entryCount: 17 entryStart: 120 config: 
      [ResTable_map_entry] id: 0x0000 name: alpha keyIndex: 2 size: 16 flags: 0x0001 count: 0x0001 parent: 0x00000000
        [Res_value] size: 8 dataType: 0x10 data: 0x00000020 (32)
         name:  name-id:16777216
```
Spent some time today. What I found is we are 2 bytes off prior to reading this `map_entry`.


Historically in Apktool, we've never relied on `entriesStart` of the spec as we've always read from one section to another and haven't had a reason to skip/random-read.

* start - 63236
* end - 63892
* size - 656
* entryStart - chunk start + 120

* actual location - 63354
* intended location - 63356

**Comment by iBotPeaches** [comment]
```
➜  3428 java -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005 -jar /usr/local/bin/apktool.jar d example.apk -s -f
I: Using Apktool v2.9.0-17-44416481-SNAPSHOT on example.apk
I: Loading resource table...
I: Decoding file-resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Decoding values */* XMLs...
I: Decoding AndroidManifest.xml with resources...
I: Regular manifest package...
I: Copying raw classes.dex file...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
➜  3428 
```

Not really happy w/ this patch attached, because I'm convinced I'm missing some form of alignment/padding, but I've looked over this for a solid bit - https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/libs/androidfw/include/androidfw/ResourceTypes.h;l=1476;bpv=0

Don't see anything wrong. So I'll hold this draft PR until source is out for QPR2 for some final inspections.

**Comment by evowizz** [comment]
Mmh, the last time `ResourcesTypes.h` was updated was in January. I don't think the sources for the QPR2 are live yet. I suppose once the sources will be released, it might be much easier to see what Google changed?

**Comment by evowizz** [comment]
I can confirm your PR does fix the issue. I built apktool based on your branch and used it to attempt to decompile various apks that previously failed. They were successfully decompiled.
