### ISSUE TITLE
[BUG] decompile crashes with InvalidPathException: Illegal char <:> in META-INF

### ISSUE THREAD

**Issue by stefan9999991** [iBotPeaches/Apktool#3455]
### Information
1. **Apktool Version 2.9.0** -
2. **Operating System Windows** -
3. **APK From? Installed from Playstore extracted with Lucky Patcher** -
4. **Java Version java 17.0.6 2023-01-17 LTS** -

### Stacktrace/Logcat

```
C:\Users\stefa.LAPTOP-61V22UAJ\Downloads\LSC.Smart.Connect.ver.1.1.5.build.16>apktool d base.apk -o out                 
I: Using Apktool 2.9.0 on base.apk                                                                                      
I: Loading resource table...                                                                                            
I: Decoding file-resources...                                                                                           
I: Loading resource table from file: C:\Users\stefa.LAPTOP-61V22UAJ\AppData\Local\apktool\framework\1.apk               
I: Decoding values */* XMLs...                                                                                          
I: Decoding AndroidManifest.xml with resources...                                                                       
I: Regular manifest package...                                                                                          
I: Baksmaling classes.dex...                                                                                            
I: Baksmaling classes10.dex...                                                                                          
I: Baksmaling classes11.dex...                                                                                          
I: Baksmaling classes12.dex...                                                                                          
I: Baksmaling classes13.dex...                                                                                          
I: Baksmaling classes14.dex...                                                                                          
I: Baksmaling classes15.dex...                                                                                          
I: Baksmaling classes2.dex...                                                                                           
I: Baksmaling classes3.dex...                                                                                           
I: Baksmaling classes4.dex...                                                                                           
I: Baksmaling classes5.dex...                                                                                           
I: Baksmaling classes6.dex...                                                                                           
I: Baksmaling classes7.dex...                                                                                           
I: Baksmaling classes8.dex...                                                                                           
I: Baksmaling classes9.dex...                                                                                           
I: Copying assets and libs...                                                                                           
I: Copying unknown files...                                                                                             
I: Copying original files...                                                                                            
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 55: out\original\META-INF\thing\mcHeader_com.thing.smart.v8:j2v8_thingMC.meta                                     
                                             at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)                                         
                                             at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
                                             at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)                                              
                                             at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
                                             at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)                                           
                                             at java.base/java.io.File.toPath(File.java:2387)
                                             at brut.directory.DirUtil.copyToDir(DirUtil.java:97)
                                             at brut.directory.DirUtil.copyToDir(DirUtil.java:72)
                                             at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:198)
                                             at brut.directory.DirUtil.copyToDir(DirUtil.java:88)
                                             at brut.directory.AbstractDirectory.copyToDir(AbstractDirectory.java:208)
                                             at brut.androlib.ApkDecoder.copyOriginalFiles(ApkDecoder.java:304)
                                             at brut.androlib.ApkDecoder.decode(ApkDecoder.java:166)
                                             at brut.apktool.Main.cmdDecode(Main.java:217)
                                             at brut.apktool.Main.main(Main.java:92)
```

### Steps to Reproduce
1. `apktool d base.apk -o out`

### APK
[playstore link to app](https://play.google.com/store/apps/details?id=com.lscsmartconnection.smart)
I then extracted the APKS file with lucky patcher, unzipped it, and used apktool on the base.apk.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? I believe so
2. If you are trying to install a modified apk, did you resign it? Does not apply
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
Hmm colon in filename is for sure causing some issues. Since colon was used to determine if file traversal was occurring.

**Comment by iBotPeaches** [comment]
Going to close for #1460.

In this situation the colon is not allowed per: https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions

So that is breaking the normalization check - I don't think we can encode values here, because it would setup an improper assumption to decode any value even if the encoded value was intentional.

So I believe our mapping table of unknown/known chars would have to be built.
