### ISSUE TITLE
[BUG] App breaks after recompiling apk

### ISSUE THREAD

**Issue by Yehh22** [iBotPeaches/Apktool#3526]
### Information
1. **Apktool Version (`apktool -version`)** 2.9.3
2. **Operating System (Mac, Linux, Windows)** Windows
3. **APK From? (Playstore, ROM, Other)** Other
4. **Java Version (`java --version`)** 21.0.2

### <del>Issue 1 (Signature check)
<del>Reproduce the following steps breaks the app behavior.
<del>1. `apktool d (apk)`
<del>2. `apktool b (apk)`
<del>3. sign

<del>It won't boot Android 7 VM after creating an instance, it throws an exception. I tried with `-s` flag but still get same error. It does not happen on untouched APK

![image](https://github.com/iBotPeaches/Apktool/assets/127546925/678cfafe-94c9-415c-9a5e-8b215b973757)

<del>Sadly the logs it generated is encrypted, so I recorded from logcat instead

<del>[logs.txt](https://github.com/iBotPeaches/Apktool/files/14350286/logs.txt)

### Issue 2
Same steps as above but with `-r` flag. Using it breaks obfuscated resource folder because extracting the files overwrites some files due to crappy Windows file system.

As you can see, the sizes of the "res" folder got reduced significantly

![image](https://github.com/iBotPeaches/Apktool/assets/127546925/5d1a531f-c90d-49e1-a243-6f357805cbdb)

Also, the icon on my app drawer changed to this instead a blue V

![image](https://github.com/iBotPeaches/Apktool/assets/127546925/067b348a-bd41-4677-9b90-2387566df098)

Logs:
```
02-20 18:00:16.700 W/PackageManager(29814): Failure retrieving xml 0x7f160001 in package com.vphonegaga.titan
02-20 18:00:16.700 W/PackageManager(29814): android.content.res.Resources$NotFoundException: File res/qv.xml from xml type xml resource ID #0x7f160001
02-20 18:00:16.700 W/PackageManager(29814): 	at android.content.res.ResourcesImpl.loadXmlResourceParser(ResourcesImpl.java:1277)
02-20 18:00:16.700 W/PackageManager(29814): 	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2426)
02-20 18:00:16.700 W/PackageManager(29814): 	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2402)
02-20 18:00:16.700 W/PackageManager(29814): 	at android.content.res.Resources.getXml(Resources.java:1303)
02-20 18:00:16.700 W/PackageManager(29814): 	at android.app.ApplicationPackageManager.getXml(ApplicationPackageManager.java:2032)
02-20 18:00:16.700 W/PackageManager(29814): 	at android.content.pm.PackageItemInfo.loadXmlMetaData(PackageItemInfo.java:397)
02-20 18:00:16.700 W/PackageManager(29814): 	at com.qq.e.comm.GDTFileProvider.b(Unknown Source:21)
02-20 18:00:16.700 W/PackageManager(29814): 	at com.qq.e.comm.GDTFileProvider.a(Unknown Source:13)
02-20 18:00:16.700 W/PackageManager(29814): 	at com.qq.e.comm.GDTFileProvider.attachInfo(Unknown Source:13)
02-20 18:00:16.700 W/PackageManager(29814): 	at android.app.ActivityThread.installProvider(ActivityThread.java:7330)
02-20 18:00:16.700 W/PackageManager(29814): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6871)
02-20 18:00:16.700 W/PackageManager(29814): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6782)
02-20 18:00:16.700 W/PackageManager(29814): 	at android.app.ActivityThread.access$1300(ActivityThread.java:250)
02-20 18:00:16.700 W/PackageManager(29814): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1962)
02-20 18:00:16.700 W/PackageManager(29814): 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-20 18:00:16.700 W/PackageManager(29814): 	at android.os.Looper.loop(Looper.java:250)
02-20 18:00:16.700 W/PackageManager(29814): 	at android.app.ActivityThread.main(ActivityThread.java:7755)
02-20 18:00:16.700 W/PackageManager(29814): 	at java.lang.reflect.Method.invoke(Native Method)
02-20 18:00:16.700 W/PackageManager(29814): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
02-20 18:00:16.700 W/PackageManager(29814): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
02-20 18:00:16.700 W/PackageManager(29814): Caused by: java.io.FileNotFoundException: res/qv.xml
02-20 18:00:16.700 W/PackageManager(29814): 	at android.content.res.AssetManager.nativeOpenXmlAsset(Native Method)
02-20 18:00:16.700 W/PackageManager(29814): 	at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:1092)
02-20 18:00:16.700 W/PackageManager(29814): 	at android.content.res.ResourcesImpl.loadXmlResourceParser(ResourcesImpl.java:1261)
02-20 18:00:16.700 W/PackageManager(29814): 	... 19 more
02-20 18:00:16.700 D/AndroidRuntime(29814): Shutting down VM
02-20 18:00:16.701 E/AndroidRuntime(29814): FATAL EXCEPTION: main
02-20 18:00:16.701 E/AndroidRuntime(29814): Process: com.vphonegaga.titan, PID: 29814
02-20 18:00:16.701 E/AndroidRuntime(29814): java.lang.RuntimeException: Unable to get provider com.qq.e.comm.GDTFileProvider: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
02-20 18:00:16.701 E/AndroidRuntime(29814): 	at android.app.ActivityThread.installProvider(ActivityThread.java:7335)
02-20 18:00:16.701 E/AndroidRuntime(29814): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6871)
02-20 18:00:16.701 E/AndroidRuntime(29814): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6782)
02-20 18:00:16.701 E/AndroidRuntime(29814): 	at android.app.ActivityThread.access$1300(ActivityThread.java:250)
02-20 18:00:16.701 E/AndroidRuntime(29814): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1962)
02-20 18:00:16.701 E/AndroidRuntime(29814): 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-20 18:00:16.701 E/AndroidRuntime(29814): 	at android.os.Looper.loop(Looper.java:250)
02-20 18:00:16.701 E/AndroidRuntime(29814): 	at android.app.ActivityThread.main(ActivityThread.java:7755)
02-20 18:00:16.701 E/AndroidRuntime(29814): 	at java.lang.reflect.Method.invoke(Native Method)
02-20 18:00:16.701 E/AndroidRuntime(29814): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
02-20 18:00:16.701 E/AndroidRuntime(29814): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
02-20 18:00:16.701 E/AndroidRuntime(29814): Caused by: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
02-20 18:00:16.701 E/AndroidRuntime(29814): 	at com.qq.e.comm.GDTFileProvider.b(:4)
02-20 18:00:16.701 E/AndroidRuntime(29814): 	at com.qq.e.comm.GDTFileProvider.a(Unknown Source:13)
02-20 18:00:16.701 E/AndroidRuntime(29814): 	at com.qq.e.comm.GDTFileProvider.attachInfo(Unknown Source:13)
02-20 18:00:16.701 E/AndroidRuntime(29814): 	at android.app.ActivityThread.installProvider(ActivityThread.java:7330)
02-20 18:00:16.701 E/AndroidRuntime(29814): 	... 10 more
02-20 18:00:16.702 W/ActivityTaskManager( 1724):   Force finishing activity com.vphonegaga.titan/.StartActivity
```

[logs2.txt](https://github.com/iBotPeaches/Apktool/files/14350303/logs2.txt)

### APK
https://gsxnj.cn/index

Clicking on Android 7 or Android 10 doesn't matter. you will get same apk

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes
2. If you are trying to install a modified apk, did you resign it? Yes
3. Are you using the latest apktool version? Yes

**Comment by iBotPeaches** [comment]
Looks quite close to your previous issue no? - https://github.com/iBotPeaches/Apktool/issues/3525

Just haven't had time yet for either.

**Comment by iBotPeaches** [comment]
Closing as the 2nd part is identical to #3525 which I just closed.
