### ISSUE TITLE
[BUG] Missing res-xml file after building

### ISSUE THREAD

**Issue by Android-Unknown** [iBotPeaches/Apktool#3532]
### Information
1. **Apktool Version (`apktool -version`)** - 2.7.0, 2.9.3
2. **Operating System (Mac, Linux, Windows)** - Windows
3. **APK From? (Playstore, ROM, Other)** - Other
4. **Java Version (`java --version`)** - 17.0.5

### Stacktrace/Logcat

```
java.lang.RuntimeException: Unable to get provider androidx.core.content.FileProvider: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:7251)
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6787)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6704)
                                                                                                    	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:223)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7664)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
                                                                                                    Caused by: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
```

### Steps to Reproduce
1. Original folder res/xml before decoding:
![изображение](https://github.com/iBotPeaches/Apktool/assets/132849640/28761d9a-3ec2-4000-af0d-3438676c3c9f)

2. `java -jar apktool_2.9.3.jar d -r app.apk`
3. `java -jar apktool_2.9.3.jar b app`
4. 
![изображение](https://github.com/iBotPeaches/Apktool/assets/132849640/63d4637c-7c21-42e4-b660-83b4f021b455)

Please, help me

**Comment by iBotPeaches** [comment]
Do you mind putting up a failing test case by editing a sample application with some of the files involved in this? Without an application that would help give me a base to start from.

**Comment by Android-Unknown** [comment]
@iBotPeaches for example this apk
https://dropmefiles.com/468105

**Comment by Android-Unknown** [comment]
@iBotPeaches any ideas?

**Comment by iBotPeaches** [comment]
Sorry, I didn't download the file in time and it expired. If you can re-upload.

**Comment by Android-Unknown** [comment]
@iBotPeaches https://dropmefiles.com/946541
