### ISSUE TITLE
decompiling APK that compiled using NP Manager APK , with error Found: NP_MANAGER3

### ISSUE THREAD

**Issue by bullghost** [iBotPeaches/Apktool#3543]
### Information
1. Apktool 2.9.3-
2. Linux 
3. APK From internet that compile with NP Manager APK
4. openjdk 11.0.16

### Stacktrace/Logcat

```
Include stacktrace here
I: Using Apktool 2.9.3 on mm.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.exceptions.AndrolibException: unsupported res type name for bags. Found: NP_MANAGER3
        at brut.androlib.res.data.value.ResValueFactory.bagFactory(ResValueFactory.java:102)
        at brut.androlib.res.decoder.ARSCDecoder.readComplexEntry(ARSCDecoder.java:462)
        at brut.androlib.res.decoder.ARSCDecoder.readEntryData(ARSCDecoder.java:383)
        at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:340)
        at brut.androlib.res.decoder.ARSCDecoder.readResourceTable(ARSCDecoder.java:96)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:44)
        at brut.androlib.res.data.ResTable.loadResPackagesFromApk(ResTable.java:182)
        at brut.androlib.res.data.ResTable.loadMainPkg(ResTable.java:134)
        at brut.androlib.res.ResourcesDecoder.decodeResources(ResourcesDecoder.java:147)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:104)
        at brut.apktool.Main.cmdDecode(Main.java:217)
        at brut.apktool.Main.main(Main.java:92)


### Steps to Reproduce
1. apktool d -f mm.apk -o ../output/

### Frameworks
no use



### Questions to ask before submission
i try decompile only

**Comment by iBotPeaches** [comment]
That isn't a valid type as far as I know. Seems like following the Facebook pattern of remapping types. Do you have the application to confirm this?

**Comment by Code-With-Reza** [comment]
no fix yet?

**Comment by iBotPeaches** [comment]
Sorry I never got the application to triage, so I don't see a fix coming. Closing.
