### ISSUE TITLE
[BUG] Dex 040 unsupported?

### ISSUE THREAD

**Issue by privacyguy123** [iBotPeaches/Apktool#3562]
### Information
1. **Apktool Version (`apktool -version`)** - 2.9.3
2. **Operating System (Mac, Linux, Windows)** - Ubuntu
3. **APK From? (Playstore, ROM, Other)** - Other
4. **Java Version (`java --version`)** - "1.8.0_401

```
I: Baksmaling classes.dex...
Exception in thread "main" com.android.tools.smali.dexlib2.util.DexUtil$UnsupportedFile: Dex version 040 is not supported
        at com.android.tools.smali.dexlib2.util.DexUtil.verifyDexHeader(DexUtil.java:96)
        at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile.getVersion(DexBackedDexFile.java:172)
        at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile.<init>(DexBackedDexFile.java:96)
        at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile.<init>(DexBackedDexFile.java:199)
        at com.android.tools.smali.dexlib2.dexbacked.ZipDexContainer$1.getDexFile(ZipDexContainer.java:180)
        at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:88)
        at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:36)
        at brut.androlib.ApkDecoder.decodeSourcesSmali(ApkDecoder.java:220)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:127)
        at brut.apktool.Main.cmdDecode(Main.java:217)
        at brut.apktool.Main.main(Main.java:92)
```

**Comment by privacyguy123** [comment]
Apologies for not looking a little harder!
