### ISSUE TITLE
[BUG] Resources$NotFoundException for drawable when decompile and build apk

### ISSUE THREAD

**Issue by mikebgrep** [iBotPeaches/Apktool#3569]
### Information
1. **Apktool Version (`apktool -version`)** - 2.6.1
2. **Operating System (Mac, Linux, Windows)** - Ubuntu 22.04
3. **APK From? (Playstore, ROM, Other)** - Pulled from the mobile device
4. **Java Version (`java --version`)** - 17.0.10

### Stacktrace/Logcat

```
FATAL EXCEPTION: main
                      Process: com.boozt, PID: 5265
                      a2.e: Error attempting to load resource: 
                       at ii0.t.C0(Unknown Source:314)
                       at ed0.k1.s(Unknown Source:226)
                       at zh0.a.G(Unknown Source:301)
                       at zh0.a.F(Unknown Source:61)
                       at lg.e.invoke(SourceFile:6)
                       at lg.e.invoke(SourceFile:1)
                       at w0.d.invoke(SourceFile:7)
                       at na0.e.j(Unknown Source:46)
                       at j0.a.invoke(SourceFile:80)
                       at j0.a.invoke(SourceFile:8)
                       at w0.d.invoke(SourceFile:7)
                       at com.bumptech.glide.d.h(Unknown Source:218)
                       at j0.oa.a(Unknown Source:77)
                       at j0.k.invoke(SourceFile:24)
                       at j0.k.invoke(SourceFile:3)
                       at w0.d.invoke(SourceFile:7)
                       at com.bumptech.glide.d.i(Unknown Source:153)
                       at na0.e.h(Unknown Source:805)
                       at w0.b.invoke(SourceFile:163)
                       at w0.b.invoke(SourceFile:13)
                       at w0.d.invoke(SourceFile:7)
                       at com.bumptech.glide.d.i(Unknown Source:153)
                       at ca0.a.k(Unknown Source:336)
                       at lg.e.invoke(SourceFile:9)
                       at lg.e.invoke(SourceFile:2)
                       at w0.d.invoke(SourceFile:7)
                       at androidx.compose.ui.platform.ComposeView.a(Unknown Source:24)
                   at s.g.invoke(SourceFile:229)
                   at s.g.invoke(SourceFile:85)
                   at w0.d.invoke(SourceFile:7)
                   at com.bumptech.glide.d.i(Unknown Source:153)
                   at x1.p1.a(Unknown Source:284)
                   at a0.h.invoke(SourceFile:318)
                   at a0.h.invoke(SourceFile:99)
                   at w0.d.invoke(SourceFile:7)
                   at com.bumptech.glide.d.i(Unknown Source:153)
                   at x1.x0.a(Unknown Source:473)
                   at x1.w3.invoke(SourceFile:5)
                   at x1.w3.invoke(SourceFile:1)
                   at w0.d.invoke(SourceFile:7)
                   at com.bumptech.glide.d.h(Unknown Source:218)
                   at x1.w3.invoke(SourceFile:22)
                   at x1.w3.invoke(SourceFile:2)
                   at w0.d.invoke(SourceFile:7)
                   at wj0.b.w(Unknown Source:14)
                   at o0.n.r(Unknown Source:111)
                   at o0.t.m(Unknown Source:41)
                   at o0.b2.a(Unknown Source:34)
                   at o0.t.n(Unknown Source:8)
                   at o0.t.b(Unknown Source:0)
                   at u.s.invoke(SourceFile:298)
                   at x1.x.setOnViewTreeOwnersAvailable(Unknown Source:6)
                   at x1.x3.b(Unknown Source:9)
                   at x1.x3.a(Unknown Source:18)
                   at androidx.lifecycle.p0.a(Unknown Source:22)
                   at androidx.lifecycle.q0.i(Unknown Source:320)
                   at androidx.lifecycle.q0.g(Unknown Source:34)
                   at androidx.lifecycle.q0.f(Unknown Source:14)
                   at androidx.fragment.app.y1.a(Unknown Source:2)
                   at androidx.fragment.app.f0.restoreViewState(Unknown Source:30)
                   at androidx.fragment.app.f0.performActivityCreated(Unknown Source:60)
                   at androidx.fragment.app.m1.a(Unknown Source:40)
                   at androidx.fragment.app.m1.k(Unknown Source:163)
                   at androidx.fragment.app.e1.P(Unknown Source:57)
                   at androidx.fragment.app.e1.t(Unknown Source:33)
                   at androidx.fragment.app.f0.performActivityCreated(Unknown Source:76)
                   at androidx.fragment.app.m1.a(Unknown Source:40)
                   at androidx.fragment.app.m1.k(Unknown Source:163)
                   at androidx.fragment.app.e1.z(Unknown Source:1145)
                   at androidx.fragment.app.e1.W(Unknown Source:81)
                   at androidx.fragment.app.e1.y(Unknown Source:31)
                   at androidx.fragment.app.a.j(Unknown Source:9)
                   at zf0.d.t0(Unknown Source:45)
                   at com.boozt.ui.BooztActivity.m0(Unknown Source:41)
                   at wl.b.c(Unknown Source:79)
                   at wl.b.invoke(Unknown Source:118)
                   at qq.i.d(Unknown Source:35)
                   at androidx.lifecycle.x0.b(Unknown Source:29)
                   at androidx.lifecycle.x0.c(Unknown Source:55)
                   at androidx.lifecycle.x0.j(Unknown Source:14)
                   at androidx.lifecycle.c1.j(Unknown Source:0)
                   at androidx.lifecycle.t0.run(Unknown Source:18)
                   at android.os.Handler.handleCallback(Handler.java:873)
                   at android.os.Handler.dispatchMessage(Handler.java:99)
                   at android.os.Looper.loop(Looper.java:216)
                   at android.app.ActivityThread.main(ActivityThread.java:7211)
                   at java.lang.reflect.Method.invoke(Native Method)
                   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
                  Caused by: android.content.res.Resources$NotFoundException: Drawable com.package:drawable/APKTOOL_DUMMY_3ed with resource ID #0x7f0803ed
                  Caused by: android.content.res.Resources$NotFoundException: File  from drawable resource ID #0x7f0803ed
```

### Steps to Reproduce
The error its comming form the base apk of a split apks.
I use `apktool b -d  file- -o file.apk --use-aapt2 ` to build the apk after was deasembled with `apktool d file.apk` 
When I install in on the mobile device I got the error In the stacktrace.
I try to fix it as I copy all the drawable files from the second file which is the split and paste the missing in the base apk drawable folder.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? - apktool b produce `brut.androlib.exceptions.AndrolibException`
5. If you are trying to install a modified apk, did you resign it? - yes it was resignit
6. Are you using the latest apktool version? - yes

I see that there a a similar issues and how can I fix this.

**Comment by mikebgrep** [comment]
I found the problem closing the issue.

**Comment by jr-k** [comment]
@mikebgrep maybe you can share ?
