### ISSUE TITLE
Error while unpacking an .apk

### ISSUE THREAD

**Issue by cyb3rgh05t** [iBotPeaches/Apktool#3583]
Hi,

i am trying to unpack an apk using Apk Editor Studio with apktool 2.9.3 an java build 1.8.0_411-b09 an i get an error:

```
I: Using Apktool 2.9.3 on StreamNet.apk
I: Loading resource table...
I: Decoding file-resources...
I: Loading resource table from file: C:\Users\User\AppData\Local\apk-editor-studio\frameworks\1.apk
I: Decoding values */* XMLs...
I: Decoding AndroidManifest.xml with resources...
Exception in thread "main" java.lang.IllegalArgumentException: expected namespace null and not 'http://schemas.android.com/apk/res/android'
	at org.xmlpull.renamed.MXSerializer.endTag(MXSerializer.java:697)
	at org.xmlpull.v1.wrapper.classic.XmlSerializerDelegate.endTag(XmlSerializerDelegate.java:124)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:215)
	at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:78)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:137)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:149)
	at brut.androlib.res.ResourcesDecoder.decodeManifest(ResourcesDecoder.java:91)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:112)
	at brut.apktool.Main.cmdDecode(Main.java:217)
	at brut.apktool.Main.main(Main.java:92)
```
is there a way how i can resolve this?

**Comment by iBotPeaches** [comment]
I don't think a workaround if thats what you are asking. You can fix it by providing an apk so we can investigate and/or fixing itself though as Apktool is open source :)

**Comment by cyb3rgh05t** [comment]
yes that would nice thanks. how do you want me to share my apk?

**Comment by iBotPeaches** [comment]
Thanks I replicate the issue.

**Comment by cyb3rgh05t** [comment]
thanks

**Comment by cyb3rgh05t** [comment]
any news on this?

**Comment by iBotPeaches** [comment]
```
➜  3583 apktool d 3583.apk -f
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
I: Using Apktool v2.9.2-40-6436e7c0-SNAPSHOT on 3583.apk with 8 thread(s).
I: Baksmaling classes.dex...
I: Baksmaling classes4.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes2.dex...
I: Loading resource table...
I: Decoding file-resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Decoding values */* XMLs...
I: Decoding AndroidManifest.xml with resources...
I: Regular manifest package...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
➜  3583 
```

Got a patch in-progress.
