### ISSUE TITLE
[BUG] Error parsing styled strings

### ISSUE THREAD

**Issue by JoshMiers-FS** [iBotPeaches/Apktool#3588]
### Information
1. **Apktool Version (`apktool -version`)** - 2.9.3
3. **Operating System (Mac, Linux, Windows)** - Mac
4. **APK From? (Playstore, ROM, Other)** - Other
5. **Java Version (`java --version`)** - Openjdk 17.0.9 2023-10-17 LTS

### Stacktrace/Logcat

```
I: Using Apktool 2.9.3 on app-debug.apk
I: Loading resource table...
Exception in thread "main" java.lang.IllegalArgumentException: Chunk [color:#00a652] is not a valid entry
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:218)
	at com.google.common.base.Splitter$MapSplitter.split(Splitter.java:525)
	at brut.androlib.res.decoder.StyledString$Span.getAttributes(StyledString.java:84)
	at brut.androlib.res.decoder.StyledString$Decoder.decodeIterate(StyledString.java:129)
	at brut.androlib.res.decoder.StyledString$Decoder.decode(StyledString.java:116)
	at brut.androlib.res.decoder.StyledString.toString(StyledString.java:48)
	at brut.androlib.res.decoder.StringBlock.getHTML(StringBlock.java:145)
	at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:482)
	at brut.androlib.res.decoder.ARSCDecoder.readEntryData(ARSCDecoder.java:385)
	at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:340)
	at brut.androlib.res.decoder.ARSCDecoder.readResourceTable(ARSCDecoder.java:96)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:44)
	at brut.androlib.res.data.ResTable.loadResPackagesFromApk(ResTable.java:182)
	at brut.androlib.res.data.ResTable.loadMainPkg(ResTable.java:134)
	at brut.androlib.res.ResourcesDecoder.decodeResources(ResourcesDecoder.java:147)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:104)
	at brut.apktool.Main.cmdDecode(Main.java:217)
	at brut.apktool.Main.main(Main.java:92)
```

### Steps to Reproduce
1. Add this to your strings.xml:
```
<string name="styled_string_single_values_0"><paragraph style="font–size:16px;">Paragraph</paragraph></string>
<string name="styled_string_single_values_1"><paragraph style="color:#00a652;">Paragraph</paragraph></string>
<string name="styled_string_double_values_0"><paragraph style="font–size:16px;color:#00a652;">Paragraph</paragraph></string>
<string name="styled_string_double_values_1"><paragraph style="color:#00a652;font–size:16px;">Paragraph</paragraph></string>
<string name="styled_string_double_values_2"><paragraph style="font–size:16px; color:#00a652;">Paragraph</paragraph></string>
<string name="styled_string_double_values_3"><paragraph style="color:#00a652; font–size:16px;">Paragraph</paragraph></string>
```
2. Run `apktool d styled-strings.apk`.

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
[styled-strings.apk.zip](https://github.com/iBotPeaches/Apktool/files/15190755/styled-strings.apk.zip)

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? Yes.
4. If you are trying to install a modified apk, did you resign it? N/A
5. Are you using the latest apktool version? Yes.

**Comment by iBotPeaches** [comment]
Thanks for the sample. Guess this new styled string handling is full of edge cases.

Possible duplicate: https://github.com/iBotPeaches/Apktool/issues/2890

**Comment by iBotPeaches** [comment]
Fixed in v3.0.0 - we added some similar test cases into tests here: https://github.com/iBotPeaches/Apktool/blob/main/brut.apktool/apktool-lib/src/test/resources/testapp/res/values-mcc001/strings.xml#L17-L19

**Comment by iBotPeaches** [comment]
Sorry forgot to revisit this. Indeed we fixed this in v3.

```
➜  test java -jar apktool_3.0.3.jar d styled-strings.apk 
I: Using Apktool 3.0.3 on styled-strings.apk with 8 threads
I: Loading resource table...
I: Baksmaling classes2.dex...
I: Baksmaling classes.dex...
I: Decoding value resources...
I: Loading resource table from file: /Users/ibotpeaches/Library/apktool/framework/1.apk
I: Decoding file resources...
I: Generating values XMLs...
I: Decoding AndroidManifest.xml with resources...
I: Copying original files...
I: Copying unknown files...
➜  test java -jar apktool_3.0.3.jar b styled-strings
I: Using Apktool 3.0.3 on styled-strings.apk with 8 threads
I: Smaling smali_classes2 folder into classes2.dex...
I: Smaling smali folder into classes.dex...
I: Building resources with aapt2...
I: Building apk file...
I: Importing unknown files...
I: Built apk into: styled-strings/dist/styled-strings.apk
➜  test 
```
