### ISSUE TITLE
[BUG] decompiled renamed cordova app crashing

### ISSUE THREAD

**Issue by Smig0l** [iBotPeaches/Apktool#3630]
### Information
1. **Apktool Version (`apktool -version`)** - 2.9.3
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - private APK from third party
4. **Java Version (`java --version`)** - `openjdk 17.0.10 2024-01-16
OpenJDK Runtime Environment (build 17.0.10+7-Ubuntu-122.04.1)
OpenJDK 64-Bit Server VM (build 17.0.10+7-Ubuntu-122.04.1, mixed mode, sharing)
`

### Stacktrace/Logcat

```
2024-06-26 09:09:27.863  2752-2850  EGL_emulation           com.studiovega.atlante               D  app_time_stats: avg=1728.90ms min=1728.90ms max=1728.90ms count=1
2024-06-26 09:09:27.980  2752-3529  InAppBrowser            com.studiovega.atlante               D  target = _blank
2024-06-26 09:09:27.980  2752-2752  InAppBrowser            com.studiovega.atlante               D  in blank
2024-06-26 09:09:28.005  2752-2752  diovega.atlante         com.studiovega.atlante               E  Invalid resource ID 0x00000000.
--------- beginning of crash
2024-06-26 09:09:28.005  2752-2752  AndroidRuntime          com.studiovega.atlante               D  Shutting down VM
2024-06-26 09:09:28.014  2752-2752  AndroidRuntime          com.studiovega.atlante               E  FATAL EXCEPTION: main
                                                                                                    Process: com.studiovega.atlante, PID: 2752
                                                                                                    android.content.res.Resources$NotFoundException: Resource ID #0x0
                                                                                                    	at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:243)
                                                                                                    	at android.content.res.Resources.getDrawableForDensity(Resources.java:993)
                                                                                                    	at android.content.res.Resources.getDrawable(Resources.java:933)
                                                                                                    	at android.content.res.Resources.getDrawable(Resources.java:908)
                                                                                                    	at org.apache.cordova.inappbrowser.InAppBrowser$6.run(InAppBrowser.java:637)
                                                                                                    	at android.app.Activity.runOnUiThread(Activity.java:7620)
                                                                                                    	at org.apache.cordova.inappbrowser.InAppBrowser.showWebPage(InAppBrowser.java:852)
                                                                                                    	at org.apache.cordova.inappbrowser.InAppBrowser$1.run(InAppBrowser.java:207)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
2024-06-26 09:09:28.262  2752-2752  Process                 com.studiovega.atlante               I  Sending signal. PID: 2752 SIG: 9

```

### Steps to Reproduce
1. decompiled, changed package name, rebuild, resigned.
2. everything seems ok..the app launches fine, but when clicking a tab where it should open a webview it crashes.

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
3. If you are trying to install a modified apk, did you resign it? yes
4. Are you using the latest apktool version? yes

**Comment by iBotPeaches** [comment]
This resource id looks bugged for sure: `Invalid resource ID 0x00000000`

Sadly though being honest - I can't investigate this without a sample. So I'll just close to not mislead you. I'd recommend reading some of these threads that look related to this specific webview crash regarding resId 0 - https://issuetracker.google.com/issues/77246450
