### ISSUE TITLE
[BUG] Exception while decompiling weird twrp apk??

### ISSUE THREAD

**Issue by endingisnight** [iBotPeaches/Apktool#3686]
### Information
1. **Apktool Version (`apktool -version`)** - v2.9.2-64-62ad27a5-SNAPSHOT
2. **Operating System (Mac, Linux, Windows)** - Linux
3. **APK From? (Playstore, ROM, Other)** - hell (see APK)
4. **Java Version (`java --version`)** - 
```
openjdk version "1.8.0_422"
OpenJDK Runtime Environment (build 1.8.0_422-b05)
OpenJDK 64-Bit Server VM (build 25.422-b05, mixed mode)
```

### Stacktrace/Logcat

```
Exception in thread "main" brut.androlib.exceptions.AndrolibException: unsupported res type name for bags. Found: c
        at brut.androlib.res.data.value.ResValueFactory.bagFactory(ResValueFactory.java:102)
        at brut.androlib.res.decoder.ARSCDecoder.readComplexEntry(ARSCDecoder.java:462)
        at brut.androlib.res.decoder.ARSCDecoder.readEntryData(ARSCDecoder.java:383)
        at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:340)
        at brut.androlib.res.decoder.ARSCDecoder.readResourceTable(ARSCDecoder.java:96)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:44)
        at brut.androlib.res.data.ResTable.loadResPackagesFromApk(ResTable.java:182)
        at brut.androlib.res.data.ResTable.loadMainPkg(ResTable.java:134)
        at brut.androlib.res.ResourcesDecoder.decodeResources(ResourcesDecoder.java:153)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:147)
        at brut.apktool.Main.cmdDecode(Main.java:220)
        at brut.apktool.Main.main(Main.java:92)
```

### Steps to Reproduce
`apktool decode --output 'out' 'GT.OTA.Helper_en.apk' `

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

Not sure if it is..

### APK
https://github.com/qiurigao/RMX2202/releases/download/1.1.0/GT.OTA.Helper_en.apk

### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything? n/a
2. If you are trying to install a modified apk, did you resign it? n/a
3. Are you using the latest apktool version? yup

**Comment by iBotPeaches** [comment]
```
Exception in thread "main" brut.androlib.exceptions.AndrolibException: unsupported res type name for bags. Found: c
```

Interesting - what type is "c"

**Comment by endingisnight** [comment]
> Interesting - what type is "c"

that's what I came here to figure out :)

**Comment by ProfessorLongBeard** [comment]
> > Interesting - what type is "c"
> 
> that's what I came here to figure out :)

Can't expect us to know everything LOL

**Comment by endingisnight** [comment]
Ah, it threw an exception so I thought it was a bug. Since this is out of the realm of apktool I'll close the issue.

**Comment by iBotPeaches** [comment]
I haven't reviewed this yet, could be bug.

**Comment by timplifier** [comment]
are there any updates on this issue ? been almost a year since it was reopened

**Comment by iBotPeaches** [comment]
> are there any updates on this issue ? been almost a year since it was reopened

I have not. I have some bugs from 10 years ago :)

**Comment by iBotPeaches** [comment]
```
➜  3686 apktool d GT.OTA.Helper_en.apk 
I: Using Apktool 3.0.1 on GT.OTA.Helper_en.apk with 8 threads
I: Loading resource table...
I: Baksmaling classes.dex...
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
W: Unsupported type for bags: c
I: Decoding value resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Decoding file resources...
I: Generating values XMLs...
I: Decoding AndroidManifest.xml with resources...
I: Copying original files...
I: Copying assets...
I: Copying unknown files...
➜  3686 
```

This was fixed in Apktool 3.0.0 during some of our type fixing. Sorry for delay.
