### ISSUE TITLE
[BUG] App raised a npe exception then crashed

### ISSUE THREAD

**Issue by AkkaXdXd** [iBotPeaches/Apktool#3715]
### Information
1. **Apktool Version (`apktool -version`)** - build from the master branch
2. **Operating System (Mac, Linux, Windows)** - windows
3. **APK From? (Playstore, ROM, Other)** - 
https://download-chromium.appspot.com/
4. **Java Version (`java --version`)** -
open jdk 18
### Stacktrace/Logcat

```
java.lang.NullPointerException: Attempt to read from field 'androidx.appcompat.widget.SearchView$SearchAutoComplete androidx.appcompat.widget.SearchView.z' on a null object reference in method 'void QB1.c(android.view.MenuItem, java.lang.String, androidx.fragment.app.FragmentActivity, PB1)'
    at QB1.c(chromium-ChromePublic.apk-default-681000000:6)
    at org.chromium.components.browser_ui.site_settings.SingleCategorySettings.d1(chromium-ChromePublic.apk-default-681000000:28)
    at ci0.j(chromium-ChromePublic.apk-default-681000000:51)
    at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(chromium-ChromePublic.apk-default-681000000:36)
    at Da.onCreatePanelMenu(chromium-ChromePublic.apk-default-681000000:10)
    at bc2.run(chromium-ChromePublic.apk-default-681000000:24)
    at android.os.Handler.handleCallback(Handler.java:958)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:224)
    at android.os.Looper.loop(Looper.java:318)
    at android.app.ActivityThread.main(ActivityThread.java:8759)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

### Steps to Reproduce
1. `apktool `
* decode
* modify apktool.yml 
* set renameManifestPackage for the pkg name
* replace string(package name) in smali and xml
* build
* install and run the app 
* goto to Setting -> Website Setting -> Desktop Website

### Frameworks
If this APK is from an OEM ROM (Samsung, HTC, LG). Please attach framework files
(`.apks` that live in `/system/framework` or `/system/priv-app`)

### APK
If this APK can be freely shared, please upload/attach a link to it.
https://commondatastorage.googleapis.com/chromium-browser-snapshots/Android/1376159/chrome-android.zip
### Questions to ask before submission
1. Have you tried `apktool d`, `apktool b` without changing anything?
yes
2. If you are trying to install a modified apk, did you resign it?
yes
3. Are you using the latest apktool version?
yes from master

**Comment by AkkaXdXd** [comment]
use -s with the same exception
use -r with the following error during the decoding:
[Fatal Error] :1:1: Invalid byte 1 of 1-byte UTF-8 sequence.

**Comment by AkkaXdXd** [comment]
may be caused by this
```java
    @Override
    protected <T extends View> T findViewTraversal(@IdRes int id) {
        if (id == mID) {
            return (T) this;
        }

        final View[] where = mChildren;
        final int len = mChildrenCount;

        for (int i = 0; i < len; i++) {
            View v = where[i];

            if ((v.mPrivateFlags & PFLAG_IS_ROOT_NAMESPACE) == 0) {
                v = v.findViewById(id);

                if (v != null) {
                    return (T) v;
                }
            }
        }

        return null;
    }
```

**Comment by AkkaXdXd** [comment]
https://stackoverflow.com/questions/17902308/null-pointer-exception-in-searchview

original file
```xml
<?xml version="1.0" encoding="utf-8"?>
<!--
Copyright 2015 The Chromium Authors
Use of this source code is governed by a BSD-style license that can be
found in the LICENSE file.
-->

<menu xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">
    <item android:id="@+id/search"
          android:title="@string/search"
          app:showAsAction="always"
          app:actionViewClass="androidx.appcompat.widget.SearchView" />
</menu>
```

decode file
```xml
<?xml version="1.0" encoding="utf-8"?>
<menu>
    <item n1:id="@id/search" n1:title="@string/search" actionViewClass="androidx.appcompat.widget.SearchView" showAsAction="always"
      xmlns:n1="http://schemas.android.com/apk/res/android" />
</menu>

```

may be caused by the missing namespace

**Comment by AkkaXdXd** [comment]
use this trick code to finally fix the exception
```java
if (value != null && value.startsWith("androidx") && name.endsWith("Class")) {
    ns = "http://schemas.android.com/apk/res-auto";
}
```
