### ISSUE TITLE
[BUG]apktool d failed java.lang.OutOfMemoryError using v2.10

### ISSUE THREAD

**Issue by avi112211** [iBotPeaches/Apktool#3736]
### Information
1. **Apktool Version: 2.10.0** -
2. **Operating System: Mac, Linux** -
3. **APK From? file** -
4. **Java Version: 17.0.12** -

### Stacktrace/Logcat

```
I: Using Apktool v2.10.0-2-c6bb75e5-SNAPSHOT on app.apk with 12 thread(s).
I: Baksmaling classes.dex...
I: Baksmaling classes34.dex...
I: Baksmaling classes40.dex...
I: Baksmaling classes12.dex...
I: Baksmaling classes25.dex...
I: Baksmaling classes11.dex...
I: Baksmaling classes13.dex...
I: Baksmaling classes9.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes5.dex...
I: Baksmaling classes43.dex...
I: Baksmaling classes37.dex...
I: Loading resource table...
I: Decoding file-resources...
I: Loading resource table from file: /Users/user/Library/apktool/framework/1.apk
[2.535s][warning][gc,alloc] pool-1-thread-12: Retried waiting for GCLocker too often allocating 1398466 words
I: Baksmaling classes36.dex...
[2.537s][warning][gc,alloc] pool-1-thread-9: Retried waiting for GCLocker too often allocating 1398466 words
I: Baksmaling classes28.dex...
[2.544s][warning][gc,alloc] pool-1-thread-6: Retried waiting for GCLocker too often allocating 1398466 words
I: Baksmaling classes26.dex...
[2.550s][warning][gc,alloc] pool-1-thread-1: Retried waiting for GCLocker too often allocating 2076432 words
I: Baksmaling classes31.dex...
[2.570s][warning][gc,alloc] pool-1-thread-2: Retried waiting for GCLocker too often allocating 1048578 words
I: Baksmaling classes17.dex...
[2.574s][warning][gc,alloc] pool-1-thread-11: Retried waiting for GCLocker too often allocating 1398466 words
I: Baksmaling classes10.dex...
[2.580s][warning][gc,alloc] pool-1-thread-3: Retried waiting for GCLocker too often allocating 1398466 words
I: Baksmaling classes35.dex...
[3.110s][warning][gc,alloc] pool-1-thread-5: Retried waiting for GCLocker too often allocating 1823816 words
I: Baksmaling classes27.dex...
[3.120s][warning][gc,alloc] pool-1-thread-8: Retried waiting for GCLocker too often allocating 1823816 words
I: Baksmaling classes15.dex...
[3.124s][warning][gc,alloc] pool-1-thread-7: Retried waiting for GCLocker too often allocating 1823816 words
I: Baksmaling classes3.dex...
[3.246s][warning][gc,alloc] pool-1-thread-4: Retried waiting for GCLocker too often allocating 1823816 words
I: Baksmaling classes7.dex...
I: Baksmaling classes14.dex...
[4.863s][warning][gc,alloc] pool-1-thread-9: Retried waiting for GCLocker too often allocating 2076432 words
I: Baksmaling classes42.dex...
[4.882s][warning][gc,alloc] pool-1-thread-3: Retried waiting for GCLocker too often allocating 2076432 words
I: Baksmaling classes4.dex...
[4.888s][warning][gc,alloc] pool-1-thread-6: Retried waiting for GCLocker too often allocating 2076432 words
I: Baksmaling classes38.dex...
I: Baksmaling classes16.dex...
[5.857s][warning][gc,alloc] pool-1-thread-5: Retried waiting for GCLocker too often allocating 2076432 words
I: Baksmaling classes29.dex...
[5.934s][warning][gc,alloc] pool-1-thread-8: Retried waiting for GCLocker too often allocating 2076432 words
I: Baksmaling classes32.dex...
[5.954s][warning][gc,alloc] pool-1-thread-4: Retried waiting for GCLocker too often allocating 2076432 words
I: Baksmaling classes6.dex...
I: Baksmaling classes8.dex...
I: Baksmaling classes33.dex...
[7.639s][warning][gc,alloc] pool-1-thread-9: Retried waiting for GCLocker too often allocating 2076432 words
I: Baksmaling classes44.dex...
I: Decoding values */* XMLs...
I: Decoding AndroidManifest.xml with resources...
I: Regular manifest package...
I: Copying assets and libs...
[8.280s][warning][gc,alloc] pool-1-thread-10: Retried waiting for GCLocker too often allocating 1924003 words
I: Baksmaling classes18.dex...
[8.370s][warning][gc,alloc] pool-1-thread-6: Retried waiting for GCLocker too often allocating 1823816 words
I: Baksmaling classes30.dex...
[8.449s][warning][gc,alloc] pool-1-thread-8: Retried waiting for GCLocker too often allocating 1048578 words
I: Baksmaling classes24.dex...
[8.473s][warning][gc,alloc] pool-1-thread-11: Retried waiting for GCLocker too often allocating 517967 words
[8.474s][warning][gc,alloc] pool-1-thread-4: Retried waiting for GCLocker too often allocating 657635 words
I: Baksmaling classes41.dex...
I: Baksmaling classes39.dex...
[8.545s][warning][gc,alloc] pool-1-thread-5: Retried waiting for GCLocker too often allocating 1048578 words
I: Baksmaling classes19.dex...
I: Baksmaling classes23.dex...
I: Baksmaling classes20.dex...
I: Baksmaling classes22.dex...
I: Baksmaling classes21.dex...
[10.726s][warning][gc,alloc] pool-1-thread-4: Retried waiting for GCLocker too often allocating 1414855 words
[10.784s][warning][gc,alloc] pool-1-thread-8: Retried waiting for GCLocker too often allocating 2076432 words
[10.806s][warning][gc,alloc] pool-1-thread-6: Retried waiting for GCLocker too often allocating 2076432 words
[10.822s][warning][gc,alloc] pool-1-thread-11: Retried waiting for GCLocker too often allocating 1048578 words
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
	at brut.androlib.BackgroundWorker.waitForFinish(BackgroundWorker.java:38)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:167)
	at brut.apktool.Main.cmdDecode(Main.java:220)
	at brut.apktool.Main.main(Main.java:92)
Caused by: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at brut.androlib.BackgroundWorker.waitForFinish(BackgroundWorker.java:36)
	... 3 more
Caused by: java.lang.OutOfMemoryError: Java heap space
```

### Steps to Reproduce
1. `apktool d app.apk`
2. the issue occurs when using large apps with many dex files.
3. I've already extended the java heap size to 2GB

### APK
Sorry can't share it

The issue started when using apktool v2.10.
The issue occurs only with large apps (250MB +) with many dex files.
I can continue increase the Java heap size, but 2GB is already large.
I saw a new print 'with 12 thread(s)' that maybe connected. I didn't find a param that can control it.

Thanks,
Avi

**Comment by avi112211** [comment]
found in the advanced option '-j' attribute to control the number of threads, changing it to 4 solved the issue.
I'll close the ticket, although I'm not sure that using so much threads by default is the right choice

**Comment by iBotPeaches** [comment]
* It was missed in documentation so covered here - https://github.com/iBotPeaches/Apktool/commit/41141513a6619f9fecb6e8ccfc52445034270acf
* It just assumes number of threads, but I see that has problem on high core computers, so I set default max to 8 - https://github.com/iBotPeaches/Apktool/commit/858c07143d3f7e0f8155e2540171bddbf4e3d16f

**Comment by ddxv** [comment]
I can't tell if I'm getting the same issue. After reading the above, I tried using `-j 2` and `-j 8` both lead to the same error. 

apktool command:
```sh
apktool decode /path/to/com.lemon.lvoverseas.apk -j 2 -f -o /output/dir/"
 ```

output
```sh
I: Using Apktool 2.10.0 on com.lemon.lvoverseas.apk with 2 thread(s).
I: Baksmaling classes.dex...
I: Baksmaling classes10.dex...
...
I: Copying original files...
I: Copying META-INF/services directory
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
        at brut.androlib.ApkDecoder.decode(SourceFile:0)
        at brut.apktool.Main.main(SourceFile:0)
Caused by: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        ... 2 more
Caused by: java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.Arrays.copyOf(Arrays.java:3541)
        at com.android.tools.smali.util.InputStreamUtil.toByteArray(SourceFile:0)
        at com.android.tools.smali.dexlib2.dexbacked.ZipDexContainer.getEntries(SourceFile:0)
        at com.android.tools.smali.dexlib2.dexbacked.ZipDexContainer.getDexEntryNames(SourceFile)
        at brut.androlib.src.SmaliDecoder.decode(SourceFile:0)
        at brut.androlib.ApkDecoder.decodeSourcesSmali(SourceFile:0)
        at brut.androlib.ApkDecoder.lambda$scheduleDecodeSourcesSmali$0(SourceFile)
        at brut.androlib.ApkDecoder$$Lambda/0x00007f0e00008000.run(Unknown Source)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.runWith(Thread.java:1596)
        at java.base/java.lang.Thread.run(Thread.java:1583)
        ```
        
 Was this the same memory / thread issue or should I open a new Issue?

**Comment by ddxv** [comment]
Ah, I realized I was mistakenly **not trying single thread**, not sure why I was trying `2` as my smallest, but tried again with `-j 1` and **this works**.

@iBotPeaches just curious, do you know why is this? I was getting this error on two multi-threaded consumer machines, one Intel and one AMD. this doesn't seem to usually happen with apktool, only with some apks. For now I'll just try first with the default then retry with single threaded for those that hit this issue.

**Comment by steadfasterX** [comment]
this solved my oom as well (using `-j1`)

**Comment by ddxv** [comment]
> Worked with `-j 1`, but can't we have a multi thread solution? or being able to set heap size (or make some profiling to know what is going on the heap?)

@brenoepics I first try without `-j 1` then fall back to trying with `-j 1` which seems to work well. That way it first tries multi-threaded right?

**Comment by brenoepics** [comment]
> > Worked with `-j 1`, but can't we have a multi thread solution? or being able to set heap size (or make some profiling to know what is going on the heap?)
> 
> [@brenoepics](https://github.com/brenoepics) I first try without `-j 1` then fall back to trying with `-j 1` which seems to work well. That way it first tries multi-threaded right?

Yeah, without `-j 1`, it will auto-detect and run as many threads as possible, up to 8. With `-j 1`, it will be single-threaded. My guess is that something is being duplicated per thread when running multithreaded, causing the heap to run out of memory. I need to investigate further. Once I have some free time, I'll check this and see if I can open a PR, but this issue is definitely still present.

**Comment by han023** [comment]
sudo java -Xmx4G -jar apktool_2.11.1.jar  d test.apk

**Comment by suprohub** [comment]
> > > Worked with `-j 1`, but can't we have a multi thread solution? or being able to set heap size (or make some profiling to know what is going on the heap?)
> > 
> > 
> > [@brenoepics](https://github.com/brenoepics) I first try without `-j 1` then fall back to trying with `-j 1` which seems to work well. That way it first tries multi-threaded right?
> 
> Yeah, without `-j 1`, it will auto-detect and run as many threads as possible, up to 8. With `-j 1`, it will be single-threaded. My guess is that something is being duplicated per thread when running multithreaded, causing the heap to run out of memory. I need to investigate further. Once I have some free time, I'll check this and see if I can open a PR, but this issue is definitely still present.

Do you fixed it?

**Comment by brenoepics** [comment]
The easiest fix would be to just increase the memory limits here:
[https://github.com/iBotPeaches/Apktool/blob/master/scripts/linux/apktool#L61](https://github.com/iBotPeaches/Apktool/blob/master/scripts/linux/apktool#L61)

But if you're running into the same issue I am (during the build), multithreading wouldn't help that much right now.

Here’s why:

The core build logic is still synchronous. For example, this part:
[https://github.com/iBotPeaches/Apktool/blob/404f78d843a802f745e2e032e96dfc212e7e955c/brut.j.dir/src/main/java/brut/directory/ZipUtils.java#L63-L74](https://github.com/iBotPeaches/Apktool/blob/404f78d843a802f745e2e032e96dfc212e7e955c/brut.j.dir/src/main/java/brut/directory/ZipUtils.java#L63-L74)
will call `zipFile` which uses `BufferedInputStream`, and will block the thread (build step does not uses background workers at all since it is sync anyways)

And then here:
[https://github.com/iBotPeaches/Apktool/blob/404f78d843a802f745e2e032e96dfc212e7e955c/brut.j.dir/src/main/java/brut/directory/ZipUtils.java#L82-L117](https://github.com/iBotPeaches/Apktool/blob/404f78d843a802f745e2e032e96dfc212e7e955c/brut.j.dir/src/main/java/brut/directory/ZipUtils.java#L82-L117)
the actual write also happens in a blocking way.

If you look at how `buildApkFile` is used:
[https://github.com/iBotPeaches/Apktool/blob/404f78d843a802f745e2e032e96dfc212e7e955c/brut.apktool/apktool-lib/src/main/java/brut/androlib/ApkBuilder.java#L414-L451](https://github.com/iBotPeaches/Apktool/blob/404f78d843a802f745e2e032e96dfc212e7e955c/brut.apktool/apktool-lib/src/main/java/brut/androlib/ApkBuilder.java#L414-L451)
you'll see it's not running on any background worker.

So if we make file reading faster with multiple threads, everything just piles up in memory since the build still runs on a single thread. That actually makes it easier to hit memory limits.
