### ISSUE TITLE
org.yaml.snakeyaml.error.YAMLException: cause by java.nio.charset.MalformedInputException: Input length = 1

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#509]
Original [issue 398](https://code.google.com/p/android-apktool/issues/detail?id=398) created by zhanyingwu12 on 2013-01-22T02:28:47.000Z:

> <b>What steps will reproduce the problem?</b>
> 1.apktool d -f _**.apk
> 2.apktool b *_*(full path)

Exception in thread &quot;main&quot; org.yaml.snakeyaml.error.YAMLException: java.nio.char
set.MalformedInputException: Input length = 1
        at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:200)
        at org.yaml.snakeyaml.reader.StreamReader.&lt;init&gt;(StreamReader.java:60)
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:412)
        at brut.androlib.Androlib.readMetaFile(Androlib.java:162)
        at brut.androlib.Androlib.build(Androlib.java:183)
        at brut.androlib.Androlib.build(Androlib.java:176)
        at brut.apktool.Main.cmdBuild(Main.java:218)
        at brut.apktool.Main.main(Main.java:74)
Caused by: java.nio.charset.MalformedInputException: Input length = 1
        at java.nio.charset.CoderResult.throwException(CoderResult.java:260)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:319)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:158)
        at java.io.InputStreamReader.read(InputStreamReader.java:167)
        at org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:123)
        at java.io.Reader.read(Reader.java:123)
        at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:184)
        ... 7 more

apktool1.5.1 on Win7, jdk6

The apk I reverse is 老黄历_1.1.2.apk.

**Comment by Dingu12345678990** [comment]
Hello,

When I am uploading my yaml file in APIConnect, I am getting the following error. Could you please suggest me what should be done for this.

java.nio.charset.MalformedInputException: Input length = 1

Thanks in advance.

**Comment by iBotPeaches** [comment]
@Dingu12345678990 Was apktool involved in this? I'm confused.

**Comment by Dingu12345678990** [comment]
apktool  is not involved in this. If you have any knowledge on this, please share with me
