### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#513]
Original [issue 402](https://code.google.com/p/android-apktool/issues/detail?id=402) created by jbruchanov on 2013-01-30T00:59:30.000Z:

> <b>What steps will reproduce the problem?</b>
> 1. apktool.bat d ....apk dir
> <b>2.</b>
> <b>3.</b>

<b>What version of the product are you using? On what operating system?</b>
Apktool v1.5.1

---

I: Baksmaling...
I: Loading resource table...
I: Loaded.
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\aaa\apktool\framework\1.apk
I: Loaded.
W: Could not decode attr value, using undecoded value instead: ns=android, name=hardwareAccelerated, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=previewImage, value=0x7f02008c
I: Regular manifest package...
I: Decoding file-resources...
W: Could not decode attr value, using undecoded value instead: ns=android, name=showAsAction, value=0x00000005
W: Could not decode attr value, using undecoded value instead: ns=android, name=fontFamily, value=0x00000028
Exception in thread &quot;main&quot; java.lang.NullPointerException
        at java.io.Writer.write(Unknown Source)
        at brut.androlib.res.util.ExtMXSerializer.writeAttributeValue(ExtMXSerializer.java:38)
        at org.xmlpull.mxp1_serializer.MXSerializer.attribute(MXSerializer.java:673)
        at org.xmlpull.v1.wrapper.classic.XmlSerializerDelegate.attribute(XmlSerializerDelegate.java:106)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
        at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:80)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:130)
        at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(ResStreamDecoderContainer.java:34)
        at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:102)
        at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:86)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:236)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:115)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:99)
        at brut.apktool.Main.cmdDecode(Main.java:141)
        at brut.apktool.Main.main(Main.java:72)

**Comment by amir1111** [comment]
maybe it's not fixed? found it still in this apk : http://www.filedropper.com/commojimjweather53202

**Comment by amir1111** [comment]
also this is the message i'm getting for the apk i uploaded:
================================================
W: Could not decode attr value, using undecoded value instead: ns=android, name=
qihoo, value=0x00000049
Exception in thread "main" java.lang.NullPointerException
        at java.io.Writer.write(Unknown Source)
        at brut.androlib.res.util.ExtMXSerializer.writeAttributeValue(ExtMXSeria
lizer.java:38)
        at org.xmlpull.mxp1_serializer.MXSerializer.attribute(MXSerializer.java:
673)
        at org.xmlpull.v1.wrapper.classic.XmlSerializerDelegate.attribute(XmlSer
ializerDelegate.java:106)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartT
ag(StaticXmlSerializerWrapper.java:267)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(Stati
cXmlSerializerWrapper.java:211)
        at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamD
ecoder.java:83)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDe
coder.java:141)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPull
StreamDecoder.java:153)
        at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecode
r.java:134)
        at brut.androlib.res.AndrolibResources.decodeManifestWithResources(Andro
libResources.java:199)
        at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:139)

        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
        at brut.apktool.Main.cmdDecode(Main.java:165)
        at brut.apktool.Main.main(Main.java:81)

**Comment by iBotPeaches** [comment]
```
ibotpeaches@raganok:~/Downloads/Apktool/Bug513$ apktool d com.moji.mjweather_53202.apk 
I: Using Apktool 2.0.1-1fb87e-SNAPSHOT on com.moji.mjweather_53202.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
ibotpeaches@raganok:~/Downloads/Apktool/Bug513$
```

Not a bug @amir1111 and since this is an old bug, I'm locking the conversation. You may open a new bug if you find a problem.
