### ISSUE TITLE
Exception in thread "main" brut.androlib.AndrolibException: Multiple resources: spec=0x7f090000 id/CompanyLogOnView, config=-en

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#517]
Original [issue 406](https://code.google.com/p/android-apktool/issues/detail?id=406) created by andreas.laendle on 2013-02-07T11:53:04.000Z:

<b>What steps will reproduce the problem?</b>
1. Just run the apktool (latest v1.5.2) against the attached APK with d[ecode]

<b>What version of the product are you using? On what operating system?</b>
Win7 / 64bit / english / apktool 1.5.2 / java 1.7.13

I need to compress the attached APK in order to not violate the 10 MB attachment limit.

**Comment by eezym** [comment]
Hi, I'm new to using apktool. Crrently, I'm using apktool v2.0.0 RC3 and am able to decompile apk files. After decompiling, I tried to re-compile the application (without changing anything at all) and I get the following error:
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec: [/tmp/brut_util_Jar_347526442271975146.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 23, --version-code, 26, --version-name, 3.5, -F, /tmp/APKTOOL947503537991695626.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /usr/share/apktool/makeup/res, -M, /usr/share/apktool/makeup/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:473)
	at brut.androlib.Androlib.buildResources(Androlib.java:407)
	at brut.androlib.Androlib.build(Androlib.java:306)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec: [/tmp/brut_util_Jar_347526442271975146.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 23, --version-code, 26, --version-name, 3.5, -F, /tmp/APKTOOL947503537991695626.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /usr/share/apktool/makeup/res, -M, /usr/share/apktool/makeup/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:439)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:459)
	... 5 more
Caused by: brut.common.BrutException: could not exec: [/tmp/brut_util_Jar_347526442271975146.tmp, p, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 23, --version-code, 26, --version-name, 3.5, -F, /tmp/APKTOOL947503537991695626.tmp, -0, arsc, -0, arsc, -I, /root/.local/share/apktool/framework/1.apk, -S, /usr/share/apktool/makeup/res, -M, /usr/share/apktool/makeup/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:97)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:433)
	... 6 more
Caused by: java.io.IOException: Cannot run program "/tmp/brut_util_Jar_347526442271975146.tmp": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
	at brut.util.OS.exec(OS.java:90)
	... 7 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:187)
	at java.lang.ProcessImpl.start(ProcessImpl.java:130)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
	... 8 more

I tried doing it on both, Windows and Linux, but no luck.
Any help will be highly appreciated. Thanks in Advance...

**Comment by iBotPeaches** [comment]
Closing this. I unfortunately don't have the APK and the report is almost 5 years old. I failed in this instance.
