### ISSUE TITLE
Failure to decompile  ending with code_item @0x28c34

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#532]
Original [issue 421](https://code.google.com/p/android-apktool/issues/detail?id=421) created by raziel23x on 2013-02-28T20:49:21.000Z:

> <b>What steps will reproduce the problem?</b>
> 1. doing normal steps
> 2. java -Xmx1024m -jar apktool.jar d ../place-apk-here-for-modding/Problemfile.apk ../projects/Problemfile
> <b>3.</b>

<b>What is the expected output? What do you see instead?</b>
the apk file to decompile 

<b>What version of the product are you using? On what operating system?</b>
latest build and also latest github build same results

<b>Please provide any additional information below.</b>

D:\apkmultitool\other&gt;java -Xmx1024m -jar apktool.jar d ../place-apk-here-for-modding/Problemfile.apk ../projects/Problemfile
I: Baksmaling...
Exception in thread &quot;main&quot; org.jf.dexlib.Util.ExceptionWithContext: Index: 27491, Size: 4776
        at org.jf.dexlib.Util.ExceptionWithContext.withContext(ExceptionWithContext.java:54)
        at org.jf.dexlib.IndexedSection.getItemByIndex(IndexedSection.java:77)
        at org.jf.dexlib.Code.InstructionWithReference.lookupReferencedItem(InstructionWithReference.java:79)
        at org.jf.dexlib.Code.InstructionWithReference.&lt;init&gt;(InstructionWithReference.java:57)
        at org.jf.dexlib.Code.Format.Instruction21c.&lt;init&gt;(Instruction21c.java:63)
        at org.jf.dexlib.Code.Format.Instruction21c.&lt;init&gt;(Instruction21c.java:40)
        at org.jf.dexlib.Code.Format.Instruction21c$Factory.makeInstruction(Instruction21c.java:112)
        at org.jf.dexlib.Code.InstructionIterator.IterateInstructions(InstructionIterator.java:82)
        at org.jf.dexlib.CodeItem.readItem(CodeItem.java:154)
        at org.jf.dexlib.Item.readFrom(Item.java:77)
        at org.jf.dexlib.OffsettedSection.readItems(OffsettedSection.java:48)
        at org.jf.dexlib.Section.readFrom(Section.java:143)
        at org.jf.dexlib.DexFile.&lt;init&gt;(DexFile.java:431)
        at org.jf.dexlib.DexFile.&lt;init&gt;(DexFile.java:267)
        at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:45)
        at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:32)
        at brut.androlib.Androlib.decodeSourcesSmali(Androlib.java:72)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:89)
        at brut.apktool.Main.cmdDecode(Main.java:146)
        at brut.apktool.Main.main(Main.java:77)
Caused by: java.lang.IndexOutOfBoundsException: Index: 27491, Size: 4776
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at org.jf.dexlib.IndexedSection.getItemByIndex(IndexedSection.java:75)
        ... 18 more
Error occured while retrieving the field_id_item item at index 27491
Error occured at code address 12
code_item @0x28c34

**Comment by goel-sunny** [comment]
UNEXPECTED TOP-LEVEL EXCEPTION:
org.jf.dexlib.Util.ExceptionWithContext
       at org.jf.dexlib.Util.ExceptionWithContext.withContext(ExceptionWithContext.java:54)
       at org.jf.dexlib.Item.addExceptionContext(Item.java:177)
       at org.jf.dexlib.Item.readFrom(Item.java:79)
       at org.jf.dexlib.IndexedSection.readItems(IndexedSection.java:50)
       at org.jf.dexlib.Section.readFrom(Section.java:143)
       at org.jf.dexlib.DexFile.<init>(DexFile.java:431)
       at org.jf.baksmali.main.main(main.java:269)
caused by: java.lang.IllegalStateException
       at org.jf.baksmali.Adaptors.Format.InstructionMethodItemFactory.checkState    (InstructionMethodItemFactory.java:124)
       at org.jf.dexlib.ClassDataItem.setParent(ClassDataItem.java:412)
       at org.jf.dexlib.ClassDefItem.readItem(ClassDefItem.java:150)
       at org.jf.dexlib.Item.readFrom(Item.java:77)
       ... 4 more
class_def_item: Lo/baR$1;

**Comment by goel-sunny** [comment]
what is that ???
Where this smali 1.3 get stuck..??
