### ISSUE TITLE
cannot parse apk file when encrypted flag is set

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#550]
Original [issue 439](https://code.google.com/p/android-apktool/issues/detail?id=439) created by thuxnder@dexlabs.org on 2013-03-25T19:54:56.000Z:

> <b>What steps will reproduce the problem?</b>
> 1. convert apk file with encrypted flag set

<b>What is the expected output? What do you see instead?</b>
apktool cannot handle the file at all:

java -jar brut.apktool/apktool-cli/build/libs/apktool-cli-1.5.3-SNAPSHOT.jar d -d delta.apk ooooo
Exception in thread &quot;main&quot; brut.androlib.AndrolibException: brut.directory.DirectoryException: java.util.zip.ZipException: invalid CEN header (encrypted entry)
    at brut.androlib.ApkDecoder.hasSources(ApkDecoder.java:201)
    at brut.androlib.ApkDecoder.decode(ApkDecoder.java:83)
    at brut.apktool.Main.cmdDecode(Main.java:148)
    at brut.apktool.Main.main(Main.java:77)
Caused by: brut.directory.DirectoryException: java.util.zip.ZipException: invalid CEN header (encrypted entry)
    at brut.directory.ZipRODirectory.&lt;init&gt;(ZipRODirectory.java:55)
    at brut.directory.ZipRODirectory.&lt;init&gt;(ZipRODirectory.java:38)
    at brut.androlib.res.util.ExtFile.getDirectory(ExtFile.java:55)
    at brut.androlib.ApkDecoder.hasSources(ApkDecoder.java:199)
    ... 3 more
Caused by: java.util.zip.ZipException: invalid CEN header (encrypted entry)
    at java.util.zip.ZipFile.open(Native Method)
    at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:214)
    at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:144)
    at java.util.zip.ZipFile.&lt;init&gt;(ZipFile.java:158)
    at brut.directory.ZipRODirectory.&lt;init&gt;(ZipRODirectory.java:53)
    ... 6 more

<b>What version of the product are you using? On what operating system?</b>
fresh checkout 69ee710e305b36184a79712219b8c95cde505fac
linux

<b>Please provide any additional information below.</b>
example file can be found here:
https://github.com/blueboxsecurity/DalvikBytecodeTampering

**Comment by nguyenvulong** [comment]
I just tried apktool (2.2.1) but it failed. So I guess this was not fixed in dexlib2?

`Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: java.util.zip.ZipException: invalid CEN header (encrypted entry)
	at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:272)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:96)
	at brut.apktool.Main.cmdDecode(Main.java:166)
	at brut.apktool.Main.main(Main.java:81)
Caused by: brut.directory.DirectoryException: java.util.zip.ZipException: invalid CEN header (encrypted entry)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:55)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:38)
	at brut.androlib.res.util.ExtFile.getDirectory(ExtFile.java:55)
	at brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:270)
	... 3 more
Caused by: java.util.zip.ZipException: invalid CEN header (encrypted entry)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:53)`

**Comment by iBotPeaches** [comment]
@nguyenvulong Encrypted flag `isEncrypted` no longer work on Android, so the hacky patches were removed. If it no longer works on Android, there is no reason to keep those patches in the tool.

If you are using an old Android version and still using this trick, you are welcome to use an old build.
