### ISSUE TITLE
Installing com.htc.resources fails

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#644]
Original [issue 534](https://code.google.com/p/android-apktool/issues/detail?id=534) created by JanTay.Duong on 2013-10-17T15:17:11.000Z:

<b>What steps will reproduce the problem?</b>
1.apktool if com.htc.resources.apk

<b>What is the expected output? What do you see instead?</b>

```
C:\Android\reverse engineering&gt;apktool d -b com.htc.resources.apk
I: Using Apktool 2.0.0-Beta7 on com.htc.resources.apk
I: Loading resource table...
Exception in thread &quot;main&quot; brut.androlib.AndrolibException: Multiple resources:
spec=0x020500c0 dimen/title_primary_xs, config=-hdpi
        at brut.androlib.res.data.ResConfig.addResource(ResConfig.java:63)
        at brut.androlib.res.data.ResConfig.addResource(ResConfig.java:56)
        at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:199)

        at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:168
)
        at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:134)
        at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:10
9)
        at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:81)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:49)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibRes
ources.java:615)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.jav
a:74)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.jav
a:66)
        at brut.androlib.Androlib.getResTable(Androlib.java:54)
        at brut.androlib.ApkDecoder.getResTable(ApkDecoder.java:216)
        at brut.androlib.ApkDecoder.setAnalysisMode(ApkDecoder.java:173)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:88)
        at brut.apktool.Main.cmdDecode(Main.java:166)
        at brut.apktool.Main.main(Main.java:85)&quot;
```

<b>What version of the product are you using? On what operating system?</b>
2.0.0 b7 - win8

**Comment by iBotPeaches** [comment]
Good to see we have another apk to investigate.

Dumping configurations of the new 5.1 HTC apk.

```
nodpi-v4
ldrtl
v21
mdpi-v4
hdpi-v4
sw320dp-hdpi-v13
sw360dp-hdpi-v13
xhdpi-v4
sw360dp-xhdpi-v13
sw432dp-400dpi-v13
xxhdpi-v4
sw360dp-xxhdpi-v13
large-v4
v11
sw600dp-v13
sw720dp-v13
v14
v19
land
sw600dp-land-v13
fa
ar
iw
da
ja
nb
de
bg
th
fi
vi
sk
el
nl
pl
sl
in
ko
ro
fr
hr
sr
tr
cs
es
it
pt
hu
ru
sv
my
zy
zh-HK
zh-CN
pt-PT
zh-TW
xlarge-v4
h480dp-v13
sw720dp-land-v13
large-mdpi-v4
sw320dp-mdpi-v13
sw360dp-mdpi-v13
sw432dp-mdpi-v13
large-hdpi-v4
sw432dp-hdpi-v13
land-hdpi-v4
large-xhdpi-v4
sw320dp-xhdpi-v13
sw432dp-xhdpi-v13
land-xhdpi-v4
400dpi-v4
large-400dpi-v4
sw320dp-400dpi-v13
sw360dp-400dpi-v13
land-400dpi-v4
large-xxhdpi-v4
sw320dp-xxhdpi-v13
sw432dp-xxhdpi-v13
land-xxhdpi-v4
xxxhdpi-v4
large-xxxhdpi-v4
sw320dp-xxxhdpi-v13
sw360dp-xxxhdpi-v13
sw432dp-xxxhdpi-v13
ja-mdpi-v4
ja-hdpi-v4
ja-xhdpi-v4
ja-400dpi-v4
ja-xxhdpi-v4
ja-xxxhdpi-v4
ko-mdpi-v4
ko-hdpi-v4
ko-xhdpi-v4
ko-400dpi-v4
ko-xxhdpi-v4
ko-xxxhdpi-v4
zh-CN-mdpi-v4
zh-CN-hdpi-v4
zh-CN-xhdpi-v4
zh-CN-400dpi-v4
zh-CN-xxhdpi-v4
zh-CN-xxxhdpi-v4
zh-TW-mdpi-v4
zh-TW-hdpi-v4
zh-TW-xhdpi-v4
zh-TW-400dpi-v4
zh-TW-xxhdpi-v4
zh-TW-xxxhdpi-v4
nokeys
ca
ca-nokeys
da-nokeys
fa-nokeys
ja-v19
ja-nokeys
nb-nokeys
be
de-nokeys
af
af-nokeys
bg-nokeys
th-nokeys
fi-nokeys
hi
hi-nokeys
vi-nokeys
kk
sk-nokeys
uk
uk-nokeys
el-nokeys
nl-nokeys
pl-nokeys
sl-nokeys
tl
tl-nokeys
am
am-nokeys
rm-nokeys
in-nokeys
ko-nokeys
ro-nokeys
ar-nokeys
fr-nokeys
hr-nokeys
sr-nokeys
tr-nokeys
cs-nokeys
es-nokeys
ms
ms-nokeys
et
it-nokeys
lt
lt-nokeys
pt-nokeys
hu-nokeys
ru-nokeys
zu
zu-nokeys
lv
lv-nokeys
sv-nokeys
iw-nokeys
sw
sw-nokeys
hy
my-v19
my-v21
fr-CA
lo-LA
en-GB
en-GB-nokeys
et-EE
ka-GE
km-KH
hy-AM
zh-CN-v19
zh-CN-nokeys
en-CN
en-IN
mn-MN
pt-BR
es-US
es-US-nokeys
pt-PT-nokeys
zh-TW-nokeys
ms-MY
rm
mcc230-mnc1
mcc262-mnc1
mcc260-mnc2
mcc232-mnc3
mcc204-mnc16
mcc204-mnc20
land-mdpi-v4
mnc1
mnc10
mcc310-mnc28
mcc246-mnc81
mcc311-mnc390
```

**Comment by jtothe4n** [comment]
Lol, the original issue was comitted by me, time flies! (-:

**Comment by iBotPeaches** [comment]
I am unfortunately or fortunately retiring this bug report. Newer iterations of `htc resources` don't have this problem and I never found out what those 2 bytes were. 

In this day of Apktool when unknown bytes are encountered I shame that OEM and usually drop support for them. Thankfully that has only been foreign oriented OEMs and not a large OEM like HTC.

If we get another HTC bug like this one, I will try to apply a quicker look into it. This is probably one of the oldest bugs here and while we fixed versions of it, we never found the true source of the problem for this specific htc resource framework file.
