### ISSUE TITLE
Exception in thread "main" - error while compiling

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#731]
Original [issue 621](https://code.google.com/p/android-apktool/issues/detail?id=621) created by siddhant.tumma1 on 2014-04-13T05:16:10.000Z:

> <b>What steps will reproduce the problem?</b>
> 1.Compiling an apk

<b>What is the expected output? What do you see instead?</b>
when i tried to compile the an apk it shows this error

Exception in thread &quot;main&quot; brut.androlib.AndrolibException: brut.directory.PathN
otExist: apktool.yml
        at brut.androlib.Androlib.readMetaFile(Androlib.java:164)
        at brut.androlib.Androlib.build(Androlib.java:183)
        at brut.androlib.Androlib.build(Androlib.java:176)
        at brut.apktool.Main.cmdBuild(Main.java:228)
        at brut.apktool.Main.main(Main.java:79)
Caused by: brut.directory.PathNotExist: apktool.yml
        at brut.directory.AbstractDirectory.getFileInput(AbstractDirectory.java:
103)
        at brut.androlib.Androlib.readMetaFile(Androlib.java:160)
        ... 4 more

<b>What version of the product are you using? On what operating system?</b>
version 1.5.2 on windows 8

<b>Please provide any additional information below.</b>

**Comment by nazmulhasan12** [comment]
is need to sign apk after recompile in ubuntu ?

**Comment by anyho** [comment]
you will get a apktool.yml  which is used in the process of building a new apk with the apktool after you decode a apk with the apktool.

**Comment by wv1124** [comment]
I: Using Apktool 2.1.0
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.PathNotExist: apktool.yml
	at brut.androlib.Androlib.readMetaFile(Androlib.java:249)
	at brut.androlib.Androlib.build(Androlib.java:261)
	at brut.androlib.Androlib.build(Androlib.java:254)
	at brut.apktool.Main.cmdBuild(Main.java:224)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.directory.PathNotExist: apktool.yml
	at brut.directory.AbstractDirectory.getFileInput(AbstractDirectory.java:105)
	at brut.androlib.Androlib.readMetaFile(Androlib.java:245)
	... 4 more

**Comment by BurgerZ** [comment]
@wv1124 100% you had errors while decompiling.
The error `brut.directory.PathNotExist: apktool.yml` stays than there is no apktool.yml file, e.g. apk was not decompiled properly!

**Comment by mjraogr** [comment]
Hello Im facing this issue just testing decompile and recompile systemUi after install apktool

9063_framework]$ apktool b SystemUI
I: Using Apktool 2.2.3
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building resources...
W: warning: string 'accessibility_toddler_mode_activate' has no default translation.
W: warning: string 'accessibility_toddler_mode_deactivate' has no default translation.
W: warning: string 'low_battery_longlifemode_notice_text' has no default translation.
W: warning: string 'navibar_cling_message' has no default translation.
W: warning: string 'watch_brightness_dialog_brightness' has no default translation.
W: warning: string 'watch_brightness_dialog_outdoor_mode' has no default translation.
W: warning: string 'watch_brightness_dialog_volume' has no default translation.
W: /home/mjr/9063_framework/SystemUI/res/layout/system_bar_notification_panel_title.xml:14: error: Error: No resource found that matches the given name (at 'style' with value '@style/SystemBarNotificationText').
W: 
W: /home/mjr/9063_framework/SystemUI/res/layout/system_bar_notification_panel_title.xml:19: error: Error: No resource found that matches the given name (at 'style' with value '@style/SystemBarNotificationText').
W: 
W: /home/mjr/9063_framework/SystemUI/res/layout/system_bar_notification_panel_title.xml:21: error: Error: No resource found that matches the given name (at 'style' with value '@style/SystemBarNotificationText').
W: 
W: /home/mjr/9063_framework/SystemUI/res/layout/system_bar_settings_view.xml:5: error: Error: No resource found that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsRow').
W: 
W: /home/mjr/9063_framework/SystemUI/res/layout/system_bar_settings_view.xml:6: error: Error: No resource found that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsIcon').
W: 
W: /home/mjr/9063_framework/SystemUI/res/layout/system_bar_settings_view.xml:7: error: Error: No resource found that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsContents').
W: 
W: /home/mjr/9063_framework/SystemUI/res/layout/system_bar_settings_view.xml:10: error: Error: No resource found that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsPanelSeparator').
W: 
W: /home/mjr/9063_framework/SystemUI/res/layout/system_bar_settings_view.xml:11: error: Error: No resource found that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsRow').
W: 
W: /home/mjr/9063_framework/SystemUI/res/layout/system_bar_settings_view.xml:12: error: Error: No resource found that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsIcon').
W: 
W: /home/mjr/9063_framework/SystemUI/res/layout/system_bar_settings_view.xml:13: error: Error: No resource found that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsContents').
W: 
W: /home/mjr/9063_framework/SystemUI/res/layout/system_bar_settings_view.xml:15: error: Error: No resource found that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsPanelSeparator').
W: 
W: /home/mjr/9063_framework/SystemUI/res/layout/system_bar_settings_view.xml:16: error: Error: No resource found that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsRow').
W: 
W: /home/mjr/9063_framework/SystemUI/res/layout/system_bar_settings_view.xml:17: error: Error: No resource found that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsIcon').
W: 
W: /home/mjr/9063_framework/SystemUI/res/layout/system_bar_settings_view.xml:18: error: Error: No resource found that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsContents').
W: 
W: /home/mjr/9063_framework/SystemUI/res/layout/system_bar_settings_view.xml:21: error: Error: No resource found that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsPanelSeparator').
W: 
W: /home/mjr/9063_framework/SystemUI/res/layout/system_bar_settings_view.xml:22: error: Error: No resource found that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsRow').
W: 
W: /home/mjr/9063_framework/SystemUI/res/layout/system_bar_settings_view.xml:23: error: Error: No resource found that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsIcon').
W: 
W: /home/mjr/9063_framework/SystemUI/res/layout/system_bar_settings_view.xml:26: error: Error: No resource found that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsPanelSeparator').
W: 
W: /home/mjr/9063_framework/SystemUI/res/layout/system_bar_settings_view.xml:27: error: Error: No resource found that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsRow').
W: 
W: /home/mjr/9063_framework/SystemUI/res/layout/system_bar_settings_view.xml:28: error: Error: No resource found that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsIcon').
W: 
W: /home/mjr/9063_framework/SystemUI/res/layout/system_bar_settings_view.xml:29: error: Error: No resource found that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsContents').
W: 
W: /home/mjr/9063_framework/SystemUI/res/layout/system_bar_settings_view.xml:32: error: Error: No resource found that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsPanelSeparator').
W: 
W: /home/mjr/9063_framework/SystemUI/res/layout/system_bar_settings_view.xml:33: error: Error: No resource found that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsRow').
W: 
W: /home/mjr/9063_framework/SystemUI/res/layout/system_bar_settings_view.xml:34: error: Error: No resource found that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsIcon').
W: 
W: /home/mjr/9063_framework/SystemUI/res/layout/system_bar_settings_view.xml:35: error: Error: No resource found that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsContents').
W: 
W: /home/mjr/9063_framework/SystemUI/res/layout/system_bar_settings_view.xml:37: error: Error: No resource found that matches the given name (at 'style' with value '@style/SystemBarPanelSettingsPanelSeparator').
W: 
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_6073466651843915526.tmp, p, --forced-package-id, 127, --min-sdk-version, 17, --target-sdk-version, 17, --version-code, 17, --version-name, 4.2.2-I9063TVJUAOL1, --no-version-vectors, -F, /tmp/APKTOOL5166518917063688540.tmp, -0, arsc, -0, arsc, -I, /home/mjr/.local/share/apktool/framework/1.apk, -S, /home/mjr/9063_framework/SystemUI/res, -M, /home/mjr/9063_framework/SystemUI/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:493)
	at brut.androlib.Androlib.buildResources(Androlib.java:427)
	at brut.androlib.Androlib.build(Androlib.java:326)
	at brut.androlib.Androlib.build(Androlib.java:264)
	at brut.apktool.Main.cmdBuild(Main.java:231)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_6073466651843915526.tmp, p, --forced-package-id, 127, --min-sdk-version, 17, --target-sdk-version, 17, --version-code, 17, --version-name, 4.2.2-I9063TVJUAOL1, --no-version-vectors, -F, /tmp/APKTOOL5166518917063688540.tmp, -0, arsc, -0, arsc, -I, /home/mjr/.local/share/apktool/framework/1.apk, -S, /home/mjr/9063_framework/SystemUI/res, -M, /home/mjr/9063_framework/SystemUI/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:441)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:479)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_6073466651843915526.tmp, p, --forced-package-id, 127, --min-sdk-version, 17, --target-sdk-version, 17, --version-code, 17, --version-name, 4.2.2-I9063TVJUAOL1, --no-version-vectors, -F, /tmp/APKTOOL5166518917063688540.tmp, -0, arsc, -0, arsc, -I, /home/mjr/.local/share/apktool/framework/1.apk, -S, /home/mjr/9063_framework/SystemUI/res, -M, /home/mjr/9063_framework/SystemUI/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:435)
	... 6 more

**Comment by msyapha** [comment]
Same error here..im going nuts!tried everything.PATH in windows ,Updating unistall JDK re install JDK.......there is an issue for sure cause i remember it working in the version 1.4+

**Comment by abhayjain1** [comment]
brut.directory.PathNotExist: apktool.yml
	at brut.androlib.Androlib.readMetaFile(Androlib.java:251)
	at brut.androlib.Androlib.build(Androlib.java:263)
	at brut.androlib.Androlib.build(Androlib.java:256)
	at brut.apktool.Main.cmdBuild(Main.java:225)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.directory.PathNotExist: apktool.yml
	at brut.directory.AbstractDirectory.getFileInput(AbstractDirectory.java:103)
	at brut.androlib.Androlib.readMetaFile(Androlib.java:246)
	... 4 more
