### ISSUE TITLE
Breaks on decoding Google+ APKs

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#745]
Original [issue 635](https://code.google.com/p/android-apktool/issues/detail?id=635) created by archon810 on 2014-05-20T15:08:46.000Z:

 > <b>What steps will reproduce the problem?</b>
1. Download Google+ APK 4.3+ from http://www.androidpolice.com/2014/05/20/google-app-gets-a-big-update-to-v4-4-with-a-new-ui-auto-awesome-stories-improved-support-for-large-photo-libraries-and-more-apk-download/
2. Attempt to decode it.
3. Receive crash midway through decoding resources.

<b>What is the expected output? What do you see instead?</b>
Exception in thread &quot;main&quot; brut.androlib.err.UndefinedResObject: resource spec: 0x7f030010
	at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:58)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:54)
	at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferenceValue.java:60)
	at brut.androlib.res.data.value.ResReferenceValue.encodeAsResXml(ResReferenceValue.java:47)
	at brut.androlib.res.data.value.ResScalarValue.encodeAsResXmlAttr(ResScalarValue.java:45)
	at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:49)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:553)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:309)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:119)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:115)
	at brut.apktool.Main.cmdDecode(Main.java:169)
	at brut.apktool.Main.main(Main.java:85)

<b>What version of the product are you using? On what operating system?</b>
Using Apktool 2.0.0-Beta9-1e3b66f9be on com.google.android.apps.plus-4.4.0.67576161.apk

**Comment by iBotPeaches** [comment]
While investigating #1103 , it had the same issue of this. A reference that points to a resource that doesn't exist. Not quite sure why this is happening yet, whether its an improper decode of a different type of resource.

Maybe we need to check if a resource exists in the private package (`0x7f`), if it doesn't then set to @null. Something is weird.

**Comment by iBotPeaches** [comment]
Very old bug. I found in the instances that this happened, they were `parent` tags in the `styles.xml` file pointing to a local resource that doesn't exist.

So then I thought the decode was missing some resources, but the failing ID didn't exist in the apk nor were then any errors - 

```
➜  Bug635 aapt d resources com.google.android.apps.plus_4.4.0.67576161.apk | grep 'CONFIG'
```

So if the parent of a style doesn't exist, we just don't write out the `parent` tag. This may lead to errors, but worked in this case and allows decode to succeed.

```
➜  Bug635 apktool d com.google.android.apps.plus_4.4.0.67576161.apk -f
I: Using Apktool 2.2.0-e1dd43-SNAPSHOT on com.google.android.apps.plus_4.4.0.67576161.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug635 apktool b com.google.android.apps.plus_4.4.0.67576161
I: Using Apktool 2.2.0-e1dd43-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
W: warning: string 'auth_client_needs_enabling_title' has no default translation.
W: warning: string 'auth_client_needs_installation_title' has no default translation.
W: warning: string 'auth_client_needs_update_title' has no default translation.
W: warning: string 'auth_client_play_services_err_notification_msg' has no default translation.
W: warning: string 'auth_client_requested_by_msg' has no default translation.
W: warning: string 'auth_client_using_bad_version_title' has no default translation.
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
➜  Bug635 
```
