### ISSUE TITLE
Custom android attribute - Recompile Fail

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#775]
Original [issue 666](https://code.google.com/p/android-apktool/issues/detail?id=666) created by openappdev on 2014-08-09T08:32:23.000Z:

<b>What steps will reproduce the problem?</b>

1.Decompile and Recompile Apk file

<b>What is the expected output? What do you see instead?</b>
When using custom library attribute , need to recompile apk file without error 

<b>What version of the product are you using? On what operating system?</b>
Windows 8 
Apktool version: 2.0.0-dirty (Builded from git)

<b>Please provide any additional information below.</b>

Issue 1 With PagerSlidingTabStrip :

    &lt;LinearLayout android:orientation=&quot;vertical&quot; android:clipChildren=&quot;false&quot; style=&quot;@style/Match&quot;&gt;
        &lt;com.astuetz.PagerSlidingTabStrip  android:pstsShouldExpand=&quot;false&quot;  /&gt;
        &lt;android.support.v4.view.ViewPager android:id=&quot;@id/pager&quot; style=&quot;@style/Match&quot; /&gt;
    &lt;/LinearLayout&gt;

SNAPSHOT\res\layout\content_pager.xml:5: error: No resource identifier found for attribute 'pstsShouldExpand' in package 'android'

Issue 2 : With custom view 

    &lt;com.myapp.android.app.widget.AspectRatioLayout  android:aspectRatio=&quot;@dimen/thumbnail_aspect_ratio&quot;&gt;
	
\res\layout-sw600dp\list_item_single.xml:4: error: No resource identifier found for attribute 'aspectRatio' in package 'android'

Issue 3: oak library

&lt;oak.widget.TextViewWithFont android:id=&quot;@id/title&quot; android:oakFont=&quot;@string/font_light&quot; style=&quot;@style/Font.Item&quot; /&gt;

\res\layout\list_item_search.xml:5: error: Noresource identifier found for attribute 'oakFont' in package 'android'

Exception:

brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:
\Users\testuser\AppData\Local\Temp\brut_util_Jar_123662913771692459.tmp, p, --forced-package-id, 127, --min-sdk-version,
14, --target-sdk-version, 20, --version-code, 1017, --version-name, 1.0-SNAPSHOT, -F, C:\Users\testuser\AppData\Local\Tem
p\APKTOOL335103424956595181.tmp, -0, arsc, -I, C:\Users\testuser\apktool\framework\1.apk, -S, C:\Users\testuser\Desktop\HB
O Nordic-com.hbo.android.app-1017-v1.0-SNAPSHOT\res, -M, C:\Users\testuser\Desktop\TestApp
.0-SNAPSHOT\AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:439)
        at brut.androlib.Androlib.buildResources(Androlib.java:367)
        at brut.androlib.Androlib.build(Androlib.java:290)
        at brut.androlib.Androlib.build(Androlib.java:262)
        at brut.apktool.Main.cmdBuild(Main.java:236)
        at brut.apktool.Main.main(Main.java:88)

Note :
unfortunately I cannot send the apk file due to Non-disclosure agreement.

**Comment by iBotPeaches** [comment]
Closing this. 

I tried my best without an apk making my own `declare-styleable` to try and duplicate. I cannot duplicate attributes being removed in the manifest no matter what I try locally.

In addition, all the attributes mentioned above do not experience a problem testing myself, which leads me to believe a framework issue as well.
