### ISSUE TITLE
Could not decode arsc file

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#789]
Original [issue 680](https://code.google.com/p/android-apktool/issues/detail?id=680) created by roener on 2014-09-26T11:40:49.000Z:

> <b>What steps will reproduce the problem?</b>
> 1. download most recent GApps and take the Phonesky.apk which is the Play Store (com.android.vending)
> 2. execute 'apktool d Phonesky.apk'

<b>What is the expected output? What do you see instead?</b>
expected output: folder with decompiled (re)sources

instead:
I: Using Apktool 2.0.0-Beta9 on Phonesky.apk
I: Loading resource table...
Exception in thread &quot;main&quot; brut.androlib.AndrolibException: Could not decode arsc file
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:54)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibRes
ources.java:604)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:74)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:66)
        at brut.androlib.Androlib.getResTable(Androlib.java:49)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:93)
        at brut.apktool.Main.cmdDecode(Main.java:169)
        at brut.apktool.Main.main(Main.java:85)
Caused by: java.io.IOException: Expected: 0x001c0001, got: 0x00000000
        at brut.util.ExtDataInput.skipCheckInt(ExtDataInput.java:48)
        at brut.androlib.res.decoder.StringBlock.read(StringBlock.java:43)
        at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:95)
        at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:81)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:49)
        ... 7 more

<b>What version of the product are you using? On what operating system?</b>
apktool v2.0.0 Beta9, Windows 8.1

Thank you for this great tool and your help!

**Comment by iPaulPro** [comment]
Having this issue with 2.0.0.

```
I: Baksmaling...
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:56)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:491)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:74)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:66)
	at brut.androlib.Androlib.getResTable(Androlib.java:50)
	at brut.androlib.ApkDecoder.getResTable(ApkDecoder.java:189)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:114)
	at brut.apktool.Main.cmdDecode(Main.java:146)
	at brut.apktool.Main.main(Main.java:77)
Caused by: java.io.IOException: Expected: 0x001c0001, got: 0x00000000
	at brut.util.ExtDataInput.skipCheckInt(ExtDataInput.java:48)
	at brut.androlib.res.decoder.StringBlock.read(StringBlock.java:44)
	at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:102)
	at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:83)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:49)
	... 8 more
```

Not sure if this helps, but here is my truncated `build.gradle`:

```
android {
    compileSdkVersion 22
    buildToolsVersion "22.0.1"

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/dependencies.txt'
        exclude 'META-INF/LGPL2.1'
    }
}
```

**Comment by tustar** [comment]
I have the same issue with 2.0.0. 
```
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:52)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:538)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:63)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:55)
	at brut.androlib.Androlib.getResTable(Androlib.java:64)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:209)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:92)
	at brut.apktool.Main.cmdDecode(Main.java:165)
	at brut.apktool.Main.main(Main.java:81)
Caused by: java.io.IOException: Expected: 0x00000008, got: 0x00000006
	at brut.util.ExtDataInput.skipCheckShort(ExtDataInput.java:56)
	at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:238)
	at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:201)
	at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:189)
	at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:157)
	at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:114)
	at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:78)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
	... 8 more
```

**Comment by hslls** [comment]
apktool_2.0.0.jar
md5: 9b324375e115acd09932d73e25fc741b

have this issue

**Comment by tustar** [comment]
@hslls Thanks

**Comment by hslls** [comment]
@tustar 好说好说
