### ISSUE TITLE
Apktool not able to decompile android studio build apk successfully; crashing.

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#809]
Original [issue 700](https://code.google.com/p/android-apktool/issues/detail?id=700) created by raghv.singh2006 on 2014-11-07T07:06:11.000Z:

> <b>What steps will reproduce the problem?</b>
> 1. apktool d an apk build by android studio

<b>What is the expected output? What do you see instead?</b>
Expected output is a decompiled for of corresponding apk.
But actual output is :

$ sudo java -jar ~/Workspace/GiT/awas-android/Tools/apktool.jar d Workspace/apk/app-debug.apk 
I: Using Apktool 2.0.0-RC2 on app-debug.apk
I: Loading resource table...
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /var/root/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
W: Could not decode attr value, using undecoded value instead: ns=android, name=touchscreenBlocksFocus, value=0xffffffff
I: Decoding values _/_ XMLs...
Exception in thread &quot;main&quot; brut.androlib.err.UndefinedResObject: resource spec: 0x0101048f
    at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
    at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:58)
    at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:54)
    at brut.androlib.res.decoder.ResAttrDecoder.decode(ResAttrDecoder.java:36)
    at brut.androlib.res.decoder.AXmlResourceParser.getAttributeValue(AXmlResourceParser.java:369)
    at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValue(XmlPullParserDelegate.java:69)
    at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
    at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
    at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:83)
    at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:141)
    at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(ResStreamDecoderContainer.java:33)
    at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:107)
    at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:91)
    at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:322)
    at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:123)
    at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
    at brut.apktool.Main.cmdDecode(Main.java:170)
    at brut.apktool.Main.main(Main.java:86)

<b>What version of the product are you using? On what operating system?</b>
version apktool_2.0.0rc2.jar

<b>Please provide any additional information below.</b>

**Comment by ashok-vserv** [comment]
Yes it did worked. Can we automate this through some switch?

**Comment by iBotPeaches** [comment]
http://forum.xda-developers.com/showpost.php?p=59737902&postcount=2953

> I have thought about a way to automate the frameworks, because of the common problem of those forgetting to update/remove the 1.apk during new apktool versions. However, I haven't spent time on a feature in months. All my work has been cat and mouse fixing problems that arise. Since the framework files live on the file system and you can manage them however you want, it currently isn't high priority to have anything automated/uninstall with the framework files.

**Comment by ashok-vserv** [comment]
Thanks..Can we fix it by simply replacing some resource in the apktool.jar and repacking apktool.jar?

**Comment by iBotPeaches** [comment]
That makes no sense. The new framework is in the latest apktool jar. We don't need to replace anything, we need to code a solution that can watch the filesystem and detect what version of framework is installed.

**Comment by ashok-vserv** [comment]
We would like to use apktool.jar as stand alone utility tool in an environment where android sdk/runtime is not installed and hence curious to know whether we can fix it by bundling within the apktool.jar.

**Comment by iBotPeaches** [comment]
No, you will need to write a script to delete `$HOME/apktool/framework/1.apk` on new versions until such functionality is implemented.

I am accepting pull requests for this, so you may work on that if you wish.

**Comment by ashok-vserv** [comment]
Thanks..Can we expect newer RC builds for apktool.jar with this issue taken care by the apktool.jar itself?If yes tentative timelines would help to take a decision.

**Comment by iBotPeaches** [comment]
No, I have no intention of adding this support before 2.0 gold. This isn't a bug. You simply have to delete one file from the filesystem before upgrading.

I don't even know how I could program this effectively. What if users wanted to use the old framework? When do you decide to remove the file or not? You would need to implement a new option of like `u / update-framework` to force the option explicitly. 

As you can see, this feature is still in a planning stage.
