### ISSUE TITLE
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.Direc toryException: file must be a directory

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#818]
Original [issue 709](https://code.google.com/p/android-apktool/issues/detail?id=709) created by nabeelshikder on 2014-11-25T05:13:54.000Z:

> <b>What steps will reproduce the problem?</b>
> 1. apktool decode C:\Users\user\Desktop\com.sgiggle.production.apk

<b>What is the expected output? What do you see instead?</b>

Expected: decode without errors

Result: 

C:\Windows&gt;apktool decode C:\Users\user\Desktop\com.sgiggle.production.apk
I: Using Apktool 2.0.0-RC2 on com.sgiggle.production.apk
I: Loading resource table...
I: Loading resource table...
Exception in thread &quot;main&quot; brut.androlib.AndrolibException: brut.directory.Direc
toryException: file must be a directory: com.sgiggle.production
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:313
)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:123)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
        at brut.apktool.Main.cmdDecode(Main.java:170)
        at brut.apktool.Main.main(Main.java:86)
Caused by: brut.directory.DirectoryException: file must be a directory: com.sgig
gle.production
        at brut.directory.FileDirectory.&lt;init&gt;(FileDirectory.java:38)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:291
)
        ... 4 more

C:\Windows&gt;apktool decode C:\Windows\com.sgiggle.production.apk
I: Using Apktool 2.0.0-RC2 on com.sgiggle.production.apk
I: Loading resource table...
I: Loading resource table...
Exception in thread &quot;main&quot; brut.androlib.AndrolibException: brut.directory.Direc
toryException: file must be a directory: com.sgiggle.production
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:313
)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:123)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
        at brut.apktool.Main.cmdDecode(Main.java:170)
        at brut.apktool.Main.main(Main.java:86)
Caused by: brut.directory.DirectoryException: file must be a directory: com.sgig
gle.production
        at brut.directory.FileDirectory.&lt;init&gt;(FileDirectory.java:38)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:291
)
        ... 4 more

<b>What version of the product are you using? On what operating system?</b>
Version 2.0.0 RC2
Windows 8 64-Bit

<b>Please provide any additional information below.</b>

The apk file is over 20MB so it is too large to attach to this Email.  However, it can be downloaded from here:  http://apk-dl.com/download/android/com.sgiggle.production/Tango-Messenger%2C-Video-%26-Calls3.12.119443-apk/

(Tango Messenger App)

Please let me know how to resolve this error.

**Comment by dunyuling** [comment]
first I execute the command 'java -jar apktool.jar d example.apk' as root, it occurs this bug.when i execute the command as myself , it successes.

**Comment by iBotPeaches** [comment]
@dunyuling using root means, frameworks are probably being written in a location which cannot be read. My suggestion is don't use root. That's dangerous and apktool doesn't need it.

**Comment by bharv410** [comment]
I had this problem and adding `sudo` to the beginning of the command solved it

**Comment by econBabar** [comment]
Facing the Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: for some apk like whatsapp. I'm using windows

Do you know any solution?

**Comment by iBotPeaches** [comment]
You'll have better luck opening a bug report following all the details as a DirectoryException can be easy as running the command wrong or a bug.

**Comment by econBabar** [comment]
As i mentioned this happens for some apps. Same commands work for my own apk. I doubt that apktool doesn't work with obfuscation or progaurd thing!

**Comment by WangChengLongWilliam** [comment]
In fact,i runing on windows 10,use administor run the cmd will be ok

**Comment by quanlinh** [comment]
change to administrator solved the problems in cmd

**Comment by PiecePaperCode** [comment]
Running it as sudo/root on Linux resolved my problem

**Comment by adojayfan** [comment]
> I had this problem and adding `sudo` to the beginning of the command solved it

Thanks , it's working for me

**Comment by Moutamid** [comment]
I am facing the same Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: and i did anything i could do but all in vain. Anyone got any solution?

**Comment by AmineAyachi** [comment]
> I had this problem and adding `sudo` to the beginning of the command solved it

for windows run cmd as administrator

**Comment by Aniket-coder95** [comment]
Exception in thread "main" brut.androlib.AndrolibException: Can't create directory: /home/kumar_pc/.local/share/apktool/framework



help me in this

**Comment by Sparta2020** [comment]
I had the exact same issue. I had to run command prompt as administrator. Hopefully this helps.

**Comment by AhmadIzaz** [comment]
I had the exact same issue. I had to run command prompt as administrator and this works,

**Comment by jws1837** [comment]
I had the exact same issue too. I had to run command prompt as administrator. Thank you

**Comment by tianxia--** [comment]
First, find a particularly simple APK parsing, and then decompile the previous failed one after success,
