### ISSUE TITLE
Exception in thread "main" brut.androlib.AndrolibException: java.io.FileNotFound

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#820]
Original [issue 711](https://code.google.com/p/android-apktool/issues/detail?id=711) created by ahm346 on 2014-11-26T01:15:21.000Z:

> <b>What steps will reproduce the problem?</b>
> 1.apktool if f framework-res.apk

<b>What is the expected output? What do you see instead?</b>
Expected output: Framework installed
Instead:
Exception in thread &quot;main&quot; brut.androlib.AndrolibException: java.io.FileNotFound
Exception: framework-res.apk (The system cannot find the file specified)
        at brut.androlib.res.AndrolibResources.installFramework(AndrolibResource
s.java:681)
        at brut.androlib.Androlib.installFramework(Androlib.java:649)
        at brut.apktool.Main.cmdInstallFramework(Main.java:256)
        at brut.apktool.Main.main(Main.java:92)
Caused by: java.io.FileNotFoundException: framework-res.apk (The system cannot f
ind the file specified)
        at java.io.RandomAccessFile.open(Native Method)
        at java.io.RandomAccessFile.&lt;init&gt;(Unknown Source)
        at org.apache.commons.compress.archivers.zip.ZipFile.&lt;init&gt;(ZipFile.java
:203)
        at org.apache.commons.compress.archivers.zip.ZipFile.&lt;init&gt;(ZipFile.java
:182)
        at org.apache.commons.compress.archivers.zip.ZipFile.&lt;init&gt;(ZipFile.java
:143)
        at brut.directory.ZipExtFile.&lt;init&gt;(ZipExtFile.java:28)
        at brut.androlib.res.AndrolibResources.installFramework(AndrolibResource
s.java:647)
        ... 3 more 

<b>What version of the product are you using? On what operating system?</b>
On windows 7
apktools version:2.0.0

<b>Please provide any additional information below.</b>

**Comment by umustbeloggedintododat** [comment]
but how do you fix
