### ISSUE TITLE
apktool does not decode apps built by Android Studio

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#840]
Original [issue 731](https://code.google.com/p/android-apktool/issues/detail?id=731) created by jason44107 on 2014-12-18T20:35:23.000Z:

> <b>What steps will reproduce the problem?</b>
> 1. Using Android Studio, create and build a simple &quot;hello world&quot; app.
> 2. Use apktool to decode it.

<b>What is the expected output? What do you see instead?</b>

The expected output is that the app is decoded.  The actual output is this error:

I: Using Apktool 2.0.0-RC3 on app-release.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/jasonk/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
W: Could not decode attr value, using undecoded value instead: ns=android, name=touchscreenBlocksFocus, value=0xffffffff
I: Decoding values _/_ XMLs...
Exception in thread &quot;main&quot; brut.androlib.err.UndefinedResObject: resource spec: 0x0101048f
    at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
    at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:57)
    at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:53)
    at brut.androlib.res.decoder.ResAttrDecoder.decode(ResAttrDecoder.java:36)
    at brut.androlib.res.decoder.AXmlResourceParser.getAttributeValue(AXmlResourceParser.java:369)
    at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValue(XmlPullParserDelegate.java:69)
    at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
    at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
    at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:83)
    at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:141)
    at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(ResStreamDecoderContainer.java:33)
    at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:114)
    at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:99)
    at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:323)
    at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:131)
    at brut.androlib.ApkDecoder.decode(ApkDecoder.java:101)
    at brut.apktool.Main.cmdDecode(Main.java:165)
    at brut.apktool.Main.main(Main.java:81)

<b>What version of the product are you using? On what operating system?</b>

2.0.0 RC3 on Mac OS X 10.10.1.

<b>Please provide any additional information below.</b>

This might be related to issues 635 and 722.

**Comment by popoaichuiniu** [comment]
apk tool decode apk, and there is  a unknown dir in the output deocde files dir .apktool does not decode apps built by Android Studio?
