### ISSUE TITLE
LG Encrypted APKs - liblgalmond.so

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#847]
Original [issue 738](https://code.google.com/p/android-apktool/issues/detail?id=738) created by yoav.goop on 2014-12-26T07:46:22.000Z:

<b>What steps will reproduce the problem?</b>
1.apktool if lge-res.apk
2.apktool if framework-res.apk
3.in resources folder rename 0.apk to 2.apk (fix error with resources)
4.compile apktool from source.
5. run this code:

```
 public static void main(String[] args) throws AndrolibException, IOException, DirectoryException {
        ApkDecoder decoder = new ApkDecoder();
        decoder.setApkFile(new File(&quot;C:\\Users\\Yoav\\Downloads\\android\\LGSystemUI.apk&quot;));
        decoder.setApi(21);
        decoder.setOutDir(new File(&quot;C:\\Users\\Yoav\\Downloads\\android\\lgcover\\&quot;));
        decoder.decode();
    }
```

<b>What is the expected output? What do you see instead?</b>
output:

```
Exception in thread &quot;main&quot; org.jf.dexlib2.dexbacked.DexBackedDexFile$NotADexFile: Invalid magic value: 01 18 24 61 70 70 6c 69
	at org.jf.dexlib2.dexbacked.DexBackedDexFile.verifyMagicAndByteOrder(DexBackedDexFile.java:151)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile.&lt;init&gt;(DexBackedDexFile.java:70)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile.&lt;init&gt;(DexBackedDexFile.java:96)
	at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:84)
	at org.jf.dexlib2.DexFileFactory.loadDexFile(DexFileFactory.java:59)
	at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:94)
	at brut.androlib.src.SmaliDecoder.decode(SmaliDecoder.java:46)
	at brut.androlib.Androlib.decodeSourcesSmali(Androlib.java:91)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:126)
	at com.company.Main.main(Main.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```

(full log - http://pastebin.com/TQzUJ4Hm )

<b>What version of the product are you using? On what operating system?</b>
Windows 8.1 64bit, compiled from source.

<b>Please provide any additional information below.</b>
LGCover.apk was pulled from my G3 D855 on 20E (5.0)

**Comment by strazzere** [comment]
Just wanted to comment on this. I've (mainly) fully reversed this and have a stand alone tool ready-ish. I'll comment here when it is fully done. However I've brought this issue with someone from the LG security team at a recent conference - where they where shocked this "old code" ever made it to a device, let alone a newer device. If I hear any other updates about this, I'll post them, though it seems like this is going to be "fixed" sooner or later on their end.

**Comment by amir1111** [comment]
I believe that these apps I uploaded might be exhibiting the same issue: 
http://www.filedropper.com/dexissue-encryptedapps
is this neccerily an LG encryption issue, or just a general encryption issue?

**Comment by strazzere** [comment]
@amir1111 Well - it's a "general encryption issue" in the sense that Apktool won't handle encryption. Though the specific issue you're speaking about is something only LG performs on their roms - so it's a LG DRM-type crypo issue.

**Comment by iBotPeaches** [comment]
I'm closing this, as it has already been said. These APKs weren't met to make it to production and no support for these APKs will be added to Apktool.

Stand alone tools may exist and can be linked in this thread for any "googlers" coming to this thread.
