### ISSUE TITLE
Problem of loading resource table

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#862]
Original [issue 753](https://code.google.com/p/android-apktool/issues/detail?id=753) created by wfg611004900521 on 2015-01-30T19:18:22.000Z:

> I'm running apkool_2.0.0rc3 to decode QQ_182.apk (link: http://gdown.baidu.com/data/wisegame/2c6a60c5cb96c593/QQ_182.apk) on a MAC 10.10.1

And it gives me following error message:

$java -jar ~/Downloads/apktool_2.0.0rc3.jar d -f QQ_182.apk
I: Using Apktool 2.0.0-RC3 on QQ_182.apk
I: Loading resource table...
Exception in thread &quot;main&quot; brut.androlib.AndrolibException: Multiple res specs: attr/0
    at brut.androlib.res.data.ResType.addResSpec(ResType.java:58)
    at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:182)
    at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:157)
    at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:125)
    at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:100)
    at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:78)
    at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
    at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:606)
    at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:75)
    at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:67)
    at brut.androlib.Androlib.getResTable(Androlib.java:61)
    at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:206)
    at brut.androlib.ApkDecoder.decode(ApkDecoder.java:92)
    at brut.apktool.Main.cmdDecode(Main.java:165)
    at brut.apktool.Main.main(Main.java:81)

Any clue of why this happen? Thanks.

**Comment by mimi86uk** [comment]
I am able to decompile the file using "advanced apktool" but when i use apktool alone via command line i get this error, so the response from conner.tumbleson is not valid. 

My apk does have a res folder i can see it using dexindexor app on my phone and it decompiled using other decompilers  its just apktool doesn't decompile it properly.

**Comment by iBotPeaches** [comment]
Then report a bug? The APK that this bug was reported for, had no `/res` folder. This makes it different.

**Comment by mimi86uk** [comment]
I'm sure this isn't a bug because Ive tried all versions of apktool as well as apks featured on apktool tutorials and it doesn't decompile for me as it does for others on this board. Its definitely something else, because some pc's work with apktool and some doesn't. 
What is the denominator?? Should be included in the system requirements for this software.
