### ISSUE TITLE
Unable to decode app

### ISSUE THREAD

**Issue by iBotPeaches** [iBotPeaches/Apktool#882]
Original [issue 773](https://code.google.com/p/android-apktool/issues/detail?id=773) created by hoperoski on 2015-03-03T16:18:55.000Z:

<b>What steps will reproduce the problem?</b>
java -jar apktool_2.0.0rc4.jar d se.feomedia.quizkampen.pl.lite.apk

<b>What is the expected output? What do you see instead?</b>
I suppose it should decode app.

Exception in thread &quot;main&quot; java.lang.NullPointerException
        at java.io.Writer.write(Writer.java:157)
        at brut.androlib.res.util.ExtMXSerializer.writeAttributeValue(ExtMXSerializer.java:38)
        at org.xmlpull.mxp1_serializer.MXSerializer.attribute(MXSerializer.java:673)
        at org.xmlpull.v1.wrapper.classic.XmlSerializerDelegate.attribute(XmlSerializerDelegate.java:106)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
        at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:83)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:141)
        at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(ResStreamDecoderContainer.java:33)
        at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:114)
        at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:99)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:339)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:133)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:104)
        at brut.apktool.Main.cmdDecode(Main.java:165)
        at brut.apktool.Main.main(Main.java:81)

<b>What version of the product are you using? On what operating system?</b>
apktool_2.0.0rc4.jar Windows XP java version &quot;1.8.0_25&quot;

<b>Please provide any additional information below.</b>
APK link:
https://mega.co.nz/#!D0shVJwL!30TDc7ICmM831rvv8RdoX-a_wBI36R-8N4x4M1KJC1Q

**Comment by iBotPeaches** [comment]
Closing in favour of #913
