### ISSUE TITLE
Could not decode attr value, using undecoded value instead

### ISSUE THREAD

**Issue by gloryon** [iBotPeaches/Apktool#899]
**What steps will reproduce the problem?**
java -jar apktool_2.0.0rc4.jar d -f .apk  KAYAK.apk

**What is the expected output? What do you see instead?**
I suppose it should decode app.
W: Could not decode attr value, using undecoded value instead: ns=android, name=parentActivityName, value=0x00000064
Exception in thread "main" java.lang.NullPointerException
        at java.io.Writer.write(Unknown Source)
        at brut.androlib.res.util.ExtMXSerializer.writeAttributeValue(ExtMXSerializer.java:38)
        at org.xmlpull.mxp1_serializer.MXSerializer.attribute(MXSerializer.java:673)
        at org.xmlpull.v1.wrapper.classic.XmlSerializerDelegate.attribute(XmlSerializerDelegate.java:106)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
        at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:83)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:141)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decodeManifest(XmlPullStreamDecoder.java:153)
        at brut.androlib.res.decoder.ResFileDecoder.decodeManifest(ResFileDecoder.java:134)
        at brut.androlib.res.AndrolibResources.decodeManifestWithResources(AndrolibResources.java:294)
        at brut.androlib.Androlib.decodeManifestWithResources(Androlib.java:138)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
        at brut.apktool.Main.cmdDecode(Main.java:165)
        at brut.apktool.Main.main(Main.java:81)

**What version of the product are you using? On what operating system?**
apktool_2.0.0rc4.jar Windows 7 java  "java version "1.8.0_25"

**Please provide any additional information below.**
APK link: https://play.google.com/store/apps/details?id=com.kayak.android

**Comment by gloryon** [comment]
I del file C:\Users\xxxx\apktool\framework\1.apk - This error does not become

**Comment by cerineu** [comment]
how did u delete it? could u explain the process?
