### ISSUE TITLE
After buid apktool successful,install framework-res.jar fail

### ISSUE THREAD

**Issue by fengsan** [iBotPeaches/Apktool#902]
java -jar apktool-2.0.0-dirty-small.jar if framework-res.apk

```
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:52)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:39)
        at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:685)
        at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:667)
        at brut.androlib.Androlib.installFramework(Androlib.java:608)
        at brut.apktool.Main.cmdInstallFramework(Main.java:240)
        at brut.apktool.Main.main(Main.java:87)
Caused by: java.io.IOException: Expected: 0x00000008, got: 0x00000000
        at brut.util.ExtDataInput.skipCheckShort(ExtDataInput.java:56)
        at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:238)
        at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:201)
        at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:189)
        at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:157)
        at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:114)
        at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:78)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
        ... 6 more
```

**Comment by iBotPeaches** [comment]
Can you upload the apk somewhere and post the link here?
