### ISSUE TITLE
Error while Install AOSP Android 5.1 framework-res.apk from (LegacyXperiaAOSP beta1 "http://downloads.gapinski.eu/lxaosp/" )

### ISSUE THREAD

**Issue by Hanger1** [iBotPeaches/Apktool#903]
apktool if framework-res.apk
--------------------------------------------------  Log  ------------------------------------------------------------------
```
Exception in thread "main" brut.androlib.AndrolibException: Invalid value type:
0
        at brut.androlib.res.data.value.ResValueFactory.factory(ResValueFactory.
java:64)
        at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:242)

        at brut.androlib.res.decoder.ARSCDecoder.readComplexEntry(ARSCDecoder.ja
va:230)
        at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:200)

        at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:188
)
        at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:156)
        at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:11
3)
        at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:78)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:39)
        at brut.androlib.res.AndrolibResources.installFramework(AndrolibResource
s.java:678)
        at brut.androlib.res.AndrolibResources.installFramework(AndrolibResource
s.java:660)
        at brut.androlib.Androlib.installFramework(Androlib.java:641)
        at brut.apktool.Main.cmdInstallFramework(Main.java:240)
        at brut.apktool.Main.main(Main.java:87)
```
-------------------------------------------------------  End  ---------------------------------------------------------------
[ Attachment ]
Here is framework-res.apk >> https://www.dropbox.com/s/midyfs5u0cndl8w/framework-res.7z?dl=0
--------------------------------------------------------------------------------------------------------------
java -version
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b25)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)
----------------------------------------------------------------------------------------------

**Comment by iBotPeaches** [comment]
This bug was fixed here - https://github.com/iBotPeaches/Apktool/commit/2db8828efb2b6a968fca11d153ea1276bfccdce5

**Comment by Hanger1** [comment]
Thanks
