### ISSUE TITLE
Error install framework

### ISSUE THREAD

**Issue by juanro49** [iBotPeaches/Apktool#906]
I have a problem to install framework from stock rom huawei to descompile apks (problem only in stock roms) 

[code] - Instalando frameworks.
- Cuando acabe volverás al menú principal.

framework-res.apk
W: Config flags size > 38. Exceeding bytes: 0x2400.
W: Invalid config flags detected: string-ERR0
W: Config flags size > 38. Exceeding bytes: 0x9C00.
W: Invalid config flags detected: string-ERR1
W: Config flags size > 38. Exceeding bytes: 0x2A02.
W: Invalid config flags detected: string-ERR2
W: Config flags size > 38. Exceeding bytes: 0x9C00.
W: Invalid config flags detected: string-ERR3
W: Config flags size > 38. Exceeding bytes: 0x8801.
W: Invalid config flags detected: string-ERR4
W: Config flags size > 38. Exceeding bytes: 0x5E03.
W: Invalid config flags detected: string-ERR5
W: Config flags size > 38. Exceeding bytes: 0xE703.
W: Invalid config flags detected: string-ERR6
W: Config flags size > 38. Exceeding bytes: 0xDE00.
W: Invalid config flags detected: string-ERR7
W: Config flags size > 38. Exceeding bytes: 0x5401.
W: Invalid config flags detected: string-ERR8
W: Config flags size > 38. Exceeding bytes: 0xE401.
W: Invalid config flags detected: string-ERR9
W: Config flags size > 38. Exceeding bytes: 0x4F00.
W: Invalid config flags detected: string-ERR10
W: Config flags size > 38. Exceeding bytes: 0x4803.
W: Invalid config flags detected: string-ERR11
W: Config flags size > 38. Exceeding bytes: 0x9C00.
W: Invalid config flags detected: string-ERR12
W: Config flags size > 38. Exceeding bytes: 0x4803.
W: Invalid config flags detected: string-ERR13
Exception in thread "main" brut.androlib.AndrolibException: Multiple resources: spec=0x0104005f string/needPuk, config=[DEFAULT]
	at brut.androlib.res.data.ResConfig.addResource(ResConfig.java:63)
	at brut.androlib.res.data.ResConfig.addResource(ResConfig.java:56)
	at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:217)
	at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:188)
	at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:156)
	at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:113)
	at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:78)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:39)
	at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:678)
	at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:660)
	at brut.androlib.Androlib.installFramework(Androlib.java:641)
	at brut.apktool.Main.cmdInstallFramework(Main.java:240)
	at brut.apktool.Main.main(Main.java:87)

framework-res-hwext.apk
W: Config flags size > 38. Exceeding bytes: 0x9C00.
W: Invalid config flags detected: string-ERR0
W: Config flags size > 38. Exceeding bytes: 0x4803.
W: Invalid config flags detected: string-ERR1
Exception in thread "main" brut.androlib.AndrolibException: Multiple resources: spec=0x02020001 string/enterPuk, config=[DEFAULT]
	at brut.androlib.res.data.ResConfig.addResource(ResConfig.java:63)
	at brut.androlib.res.data.ResConfig.addResource(ResConfig.java:56)
	at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:217)
	at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:188)
	at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:156)
	at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:113)
	at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:78)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:39)
	at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:678)
	at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:660)
	at brut.androlib.Androlib.installFramework(Androlib.java:641)
	at brut.apktool.Main.cmdInstallFramework(Main.java:240)
	at brut.apktool.Main.main(Main.java:87)

- Volviendo al menú principal. [/code]

**Comment by iBotPeaches** [comment]
Huawei modifies the qualifiers at an OEM level, it doesn't match AOSP. Therefore is not supported.
