### ISSUE TITLE
Error while compiling aosp 5.1 

### ISSUE THREAD

**Issue by adityaakadynamo** [iBotPeaches/Apktool#912]
![apk](https://cloud.githubusercontent.com/assets/11988517/7196286/badf8744-e4ec-11e4-956b-9fbe4604b347.png)

Exception in thread "main" brut.androlib.AndrolibException: Invalid value type:
0
        at brut.androlib.res.data.value.ResValueFactory.factory(ResValueFactory.
java:64)
        at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:242)

        at brut.androlib.res.decoder.ARSCDecoder.readComplexEntry(ARSCDecoder.ja
va:230)
        at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:200)

        at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:188
)
        at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:156)
        at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:11
3)
        at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:78)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:39)
        at brut.androlib.res.AndrolibResources.installFramework(AndrolibResource
s.java:678)
        at brut.androlib.res.AndrolibResources.installFramework(AndrolibResource
s.java:660)
        at brut.androlib.Androlib.installFramework(Androlib.java:641)
        at brut.apktool.Main.cmdInstallFramework(Main.java:240)
        at brut.apktool.Main.main(Main.java:87)

Could Not Get it Done ,Need Help 
Searched it over , got this as the answer 

https://github.com/iBotPeaches/Apktool/commit/2db8828efb2b6a968fca11d153ea1276bfccdce5

Not able to locate the perfect file in it 
@iBotPeaches Look over it

**Comment by adityaakadynamo** [comment]
Got It working , Used another jar 



for those who getting the same error replace urs with it

**Comment by iBotPeaches** [comment]
Support for 5.1 was added here - https://github.com/iBotPeaches/Apktool/commit/2db8828efb2b6a968fca11d153ea1276bfccdce5
