### ISSUE TITLE
Exception in thread "main" brut.androlib.AndrolibException: Multiple resources:

### ISSUE THREAD

**Issue by jchjian** [iBotPeaches/Apktool#914]
when i execute apktool.jar if framework-res.apk, it have some error as below, also decode
```
Exception in thread "main" brut.androlib.AndrolibException: Multiple resources: spec=0x01040308 string/lockscreen_carrier_default, config=[DEFAULT]
	at brut.androlib.res.data.ResConfig.addResource(ResConfig.java:63)
	at brut.androlib.res.data.ResConfig.addResource(ResConfig.java:56)
	at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:218)
	at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:189)
	at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:157)
	at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:114)
	at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:78)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:39)
	at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:685)
	at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:667)
	at brut.androlib.Androlib.installFramework(Androlib.java:657)
	at brut.apktool.Main.cmdInstallFramework(Main.java:240)
	at brut.apktool.Main.main(Main.java:87)
```

i don't know how it can be fixed, maybe the framework-res is encrypted?
the framework-res.apk has been uploaded, https://github.com/jchjian/framework-res, can you help me? Thank you very much for helping!

**Comment by iBotPeaches** [comment]
This is usually an indication of broken qualifiers. I checked these out via `aapt d configurations framework-res.apk` and had quite a weird list of them.

```
ca-
ca-��
da
da
da-
da-��
fa
fa
fa-
fa-��
ja
ja
ja-
ja-
ja-��
es-��-US
es-	
es-�-US
lt-LT
```

As you can see we have some character combinations that aren't recognized properly. Can you give me any more details on what OEM / version / where this framework came from?

**Comment by jchjian** [comment]
it cames from EMUI of huawei, the version is android 4.4

**Comment by iBotPeaches** [comment]
Hmm Huawei modifies AOSP qualifiers which is why this isn't working. I usually close these bugs as `wont-fix`, but I'll send an email to Huawei and see if I can get an explanation of the qualifiers since I don't really want to blackbox research them.

**Comment by iBotPeaches** [comment]
Yeah they won't provide source.

I have no idea what the `otab` and `otaa` fields mean in these qualifiers. I could maybe reverse engineer a dump of their `aapt`, but this is outside of a basic apktool bug. This is non-standard, thus not supported.

Sorry! If you happen to find information on these qualifiers via Huawei, feel free to respond.
