### ISSUE TITLE
isProviderStringReplacementWorking test failing on OS X

### ISSUE THREAD

**Issue by Benjamin-Dobell** [iBotPeaches/Apktool#918]
```
brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/var/folders/_n/gbbjzzmn5xx8nkh4k6hh8r4w0000gn/T/brut_util_Jar_4793197039505019454.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 22, --version-code, 1, --version-name, 1.0, -F, /var/folders/_n/gbbjzzmn5xx8nkh4k6hh8r4w0000gn/T/APKTOOL5777628875569945025.tmp, -0, arsc, -I, /Users/ben/Library/apktool/framework/1.apk, -S, /var/folders/_n/gbbjzzmn5xx8nkh4k6hh8r4w0000gn/T/BRUT6885194488963012093.tmp/issue636.apk.out/res, -M, /var/folders/_n/gbbjzzmn5xx8nkh4k6hh8r4w0000gn/T/BRUT6885194488963012093.tmp/issue636.apk.out/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:458)
	at brut.androlib.Androlib.buildResources(Androlib.java:396)
	at brut.androlib.Androlib.build(Androlib.java:285)
	at brut.androlib.ProviderAttributeTest.isProviderStringReplacementWorking(ProviderAttributeTest.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:355)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/var/folders/_n/gbbjzzmn5xx8nkh4k6hh8r4w0000gn/T/brut_util_Jar_4793197039505019454.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 22, --version-code, 1, --version-name, 1.0, -F, /var/folders/_n/gbbjzzmn5xx8nkh4k6hh8r4w0000gn/T/APKTOOL5777628875569945025.tmp, -0, arsc, -I, /Users/ben/Library/apktool/framework/1.apk, -S, /var/folders/_n/gbbjzzmn5xx8nkh4k6hh8r4w0000gn/T/BRUT6885194488963012093.tmp/issue636.apk.out/res, -M, /var/folders/_n/gbbjzzmn5xx8nkh4k6hh8r4w0000gn/T/BRUT6885194488963012093.tmp/issue636.apk.out/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:444)
	... 47 more
Caused by: brut.common.BrutException: could not exec command: [/var/folders/_n/gbbjzzmn5xx8nkh4k6hh8r4w0000gn/T/brut_util_Jar_4793197039505019454.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 22, --version-code, 1, --version-name, 1.0, -F, /var/folders/_n/gbbjzzmn5xx8nkh4k6hh8r4w0000gn/T/APKTOOL5777628875569945025.tmp, -0, arsc, -I, /Users/ben/Library/apktool/framework/1.apk, -S, /var/folders/_n/gbbjzzmn5xx8nkh4k6hh8r4w0000gn/T/BRUT6885194488963012093.tmp/issue636.apk.out/res, -M, /var/folders/_n/gbbjzzmn5xx8nkh4k6hh8r4w0000gn/T/BRUT6885194488963012093.tmp/issue636.apk.out/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:90)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:413)
	... 48 more
```

**Comment by iBotPeaches** [comment]
hmm. I didn't experience this when I tested on osx. Can you run with `--info` and post the last 50ish lines during failure?

**Comment by Benjamin-Dobell** [comment]
```
    Apr 20, 2015 2:42:58 PM brut.androlib.res.AndrolibResources installFramework
    INFO: Framework installed to: /var/folders/_n/gbbjzzmn5xx8nkh4k6hh8r4w0000gn/T/BRUT4595586164806822176.tmp/2-shared.apk
    Apr 20, 2015 2:42:58 PM brut.androlib.ApkDecoder decode
    INFO: Using Apktool 2.0.0-d76d7d-SNAPSHOT on client.apk
    Apr 20, 2015 2:42:58 PM brut.androlib.res.AndrolibResources loadMainPkg
    INFO: Loading resource table...
    Apr 20, 2015 2:42:58 PM brut.androlib.res.decoder.ARSCDecoder readLibraryType
    INFO: Decoding Shared Library (com.google.android.test.shared_library), pkgId: 2
    Apr 20, 2015 2:42:58 PM brut.androlib.res.AndrolibResources decodeManifestWithResources
    INFO: Decoding AndroidManifest.xml with resources...
    Apr 20, 2015 2:42:58 PM brut.androlib.res.AndrolibResources loadFrameworkPkg
    INFO: Loading resource table from file: /var/folders/_n/gbbjzzmn5xx8nkh4k6hh8r4w0000gn/T/BRUT4595586164806822176.tmp/1.apk
    Apr 20, 2015 2:42:58 PM brut.androlib.res.AndrolibResources adjustPackageManifest
    INFO: Regular manifest package...
    Apr 20, 2015 2:42:58 PM brut.androlib.res.AndrolibResources decode
    INFO: Decoding file-resources...
    Apr 20, 2015 2:42:58 PM brut.androlib.res.AndrolibResources loadFrameworkPkg
    INFO: Loading resource table from file: /var/folders/_n/gbbjzzmn5xx8nkh4k6hh8r4w0000gn/T/BRUT4595586164806822176.tmp/2-shared.apk
    Apr 20, 2015 2:42:58 PM brut.androlib.res.AndrolibResources decode
    INFO: Decoding values */* XMLs...
    Apr 20, 2015 2:42:58 PM brut.androlib.Androlib decodeSourcesSmali
    INFO: Baksmaling classes.dex...
    Apr 20, 2015 2:42:58 PM brut.androlib.Androlib decodeRawFiles
    INFO: Copying assets and libs...
    Apr 20, 2015 2:42:58 PM brut.androlib.Androlib decodeUnknownFiles
    INFO: Copying unknown files...
    Apr 20, 2015 2:42:58 PM brut.androlib.Androlib writeOriginalFiles
    INFO: Copying original files...
    Apr 20, 2015 2:42:58 PM brut.androlib.ApkDecoder decode
    INFO: Using Apktool 2.0.0-d76d7d-SNAPSHOT on library.apk
    Apr 20, 2015 2:42:58 PM brut.androlib.res.AndrolibResources loadMainPkg
    INFO: Loading resource table...
    Apr 20, 2015 2:42:58 PM brut.androlib.res.AndrolibResources decodeManifestWithResources
    INFO: Decoding AndroidManifest.xml with resources...
    Apr 20, 2015 2:42:58 PM brut.androlib.res.AndrolibResources loadFrameworkPkg
    INFO: Loading resource table from file: /var/folders/_n/gbbjzzmn5xx8nkh4k6hh8r4w0000gn/T/BRUT4595586164806822176.tmp/1.apk
    Apr 20, 2015 2:42:58 PM brut.androlib.res.AndrolibResources adjustPackageManifest
    INFO: Regular manifest package...
    Apr 20, 2015 2:42:58 PM brut.androlib.res.AndrolibResources decode
    INFO: Decoding file-resources...
    Apr 20, 2015 2:42:58 PM brut.androlib.res.AndrolibResources decode
    INFO: Decoding values */* XMLs...
    Apr 20, 2015 2:42:58 PM brut.androlib.Androlib decodeSourcesSmali
    INFO: Baksmaling classes.dex...
    Apr 20, 2015 2:42:58 PM brut.androlib.Androlib decodeRawFiles
    INFO: Copying assets and libs...
    Apr 20, 2015 2:42:58 PM brut.androlib.Androlib decodeUnknownFiles
    INFO: Copying unknown files...
    Apr 20, 2015 2:42:58 PM brut.androlib.Androlib writeOriginalFiles
    INFO: Copying original files...
    Apr 20, 2015 2:42:58 PM brut.androlib.Androlib build
    INFO: Using Apktool 2.0.0-d76d7d-SNAPSHOT
    Apr 20, 2015 2:42:58 PM brut.androlib.Androlib buildSourcesSmali
    INFO: Checking whether sources has changed...
    Apr 20, 2015 2:42:58 PM brut.androlib.Androlib buildSourcesSmali
    INFO: Smaling smali folder into classes.dex...
    Apr 20, 2015 2:42:59 PM brut.androlib.Androlib buildResourcesFull
    INFO: Checking whether resources has changed...
    Apr 20, 2015 2:42:59 PM brut.androlib.Androlib buildResourcesFull
    INFO: Building resources...
    Apr 20, 2015 2:42:59 PM brut.androlib.Androlib buildApk
    INFO: Building apk file...
    Apr 20, 2015 2:42:59 PM brut.androlib.Androlib build
    INFO: Using Apktool 2.0.0-d76d7d-SNAPSHOT
    Apr 20, 2015 2:42:59 PM brut.androlib.Androlib buildSourcesSmali
    INFO: Checking whether sources has changed...
    Apr 20, 2015 2:42:59 PM brut.androlib.Androlib buildSourcesSmali
    INFO: Smaling smali folder into classes.dex...
    Apr 20, 2015 2:42:59 PM brut.androlib.Androlib buildResourcesFull
    INFO: Checking whether resources has changed...
    Apr 20, 2015 2:42:59 PM brut.androlib.Androlib buildResourcesFull
    INFO: Building resources...
    Apr 20, 2015 2:42:59 PM brut.androlib.Androlib buildApk
    INFO: Building apk file...

brut.androlib.SharedLibraryTest > isFrameworkTaggingWorking STANDARD_ERROR
    Apr 20, 2015 2:42:59 PM brut.androlib.res.AndrolibResources installFramework
    INFO: Framework installed to: /var/folders/_n/gbbjzzmn5xx8nkh4k6hh8r4w0000gn/T/BRUT4595586164806822176.tmp/2-building.apk

brut.androlib.SharedLibraryTest > isFrameworkInstallingWorking STANDARD_ERROR
    Apr 20, 2015 2:42:59 PM brut.androlib.res.AndrolibResources installFramework
    INFO: Framework installed to: /var/folders/_n/gbbjzzmn5xx8nkh4k6hh8r4w0000gn/T/BRUT4595586164806822176.tmp/2.apk
Gradle Test Executor 1 finished executing tests.

54 tests completed, 1 failed
Finished generating test XML results (0.015 secs) into: /Users/ben/Development/Apktool/brut.apktool/apktool-lib/build/test-results
Generating HTML test report...
Finished generating test html results (0.029 secs) into: /Users/ben/Development/Apktool/brut.apktool/apktool-lib/build/reports/tests
:brut.apktool:apktool-lib:test FAILED
:brut.apktool:apktool-lib:test (Thread[main,5,main]) completed. Took 4.272 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':brut.apktool:apktool-lib:test'.
> There were failing tests. See the report at: file:///Users/ben/Development/Apktool/brut.apktool/apktool-lib/build/reports/tests/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

Total time: 15.564 secs
Stopped 0 compiler daemon(s).
BenMBPR:Apktool ben$ ./gradlew build fatJar --info &> ERRRRRR
BenMBPR:Apktool ben$ tail -n 50 ERRRRRR 
    Apr 20, 2015 2:43:44 PM brut.androlib.Androlib decodeUnknownFiles
    INFO: Copying unknown files...
    Apr 20, 2015 2:43:44 PM brut.androlib.Androlib writeOriginalFiles
    INFO: Copying original files...
    Apr 20, 2015 2:43:44 PM brut.androlib.Androlib build
    INFO: Using Apktool 2.0.0-d76d7d-SNAPSHOT
    Apr 20, 2015 2:43:44 PM brut.androlib.Androlib buildSourcesSmali
    INFO: Checking whether sources has changed...
    Apr 20, 2015 2:43:44 PM brut.androlib.Androlib buildSourcesSmali
    INFO: Smaling smali folder into classes.dex...
    Apr 20, 2015 2:43:44 PM brut.androlib.Androlib buildResourcesFull
    INFO: Checking whether resources has changed...
    Apr 20, 2015 2:43:44 PM brut.androlib.Androlib buildResourcesFull
    INFO: Building resources...
    Apr 20, 2015 2:43:44 PM brut.androlib.Androlib buildApk
    INFO: Building apk file...
    Apr 20, 2015 2:43:44 PM brut.androlib.Androlib build
    INFO: Using Apktool 2.0.0-d76d7d-SNAPSHOT
    Apr 20, 2015 2:43:44 PM brut.androlib.Androlib buildSourcesSmali
    INFO: Checking whether sources has changed...
    Apr 20, 2015 2:43:44 PM brut.androlib.Androlib buildSourcesSmali
    INFO: Smaling smali folder into classes.dex...
    Apr 20, 2015 2:43:44 PM brut.androlib.Androlib buildResourcesFull
    INFO: Checking whether resources has changed...
    Apr 20, 2015 2:43:44 PM brut.androlib.Androlib buildResourcesFull
    INFO: Building resources...
    Apr 20, 2015 2:43:44 PM brut.androlib.Androlib buildApk
    INFO: Building apk file...
Gradle Test Executor 1 finished executing tests.

54 tests completed, 1 failed
Finished generating test XML results (0.014 secs) into: /Users/ben/Development/Apktool/brut.apktool/apktool-lib/build/test-results
Generating HTML test report...
Finished generating test html results (0.031 secs) into: /Users/ben/Development/Apktool/brut.apktool/apktool-lib/build/reports/tests
:brut.apktool:apktool-lib:test FAILED
:brut.apktool:apktool-lib:test (Thread[main,5,main]) completed. Took 3.484 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':brut.apktool:apktool-lib:test'.
> There were failing tests. See the report at: file:///Users/ben/Development/Apktool/brut.apktool/apktool-lib/build/reports/tests/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

Total time: 11.987 secs
Stopped 0 compiler daemon(s).
```

**Comment by Benjamin-Dobell** [comment]
Sorry, this is probably more useful:

```
    INFO: Building resources...
    /var/folders/_n/gbbjzzmn5xx8nkh4k6hh8r4w0000gn/T/BRUT6417073804122197419.tmp/issue636.apk.out/res/values-v21/styles.xml:3: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Widget.TextSuggestionsPopupWindow'.


brut.androlib.ProviderAttributeTest > isProviderStringReplacementWorking FAILED
    brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/var/folders/_n/gbbjzzmn5xx8nkh4k6hh8r4w0000gn/T/brut_util_Jar_7350132307904860385.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 22, --version-code, 1, --version-name, 1.0, -F, /var/folders/_n/gbbjzzmn5xx8nkh4k6hh8r4w0000gn/T/APKTOOL2573752017852471637.tmp, -0, arsc, -I, /Users/ben/Library/apktool/framework/1.apk, -S, /var/folders/_n/gbbjzzmn5xx8nkh4k6hh8r4w0000gn/T/BRUT6417073804122197419.tmp/issue636.apk.out/res, -M, /var/folders/_n/gbbjzzmn5xx8nkh4k6hh8r4w0000gn/T/BRUT6417073804122197419.tmp/issue636.apk.out/AndroidManifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:458)
        at brut.androlib.Androlib.buildResources(Androlib.java:396)
        at brut.androlib.Androlib.build(Androlib.java:285)
        at brut.androlib.ProviderAttributeTest.isProviderStringReplacementWorking(ProviderAttributeTest.java:59)

        Caused by:
        brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/var/folders/_n/gbbjzzmn5xx8nkh4k6hh8r4w0000gn/T/brut_util_Jar_7350132307904860385.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 22, --version-code, 1, --version-name, 1.0, -F, /var/folders/_n/gbbjzzmn5xx8nkh4k6hh8r4w0000gn/T/APKTOOL2573752017852471637.tmp, -0, arsc, -I, /Users/ben/Library/apktool/framework/1.apk, -S, /var/folders/_n/gbbjzzmn5xx8nkh4k6hh8r4w0000gn/T/BRUT6417073804122197419.tmp/issue636.apk.out/res, -M, /var/folders/_n/gbbjzzmn5xx8nkh4k6hh8r4w0000gn/T/BRUT6417073804122197419.tmp/issue636.apk.out/AndroidManifest.xml]
            at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)
            at brut.androlib.Androlib.buildResourcesFull(Androlib.java:444)
            ... 3 more

            Caused by:
            brut.common.BrutException: could not exec command: [/var/folders/_n/gbbjzzmn5xx8nkh4k6hh8r4w0000gn/T/brut_util_Jar_7350132307904860385.tmp, p, --forced-package-id, 127, --min-sdk-version, 21, --target-sdk-version, 22, --version-code, 1, --version-name, 1.0, -F, /var/folders/_n/gbbjzzmn5xx8nkh4k6hh8r4w0000gn/T/APKTOOL2573752017852471637.tmp, -0, arsc, -I, /Users/ben/Library/apktool/framework/1.apk, -S, /var/folders/_n/gbbjzzmn5xx8nkh4k6hh8r4w0000gn/T/BRUT6417073804122197419.tmp/issue636.apk.out/res, -M, /var/folders/_n/gbbjzzmn5xx8nkh4k6hh8r4w0000gn/T/BRUT6417073804122197419.tmp/issue636.apk.out/AndroidManifest.xml]
                at brut.util.OS.exec(OS.java:90)
                at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:413)
                ... 4 more

brut.androlib.SharedLibraryTest > isFrameworkTaggingWorking STANDARD_ERROR
    Apr 20, 2015 2:45:26 PM brut.androlib.res.AndrolibResources installFramework
    INFO: Framework installed to: /var/folders/_n/gbbjzzmn5xx8nkh4k6hh8r4w0000gn/T/BRUT8603040101517253244.tmp/2-building.apk
```

**Comment by iBotPeaches** [comment]
Wherever apktool stores its framework files, on osx usually `$HOME/Library/apktool/framework`. Can you delete the `1.apk` file in there and try the build again? I have a strange idea that the latest "test apk" I used was built on the newest API, thus if a framework file is outdated it will fail the build.

**Comment by iBotPeaches** [comment]
Had this exact error on an old system. Turns out one of the test case APKs I added was API21, which required a framework update (If you didn't have a new one) like listed above.

That solved it for me, so closing this. Let me know if this doesn't appear to be the case for you.

**Comment by Benjamin-Dobell** [comment]
@iBotPeaches After fixing #949 with https://github.com/JesusFreke/smali/pull/290 I ran into this again. So I followed your advice and deleted  ```$HOME/Library/apktool/framework/1.apk```. I can now confirm that was indeed the was the source of the problem on my machine, thanks!
