### ISSUE TITLE
Please support LG G*

### ISSUE THREAD

**Issue by hoangnova** [iBotPeaches/Apktool#919]
Hello, 
I'm trying to decompile LG G* apk it doesnt work.

D:\Dev\apktool>apktool.bat if D:\Dev\apktool\g*\framework-res.apk
Exception in thread "main" brut.androlib.AndrolibException: Invalid value type:
0
        at brut.androlib.res.data.value.ResValueFactory.factory(ResValueFactory.
java:64)
        at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:242)

        at brut.androlib.res.decoder.ARSCDecoder.readComplexEntry(ARSCDecoder.ja
va:230)
        at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:200)

        at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:188
)
        at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:156)
        at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:11
3)
        at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:78)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:39)
        at brut.androlib.res.AndrolibResources.installFramework(AndrolibResource

**Comment by iBotPeaches** [comment]
Fixed here: https://github.com/iBotPeaches/Apktool/commit/2db8828efb2b6a968fca11d153ea1276bfccdce5

New version will be out tomorrow.
