### ISSUE TITLE
Apktool craps out on Android for Work APK

### ISSUE THREAD

**Issue by archon810** [iBotPeaches/Apktool#920]
http://www.apkmirror.com/apk/google-inc/android-for-work-app/android-work-app-1-1-0-android-apk-download/

Lots of errors here with 2.0RC4.

```
Error occurred while disassembling class Lcom.google.android.apps.work.common.sd
k.security.AfwAppKeyStore$State; - skipping class
org.jf.util.ExceptionWithContext: Invalid annotation visibility 161
        at org.jf.dexlib2.AnnotationVisibility.getVisibility(AnnotationVisibilit
y.java:45)
        at org.jf.baksmali.Adaptors.AnnotationFormatter.writeTo(AnnotationFormat
ter.java:60)
        at org.jf.baksmali.Adaptors.AnnotationFormatter.writeTo(AnnotationFormat
ter.java:53)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeAnnotations(ClassDefini
tion.java:174)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java
:109)
        at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:226)
        at org.jf.baksmali.baksmali.access$000(baksmali.java:56)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:150)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:148)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)



Error occurred while disassembling class Lcom.google.android.apps.work.common.sd
k.security.AfwAppKeyChainExceptionImpl; - skipping class


Error occurred while disassembling class Lcom.google.android.apps.work.common.sd
k.security.AfwAppKeyChainAliasCallbackImpl; - skipping class


Error occurred while disassembling class Lcom.google.android.apps.work.common.sd
k.security.IKeyChainAliasCallback; - skipping class
java.lang.IllegalArgumentException: bad utf-8 byte 00 at offset 0006afa0
        at org.jf.util.Utf8Utils.throwBadUtf8(Utf8Utils.java:283)
        at org.jf.util.Utf8Utils.utf8BytesWithUtf16LengthToString(Utf8Utils.java
:210)
        at org.jf.dexlib2.dexbacked.BaseDexReader.readString(BaseDexReader.java:
514)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile.getString(DexBackedDexFile.
java:236)
        at org.jf.dexlib2.dexbacked.DexBackedMethod.getName(DexBackedMethod.java
:113)
        at org.jf.dexlib2.immutable.reference.ImmutableMethodReference.of(Immuta
bleMethodReference.java:74)
        at org.jf.dexlib2.dexbacked.DexBackedClassDef$5$1.readNextItem(DexBacked
ClassDef.java:366)
        at org.jf.dexlib2.dexbacked.DexBackedClassDef$5$1.readNextItem(DexBacked
ClassDef.java:350)
        at org.jf.dexlib2.dexbacked.util.VariableSizeLookaheadIterator.computeNe
xt(VariableSizeLookaheadIterator.java:60)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractI
terator.java:143)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.j
ava:138)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeVirtualMethods(ClassDef
inition.java:300)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java
:113)
        at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:226)
        at org.jf.baksmali.baksmali.access$000(baksmali.java:56)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:150)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:148)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
org.jf.dexlib2.dexbacked.DexBackedDexFile$InvalidItemIndex: Field index out of b
ounds: 65537
        at org.jf.dexlib2.dexbacked.DexBackedDexFile.getFieldIdItemOffset(DexBac
kedDexFile.java:180)
        at org.jf.dexlib2.dexbacked.DexBackedField.getFieldIdItemOffset(DexBacke
dField.java:130)
        at org.jf.dexlib2.dexbacked.DexBackedField.getName(DexBackedField.java:9
6)
        at org.jf.dexlib2.immutable.reference.ImmutableFieldReference.of(Immutab
leFieldReference.java:57)
        at org.jf.dexlib2.dexbacked.DexBackedClassDef$3$1.readNextItem(DexBacked
ClassDef.java:241)
        at org.jf.dexlib2.dexbacked.DexBackedClassDef$3$1.readNextItem(DexBacked
ClassDef.java:224)
        at org.jf.dexlib2.dexbacked.util.VariableSizeLookaheadIterator.computeNe
xt(VariableSizeLookaheadIterator.java:60)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractI
terator.java:143)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.j
ava:138)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeInstanceFields(ClassDef
inition.java:224)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java
:111)
        at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:226)
        at org.jf.baksmali.baksmali.access$000(baksmali.java:56)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:150)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:148)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

org.jf.util.ExceptionWithContext: Invalid annotation visibility 164
        at org.jf.dexlib2.AnnotationVisibility.getVisibility(AnnotationVisibilit
y.java:45)
        at org.jf.baksmali.Adaptors.AnnotationFormatter.writeTo(AnnotationFormat
ter.java:60)
        at org.jf.baksmali.Adaptors.AnnotationFormatter.writeTo(AnnotationFormat
ter.java:53)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeAnnotations(ClassDefini
tion.java:174)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java
:109)
        at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:226)
        at org.jf.baksmali.baksmali.access$000(baksmali.java:56)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:150)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:148)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)



Error occurred while disassembling class Ldalvik.system.BlockGuard; - skipping c
lass


Error occurred while disassembling class Ldalvik.system.BlockGuard$Policy; - ski
pping class
org.jf.util.ExceptionWithContext: Invalid annotation visibility 164
        at org.jf.dexlib2.AnnotationVisibility.getVisibility(AnnotationVisibilit
y.java:45)
        at org.jf.baksmali.Adaptors.AnnotationFormatter.writeTo(AnnotationFormat
ter.java:60)
        at org.jf.baksmali.Adaptors.AnnotationFormatter.writeTo(AnnotationFormat
ter.java:53)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeAnnotations(ClassDefini
tion.java:174)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java
:109)
        at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:226)
        at org.jf.baksmali.baksmali.access$000(baksmali.java:56)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:150)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:148)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

org.jf.util.ExceptionWithContext: Invalid annotation visibility 161
        at org.jf.dexlib2.AnnotationVisibility.getVisibility(AnnotationVisibilit
y.java:45)
        at org.jf.baksmali.Adaptors.AnnotationFormatter.writeTo(AnnotationFormat
ter.java:60)
        at org.jf.baksmali.Adaptors.AnnotationFormatter.writeTo(AnnotationFormat
ter.java:53)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeAnnotations(ClassDefini
tion.java:174)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java
:109)
        at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:226)
        at org.jf.baksmali.baksmali.access$000(baksmali.java:56)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:150)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:148)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)



Error occurred while disassembling class Lcom.google.android.apps.work.common.sd
k.utils.AfwAppLogImpl; - skipping class
java.lang.IllegalArgumentException: bad utf-8 byte 00 at offset 000679b9
        at org.jf.util.Utf8Utils.throwBadUtf8(Utf8Utils.java:283)
        at org.jf.util.Utf8Utils.utf8BytesWithUtf16LengthToString(Utf8Utils.java
:210)
        at org.jf.dexlib2.dexbacked.BaseDexReader.readString(BaseDexReader.java:
514)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile.getString(DexBackedDexFile.
java:236)
        at org.jf.dexlib2.dexbacked.DexBackedField.getName(DexBackedField.java:9
6)
        at org.jf.dexlib2.immutable.reference.ImmutableFieldReference.of(Immutab
leFieldReference.java:57)
        at org.jf.dexlib2.dexbacked.DexBackedClassDef$3$1.readNextItem(DexBacked
ClassDef.java:241)
        at org.jf.dexlib2.dexbacked.DexBackedClassDef$3$1.readNextItem(DexBacked
ClassDef.java:224)
        at org.jf.dexlib2.dexbacked.util.VariableSizeLookaheadIterator.computeNe
xt(VariableSizeLookaheadIterator.java:60)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractI
terator.java:143)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.j
ava:138)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeInstanceFields(ClassDef
inition.java:224)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java
:111)
        at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:226)
        at org.jf.baksmali.baksmali.access$000(baksmali.java:56)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:150)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:148)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)


Error occurred while disassembling class Lorg.apache.harmony.security.utils.AlgN
ameMapper; - skipping class


Error occurred while disassembling class Ldividelibcore.io.IoUtils; - skipping c
lass
org.jf.dexlib2.dexbacked.DexBackedDexFile$InvalidItemIndex: Field index out of b
ounds: 65538
        at org.jf.dexlib2.dexbacked.DexBackedDexFile.getFieldIdItemOffset(DexBac
kedDexFile.java:180)
        at org.jf.dexlib2.dexbacked.DexBackedField.getFieldIdItemOffset(DexBacke
dField.java:130)
        at org.jf.dexlib2.dexbacked.DexBackedField.getName(DexBackedField.java:9
6)
        at org.jf.dexlib2.immutable.reference.ImmutableFieldReference.of(Immutab
leFieldReference.java:57)
        at org.jf.dexlib2.dexbacked.DexBackedClassDef$3$1.readNextItem(DexBacked
ClassDef.java:241)
        at org.jf.dexlib2.dexbacked.DexBackedClassDef$3$1.readNextItem(DexBacked
ClassDef.java:224)
        at org.jf.dexlib2.dexbacked.util.VariableSizeLookaheadIterator.computeNe
xt(VariableSizeLookaheadIterator.java:60)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractI
terator.java:143)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.j
ava:138)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeInstanceFields(ClassDef
inition.java:224)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java
:111)
        at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:226)
        at org.jf.baksmali.baksmali.access$000(baksmali.java:56)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:150)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:148)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

java.lang.IllegalArgumentException: bad utf-8 byte 00 at offset 000679b9
        at org.jf.util.Utf8Utils.throwBadUtf8(Utf8Utils.java:283)
        at org.jf.util.Utf8Utils.utf8BytesWithUtf16LengthToString(Utf8Utils.java
:210)
        at org.jf.dexlib2.dexbacked.BaseDexReader.readString(BaseDexReader.java:
514)
        at org.jf.dexlib2.dexbacked.DexBackedDexFile.getString(DexBackedDexFile.
java:236)
        at org.jf.dexlib2.dexbacked.DexBackedField.getName(DexBackedField.java:9
6)
        at org.jf.dexlib2.immutable.reference.ImmutableFieldReference.of(Immutab
leFieldReference.java:57)
        at org.jf.dexlib2.dexbacked.DexBackedClassDef$3$1.readNextItem(DexBacked
ClassDef.java:241)
        at org.jf.dexlib2.dexbacked.DexBackedClassDef$3$1.readNextItem(DexBacked
ClassDef.java:224)
        at org.jf.dexlib2.dexbacked.util.VariableSizeLookaheadIterator.computeNe
xt(VariableSizeLookaheadIterator.java:60)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractI
terator.java:143)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.j
ava:138)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeInstanceFields(ClassDef
inition.java:224)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java
:111)
        at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:226)
        at org.jf.baksmali.baksmali.access$000(baksmali.java:56)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:150)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:148)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by iBotPeaches** [comment]
Yeah I duplicated with current apktool. I then re-synced up to newest smali and tried that. No errors. 

I don't like merging in unreleased smali builds, so the instant @JesusFreke cuts a `2.0.6` release for smali, we can get this fixed.

**Comment by JesusFreke** [comment]
I've been meaning to do a release, just hadn't got around to it. I'll try and do one this week

**Comment by JesusFreke** [comment]
2.0.6 has been released :)

**Comment by iBotPeaches** [comment]
Thanks!

Merged in - 1fb87e3e4c1fc7b503ada47ca5607dfbef21eecav

Will be in 2.0.1.
