### ISSUE TITLE
Error when trying to decompile.

### ISSUE THREAD

**Issue by VileRegEx** [iBotPeaches/Apktool#925]
Wed 04/22/2015 
15:50:41.85 
Decompiling.. 
 
I: Baksmaling...
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:56)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:390)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:56)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:48)
	at brut.androlib.Androlib.getResTable(Androlib.java:48)
	at brut.androlib.ApkDecoder.getResTable(ApkDecoder.java:166)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:99)
	at brut.apktool.Main.cmdDecode(Main.java:131)
	at brut.apktool.Main.main(Main.java:68)
Caused by: java.io.IOException: Expected: 0x001c0001, got: 0x00000000
	at brut.util.ExtDataInput.skipCheckInt(ExtDataInput.java:48)
	at brut.androlib.res.decoder.StringBlock.read(StringBlock.java:44)
	at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:98)
	at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:83)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:49)
	... 8 more

**Comment by iBotPeaches** [comment]
For issues like this. It would help to upload an APK to some file hosting site and provide the link. This issue can be because of a thousand different things.

I'll re-open the bug for investigation if you can provide an apk.
