### ISSUE TITLE
Error while decompiling

### ISSUE THREAD

**Issue by AndyFresh** [iBotPeaches/Apktool#945]
Hi. I try to decompile an apk, but exception is appear.

Using Apktool 2.0.0 on Win7 x64.

D:\Media\android\apktool>apktool decode nova.apk
I: Using Apktool 2.0.0 on nova.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\username\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
W: Could not decode attr value, using undecoded value instead: ns=android, name=touchscreenBlocksFocus, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=strokeAlpha, value=0x3dcccccd
W: Could not decode attr value, using undecoded value instead: ns=android, name=fillAlpha, value=0x3dcccccd
W: Could not decode attr value, using undecoded value instead: ns=android, name=strokeAlpha, value=0x3e4ccccd
W: Could not decode attr value, using undecoded value instead: ns=android, name=fillAlpha, value=0x3e4ccccd
I: Decoding values */* XMLs...
Exception in thread "main" brut.androlib.err.UndefinedResObject: resource spec: 0x010104ce
        at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
        at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:65)
        at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:61)
        at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferenceValue.java:57)
        at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:54)
        at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:496)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:252)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:134)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:104)
        at brut.apktool.Main.cmdDecode(Main.java:165)
        at brut.apktool.Main.main(Main.java:81)

**Comment by iBotPeaches** [comment]
Read this - http://ibotpeaches.github.io/Apktool/documentation/#framework-files

Based on this

```
W: Could not decode attr value, using undecoded value instead: ns=android, name=touchscreenBlocksFocus, value=0xffffffff
```

I know your frameworks are out of date, so delete the file at `$HOME/apktool/framework/1.apk` and try again. Assuming you are using 2.0.0.
