### ISSUE TITLE
UndefinedResObject for android vending app

### ISSUE THREAD

**Issue by dweinstein** [iBotPeaches/Apktool#946]
@iBotPeaches 

``` 
% java -jar Apktool/brut.apktool/apktool-cli/build/libs/apktool-cli.jar d --no-src ~/android/apks/com.android.vending-5.0.37-80300037-minAPI9.apk
I: Using Apktool 2.0.1-825476-SNAPSHOT on com.android.vending-5.0.37-80300037-minAPI9.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /Users/user/Library/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
Exception in thread "main" brut.androlib.err.UndefinedResObject: resource spec: 0x01010462
        at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
        at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:65)
        at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:61)
        at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferenceValue.java:57)
        at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:54)
        at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:496)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:252)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:134)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:104)
        at brut.apktool.Main.cmdDecode(Main.java:165)
        at brut.apktool.Main.main(Main.java:81)
java -jar Apktool/brut.apktool/apktool-cli/build/libs/apktool-cli.jar d    5.20s user 0.61s system 147% cpu 3.933 total
```

**Comment by iBotPeaches** [comment]
```
ibotpeaches@raganok:~/Downloads/Apktool/Bug946$ apktool d -s com.android.vending-5.0.37-80300037-minAPI9.apk
I: Using Apktool 2.0.1-1fb87e-SNAPSHOT on com.android.vending-5.0.37-80300037-minAPI9.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying raw classes.dex file...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
ibotpeaches@raganok:~/Downloads/Apktool/Bug946$ 
```

http://ibotpeaches.github.io/Apktool/documentation/#framework-files - I think your `1.apk` is out of date. Try deleting `$HOME/apktool/framework/1.apk` and try again.
