### ISSUE TITLE
:brut.apktool.smali:dexlib2:test FAILED when compiling repo

### ISSUE THREAD

**Issue by raziel23x** [iBotPeaches/Apktool#947]
org.jf.dexlib2.AccessorTest > testAccessors FAILED
    junit.framework.AssertionFailedError: expected:<12> but was:<1>
        at junit.framework.Assert.fail(Assert.java:47)
        at junit.framework.Assert.failNotEquals(Assert.java:277)
        at junit.framework.Assert.assertEquals(Assert.java:64)
        at junit.framework.Assert.assertEquals(Assert.java:195)
        at junit.framework.Assert.assertEquals(Assert.java:201)
        at org.jf.dexlib2.AccessorTest.testAccessors(AccessorTest.java:125)

105 tests completed, 1 failed
:brut.apktool.smali:dexlib2:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':brut.apktool.smali:dexlib2:test'.

**Comment by iBotPeaches** [comment]
Can't duplicate here. Test is from smali anyhow.

**Comment by raziel23x** [comment]
I have just did a clean install of Ubuntu 14.04.2 and tried to build and gotten the same error as my windows

**Comment by Benjamin-Dobell** [comment]
Same error on Mac OS X - investigating further...
