### ISSUE TITLE
The Twitter app does not rebuild

### ISSUE THREAD

**Issue by Fi5t** [iBotPeaches/Apktool#950]
When I try to decompile and build Twitter app I see such log (apktool v2.0.0)
```bash
user@host:~/tools/apktool$ java -jar apktool.jar d -d ./twitter.apk -o ./out
I: Using Apktool 2.0.0 on twitter.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/user/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
user@host:~/tools/apktool$ java -jar apktool.jar b -d ./out -o twitter-debug.apk
I: Using Apktool 2.0.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
/home/user/tools/apktool/./out/res/values-v21/styles.xml:7: error: Error: No resource found that matches the given name: attr 'android:state_accessibility_focused'.

/home/user/tools/apktool/./out/res/values-v21/styles.xml:13: error: Error: No resource found that matches the given name: attr 'android:internalMaxWidth'.

/home/user/tools/apktool/./out/res/values-v21/styles.xml:12: error: Error: No resource found that matches the given name: attr 'android:majorWeightMax'.

/home/user/tools/apktool/./out/res/values-v21/styles.xml:19: error: Error: No resource found that matches the given name: attr 'android:state_accessibility_focused'.

/home/user/tools/apktool/./out/res/values-v21/styles.xml:30: error: Error: No resource found that matches the given name: attr 'android:glowRadius'.

/home/user/tools/apktool/./out/res/values-v21/styles.xml:29: error: Error: No resource found that matches the given name: attr 'android:pointDrawable'.

/home/user/tools/apktool/./out/res/values-v21/styles.xml:33: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Preference.Holo.RingtonePreference'.

/home/user/tools/apktool/./out/res/values-v21/styles.xml:45: error: Error: No resource found that matches the given name: attr 'android:glowRadius'.

/home/user/tools/apktool/./out/res/values-v21/styles.xml:44: error: Error: No resource found that matches the given name: attr 'android:pointDrawable'.

/home/user/tools/apktool/./out/res/values-v21/styles.xml:54: error: Error: No resource found that matches the given name: attr 'android:pointDrawable'.

/home/user/tools/apktool/./out/res/values-v21/styles.xml:58: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Preference.Holo.DialogPreference.YesNoPreference'.

/home/user/tools/apktool/./out/res/values-v21/styles.xml:68: error: Error: No resource found that matches the given name: attr 'android:borderRight'.

/home/user/tools/apktool/./out/res/values-v21/styles.xml:71: error: Error: No resource found that matches the given name: attr 'android:disableChildrenWhenDisabled'.

/home/user/tools/apktool/./out/res/values-v21/styles.xml:74: error: Error: No resource found that matches the given name: attr 'android:glowRadius'.

/home/user/tools/apktool/./out/res/values-v21/styles.xml:72: error: Error: No resource found that matches the given name: attr 'android:internalLayout'.

/home/user/tools/apktool/./out/res/values-v21/styles.xml:69: error: Error: No resource found that matches the given name: attr 'android:layout_removeBorders'.

/home/user/tools/apktool/./out/res/values-v21/styles.xml:73: error: Error: No resource found that matches the given name: attr 'android:pointDrawable'.

/home/user/tools/apktool/./out/res/values-v21/styles.xml:70: error: Error: No resource found that matches the given name: attr 'android:preserveIconSpacing'.

/home/user/tools/apktool/./out/res/values-v21/styles.xml:67: error: Error: No resource found that matches the given name: attr 'android:progressLayout'.

/home/user/tools/apktool/./out/res/values-v21/styles.xml:66: error: Error: No resource found that matches the given name: attr 'android:searchResultListItemHeight'.

/home/user/tools/apktool/./out/res/values-v21/styles.xml:82: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/TextAppearance.NumPadKey'.

/home/user/tools/apktool/./out/res/values-v21/styles.xml:91: error: Error: No resource found that matches the given name: attr 'android:pointDrawable'.

/home/user/tools/apktool/./out/res/values-v21/styles.xml:93: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Preference.Holo.RingtonePreference'.

/home/user/tools/apktool/./out/res/values-v21/styles.xml:94: error: Error: No resource found that matches the given name: attr 'android:preserveIconSpacing'.

/home/user/tools/apktool/./out/res/values-v21/styles.xml:96: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/PreferencePanel'.

/home/user/tools/apktool/./out/res/values-v21/styles.xml:97: error: Error: No resource found that matches the given name: attr 'android:preserveIconSpacing'.

/home/user/tools/apktool/./out/res/values-v21/styles.xml:100: error: Error: No resource found that matches the given name: attr 'android:preserveIconSpacing'.

/home/user/tools/apktool/./out/res/values-v21/styles.xml:104: error: Error: No resource found that matches the given name: attr 'android:singleChoiceItemLayout'.

Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/tmp/brut_util_Jar_5363911800319896477.tmp, p, --debug-mode, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 21, --version-code, 4030820, --version-name, 5.58.0, -F, /tmp/APKTOOL361155088180307149.tmp, -0, arsc, -I, /home/user/apktool/framework/1.apk, -S, /home/user/tools/apktool/./out/res, -M, /home/user/tools/apktool/./out/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:458)
	at brut.androlib.Androlib.buildResources(Androlib.java:396)
	at brut.androlib.Androlib.build(Androlib.java:285)
	at brut.androlib.Androlib.build(Androlib.java:256)
	at brut.apktool.Main.cmdBuild(Main.java:225)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/tmp/brut_util_Jar_5363911800319896477.tmp, p, --debug-mode, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 21, --version-code, 4030820, --version-name, 5.58.0, -F, /tmp/APKTOOL361155088180307149.tmp, -0, arsc, -I, /home/user/apktool/framework/1.apk, -S, /home/user/tools/apktool/./out/res, -M, /home/user/tools/apktool/./out/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:444)
	... 5 more
Caused by: brut.common.BrutException: could not exec command: [/tmp/brut_util_Jar_5363911800319896477.tmp, p, --debug-mode, --forced-package-id, 127, --min-sdk-version, 14, --target-sdk-version, 21, --version-code, 4030820, --version-name, 5.58.0, -F, /tmp/APKTOOL361155088180307149.tmp, -0, arsc, -I, /home/user/apktool/framework/1.apk, -S, /home/user/tools/apktool/./out/res, -M, /home/user/tools/apktool/./out/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:89)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:413)
	... 6 more
```

**Comment by telkomsel13** [comment]
#0

**Comment by iBotPeaches** [comment]
```
ibotpeaches@raganok:~/Downloads/Apktool/Bug950$ apktool d com.twitter.android-5.59.0-4030821-minAPI14.apk 
I: Using Apktool 2.0.1-1fb87e-SNAPSHOT on com.twitter.android-5.59.0-4030821-minAPI14.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
ibotpeaches@raganok:~/Downloads/Apktool/Bug950$ apktool b com.twitter.android-5.59.0-4030821-minAPI14
I: Using Apktool 2.0.1-1fb87e-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
ibotpeaches@raganok:~/Downloads/Apktool/Bug950$ 
```

Couldn't duplicate with latest source & framework.

**Comment by Fi5t** [comment]
Works fine with lastest framework! Thank you!
