### ISSUE TITLE
Error for input '.p arameter': Invalid directive

### ISSUE THREAD

**Issue by rowan23uk** [iBotPeaches/Apktool#956]
I'm using a program that uses apktool 2.0.0.rc4.
It decompiles fine but when i recompile i get this error:

I: Using Apktool 2.0.0
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
FRamabind\smali\com\alephzain\framaroot\ycadklia.smali[47,4] Error for input '.p
arameter': Invalid directive
FRamabind\smali\com\alephzain\framaroot\ycadklia.smali[47,15] mismatched input '
"is"' expecting END_METHOD_DIRECTIVE
FRamabind\smali\com\alephzain\framaroot\ycadklia.smali[94,4] Error for input '.p
arameter': Invalid directive
FRamabind\smali\com\alephzain\framaroot\ycadklia.smali[95,4] Error for input '.p
arameter': Invalid directive
FRamabind\smali\com\alephzain\framaroot\ycadklia.smali[94,15] mismatched input '
"context"' expecting END_METHOD_DIRECTIVE
Exception in thread "main" brut.androlib.AndrolibException: Could not smali file
: com/alephzain/framaroot/ycadklia.smali
        at brut.androlib.src.SmaliBuilder.buildFile(SmaliBuilder.java:71)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:55)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:41)
        at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:371)
        at brut.androlib.Androlib.buildSources(Androlib.java:298)
        at brut.androlib.Androlib.build(Androlib.java:282)
        at brut.androlib.Androlib.build(Androlib.java:256)
        at brut.apktool.Main.cmdBuild(Main.java:225)
        at brut.apktool.Main.main(Main.java:84)

Ive been told its because the program originally uses apktool 1.5 (old software) to create smali's and its using apktool 2.0.0rc4 to recompile because i updated it. Apktool 1.5 doesn't work for me.

I read through your doc on your website and i don't know how to get it to recompile. Any advice?
I heard by using baksmali1.5.jar or something but i don't know how to use these. 
I cant find any information on it.

**Comment by iBotPeaches** [comment]
This is a bug tracker. Not support forum. The smali syntax you are using is probably the 1.5.x format, while 2.0.0 expects the new syntax.

Update your smali changes to the new syntax.

**Comment by rowan23uk** [comment]
Oh sorry. 
Errrr .... how do i do that?

**Comment by iBotPeaches** [comment]
Once again, use the forums or stackoverflow for help. This is a bug tracker.

Read the upgrade guide - https://code.google.com/p/smali/wiki/SmaliBaksmali20
