### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by amir1111** [iBotPeaches/Apktool#957]
have seen this issue mentioned in other places, but they are all marked as closed,
but I don't think it's resolved, because I have compiled and tried the latest version, and also tried different frameworks, but still couldn't get it to work

have put the apk here: 
====================
http://www.filedropper.com/comcarrotcarrotfantasy398

and here's the decompile output/errors:
===================================
```
I: Using Apktool 2.0.1-825476-SNAPSHOT on com.carrot.carrotfantasy_398.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Amir\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
Exception in thread "main" java.lang.ClassCastException: brut.androlib.res.data.
value.ResStyleValue cannot be cast to brut.androlib.res.data.value.ResAttr
        at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(Re
sStyleValue.java:65)
        at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResour
ces.java:496)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:252
)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:134)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:104)
        at brut.apktool.Main.cmdDecode(Main.java:165)
        at brut.apktool.Main.main(Main.java:81)
```

**Comment by iBotPeaches** [comment]
Confirmed.

**Comment by amir1111** [comment]
found another app that matches this error and uploaded it to 
http://www.filedropper.com/baoweiluobu2300_1

**Comment by amir1111** [comment]
has to do with the value -
0x01030007 style/Theme.NoTitleBar.Fullscreen (in both apps) - the address is for the second app

**Comment by cutler** [comment]
What time can solve?   2.0.1 still have this problem

**Comment by iBotPeaches** [comment]
```
ibotpeaches@tombstone:~/Downloads/Apktool/Bug957$ apktool debug d com.carrot.carrotfantasy_398.apk -f
I: Using Apktool 2.0.3-e7c1bc-SNAPSHOT on com.carrot.carrotfantasy_398.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
ibotpeaches@tombstone:~/Downloads/Apktool/Bug957$ apktool b com.carrot.carrotfantasy_398
I: Using Apktool 2.0.3-e7c1bc-SNAPSHOT
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
```

A bit late, but looks fixed.
