### ISSUE TITLE
Recompiled & Uninstallable app

### ISSUE THREAD

**Issue by amir1111** [iBotPeaches/Apktool#959]
the app itself is decompiled and built without any errors, but the final apk cannot be installed (after signing it of course, like I have done with other apps). the original works.
# I upload the apk to:

http://www.filedropper.com/shoujitianmao143
# the output is:

```
C:\apktool>java -jar apktool-cli.jar d -f shoujitianmao_143.apk
I: Using Apktool 2.0.1-825476-SNAPSHOT on shoujitianmao_143.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Amir\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
```

```
C:\apktool>java -jar apktool-cli.jar b -f shoujitianmao_143
I: Using Apktool 2.0.1-825476-SNAPSHOT
I: Smaling smali folder into classes.dex...
I: Building resources...
warning: string 'dummy_tip' has no default translation.
warning: string 'kakalib_ok' has no default translation.
I: Copying libs... (/lib)
I: Building apk file...
I: Copying unknown files/dir...
```

**Comment by iBotPeaches** [comment]
The upload is bad.

```
ibotpeaches@raganok:~/Downloads/Apktool/Bug959$ unzip shoujitianmao_143.apk 
Archive:  shoujitianmao_143.apk
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of shoujitianmao_143.apk or
        shoujitianmao_143.apk.zip, and cannot find shoujitianmao_143.apk.ZIP, period.
```

**Comment by amir1111** [comment]
sorry, reuploaded
http://www.filedropper.com/shoujitianmao143_1

**Comment by iBotPeaches** [comment]
```
D/Finsky  (20864): [1] PackageVerificationReceiver.onReceive: Verification requested, id = 6
D/Finsky  (20864): [1] WorkerTask.onPreExecute: Verification Requested for id = 6, data=file:///data/local/tmp/test.apk flags=112 fromVerificationActivity=false
D/Finsky  (20864): [9228] PackageVerificationService.getPackageInfo: Cannot read archive for file:///data/local/tmp/test.apk in request id=6
D/Finsky  (20864): [1] PackageVerificationReceiver.onReceive: Verification requested, id = 6
D/DefContainer(14065): Copying /data/local/tmp/test.apk to base.apk
W/PackageManager(  780): Failed parse during installPackageLI
W/PackageManager(  780): android.content.pm.PackageParser$PackageParserException: /data/app/vmdl975343093.tmp/base.apk (at Binary XML file line #107): <meta-data> requires an android:name attribute
W/PackageManager(  780): 	at android.content.pm.PackageParser.parseBaseApk(PackageParser.java:900)
W/PackageManager(  780): 	at android.content.pm.PackageParser.parseClusterPackage(PackageParser.java:806)
W/PackageManager(  780): 	at android.content.pm.PackageParser.parsePackage(PackageParser.java:770)
W/PackageManager(  780): 	at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:11220)
W/PackageManager(  780): 	at com.android.server.pm.PackageManagerService.access$2500(PackageManagerService.java:270)
W/PackageManager(  780): 	at com.android.server.pm.PackageManagerService$5.run(PackageManagerService.java:9292)
W/PackageManager(  780): 	at android.os.Handler.handleCallback(Handler.java:739)
W/PackageManager(  780): 	at android.os.Handler.dispatchMessage(Handler.java:95)
W/PackageManager(  780): 	at android.os.Looper.loop(Looper.java:135)
W/PackageManager(  780): 	at android.os.HandlerThread.run(HandlerThread.java:61)
W/PackageManager(  780): 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

Can confirm original works, but then rebuilt crashes. Might be a new restrictive `aapt`. Not sure yet.

**Comment by iBotPeaches** [comment]
Sorry 5+ years later. I don't have the application and not located in my Apktool folder on computer.

Closing.
