### ISSUE TITLE
Error occurred while disassembling class LHttpUtils.a; - skipping class

### ISSUE THREAD

**Issue by divensept33b1a0d349e** [iBotPeaches/Apktool#961]
Hi,

It seems I'm unable to decompile this APK properly and so when I try to recompile it obviously doesn't work.

# APK download
http://s1.music.126.net/download/android/CloudMusic_offcial_2.6.1.apk

# Cmd output excerpt
```
D:\Users\USERNAME\Desktop\Netease>apktool -d d version_2.6.1.apk
I: Using Apktool 2.0.0 on version_2.6.1.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\USERNAME\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...


Error occurred while disassembling class LHttpUtils.a; - skipping class
java.lang.ArrayIndexOutOfBoundsException: 4
        at org.jf.dexlib2.analysis.AnalyzedInstruction.setPostRegisterType(AnalyzedInstruction.java:220)
        at org.jf.dexlib2.analysis.MethodAnalyzer.setPostRegisterTypeAndPropagateChanges(MethodAnalyzer.java:341)
        at org.jf.dexlib2.analysis.MethodAnalyzer.setDestinationRegisterTypeAndPropagateChanges(MethodAnalyzer.java:332)
        at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeUnaryOp(MethodAnalyzer.java:1286)
        at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstruction(MethodAnalyzer.java:778)
        at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:202)
        at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:137)
        at org.jf.baksmali.Adaptors.MethodDefinition.addAnalyzedInstructionMethodItems(MethodDefinition.java:403)
        at org.jf.baksmali.Adaptors.MethodDefinition.getMethodItems(MethodDefinition.java:312)
        at org.jf.baksmali.Adaptors.MethodDefinition.writeTo(MethodDefinition.java:209)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeVirtualMethods(ClassDefinition.java:328)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:113)
        at org.jf.baksmali.baksmali.disassembleClass(baksmali.java:226)
        at org.jf.baksmali.baksmali.access$000(baksmali.java:56)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:150)
        at org.jf.baksmali.baksmali$1.call(baksmali.java:148)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

###### The full thing spans some 2400 lines and can be found here:
https://gist.github.com/divensept33b1a0d349e/8d51d99e7df698401729

**Comment by iBotPeaches** [comment]
Fixed during the merge of smali `2.0.6`. Will be in apktool `2.0.1`

```
ibotpeaches@raganok:~/Downloads/Apktool/Bug961$ apktool d CloudMusic_offcial_2.6.1.apk 
I: Using Apktool 2.0.1-1fb87e-SNAPSHOT on CloudMusic_offcial_2.6.1.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
```
