### ISSUE TITLE
Error installing framework

### ISSUE THREAD

**Issue by MorzeCBP** [iBotPeaches/Apktool#966]
Error LOG:
[*] Installing framework framework-res-hwext.apk
```
Exception in thread "main" brut.androlib.AndrolibException: Multiple resources: spec=0x02020010 string/wifi_switch_to_pdp_title, config=[DEFAULT]
	at brut.androlib.res.data.ResConfig.addResource(ResConfig.java:63)
	at brut.androlib.res.data.ResConfig.addResource(ResConfig.java:56)
	at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:218)
	at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:189)
	at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:157)
	at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:114)
	at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:78)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:39)
	at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:593)
	at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:575)
	at brut.androlib.Androlib.installFramework(Androlib.java:660)
	at brut.apktool.Main.cmdInstallFramework(Main.java:240)
	at brut.apktool.Main.main(Main.java:87)
```
[*] ---> Error installing framework framework-res-hwext.apk 
[*] Installing framework framework-res.apk
```
Exception in thread "main" brut.androlib.AndrolibException: Multiple resources: spec=0x01040308 string/lockscreen_carrier_default, config=[DEFAULT]
	at brut.androlib.res.data.ResConfig.addResource(ResConfig.java:63)
	at brut.androlib.res.data.ResConfig.addResource(ResConfig.java:56)
	at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:218)
	at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:189)
	at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:157)
	at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:114)
	at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:78)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:39)
	at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:593)
	at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:575)
	at brut.androlib.Androlib.installFramework(Androlib.java:660)
	at brut.apktool.Main.cmdInstallFramework(Main.java:240)
	at brut.apktool.Main.main(Main.java:87)
```
[*] ---> Error installing framework framework-res.apk

framework-res.apk:
http://dropmefiles.com/5wbsL

Apktool - 2.0.0
java - 8_45
Windows 7

Thanks

**Comment by iBotPeaches** [comment]
Is this from a Huwaei phone/rom?

Seems to have some unsupported qualifiers.

`aapt d configurations`

```
zh-CN
zh-
zh-
zh-\
zh-zH-CN
zh-��-CN
zh-��
hi-IN
```

**Comment by MorzeCBP** [comment]
Huawaei Honor 6 (model Н60-L02)

**Comment by iBotPeaches** [comment]
Took a look at this. Sorry but Huawaei is modifying AOSP, including the qualifiers. This makes it non-standard.

While MIUI (Xiaomi) also does this. They provided the source changes to `aapt`, so I could put those changes into Apktool. I have no idea who to reach out to at Huawaei about this, therefore it will not be supported.

Sorry bout that. You are free to investigate the qualifiers and provide information.
