### ISSUE TITLE
Not able to unpack the apk

### ISSUE THREAD

**Issue by AshiqKony** [iBotPeaches/Apktool#973]
I am having one apk which I am trying to unpack using apktool.

But it results in following exception .

   .    ------   ANDROID ------  7433678396762095618
	    
	    .    ------   ANDROID_TABLET ------  7433678416592764931
	    
		.    ------   ANDROID ------  7617584308649199702
		
				.  -    ANDROID - 7617584308649199702
		Warning: AndroidManifest.xml already defines versionCode (in http://schemas.android.com/apk/res/android); using existing value in manifest.
Warning: AndroidManifest.xml already defines versionName (in http://schemas.android.com/apk/res/android); using existing value in manifest.
Warning: AndroidManifest.xml already defines minSdkVersion (in http://schemas.android.com/apk/res/android); using existing value in manifest.
Warning: AndroidManifest.xml already defines targetSdkVersion (in http://schemas.android.com/apk/res/android); using existing value in manifest.

		.    ------   ANDROID ------  7618516158349579183
		W: Could not decode attr value, using undecoded value instead: ns=android, name=touchscreenBlocksFocus, value=0xffffffff
Exception in thread "main" brut.androlib.err.UndefinedResObject: resource spec: 0x0101048f
	at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:58)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:54)
	at brut.androlib.res.decoder.ResAttrDecoder.decode(ResAttrDecoder.java:36)
	at brut.androlib.res.decoder.AXmlResourceParser.getAttributeValue(AXmlResourceParser.java:369)
	at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValue(XmlPullParserDelegate.java:69)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
	at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:83)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:141)
	at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(ResStreamDecoderContainer.java:33)
	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:107)
	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:91)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:322)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:123)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:102)
	at brut.apktool.Main.cmdDecode(Main.java:170)
	at brut.apktool.Main.main(Main.java:86)

**Comment by iBotPeaches** [comment]
Please give a read here - http://ibotpeaches.github.io/Apktool/documentation/#framework-files

You need to delete the file at `$HOME/apktool/framework/1.apk` and try again.

**Comment by BurgerZ** [comment]
@iBotPeaches you have iron balls pointing users to the frameworks related part of docs every day :+1: )))

**Comment by raziel23x** [comment]
I agree out of habit every time i recompile the apktool SRC or ibot releases a new release i always delete the apktool/framework/1.apk
