### ISSUE TITLE
Can't rebuild ressources

### ISSUE THREAD

**Issue by derderder77** [iBotPeaches/Apktool#974]
VERSION 
apktool2.0.0rc4
OS
Debian ARM with Oracle JDK 7, chrooted on my android devices.

When I try to rebuild an apk, include a basic hello world, I have this error
 ```
 I: Using Apktool 2.0.0-RC4
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
I: Checking whether resources has changed...
I: Building resources...
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/tmp/brut_util_Jar_3812110238312493303.tmp, p, --forced-package-id, 127, --min-sdk-version, 7, --target-sdk-version, 13, --version-code, 37, --version-name, 1.2.5, -F, /tmp/APKTOOL7604849846941091900.tmp, -0, arsc, -I, /root/apktool/framework/1.apk, -S, /media/sdcard/algoid-apktool/res, -M, /media/sdcard/algoid-apktool/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:442)
	at brut.androlib.Androlib.buildResources(Androlib.java:379)
	at brut.androlib.Androlib.build(Androlib.java:282)
	at brut.androlib.Androlib.build(Androlib.java:255)
	at brut.apktool.Main.cmdBuild(Main.java:225)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/tmp/brut_util_Jar_3812110238312493303.tmp, p, --forced-package-id, 127, --min-sdk-version, 7, --target-sdk-version, 13, --version-code, 37, --version-name, 1.2.5, -F, /tmp/APKTOOL7604849846941091900.tmp, -0, arsc, -I, /root/apktool/framework/1.apk, -S, /media/sdcard/algoid-apktool/res, -M, /media/sdcard/algoid-apktool/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:504)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:428)
	... 5 more
Caused by: brut.common.BrutException: could not exec command: [/tmp/brut_util_Jar_3812110238312493303.tmp, p, --forced-package-id, 127, --min-sdk-version, 7, --target-sdk-version, 13, --version-code, 37, --version-name, 1.2.5, -F, /tmp/APKTOOL7604849846941091900.tmp, -0, arsc, -I, /root/apktool/framework/1.apk, -S, /media/sdcard/algoid-apktool/res, -M, /media/sdcard/algoid-apktool/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:89)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:498)
	... 6 more
/tmp/brut_util_Jar_3812110238312493303.tmp: 1: Syntax error: "(" unexpected
```
Sorry for bad english

**Comment by iBotPeaches** [comment]
Aapt isn't supported on ARM. This is unfortunate, but there are a great deal of features in aapt that during compilation on ARM have to be commented out for a successful compilation, therefore it is not supported.

You can try the aapt here, and reference it using the `-aapt` option = https://github.com/skyleecm/android-build-tools-for-arm/blob/master/out/host/linux-arm/bin/aapt
