### ISSUE TITLE
[ERROR][COMPILING] Help Please

### ISSUE THREAD

**Issue by spektro10** [iBotPeaches/Apktool#976]
Microsoft Windows [Versione 6.3.9600]
(c) 2013 Microsoft Corporation. Tutti i diritti riservati.
```
C:\Users\Riccardo\Desktop\origi (1)>java -jar apktool.jar d -s framework-res.apk
I: Using Apktool 2.0.0-RC4 on framework-res.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
```
```
C:\Users\Riccardo\Desktop\origi (1)>java -jar apktool.jar b framework-res
I: Using Apktool 2.0.0-RC4
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
warning: string 'default_audio_route_name_hdmi' has no default translation.
warning: string 'default_permission_group' has no default translation.
warning: string 'lockscreen_unlock_guide_text_multi_user' has no default transla
tion.
warning: string 'perms_hide' has no default translation.
warning: string 'perms_show_all' has no default translation.
warning: string 's_view_cover_shortcuts_camera_text' has no default translation.

warning: string 's_view_cover_shortcuts_music_player_text' has no default transl
ation.
warning: string 's_view_cover_shortcuts_quick_memo_text' has no default translat
ion.
warning: string 'tommorrow' has no default translation.
C:\Users\Riccardo\Desktop\origi (1)\framework-res\res\layout\keyguard_screen_pas
sword_landscape.xml:22: error: Error: No resource found that matches the given n
ame (at 'layout' with value '@layout/keyguard_transport_control').

C:\Users\Riccardo\Desktop\origi (1)\framework-res\res\layout\keyguard_screen_pas
sword_portrait.xml:22: error: Error: No resource found that matches the given na
me (at 'layout' with value '@layout/keyguard_transport_control').

C:\Users\Riccardo\Desktop\origi (1)\framework-res\res\layout\keyguard_screen_tab
_unlock.xml:23: error: Error: No resource found that matches the given name (at
'layout' with value '@layout/keyguard_transport_control').

C:\Users\Riccardo\Desktop\origi (1)\framework-res\res\layout\keyguard_screen_tab
_unlock_land.xml:17: error: Error: No resource found that matches the given name
 (at 'layout' with value '@layout/keyguard_transport_control').

C:\Users\Riccardo\Desktop\origi (1)\framework-res\res\layout\keyguard_screen_unl
ock_landscape.xml:18: error: Error: No resource found that matches the given nam
e (at 'layout' with value '@layout/keyguard_transport_control').

C:\Users\Riccardo\Desktop\origi (1)\framework-res\res\layout\keyguard_screen_unl
ock_portrait.xml:23: error: Error: No resource found that matches the given name
 (at 'layout' with value '@layout/keyguard_transport_control').

Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.Androl
ibException: brut.common.BrutException: could not exec command: [C:\Users\Riccar
do\AppData\Local\Temp\brut_util_Jar_4314225215935308861.tmp, p, --forced-package
-id, 1, --min-sdk-version, 17, --target-sdk-version, 17, --version-code, 17, --v
ersion-name, 4.2.2-G350XXU0ANG4, -F, C:\Users\Riccardo\AppData\Local\Temp\APKTOO
L3727008907599784997.tmp, -x, -0, arsc, -S, C:\Users\Riccardo\Desktop\origi (1)\
framework-res\res, -M, C:\Users\Riccardo\Desktop\origi (1)\framework-res\Android
Manifest.xml]
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:442)
        at brut.androlib.Androlib.buildResources(Androlib.java:379)
        at brut.androlib.Androlib.build(Androlib.java:282)
        at brut.androlib.Androlib.build(Androlib.java:255)
        at brut.apktool.Main.cmdBuild(Main.java:225)
        at brut.apktool.Main.main(Main.java:84)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not
 exec command: [C:\Users\Riccardo\AppData\Local\Temp\brut_util_Jar_4314225215935
308861.tmp, p, --forced-package-id, 1, --min-sdk-version, 17, --target-sdk-versi
on, 17, --version-code, 17, --version-name, 4.2.2-G350XXU0ANG4, -F, C:\Users\Ric
cardo\AppData\Local\Temp\APKTOOL3727008907599784997.tmp, -x, -0, arsc, -S, C:\Us
ers\Riccardo\Desktop\origi (1)\framework-res\res, -M, C:\Users\Riccardo\Desktop\
origi (1)\framework-res\AndroidManifest.xml]
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.jav
a:504)
        at brut.androlib.Androlib.buildResourcesFull(Androlib.java:428)
        ... 5 more
Caused by: brut.common.BrutException: could not exec command: [C:\Users\Riccardo
\AppData\Local\Temp\brut_util_Jar_4314225215935308861.tmp, p, --forced-package-i
d, 1, --min-sdk-version, 17, --target-sdk-version, 17, --version-code, 17, --ver
sion-name, 4.2.2-G350XXU0ANG4, -F, C:\Users\Riccardo\AppData\Local\Temp\APKTOOL3
727008907599784997.tmp, -x, -0, arsc, -S, C:\Users\Riccardo\Desktop\origi (1)\fr
amework-res\res, -M, C:\Users\Riccardo\Desktop\origi (1)\framework-res\AndroidMa
nifest.xml]
        at brut.util.OS.exec(OS.java:89)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.jav
a:498)
        ... 6 more

C:\Users\Riccardo\Desktop\origi (1)>
```

**Comment by iBotPeaches** [comment]
Can you upload the apk? and all the frameworks? Want to do some investigation.

**Comment by spektro10** [comment]
https://drive.google.com/file/d/0BwnjE_5wgnVMcUxaX3BjQzl4OFE/view?usp=sharing

**Comment by iBotPeaches** [comment]
Combined with some broken resources & restrictive aapt, this application won't rebuild cleanly.

As you can see, it is looking for `@layout/keyguard_transport_control`

If we `grep` for that resource, we get this.

```
ibotpeaches@raganok:~/Downloads/Apktool/Bug976$ grep -r -i 'keyguard_transport_control' *
framework-res/res/values/ids.xml:    <item type="id" name="keyguard_transport_control">false</item>
framework-res/res/values/public.xml:    <public type="id" name="keyguard_transport_control" id="0x010203c7" />
framework-res/res/values/public.xml:    <public type="layout" name="keyguard_transport_control_view" id="0x0109009e" />
framework-res/original/META-INF/MANIFEST.MF:Name: res/layout/keyguard_transport_control_view.xml
framework-res/original/META-INF/CERT.SF:Name: res/layout/keyguard_transport_control_view.xml
```

The layout is actually called `keyguard_transport_control_view`. So switch out the naming for the correct resource and you get.

```
ibotpeaches@raganok:~/Downloads/Apktool/Bug976$ apktool b framework-res
I: Using Apktool 2.0.1
W: Could not find sources
I: Checking whether resources has changed...
I: Building resources...
warning: string 'default_audio_route_name_hdmi' has no default translation.
warning: string 'default_permission_group' has no default translation.
warning: string 'lockscreen_unlock_guide_text_multi_user' has no default translation.
warning: string 'perms_hide' has no default translation.
warning: string 'perms_show_all' has no default translation.
warning: string 's_view_cover_shortcuts_camera_text' has no default translation.
warning: string 's_view_cover_shortcuts_music_player_text' has no default translation.
warning: string 's_view_cover_shortcuts_quick_memo_text' has no default translation.
warning: string 'tommorrow' has no default translation.
I: Building apk file...
ibotpeaches@raganok:~/Downloads/Apktool/Bug976$ 
```

A working apk :)
