### ISSUE TITLE
Could not decode arsc file

### ISSUE THREAD

**Issue by PaulSD** [iBotPeaches/Apktool#977]
Decoding framework-res.apk from Android 5.1 on a stock Moto E 2015 phone:
```
$ ./apktool d framework-res.apk 
I: Using Apktool 2.0.0 on framework-res.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:52)
        at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:538)
        at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:63)
        at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:55)
        at brut.androlib.Androlib.getResTable(Androlib.java:64)
        at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:209)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:92)
        at brut.apktool.Main.cmdDecode(Main.java:165)
        at brut.apktool.Main.main(Main.java:81)
Caused by: java.io.IOException: Expected: 0x00000008, got: 0x00000001
        at brut.util.ExtDataInput.skipCheckShort(ExtDataInput.java:56)
        at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:238)
        at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:201)
        at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:189)
        at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:157)
        at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:114)
        at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:78)
        at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
        ... 8 more
```

A copy of the apk can be found here: https://drive.google.com/file/d/0Bzn39se_cwdTREJMX3g4OTduRGM/view?usp=sharing

Before updating to Android 5.1, I was previously able to decode the stock Android 5.0 framework-res.apk from this same phone.

Thanks!

**Comment by iBotPeaches** [comment]
Duplicate #924.

Fixed in 2.0.1. Which will be out in under 2 weeks.
