### ISSUE TITLE
Error 'Exception in thread "main" brut.androlib.AndrolibException: Multiple resources'

### ISSUE THREAD

**Issue by porelli** [iBotPeaches/Apktool#978]
What steps will reproduce the problem?
apktool if framework-res.apk
(Honor6 framework-res.apk -> https://mega.nz/#!eQl2VSYL!YxcfdcpdARNiQtF4ohi-SQS07rl4jLvPDBFfg3BJWiU)

What is the expected output?
Framework installed.

What do you see instead?
$ java -jar apktool.jar if framework-res.apk
Exception in thread "main" brut.androlib.AndrolibException: Multiple resources: spec=0x01040308 string/lockscreen_carrier_default, config=[DEFAULT]
	at brut.androlib.res.data.ResConfig.addResource(ResConfig.java:63)
	at brut.androlib.res.data.ResConfig.addResource(ResConfig.java:56)
	at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:218)
	at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:189)
	at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:157)
	at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:114)
	at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:78)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:39)
	at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:593)
	at brut.androlib.res.AndrolibResources.installFramework(AndrolibResources.java:575)
	at brut.androlib.Androlib.installFramework(Androlib.java:660)
	at brut.apktool.Main.cmdInstallFramework(Main.java:240)
	at brut.apktool.Main.main(Main.java:87)

What version of the product are you using? On what operating system?
apktool_2.0.0 on Debian 8.1

Please provide any additional information below.
$ java -version
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-1~deb8u1)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)

**Comment by iBotPeaches** [comment]
Sorry but Huawei isn't supported. See #966.
