### ISSUE TITLE
Exception in thread "main" brut.androlib.err.UndefinedResObject

### ISSUE THREAD

**Issue by JenyaKirmiza** [iBotPeaches/Apktool#980]
I used apktool 2-0 latest version from the website
I use Ubuntu 12-04

**Comment by raziel23x** [comment]
catlog or error log from decompiling and recompiling,,,,,

**Comment by iBotPeaches** [comment]
I need a lot more information than this. A logcat, apk or something. Until then, I will keep this closed.

**Comment by raziel23x** [comment]
and also upload a example apk file

**Comment by JenyaKirmiza** [comment]
I: Using Apktool 2.0.0 on fakegps.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /root/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
W: Could not decode attr value, using undecoded value instead: ns=android, name=touchscreenBlocksFocus, value=0xffffffff
I: Decoding values */* XMLs...
Exception in thread "main" brut.androlib.err.UndefinedResObject: resource spec: 0x0101048f
	at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:65)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:61)
	at brut.androlib.res.decoder.ResAttrDecoder.decode(ResAttrDecoder.java:36)
	at brut.androlib.res.decoder.AXmlResourceParser.getAttributeValue(AXmlResourceParser.java:369)
	at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValue(XmlPullParserDelegate.java:69)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
	at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:83)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:141)
	at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(ResStreamDecoderContainer.java:33)
	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:114)
	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:99)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:247)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:134)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:104)
	at brut.apktool.Main.cmdDecode(Main.java:165)
	at brut.apktool.Main.main(Main.java:81)

**Comment by JenyaKirmiza** [comment]
https://www.dropbox.com/s/tjx23ulhtc8vs73/com.fakegps.mock-3.22-APK4Fun.com.apk?dl=0
apk file

**Comment by JenyaKirmiza** [comment]
first i aded sudo apktool if framework-res.apk
it was added normally
I: Framework installed to: /root/apktool/framework/1.apk
then i tried 
sudo  apktool d -f fakegps.apk
and got that exception.

**Comment by iBotPeaches** [comment]
Update your frameworks. This isn't a bug. Delete the file at `$HOME/apktool/framework/1.apk` and let Apktool re-create it.

**Comment by JenyaKirmiza** [comment]
to recreate if i need to use sudo apktool if framework-res.apk?

**Comment by JenyaKirmiza** [comment]
Ok. i rebuilt it. And got new 1.apk file, but got the same exception

**Comment by JenyaKirmiza** [comment]
Can you check if this apk is really decompilable? or maybe i have wrong framework file

**Comment by iBotPeaches** [comment]
I told you exactly what to do. This error

```
W: Could not decode attr value, using undecoded value instead: ns=android, name=touchscreenBlocksFocus, value=0xffffffff
```

Means you have an outdated framework. Nothing else.

To ease your concerns, here is proof.

```
ibotpeaches@raganok:~/Downloads/Apktool/Bug980$ apktool d com.fakegps.mock-3.22-APK4Fun.com.apk 
I: Using Apktool 2.0.0 on com.fakegps.mock-3.22-APK4Fun.com.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
ibotpeaches@raganok:~/Downloads/Apktool/Bug980$ 
```

**Comment by JenyaKirmiza** [comment]
Can you give me the right framework?

**Comment by iBotPeaches** [comment]
Please read what I'm saying. It is internal in Apktool. Read what I said above or here: http://ibotpeaches.github.io/Apktool/documentation/#frameworks
