### ISSUE TITLE
NullPointerException in when writing attribute

### ISSUE THREAD

**Issue by cryptax** [iBotPeaches/Apktool#982]
I am unable to decompile this application:

    java -jar ~/softs/apktool/apktool.jar d --force --output ./welcome Welcome.apk
    I: Using Apktool 2.0.0 on Welcome.apk
    I: Loading resource table...
    I: Decoding AndroidManifest.xml with resources...
    I: Loading resource table from file: /home/axelle/apktool/framework/1.apk
    I: Regular manifest package...
    I: Decoding file-resources...
    W: Could not decode attr value, using undecoded value instead: ns=android, name=interpolator,   value=0x010c0003
    W: Could not decode attr value, using undecoded value instead: ns=android, name=textAllCaps, value=0xffffffff
    W: Could not decode attr value, using undecoded value instead: ns=android, name=ordering, value=0x00000000
    W: Could not decode attr value, using undecoded value instead: ns=android, name=fontFamily, value=0x00000015
     Exception in thread "main" java.lang.NullPointerException
        at java.io.Writer.write(Writer.java:157)
        at brut.androlib.res.util.ExtMXSerializer.writeAttributeValue(ExtMXSerializer.java:38)
        at org.xmlpull.mxp1_serializer.MXSerializer.attribute(MXSerializer.java:673)
        at org.xmlpull.v1.wrapper.classic.XmlSerializerDelegate.attribute(XmlSerializerDelegate.java:106)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
        at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
        at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:83)
        at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:141)
        at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(ResStreamDecoderContainer.java:33)
        at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:114)
        at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:99)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:247)
       at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:134)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:104)
        at brut.apktool.Main.cmdDecode(Main.java:165)
        at brut.apktool.Main.main(Main.java:81)

I am using Linux Mint 17.1, with apktool 2.0.0. My java version is 1.8.0_40.

**Comment by iBotPeaches** [comment]
This error `W: Could not decode attr value, using undecoded value instead: ns=android, name=textAllCaps, value=0xffffffff` makes me think your frameworks are out of date.

This one `W: Could not decode attr value, using undecoded value instead: ns=android, name=interpolator,   value=0x010c0003` I believe is fixed in `2.0.1` which is not yet released. Do you have an apk so I can confirm?

**Comment by cryptax** [comment]
Hi Connor,

>makes me think your frameworks are out of date.

What do you mean by framework? The Android SDK tools? No, they're up to
date (24.3.3), so are the platform tools and build tools.

>Do you have an apk so I can confirm?

Yes, I do, unfortunately I can't send it on this email: the email bounced
for over size limit.
So, I've uploaded it here:
http://www.mediafire.com/download/awm7gr9iazidcxi/Welcome.apk

Cheers
Axelle

**Comment by iBotPeaches** [comment]
```
ibotpeaches@raganok:~/Downloads/Apktool/Bug982$ apktool d Welcome.apk 
I: Using Apktool 2.0.1 on Welcome.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
ibotpeaches@raganok:~/Downloads/Apktool/Bug982$ 
```

No issue here. The framework I mean is at `$HOME/apktool/framework/1.apk`. I'd recommend reading over the docs here: http://ibotpeaches.github.io/Apktool/documentation/#framework-files

**Comment by cryptax** [comment]
You are right indeed, my error: I installed the right framework apk and it
worked straight away.
Sorry!
Axelle

**Comment by Ankh9** [comment]
Hello. I wanted to change settings.apk, but I  from this error:

C:\Users\SimoBaro\Desktop\apktool-install-windows>java -jar apktool.jar d -s Set
tings.apk
I: Using Apktool 2.2.0 on Settingsori.apk
I: Loading resource table...
I: Decoding Shared Library (com.mediatek), pkgId: 8
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\SimoBaro\AppData\Local\apktool\fra
mework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
Exception in thread "main" java.lang.NullPointerException
        at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(Re
sStyleValue.java:58)
        at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResour
ces.java:516)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:267
)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:131)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:108)
        at brut.apktool.Main.cmdDecode(Main.java:163)
        at brut.apktool.Main.main(Main.java:81)

you can help me, thanks!!!

**Comment by huopochuan** [comment]
[apktool_2.2.0.jar](https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.2.0.jar)
I use the new apktool, and it works

**Comment by Ankh9** [comment]
@huopochuan 
I used apktool 2.2.0.... 
works with all other systemapp, but not with settings.apk

**Comment by wanwjing** [comment]
![image](https://user-images.githubusercontent.com/16173626/33698346-d74e01fa-db46-11e7-8e66-e96312b55797.png)
I was try out many version of the apktool still cant. May i know what happen with this? Thank for reply.
