### ISSUE TITLE
brut.androlib.err.UndefinedResObject: resource spec: 0x01010462

### ISSUE THREAD

**Issue by srasthofer** [iBotPeaches/Apktool#988]
It is not possible to decode the following apk:
https://dl.dropboxusercontent.com/u/18007092/SENDSECRET.apk

Setup:
- using latest release

Exception:
W: Could not decode attr value, using undecoded value instead: ns=, name=, value=0xffffffff
I: Decoding values */* XMLs...
Exception in thread "main" brut.androlib.err.UndefinedResObject: resource spec: 0x01010462
	at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:65)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:61)
	at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferenceValue.java:57)
	at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:54)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:496)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:252)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:134)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:104)
	at brut.apktool.Main.cmdDecode(Main.java:165)
	at brut.apktool.Main.main(Main.java:81)

Thank you in advance!

**Comment by iBotPeaches** [comment]
```
ibotpeaches@raganok:~/Downloads/Apktool/Bug988$ apktool d SENDSECRET.apk 
I: Using Apktool 2.0.1 on SENDSECRET.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
ibotpeaches@raganok:~/Downloads/Apktool/Bug988$ 
```

This warning you have `W: Could not decode attr value, using undecoded value instead: ns=, name=, value=0xffffffff` means your framework files are out of date.

Delete the file at `$HOME/apktool/framework/1.apk` and try again. Give this is a read: http://ibotpeaches.github.io/Apktool/documentation/#framework-files

**Comment by q1q1w1w1q** [comment]
**Delete the file at $HOME/apktool/framework/1.apk and try again.**

It works, thanks!

**Comment by nmr8acme** [comment]
Note that if you installed with brew the file is in a slightly different path, `~/Library/apktool/framework/1.apk`

**Comment by Alberne** [comment]
I use apktool to Decoding my apk, the error message :

`I: Using Apktool 2.0.1 on AndUC-debug.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: C:\Users\Administrator\apktool\framework\1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
Exception in thread "main" brut.androlib.err.UndefinedResObject: resource spec: 0x010104e2
        at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
        at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:65)
        at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:61)
        at brut.androlib.res.data.value.ResReferenceValue.getReferent(ResReferenceValue.java:57)
        at brut.androlib.res.data.value.ResReferenceValue.encodeAsResXml(ResReferenceValue.java:47)
        at brut.androlib.res.data.value.ResScalarValue.encodeAsResXmlValue(ResScalarValue.java:58)
        at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:71)
        at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:496)
        at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:252)
        at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:134)
        at brut.androlib.ApkDecoder.decode(ApkDecoder.java:104)
        at brut.apktool.Main.cmdDecode(Main.java:165)
        at brut.apktool.Main.main(Main.java:81)`

when I update apktool to 2.2.1 version , that okay
