### ISSUE TITLE
Breaks on decoding TTS v3.5.5

### ISSUE THREAD

**Issue by CodyToombs** [iBotPeaches/Apktool#992]
**Steps to reproduce**
To reproduce, just attempt to decode TTS v3.5.5. The crash occurs almost immediately.

**The APK is available at:** http://www.apkmirror.com/apk/google-inc/google-text-to-speech-engine/google-text-speech-engine-3-5-5-2050975-arm-neon-android-apk-download/

**Version & OS:**
ApkTool 2.0.0 on OS X 10.7

**Error**
```
I: Using Apktool 2.0.0 on com.google.android.tts-3.5.5.2050975.arm.neon-210305053-minAPI19.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:52)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:538)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:63)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:55)
	at brut.androlib.Androlib.getResTable(Androlib.java:64)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:209)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:92)
	at brut.apktool.Main.cmdDecode(Main.java:165)
	at brut.apktool.Main.main(Main.java:81)
Caused by: java.io.IOException: Expected: 0x00000008, got: 0x00000004
	at brut.util.ExtDataInput.skipCheckShort(ExtDataInput.java:56)
	at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:238)
	at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:201)
	at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:189)
	at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:157)
	at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:114)
	at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:78)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
```

**Comment by iBotPeaches** [comment]
```
ibotpeaches@raganok:~/Downloads/Apktool/Bug992$ apktool d com.google.android.tts-3.5.5.2050975.arm.neon-210305053-minAPI19.apk 
I: Using Apktool 2.0.1 on com.google.android.tts-3.5.5.2050975.arm.neon-210305053-minAPI19.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
ibotpeaches@raganok:~/Downloads/Apktool/Bug992$ 
```

This bug was fixed in : https://github.com/iBotPeaches/Apktool/commit/6ee029dd30808a05f842c46672261a27dbb107da or #924. Will be in next public release (2.0.1)
