### ISSUE TITLE
Can not decode Settings.apk of flyme

### ISSUE THREAD

**Issue by duanqz** [iBotPeaches/Apktool#994]
Settings.apk: https://github.com/duanqz/holder/blob/master/Settings.apk
framework-res.apk : https://github.com/duanqz/holder/blob/master/framework-res.apk
flyme-res.apk : https://github.com/duanqz/holder/blob/master/flyme-res.apk

After installed the framework apks, I have confronted with the following errors when decoding settings.apk: 

```
I: Using Apktool 2.0.1-e407fe-SNAPSHOT on Settings.apk
....
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/ic_flag_dbls.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/ic_flag_singapore.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/ic_flag_bahamas.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/earpod_adjust_tips_img.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/ic_flag_sierra_leone.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/mz_ic_list_doc_big.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/mz_ic_list_txt_small.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/ic_flag_czech_republic.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/ic_flag_luxembourg.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/mz_ic_list_html_big.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/mz_stat_notify_email_fail.png
Exception in thread "main" java.lang.ClassCastException: brut.androlib.res.data.value.ResStyleValue cannot be cast to brut.androlib.res.data.value.ResAttr
    at brut.androlib.res.decoder.ResAttrDecoder.decode(ResAttrDecoder.java:36)
    at brut.androlib.res.decoder.AXmlResourceParser.getAttributeValue(AXmlResourceParser.java:369)
    at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValue(XmlPullParserDelegate.java:69)
    at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
    at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
    at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:83)
    at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:141)
    at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(ResStreamDecoderContainer.java:33)
    at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:114)
    at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:99)
    at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:247)
    at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:134)
    at brut.androlib.ApkDecoder.decode(ApkDecoder.java:104)
    at brut.apktool.Main.cmdDecode(Main.java:165)
    at brut.apktool.Main.main(Main.java:81)
```

**Comment by iBotPeaches** [comment]
```
➜  Bug994 apktool if framework-res.apk -t 994
I: Framework installed to: /home/ibotpeaches/.local/share/apktool/framework/1-994.apk
➜  Bug994 apktool if flyme-res.apk -t 994
I: Framework installed to: /home/ibotpeaches/.local/share/apktool/framework/2-994.apk
➜  Bug994 apktool d Settings.apk -t 994
I: Using Apktool 2.2.2-b60db0-SNAPSHOT on Settings.apk
I: Loading resource table...
I: Decoding Shared Library (flyme), pkgId: 2
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/ibotpeaches/.local/share/apktool/framework/1-994.apk
I: Regular manifest package...
I: Decoding file-resources...
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/mz_status_ic_pppoe.png
S: Could not decode file, replacing by FALSE value: drawable-xxhdpi-v4/ic_flag_wallis_and_futuna.png
...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
➜  Bug994 
```

Resolved with 2.2.2 - coming out soon. Sorry for delay.
