### ISSUE TITLE
No such file or directory - "/tmp/brut_util_Jar_3373852466288253568.tmp"

### ISSUE THREAD

**Issue by Lilleengen** [iBotPeaches/Apktool#997]
Trying to build a apk results in the following error:
```
I: Using Apktool 2.0.0
I: Checking whether sources has changed...
I: Checking whether resources has changed...
I: Building apk file...
Exception in thread "main" brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [/tmp/brut_util_Jar_3373852466288253568.tmp, p, -F, /home/ithenrik/apktools/no.dnb.vipps-11/dist/no.dnb.vipps-11.apk, -0, arsc, -A, /home/ithenrik/apktools/no.dnb.vipps-11/assets, /home/ithenrik/apktools/no.dnb.vipps-11/build/apk]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:419)
	at brut.androlib.Androlib.buildApk(Androlib.java:651)
	at brut.androlib.Androlib.build(Androlib.java:289)
	at brut.androlib.Androlib.build(Androlib.java:256)
	at brut.apktool.Main.cmdBuild(Main.java:225)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.common.BrutException: could not exec command: [/tmp/brut_util_Jar_3373852466288253568.tmp, p, -F, /home/ithenrik/apktools/no.dnb.vipps-11/dist/no.dnb.vipps-11.apk, -0, arsc, -A, /home/ithenrik/apktools/no.dnb.vipps-11/assets, /home/ithenrik/apktools/no.dnb.vipps-11/build/apk]
	at brut.util.OS.exec(OS.java:93)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:413)
	... 5 more
Caused by: java.io.IOException: Cannot run program "/tmp/brut_util_Jar_3373852466288253568.tmp": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:485)
	at brut.util.OS.exec(OS.java:84)
	... 6 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 9 more
```

**Comment by iBotPeaches** [comment]
It appears you cannot execute executables in `/tmp`. Prebuilt aapts can be found here: https://github.com/iBotPeaches/Apktool/tree/master/brut.apktool/apktool-lib/src/main/resources/prebuilt/aapt

Download the platform one for you (unix) and place somewhere then use parameter `-a` or `-aapt` and the location to that file.
